#!/usr/bin/env python3
"""Fresh source __invoke argument views, saved owners and CONFIG borrowing."""
import argument_introspection_protocol as arguments
import argument_introspection_current_protocol as current
import include_mutable_protocol as include

EXTRA = r'''
dec $union_saved_argref_sender(pstate, ptask*) : pstate?
def $union_saved_argref_sender(S, eps) = eps
def $union_saved_argref_sender(S, (ARGINFO_REF_CAPTURE pargref n poperand*) :: ptask_tail*) = (S[.TODO = (ARGINFO_REF_CAPTURE pargref n poperand*) :: ptask_tail*])
def $union_saved_argref_sender(S, ptask :: ptask_tail*) = $union_saved_argref_sender($call_after_origin(S, ptask), ptask_tail*)
  -- if ~$saved_argref_capture(ptask)
dec $union_config_frame(pframe) : bool
def $union_config_frame(pframe) = true
  -- if pframe.TODO = (STRINGIFY_RESULT n_object porigin_child z_call) :: (CONFIG_STRING_RESULT pconfigcall n_object porigin_child z_child z_call) :: ptask_tail*
def $union_config_frame(pframe) = false -- otherwise
dec $union_config_frame_index(pframe*, nat) : nat?
def $union_config_frame_index(eps, n) = eps
def $union_config_frame_index(pframe :: pframe_tail*, n) = (n)
  -- if $union_config_frame(pframe)
def $union_config_frame_index(pframe :: pframe_tail*, n) = $union_config_frame_index(pframe_tail*, $(n + 1))
  -- if ~$union_config_frame(pframe)
'''
PREFIX = arguments.SAVED + current.SENDER + EXTRA + include.PREFIX
FINISH = current.FINISH
GUARDS = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
          '$call_descriptors_valid(S)', '$closure_state_valid(S)',
          '$heap_valid($heap_graph(S))']

SOURCES = {
    'captured-inherited-live-argument': {
        "source": b'<?php function union_argpos13(&$a){echo "K";$a=9;return 0;}class UnionBase13{public function __invoke(&$a,$b=5){echo func_num_args(),":",func_get_arg(union_argpos13($a)),":",func_get_args()[0],";";}}class UnionChild13 extends UnionBase13{}$o=new UnionChild13;$f=$o(...);$o=new UnionChild13;$x=7;$f(...["a"=>&$x]);echo $x;',
        "expected_stdout": b'1:K9:9;9',
    },
    'source-invoke-delayed-tmp-reference': {
        # A forward callee defers reference demand to FETCH_DIM_FUNC_ARG.
        "source": b'<?php function union_key13(&$a){echo "K";$a=9;return 0;}class UnionTmp13{public function __invoke($a){try{union_take13(func_get_args()[union_key13($a)]);}catch(Error $e){echo "E";}echo ":",$a,":",func_num_args();}}function union_take13(&$x){echo "BAD";}(new UnionTmp13)(7);',
        "expected_stdout": b'KE:9:1',
    },
    'set-packs-nested-source-invoke': {
        "source": b'<?php declare(strict_types=1);class UnionInner13{public function __invoke($a){echo func_num_args(),func_get_arg(0),func_get_args()[0];return "union-path";}}class UnionString13{public function __toString():string{$i=new UnionInner13;return $i(7);}}$f=set_include_path(...);echo $f->__invoke(...["include_path"=>new UnionString13]);',
        "expected_stdout": b'177.:',
    },
}

CASES = [
    {
        "id": 'captured-saved-selector',
        "source_id": 'captured-inherited-live-argument',
        "stage": '$saved_arginfo_stage(S)',
        "checks": [
            'S.FRAMES = pframe :: pframe_tail*',
            '$saved_arginfo(pframe.TODO) = (pargcall)',
            'pargcall.KIND = INTRINSIC_FUNC_GET_ARG',
            'S.CURRENT = (pcallcontext)',
            'pcallcontext.NAME = $ptascii("union_argpos13")',
            'pcallcontext.INSTANCE = eps',
            'pcallcontext.RECEIVER = eps',
            'pcallcontext.ARGC = 1',
            'pframe.CONTEXT = (pcallcontext_saved)',
            'pcallcontext_saved.TARGET = CLOSURE_TARGET n_capture',
            'pcallcontext_saved.INSTANCE = (n_capture)',
            'pcallcontext_saved.RECEIVER = (n_receiver)',
            'pcallcontext_saved.ARGC = 1',
            'pcallcontext_saved.PARAMS = [$ptascii("a"), $ptascii("b")]',
            'S.OBJECTS[n_capture] = METHODCLOSURE porigin_method porigin_site porigin_called eps',
            '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
            '~pmethoddesc.STATIC',
            'pmethoddesc.VISIBILITY = PROPERTY_PUBLIC',
            '$class_at(S.CLASSES, pmethoddesc.OWNER) = (pclassdesc_owner)',
            'pclassdesc_owner.NAME = $ptascii("UnionBase13")',
            '$class_at(S.CLASSES, porigin_called) = (pclassdesc_called)',
            'pclassdesc_called.NAME = $ptascii("UnionChild13")',
            'pmethoddesc.OWNER =/= porigin_called',
            'pcallcontext_saved.LEXICAL_CLASS = (pmethoddesc.OWNER)',
            'pcallcontext_saved.CALLED_CLASS = (porigin_called)',
            '$closure_scope_at(S.CLOSURESCOPES, n_capture) = (pclosurescope)',
            'pclosurescope.RECEIVER = (n_receiver)',
            'pclosurescope.LEXICAL = pmethoddesc.OWNER',
            'pclosurescope.CALLED = porigin_called',
            'pclosurescope.CREATION = eps',
            '$closure_scope_row_valid(S, pclosurescope)',
            '$node_children(S, HOBJECT n_capture) = [HOBJECT n_receiver]',
            'S.GLOBALTABLE = (psymboltable_global)',
            '$lookup(psymboltable_global.ENV, $ptascii("o")) = (n_cell_o)',
            'S.STORE[n_cell_o] = DEFINED (POBJECT n_replacement)',
            'n_receiver =/= n_replacement',
            'S.OBJECTS[n_replacement] = INSTANCE porigin_called',
            'pframe.LOCALS = (psymboltable)',
            '$target_function(S, CLOSURE_TARGET n_capture) = (pfunction_saved)',
            'psymboltable.CVS = pfunction_saved.CVS',
            '$lookup(psymboltable.ENV, $ptascii("a")) = (n_cell_a)',
            '$lookup(psymboltable.ENV, $ptascii("b")) = (n_cell_b)',
            'S.STORE[n_cell_a] = DEFINED (PINT 7)',
            'S.STORE[n_cell_b] = DEFINED (PINT 5)',
            '$call_saved_context_valid(S, pframe)',
            'S_saved = S[.CURRENT = pframe.CONTEXT][.ORIGIN = pframe.ORIGIN][.TODO = pframe.TODO][.ENV = psymboltable.ENV][.CVS = psymboltable.CVS][.SYMBOLS = psymboltable.SYMBOLS]',
            '$arginfo_values(S_saved, pcallcontext_saved) = [PINT 7]',
            '$current_saved_arginfo_sender(S_saved, pframe.TODO) = (S_send)',
            'S_send.ORIGIN = (pargcall.SITE)',
            '$call_task_valid(S_send, ARGINFO_SEND pargcall)',
            '~$call_task_valid(S_send, ARGINFO_SEND pargcall[.LINE = 999])',
            '~$call_saved_context_valid(S, pframe[.CONTEXT = (pcallcontext_saved[.INSTANCE = (n_receiver)])])',
            '~$call_saved_context_valid(S, pframe[.CONTEXT = (pcallcontext_saved[.RECEIVER = (n_replacement)])])',
            '~$call_saved_context_valid(S, pframe[.CONTEXT = (pcallcontext_saved[.LEXICAL_CLASS = (porigin_called)])])',
            '~$call_saved_context_valid(S, pframe[.CONTEXT = (pcallcontext_saved[.CALLED_CLASS = (pmethoddesc.OWNER)])])',
            '~$call_saved_context_valid(S, pframe[.CONTEXT = (pcallcontext_saved[.ARGC = 999])])',
            '~$call_saved_context_valid(S, pframe[.LOCALS = (psymboltable[.CVS = eps])])',
            '~$call_descriptors_valid(S[.FRAMES = pframe[.CONTEXT = (pcallcontext_saved[.RECEIVER = (n_replacement)])] :: pframe_tail*])',
            *GUARDS,
            *FINISH,
            '$outputs(S_done.EVENTS) = $ptascii("1:K9:9;9")',
        ],
    },
    {
        "id": 'invoke-tmp-saved-key',
        "source_id": 'source-invoke-delayed-tmp-reference',
        "stage": '$saved_argref_stage(S)',
        "checks": [
            'S.FRAMES = pframe :: pframe_tail*',
            '$saved_argref(pframe.TODO) = (pargref)',
            'S.CURRENT = (pcallcontext)',
            'pcallcontext.NAME = $ptascii("union_key13")',
            'pcallcontext.INSTANCE = eps',
            'pcallcontext.RECEIVER = eps',
            'pcallcontext.ARGC = 1',
            'pframe.CONTEXT = (pcallcontext_saved)',
            'pcallcontext_saved.TARGET = METHOD_TARGET n_receiver porigin_method',
            'pcallcontext_saved.INSTANCE = eps',
            'pcallcontext_saved.RECEIVER = (n_receiver)',
            'pcallcontext_saved.ARGC = 1',
            'pcallcontext_saved.PARAMS = [$ptascii("a")]',
            '$object_invoke_method(S, n_receiver) = (pmethoddesc)',
            'pmethoddesc.FUNCTION.ORIGIN = porigin_method',
            '$target_function(S, METHOD_TARGET n_receiver porigin_method) = (pfunction_saved)',
            'pframe.LOCALS = (psymboltable)',
            'psymboltable.CVS = pfunction_saved.CVS',
            '$lookup(psymboltable.ENV, $ptascii("a")) = (n_cell_a)',
            'S.STORE[n_cell_a] = DEFINED (PINT 7)',
            '$saved_argref_prefix(pframe.TODO) = [KNOWN (PARRAY n_array)]',
            'S.ARRAYS[n_array].ITEMS = [ENTRY (KINT 0) (DIRECT (PINT 7))]',
            '$heap_owners($heap_graph(S), HARRAY n_array) = 1',
            '$call_saved_context_valid(S, pframe)',
            'S_saved = S[.CURRENT = pframe.CONTEXT][.ORIGIN = pframe.ORIGIN][.TODO = pframe.TODO][.ENV = psymboltable.ENV][.CVS = psymboltable.CVS][.SYMBOLS = psymboltable.SYMBOLS]',
            '$union_saved_argref_sender(S_saved, pframe.TODO) = (S_ref)',
            'S_ref.ORIGIN = (pargref.ARGUMENT)',
            'S_ref.TODO = (ARGINFO_REF_CAPTURE pargref 1 ([KNOWN (PARRAY n_array)])) :: ptask_ref*',
            '$call_task_valid(S_ref, ARGINFO_REF_CAPTURE pargref 1 ([KNOWN (PARRAY n_array)]))',
            '$task_nodes(ARGINFO_REF_CAPTURE pargref 1 ([KNOWN (PARRAY n_array)])) = [HARRAY n_array]',
            '~$call_task_valid(S_ref, ARGINFO_REF_CAPTURE pargref[.LINE = 999] 1 ([KNOWN (PARRAY n_array)]))',
            '~$call_saved_context_valid(S, pframe[.CONTEXT = (pcallcontext_saved[.INSTANCE = (n_receiver)])])',
            '~$call_saved_context_valid(S, pframe[.CONTEXT = (pcallcontext_saved[.RECEIVER = eps])])',
            '~$call_saved_context_valid(S, pframe[.CONTEXT = (pcallcontext_saved[.ARGC = 999])])',
            '~$call_saved_context_valid(S, pframe[.LOCALS = (psymboltable[.CVS = eps])])',
            '~$call_descriptors_valid(S[.FRAMES = pframe[.CONTEXT = (pcallcontext_saved[.INSTANCE = (n_receiver)])] :: pframe_tail*])',
            *GUARDS,
            *FINISH,
            '$outputs(S_done.EVENTS) = $ptascii("KE:9:1")',
        ],
    },
    {
        "id": 'invoke-tmp-reference-error',
        "source_id": 'source-invoke-delayed-tmp-reference',
        "stage": 'S.TODO = (ARGINFO_REF_ERROR pargref poperand*) :: ptask*',
        "checks": [
            'S.TODO = (ARGINFO_REF_ERROR pargref poperand*) :: ptask*',
            '$call_task_valid(S, ARGINFO_REF_ERROR pargref poperand*)',
            '$arginfo_result_valid(S)',
            'S.CURRENT = (pcallcontext)',
            'pcallcontext.TARGET = METHOD_TARGET n_receiver porigin_method',
            'pcallcontext.INSTANCE = eps',
            'pcallcontext.RECEIVER = (n_receiver)',
            'pcallcontext.ARGC = 1',
            'pcallcontext.PARAMS = [$ptascii("a")]',
            '$object_invoke_method(S, n_receiver) = (pmethoddesc)',
            'pmethoddesc.FUNCTION.ORIGIN = porigin_method',
            '$target_function(S, METHOD_TARGET n_receiver porigin_method) = (pfunction)',
            'S.CVS = pfunction.CVS',
            'poperand* = [KNOWN (PARRAY n_array), KNOWN (PINT 0)]',
            'S.ARRAYS[n_array].ITEMS = [ENTRY (KINT 0) (DIRECT (PINT 7))]',
            '$lookup(S.ENV, $ptascii("a")) = (n_cell_a)',
            'S.STORE[n_cell_a] = DEFINED (PINT 9)',
            '$arginfo_values(S, pcallcontext) = [PINT 9]',
            '$heap_owners($heap_graph(S), HARRAY n_array) = 1',
            '$task_nodes(ARGINFO_REF_ERROR pargref poperand*) = [HARRAY n_array]',
            '$outputs(S.EVENTS) = $ptascii("K")',
            '~$call_task_valid(S, ARGINFO_REF_ERROR pargref[.LINE = 999] poperand*)',
            '~$call_task_valid(S, ARGINFO_REF_ERROR pargref[.POSITION = 999] poperand*)',
            '~$call_task_valid(S, ARGINFO_REF_ERROR pargref eps)',
            '~$arginfo_result_valid(S[.TODO = (ARGINFO_REF_ERROR pargref ([KNOWN PNULL, KNOWN (PINT 0)])) :: ptask*])',
            '~$call_current_valid(S[.CURRENT = (pcallcontext[.INSTANCE = (n_receiver)])])',
            '~$call_current_valid(S[.CURRENT = (pcallcontext[.RECEIVER = eps])])',
            '~$call_current_valid(S[.CVS = eps])',
            *GUARDS,
            *FINISH,
            '$outputs(S_done.EVENTS) = $ptascii("KE:9:1")',
        ],
    },
    {
        "id": 'set-packs-nested-arginfo',
        "source_id": 'set-packs-nested-source-invoke',
        "stage": 'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask* -- if pargcall.KIND = INTRINSIC_FUNC_NUM_ARGS',
        "checks": [
            'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask*',
            'pargcall.KIND = INTRINSIC_FUNC_NUM_ARGS',
            '$call_task_valid(S, ARGINFO_INVOKE pargcall)',
            'S.CURRENT = (pcallcontext)',
            'pcallcontext.TARGET = METHOD_TARGET n_receiver porigin_method',
            'pcallcontext.INSTANCE = eps',
            'pcallcontext.RECEIVER = (n_receiver)',
            'pcallcontext.ARGC = 1',
            'pcallcontext.PARAMS = [$ptascii("a")]',
            '$arginfo_values(S, pcallcontext) = [PINT 7]',
            '$object_invoke_method(S, n_receiver) = (pmethoddesc)',
            'pmethoddesc.FUNCTION.ORIGIN = porigin_method',
            '$target_function(S, METHOD_TARGET n_receiver porigin_method) = (pfunction)',
            'S.CVS = pfunction.CVS',
            '$union_config_frame_index(S.FRAMES, 0) = (n_config)',
            '$(n_config > 0)',
            'pframe_config = S.FRAMES[n_config]',
            'pframe_config.TODO = (STRINGIFY_RESULT n_object porigin_child z_call) :: (CONFIG_STRING_RESULT pconfigcall n_object porigin_child z_child z_call) :: ptask_tail*',
            'pframe_prefix* = S.FRAMES[0:n_config]',
            'n_config_next = $(n_config + 1)',
            'n_config_rest = $nabs($(|S.FRAMES| - n_config - 1))',
            'pframe_suffix* = S.FRAMES[n_config_next:n_config_rest]',
            'S.FRAMES = pframe_prefix* ++ [pframe_config] ++ pframe_suffix*',
            'pframe_string = S.FRAMES[$nabs($(n_config - 1))]',
            'pframe_string.CONTEXT = (pcallcontext_string)',
            'pcallcontext_string.TARGET = METHOD_TARGET n_object porigin_string',
            'pcallcontext_string.INSTANCE = eps',
            'pcallcontext_string.RECEIVER = (n_object)',
            'pcallcontext_string.ARGC = 0',
            'pframe_string.LOCALS = (psymboltable_string)',
            '$target_function(S, METHOD_TARGET n_object porigin_string) = (pfunction_string)',
            'psymboltable_string.CVS = pfunction_string.CVS',
            'S_string = S[.CURRENT = pframe_string.CONTEXT][.ORIGIN = pframe_string.ORIGIN][.TODO = pframe_string.TODO][.ENV = psymboltable_string.ENV][.CVS = psymboltable_string.CVS][.SYMBOLS = psymboltable_string.SYMBOLS][.FRAMES = pframe_config :: pframe_suffix*]',
            '$stringify_entered(S, S.CURRENT, S.FRAMES, METHOD_TARGET n_object porigin_string, porigin_child)',
            '$config_string_trace_context(S_string, pcallcontext_string)',
            'pconfigcall.KIND = INTRINSIC_SET_INCLUDE_PATH',
            'pconfigcall.NAMED',
            'pconfigcall.OWNER = (n_owner)',
            'pconfigcall.SELECTION = eps',
            'pconfigcall.SENT = [NAMED_SENT (KNOWN (POBJECT n_object))]',
            'pconfigcall.PACKS = [pconfigpack]',
            'pconfigpack.ITEMS = [ENTRY (KSTRING $ptascii("include_path")) (DIRECT (POBJECT n_object))]',
            'S.OBJECTS[n_owner] = INTRINSICCLOSURE INTRINSIC_SET_INCLUDE_PATH',
            '$config_string_site_valid(S_string, pconfigcall, n_object, porigin_child, z_child, z_call)',
            '$config_nodes(pconfigcall) = [HOBJECT n_owner, HOBJECT n_object]',
            '$task_nodes(CONFIG_STRING_RESULT pconfigcall n_object porigin_child z_child z_call) = [HOBJECT n_object, HOBJECT n_owner, HOBJECT n_object]',
            '~((HARRAY pconfigpack.ARRAY) <- $config_nodes(pconfigcall))',
            'S.CODE = [pcode]',
            'pcode.STRICT',
            '~$config_strict(S_string, pconfigcall)',
            '~$config_string_site_valid(S_string, pconfigcall[.PACKS = eps], n_object, porigin_child, z_child, z_call)',
            '~$config_string_site_valid(S_string, pconfigcall[.PACKS = [pconfigpack[.INDEX = 999]]], n_object, porigin_child, z_child, z_call)',
            'pframe_bad = pframe_config[.TODO = (STRINGIFY_RESULT n_object porigin_child z_call) :: (CONFIG_STRING_RESULT pconfigcall[.PACKS = eps] n_object porigin_child z_child z_call) :: ptask_tail*]',
            '~$call_descriptors_valid(S[.FRAMES = pframe_prefix* ++ [pframe_bad] ++ pframe_suffix*])',
            'pframe_bad_owner = pframe_config[.TODO = (STRINGIFY_RESULT n_object porigin_child z_call) :: (CONFIG_STRING_RESULT pconfigcall[.OWNER = (n_receiver)] n_object porigin_child z_child z_call) :: ptask_tail*]',
            '~$call_descriptors_valid(S[.FRAMES = pframe_prefix* ++ [pframe_bad_owner] ++ pframe_suffix*])',
            '~$call_current_valid(S[.CURRENT = (pcallcontext[.INSTANCE = (n_receiver)])])',
            '~$call_current_valid(S[.CURRENT = (pcallcontext[.RECEIVER = eps])])',
            *GUARDS,
            *FINISH,
            'S_done.FILEINCLUDEPATH = ($ptascii("union-path"))',
            '$outputs(S_done.EVENTS) = $ptascii("177.:")',
        ],
    },
]
