"""Source-backed access result, class notice and captured truth continuations."""
from error_handler_protocol import PREFIX


def guards(s='S'):
    return [f'$call_current_valid({s})', f'$call_frames_valid({s}, {s}.FRAMES)',
            f'$call_descriptors_valid({s})', f'$heap_valid($heap_graph({s}))']


FINISH = ['S_done.COMPLETION = NORMAL', 'S_done.TODO = eps',
          'S_done.CURRENT = eps', 'S_done.FRAMES = eps', 'S_done.HELD = eps',
          'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
          *guards('S_done')]


CASES = [
    ('append-return-keeps-authentic-constant-rhs-pointer',
     'direct-append-and-array-offset-set-preserve-assignment-value',
     'S.TODO = (ACCESS_RESULT paccess) :: ptask_tail* -- if paccess.MODE = ACCESS_SET -- if paccess.RHS = KNOWN (PINT 13)', [
        'S.TODO = (ACCESS_RESULT paccess) :: ptask_tail*',
        'paccess.MODE = ACCESS_SET', 'paccess.PHASE = ACCESS_CALL $ptascii("offsetSet")',
        'paccess.LINE = 11', 'paccess.KEYLINE = 11',
        'paccess.INPUT = KNOWN PNULL', 'paccess.OFFSET = PNULL',
        'paccess.RHS = KNOWN (PINT 13)', 'paccess.SELECTED = KNOWN (PINT 13)',
        'paccess.VALUE = PINT 13', 'paccess.OUTER', '~paccess.LATCH',
        'paccess.BASE = BASE_VALUE (VARIABLE $ptascii("o284") 11)',
        'paccess.TASK = ASSIGN_ARRAY (BASE_APPEND paccess.BASE z_base) 11 false',
        'paccess.OBJECT = (n_object)',
        '$lookup(S.ENV, $ptascii("o284")) = (n_cv)',
        'S.STORE[n_cv] = DEFINED (POBJECT n_object)',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_object) = 3',
        '$task_nodes(ACCESS_RESULT paccess) = [HOBJECT n_object, HOBJECT n_object]',
        '$outputs(S.EVENTS) = $ptascii("S:1:13;")', '$access_valid(S, paccess)',
        '~$access_valid(S, paccess[.SELECTED = KNOWN (PINT 17)])',
        '~$access_valid(S, paccess[.VALUE = PINT 17])',
        '~$access_valid(S, paccess[.RHS = KNOWN (PINT 17)][.SELECTED = KNOWN (PINT 17)][.VALUE = PINT 17])',
        '~$access_valid(S, paccess[.INPUT = KNOWN (PINT 1)][.OFFSET = PINT 1])',
        '~$access_valid(S, paccess[.OBJECT = eps])',
        '~$access_valid(S, paccess[.OUTER = false])',
        '~$access_valid(S, paccess[.MODE = ACCESS_UNSET])',
        '~$access_valid(S, paccess[.PHASE = ACCESS_CALL $ptascii("offsetGet")])',
        '~$access_valid(S, paccess[.LINE = 12])',
        '~$access_valid(S, paccess[.TARGET = paccess.SITE])',
        '$origin_node(S.SOURCES, paccess.SITE) = (pcnode)',
        '~$access_context_node(pcnode, $ptascii("__tostring"))',
        *guards(), 'PhpStep: S ~> S_result',
        'S_result.TODO = ptask_tail*', 'S_result.RESULT = KNOWN (PINT 13)',
        'S_result.STORE = S.STORE', 'S_result.EVENTS = S.EVENTS',
        '$heap_owners($heap_prune($heap_graph(S_result)), HOBJECT n_object) = 1',
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.TODO = S_result.TODO', 'S_budget.RESULT = S_result.RESULT',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("x284")) = (n_x)',
        'S_done.STORE[n_x] = DEFINED (PINT 13)',
        '$lookup(S_done.ENV, $ptascii("y284")) = (n_y)',
        'S_done.STORE[n_y] = DEFINED (PINT 17)',
    ]),
    ('published-arrayaccess-notice-authenticates-tentative-prototype',
     'tentative-return-notice-and-return-type-will-change',
     'S.TODO = (DECL_NOTICES pdeclnoticebatch) :: ptask_tail* -- if pdeclnoticebatch.INDEX = 0', [
        'S.TODO = (DECL_NOTICES pdeclnoticebatch) :: ptask_tail*',
        'pdeclnoticebatch.KIND = NOTICE_RUNTIME', 'pdeclnoticebatch.INDEX = 0',
        'pdeclnoticebatch.NOTICES = [METHOD_NOTICE pdeclnotice]',
        'pdeclnoticebatch.CLASSES = [(porigin_class, n_prefix)]',
        'pdeclnotice.CLASS = porigin_class', 'pdeclnotice.LINE = 5',
        '$class_at(S.CLASSES, porigin_class) = (pclassdesc)',
        'pclassdesc.NAME = $ptascii("NoticeAccess284")',
        '$class_origin_matches(S, porigin_class, $ptascii("ArrayAccess"), |S.CLASSES|)',
        '$effective_method(S, porigin_class, $ptascii("offsetExists"), |S.CLASSES|) = (pmethoddesc_exists)',
        '$effective_method(S, porigin_class, $ptascii("offsetGet"), |S.CLASSES|) = (pmethoddesc_get)',
        'pdeclnotice.METHOD = pmethoddesc_exists.FUNCTION.ORIGIN',
        '$arrayaccess_method_issue(S, pclassdesc, pmethoddesc_exists) = METHOD_OK',
        '$arrayaccess_method_issue(S, pclassdesc, pmethoddesc_get) = METHOD_OK',
        '$arrayaccess_notice_return(S, pclassdesc, pmethoddesc_exists) = PMCHECK PVNO ptbytes_note*',
        '$iterator_notice_suppressed(S, pmethoddesc_get)',
        '$arrayaccess_notice_method(S, pclassdesc, pclassdesc, pmethoddesc_get, $arrayaccess_notice_return(S, pclassdesc, pmethoddesc_get)) = DECLNOTICES eps',
        '$iterator_notice_plan(S, pclassdesc) = DECLNOTICES ([pdeclnotice])',
        '$iterator_notice_batch_valid(S, pdeclnoticebatch)',
        '~$iterator_notice_batch_valid(S, pdeclnoticebatch[.INDEX = 2])',
        '~$iterator_notice_batch_valid(S, pdeclnoticebatch[.SITE = PORIGIN 999 eps])',
        '~$iterator_notice_batch_valid(S, pdeclnoticebatch[.NOTICES = [METHOD_NOTICE pdeclnotice[.MESSAGE = $ptascii("forged")]]])',
        '~$iterator_notice_batch_valid(S, pdeclnoticebatch[.NOTICES = [METHOD_NOTICE pdeclnotice[.METHOD = pmethoddesc_get.FUNCTION.ORIGIN]]])',
        '~$iterator_notice_batch_valid(S, pdeclnoticebatch[.NOTICES = [METHOD_NOTICE pdeclnotice[.LINE = 6]]])',
        '$task_nodes(DECL_NOTICES pdeclnoticebatch) = eps', '$outputs(S.EVENTS) = eps',
        *guards(), 'PhpStep: S ~> S_warning',
        'S_warning.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = DECL_NOTICE_RESUME pdeclnoticebatch[.INDEX = 1]',
        'perrorcall.LEVEL = 8192', 'perrorcall.LINE = 5',
        'perrorcall.MESSAGE = pdeclnotice.MESSAGE', '$error_call_valid(S_warning, perrorcall)',
        '~$error_call_valid(S_warning, perrorcall[.MESSAGE = $ptascii("forged")])',
        'S_done = $drive(S_warning, 3000)', *FINISH,
        '$class_at(S_done.CLASSES, porigin_class) = (pclassdesc)',
        '$lookup(S_done.ENV, $ptascii("o284")) = (n_o)',
        'S_done.STORE[n_o] = DEFINED (POBJECT n_object)',
        'S_done.OBJECTS[n_object] = INSTANCE porigin_class',
    ]),
    ('nan-truth-return-retains-inner-receiver-and-copied-key',
     'empty-nan-get-warning-keeps-handler-receiver-and-real-key-cell',
     'S.TODO = (ACCESS_RESUME paccess) :: ptask_tail* -- if paccess.PHASE = ACCESS_TRUTH ptbytes b', [
        'S.TODO = (ACCESS_RESUME paccess) :: ptask_tail*',
        'paccess.PHASE = ACCESS_TRUTH $ptascii("offsetGet") true',
        'paccess.MODE = ACCESS_READ (KEY_TEST true)',
        'paccess.LINE = 12', 'paccess.KEYLINE = 12',
        'paccess.INPUT = VARIABLE $ptascii("key284") 12',
        'paccess.RHS = KNOWN PNULL', 'paccess.VALUE = PFLOAT n_nan',
        '$number_bool(NFLOAT n_nan) = (true, true)',
        'paccess.BASE = BASE_VALUE (VARIABLE $ptascii("o284") 12)',
        'paccess.OBJECT = (n_object)', 'paccess.OFFSET = PARRAY n_key',
        '~paccess.OUTER', '~paccess.LATCH',
        '$lookup(S.ENV, $ptascii("o284")) = eps',
        '$lookup(S.ENV, $ptascii("key284")) = eps',
        '$lookup(S.ENV, $ptascii("cell284")) = eps',
        '$entry_lookup(S.ARRAYS[n_key].ITEMS, KINT 0) = (DIRECT (PINT 1))',
        '$entry_lookup(S.ARRAYS[n_key].ITEMS, KINT 1) = (ALIAS n_cell)',
        'S.STORE[n_cell] = DEFINED (PINT 9)', 'n_cell <- S.REFCELLS',
        '~((HARRAY n_key) <- $pools_nodes(S.POOLS))',
        '$task_nodes(ACCESS_RESUME paccess) = [HOBJECT n_object, HARRAY n_key]',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_object) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_key) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_cell) = 1',
        '$outputs(S.EVENTS) = $ptascii("E;G;W:12;")', '$access_valid(S, paccess)',
        '~$access_valid(S, paccess[.OBJECT = eps])',
        '~$access_valid(S, paccess[.PHASE = ACCESS_TRUTH $ptascii("offsetGet") false])',
        '~$access_valid(S, paccess[.VALUE = PINT 1])',
        '~$access_valid(S, paccess[.MODE = ACCESS_READ KEY_R])',
        '~$access_valid(S, paccess[.LINE = 13])',
        '~$access_valid(S, paccess[.OUTER = true])',
        '~$access_valid(S, paccess[.INPUT = KNOWN (PARRAY n_key)])',
        '~$call_task_valid(S, ACCESS_RESULT paccess)', *guards(),
        'PhpStep: S ~> S_predicate', 'S_predicate.TODO = ptask_tail*',
        'S_predicate.RESULT = KNOWN (PINT 1)',
        'S_predicate.EVENTS = S.EVENTS', 'S_predicate.STORE = S.STORE',
        '$heap_owners($heap_prune($heap_graph(S_predicate)), HOBJECT n_object) = 0',
        '$heap_owners($heap_prune($heap_graph(S_predicate)), HARRAY n_key) = 0',
        '$heap_owners($heap_prune($heap_graph(S_predicate)), HCELL n_cell) = 0',
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.TODO = S_predicate.TODO', 'S_budget.RESULT = S_predicate.RESULT',
        '~((HOBJECT n_object) <- S_budget.ALLOCATIONS)',
        '~((HARRAY n_key) <- S_budget.ALLOCATIONS)',
        '~((HCELL n_cell) <- S_budget.ALLOCATIONS)',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("r284")) = (n_r)',
        'S_done.STORE[n_r] = DEFINED (PBOOL false)',
    ]),
]
