"""Genuine source-reached writable ArrayAccess and affected GLOBALS continuations."""
from error_handler_protocol import PREFIX as BASE_PREFIX

PREFIX = BASE_PREFIX + r'''
dec $author_final_array(pstate) : bool
def $author_final_array(S) = true
  -- if S.TODO = (KEY_WRITE_DIM (KNOWN (PINT 3)) z false) :: ptask_tail*
  -- if $container_writer(S.TODO) = (pkeywriter)
  -- if pkeywriter.BASE = BASE_DIM (BASE_RETURNED porigin n) (KNOWN (PINT 3)) z
  -- if S.ORIGIN = (pkeywriter.TARGET)
def $author_final_array(S) = false -- otherwise
dec $author_seek_final_array(pstate, nat) : pstate
def $author_seek_final_array(S, n) = S -- if $author_final_array(S) -- if S.COMPLETION = NORMAL \/ S.COMPLETION = BUDGET
def $author_seek_final_array(S, n) = $author_seek_final_array($drive_steps(S[.COMPLETION = NORMAL], 1), $nabs($(n - 1)))
  -- if ~$author_final_array(S)
  -- if S.COMPLETION = NORMAL \/ S.COMPLETION = BUDGET
  -- if $(n > 0)
def $author_seek_final_array(S, n) = S -- if S.COMPLETION =/= NORMAL /\ S.COMPLETION =/= BUDGET

dec $own_access_return(pstate, paccessmode, ptbytes, int) : bool
def $own_access_return(S, paccessmode, ptbytes, z) = true
  -- if S.TODO = (ACCESS_RESULT paccess) :: ptask_tail*
  -- if paccess.MODE = paccessmode
  -- if paccess.PHASE = ACCESS_CALL ptbytes
  -- if paccess.LINE = z
def $own_access_return(S, paccessmode, ptbytes, z) = false -- otherwise
dec $own_seek_access(pstate, paccessmode, ptbytes, int, nat) : pstate
def $own_seek_access(S, paccessmode, ptbytes, z, n) = S
  -- if $own_access_return(S, paccessmode, ptbytes, z)
  -- if S.COMPLETION = NORMAL \/ S.COMPLETION = BUDGET
def $own_seek_access(S, paccessmode, ptbytes, z, n) = $own_seek_access($drive_steps(S[.COMPLETION = NORMAL], 1), paccessmode, ptbytes, z, $nabs($(n - 1)))
  -- if ~$own_access_return(S, paccessmode, ptbytes, z)
  -- if S.COMPLETION = NORMAL \/ S.COMPLETION = BUDGET
  -- if $(n > 0)
def $own_seek_access(S, paccessmode, ptbytes, z, n) = S
  -- if S.COMPLETION =/= NORMAL /\ S.COMPLETION =/= BUDGET
'''


def guards(s='S'):
    return [f'$call_current_valid({s})', f'$call_frames_valid({s}, {s}.FRAMES)',
            f'$call_descriptors_valid({s})', f'$heap_valid($heap_graph({s}))']


FINISH = ['S_done.COMPLETION = NORMAL', 'S_done.TODO = eps',
          'S_done.CURRENT = eps', 'S_done.FRAMES = eps', 'S_done.HELD = eps',
          'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
          *guards('S_done')]


CASES = [
    ('append-compound-preserves-authentic-get-and-set-consumer',
     'direct-append-compound-passes-null-to-get-and-set',
     'S.TODO = (ACCESS_RESULT paccess) :: ptask_tail* -- if paccess.MODE = ACCESS_COMPOUND ADD (PINT 9) -- if paccess.PHASE = ACCESS_CALL $ptascii("offsetSet")', [
        'S.TODO = (ACCESS_RESULT paccess) :: ptask_tail*',
        'paccess.MODE = ACCESS_COMPOUND ADD (PINT 9)',
        'paccess.PHASE = ACCESS_CALL $ptascii("offsetSet")',
        'paccess.LINE = 12', 'paccess.KEYLINE = 12',
        'paccess.INPUT = KNOWN PNULL', 'paccess.OFFSET = PNULL',
        'paccess.RHS = KNOWN (PINT 3)', 'paccess.SELECTED = paccess.RHS',
        'paccess.VALUE = PINT 12', 'paccess.OUTER', '~paccess.LATCH',
        'paccess.BASE = BASE_VALUE (VARIABLE $ptascii("o292") 12)',
        'paccess.TASK = COMPOUND_APPLY ADD (BASE_APPEND paccess.BASE 12) false 12',
        'paccess.OBJECT = (n_object)', '$access_valid(S, paccess)',
        'S.OBJECTS[n_object] = INSTANCE porigin_class',
        '$effective_method(S, porigin_class, $ptascii("offsetSet"), |S.CLASSES|) = (pmethoddesc)',
        '$access_method_selected(S, paccess, METHOD_TARGET n_object pmethoddesc.FUNCTION.ORIGIN)',
        '$task_nodes(ACCESS_RESULT paccess) = [HOBJECT n_object, HOBJECT n_object]',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_object) = 3',
        '~$access_valid(S, paccess[.MODE = ACCESS_COMPOUND SUBTRACT (PINT 9)])',
        '~$access_valid(S, paccess[.RHS = KNOWN (PINT 4)][.SELECTED = KNOWN (PINT 4)])',
        '~$access_valid(S, paccess[.INPUT = KNOWN (PINT 1)][.OFFSET = PINT 1])',
        '~$access_valid(S, paccess[.MODE = ACCESS_SET])',
        '~$access_valid(S, paccess[.PHASE = ACCESS_CALL $ptascii("offsetGet")])',
        '~$access_valid(S, paccess[.OBJECT = eps])',
        '~$access_valid(S, paccess[.OUTER = false])',
        '~$access_valid(S, paccess[.LINE = 13])',
        '~$access_valid(S, paccess[.SITE = PORIGIN 999 eps])',
        '~$access_valid(S, paccess[.TARGET = paccess.SITE])',
        '$origin_node(S.SOURCES, paccess.SITE) = (pcnode)',
        '~$access_context_node(pcnode, $ptascii("__tostring"))',
        *guards(), 'PhpStep: S ~> S_next',
        'S_next.TODO = ptask_tail*', 'S_next.RESULT = KNOWN (PINT 12)',
        'S_next.STORE = S.STORE', 'S_next.EVENTS = S.EVENTS',
        '$heap_owners($heap_prune($heap_graph(S_next)), HOBJECT n_object) = 1',
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.TODO = S_next.TODO', 'S_budget.RESULT = S_next.RESULT',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("r292")) = (n_result)',
        'S_done.STORE[n_result] = DEFINED (PINT 12)',
    ]),
    ('depth-three-fetch-extracts-row-and-retains-final-base-until-write',
     'returned-array-depth-three-writes-only-owned-temporary',
     'S.TODO = (ACCESS_RESUME paccess) :: ptask_tail* -- if paccess.PHASE = ACCESS_NOTICE', [
        'S.TODO = (ACCESS_RESUME paccess) :: ptask_tail*',
        'paccess.MODE = ACCESS_FETCH false false', 'paccess.PHASE = ACCESS_NOTICE',
        'paccess.VALUE = PARRAY n_parent', 'paccess.LINE = 13',
        'paccess.INPUT = KNOWN (PINT 1)', 'paccess.OFFSET = PINT 1',
        'paccess.OBJECT = (n_object)', 'paccess.OUTER', '$access_valid(S, paccess)',
        '$lookup(S.ENV, $ptascii("a292")) = (n_a)',
        'S.STORE[n_a] = DEFINED (PARRAY n_parent)',
        '$entry_lookup(S.ARRAYS[n_parent].ITEMS, KINT 2) = (DIRECT (PARRAY n_child))',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_parent) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_object) = 2',
        '$task_nodes(ACCESS_RESUME paccess) = [HARRAY n_parent, HOBJECT n_object]',
        '~$access_valid(S, paccess[.MODE = ACCESS_FETCH false true])',
        '~$access_valid(S, paccess[.MODE = ACCESS_SET])',
        '~$access_valid(S, paccess[.MODE = ACCESS_FETCH true false])',
        '~$access_valid(S, paccess[.LINE = 14])',
        '~$access_valid(S, paccess[.INPUT = KNOWN (PINT 2)][.OFFSET = PINT 2])',
        *guards(), 'PhpStep: S ~> S_next',
        'n_first = |S.STORE|', 'S_next.LOCATION = ROOT n_first',
        'S_next.STORE[n_first] = DEFINED (PARRAY n_parent)',
        '$heap_owners($heap_prune($heap_graph(S_next)), HCELL n_first) = 1',
        '$heap_owners($heap_prune($heap_graph(S_next)), HOBJECT n_object) = 1',
        'S_final_reached = $author_seek_final_array(S_next, 100)',
        r'S_final_reached.COMPLETION = NORMAL \/ S_final_reached.COMPLETION = BUDGET',
        'S_final = S_final_reached[.COMPLETION = NORMAL]',
        'S_final.TODO = (KEY_WRITE_DIM (KNOWN (PINT 3)) 13 false) :: ptask_final*',
        '$container_writer(S_final.TODO) = (pkeywriter)',
        'pkeywriter.BASE = BASE_DIM (BASE_RETURNED porigin_row n_row) (KNOWN (PINT 3)) 13',
        'S_final.ORIGIN = (pkeywriter.TARGET)', 'S_final.LOCATION = ROOT n_row',
        'S_final.STORE[n_row] = DEFINED (PARRAY n_child)',
        '$key_writer_valid(S_final, pkeywriter, ptask_final*)',
        '$heap_owners($heap_prune($heap_graph(S_final)), HCELL n_first) = 0',
        '$heap_owners($heap_prune($heap_graph(S_final)), HCELL n_row) = 1',
        '$heap_owners($heap_prune($heap_graph(S_final)), HARRAY n_parent) = 1',
        '$heap_owners($heap_prune($heap_graph(S_final)), HARRAY n_child) = 2',
        'n_dead = |S.ARRAYS|',
        '$(n_dead < |S_final.ARRAYS|)',
        '$entry_lookup(S_final.ARRAYS[n_dead].ITEMS, KINT 2) = (DIRECT (PARRAY n_child))',
        '~((HARRAY n_dead) <- S_final.ALLOCATIONS)',
        '$heap_owners($heap_prune($heap_graph(S_final)), HARRAY n_dead) = 0',
        '~$access_fetch_releases(S_final.TODO, pkeywriter.TARGET)',
        'n_unallocated = |S_final.STORE|',
        '~$key_write_base_source(S_final, porigin_row, BASE_RETURNED porigin_row n_unallocated)',
        '~$key_write_base_source(S_final, pkeywriter.TARGET, BASE_RETURNED porigin_row n_row)',
        *guards('S_final'), 'PhpStep: S_final ~> S_target',
        'n_written = |S_final.ARRAYS|', 'S_target.LOCATION = ELEMENT n_written (KINT 3)',
        'S_target.STORE[n_row] = DEFINED (PARRAY n_written)',
        '$heap_owners($heap_prune($heap_graph(S_target)), HCELL n_row) = 1',
        '$heap_owners($heap_prune($heap_graph(S_target)), HARRAY n_written) = 1',
        '$heap_owners($heap_prune($heap_graph(S_target)), HARRAY n_child) = 1',
        '$entry_lookup(S_target.ARRAYS[n_written].ITEMS, KINT 3) = (DIRECT (PINT 5))',
        '$container_writer(S_target.TODO) = (pkeywriter)',
        *guards('S_target'), 'S_budget = $drive_steps(S_final, 1)',
        'S_budget.COMPLETION = BUDGET', 'S_budget.LOCATION = S_target.LOCATION',
        'S_budget.STORE = S_target.STORE',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        '$heap_owners($heap_prune($heap_graph(S_done)), HARRAY n_written) = 0',
        '$entry_lookup(S_done.ARRAYS[n_child].ITEMS, KINT 3) = (DIRECT (PINT 5))',
    ]),
    ('update-notice-keeps-owned-get-var-without-invoking-set',
     'pre-and-post-updates-use-get-temporary-without-set',
     'S.TODO = (ACCESS_RESUME paccess) :: ptask_tail* -- if paccess.PHASE = ACCESS_NOTICE -- if $container_writer(S.TODO) = (pkeywriter) -- if pkeywriter.TASK = UPDATE_PREP INCREMENT false 12', [
        'S.TODO = (ACCESS_RESUME paccess) :: ptask_tail*',
        'paccess.MODE = ACCESS_FETCH false true', 'paccess.PHASE = ACCESS_NOTICE',
        'paccess.VALUE = PINT 7', 'paccess.LINE = 12', 'paccess.KEYLINE = 12',
        'paccess.INPUT = KNOWN (PINT 1)', 'paccess.OFFSET = PINT 1',
        'paccess.OBJECT = (n_object)', 'paccess.OUTER', '$access_valid(S, paccess)',
        '$container_writer(S.TODO) = (pkeywriter)',
        'pkeywriter.TASK = UPDATE_PREP INCREMENT false 12',
        '$task_nodes(ACCESS_RESUME paccess) = [HOBJECT n_object]',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_object) = 2',
        '~$access_valid(S, paccess[.MODE = ACCESS_FETCH false false])',
        '~$access_valid(S, paccess[.MODE = ACCESS_COMPOUND ADD PNULL])',
        '~$access_valid(S, paccess[.INPUT = KNOWN (PINT 2)][.OFFSET = PINT 2])',
        '~$access_valid(S, paccess[.OBJECT = eps])',
        '~$access_valid(S, paccess[.LINE = 13])',
        '~$access_valid(S, paccess[.PHASE = ACCESS_CALL $ptascii("offsetGet")])',
        *guards(), 'PhpStep: S ~> S_next',
        'n_temp = |S.STORE|', 'S_next.LOCATION = ROOT n_temp',
        'S_next.STORE[n_temp] = DEFINED (PINT 7)',
        '$container_writer(S_next.TODO) = (pkeywriter_next)',
        'pkeywriter_next.BASE = BASE_RETURNED paccess.TARGET n_temp',
        '$heap_owners($heap_prune($heap_graph(S_next)), HCELL n_temp) = 1',
        '$heap_owners($heap_prune($heap_graph(S_next)), HOBJECT n_object) = 1',
        '$key_writer_valid(S_next, pkeywriter_next, ptask_tail*)',
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.STORE = S_next.STORE', 'S_budget.LOCATION = S_next.LOCATION',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("x292")) = (n_x)',
        '$lookup(S_done.ENV, $ptascii("y292")) = (n_y)',
        'S_done.STORE[n_x] = DEFINED (PINT 8)',
        'S_done.STORE[n_y] = DEFINED (PINT 7)',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_temp) = 0',
    ]),
]


CASES += [
    ('get-return-uses-live-rhs-wrapper-and-current-set-key',
     'compound-live-key-and-borrowed-old-typed-rhs-cell',
     'S.TODO = (ACCESS_RESULT paccess) :: ptask_tail* -- if paccess.PHASE = ACCESS_CALL $ptascii("offsetGet")', [
        'S.TODO = (ACCESS_RESULT paccess) :: ptask_tail*',
        'paccess.MODE = ACCESS_COMPOUND ADD PNULL',
        'paccess.PHASE = ACCESS_CALL $ptascii("offsetGet")',
        'paccess.LINE = 13', 'paccess.KEYLINE = 13', 'paccess.VALUE = PNULL',
        'paccess.INPUT = VARIABLE $ptascii("key292") 13', 'paccess.OFFSET = PINT 1',
        'paccess.RHS = VARIABLE $ptascii("rhs292") 13',
        'paccess.SELECTED = paccess.RHS', 'paccess.OUTER', '~paccess.LATCH',
        'paccess.BASE = BASE_VALUE (VARIABLE $ptascii("o292") 13)',
        'paccess.OBJECT = (n_object)', 'S.RESULT = KNOWN (PINT 5)',
        '$lookup(S.ENV, $ptascii("o292")) = eps',
        '$lookup(S.ENV, $ptascii("key292")) = (n_key)',
        'S.STORE[n_key] = DEFINED (PINT 7)',
        '$lookup(S.ENV, $ptascii("held292")) = (n_old)',
        'S.STORE[n_old] = DEFINED (PINT 19)', 'n_old <- S.REFCELLS',
        '$lookup(S.ENV, $ptascii("rhs292")) = (n_new)',
        '$lookup(S.ENV, $ptascii("replacement292")) = (n_new)',
        'n_new =/= n_old', 'S.STORE[n_new] = DEFINED (PINT 17)',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_old) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_new) = 2',
        '$task_nodes(ACCESS_RESULT paccess) = [HOBJECT n_object, HOBJECT n_object]',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_object) = 2',
        '$access_valid(S, paccess)', '$outputs(S.EVENTS) = $ptascii("G:1;")',
        '~$access_valid(S, paccess[.SELECTED = REFERENCE n_old])',
        '~$access_valid(S, paccess[.MODE = ACCESS_COMPOUND SUBTRACT PNULL])',
        '~$access_valid(S, paccess[.MODE = ACCESS_SET])',
        '~$access_valid(S, paccess[.RHS = KNOWN (PINT 19)][.SELECTED = KNOWN (PINT 19)])',
        '~$access_valid(S, paccess[.LINE = 14])',
        '~$access_valid(S, paccess[.SITE = PORIGIN 999 eps])',
        '~$access_valid(S, paccess[.OUTER = false])',
        '~$access_valid(S, paccess[.OBJECT = eps])',
        *guards(), 'PhpStep: S ~> S_set',
        'S_set.TODO = (CALL_ARGS (METHOD_TARGET n_object porigin_set) eps 2 ([KNOWN (PINT 7), KNOWN (PINT 22)]) (paccess.SITE) 13) :: (ACCESS_RESULT paccess_set) :: ptask_tail*',
        'paccess_set = paccess[.MODE = ACCESS_COMPOUND ADD (PINT 5)][.VALUE = PINT 22][.OFFSET = PINT 7][.PHASE = ACCESS_CALL $ptascii("offsetSet")]',
        '$access_valid(S_set, paccess_set)',
        '$task_nodes(ACCESS_RESULT paccess_set) = $task_nodes(ACCESS_RESULT paccess)',
        '$heap_owners($heap_prune($heap_graph(S_set)), HOBJECT n_object) = 3',
        'S_set.STORE = S.STORE', 'S_set.EVENTS = S.EVENTS',
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.TODO = S_set.TODO', 'S_budget.STORE = S_set.STORE',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("r292")) = (n_result)',
        'S_done.STORE[n_result] = DEFINED (PINT 22)',
        'S_done.STORE[n_old] = DEFINED (PINT 23)',
        'S_done.STORE[n_new] = DEFINED (PINT 17)',
        '$heap_owners($heap_prune($heap_graph(S_done)), HOBJECT n_object) = 0',
    ]),
    ('indirect-notice-drops-key-copy-but-keeps-real-get-row',
     'nested-write-notice-keeps-returned-real-cell-not-old-key-copy',
     'S.TODO = (ACCESS_RESUME paccess) :: ptask_tail* -- if paccess.PHASE = ACCESS_NOTICE', [
        'S.TODO = (ACCESS_RESUME paccess) :: ptask_tail*',
        'paccess.MODE = ACCESS_FETCH false false', 'paccess.PHASE = ACCESS_NOTICE',
        'paccess.LINE = 14', 'paccess.KEYLINE = 14',
        'paccess.TASK = KEY_WRITE_DIM paccess.INPUT 14 false',
        'paccess.INPUT = VARIABLE $ptascii("key292") 14',
        'paccess.RHS = KNOWN (PINT 17)', 'paccess.VALUE = PARRAY n_row',
        'paccess.OFFSET = PARRAY n_key', 'paccess.OBJECT = (n_object)',
        'paccess.OUTER', '~paccess.LATCH', 'paccess.SITE = paccess.TARGET',
        'paccess.BASE = BASE_VALUE (KNOWN PNULL)',
        '$lookup(S.ENV, $ptascii("o292")) = eps',
        '$lookup(S.ENV, $ptascii("key292")) = eps',
        '$lookup(S.ENV, $ptascii("keyCell292")) = eps',
        '$lookup(S.ENV, $ptascii("held292")) = (n_cell)',
        'S.STORE[n_cell] = DEFINED (PINT 13)',
        '$entry_lookup(S.ARRAYS[n_row].ITEMS, KINT 1) = (ALIAS n_cell)',
        '$entry_lookup(S.ARRAYS[n_key].ITEMS, KINT 1) = (ALIAS n_key_cell)',
        'S.STORE[n_key_cell] = DEFINED (PINT 7)',
        '~((HARRAY n_row) <- $pools_nodes(S.POOLS))',
        '~((HARRAY n_key) <- $pools_nodes(S.POOLS))',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_key) = 0',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_key_cell) = 0',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_row) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_cell) = 3',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_object) = 1',
        '$task_nodes(ACCESS_RESUME paccess) = [HARRAY n_row, HOBJECT n_object]',
        '$access_valid(S, paccess)',
        '$outputs(S.EVENTS) = $ptascii("G;N:8:0;")',
        '~$access_valid(S, paccess[.MODE = ACCESS_FETCH true false])',
        '~$access_valid(S, paccess[.MODE = ACCESS_FETCH false true])',
        '~$access_valid(S, paccess[.MODE = ACCESS_SET])',
        '~$access_valid(S, paccess[.LINE = 15])',
        '~$access_valid(S, paccess[.OBJECT = eps])',
        '~$access_valid(S, paccess[.BASE = BASE_VALUE (KNOWN (PARRAY n_key))])',
        *guards(), 'PhpStep: S ~> S_next',
        'n_temp = |S.STORE|', 'S_next.LOCATION = ROOT n_temp',
        'S_next.STORE[n_temp] = DEFINED (PARRAY n_row)',
        '$container_writer(S_next.TODO) = (pkeywriter)',
        '$access_has_returned(pkeywriter.BASE)',
        '$heap_owners($heap_prune($heap_graph(S_next)), HCELL n_temp) = 1',
        '$heap_owners($heap_prune($heap_graph(S_next)), HARRAY n_row) = 1',
        '$heap_owners($heap_prune($heap_graph(S_next)), HCELL n_cell) = 3',
        '$heap_owners($heap_prune($heap_graph(S_next)), HOBJECT n_object) = 0',
        '~$key_write_base_source(S_next, paccess.TARGET, BASE_RETURNED paccess.TARGET (|S_next.STORE|))',
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.STORE = S_next.STORE', 'S_budget.LOCATION = S_next.LOCATION',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        'S_done.STORE[n_cell] = DEFINED (PINT 17)',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_cell) = 2',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_temp) = 0',
        '$heap_owners($heap_prune($heap_graph(S_done)), HARRAY n_row) = 0',
    ]),
    ('get-throw-replacement-preserves-original-and-older-chain',
     'compound-get-throw-replacement-keeps-exact-original-older-chain',
     'S.TODO = (THROW_SEARCH n_original) :: (ACCESS_RESULT paccess) :: ptask_tail* -- if paccess.PHASE = ACCESS_CALL $ptascii("offsetGet")', [
        'S.TODO = (THROW_SEARCH n_original) :: (ACCESS_RESULT paccess) :: ptask_tail*',
        'paccess.MODE = ACCESS_COMPOUND ADD PNULL',
        'paccess.PHASE = ACCESS_CALL $ptascii("offsetGet")',
        'paccess.LINE = 13', 'paccess.KEYLINE = 13', 'S.ORIGIN = (paccess.SITE)',
        'paccess.INPUT = KNOWN (PINT 1)', 'paccess.OFFSET = PINT 1',
        'paccess.RHS = KNOWN (PINT 2)', 'paccess.SELECTED = paccess.RHS',
        'paccess.VALUE = PNULL', 'paccess.OUTER', 'paccess.OBJECT = (n_object)',
        '$lookup(S.ENV, $ptascii("original292")) = eps',
        '$lookup(S.ENV, $ptascii("older292")) = eps',
        '$lookup(S.ENV, $ptascii("o292")) = eps',
        '$lookup(S.ENV, $ptascii("expected292")) = (n_expected)',
        'S.STORE[n_expected] = DEFINED (POBJECT n_original)',
        '$lookup(S.ENV, $ptascii("expectedOlder292")) = (n_expected_older)',
        'S.STORE[n_expected_older] = DEFINED (POBJECT n_older)',
        '$lookup(S.ENV, $ptascii("target292")) = (n_cell)',
        'S.STORE[n_cell] = DEFINED (PINT 9)',
        '$throwable_field(S, n_original, "previous") = POBJECT n_older',
        '$throwable_field(S, n_original, "message") = PSTRING $ptascii("get")',
        '$throwable_field(S, n_older, "message") = PSTRING $ptascii("older")',
        '$throwable_field(S, n_original, "line") = PINT 11',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_original) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_older) = 2',
        '$access_valid(S, paccess)',
        '~$access_valid(S, paccess[.LINE = 11])',
        '~$access_valid(S, paccess[.MODE = ACCESS_SET])',
        '~$access_valid(S, paccess[.RHS = KNOWN (PINT 3)][.SELECTED = KNOWN (PINT 3)])',
        *guards(), 'PhpStep: S ~> S_replaced',
        'n_new = |S.OBJECTS|', 'n_new =/= n_original',
        'S_replaced.TODO = (THROW_SEARCH n_new) :: ptask_tail*',
        'S_replaced.COMPLETION = NORMAL',
        '$throwable_field(S_replaced, n_new, "previous") = POBJECT n_original',
        '$throwable_field(S_replaced, n_original, "previous") = POBJECT n_older',
        '$throwable_field(S_replaced, n_new, "message") = PSTRING $ptascii("Cannot use object of type ChainRead292 as array")',
        '$throwable_field(S_replaced, n_new, "line") = PINT 13',
        '$throwable_field(S_replaced, n_new, "file") = PSTRING $call_sourcefile(S.FILES, paccess.SITE)',
        '$heap_owners($heap_prune($heap_graph(S_replaced)), HOBJECT n_object) = 0',
        '$heap_owners($heap_prune($heap_graph(S_replaced)), HOBJECT n_original) = 2',
        '$heap_owners($heap_prune($heap_graph(S_replaced)), HOBJECT n_older) = 2',
        'S_replaced.STORE[n_cell] = DEFINED (PINT 9)',
        '$call_current_valid(S_replaced)', '$call_frames_valid(S_replaced, S_replaced.FRAMES)',
        '$heap_valid($heap_graph(S_replaced))',
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.TODO = S_replaced.TODO', 'S_budget.STORE = S_replaced.STORE',
        'S_after = S_budget[.COMPLETION = NORMAL]',
        '|S_after.DESTRUCTION.HANDLES| = |S_after.OBJECTS|',
        '~((HOBJECT n_object) <- S_after.ALLOCATIONS)',
        '(HOBJECT n_new) <- S_after.ALLOCATIONS', *guards('S_after'),
        'S_done = $drive(S_after, 3000)', *FINISH,
        'S_done.STORE[n_cell] = DEFINED (PINT 9)',
        '$lookup(S_done.ENV, $ptascii("expected292")) = eps',
        '$lookup(S_done.ENV, $ptascii("expectedOlder292")) = eps',
        '$lookup(S_done.ENV, $ptascii("e")) = (n_catch)',
        'S_done.STORE[n_catch] = DEFINED (POBJECT n_new)',
        '$heap_owners($heap_prune($heap_graph(S_done)), HOBJECT n_original) = 1',
        '$heap_owners($heap_prune($heap_graph(S_done)), HOBJECT n_older) = 1',
    ]),
    ('entered-set-retains-get-rv-rhs-result-and-real-cell-edges',
     'compound-computed-array-rhs-shares-real-cell-after-retirement',
     'S.CURRENT = (pcallcontext) -- if S.FRAMES = pframe :: pframe_tail* -- if pframe.TODO = (ACCESS_RESULT paccess) :: ptask_saved* -- if paccess.MODE = ACCESS_COMPOUND ADD (PARRAY n_left) -- if paccess.PHASE = ACCESS_CALL $ptascii("offsetSet") -- if $outputs(S.EVENTS) = $ptascii("G:1:9;S:7:13:13;")', [
        'S.CURRENT = (pcallcontext)', 'S.FRAMES = pframe :: pframe_tail*',
        'pframe.TODO = (ACCESS_RESULT paccess) :: ptask_saved*',
        'paccess.MODE = ACCESS_COMPOUND ADD (PARRAY n_left)',
        'paccess.PHASE = ACCESS_CALL $ptascii("offsetSet")',
        'paccess.LINE = 12', 'paccess.KEYLINE = 12',
        'paccess.RHS = KNOWN (PARRAY n_rhs)',
        'paccess.SELECTED = paccess.RHS', 'paccess.VALUE = PARRAY n_result',
        'paccess.INPUT = VARIABLE $ptascii("key292") 12',
        'paccess.OFFSET = PARRAY n_key', 'paccess.OBJECT = (n_object)',
        'paccess.OUTER', '~paccess.LATCH',
        'S.GLOBALTABLE = (psymboltable)',
        '$lookup(psymboltable.ENV, $ptascii("o292")) = eps',
        '$lookup(psymboltable.ENV, $ptascii("held292")) = eps',
        '$lookup(S.ENV, $ptascii("value")) = (n_parameter)',
        'S.STORE[n_parameter] = DEFINED (PARRAY n_result)',
        '$entry_lookup(S.ARRAYS[n_rhs].ITEMS, KINT 2) = (ALIAS n_cell)',
        '$entry_lookup(S.ARRAYS[n_left].ITEMS, KINT 1) = (ALIAS n_cell)',
        'S.ARRAYS[n_result].ITEMS = [ENTRY (KINT 1) (ALIAS n_cell), ENTRY (KINT 2) (ALIAS n_cell)]',
        'S.STORE[n_cell] = DEFINED (PINT 13)',
        'n_rhs =/= n_left', 'n_result =/= n_left', 'n_result =/= n_rhs',
        '~((HARRAY n_rhs) <- $pools_nodes(S.POOLS))',
        '~((HARRAY n_left) <- $pools_nodes(S.POOLS))',
        '$task_nodes(ACCESS_RESULT paccess) = [HARRAY n_rhs, HARRAY n_left, HARRAY n_result, HOBJECT n_object, HOBJECT n_object, HARRAY n_key]',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_rhs) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_left) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_result) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_cell) = 5',
        'pcallcontext.ARGC = 2', 'pcallcontext.CALLSITE = (paccess.SITE)',
        'pcallcontext.LINE = 12', '$access_frame(S, pcallcontext, pframe)',
        '~$access_frame(S, pcallcontext[.ARGC = 1], pframe)',
        '~$access_frame(S, pcallcontext[.LINE = 13], pframe)',
        '~$access_frame(S, pcallcontext, pframe[.TODO = ptask_saved*])',
        '$outputs(S.EVENTS) = $ptascii("G:1:9;S:7:13:13;")', *guards(),
        'S_restored_reached = $own_seek_access(S, paccess.MODE, $ptascii("offsetSet"), 12, 3000)',
        r'S_restored_reached.COMPLETION = NORMAL \/ S_restored_reached.COMPLETION = BUDGET',
        'S_restored = S_restored_reached[.COMPLETION = NORMAL]',
        'S_restored.TODO = (ACCESS_RESULT paccess) :: ptask_saved*',
        '$access_valid(S_restored, paccess)',
        'S_restored.STORE[n_cell] = DEFINED (PINT 17)',
        '$heap_owners($heap_prune($heap_graph(S_restored)), HARRAY n_rhs) = 1',
        '$heap_owners($heap_prune($heap_graph(S_restored)), HARRAY n_left) = 1',
        '$heap_owners($heap_prune($heap_graph(S_restored)), HARRAY n_result) = 1',
        *guards('S_restored'), 'PhpStep: S_restored ~> S_returned',
        'S_returned.TODO = ptask_saved*', 'S_returned.RESULT = KNOWN (PARRAY n_result)',
        '$heap_owners($heap_prune($heap_graph(S_returned)), HARRAY n_rhs) = 0',
        '$heap_owners($heap_prune($heap_graph(S_returned)), HARRAY n_left) = 0',
        '$heap_owners($heap_prune($heap_graph(S_returned)), HARRAY n_result) = 1',
        'S_done = $drive(S_returned, 3000)', *FINISH,
        'S_done.STORE[n_cell] = DEFINED (PINT 19)',
        '$heap_owners($heap_prune($heap_graph(S_done)), HARRAY n_rhs) = 0',
        '$heap_owners($heap_prune($heap_graph(S_done)), HARRAY n_left) = 0',
        '$lookup(S_done.ENV, $ptascii("r292")) = (n_destination)',
        'S_done.STORE[n_destination] = DEFINED (PARRAY n_result)',
    ]),
]


CASES += [
    ('notice-throw-preserves-primary-and-skips-late-rhs',
     'nested-notice-throw-skips-late-rhs-and-typed-destination',
     'S.TODO = (THROW_SEARCH n_error) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail* -- if perrorcall.RESUME = ACCESS_RESUME paccess -- if paccess.PHASE = ACCESS_NOTICE', [
        'S.TODO = (THROW_SEARCH n_error) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = ACCESS_RESUME paccess', '$error_call_valid(S, perrorcall)',
        'paccess.MODE = ACCESS_FETCH false false',
        'paccess.PHASE = ACCESS_NOTICE', 'paccess.RHS = VARIABLE $ptascii("missing292") 15',
        'paccess.VALUE = PARRAY n_row', 'paccess.OBJECT = (n_object)',
        'paccess.OUTER', 'S.ORIGIN = (paccess.SITE)', '$access_valid(S, paccess)',
        '$lookup(S.ENV, $ptascii("o292")) = eps',
        '$lookup(S.ENV, $ptascii("missing292")) = eps',
        '$lookup(S.ENV, $ptascii("error292")) = eps',
        '$lookup(S.ENV, $ptascii("older292")) = eps',
        '$lookup(S.ENV, $ptascii("target292")) = (n_target)',
        'S.STORE[n_target] = DEFINED (PINT 9)',
        '$lookup(S.ENV, $ptascii("data292")) = (n_data)',
        'S.STORE[n_data] = DEFINED (PARRAY n_row)',
        '$entry_lookup(S.ARRAYS[n_row].ITEMS, KINT 1) = (DIRECT (PINT 9))',
        '$throwable_field(S, n_error, "message") = PSTRING $ptascii("notice")',
        '$throwable_field(S, n_error, "previous") = POBJECT n_older',
        '$throwable_field(S, n_older, "message") = PSTRING $ptascii("older")',
        '$outputs(S.EVENTS) = $ptascii("G;N;")',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_row) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_object) = 1',
        '~$access_valid(S, paccess[.MODE = ACCESS_COMPOUND ADD PNULL])',
        '~$access_valid(S, paccess[.MODE = ACCESS_FETCH true false])',
        '~$access_valid(S, paccess[.RHS = KNOWN (PINT 17)])',
        '~$access_valid(S, paccess[.LINE = 999])',
        *guards(), 'PhpStep: S ~> S_next',
        'S_next.TODO = (THROW_SEARCH n_error) :: ptask_tail*',
        'S_next.COMPLETION = NORMAL', 'S_next.OBJECTS = S.OBJECTS',
        'S_next.STORE = S.STORE', 'S_next.EVENTS = S.EVENTS',
        '$lookup(S_next.ENV, $ptascii("missing292")) = eps',
        '$throwable_field(S_next, n_error, "previous") = POBJECT n_older',
        '$heap_owners($heap_prune($heap_graph(S_next)), HARRAY n_row) = 1',
        '$heap_owners($heap_prune($heap_graph(S_next)), HOBJECT n_object) = 0',
        *guards('S_next'), 'S_budget = $drive_steps(S, 1)',
        'S_budget.COMPLETION = BUDGET', 'S_budget.TODO = S_next.TODO',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        'S_done.STORE[n_target] = DEFINED (PINT 9)',
        '$lookup(S_done.ENV, $ptascii("missing292")) = eps',
        '$entry_lookup(S_done.ARRAYS[n_row].ITEMS, KINT 1) = (DIRECT (PINT 9))',
        '$lookup(S_done.ENV, $ptascii("e")) = (n_catch)',
        'S_done.STORE[n_catch] = DEFINED (POBJECT n_error)',
        '$throwable_field(S_done, n_error, "previous") = POBJECT n_older',
    ]),
    ('returned-child-object-skips-notice-and-keeps-sole-owner',
     'nested-returned-object-survives-both-global-retirements',
     'S.TODO = (ACCESS_RESULT paccess) :: ptask_tail* -- if paccess.MODE = ACCESS_FETCH false false -- if S.RESULT = KNOWN (POBJECT n_child)', [
        'S.TODO = (ACCESS_RESULT paccess) :: ptask_tail*',
        'paccess.MODE = ACCESS_FETCH false false',
        'paccess.PHASE = ACCESS_CALL $ptascii("offsetGet")',
        'paccess.VALUE = PNULL', 'paccess.OBJECT = (n_outer)',
        'paccess.INPUT = KNOWN (PINT 1)', 'paccess.RHS = KNOWN (PINT 13)',
        'paccess.OUTER', 'S.RESULT = KNOWN (POBJECT n_child)',
        'n_child =/= n_outer', '$access_valid(S, paccess)',
        '$lookup(S.ENV, $ptascii("inner292")) = eps',
        '$lookup(S.ENV, $ptascii("o292")) = eps',
        '$outputs(S.EVENTS) = $ptascii("G;")',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_child) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_outer) = 2',
        '~$access_valid(S, paccess[.MODE = ACCESS_FETCH false true])',
        '~$access_valid(S, paccess[.MODE = ACCESS_SET])',
        '~$access_valid(S, paccess[.LINE = 999])',
        *guards(), 'PhpStep: S ~> S_next',
        'n_temp = |S.STORE|', 'S_next.LOCATION = ROOT n_temp',
        'S_next.STORE[n_temp] = DEFINED (POBJECT n_child)',
        'S_next.RESULT = KNOWN PNULL', 'S_next.EVENTS = S.EVENTS',
        '$container_writer(S_next.TODO) = (pkeywriter)',
        '$access_has_returned(pkeywriter.BASE)',
        '$heap_owners($heap_prune($heap_graph(S_next)), HCELL n_temp) = 1',
        '$heap_owners($heap_prune($heap_graph(S_next)), HOBJECT n_child) = 1',
        '$heap_owners($heap_prune($heap_graph(S_next)), HOBJECT n_outer) = 0',
        *guards('S_next'), 'S_budget = $drive_steps(S, 1)',
        'S_budget.COMPLETION = BUDGET', 'S_budget.LOCATION = S_next.LOCATION',
        'S_budget.TODO = S_next.TODO',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_temp) = 0',
        '$heap_owners($heap_prune($heap_graph(S_done)), HOBJECT n_child) = 0',
        '$heap_owners($heap_prune($heap_graph(S_done)), HOBJECT n_outer) = 0',
        '$lookup(S_done.ENV, $ptascii("written292")) = (n_written)',
        'S_done.STORE[n_written] = DEFINED (PINT 13)',
        '$lookup(S_done.ENV, $ptascii("r292")) = (n_result)',
        'S_done.STORE[n_result] = DEFINED (PINT 13)',
    ]),
]


STAGE = ('S.TODO = (ACCESS_RESUME paccess) :: ptask_tail* -- if paccess.MODE = ACCESS_UNSET '
         '-- if paccess.PHASE = ACCESS_KEY_CV $ptascii("missing292")')

COMMON = [
    'S.TODO = (ACCESS_RESUME paccess) :: ptask_tail*',
    'paccess.MODE = ACCESS_UNSET',
    'paccess.PHASE = ACCESS_KEY_CV $ptascii("missing292")',
    'paccess.INPUT = VARIABLE $ptascii("missing292") 24',
    'paccess.TASK = KEY_UNSET_DIM paccess.INPUT 24 true',
    'paccess.LINE = 24', 'paccess.KEYLINE = 24',
    'paccess.LATCH', 'paccess.OFFSET = PNULL', 'paccess.VALUE = PNULL',
    'paccess.OBJECT = eps', '~paccess.OUTER',
    'paccess.BASE = BASE_VALUE (KNOWN PNULL)',
    'paccess.RHS = KNOWN PNULL', '$access_valid(S, paccess)',
    '$task_nodes(ACCESS_RESUME paccess) = eps',
    '$lookup(S.ENV, $ptascii("missing292")) = (n_key)',
    'S.STORE[n_key] = DEFINED (PINT 7)',
    'S_selected = $quiet_operand(S, paccess.SELECTED)',
    'S_selected.RESULT = KNOWN (POBJECT n_selected)',
    '~$access_valid(S, paccess[.SELECTED = BORROWED NOWHERE])',
    '~$access_valid(S, paccess[.SELECTED = BORROWED (ROOT (|S.STORE|))])',
    '~$access_valid(S, paccess[.SELECTED = BORROWED (ELEMENT (|S.ARRAYS|) (KINT 1))])',
    '~$access_valid(S, paccess[.SELECTED = BORROWED (PROPERTY n_selected $ptascii("x"))])',
    '~$access_valid(S, paccess[.SELECTED = REFERENCE (|S.STORE|)])',
    '~$access_valid(S, paccess[.LINE = 999])',
    '~$access_valid(S, paccess[.MODE = ACCESS_FETCH true false])',
    *guards(),
]

RESUME = [
    'PhpStep: S ~> S_call',
    'S_call.TODO = (CALL_ARGS (METHOD_TARGET n_selected porigin_unset) eps 1 ([KNOWN PNULL]) (paccess.SITE) 24) :: (ACCESS_RESULT paccess_call) :: ptask_tail*',
    'paccess_call = paccess[.OBJECT = (n_selected)][.PHASE = ACCESS_CALL $ptascii("offsetUnset")]',
    '$access_valid(S_call, paccess_call)', 'S_call.EVENTS = S.EVENTS',
    '$task_nodes(ACCESS_RESULT paccess_call) = [HOBJECT n_selected]',
    '$heap_owners($heap_prune($heap_graph(S_call)), HOBJECT n_selected) = 3',
    *guards('S_call'),
    'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
    'S_budget.TODO = S_call.TODO', 'S_budget.STORE = S_call.STORE',
    'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
]


CASES += [
    ('returned-unset-borrows-owned-temp-through-key-callback',
     'nested-unset-returned-object-keeps-temporary-after-global-rebind', STAGE, [
        *COMMON, 'paccess.SELECTED = BORROWED (ROOT n_temp)',
        'S.LOCATION = ROOT n_temp', 'S.STORE[n_temp] = DEFINED (POBJECT n_selected)',
        '$object_name(S, n_selected) = $ptascii("FirstUnset292")',
        '$lookup(S.ENV, $ptascii("o292")) = eps',
        '$lookup(S.ENV, $ptascii("inner292")) = (n_inner)',
        'S.STORE[n_inner] = DEFINED (POBJECT n_replacement)',
        'n_replacement =/= n_selected',
        '$object_name(S, n_replacement) = $ptascii("SecondUnset292")',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_temp) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_selected) = 1',
        '$outputs(S.EVENTS) = $ptascii("G;U;")', *RESUME,
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_temp) = 0',
        '$heap_owners($heap_prune($heap_graph(S_done)), HOBJECT n_selected) = 0',
        '$heap_owners($heap_prune($heap_graph(S_done)), HOBJECT n_replacement) = 1',
    ]),
    ('unset-extracted-alias-keeps-old-wrapper-after-rebind',
     'nested-unset-alias-keeps-old-reference-after-variable-rebind', STAGE, [
        *COMMON, 'paccess.SELECTED = BORROWED (ROOT n_old)',
        'S.LOCATION = ROOT n_old', 'S.STORE[n_old] = DEFINED (POBJECT n_selected)',
        'n_old <- S.REFCELLS',
        '$lookup(S.ENV, $ptascii("held292")) = (n_old)',
        '$lookup(S.ENV, $ptascii("child292")) = (n_new)',
        '$lookup(S.ENV, $ptascii("replacement292")) = (n_new)',
        'n_new =/= n_old',
        '$object_name(S, n_selected) = $ptascii("FirstUnset292")',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_old) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_selected) = 1',
        '$outputs(S.EVENTS) = $ptascii("G;N;U;")', *RESUME,
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_old) = 1',
        '$heap_owners($heap_prune($heap_graph(S_done)), HOBJECT n_selected) = 1',
        '$lookup(S_done.ENV, $ptascii("child292")) = (n_new)',
        '$lookup(S_done.ENV, $ptascii("held292")) = (n_old)',
    ]),
    ('unset-borrowed-element-observes-callback-replacement',
     'nested-unset-ordinary-array-rereads-borrowed-element-after-warning', STAGE, [
        *COMMON, 'paccess.SELECTED = BORROWED (ELEMENT n_row (KINT 1))',
        'S.LOCATION = ELEMENT n_row (KINT 1)',
        '$lookup(S.ENV, $ptascii("row292")) = (n_row_cell)',
        'S.STORE[n_row_cell] = DEFINED (PARRAY n_row)',
        '$entry_lookup(S.ARRAYS[n_row].ITEMS, KINT 1) = (DIRECT (POBJECT n_selected))',
        '$object_name(S, n_selected) = $ptascii("SecondUnset292")',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_row) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_selected) = 1',
        '$outputs(S.EVENTS) = $ptascii("U;")', *RESUME,
        '$heap_owners($heap_prune($heap_graph(S_done)), HARRAY n_row) = 1',
        '$heap_owners($heap_prune($heap_graph(S_done)), HOBJECT n_selected) = 1',
    ]),
]


CASES += [
    ('globals-reference-finish-keeps-name-key-and-source-cell',
     'globals-reference-writer-computed-array-keeps-key-and-source-cell-owners',
     'S.TODO = (KEY_WRITE_FINISH pkeywriter) :: ptask_tail* -- if $reference_global_pending(S) -- if S.RESULT = KNOWN (PSTRING $ptascii("Array"))', [
        'S.TODO = (KEY_WRITE_FINISH pkeywriter) :: ptask_tail*',
        'pkeywriter.BASE = BASE_GLOBAL (KNOWN (PARRAY n_key)) 9',
        'pkeywriter.TASK = REF_ARRAY pkeywriter.BASE n_source 9',
        'pkeywriter.RHS = REFERENCE n_source', 'pkeywriter.TEMP = eps',
        'S.RESULT = KNOWN (PSTRING $ptascii("Array"))',
        'S.ORIGIN = (pkeywriter.SITE)', 'S.LOCATION = ROOT n_target',
        '$lookup(S.ENV, $ptascii("Array")) = (n_target)',
        '$lookup(S.ENV, $ptascii("old292")) = (n_source)',
        '$lookup(S.ENV, $ptascii("rhs292")) = (n_new)',
        '$lookup(S.ENV, $ptascii("next292")) = (n_new)', 'n_new =/= n_source',
        'S.STORE[n_source] = DEFINED (PINT 5)',
        'S.STORE[n_new] = DEFINED (PINT 7)',
        '$lookup(S.ENV, $ptascii("cell292")) = eps',
        '$lookup(S.ENV, $ptascii("held292")) = (n_cell)',
        'S.STORE[n_cell] = DEFINED (PINT 3)',
        '$entry_lookup(S.ARRAYS[n_key].ITEMS, KINT 1) = (ALIAS n_cell)',
        '$outputs(S.EVENTS) = $ptascii("A;")',
        '$reference_global_pending(S)', '$reference_global_valid(S, pkeywriter, $ptascii("Array"))',
        '$key_writer_valid(S, pkeywriter, ptask_tail*)',
        '$task_nodes(KEY_WRITE_FINISH pkeywriter) = [HARRAY n_key, HCELL n_source]',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_key) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_source) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_cell) = 2',
        '~$reference_global_valid(S[.LOCATION = ROOT n_source], pkeywriter, $ptascii("Array"))',
        '~$reference_global_valid(S[.LOCATION = ELEMENT n_key (KINT 1)], pkeywriter, $ptascii("Array"))',
        '$reference_global_pending(S[.LOCATION = ELEMENT n_key (KINT 1)])',
        '~$reference_global_valid(S, pkeywriter, $ptascii("rhs292"))',
        '~$reference_global_valid(S, pkeywriter[.SITE = PORIGIN 999 eps], $ptascii("Array"))',
        '~$reference_global_valid(S, pkeywriter[.TARGET = PORIGIN 999 eps], $ptascii("Array"))',
        '~$reference_global_valid(S, pkeywriter[.RHS = REFERENCE (|S.STORE|)], $ptascii("Array"))',
        '~$reference_global_valid(S, pkeywriter[.BASE = BASE_RETURNED pkeywriter.TARGET n_target], $ptascii("Array"))',
        *guards(), 'PhpStep: S ~> S_bound',
        'S_bound.TODO = ptask_tail*', 'S_bound.RESULT = REFERENCE n_source',
        'S_bound.EVENTS = S.EVENTS', 'S_bound.STORE = S.STORE',
        '$lookup(S_bound.ENV, $ptascii("Array")) = (n_source)',
        '$lookup(S_bound.ENV, $ptascii("old292")) = (n_source)',
        '$lookup(S_bound.ENV, $ptascii("rhs292")) = (n_new)',
        '$heap_owners($heap_prune($heap_graph(S_bound)), HARRAY n_key) = 0',
        '$heap_owners($heap_prune($heap_graph(S_bound)), HCELL n_source) = 3',
        '$heap_owners($heap_prune($heap_graph(S_bound)), HCELL n_cell) = 1',
        *guards('S_bound'), 'S_budget = $drive_steps(S, 1)',
        'S_budget.COMPLETION = BUDGET', 'S_budget.TODO = S_bound.TODO',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        'S_done.STORE[n_source] = DEFINED (PINT 11)',
        'S_done.STORE[n_new] = DEFINED (PINT 7)',
        'S_done.STORE[n_cell] = DEFINED (PINT 3)',
        '$heap_owners($heap_prune($heap_graph(S_done)), HARRAY n_key) = 0',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_source) = 2',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_cell) = 1',
    ]),
]
