#!/usr/bin/env python3
"""Array callback selection certificates, reception and ownership witnesses."""
from pathlib import Path
import json
import warnings

import closure_call_protocol as protocol

CATALOGUE = Path(__file__).with_name('array_callables_cases.json')
SOURCES = {row['id']: row['source'] for row in json.loads(CATALOGUE.read_text())}
VALID = ['$call_descriptors_valid(S)', '$class_state_valid(S)',
         '$closure_state_valid(S)', '$heap_valid($heap_graph(S))']
SELECTED = [
    'S.TODO = (CALL_ARGS (ARRAY_METHOD_TARGET pcalltarget parrayselection) phpType7* n_index poperand* (porigin_site) z_call) :: ptask_tail*',
    'parrayselection.SITE = porigin_site',
    'parrayselection.LINE = z_call',
    'parrayselection.INIT = $dynamic_init_line(S, porigin_site)',
    'parrayselection.NAME = $ptascii("run")',
    '$array_target_identity(S, pcalltarget, parrayselection)',
    '$array_site_valid(S, parrayselection, false)',
    '$target_function(S, pcalltarget) = (pfunction)',
    '$class_method_origin(S.CLASSES, pfunction.ORIGIN) = (pmethoddesc)',
    *VALID,
    '~$array_target_identity(S, pcalltarget, parrayselection[.NAME = $ptascii("missing")])',
    '~$array_target_identity(S, pcalltarget, parrayselection[.REQUESTED = PORIGIN 999 eps])',
    '~$array_target_identity(S, ARRAY_METHOD_TARGET pcalltarget parrayselection, parrayselection)',
    '~$array_site_valid(S, parrayselection[.SITE = pfunction.ORIGIN], false)',
    '~$array_site_valid(S, parrayselection[.INIT = $(parrayselection.INIT + 100)], false)',
    '~$array_site_valid(S, parrayselection[.LINE = $(z_call + 100)], false)',
    '~$call_task_valid(S, CALL_ARGS (ARRAY_METHOD_TARGET pcalltarget parrayselection[.NAME = $ptascii("missing")]) phpType7* n_index poperand* (porigin_site) z_call)',
]
AFTER = ['S_done = $drive(S, 2000)', 'S_done.COMPLETION = NORMAL',
         '$call_descriptors_valid(S_done)', '$closure_state_valid(S_done)',
         '$heap_valid($heap_graph(S_done))']

CASES = {
    'selected-reference-members-retired-array': {
        'source': SOURCES['reference-selector-mutation'],
        'stage': ('S.TODO = (CALL_ARGS (ARRAY_METHOD_TARGET pcalltarget parrayselection) phpType7* 1 poperand* (porigin_site) z_call) :: ptask_tail*'),
        'checks': [
            *SELECTED, 'n_index = 1',
            'pcalltarget = METHOD_TARGET n_receiver pmethoddesc.FUNCTION.ORIGIN',
            '$target_nodes(ARRAY_METHOD_TARGET pcalltarget parrayselection) = [HOBJECT n_receiver]',
            'S.OBJECTS[n_receiver] = INSTANCE parrayselection.REQUESTED',
            '$lookup(S.ENV, $ptascii("cb")) = (n_cb)', 'S.STORE[n_cb] = DEFINED PNULL',
            '$lookup(S.ENV, $ptascii("r")) = (n_r)', 'S.STORE[n_r] = DEFINED (POBJECT n_other)',
            'n_receiver =/= n_other',
            '$lookup(S.ENV, $ptascii("m")) = (n_m)', 'S.STORE[n_m] = DEFINED (PSTRING $ptascii("other"))',
            'S.ARRAYS[0] = parray_original', '~((HARRAY 0) <- S.ALLOCATIONS)',
            '(HOBJECT n_receiver) <- S.ALLOCATIONS',
            '~$array_target_identity(S, METHOD_TARGET n_other pmethoddesc.FUNCTION.ORIGIN, parrayselection)',
            *AFTER, 'S_done.EVENTS = [OUTPUT $ptascii("F"), OUTPUT $ptascii("!")]',
            '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
        ],
    },
    'selected-object-static-receiver-retirement': {
        'source': SOURCES['object-static-no-this-selected-class'],
        'stage': ('S.TODO = (CALL_ARGS (ARRAY_METHOD_TARGET pcalltarget parrayselection) phpType7* 1 poperand* (porigin_site) z_call) :: ptask_tail*'),
        'checks': [
            *SELECTED, 'n_index = 1',
            'pcalltarget = STATIC_METHOD_TARGET parrayselection.REQUESTED pmethoddesc.FUNCTION.ORIGIN',
            'pmethoddesc.STATIC', 'pmethoddesc.OWNER =/= parrayselection.REQUESTED',
            '$target_nodes(ARRAY_METHOD_TARGET pcalltarget parrayselection) = eps',
            '$target_receiver(S, ARRAY_METHOD_TARGET pcalltarget parrayselection) = eps',
            '$target_called_class(S, ARRAY_METHOD_TARGET pcalltarget parrayselection) = (parrayselection.REQUESTED)',
            '$target_lexical_class(S, ARRAY_METHOD_TARGET pcalltarget parrayselection) = (pmethoddesc.OWNER)',
            '$lookup(S.ENV, $ptascii("receiver")) = (n_receiver_cell)', 'S.STORE[n_receiver_cell] = DEFINED PNULL',
            '$lookup(S.ENV, $ptascii("cb")) = (n_cb)', 'S.STORE[n_cb] = DEFINED PNULL',
            'S.OBJECTS[0] = INSTANCE parrayselection.REQUESTED', '~((HOBJECT 0) <- S.ALLOCATIONS)',
            '~((HARRAY 0) <- S.ALLOCATIONS)',
            *AFTER, 'S_done.EVENTS = [OUTPUT $ptascii("Child"), OUTPUT $ptascii("-"), OUTPUT $ptascii("s")]',
        ],
    },
    'capture-direct-allocation-and-certificate': {
        'source': SOURCES['capture-clone-member-retirement'],
        'stage': 'S.TODO = (ARRAY_CONVERT pcalltarget parrayselection) :: ptask_tail*',
        'checks': [
            'pcalltarget = METHOD_TARGET n_receiver porigin_method',
            'parrayselection.NAME = $ptascii("run")',
            '$array_convert_valid(S, pcalltarget, parrayselection)',
            '$array_site_valid(S, parrayselection, true)', *VALID,
            '~$array_convert_valid(S, pcalltarget, parrayselection[.NAME = $ptascii("other")])',
            '~$array_convert_valid(S, pcalltarget, parrayselection[.SITE = porigin_method])',
            '~$array_convert_valid(S, pcalltarget, parrayselection[.INIT = $(parrayselection.INIT + 1)])',
            '~$array_convert_valid(S, pcalltarget, parrayselection[.LINE = $(parrayselection.LINE + 1)])',
            '~$array_convert_valid(S, pcalltarget, parrayselection[.REQUESTED = PORIGIN 999 eps])',
            '$task_nodes(ARRAY_CONVERT pcalltarget parrayselection) = [HOBJECT n_receiver]',
            'n_capture = |S.OBJECTS|', 'PhpStep: S ~> S_one',
            'S_one.COMPLETION = NORMAL', 'S_one.TODO = ptask_tail*',
            'S_one.OBJECTS[n_capture] = ARRAYMETHODCLOSURE pcalltarget parrayselection $method_capture_current(S, parrayselection.SITE)',
            'S_one.RESULT = KNOWN (POBJECT n_capture)',
            'S_one.STORE = S.STORE', 'S_one.EVENTS = S.EVENTS',
            'S_one.ALLOCATIONS = S.ALLOCATIONS ++ [HOBJECT n_capture]',
            '$closure_callable(S_one, n_capture)', '$typed_closure(S_one, n_capture)',
            '$node_children(S_one, HOBJECT n_capture) = [HOBJECT n_receiver]',
            '$closure_scope_at(S_one.CLOSURESCOPES, n_capture) = (pclosurescope)',
            '$closure_scope_row_valid(S_one, pclosurescope)',
            '~$closure_scope_row_valid(S_one, pclosurescope[.RECEIVER = eps])',
            '$closure_state_valid(S_one)', '$call_descriptors_valid(S_one)',
            'S_done = $drive(S_one, 2000)', 'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT $ptascii("F"), OUTPUT $ptascii("c")]',
            '$closure_state_valid(S_done)', '$heap_valid($heap_graph(S_done))',
        ],
    },
    'capture-clone-shared-static-default-cache': {
        'source': SOURCES['capture-clone-shared-method-static-deferred-default'],
        'stage': ('S.TODO = (CALL_ARGS (CLOSURE_TARGET n_capture) eps 0 eps (porigin_site) z_call) :: ptask_tail* '
                  '-- if $lookup(S.ENV, $ptascii("g")) = (n_g) '
                  '-- if S.STORE[n_g] = DEFINED (POBJECT n_capture)'),
        'checks': [
            'S.OBJECTS[n_capture] = ARRAYMETHODCLOSURE pcalltarget parrayselection pmethodcapture?',
            '$lookup(S.ENV, $ptascii("f")) = (n_f)', 'S.STORE[n_f] = DEFINED (POBJECT n_original)',
            'n_original =/= n_capture', 'S.OBJECTS[n_original] = S.OBJECTS[n_capture]',
            '$clone_same_kind(S.OBJECTS[n_original], S.OBJECTS[n_capture])',
            '$closure_callable(S, n_capture)', '$closure_callable(S, n_original)',
            '$target_function(S, CLOSURE_TARGET n_capture) = (pfunction)',
            '$class_method_origin(S.CLASSES, pfunction.ORIGIN) = (pmethoddesc)',
            'pfunction.DEFAULTS = [pdefault]', 'pdefault.KIND = PDDEFERRED',
            '$default_cache_at(S.DEFAULTCACHE, pdefault.ORIGIN) = (pdefaultcache)',
            'pdefaultcache.VALUE = PINT 3', '$default_caches_valid(S, S.DEFAULTCACHE)',
            'S.STATICS = [pstaticcell]', 'S.STORE[pstaticcell.CELL] = DEFINED (PINT 2)',
            'S.EVENTS = [OUTPUT $ptascii("1"), OUTPUT $ptascii(":"), OUTPUT $ptascii("3"), OUTPUT $ptascii(";"), OUTPUT $ptascii("2"), OUTPUT $ptascii(":"), OUTPUT $ptascii("3"), OUTPUT $ptascii(";")]', *VALID,
            *AFTER, 'S_done.EVENTS = [OUTPUT $ptascii("1"), OUTPUT $ptascii(":"), OUTPUT $ptascii("3"), OUTPUT $ptascii(";"), OUTPUT $ptascii("2"), OUTPUT $ptascii(":"), OUTPUT $ptascii("3"), OUTPUT $ptascii(";"), OUTPUT $ptascii("3"), OUTPUT $ptascii(":"), OUTPUT $ptascii("3"), OUTPUT $ptascii(";")]',
            'S_done.STORE[pstaticcell.CELL] = DEFINED (PINT 3)',
            '~((HOBJECT n_original) <- S_done.ALLOCATIONS)', '~((HOBJECT n_capture) <- S_done.ALLOCATIONS)',
        ],
    },
    'method-frame-admission-distinct-from-dispatch': {
        'source': SOURCES['method-frame-nonstatic-class-truth-only'],
        'stage': 'S.TODO = [TYPE_RECEIVE porigin_function 0]',
        'checks': [
            '$function_at($all_functions(S), porigin_function) = (pfunction)',
            '$lookup(S.ENV, $ptascii("value")) = (n_value)', 'S.STORE[n_value] = DEFINED (PARRAY n_array)',
            'S.CURRENT = (pcallcontext)', 'pcallcontext.FUNCTION = porigin_function',
            'pcallcontext.LEXICAL_CLASS = (porigin_owner)', 'pcallcontext.RECEIVER = (n_receiver)',
            '$array_resolve(S, n_array, ARRAY_ADMISSION) = ARRAYADMITTED',
            '$array_implicit_this(S, porigin_owner)',
            '$array_resolve(S, n_array, ARRAY_DISPATCH) = ARRAYINVALID $ptascii("Non-static method Owner::run() cannot be called statically")',
            '$typed_callable(S, PARRAY n_array) = (true)',
            '$typed_parameter_conversion(S, pfunction.SIGNATURE.PARAMETERS[0], PARRAY n_array) = TYPEVALUE (PARRAY n_array)',
            '~$array_implicit_this(S[.CURRENT = (pcallcontext[.RECEIVER = eps])], porigin_owner)',
            '$typed_callable(S[.CURRENT = (pcallcontext[.RECEIVER = eps])], PARRAY n_array) = (false)',
            *VALID, 'PhpStep: S ~> S_one', 'S_one.COMPLETION = NORMAL',
            'S_one.STORE = S.STORE', 'S_one.EVENTS = S.EVENTS', 'S_one.ALLOCATIONS = S.ALLOCATIONS',
            'S_one.CURRENT = S.CURRENT', '$call_descriptors_valid(S_one)',
            'S_done = $drive(S_one, 2000)', 'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT $ptascii("A"), OUTPUT $ptascii(":"), OUTPUT $ptascii("Non-static method Owner::run() cannot be called statically")]',
            '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))',
        ],
    },
    'structural-method-kind-before-class-service': {
        'source': SOURCES['invalid-method-before-unknown-class'],
        'stage': 'S.TODO = (CALL_DYNAMIC porigin_site z_init z_call) :: ptask_tail*',
        'checks': [
            'S.RESULT = VARIABLE $ptascii("cb") z_read',
            '$lookup(S.ENV, $ptascii("cb")) = (n_cb)', 'S.STORE[n_cb] = DEFINED (PARRAY n_array)',
            '$dynamic_operand_valid(S, porigin_site)', '$dynamic_task_valid(S, porigin_site, z_init, z_call)',
            '$array_resolve(S, n_array, ARRAY_DISPATCH) = ARRAYINVALID $ptascii("Second array member is not a valid method")',
            '$typed_callable(S, PARRAY n_array) = (false)', *VALID,
            '~$dynamic_task_valid(S, porigin_site, $(z_init + 1), z_call)',
            '~$dynamic_task_valid(S, porigin_site, z_init, $(z_call + 1))',
            'PhpStep: S ~> S_one',
            'S_one.COMPLETION = THROWN "Error" $ptascii("Second array member is not a valid method") z_error',
            'z_error = z_init', 'S_one.EVENTS = S.EVENTS',
            'S_done = $drive(S_one, 2000)', 'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT $ptascii("Second array member is not a valid method")]',
        ],
    },
}

FILE_CASES = [(
    'array-selected-live-method-ini-prefix', SOURCES['array-method-current-ini-prefix'].encode(),
    'S.TODO = (CONFIG_INVOKE pconfigcall) :: ptask_tail*\n'
    '  -- if pconfigcall.KIND = INTRINSIC_SET_INCLUDE_PATH',
    [
        'S.TODO = (CONFIG_INVOKE pconfigcall) :: ptask_tail*',
        'pconfigcall.KIND = INTRINSIC_SET_INCLUDE_PATH',
        'S.CURRENT = (pcallcontext)',
        'pcallcontext.TARGET = ARRAY_METHOD_TARGET pcalltarget parrayselection',
        'pcalltarget = METHOD_TARGET n_receiver pcallcontext.FUNCTION',
        'pcallcontext.RECEIVER = (n_receiver)',
        '$array_target_identity(S, pcalltarget, parrayselection)',
        '$call_selected_valid(S, pcallcontext.TARGET, pcallcontext.CALLSITE)',
        'S.FILEINCLUDEPATH = ($ptascii("first") ++ [0] ++ $ptascii("tail"))',
        '$outputs(S.EVENTS) = $ptascii("R:")', '$config_invoke_valid(S, pconfigcall)',
        *VALID,
        '~$call_descriptors_valid(S[.CURRENT = (pcallcontext[.RECEIVER = eps])])',
        'S_one = $config_receive(S, pconfigcall)', 'S_one.COMPLETION = NORMAL',
        'S_one.RESULT = KNOWN (PSTRING $ptascii("first"))',
        'S_one.FILEINCLUDEPATH = ($ptascii("last"))',
        'S_one.CURRENT = S.CURRENT', 'S_one.STORE = S.STORE',
        'S_one.ALLOCATIONS = S.ALLOCATIONS', 'S_one.EVENTS = S.EVENTS',
        'S_done = $drive(S_one, 2000)', 'S_done.COMPLETION = NORMAL',
        '$outputs(S_done.EVENTS) = $ptascii("R:first")',
        '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))',
    ],
)]


FILE_CASES.append((
    'array-capture-current-publication-restore-property',
    SOURCES['array-capture-current-publication-restore-property'].encode(),
    'S.CURRENT = (pcallcontext_inner)\n'
    '  -- if S.FRAMES = pframe_option :: pframe_owner :: pframe_tail*\n'
    '  -- if pframe_option.TODO = (STRINGIFY_RESULT n_inner porigin_static z_static) :: (STATIC_STRING_RESULT pstaticstring) :: (STATIC_STRING_CAPTURE pstaticstring) :: ptask_option*\n'
    '  -- if pframe_owner.TODO = (STRINGIFY_RESULT n_option porigin_option z_option) :: (CONFIG_STRING_RESULT pconfigcall n_option porigin_option z_child z_option) :: ptask_owner*',
    [
        'S.CURRENT = (pcallcontext_inner)',
        'S.FRAMES = pframe_option :: pframe_owner :: pframe_tail*',
        'pframe_option.TODO = (STRINGIFY_RESULT n_inner porigin_static z_static) :: (STATIC_STRING_RESULT pstaticstring) :: (STATIC_STRING_CAPTURE pstaticstring) :: ptask_option*',
        'pframe_owner.TODO = (STRINGIFY_RESULT n_option porigin_option z_option) :: (CONFIG_STRING_RESULT pconfigcall n_option porigin_option z_child z_option) :: ptask_owner*',
        'pframe_option.CONTEXT = (pcallcontext_option)',
        'pframe_owner.CONTEXT = (pcallcontext_owner)',
        'pframe_owner.LOCALS = (psymboltable_owner)',
        'pcallcontext_inner.TARGET = METHOD_TARGET n_inner pcallcontext_inner.FUNCTION',
        'pcallcontext_inner.RECEIVER = (n_inner)',
        'pcallcontext_inner.ARGC = 0',
        'pcallcontext_inner.PARAMS = eps',
        'pcallcontext_option.TARGET = METHOD_TARGET n_option pcallcontext_option.FUNCTION',
        'pcallcontext_option.ARGC = 0',
        'pcallcontext_option.PARAMS = eps',
        'pcallcontext_owner.TARGET = CLOSURE_TARGET n_capture',
        'pcallcontext_owner.INSTANCE = (n_capture)',
        'pcallcontext_owner.RECEIVER = (n_receiver)',
        'pcallcontext_owner.LEXICAL_CLASS = (porigin_owner)',
        'pcallcontext_owner.CALLED_CLASS = (porigin_called)',
        'porigin_owner =/= porigin_called',
        'pcallcontext_owner.CALLSITE = (porigin_invoke)',
        'pcallcontext_owner.ARGC = 1',
        'pcallcontext_owner.PARAMS = [$ptascii("v")]',
        '$lookup(psymboltable_owner.ENV, $ptascii("v")) = (n_value)',
        'S.STORE[n_value] = DEFINED (PSTRING $ptascii("x"))',
        '$arginfo_values(S[.ENV = psymboltable_owner.ENV], pcallcontext_owner) = [PSTRING $ptascii("x")]',
        'S.OBJECTS[n_capture] = ARRAYMETHODCLOSURE pcalltarget parrayselection (pmethodcapture)',
        'pcalltarget = METHOD_TARGET n_receiver pcallcontext_owner.FUNCTION',
        'S.OBJECTS[n_receiver] = INSTANCE porigin_called',
        '$declaration_early(S.DECLARATIONS, porigin_called, PPCLASS)',
        'parrayselection.REQUESTED = porigin_called',
        'parrayselection.NAME = $ptascii("run")',
        'parrayselection.SITE =/= porigin_invoke',
        '$array_target_identity(S, pcalltarget, parrayselection)',
        '$array_site_valid(S, parrayselection, true)',
        '$target_function(S, CLOSURE_TARGET n_capture) = (pfunction_owner)',
        'pfunction_owner.ORIGIN = pcallcontext_owner.FUNCTION',
        '$class_method_origin(S.CLASSES, pfunction_owner.ORIGIN) = (pmethoddesc)',
        'pmethoddesc.OWNER = porigin_owner',
        'n_original = 3',
        'n_original =/= n_capture',
        'S.OBJECTS[n_original] = S.OBJECTS[n_capture]',
        '~((HOBJECT n_original) <- S.ALLOCATIONS)',
        'n_array = |S_initial.ARRAYS|',
        'S.ARRAYS[n_array].ITEMS = [ENTRY (KINT 0) (DIRECT (POBJECT n_receiver)), ENTRY (KINT 1) (DIRECT (PSTRING $ptascii("run")))]',
        '~((HARRAY n_array) <- S.ALLOCATIONS)',
        '(HOBJECT n_capture) <- S.ALLOCATIONS',
        '(HOBJECT n_receiver) <- S.ALLOCATIONS',
        '$node_children(S, HOBJECT n_capture) = [HOBJECT n_receiver]',
        '$closure_scope_at(S.CLOSURESCOPES, n_capture) = (pclosurescope)',
        '$closure_scope_row_valid(S, pclosurescope)',
        'pmethodcapture.CALLSITE = (porigin_maker_invoke)',
        'pmethodcapture.LEXICAL_CLASS = (porigin_creator)',
        'pmethodcapture.CALLED_CLASS = (porigin_creator)',
        'S.OBJECTS[0] = REALCLOSURE pmethodcapture.FUNCTION pitem* pstaticcell*',
        'S.OBJECTS[1] = INSTANCE porigin_creator',
        '~((HOBJECT 0) <- S.ALLOCATIONS)',
        '~((HOBJECT 1) <- S.ALLOCATIONS)',
        '$method_capture_certificate_valid(S, parrayselection.SITE, (pmethodcapture))',
        '~$method_capture_certificate_valid(S, parrayselection.SITE, (pmethodcapture[.CALLSITE = (parrayselection.SITE)]))',
        '$function_at(S.CLOSURETEMPLATES, pmethodcapture.FUNCTION) = (pfunction_creator)',
        '$declaration_invocation(S, pfunction_creator, porigin_maker_invoke, (porigin_creator), (porigin_creator), eps)',
        'pstaticstring.OBJECT = n_inner',
        'pstaticstring.NAME = $ptascii("value")',
        '$static_string_record_valid(S, pstaticstring)',
        '$static_string_pairs_valid(pframe_option.TODO)',
        'pconfigcall.KIND = INTRINSIC_INI_RESTORE',
        '$config_string_site_valid(S, pconfigcall, n_option, porigin_option, z_child, z_option)',
        '$outputs(S.EVENTS) = $ptascii("Owner/Child:1:x|o0")',
        '~S.COMPILESTOP',
        '$declaration_history_valid(S)',
        '~$declaration_history_valid(S[.DECLARATIONS = eps])',
        '$declaration_invocation(S, pfunction_owner, porigin_invoke, (porigin_owner), (porigin_called), eps)',
        '~$declaration_invocation(S, pfunction_owner, porigin_invoke, (porigin_called), (porigin_called), eps)',
        *VALID,
        '~$array_target_identity(S, pcalltarget, parrayselection[.NAME = $ptascii("missing")])',
        '~$array_site_valid(S, parrayselection[.SITE = porigin_invoke], true)',
        '~$call_saved_context_valid(S, pframe_owner[.CONTEXT = (pcallcontext_owner[.CALLED_CLASS = (porigin_owner)])])',
        '~$call_saved_context_valid(S, pframe_owner[.CONTEXT = (pcallcontext_owner[.TARGET = CLOSURE_TARGET n_original])])',
        'S_done = $drive(S, 3000)',
        'S_done.COMPLETION = NORMAL',
        '$outputs(S_done.EVENTS) = $ptascii("Owner/Child:1:x|o0p0K|value|1:x")',
        'S_done.FILEINCLUDEPATH = ($ptascii("after"))',
        '$class_static_at(S_done.CLASSSTATICS, pstaticstring.DECL) = (pclassstatic)',
        'pclassstatic.STATE = PROP_VALUE (DIRECT (PSTRING $ptascii("value")))',
        '~((HOBJECT n_original) <- S_done.ALLOCATIONS)',
        '~((HOBJECT n_capture) <- S_done.ALLOCATIONS)',
        '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
        '~((HOBJECT n_inner) <- S_done.ALLOCATIONS)',
        '~((HOBJECT n_option) <- S_done.ALLOCATIONS)',
        '$declaration_history_valid(S_done)',
        '$call_descriptors_valid(S_done)',
        '$class_state_valid(S_done)',
        '$closure_state_valid(S_done)',
        '$heap_valid($heap_graph(S_done))',
    ],
))


INI_OPTION_PREFIX = '''
dec $array_ini_result_stage(pstate) : bool
def $array_ini_result_stage(S) = true
  -- if S.TODO = (CONFIG_STRING_RESULT pconfigcall n_object porigin_child z_child z_call) :: ptask_tail*
  -- if pconfigcall.KIND = INTRINSIC_INI_SET
def $array_ini_result_stage(S) = false -- otherwise
dec $array_ini_result_seek(pstate, nat) : pstate
def $array_ini_result_seek(S, n) = S -- if $array_ini_result_stage(S)
def $array_ini_result_seek(S, n) = $array_ini_result_seek(S_next, $nabs($(n - 1)))
  -- if ~$array_ini_result_stage(S)
  -- if S.COMPLETION = NORMAL
  -- if $(n > 0)
  -- PhpStep: S ~> S_next
dec $array_ini_step(pstate) : pstate
def $array_ini_step(S) = S_next -- PhpStep: S ~> S_next
'''

FILE_CASES.append((
    'array-method-current-ini-option-value-rejection',
    SOURCES['array-method-current-ini-option-value-rejection'].encode(),
    'S.CURRENT = (pcallcontext_option)\n'
    '  -- if S.FRAMES = pframe_owner :: pframe_tail*\n'
    '  -- if pframe_owner.TODO = (STRINGIFY_RESULT n_option porigin_child z_call) :: (CONFIG_STRING_RESULT pconfigcall n_option porigin_child z_child z_call) :: ptask_owner*\n'
    '  -- if S.FILEINCLUDEPATH = ($ptascii("mutated") ++ [0] ++ $ptascii("tail"))',
    [
        'S.CURRENT = (pcallcontext_option)',
        'S.FRAMES = pframe_owner :: pframe_tail*',
        'pframe_owner.TODO = (STRINGIFY_RESULT n_option porigin_child z_call) :: (CONFIG_STRING_RESULT pconfigcall n_option porigin_child z_child z_call) :: ptask_owner*',
        'pframe_owner.CONTEXT = (pcallcontext_owner)',
        'pframe_owner.LOCALS = (psymboltable_owner)',
        'pcallcontext_option.TARGET = METHOD_TARGET n_option pcallcontext_option.FUNCTION',
        'pcallcontext_option.ARGC = 0',
        'pcallcontext_option.PARAMS = eps',
        '$arginfo_values(S, pcallcontext_option) = eps',
        'pcallcontext_owner.TARGET = ARRAY_METHOD_TARGET pcalltarget parrayselection',
        'pcalltarget = METHOD_TARGET n_receiver pcallcontext_owner.FUNCTION',
        'pcallcontext_owner.RECEIVER = (n_receiver)',
        'pcallcontext_owner.LEXICAL_CLASS = (porigin_owner)',
        'pcallcontext_owner.CALLED_CLASS = (porigin_called)',
        'porigin_owner =/= porigin_called',
        'pcallcontext_owner.ARGC = 1',
        'pcallcontext_owner.PARAMS = [$ptascii("v")]',
        '$arginfo_values(S[.ENV = psymboltable_owner.ENV], pcallcontext_owner) = [PSTRING $ptascii("x")]',
        'S.OBJECTS[n_receiver] = INSTANCE porigin_called',
        'parrayselection.REQUESTED = porigin_called',
        'parrayselection.NAME = $ptascii("run")',
        '$array_target_identity(S, pcalltarget, parrayselection)',
        '$array_site_valid(S, parrayselection, false)',
        '$target_nodes(pcallcontext_owner.TARGET) = [HOBJECT n_receiver]',
        'n_array = |S_initial.ARRAYS|',
        'S.ARRAYS[n_array].ITEMS = [ENTRY (KINT 0) (DIRECT (POBJECT n_receiver)), ENTRY (KINT 1) (DIRECT (PSTRING $ptascii("run")))]',
        '~((HARRAY n_array) <- S.ALLOCATIONS)',
        '(HOBJECT n_receiver) <- S.ALLOCATIONS',
        'pconfigcall.KIND = INTRINSIC_INI_SET',
        'pconfigcall.NAMED',
        'pconfigcall.OWNER = eps',
        'pconfigcall.SELECTION = eps',
        'pconfigcall.SENT = [NAMED_SENT (KNOWN (POBJECT n_option)), NAMED_SENT (KNOWN (POBJECT n_rejected))]',
        'n_option =/= n_rejected',
        '$intrinsic_argument(S, pconfigcall.SITE, 1) = ((expression_option, false, preqbytes_option?, porigin_child, z_child))',
        'preqbytes_option? = ($ptascii("option"))',
        '$intrinsic_argument(S, pconfigcall.SITE, 0) = ((expression_value, false, preqbytes_value?, porigin_value, z_value))',
        'preqbytes_value? = ($ptascii("value"))',
        '$config_destination(INTRINSIC_INI_SET, preqbytes_option?, 1) = (0)',
        '$config_destination(INTRINSIC_INI_SET, preqbytes_value?, 0) = (1)',
        '$config_string_source(S, pconfigcall) = ((porigin_child, z_child))',
        '$config_string_site_valid(S, pconfigcall, n_option, porigin_child, z_child, z_call)',
        '$config_string_trace_context(S, pcallcontext_option)',
        '(HOBJECT n_option) <- $task_nodes(CONFIG_STRING_RESULT pconfigcall n_option porigin_child z_child z_call)',
        '(HOBJECT n_rejected) <- $task_nodes(CONFIG_STRING_RESULT pconfigcall n_option porigin_child z_child z_call)',
        '$trace_context(S, S.ENV, S.CURRENT) = [ptraceframe_option, ptraceframe_ini]',
        'ptraceframe_option.FUNCTION = $ptascii("__toString")',
        'ptraceframe_option.ARGS = eps',
        'ptraceframe_ini.FUNCTION = $ptascii("ini_set")',
        'ptraceframe_ini.ARGS = [(KINT 0, POBJECT n_option), (KINT 1, POBJECT n_rejected)]',
        '$outputs(S.EVENTS) = $ptascii("Owner/Child:1:x|o0z")',
        'S.FILEINCLUDEPATH = ($ptascii("mutated") ++ [0] ++ $ptascii("tail"))',
        *VALID,
        '~$config_string_site_valid(S, pconfigcall[.SITE = PORIGIN 999 eps], n_option, porigin_child, z_child, z_call)',
        '~$config_string_site_valid(S, pconfigcall[.LINE = 999], n_option, porigin_child, z_child, z_call)',
        '~$config_string_site_valid(S, pconfigcall[.SENT = [NAMED_SENT (KNOWN (POBJECT n_rejected)), NAMED_SENT (KNOWN (POBJECT n_option))]], n_option, porigin_child, z_child, z_call)',
        '~$call_descriptors_valid(S[.ALLOCATIONS = $call_remove_owner(S.ALLOCATIONS, HOBJECT n_rejected)])',
        '~$call_saved_context_valid(S, pframe_owner[.CONTEXT = (pcallcontext_owner[.RECEIVER = eps])])',
        '~$array_target_identity(S, pcalltarget, parrayselection[.NAME = $ptascii("missing")])',
        'S_result = $array_ini_result_seek(S, 100)',
        'S_result.COMPLETION = NORMAL',
        'S_result.TODO = (CONFIG_STRING_RESULT pconfigcall n_option porigin_child z_child z_call) :: ptask_owner*',
        'S_result.RESULT = KNOWN (PSTRING $ptascii("include_path"))',
        'S_result.CURRENT = (pcallcontext_owner)',
        'S_result.ORIGIN = (porigin_child)',
        'S_result.FILEINCLUDEPATH = S.FILEINCLUDEPATH',
        'S_result.EVENTS = S.EVENTS',
        '$call_descriptors_valid(S_result)',
        '$config_ini_value_conversion(POBJECT n_rejected) = TYPEREJECT',
        'S_error = $array_ini_step(S_result)',
        'S_error.COMPLETION = THROWING n_error',
        'S_error.OBJECTS[n_error] = THROWABLE pthrowable',
        'pthrowable.KIND = "TypeError"',
        'pthrowable.ORIGIN = (pconfigcall.SITE)',
        '$throwable_field(S_error, n_error, "trace") = PARRAY n_trace',
        'S_error.ARRAYS[n_trace].ITEMS = [ENTRY (KINT 0) (DIRECT (PARRAY n_trace_ini)), ENTRY (KINT 1) (DIRECT (PARRAY n_trace_owner))]',
        '$trace_array_field(S_error, n_trace_ini, $ptascii("function")) = PSTRING $ptascii("ini_set")',
        '$trace_array_field(S_error, n_trace_ini, $ptascii("args")) = PARRAY n_ini_args',
        'S_error.ARRAYS[n_ini_args].ITEMS = [ENTRY (KINT 0) (DIRECT (PSTRING $ptascii("include_path"))), ENTRY (KINT 1) (DIRECT (POBJECT n_rejected))]',
        '$trace_array_field(S_error, n_trace_owner, $ptascii("function")) = PSTRING $ptascii("run")',
        '$trace_array_field(S_error, n_trace_owner, $ptascii("class")) = PSTRING $ptascii("Owner")',
        '$trace_array_field(S_error, n_trace_owner, $ptascii("type")) = PSTRING $ptascii("->")',
        '$trace_array_field(S_error, n_trace_owner, $ptascii("args")) = PARRAY n_owner_args',
        'S_error.ARRAYS[n_owner_args].ITEMS = [ENTRY (KINT 0) (DIRECT (PSTRING $ptascii("x")))]',
        'S_error.FILEINCLUDEPATH = S.FILEINCLUDEPATH',
        'S_error.EVENTS = S.EVENTS',
        'S_done = $drive(S_error, 3000)',
        'S_done.COMPLETION = NORMAL',
        '$outputs(S_done.EVENTS) = $ptascii("Owner/Child:1:x|o0zE|1:x|K")',
        'S_done.FILEINCLUDEPATH = ($ptascii("after"))',
        '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
        '~((HOBJECT n_option) <- S_done.ALLOCATIONS)',
        '~((HOBJECT n_rejected) <- S_done.ALLOCATIONS)',
        '~((HOBJECT n_error) <- S_done.ALLOCATIONS)',
        '$call_descriptors_valid(S_done)',
        '$class_state_valid(S_done)',
        '$closure_state_valid(S_done)',
        '$heap_valid($heap_graph(S_done))',
    ],
))


def main():
    protocol.run(CASES, (Path(__file__), CATALOGUE))
    warnings.filterwarnings('ignore', category=SyntaxWarning, message='invalid escape sequence')
    import include_mutable_protocol
    include_mutable_protocol.PREFIX += INI_OPTION_PREFIX
    include_mutable_protocol.main(FILE_CASES, (Path(__file__), CATALOGUE))


if __name__ == '__main__':
    main()
