"""Independent production states for append reconstruction and real owners."""
from error_handler_protocol import PREFIX as BASE_PREFIX


PREFIX = BASE_PREFIX + r'''
dec $append_ready(pstate, porigin) : bool
def $append_ready(S, porigin) = true
  -- if S.ORIGIN = (porigin)
  -- if S.TODO = (KEY_WRITE_APPEND z false) :: ptask_tail*
def $append_ready(S, porigin) = false -- otherwise
dec $append_seek(pstate, porigin, nat) : pstate
def $append_seek(S, porigin, n) = S
  -- if $append_ready(S, porigin)
  -- if S.COMPLETION = NORMAL \/ S.COMPLETION = BUDGET
def $append_seek(S, porigin, n) = $append_seek($drive_steps(S[.COMPLETION = NORMAL], 1), porigin, $nabs($(n - 1)))
  -- if ~$append_ready(S, porigin)
  -- if S.COMPLETION = NORMAL \/ S.COMPLETION = BUDGET
  -- if $(n > 0)
def $append_seek(S, porigin, n) = S
  -- if S.COMPLETION =/= NORMAL /\ S.COMPLETION =/= BUDGET
'''


def guards(s='S'):
    return [f'$call_current_valid({s})', f'$call_frames_valid({s}, {s}.FRAMES)',
            f'$call_descriptors_valid({s})', f'$heap_valid($heap_graph({s}))']


FINISH = ['S_done.COMPLETION = NORMAL', 'S_done.TODO = eps',
          'S_done.CURRENT = eps', 'S_done.FRAMES = eps', 'S_done.HELD = eps',
          'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
          *guards('S_done')]


CASES = [
    ('append-cut-extracts-new-row-and-keeps-live-rhs',
     'intermediate-append-notice-rereads-rhs-after-root-retirement',
     'S.TODO = (ACCESS_RESUME paccess) :: ptask_tail* -- if paccess.PHASE = ACCESS_NOTICE', [
        'S.TODO = (ACCESS_RESUME paccess) :: ptask_tail*',
        'paccess.MODE = ACCESS_FETCH false false', 'paccess.PHASE = ACCESS_NOTICE',
        'paccess.INPUT = KNOWN (PSTRING $ptascii("root"))',
        'paccess.TASK = KEY_WRITE_DIM paccess.INPUT paccess.LINE false',
        'paccess.RHS = VARIABLE $ptascii("rhs304") z_rhs',
        'paccess.VALUE = PARRAY n_row', 'S.ARRAYS[n_row].ITEMS = eps',
        'paccess.OBJECT = (n_object)', 'paccess.OUTER', '~paccess.LATCH',
        '$lookup(S.ENV, $ptascii("root304")) = eps',
        '$lookup(S.ENV, $ptascii("rhs304")) = (n_rhs)',
        'S.STORE[n_rhs] = DEFINED (PINT 9)',
        '$container_writer(S.TODO) = (pkeywriter)',
        'pkeywriter.RHS = paccess.RHS',
        'pkeywriter.BASE = BASE_DIM (BASE_APPEND pbase_get z_append) (KNOWN (PSTRING $ptascii("leaf"))) z_leaf',
        '$origin_child((pkeywriter.TARGET), [PCFIELD 0]) = (porigin_append)',
        '$origin_child((porigin_append), [PCFIELD 0]) = (paccess.TARGET)',
        '$outputs(S.EVENTS) = $ptascii("G:root;N;")',
        '$task_nodes(ACCESS_RESUME paccess) = [HARRAY n_row, HOBJECT n_object]',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_object) = 1',
        '$access_valid(S, paccess)',
        '~$access_valid(S, paccess[.TASK = KEY_WRITE_APPEND paccess.LINE false][.INPUT = KNOWN PNULL])',
        '~$access_valid(S, paccess[.MODE = ACCESS_FETCH false true])',
        '~$access_valid(S, paccess[.RHS = KNOWN (PINT 4)])',
        '~$access_valid(S, paccess[.LINE = 999])',
        '~$access_valid(S, paccess[.OBJECT = eps])',
        *guards(), 'PhpStep: S ~> S_cut',
        'n_temp = |S.STORE|', 'S_cut.LOCATION = ROOT n_temp',
        'S_cut.STORE[n_temp] = DEFINED (PARRAY n_row)',
        '$container_writer(S_cut.TODO) = (pkeywriter_cut)',
        'pkeywriter_cut.BASE = BASE_DIM (BASE_APPEND (BASE_RETURNED paccess.TARGET n_temp) z_append) (KNOWN (PSTRING $ptascii("leaf"))) z_leaf',
        '$heap_owners($heap_prune($heap_graph(S_cut)), HCELL n_temp) = 1',
        '$heap_owners($heap_prune($heap_graph(S_cut)), HOBJECT n_object) = 0',
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.TODO = S_cut.TODO', 'S_budget.STORE = S_cut.STORE',
        'S_append_reached = $append_seek(S_budget[.COMPLETION = NORMAL], porigin_append, 1500)',
        r'S_append_reached.COMPLETION = NORMAL \/ S_append_reached.COMPLETION = BUDGET',
        'S_append = S_append_reached[.COMPLETION = NORMAL]',
        'S_append.TODO = (KEY_WRITE_APPEND z_append false) :: ptask_append*',
        'S_append.LOCATION = ROOT n_temp',
        'S_append.STORE[n_temp] = DEFINED (PARRAY n_row)',
        '$container_writer(S_append.TODO) = (pkeywriter_cut)',
        '$access_parent_tasks(S_append.TODO, paccess.TARGET) = (n_temp)',
        '$key_write_append_source(S_append, porigin_append, z_append)',
        '~$key_write_append_source(S_append, paccess.TARGET, paccess.LINE)',
        '$call_task_valid(S_append, KEY_WRITE_APPEND z_append false)',
        '~$call_task_valid(S_append, KEY_WRITE_APPEND 999 false)',
        '~$call_task_valid(S_append, KEY_WRITE_APPEND z_append true)',
        '~$call_task_valid(S_append[.ORIGIN = (paccess.TARGET)], KEY_WRITE_APPEND z_append false)',
        '~$access_probe(S_append, pkeywriter_cut.BASE)',
        *guards('S_append'), 'PhpStep: S_append ~> S_added',
        'n_copy = |S_append.ARRAYS|',
        'S_added.ARRAYS[n_copy].ITEMS = [ENTRY (KINT 0) UNINITIALIZED]',
        'S_added.ARRAYS[n_row].ITEMS = eps',
        'n_child = |S_append.STORE|', 'n_child =/= n_temp',
        'S_added.LOCATION = ROOT n_child', 'S_added.STORE[n_child] = UNDEFINED',
        '$container_writer(S_added.TODO) = (pkeywriter_added)',
        'pkeywriter_added.BASE = BASE_DIM (BASE_RETURNED porigin_append n_child) (KNOWN (PSTRING $ptascii("leaf"))) z_leaf',
        '$heap_owners($heap_prune($heap_graph(S_added)), HCELL n_temp) = 0',
        '$heap_owners($heap_prune($heap_graph(S_added)), HARRAY n_copy) = 0',
        '$heap_owners($heap_prune($heap_graph(S_added)), HCELL n_child) = 1',
        'S_added.EVENTS = S_append.EVENTS',
        'S_added_budget = $drive_steps(S_append, 1)', 'S_added_budget.COMPLETION = BUDGET',
        'S_added_budget.STORE = S_added.STORE', 'S_added_budget.ARRAYS = S_added.ARRAYS',
        'S_added_budget.LOCATION = S_added.LOCATION',
        *guards('S_added_budget'),
        'S_done = $drive(S_added_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("r304")) = (n_result)',
        'S_done.STORE[n_result] = DEFINED (PINT 9)',
        'S_done.STORE[n_rhs] = DEFINED (PINT 9)',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_temp) = 0',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_child) = 0',
    ]),
    ('child-append-compound-null-key-keeps-returned-object',
     'child-append-compound-uses-null-key-and-sole-returned-object',
     'S.TODO = (ACCESS_RESULT paccess) :: ptask_tail* -- if paccess.TASK = KEY_WRITE_APPEND z true -- if paccess.PHASE = ACCESS_CALL $ptascii("offsetGet")', [
        'S.TODO = (ACCESS_RESULT paccess) :: ptask_tail*',
        'paccess.TASK = KEY_WRITE_APPEND z true',
        'paccess.MODE = ACCESS_COMPOUND ADD PNULL',
        'paccess.PHASE = ACCESS_CALL $ptascii("offsetGet")',
        'paccess.INPUT = KNOWN PNULL', 'paccess.OFFSET = PNULL',
        'paccess.VALUE = PNULL', 'paccess.BASE = BASE_VALUE (KNOWN PNULL)',
        'paccess.RHS = VARIABLE $ptascii("rhs304") z_rhs',
        'paccess.SELECTED = paccess.RHS', 'paccess.OUTER', '~paccess.LATCH',
        'paccess.OBJECT = (n_child)', 'S.RESULT = KNOWN (PINT 5)',
        '$container_writer(S.TODO) = (pkeywriter)',
        'pkeywriter.BASE = BASE_APPEND (BASE_RETURNED porigin_get n_temp) z',
        'pkeywriter.TARGET = paccess.TARGET', 'pkeywriter.SITE = paccess.SITE',
        'S.STORE[n_temp] = DEFINED (POBJECT n_child)',
        '$lookup(S.ENV, $ptascii("o304")) = eps',
        '$lookup(S.ENV, $ptascii("inner304")) = eps',
        '$lookup(S.ENV, $ptascii("rhs304")) = (n_rhs)',
        'S.STORE[n_rhs] = DEFINED (PINT 17)',
        '$outputs(S.EVENTS) = $ptascii("O:1;C:N;")',
        '$task_nodes(ACCESS_RESULT paccess) = [HOBJECT n_child, HOBJECT n_child]',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_temp) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_child) = 3',
        '$access_valid(S, paccess)',
        '~$access_valid(S, paccess[.INPUT = KNOWN (PSTRING eps)])',
        '~$access_valid(S, paccess[.MODE = ACCESS_FETCH false true])',
        '~$access_valid(S, paccess[.TASK = KEY_WRITE_DIM (KNOWN PNULL) z true])',
        'paccess_bad = paccess[.TASK = KEY_WRITE_DIM (KNOWN PNULL) z true]',
        'S_bad = S[.TODO = (ACCESS_RESULT paccess_bad) :: ptask_tail*]',
        '~$access_source(S_bad, paccess_bad)',
        '~$access_valid(S_bad, paccess_bad)',
        '~$call_task_valid(S_bad, ACCESS_RESULT paccess_bad)',
        '~$call_descriptors_valid(S_bad)',
        '$heap_valid($heap_graph(S_bad))',
        '$task_nodes(ACCESS_RESULT paccess_bad) = $task_nodes(ACCESS_RESULT paccess)',
        '~$access_valid(S, paccess[.KEYLINE = 999])',
        '~$access_valid(S, paccess[.TARGET = porigin_get])',
        '~$access_valid(S, paccess[.RHS = KNOWN (PINT 11)][.SELECTED = KNOWN (PINT 11)])',
        *guards(), 'PhpStep: S ~> S_set',
        'S_set.TODO = (CALL_ARGS (METHOD_TARGET n_child porigin_set) eps 2 ([KNOWN PNULL, KNOWN (PINT 22)]) (paccess.SITE) paccess.LINE) :: (ACCESS_RESULT paccess_set) :: ptask_set*',
        'paccess_set = paccess[.MODE = ACCESS_COMPOUND ADD (PINT 5)][.VALUE = PINT 22][.OFFSET = PNULL][.PHASE = ACCESS_CALL $ptascii("offsetSet")]',
        '$access_valid(S_set, paccess_set)',
        '$heap_owners($heap_prune($heap_graph(S_set)), HOBJECT n_child) = 4',
        'S_set.STORE[n_temp] = DEFINED (POBJECT n_child)',
        'S_set.EVENTS = S.EVENTS',
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.TODO = S_set.TODO', *guards('S_budget'),
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("r304")) = (n_result)',
        'S_done.STORE[n_result] = DEFINED (PINT 22)',
        '$lookup(S_done.ENV, $ptascii("saved304")) = (n_saved)',
        'S_done.STORE[n_saved] = DEFINED (PINT 22)',
        'S_done.STORE[n_rhs] = DEFINED (PINT 17)',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_temp) = 0',
        '$heap_owners($heap_prune($heap_graph(S_done)), HOBJECT n_child) = 0',
    ]),
]


def real_cell_case(kept):
    suffix = 'kept-real-row-core-observers' if kept else 'singleton-detach-core-observers'
    source_id = 'copied-real-row-append-keeps-old-cell-after-global-rebind-genuine-globals-target-' + suffix
    before = [
        'S.TODO = (KEY_WRITE_APPEND z_append false) :: ptask_tail*',
        'S.ORIGIN = (porigin_append)', 'S.LOCATION = ROOT n_selected',
        '$container_writer(S.TODO) = (pkeywriter)',
        'pkeywriter.BASE = BASE_DIM (BASE_APPEND (BASE_RETURNED porigin_ref n_selected) z_append) (KNOWN (PSTRING $ptascii("leaf"))) z_leaf',
        'pkeywriter.RHS = VARIABLE $ptascii("rhs304") z_rhs',
        '$origin_child((pkeywriter.TARGET), [PCFIELD 0]) = (porigin_append)',
        '$origin_child((porigin_append), [PCFIELD 0]) = (porigin_ref)',
        '$lookup(S.ENV, $ptascii("data304")) = (n_data)',
        'S.STORE[n_data] = DEFINED (PARRAY n_data_array)',
        '$entry_lookup(S.ARRAYS[n_data_array].ITEMS, KSTRING $ptascii("ref")) = (ALIAS n_old)',
        'S.STORE[n_old] = DEFINED (PARRAY n_old_array)', 'n_old <- S.REFCELLS',
        'S.STORE[n_selected] = DEFINED (PARRAY n_old_array)',
        'S.ARRAYS[n_old_array].ITEMS = [ENTRY (KSTRING $ptascii("old")) (DIRECT (PINT 5))]',
        '$lookup(S.ENV, $ptascii("old304")) = (n_new)',
        '$lookup(S.ENV, $ptascii("new304")) = (n_new)',
        'n_new =/= n_old', 'S.STORE[n_new] = DEFINED (PARRAY n_new_array)',
        'S.ARRAYS[n_new_array].ITEMS = [ENTRY (KSTRING $ptascii("replace")) (DIRECT (PINT 7))]',
        '$lookup(S.ENV, $ptascii("root304")) = eps',
        '$lookup(S.ENV, $ptascii("rhs304")) = (n_rhs)',
        'S.STORE[n_rhs] = DEFINED (PINT 11)',
        '$outputs(S.EVENTS) = $ptascii("G:root;N;")',
        '$call_task_valid(S, KEY_WRITE_APPEND z_append false)',
        '$key_writer_valid(S, pkeywriter, ptask_tail*)',
        '$key_write_append_source(S, porigin_append, z_append)',
        '~$key_write_append_source(S, porigin_ref, z_append)',
        '~$call_task_valid(S, KEY_WRITE_APPEND z_append true)',
        '~$call_task_valid(S, KEY_WRITE_APPEND 999 false)',
        '~$call_task_valid(S[.ORIGIN = (porigin_ref)], KEY_WRITE_APPEND z_append false)',
        '$access_parent_tasks(S.TODO, porigin_ref) = (n_selected)',
        '(HARRAY n_old_array) <- $pools_nodes(S.POOLS)',
        '$($heap_owners($heap_prune($heap_graph(S)), HARRAY n_old_array) > 1)',
    ]
    before += ([
        'n_selected = n_old', '$lookup(S.ENV, $ptascii("keep304")) = (n_old)',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_old) = 3',
    ] if kept else [
        'n_selected =/= n_old', '~(n_selected <- S.REFCELLS)',
        '$lookup(S.ENV, $ptascii("keep304")) = eps',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_old) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_selected) = 1',
    ])
    after = [*guards(), 'PhpStep: S ~> S_added',
        'n_copy = |S.ARRAYS|',
        'S_added.ARRAYS[n_copy].ITEMS = [ENTRY (KSTRING $ptascii("old")) (DIRECT (PINT 5)), ENTRY (KINT 0) UNINITIALIZED]',
        'S_added.ARRAYS[n_old_array] = S.ARRAYS[n_old_array]',
        'S_added.STORE[n_new] = S.STORE[n_new]',
        'S_added.EVENTS = S.EVENTS',
        '$container_writer(S_added.TODO) = (pkeywriter_added)',
    ]
    after += ([
        'S_added.LOCATION = ELEMENT n_copy (KINT 0)',
        'S_added.STORE[n_old] = DEFINED (PARRAY n_copy)',
        'pkeywriter_added.BASE = BASE_DIM (BASE_PLACE porigin_append (ELEMENT n_copy (KINT 0))) (KNOWN (PSTRING $ptascii("leaf"))) z_leaf',
        '$heap_owners($heap_prune($heap_graph(S_added)), HCELL n_old) = 2',
        '$heap_owners($heap_prune($heap_graph(S_added)), HARRAY n_copy) = 1',
    ] if kept else [
        'n_child = |S.STORE|', 'S_added.LOCATION = ROOT n_child',
        'S_added.STORE[n_child] = UNDEFINED',
        'S_added.STORE[n_old] = S.STORE[n_old]',
        'pkeywriter_added.BASE = BASE_DIM (BASE_RETURNED porigin_append n_child) (KNOWN (PSTRING $ptascii("leaf"))) z_leaf',
        '$heap_owners($heap_prune($heap_graph(S_added)), HCELL n_selected) = 0',
        '$heap_owners($heap_prune($heap_graph(S_added)), HARRAY n_copy) = 0',
        '$heap_owners($heap_prune($heap_graph(S_added)), HCELL n_child) = 1',
    ])
    after += [
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.TODO = S_added.TODO', 'S_budget.STORE = S_added.STORE',
        'S_budget.ARRAYS = S_added.ARRAYS', 'S_budget.LOCATION = S_added.LOCATION',
        *guards('S_budget'), 'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
        *FINISH, '$lookup(S_done.ENV, $ptascii("r304")) = (n_result)',
        'S_done.STORE[n_result] = DEFINED (PINT 11)',
        'S_done.STORE[n_new] = S.STORE[n_new]',
        '$entry_lookup(S_done.ARRAYS[n_data_array].ITEMS, KSTRING $ptascii("ref")) = (ALIAS n_old)',
    ]
    after += ([
        'S_done.STORE[n_old] = DEFINED (PARRAY n_copy)',
        '$entry_lookup(S_done.ARRAYS[n_copy].ITEMS, KINT 0) = (DIRECT (PARRAY n_leaf_array))',
        '$entry_lookup(S_done.ARRAYS[n_leaf_array].ITEMS, KSTRING $ptascii("leaf")) = (DIRECT (PINT 11))',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_old) = 2',
    ] if kept else [
        'S_done.STORE[n_old] = S.STORE[n_old]',
        '$entry_lookup(S_done.ARRAYS[n_old_array].ITEMS, KINT 0) = eps',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_old) = 1',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_selected) = 0',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_child) = 0',
    ])
    return ('append-retains-real-reference-cell' if kept else 'append-separates-singleton-reference-cell',
        source_id, 'S.TODO = (KEY_WRITE_APPEND z false) :: ptask_tail*', before + after)


CASES += [real_cell_case(False), real_cell_case(True)]


CASES.append((
    'append-pending-zero-replacement-keeps-real-table-and-chain',
    'append-false-divzero-replaces-pending-deprecated-with-full-chain',
    'S.TODO = (THROW_SEARCH n_error) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail* -- if perrorcall.RESUME = CONTAINER_WRITE_RESULT pcontainerwrite -- if pcontainerwrite.PHASE = CONTAINER_FALSE n', [
        'S.TODO = (THROW_SEARCH n_error) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = CONTAINER_WRITE_RESULT pcontainerwrite',
        'perrorcall.LEVEL = 8192', 'perrorcall.LINE = 19',
        'perrorcall.CALLBACK = POBJECT n_handler',
        'S.ERRORHANDLER.CALLBACK = eps',
        'pcontainerwrite.INPUT = KNOWN PNULL',
        'pcontainerwrite.PHASE = CONTAINER_FALSE n_array',
        'pcontainerwrite.KIND = CONTAINER_COMPOUND', 'pcontainerwrite.RW',
        'pcontainerwrite.BINDING = eps', 'pcontainerwrite.PLACE = ROOT n_temp',
        'pcontainerwrite.LINE = 19', 'S.ORIGIN = (pcontainerwrite.SITE)',
        'pcontainerwrite.WRITER = pkeywriter',
        'pkeywriter.TASK = COMPOUND_APPLY DIVIDE pbase false 19',
        'pkeywriter.RHS = KNOWN (PINT 0)',
        'pkeywriter.BASE = BASE_APPEND (BASE_RETURNED porigin_get n_temp) 19',
        'S.STORE[n_temp] = DEFINED (PARRAY n_array)',
        '~(n_temp <- S.REFCELLS)', 'S.ARRAYS[n_array].ITEMS = eps',
        '~((HARRAY n_array) <- $pools_nodes(S.POOLS))',
        '$lookup(S.ENV, $ptascii("root304")) = eps',
        '$lookup(S.ENV, $ptascii("r304")) = eps',
        '$outputs(S.EVENTS) = $ptascii("G:root;H:8:19;H:8192:19;")',
        '$task_nodes(CONTAINER_WRITE_RESULT pcontainerwrite) = [HARRAY n_array]',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_array) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_temp) = 1',
        '$throwable_field(S, n_error, "message") = PSTRING $ptascii("deprecated304")',
        '$throwable_field(S, n_error, "line") = PINT 13',
        '$throwable_field(S, n_error, "previous") = POBJECT n_older',
        '$throwable_field(S, n_older, "message") = PSTRING $ptascii("older304")',
        '$throwable_field(S, n_older, "previous") = PNULL',
        '$container_valid(S, pcontainerwrite)', '$error_call_valid(S, perrorcall)',
        '~$container_valid(S, pcontainerwrite[.PLACE = ROOT (|S.STORE|)])',
        '~$container_valid(S, pcontainerwrite[.PLACE = ELEMENT (|S.ARRAYS|) (KINT 0)])',
        '~$container_valid(S, pcontainerwrite[.PLACE = NOWHERE])',
        '~$container_valid(S, pcontainerwrite[.LINE = 13])',
        '~$container_valid(S, pcontainerwrite[.INPUT = KNOWN (PSTRING eps)])',
        '~$container_valid(S, pcontainerwrite[.KIND = CONTAINER_FETCH])',
        '~$container_valid(S, pcontainerwrite[.RW = false])',
        '~$container_valid(S, pcontainerwrite[.PHASE = CONTAINER_FALSE (|S.ARRAYS|)])',
        '~$error_call_valid(S, perrorcall[.LINE = 13])',
        '~$error_call_valid(S, perrorcall[.LEVEL = 8])',
        *guards(), 'PhpStep: S ~> S_replaced',
        'n_new = |S.OBJECTS|', 'n_new =/= n_error',
        'S_replaced.TODO = (THROW_SEARCH n_new) :: ptask_tail*',
        'S_replaced.COMPLETION = NORMAL',
        'S_replaced.ARRAYS[n_array].ITEMS = [ENTRY (KINT 0) (DIRECT PNULL)]',
        'S_replaced.STORE[n_temp] = S.STORE[n_temp]',
        '$throwable_field(S_replaced, n_new, "message") = PSTRING $ptascii("Division by zero")',
        '$throwable_field(S_replaced, n_new, "line") = PINT 19',
        '$throwable_field(S_replaced, n_new, "file") = PSTRING $call_sourcefile(S.FILES, pkeywriter.SITE)',
        '$throwable_field(S_replaced, n_new, "previous") = POBJECT n_error',
        '$throwable_field(S_replaced, n_error, "previous") = POBJECT n_older',
        'S_replaced.EVENTS = S.EVENTS',
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.TODO = S_replaced.TODO', 'S_budget.STORE = S_replaced.STORE',
        'S_budget.ARRAYS = S_replaced.ARRAYS',
        '|S_budget.DESTRUCTION.HANDLES| = |S_budget.OBJECTS|',
        '(HOBJECT n_new) <- S_budget.ALLOCATIONS', *guards('S_budget'),
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("e304")) = (n_catch)',
        'S_done.STORE[n_catch] = DEFINED (POBJECT n_new)',
        '$throwable_field(S_done, n_new, "previous") = POBJECT n_error',
        '$throwable_field(S_done, n_error, "previous") = POBJECT n_older',
        '$throwable_field(S_done, n_older, "previous") = PNULL',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_temp) = 0',
        '$heap_owners($heap_prune($heap_graph(S_done)), HARRAY n_array) = 0',
        '$lookup(S_done.ENV, $ptascii("r304")) = eps',
    ]))


CASES.append((
    'ordinary-pending-append-writes-live-rhs-and-preserves-primary',
    'ordinary-false-pending-append-stores-late-rhs',
    'S.TODO = (THROW_SEARCH n_error) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail* -- if perrorcall.RESUME = CONTAINER_WRITE_RESULT pcontainerwrite -- if pcontainerwrite.PHASE = CONTAINER_FALSE n', [
        'S.TODO = (THROW_SEARCH n_error) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = CONTAINER_WRITE_RESULT pcontainerwrite',
        'perrorcall.LEVEL = 8192', 'perrorcall.LINE = 10',
        'perrorcall.CALLBACK = POBJECT n_handler',
        'S.ERRORHANDLER.CALLBACK = eps',
        'pcontainerwrite.INPUT = KNOWN PNULL',
        'pcontainerwrite.PHASE = CONTAINER_FALSE n_array',
        'pcontainerwrite.KIND = CONTAINER_COMPOUND', 'pcontainerwrite.RW',
        'pcontainerwrite.BINDING = ($ptascii("row304"))',
        'pcontainerwrite.PLACE = ROOT n_row',
        'pcontainerwrite.LINE = 10', 'S.ORIGIN = (pcontainerwrite.SITE)',
        'pcontainerwrite.WRITER = pkeywriter',
        'pkeywriter.TASK = COMPOUND_APPLY ADD pbase false 10',
        'pkeywriter.RHS = VARIABLE $ptascii("rhs304") 10',
        'pkeywriter.BASE = BASE_APPEND (BASE_VALUE (VARIABLE $ptascii("row304") 10)) 10',
        '$lookup(S.ENV, $ptascii("row304")) = (n_row)',
        'S.STORE[n_row] = DEFINED (PARRAY n_array)',
        '~(n_row <- S.REFCELLS)', 'S.ARRAYS[n_array].ITEMS = eps',
        '~((HARRAY n_array) <- $pools_nodes(S.POOLS))',
        '$lookup(S.ENV, $ptascii("rhs304")) = (n_rhs)',
        'S.STORE[n_rhs] = DEFINED (PINT 13)',
        '$lookup(S.ENV, $ptascii("result304")) = eps',
        '$outputs(S.EVENTS) = $ptascii("H:8192;")',
        '$task_nodes(CONTAINER_WRITE_RESULT pcontainerwrite) = [HARRAY n_array]',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_array) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_row) = 1',
        '$throwable_field(S, n_error, "message") = PSTRING $ptascii("pending304")',
        '$throwable_field(S, n_error, "line") = PINT 8',
        '$throwable_field(S, n_error, "previous") = PNULL',
        '$container_valid(S, pcontainerwrite)', '$error_call_valid(S, perrorcall)',
        '~$container_valid(S, pcontainerwrite[.PLACE = ROOT (|S.STORE|)])',
        '~$container_valid(S, pcontainerwrite[.PLACE = ELEMENT (|S.ARRAYS|) (KINT 0)])',
        '~$container_valid(S, pcontainerwrite[.PLACE = NOWHERE])',
        '~$container_valid(S, pcontainerwrite[.BINDING = ($ptascii("rhs304"))])',
        '~$container_valid(S, pcontainerwrite[.LINE = 8])',
        '~$container_valid(S, pcontainerwrite[.RW = false])',
        '~$container_valid(S, pcontainerwrite[.WRITER = pkeywriter[.RHS = KNOWN (PINT 7)]])',
        '~$container_valid(S, pcontainerwrite[.PHASE = CONTAINER_FALSE (|S.ARRAYS|)])',
        '~$error_call_valid(S, perrorcall[.LINE = 8])',
        '~$error_call_valid(S, perrorcall[.LEVEL = 8])',
        *guards(), 'PhpStep: S ~> S_written',
        'S_written.TODO = (THROW_SEARCH n_error) :: ptask_tail*',
        'S_written.COMPLETION = NORMAL',
        'S_written.ARRAYS[n_array].ITEMS = [ENTRY (KINT 0) (DIRECT (PINT 13))]',
        'S_written.STORE[n_row] = S.STORE[n_row]',
        'S_written.STORE[n_rhs] = S.STORE[n_rhs]',
        'S_written.OBJECTS = S.OBJECTS', 'S_written.EVENTS = S.EVENTS',
        'S_written.ERRORHANDLER.CALLBACK = (perrorcall.CALLBACK)',
        'S_written.REPORTING = S.REPORTING', 'S_written.HELD = S.HELD',
        '$heap_owners($heap_prune($heap_graph(S_written)), HARRAY n_array) = 1',
        '$heap_owners($heap_prune($heap_graph(S_written)), HCELL n_row) = 1',
        '$throwable_field(S_written, n_error, "previous") = PNULL',
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.TODO = S_written.TODO', 'S_budget.STORE = S_written.STORE',
        'S_budget.ARRAYS = S_written.ARRAYS', 'S_budget.ERRORHANDLER = S_written.ERRORHANDLER',
        *guards('S_budget'),
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("row304")) = (n_row)',
        'S_done.STORE[n_row] = DEFINED (PARRAY n_array)',
        'S_done.ARRAYS[n_array].ITEMS = [ENTRY (KINT 0) (DIRECT (PINT 13))]',
        'S_done.STORE[n_rhs] = DEFINED (PINT 13)',
        '$lookup(S_done.ENV, $ptascii("result304")) = eps',
        '$lookup(S_done.ENV, $ptascii("error304")) = (n_catch)',
        'S_done.STORE[n_catch] = DEFINED (POBJECT n_error)',
        '$throwable_field(S_done, n_error, "line") = PINT 8',
        '$throwable_field(S_done, n_error, "previous") = PNULL',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_row) = 1',
        '$heap_owners($heap_prune($heap_graph(S_done)), HARRAY n_array) = 1',
    ]))
