"""Independent source-reached Set pointers, warning latches and source forms."""
from error_handler_protocol import PREFIX


def guards(s='S'):
    return [f'$call_current_valid({s})', f'$call_frames_valid({s}, {s}.FRAMES)',
            f'$call_descriptors_valid({s})', f'$heap_valid($heap_graph({s}))']


FINISH = ['S_done.COMPLETION = NORMAL', 'S_done.TODO = eps',
          'S_done.CURRENT = eps', 'S_done.FRAMES = eps', 'S_done.HELD = eps',
          *guards('S_done')]


CASES = [
    ('returned-simple-append-readback-keeps-old-reference-cell',
     'returned-child-simple-append-keeps-old-rhs-reference-cell',
     'S.TODO = (ACCESS_RESULT paccess) :: ptask_tail* -- if paccess.MODE = ACCESS_SET -- if paccess.PHASE = ACCESS_CALL $ptascii("offsetSet")', [
        'S.TODO = (ACCESS_RESULT paccess) :: ptask_tail*',
        'paccess.MODE = ACCESS_SET', 'paccess.PHASE = ACCESS_CALL $ptascii("offsetSet")',
        'paccess.TASK = KEY_WRITE_FINISH pkeywriter',
        'pkeywriter.TASK = ASSIGN_ARRAY (BASE_APPEND pbase_original z_prefix) paccess.LINE b_self',
        'pkeywriter.BASE = BASE_RETURNED porigin_prefix n_temp',
        'pkeywriter.TARGET = porigin_prefix', 'porigin_prefix =/= paccess.TARGET',
        'paccess.BASE = pkeywriter.BASE', 'paccess.INPUT = KNOWN PNULL',
        'paccess.KEYLINE = paccess.LINE', 'paccess.OFFSET = PNULL',
        'paccess.VALUE = PINT 17', 'paccess.SELECTED = REFERENCE n_old',
        'paccess.RHS = VARIABLE $ptascii("rhs309") z_rhs',
        'paccess.OUTER', '~paccess.LATCH', 'paccess.OBJECT = (n_child)',
        'S.STORE[n_temp] = DEFINED (POBJECT n_child)',
        '$container_writer(ptask_tail*) = eps',
        '$lookup(S.ENV, $ptascii("outer309")) = eps',
        '$lookup(S.ENV, $ptascii("child309")) = eps',
        '$lookup(S.ENV, $ptascii("alias309")) = (n_old)',
        'S.STORE[n_old] = DEFINED (PINT 25)',
        '$lookup(S.ENV, $ptascii("rhs309")) = (n_new)',
        '$lookup(S.ENV, $ptascii("new309")) = (n_new)',
        'n_new =/= n_old', 'S.STORE[n_new] = DEFINED (PINT 31)',
        '$access_valid(S, paccess)', '$access_finish_task(paccess.TASK)',
        '$key_write_append_source(S, paccess.TARGET, paccess.LINE)',
        '~$key_write_append_source(S, porigin_prefix, paccess.LINE)',
        '$task_nodes(ACCESS_RESULT paccess) = [HCELL n_temp, HOBJECT n_child, HOBJECT n_child]',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_temp) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_child) = 3',
        '~$access_valid(S, paccess[.TARGET = porigin_prefix])',
        'pkeywriter_dim = pkeywriter[.TASK = ASSIGN_ARRAY (BASE_DIM pbase_original (KNOWN PNULL) z_prefix) paccess.LINE b_self]',
        '~$access_valid(S, paccess[.TASK = KEY_WRITE_FINISH pkeywriter_dim])',
        '~$access_valid(S, paccess[.INPUT = KNOWN (PINT 0)][.OFFSET = PINT 0])',
        '~$access_valid(S, paccess[.LINE = 999][.KEYLINE = 999])',
        '~$access_valid(S, paccess[.SITE = PORIGIN 999 eps])',
        '~$access_valid(S, paccess[.MODE = ACCESS_FETCH false false])',
        '~$access_valid(S, paccess[.BASE = BASE_VALUE (KNOWN PNULL)])',
        '~$access_valid(S, paccess[.OBJECT = eps])',
        'S_bad = S[.TODO = (ACCESS_RESULT paccess[.TARGET = porigin_prefix]) :: ptask_tail*]',
        '$heap_valid($heap_graph(S_bad))', '~$call_descriptors_valid(S_bad)',
        *guards(), 'PhpStep: S ~> S_raw', 'S_raw.RESULT = KNOWN (PINT 25)',
        'S_raw.TODO = ptask_tail*',
        '$heap_owners($heap_prune($heap_graph(S_raw)), HCELL n_temp) = 0',
        '$heap_owners($heap_prune($heap_graph(S_raw)), HOBJECT n_child) = 0',
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.RESULT = S_raw.RESULT', 'S_budget.TODO = S_raw.TODO',
        *guards('S_budget'),
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("r309")) = (n_result)',
        'S_done.STORE[n_result] = DEFINED (PINT 25)',
        '$lookup(S_done.ENV, $ptascii("saved309")) = (n_saved)',
        'S_done.STORE[n_saved] = DEFINED (PINT 17)',
    ]),
    ('returned-simple-append-warning-keeps-null-and-original-child',
     'returned-child-simple-append-missing-rhs-latches-null-and-selected-child',
     'S.TODO = (ACCESS_RESUME paccess) :: ptask_tail* -- if paccess.MODE = ACCESS_SET -- if paccess.PHASE = ACCESS_VALUE_CV $ptascii("rhs309")', [
        'S.TODO = (ACCESS_RESUME paccess) :: ptask_tail*',
        'paccess.MODE = ACCESS_SET', 'paccess.PHASE = ACCESS_VALUE_CV $ptascii("rhs309")',
        'paccess.TASK = KEY_WRITE_FINISH pkeywriter',
        'pkeywriter.BASE = BASE_RETURNED porigin_prefix n_temp',
        'paccess.BASE = pkeywriter.BASE', 'paccess.INPUT = KNOWN PNULL',
        'paccess.RHS = VARIABLE $ptascii("rhs309") z_rhs',
        'paccess.SELECTED = KNOWN PNULL', 'paccess.VALUE = PNULL',
        'paccess.OFFSET = PNULL', 'paccess.OUTER', '~paccess.LATCH',
        'paccess.OBJECT = (n_child)', 'S.STORE[n_temp] = DEFINED (POBJECT n_child)',
        '$lookup(S.ENV, $ptascii("rhs309")) = (n_rhs)',
        'S.STORE[n_rhs] = DEFINED (PINT 23)',
        '$lookup(S.ENV, $ptascii("child309")) = (n_replacement)',
        'S.STORE[n_replacement] = DEFINED (POBJECT n_new_child)',
        'n_new_child =/= n_child', '$lookup(S.ENV, $ptascii("outer309")) = eps',
        '$container_writer(ptask_tail*) = eps', '$access_valid(S, paccess)',
        '$task_nodes(ACCESS_RESUME paccess) = [HCELL n_temp, HOBJECT n_child]',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_child) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HOBJECT n_new_child) = 1',
        '~$access_valid(S, paccess[.SELECTED = paccess.RHS])',
        '~$access_valid(S, paccess[.VALUE = PINT 23])',
        '~$access_valid(S, paccess[.PHASE = ACCESS_KEY_CV $ptascii("rhs309")])',
        '~$access_valid(S, paccess[.INPUT = KNOWN (PINT 0)])',
        'S_bad = S[.TODO = (ACCESS_RESUME paccess[.VALUE = PINT 23]) :: ptask_tail*]',
        '$heap_valid($heap_graph(S_bad))', '~$call_descriptors_valid(S_bad)',
        *guards(), 'PhpStep: S ~> S_call',
        'S_call.TODO = (CALL_ARGS (METHOD_TARGET n_child porigin_set) eps 2 ([KNOWN PNULL, KNOWN PNULL]) (paccess.SITE) paccess.LINE) :: (ACCESS_RESULT paccess_call) :: ptask_tail*',
        'paccess_call = paccess[.PHASE = ACCESS_CALL $ptascii("offsetSet")]',
        '$access_valid(S_call, paccess_call)', *guards('S_call'),
        'S_budget = $drive_steps(S, 1)', 'S_budget.COMPLETION = BUDGET',
        'S_budget.TODO = S_call.TODO', *guards('S_budget'),
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("r309")) = (n_result)',
        'S_done.STORE[n_result] = DEFINED PNULL',
        '$lookup(S_done.ENV, $ptascii("saved309")) = (n_saved)',
        'S_done.STORE[n_saved] = DEFINED PNULL',
        '$lookup(S_done.ENV, $ptascii("rhs309")) = (n_rhs_done)',
        'S_done.STORE[n_rhs_done] = DEFINED (PINT 41)',
        '$heap_owners($heap_prune($heap_graph(S_done)), HOBJECT n_child) = 0',
        '$heap_owners($heap_prune($heap_graph(S_done)), HOBJECT n_new_child) = 1',
    ]),
]
