#!/usr/bin/env python3
"""Source-reached certificates for cached and terminal handler API consumers."""
import argparse
import json
from pathlib import Path

import shutdown_state_review as runner

SOURCES = {row['id']: row['source'] for row in json.loads(
    Path(__file__).with_name('callback_api_review_cases.json').read_text())}
VALID = runner.VALID
DONE = runner.DONE

runner.CASES = {
    'cached-live-leaf-after-registration-warning': {
        'source': SOURCES['shutdown-compound-live-method-warning'],
        'stage': 'S.TODO = [SHUTDOWN_SEND 0 0 eps]',
        'checks': [
            'pshutdownentry = S.SHUTDOWN.ENTRIES[0]',
            'pshutdownentry.TARGET = API_METHOD_TARGET papiquery porigin_method ptbytes true',
            'papiquery.SOURCE = CONFIG_INVOKE pshutdownentry.CALL',
            'papiquery.INPUT = PSTRING $ptascii("B")',
            'papiquery.ORIGINAL = $ptascii("A::h")',
            'papiquery.METHOD = DIRECT (PSTRING $ptascii("Q::k"))',
            'papiquery.PREFIX = 3 /\\ papiquery.WIDTH = 1',
            'ptbytes = $ptascii("k")',
            'papiquery.SCOPE = eps /\\ papiquery.CALLED = eps /\\ papiquery.THIS = eps',
            'papiquery.OUTER = (papiclass_outer)',
            'papiquery.VALUE = PARRAY n_raw',
            '~((HARRAY n_raw) <- S.ALLOCATIONS)',
            'pshutdownentry.ARGS = [PSTRING $ptascii("x")]',
            '$target_nodes(pshutdownentry.TARGET) = eps',
            '$shutdown_roots(S.SHUTDOWN.ENTRIES) = eps',
            '$consumer_shutdown_scope(S, papiquery, pshutdownentry)',
            '$consumer_method_valid(S, papiquery, porigin_method, ptbytes)',
            '$api_carrier_valid(S, papiquery, porigin_method, ptbytes, true)',
            '$shutdown_entry_valid(S, pshutdownentry)',
            '~$consumer_method_valid(S, papiquery, porigin_method, $ptascii("h"))',
            '~$consumer_method_valid(S, papiquery[.CLASS = papiclass_outer], porigin_method, ptbytes)',
            '~$consumer_method_valid(S, papiquery[.WIDTH = 0], porigin_method, ptbytes)',
            '~$consumer_shutdown_scope(S, papiquery[.SCOPE = (papiquery.CLASS.REQUESTED)], pshutdownentry)',
            '~$consumer_shutdown_scope(S, papiquery[.CALLED = (papiquery.CLASS.REQUESTED)], pshutdownentry)',
            '~$consumer_shutdown_scope(S, papiquery[.LINE = 0], pshutdownentry)',
            '~$shutdown_entry_valid(S, pshutdownentry[.RAW = ($array_empty())])',
            '~$shutdown_entry_valid(S, pshutdownentry[.ARGS = [PNULL]])',
            '~$call_task_valid(S, SHUTDOWN_SEND 1 0 eps)',
            '$call_task_valid(S, SHUTDOWN_SEND 0 0 eps)',
            *VALID,
            'S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
            'S_paused.SHUTDOWN = S.SHUTDOWN',
            'S_done = $drive(S, 2000)', 'S_done.COMPLETION = NORMAL', *DONE,
            '$drive(S_paused[.COMPLETION = NORMAL], 2000) = S_done',
        ],
    },
    'cached-private-receiver-after-alias-retirement': {
        'source': SOURCES['shutdown-compound-receiver-alias-retirement'],
        'stage': 'S.TODO = [SHUTDOWN_SEND 0 0 eps]',
        'checks': [
            'pshutdownentry = S.SHUTDOWN.ENTRIES[0]',
            'pshutdownentry.TARGET = API_METHOD_TARGET papiquery porigin_method ptbytes false',
            'papiquery.INPUT = POBJECT n_receiver',
            'papiquery.THIS = (n_receiver)',
            'papiquery.CLASS.RECEIVER = (n_receiver)',
            'papiquery.CALLED = (papiquery.CLASS.CALLED)',
            'papiquery.VALUE = PARRAY n_raw',
            '~((HARRAY n_raw) <- S.ALLOCATIONS)',
            '$target_nodes(pshutdownentry.TARGET) = [HOBJECT n_receiver]',
            '$shutdown_roots(S.SHUTDOWN.ENTRIES) = [HOBJECT n_receiver]',
            '$heap_owners($heap_graph(S), HOBJECT n_receiver) = 1',
            '$consumer_shutdown_scope(S, papiquery, pshutdownentry)',
            '$api_carrier_valid(S, papiquery, porigin_method, ptbytes, false)',
            '$shutdown_entry_valid(S, pshutdownentry)',
            '~$consumer_shutdown_scope(S, papiquery[.SCOPE = eps], pshutdownentry)',
            '~$consumer_shutdown_scope(S, papiquery[.CALLED = eps], pshutdownentry)',
            '~$consumer_shutdown_scope(S, papiquery[.THIS = eps], pshutdownentry)',
            '~$consumer_shutdown_scope(S, papiquery[.THIS = (|S.OBJECTS|)], pshutdownentry)',
            '~$consumer_shutdown_scope(S, papiquery[.SOURCE = CONFIG_INVOKE pshutdownentry.CALL[.KIND = INTRINSIC_SET_EXCEPTION_HANDLER]], pshutdownentry)',
            *VALID,
            'S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
            'S_paused.ALLOCATIONS = S.ALLOCATIONS',
            'S_done = $drive(S, 2000)', 'S_done.COMPLETION = NORMAL', *DONE,
            '$drive(S_paused[.COMPLETION = NORMAL], 2000) = S_done',
            '$heap_owners($heap_graph(S_done), HOBJECT n_receiver) = 1',
        ],
    },
    'terminal-selector-after-stack-restore': {
        'source': SOURCES['exception-compound-terminal-pop-original'],
        'stage': 'S.TODO = (API_CALLABLE_RESULT papiquery 1) :: ptask_tail* -- if '
                 '$consumer_exception_source(papiquery.SOURCE)',
        'checks': [
            'papiquery.SOURCE = EXCEPTION_HANDLER_INVOKE pexceptioncall',
            'S.CURRENT = eps', 'S.FRAMES = eps', 'S.CONSTCONTEXT = eps',
            'S.ORIGIN = (papiquery.CLASS.REQUESTED)',
            'S.EXCEPTIONHANDLER = (pexceptioncall.CALLBACK)',
            'pexceptioncall.TARGET = eps', 'pexceptioncall.SENT = eps',
            'pexceptioncall.RECEIVED = eps',
            'papiquery.VALUE = pexceptioncall.CALLBACK',
            'papiquery.LINE = 0',
            'papiquery.SCOPE = eps /\\ papiquery.CALLED = eps /\\ papiquery.THIS = eps',
            '$consumer_exception_pending(S, pexceptioncall)',
            '$consumer_exception_original(S, papiquery)',
            '~$exception_invoke_valid(S, pexceptioncall)',
            '$api_query_valid(S, papiquery, 1)',
            '$task_nodes(API_CALLABLE_RESULT papiquery 1) = [HOBJECT pexceptioncall.OBJECT]',
            '$heap_owners($heap_graph(S), HOBJECT pexceptioncall.OBJECT) = 1',
            '~$api_query_valid(S, papiquery[.SOURCE = EXCEPTION_HANDLER_INVOKE pexceptioncall[.RAW = ($array_empty())]], 1)',
            '~$api_query_valid(S, papiquery[.SOURCE = EXCEPTION_HANDLER_INVOKE pexceptioncall[.OBJECT = |S.OBJECTS|]], 1)',
            '~$api_query_valid(S, papiquery[.SCOPE = (papiquery.CLASS.REQUESTED)], 1)',
            '~$api_query_valid(S, papiquery[.CALLED = (papiquery.CLASS.REQUESTED)], 1)',
            '~$api_query_valid(S, papiquery[.LINE = 1], 1)',
            '~$api_query_valid(S[.ORIGIN = eps], papiquery, 1)',
            '~$api_query_valid(S[.CONSTCONTEXT = ({ORIGIN papiquery.CLASS.REQUESTED, LINE 0, FACTS eps})], papiquery, 1)',
            *VALID,
            'S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
            'S_paused.TODO = S.TODO', 'S_paused.ALLOCATIONS = S.ALLOCATIONS',
            'S_done = $drive(S, 2000)', 'S_done.COMPLETION = NORMAL', *DONE,
            '$drive(S_paused[.COMPLETION = NORMAL], 2000) = S_done',
            '~((HOBJECT pexceptioncall.OBJECT) <- S_done.ALLOCATIONS)',
        ],
    },
    'entered-terminal-api-marker': {
        'source': SOURCES['exception-compound-register-and-late'],
        'stage': 'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* -- if '
                 'pargcall.KIND = INTRINSIC_FUNC_NUM_ARGS -- if S.CURRENT = (pcallcontext) -- if '
                 '$exception_context_kind(S, pcallcontext)',
        'checks': [
            'S.CURRENT = (pcallcontext)',
            'S.FRAMES = [pframe]',
            'pframe.TODO = (EXCEPTION_HANDLER_RESULT pexceptioncall) :: ptask_saved*',
            'pcallcontext.TARGET = API_METHOD_TARGET papiquery porigin_method ptbytes true',
            'pexceptioncall.TARGET = (pcallcontext.TARGET)',
            'papiquery.SOURCE = EXCEPTION_HANDLER_INVOKE pexceptioncall_original',
            'pexceptioncall_original.OBJECT = pexceptioncall.OBJECT',
            'pcallcontext.ARGC = 1', 'pcallcontext.EXTRA = eps',
            'pcallcontext.CALLSITE = eps', 'pcallcontext.LINE = $(-1)',
            'pcallcontext.HOLES = eps', 'pcallcontext.WRAPPER = eps',
            'pframe.CONTEXT = eps', 'pframe.LOCALS = eps',
            'pframe.ORIGIN = eps', 'pframe.CONSTCONTEXT = eps',
            '$exception_result_valid(S, pexceptioncall)',
            '$exception_context_valid(S, pcallcontext)',
            '$task_nodes(EXCEPTION_HANDLER_RESULT pexceptioncall) = [HOBJECT pexceptioncall.OBJECT]',
            '~$exception_result_valid(S, pexceptioncall[.RAW = ($array_empty())])',
            '~$exception_result_valid(S, pexceptioncall[.SENT = (KNOWN PNULL)])',
            '~$exception_context_valid(S, pcallcontext[.ARGC = 0])',
            '~$exception_context_valid(S, pcallcontext[.EXTRA = [KNOWN PNULL]])',
            '~$exception_context_valid(S, pcallcontext[.CALLSITE = (pcallcontext.FUNCTION)])',
            '~$exception_context_valid(S, pcallcontext[.HOLES = [0]])',
            '~$exception_context_valid(S[.FRAMES = [pframe[.ORIGIN = (pcallcontext.FUNCTION)]]], pcallcontext)',
            '~$exception_context_valid(S[.FRAMES = [pframe[.CONSTCONTEXT = ({ORIGIN pcallcontext.FUNCTION, LINE 0, FACTS eps})]]], pcallcontext)',
            *VALID,
            'S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
            'S_done = $drive(S, 2000)', 'S_done.COMPLETION = NORMAL', *DONE,
            '$drive(S_paused[.COMPLETION = NORMAL], 2000) = S_done',
            '~((HOBJECT pexceptioncall.OBJECT) <- S_done.ALLOCATIONS)',
        ],
    },
    'retired-intrinsic-api-and-static-shutdown-selector': {
        'source': SOURCES['shutdown-compound-retired-intrinsic-api-and-static-selector'],
        'stage': 'S.TODO = [SHUTDOWN_SEND 0 0 eps]',
        'checks': [
            'pshutdownentry = S.SHUTDOWN.ENTRIES[0]',
            'pshutdownentry.TARGET = API_METHOD_TARGET papiquery porigin_method ptbytes true',
            'papiquery.INPUT = POBJECT n_selector',
            'papiquery.THIS = (n_selector)',
            'papiquery.CLASS.RECEIVER = (n_selector)',
            'pshutdownentry.CALL.OWNER = (n_api)',
            'pshutdownentry.CALL.SENT = [NAMED_SENT (KNOWN (PARRAY n_raw)), NAMED_SENT (KNOWN (POBJECT n_arg))]',
            'pshutdownentry.ARGS = [POBJECT n_arg]',
            '~((HOBJECT n_api) <- S.ALLOCATIONS)',
            '~((HOBJECT n_selector) <- S.ALLOCATIONS)',
            '~((HARRAY n_raw) <- S.ALLOCATIONS)',
            '$target_nodes(pshutdownentry.TARGET) = eps',
            '$shutdown_roots(S.SHUTDOWN.ENTRIES) = [HOBJECT n_arg]',
            '$heap_owners($heap_graph(S), HOBJECT n_arg) = 1',
            '$shutdown_registration_valid(S, pshutdownentry.CALL)',
            '$consumer_shutdown_scope(S, papiquery, pshutdownentry)',
            '$api_carrier_valid(S, papiquery, porigin_method, ptbytes, true)',
            '$shutdown_entry_valid(S, pshutdownentry)',
            '~$shutdown_registration_valid(S, pshutdownentry.CALL[.OWNER = (n_arg)])',
            '~$consumer_shutdown_scope(S, papiquery[.THIS = eps], pshutdownentry)',
            '~$consumer_shutdown_scope(S, papiquery[.SCOPE = eps], pshutdownentry)',
            *VALID,
            'S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
            'S_paused.ALLOCATIONS = S.ALLOCATIONS',
            'S_done = $drive(S, 2000)', 'S_done.COMPLETION = NORMAL', *DONE,
            '$drive(S_paused[.COMPLETION = NORMAL], 2000) = S_done',
            '$heap_owners($heap_graph(S_done), HOBJECT n_arg) = 1',
            '~((HOBJECT n_selector) <- S_done.ALLOCATIONS)',
        ],
    },
    'retired-terminal-static-selector': {
        'source': SOURCES['exception-compound-retired-api-and-static-selector'],
        'stage': 'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* -- if '
                 'pargcall.KIND = INTRINSIC_FUNC_NUM_ARGS -- if S.CURRENT = (pcallcontext) -- if '
                 '$exception_context_kind(S, pcallcontext)',
        'checks': [
            'S.CURRENT = (pcallcontext)',
            'S.FRAMES = [pframe]',
            'pframe.TODO = (EXCEPTION_HANDLER_RESULT pexceptioncall) :: ptask_saved*',
            'pcallcontext.TARGET = API_METHOD_TARGET papiquery porigin_method ptbytes true',
            'papiquery.INPUT = POBJECT n_selector',
            'papiquery.CLASS.RECEIVER = (n_selector)', 'papiquery.THIS = eps',
            'pexceptioncall.CALLBACK = PARRAY n_raw',
            '~((HOBJECT n_selector) <- S.ALLOCATIONS)',
            '~((HARRAY n_raw) <- S.ALLOCATIONS)',
            'S.EXCEPTIONHANDLER = eps', 'S.EXCEPTIONHANDLERS = eps',
            '$target_nodes(pcallcontext.TARGET) = eps',
            '$task_nodes(EXCEPTION_HANDLER_RESULT pexceptioncall) = [HOBJECT pexceptioncall.OBJECT]',
            '$exception_result_valid(S, pexceptioncall)',
            '$exception_context_valid(S, pcallcontext)',
            '~$exception_result_valid(S, pexceptioncall[.RAW = ($array_empty())])',
            '~$exception_context_valid(S, pcallcontext[.EXTRA = [KNOWN PNULL]])',
            '~$exception_context_valid(S[.FRAMES = [pframe[.CONTEXT = (pcallcontext)]]], pcallcontext)',
            *VALID,
            'S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
            'S_paused.ALLOCATIONS = S.ALLOCATIONS',
            'S_done = $drive(S, 2000)', 'S_done.COMPLETION = NORMAL',
            'S_done.TODO = eps', 'S_done.CURRENT = eps', 'S_done.FRAMES = eps',
            '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))',
            '$drive(S_paused[.COMPLETION = NORMAL], 2000) = S_done',
            '~((HOBJECT n_selector) <- S_done.ALLOCATIONS)',
            '~((HOBJECT pexceptioncall.OBJECT) <- S_done.ALLOCATIONS)',
        ],
    },
    'byref-warning-preserves-immutable-terminal-leaf': {
        'source': SOURCES['exception-compound-byref-warning-keeps-selected-leaf'],
        'stage': 'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* -- if '
                 'pargcall.KIND = INTRINSIC_FUNC_NUM_ARGS -- if S.CURRENT = (pcallcontext) -- if '
                 '$exception_context_kind(S, pcallcontext)',
        'checks': [
            'S.CURRENT = (pcallcontext)', 'S.FRAMES = [pframe]',
            'pframe.TODO = (EXCEPTION_HANDLER_RESULT pexceptioncall) :: ptask_saved*',
            'pcallcontext.TARGET = API_METHOD_TARGET papiquery porigin_method ptbytes true',
            'ptbytes = $ptascii("h")',
            'papiquery.METHOD = DIRECT (PSTRING $ptascii("A::h"))',
            'papiquery.VALUE = PARRAY n_raw',
            '$entry_lookup(S.ARRAYS[n_raw].ITEMS, KINT 1) = (ALIAS n_method)',
            'S.STORE[n_method] = DEFINED (PSTRING $ptascii("A::k"))',
            'pexceptioncall.SENT = (REFERENCE n_sent)',
            'S.STORE[n_sent] = DEFINED (POBJECT pexceptioncall.OBJECT)',
            'pcallcontext.ARGC = 1', 'pcallcontext.EXTRA = eps',
            'pcallcontext.CALLSITE = eps', 'pcallcontext.LINE = $(-1)',
            'pcallcontext.HOLES = eps', 'pframe.CONTEXT = eps',
            'pframe.ORIGIN = eps', 'pframe.CONSTCONTEXT = eps',
            '$heap_owners($heap_graph(S), HCELL n_sent) = 1',
            '$heap_owners($heap_graph(S), HOBJECT pexceptioncall.OBJECT) = 2',
            '$exception_result_valid(S, pexceptioncall)',
            '$exception_context_valid(S, pcallcontext)',
            '~$exception_result_valid(S, pexceptioncall[.SENT = (REFERENCE n_method)])',
            '~$exception_result_valid(S, pexceptioncall[.RAW = ($array_empty())])',
            '~$consumer_method_valid(S, papiquery, porigin_method, $ptascii("k"))',
            '~$exception_context_valid(S, pcallcontext[.EXTRA = [KNOWN PNULL]])',
            *VALID,
            'S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
            'S_paused.ALLOCATIONS = S.ALLOCATIONS',
            'S_done = $drive(S, 2000)', 'S_done.COMPLETION = NORMAL',
            'S_done.TODO = eps', 'S_done.CURRENT = eps', 'S_done.FRAMES = eps',
            '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))',
            '$drive(S_paused[.COMPLETION = NORMAL], 2000) = S_done',
            '~((HCELL n_sent) <- S_done.ALLOCATIONS)',
            '~((HOBJECT pexceptioncall.OBJECT) <- S_done.ALLOCATIONS)',
        ],
    },
    'retired-method-exception-maker-capture': {
        'source': SOURCES['shutdown-keyword-from-retired-method-exception-handler'],
        'stage': 'S.TODO = [SHUTDOWN_SEND 0 0 eps]',
        'checks': [
            'pshutdownentry = S.SHUTDOWN.ENTRIES[0]',
            'pshutdownentry.TARGET = API_METHOD_TARGET papiquery porigin_method ptbytes true',
            'pshutdownentry.CAPTURE = (pmethodcapture)',
            'pshutdownentry.PRODUCER = (pshutdownproducer)',
            'pshutdownproducer.INTERNAL',
            'pshutdownproducer.SCOPE = eps /\\ pshutdownproducer.BINDING = eps',
            'pshutdownproducer.SITE = eps',
            'pmethodcapture.CALLSITE = eps',
            'S.EXCEPTIONHANDLER = eps /\\ S.EXCEPTIONHANDLERS = eps',
            '$target_function(S, pshutdownproducer.TARGET) = (pfunction)',
            'pmethodcapture.FUNCTION = pfunction.ORIGIN',
            '$class_named(S.CLASSNAMES, $ptascii("d")) = (porigin_called)',
            'pmethodcapture.CALLED_CLASS = (porigin_called)',
            'papiquery.CALLED = (porigin_called)',
            'papiquery.THIS = eps',
            '$target_nodes(pshutdownproducer.TARGET) = eps',
            '$shutdown_roots(S.SHUTDOWN.ENTRIES) = eps',
            '$consumer_producer_capture(S, pshutdownentry)',
            '$shutdown_entry_valid(S, pshutdownentry)',
            '~$consumer_producer_capture(S, pshutdownentry[.PRODUCER = eps])',
            '~$consumer_producer_capture(S, pshutdownentry[.CAPTURE = (pmethodcapture[.CALLSITE = (pshutdownentry.CALL.SITE)])])',
            '~$consumer_producer_capture(S, pshutdownentry[.PRODUCER = (pshutdownproducer[.SITE = (pshutdownentry.CALL.SITE)])])',
            '~$consumer_producer_capture(S, pshutdownentry[.PRODUCER = (pshutdownproducer[.INTERNAL = false])])',
            '~$consumer_producer_capture(S, pshutdownentry[.CAPTURE = (pmethodcapture[.CALLED_CLASS = pmethodcapture.LEXICAL_CLASS])])',
            *VALID,
            'S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
            'S_paused.SHUTDOWN = S.SHUTDOWN',
            'S_done = $drive(S, 2000)', 'S_done.COMPLETION = NORMAL', *DONE,
            '$drive(S_paused[.COMPLETION = NORMAL], 2000) = S_done',
        ],
    },
    'original-receiver-despite-genuine-replacement': {
        'source': SOURCES['shutdown-compound-original-receiver-after-genuine-swap'],
        'stage': 'S.TODO = [SHUTDOWN_SEND 0 0 eps]',
        'checks': [
            'pshutdownentry = S.SHUTDOWN.ENTRIES[0]',
            'pshutdownentry.TARGET = API_METHOD_TARGET papiquery porigin_method ptbytes false',
            'pshutdownentry.PRODUCER = (pshutdownproducer)',
            'pshutdownproducer.TARGET = METHOD_TARGET n_receiver porigin_maker',
            '~pshutdownproducer.INTERNAL',
            'papiquery.INPUT = POBJECT n_receiver',
            'papiquery.THIS = (n_receiver)',
            'papiquery.CLASS.RECEIVER = (n_receiver)',
            '$lookup(S.ENV, $ptascii("b")) = (n_cell)',
            'S.STORE[n_cell] = DEFINED (POBJECT n_other)',
            'n_other =/= n_receiver',
            'S.OBJECTS[n_receiver] = INSTANCE porigin_class',
            'S.OBJECTS[n_other] = INSTANCE porigin_class',
            '(HOBJECT n_other) <- S.ALLOCATIONS',
            '$shutdown_roots(S.SHUTDOWN.ENTRIES) = [HOBJECT n_receiver]',
            '$heap_owners($heap_graph(S), HOBJECT n_receiver) = 1',
            '$consumer_producer_capture(S, pshutdownentry)',
            '$consumer_shutdown_scope(S, papiquery, pshutdownentry)',
            '$shutdown_entry_valid(S, pshutdownentry)',
            '~$consumer_producer_capture(S, pshutdownentry[.PRODUCER = (pshutdownproducer[.TARGET = METHOD_TARGET n_other porigin_maker])])',
            'papiquery_other = papiquery[.THIS = (n_other)]',
            'pshutdownentry_other = pshutdownentry[.TARGET = API_METHOD_TARGET papiquery_other porigin_method ptbytes false]',
            '~$consumer_producer_capture(S, pshutdownentry_other)',
            '~$consumer_shutdown_scope(S, papiquery_other, pshutdownentry_other)',
            '~$shutdown_state_valid(S[.SHUTDOWN.ENTRIES = [pshutdownentry_other]])',
            '~$consumer_shutdown_scope(S, papiquery[.THIS = eps], pshutdownentry)',
            *VALID,
            'S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
            'S_paused.ALLOCATIONS = S.ALLOCATIONS',
            'S_done = $drive(S, 2000)', 'S_done.COMPLETION = NORMAL', *DONE,
            '$drive(S_paused[.COMPLETION = NORMAL], 2000) = S_done',
            '$heap_owners($heap_graph(S_done), HOBJECT n_receiver) = 1',
        ],
    },
    'retired-selected-closure-maker-scope': {
        'source': SOURCES['shutdown-keyword-from-retired-selected-closure-maker'],
        'stage': 'S.TODO = [SHUTDOWN_SEND 0 0 eps]',
        'checks': [
            'pshutdownentry = S.SHUTDOWN.ENTRIES[0]',
            'pshutdownentry.CAPTURE = (pmethodcapture)',
            'pshutdownentry.PRODUCER = (pshutdownproducer)',
            'pshutdownproducer.TARGET = CLOSURE_TARGET n_closure',
            'pshutdownproducer.SCOPE = (pclosurescope)',
            'pshutdownproducer.BINDING = eps',
            'pshutdownproducer.INTERNAL',
            'pshutdownproducer.SITE = eps',
            'pclosurescope.OBJECT = n_closure',
            'pclosurescope.RECEIVER = eps',
            'pmethodcapture.CALLSITE = eps',
            '~((HOBJECT n_closure) <- S.ALLOCATIONS)',
            '$closure_scope_at(S.CLOSURESCOPES, n_closure) = eps',
            'S.EXCEPTIONHANDLER = eps /\\ S.EXCEPTIONHANDLERS = eps',
            '$shutdown_roots(S.SHUTDOWN.ENTRIES) = eps',
            '$heap_owners($heap_graph(S), HOBJECT n_closure) = 0',
            '$consumer_producer_capture(S, pshutdownentry)',
            '$shutdown_entry_valid(S, pshutdownentry)',
            '~$consumer_producer_capture(S, pshutdownentry[.PRODUCER = (pshutdownproducer[.SCOPE = eps])])',
            '~$consumer_producer_capture(S, pshutdownentry[.PRODUCER = (pshutdownproducer[.SCOPE = (pclosurescope[.OBJECT = |S.OBJECTS|])])])',
            '~$consumer_producer_capture(S, pshutdownentry[.PRODUCER = (pshutdownproducer[.SCOPE = (pclosurescope[.RECEIVER = (n_closure)])])])',
            '~$consumer_producer_capture(S, pshutdownentry[.CAPTURE = (pmethodcapture[.CALLSITE = (pshutdownentry.CALL.SITE)])])',
            '~$consumer_producer_capture(S, pshutdownentry[.PRODUCER = (pshutdownproducer[.SITE = (pshutdownentry.CALL.SITE)])])',
            *VALID,
            'S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
            'S_paused.ALLOCATIONS = S.ALLOCATIONS',
            'S_done = $drive(S, 2000)', 'S_done.COMPLETION = NORMAL', *DONE,
            '$drive(S_paused[.COMPLETION = NORMAL], 2000) = S_done',
            '~((HOBJECT n_closure) <- S_done.ALLOCATIONS)',
        ],
    },
}

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--case', action='append')
    args = parser.parse_args()
    raise SystemExit(0 if runner.run(args.case) else 1)
