#!/usr/bin/env python3
"""Public method-string source certificates, capture roots and callback frames."""
from pathlib import Path
import json
import warnings

import closure_call_protocol as protocol

CATALOGUE = Path(__file__).with_name('class_method_strings_cases.json')
SOURCES = {row['id']: row['source'] for row in json.loads(CATALOGUE.read_text())}
VALID = ['$call_descriptors_valid(S)', '$class_state_valid(S)',
         '$closure_state_valid(S)', '$heap_valid($heap_graph(S))']
AFTER = ['S_done = $drive(S, 3000)', 'S_done.COMPLETION = NORMAL',
         '$call_descriptors_valid(S_done)', '$closure_state_valid(S_done)',
         '$heap_valid($heap_graph(S_done))']

CASES = {
    'fixed-parent-selection-despite-child-override': {
        'source': SOURCES['fixed-nonstatic-requested-parent-overridden-child'],
        'stage': ('S.TODO = (CALL_ARGS (STRING_METHOD_TARGET pcalltarget pstringselection) '
                  'phpType7* 0 poperand* (porigin_site) z_call) :: ptask_tail*'),
        'checks': [
            'pcalltarget = SCOPED_TARGET porigin_requested porigin_method porigin_called (n_receiver) (KNOWN (PSTRING $ptascii("Owner")))',
            'pstringselection.SITE = porigin_site',
            'pstringselection.REQUESTED = porigin_requested',
            'pstringselection.ORIGINAL = $ptascii("Owner::run")',
            'pstringselection.INIT = $dynamic_init_line(S, porigin_site)',
            'pstringselection.LINE = z_call',
            '$dynamic_fixed_name(S, porigin_site) = ($ptascii("Owner::run"))',
            '$string_target_identity(S, pcalltarget, pstringselection)',
            '$string_site_valid(S, pstringselection, false)',
            '$call_selected_valid(S, STRING_METHOD_TARGET pcalltarget pstringselection, (porigin_site))',
            '$target_function(S, pcalltarget) = (pfunction)',
            '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
            'pmethoddesc.FUNCTION = pfunction',
            'pmethoddesc.OWNER = porigin_requested',
            '~pmethoddesc.STATIC',
            'porigin_requested =/= porigin_called',
            'S.OBJECTS[n_receiver] = INSTANCE porigin_called',
            '$target_nodes(STRING_METHOD_TARGET pcalltarget pstringselection) = [HOBJECT n_receiver]',
            '$target_receiver(S, STRING_METHOD_TARGET pcalltarget pstringselection) = (n_receiver)',
            '$target_lexical_class(S, STRING_METHOD_TARGET pcalltarget pstringselection) = (porigin_requested)',
            '$target_called_class(S, STRING_METHOD_TARGET pcalltarget pstringselection) = (porigin_called)',
            '$effective_method(S, porigin_called, $ptascii("run"), |S.CLASSES|) = (pmethoddesc_child)',
            'pmethoddesc_child.FUNCTION.ORIGIN =/= porigin_method',
            '$target_function(S, METHOD_TARGET n_receiver porigin_method) = eps',
            '$typed_callable(S, PSTRING $ptascii("Owner::run")) = (true)',
            '$typed_callable(S, PSTRING $ptascii("Child::run")) = (false)',
            '$string_resolve(S, $ptascii("Owner::run"), ARRAY_DISPATCH, false) = ARRAYINVALID $ptascii("Non-static method Owner::run() cannot be called statically")',
            'S.GLOBALTABLE = (psymboltable)',
            '$lookup(psymboltable.ENV, $ptascii("other")) = (n_other_cell)',
            'S.STORE[n_other_cell] = DEFINED (POBJECT n_other)',
            'n_other =/= n_receiver',
            'S.OBJECTS[n_other] = INSTANCE porigin_called',
            '$target_function(S, SCOPED_TARGET porigin_requested porigin_method porigin_called (n_other) (KNOWN (PSTRING $ptascii("Owner")))) = (pfunction)',
            '~$call_selected_valid(S, STRING_METHOD_TARGET (SCOPED_TARGET porigin_requested porigin_method porigin_called (n_other) (KNOWN (PSTRING $ptascii("Owner")))) pstringselection, (porigin_site))',
            *VALID,
            '~$string_target_identity(S, SCOPED_TARGET porigin_requested porigin_method porigin_requested (n_receiver) (KNOWN (PSTRING $ptascii("Owner"))), pstringselection)',
            '~$string_target_identity(S, SCOPED_TARGET porigin_requested porigin_method porigin_called eps (KNOWN (PSTRING $ptascii("Owner"))), pstringselection)',
            '~$string_target_identity(S, SCOPED_TARGET porigin_requested porigin_method porigin_called (n_receiver) (KNOWN (PSTRING $ptascii("Child"))), pstringselection)',
            '~$string_site_valid(S, pstringselection[.SITE = porigin_method], false)',
            '~$string_site_valid(S, pstringselection[.INIT = $(pstringselection.INIT + 100)], false)',
            '~$string_site_valid(S, pstringselection[.LINE = $(pstringselection.LINE + 100)], false)',
            '~$call_task_valid(S, CALL_ARGS (STRING_METHOD_TARGET pcalltarget pstringselection[.ORIGINAL = $ptascii("Child::run")]) phpType7* 0 poperand* (porigin_site) z_call)',
            *AFTER,
            'S_done.EVENTS = [OUTPUT $ptascii("Owner"), OUTPUT $ptascii("/"), OUTPUT $ptascii("Child"), OUTPUT $ptascii(":"), OUTPUT $ptascii("x")]',
            '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
        ],
    },
    'computed-static-capture-direct-allocation': {
        'source': SOURCES['captured-clone-nominal-closure-invoke-missing'],
        'stage': ('S.TODO = (STRING_CONVERT pcalltarget pstringselection) :: ptask_tail* '
                  '-- if $dynamic_fixed_name(S, pstringselection.SITE) = eps'),
        'checks': [
            'pcalltarget = STATIC_METHOD_TARGET pstringselection.REQUESTED porigin_method',
            'pstringselection.ORIGINAL = $ptascii("Child::run")',
            '$string_convert_valid(S, pcalltarget, pstringselection)',
            '$string_target_identity(S, pcalltarget, pstringselection)',
            '$string_site_valid(S, pstringselection, true)',
            '$target_nodes(pcalltarget) = eps',
            '$target_receiver(S, pcalltarget) = eps',
            '$target_function(S, pcalltarget) = (pfunction)',
            '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
            'pmethoddesc.STATIC',
            'pmethoddesc.OWNER =/= pstringselection.REQUESTED',
            *VALID,
            '~$string_convert_valid(S, pcalltarget, pstringselection[.ORIGINAL = $ptascii("Child::missing")])',
            '~$string_convert_valid(S, pcalltarget, pstringselection[.REQUESTED = pmethoddesc.OWNER])',
            '~$string_convert_valid(S, pcalltarget, pstringselection[.INIT = $(pstringselection.INIT + 100)])',
            '~$string_convert_valid(S, pcalltarget, pstringselection[.LINE = $(pstringselection.LINE + 100)])',
            '~$string_convert_valid(S, STRING_METHOD_TARGET pcalltarget pstringselection, pstringselection)',
            'n_capture = |S.OBJECTS|',
            'PhpStep: S ~> S_one',
            'S_one.COMPLETION = NORMAL',
            'S_one.TODO = ptask_tail*',
            'S_one.OBJECTS[n_capture] = STRINGMETHODCLOSURE pcalltarget pstringselection',
            'S_one.RESULT = KNOWN (POBJECT n_capture)',
            'S_one.STORE = S.STORE',
            'S_one.EVENTS = S.EVENTS',
            'S_one.ALLOCATIONS = S.ALLOCATIONS ++ [HOBJECT n_capture]',
            '$closure_callable(S_one, n_capture)',
            '$typed_closure(S_one, n_capture)',
            '$node_children(S_one, HOBJECT n_capture) = eps',
            '$closure_scope_at(S_one.CLOSURESCOPES, n_capture) = (pclosurescope)',
            'pclosurescope.CREATION = eps',
            'pclosurescope.RECEIVER = eps',
            'pclosurescope.LEXICAL = pmethoddesc.OWNER',
            'pclosurescope.CALLED = pstringselection.REQUESTED',
            '$closure_scope_row_valid(S_one, pclosurescope)',
            '~$closure_scope_row_valid(S_one, pclosurescope[.RECEIVER = (999)])',
            '~$closure_scope_row_valid(S_one, pclosurescope[.CALLED = pmethoddesc.OWNER])',
            '$closure_state_valid(S_one)',
            '$call_descriptors_valid(S_one)',
            'S_done = $drive(S_one, 4000)',
            'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT $ptascii("Closure"), OUTPUT $ptascii(":"), OUTPUT $ptascii("R"), OUTPUT $ptascii("x"), OUTPUT $ptascii("R"), OUTPUT $ptascii("y"), OUTPUT $ptascii(":E")]',
            '~((HOBJECT n_capture) <- S_done.ALLOCATIONS)',
            '$closure_state_valid(S_done)',
            '$call_descriptors_valid(S_done)',
            '$heap_valid($heap_graph(S_done))',
        ],
    },
    'fixed-parent-capture-clone-retains-only-selected-receiver': {
        'source': SOURCES['fixed-capture-requested-descriptor-receiver-retirement'],
        'stage': ('S.CURRENT = (pcallcontext) '
                  '-- if pcallcontext.TARGET = CLOSURE_TARGET n_capture '
                  '-- if S.OBJECTS[n_capture] = STRINGMETHODCLOSURE pcalltarget pstringselection '
                  '-- if $lookup(S.ENV, $ptascii("v")) = (n_value) '
                  '-- if S.STORE[n_value] = DEFINED (PSTRING $ptascii("k"))'),
        'checks': [
            'pcalltarget = SCOPED_TARGET porigin_requested porigin_method porigin_called (n_receiver) (KNOWN (PSTRING $ptascii("Owner")))',
            'pstringselection.REQUESTED = porigin_requested',
            'pstringselection.ORIGINAL = $ptascii("Owner::run")',
            '$string_site_valid(S, pstringselection, true)',
            '$string_target_identity(S, pcalltarget, pstringselection)',
            '$target_function(S, CLOSURE_TARGET n_capture) = (pfunction)',
            'pfunction.ORIGIN = porigin_method',
            '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
            'pmethoddesc.OWNER = porigin_requested',
            '~pmethoddesc.STATIC',
            'porigin_called =/= porigin_requested',
            'S.OBJECTS[n_receiver] = INSTANCE porigin_called',
            '$target_function(S, METHOD_TARGET n_receiver porigin_method) = eps',
            '$node_children(S, HOBJECT n_capture) = [HOBJECT n_receiver]',
            '$target_nodes(pcalltarget) = [HOBJECT n_receiver]',
            'pcallcontext.RECEIVER = (n_receiver)',
            'pcallcontext.LEXICAL_CLASS = (porigin_requested)',
            'pcallcontext.CALLED_CLASS = (porigin_called)',
            'pcallcontext.ARGC = 1',
            '$arginfo_values(S, pcallcontext) = [PSTRING $ptascii("k")]',
            'S.GLOBALTABLE = (psymboltable)',
            '$lookup(psymboltable.ENV, $ptascii("copy")) = (n_copy)',
            'S.STORE[n_copy] = DEFINED (POBJECT n_capture)',
            '$lookup(psymboltable.ENV, $ptascii("receiver")) = eps',
            '$lookup(psymboltable.ENV, $ptascii("saved")) = eps',
            'n_original = $nabs($(n_capture - 1))',
            'S.OBJECTS[n_original] = S.OBJECTS[n_capture]',
            '~((HOBJECT n_original) <- S.ALLOCATIONS)',
            '(HOBJECT n_receiver) <- S.ALLOCATIONS',
            '$closure_scope_at(S.CLOSURESCOPES, n_capture) = (pclosurescope)',
            'pclosurescope.CREATION = eps',
            '$closure_scope_row_valid(S, pclosurescope)',
            '~$closure_scope_row_valid(S, pclosurescope[.RECEIVER = eps])',
            '~$closure_scope_row_valid(S, pclosurescope[.CALLED = porigin_requested])',
            '~$string_target_identity(S, SCOPED_TARGET porigin_requested porigin_method porigin_called eps (KNOWN (PSTRING $ptascii("Owner"))), pstringselection)',
            *VALID,
            *AFTER,
            'S_done.EVENTS = [OUTPUT $ptascii("Owner"), OUTPUT $ptascii("/"), OUTPUT $ptascii("Child"), OUTPUT $ptascii(":"), OUTPUT $ptascii("k")]',
            '~((HOBJECT n_capture) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
        ],
    },
    'fixed-conversion-binds-producer-this': {
        'source': SOURCES['fixed-capture-requested-descriptor-receiver-retirement'],
        'stage': ('S.TODO = (STRING_CONVERT pcalltarget pstringselection) :: ptask_tail* '
                  '-- if pcalltarget = SCOPED_TARGET porigin_requested porigin_method porigin_called (n_receiver) (KNOWN (PSTRING $ptascii("Owner")))'),
        'checks': [
            'S.CURRENT = (pcallcontext)',
            'pcallcontext.RECEIVER = (n_receiver)',
            'pstringselection.ORIGINAL = $ptascii("Owner::run")',
            'pstringselection.REQUESTED = porigin_requested',
            '$string_target_identity(S, pcalltarget, pstringselection)',
            '$string_site_valid(S, pstringselection, true)',
            '$string_convert_valid(S, pcalltarget, pstringselection)',
            '$string_fixed_receiver(S, porigin_requested) = (n_receiver)',
            'S.GLOBALTABLE = (psymboltable)',
            '$lookup(psymboltable.ENV, $ptascii("other")) = (n_other_cell)',
            'S.STORE[n_other_cell] = DEFINED (POBJECT n_other)',
            'n_other =/= n_receiver',
            'S.OBJECTS[n_other] = INSTANCE porigin_called',
            '$string_target_identity(S, SCOPED_TARGET porigin_requested porigin_method porigin_called (n_other) (KNOWN (PSTRING $ptascii("Owner"))), pstringselection)',
            '~$string_convert_valid(S, SCOPED_TARGET porigin_requested porigin_method porigin_called (n_other) (KNOWN (PSTRING $ptascii("Owner"))), pstringselection)',
            '$task_nodes(STRING_CONVERT pcalltarget pstringselection) = [HOBJECT n_receiver]',
            *VALID,
            'n_capture = |S.OBJECTS|',
            'PhpStep: S ~> S_one',
            'S_one.COMPLETION = NORMAL',
            'S_one.TODO = ptask_tail*',
            'S_one.OBJECTS[n_capture] = STRINGMETHODCLOSURE pcalltarget pstringselection',
            'S_one.RESULT = KNOWN (POBJECT n_capture)',
            'S_one.ALLOCATIONS = S.ALLOCATIONS ++ [HOBJECT n_capture]',
            'S_one.STORE = S.STORE',
            'S_one.EVENTS = S.EVENTS',
            '$node_children(S_one, HOBJECT n_capture) = [HOBJECT n_receiver]',
            '$closure_state_valid(S_one)',
            '$call_descriptors_valid(S_one)',
            'S_done = $drive(S_one, 3000)',
            'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT $ptascii("Owner"), OUTPUT $ptascii("/"), OUTPUT $ptascii("Child"), OUTPUT $ptascii(":"), OUTPUT $ptascii("k")]',
            '~((HOBJECT n_capture) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_other) <- S_done.ALLOCATIONS)',
            '$call_descriptors_valid(S_done)',
            '$closure_state_valid(S_done)',
            '$heap_valid($heap_graph(S_done))',
        ],
    },
}

INI_OPTION_PREFIX = '''
dec $string_ini_result_stage(pstate) : bool
def $string_ini_result_stage(S) = true
  -- if S.TODO = (CONFIG_STRING_RESULT pconfigcall n_object porigin_child z_child z_call) :: ptask_tail*
  -- if pconfigcall.KIND = INTRINSIC_INI_SET
def $string_ini_result_stage(S) = false -- otherwise
dec $string_ini_result_seek(pstate, nat) : pstate
def $string_ini_result_seek(S, n) = S -- if $string_ini_result_stage(S)
def $string_ini_result_seek(S, n) = $string_ini_result_seek(S_next, $nabs($(n - 1)))
  -- if ~$string_ini_result_stage(S)
  -- if S.COMPLETION = NORMAL
  -- if $(n > 0)
  -- PhpStep: S ~> S_next
dec $string_ini_step(pstate) : pstate
def $string_ini_step(S) = S_next -- PhpStep: S ~> S_next
'''

FILE_CASES = [(
    'static-string-selected-ini-option-value-rejection',
    SOURCES['static-string-current-ini-option-arguments-trace'].encode(),
    'S.CURRENT = (pcallcontext_option)\n'
    '  -- if S.FRAMES = pframe_owner :: pframe_tail*\n'
    '  -- if pframe_owner.TODO = (STRINGIFY_RESULT n_option porigin_child z_call) :: (CONFIG_STRING_RESULT pconfigcall n_option porigin_child z_child z_call) :: ptask_owner*\n'
    '  -- if S.FILEINCLUDEPATH = ($ptascii("mutated") ++ [0] ++ $ptascii("tail"))',
    [
        'S.CURRENT = (pcallcontext_option)',
        'S.FRAMES = pframe_owner :: pframe_tail*',
        'pframe_owner.TODO = (STRINGIFY_RESULT n_option porigin_child z_call) :: (CONFIG_STRING_RESULT pconfigcall n_option porigin_child z_child z_call) :: ptask_owner*',
        'pframe_owner.CONTEXT = (pcallcontext_owner)',
        'pframe_owner.LOCALS = (psymboltable_owner)',
        'pcallcontext_option.TARGET = METHOD_TARGET n_option pcallcontext_option.FUNCTION',
        'pcallcontext_option.ARGC = 0',
        'pcallcontext_option.PARAMS = eps',
        '$arginfo_values(S, pcallcontext_option) = eps',
        'pcallcontext_owner.TARGET = STRING_METHOD_TARGET pcalltarget pstringselection',
        'pcalltarget = STATIC_METHOD_TARGET porigin_called pcallcontext_owner.FUNCTION',
        'pcallcontext_owner.RECEIVER = eps',
        'pcallcontext_owner.LEXICAL_CLASS = (porigin_owner)',
        'pcallcontext_owner.CALLED_CLASS = (porigin_called)',
        'porigin_owner =/= porigin_called',
        'pcallcontext_owner.ARGC = 1',
        'pcallcontext_owner.PARAMS = [$ptascii("v")]',
        '$arginfo_values(S[.ENV = psymboltable_owner.ENV], pcallcontext_owner) = [PSTRING $ptascii("x")]',
        'pstringselection.REQUESTED = porigin_called',
        'pstringselection.ORIGINAL = $ptascii("Child::run")',
        '$string_target_identity(S, pcalltarget, pstringselection)',
        '$string_site_valid(S, pstringselection, false)',
        '$call_selected_valid(S, pcallcontext_owner.TARGET, pcallcontext_owner.CALLSITE)',
        '$target_nodes(pcallcontext_owner.TARGET) = eps',
        '$target_receiver(S, pcallcontext_owner.TARGET) = eps',
        'pconfigcall.KIND = INTRINSIC_INI_SET',
        'pconfigcall.NAMED',
        'pconfigcall.OWNER = eps',
        'pconfigcall.SELECTION = eps',
        'pconfigcall.SENT = [NAMED_SENT (KNOWN (POBJECT n_option)), NAMED_SENT (KNOWN (POBJECT n_rejected))]',
        'n_option =/= n_rejected',
        '$intrinsic_argument(S, pconfigcall.SITE, 1) = ((expression_option, false, preqbytes_option?, porigin_child, z_child))',
        'preqbytes_option? = ($ptascii("option"))',
        '$intrinsic_argument(S, pconfigcall.SITE, 0) = ((expression_value, false, preqbytes_value?, porigin_value, z_value))',
        'preqbytes_value? = ($ptascii("value"))',
        '$config_destination(INTRINSIC_INI_SET, preqbytes_option?, 1) = (0)',
        '$config_destination(INTRINSIC_INI_SET, preqbytes_value?, 0) = (1)',
        '$config_string_source(S, pconfigcall) = ((porigin_child, z_child))',
        '$config_string_site_valid(S, pconfigcall, n_option, porigin_child, z_child, z_call)',
        '$config_string_trace_context(S, pcallcontext_option)',
        '(HOBJECT n_option) <- $task_nodes(CONFIG_STRING_RESULT pconfigcall n_option porigin_child z_child z_call)',
        '(HOBJECT n_rejected) <- $task_nodes(CONFIG_STRING_RESULT pconfigcall n_option porigin_child z_child z_call)',
        '$trace_context(S, S.ENV, S.CURRENT) = [ptraceframe_option, ptraceframe_ini]',
        'ptraceframe_option.FUNCTION = $ptascii("__toString")',
        'ptraceframe_option.ARGS = eps',
        'ptraceframe_ini.FUNCTION = $ptascii("ini_set")',
        'ptraceframe_ini.ARGS = [(KINT 0, POBJECT n_option), (KINT 1, POBJECT n_rejected)]',
        '$outputs(S.EVENTS) = $ptascii("Owner/Child:1:x|o0z")',
        'S.FILEINCLUDEPATH = ($ptascii("mutated") ++ [0] ++ $ptascii("tail"))',
        *VALID,
        '~$string_target_identity(S, pcalltarget, pstringselection[.ORIGINAL = $ptascii("Child::missing")])',
        '~$string_site_valid(S, pstringselection[.LINE = $(pstringselection.LINE + 100)], false)',
        '~$config_string_site_valid(S, pconfigcall[.SITE = PORIGIN 999 eps], n_option, porigin_child, z_child, z_call)',
        '~$config_string_site_valid(S, pconfigcall[.LINE = 999], n_option, porigin_child, z_child, z_call)',
        '~$config_string_site_valid(S, pconfigcall[.SENT = [NAMED_SENT (KNOWN (POBJECT n_rejected)), NAMED_SENT (KNOWN (POBJECT n_option))]], n_option, porigin_child, z_child, z_call)',
        '~$call_descriptors_valid(S[.ALLOCATIONS = $call_remove_owner(S.ALLOCATIONS, HOBJECT n_rejected)])',
        '~$call_saved_context_valid(S, pframe_owner[.CONTEXT = (pcallcontext_owner[.CALLED_CLASS = (porigin_owner)])])',
        'S_result = $string_ini_result_seek(S, 100)',
        'S_result.COMPLETION = NORMAL',
        'S_result.TODO = (CONFIG_STRING_RESULT pconfigcall n_option porigin_child z_child z_call) :: ptask_owner*',
        'S_result.RESULT = KNOWN (PSTRING $ptascii("include_path"))',
        'S_result.CURRENT = (pcallcontext_owner)',
        'S_result.ORIGIN = (porigin_child)',
        'S_result.FILEINCLUDEPATH = S.FILEINCLUDEPATH',
        'S_result.EVENTS = S.EVENTS',
        '$call_descriptors_valid(S_result)',
        '$config_ini_value_conversion(POBJECT n_rejected) = TYPEREJECT',
        'S_error = $string_ini_step(S_result)',
        'S_error.COMPLETION = THROWING n_error',
        'S_error.OBJECTS[n_error] = THROWABLE pthrowable',
        'pthrowable.KIND = "TypeError"',
        'pthrowable.ORIGIN = (pconfigcall.SITE)',
        '$throwable_field(S_error, n_error, "trace") = PARRAY n_trace',
        'S_error.ARRAYS[n_trace].ITEMS = [ENTRY (KINT 0) (DIRECT (PARRAY n_trace_ini)), ENTRY (KINT 1) (DIRECT (PARRAY n_trace_owner))]',
        '$trace_array_field(S_error, n_trace_ini, $ptascii("function")) = PSTRING $ptascii("ini_set")',
        '$trace_array_field(S_error, n_trace_ini, $ptascii("args")) = PARRAY n_ini_args',
        'S_error.ARRAYS[n_ini_args].ITEMS = [ENTRY (KINT 0) (DIRECT (PSTRING $ptascii("include_path"))), ENTRY (KINT 1) (DIRECT (POBJECT n_rejected))]',
        '$trace_array_field(S_error, n_trace_owner, $ptascii("function")) = PSTRING $ptascii("run")',
        '$trace_array_field(S_error, n_trace_owner, $ptascii("class")) = PSTRING $ptascii("Owner")',
        '$trace_array_field(S_error, n_trace_owner, $ptascii("type")) = PSTRING $ptascii("::")',
        '$trace_array_field(S_error, n_trace_owner, $ptascii("args")) = PARRAY n_owner_args',
        'S_error.ARRAYS[n_owner_args].ITEMS = [ENTRY (KINT 0) (DIRECT (PSTRING $ptascii("x")))]',
        'S_error.FILEINCLUDEPATH = S.FILEINCLUDEPATH',
        'S_error.EVENTS = S.EVENTS',
        'S_done = $drive(S_error, 3000)',
        'S_done.COMPLETION = NORMAL',
        '$outputs(S_done.EVENTS) = $ptascii("Owner/Child:1:x|o0zE::|1:x|K")',
        'S_done.FILEINCLUDEPATH = ($ptascii("after"))',
        '~((HOBJECT n_option) <- S_done.ALLOCATIONS)',
        '~((HOBJECT n_rejected) <- S_done.ALLOCATIONS)',
        '~((HOBJECT n_error) <- S_done.ALLOCATIONS)',
        '$call_descriptors_valid(S_done)',
        '$class_state_valid(S_done)',
        '$closure_state_valid(S_done)',
        '$heap_valid($heap_graph(S_done))',
    ],
)]


# Current error-handler interaction keeps the selected static string caller.
INI_OPTION_PREFIX += '''
dec $string_handler_trace_stage(pstate) : bool
def $string_handler_trace_stage(S) = true
  -- if S.TODO = (GETTER_INVOKE pgettercall) :: ptask_tail*
  -- if pgettercall.METHOD = GET_TRACE_STRING
def $string_handler_trace_stage(S) = false -- otherwise
dec $string_handler_trace_seek(pstate, nat) : pstate
def $string_handler_trace_seek(S, n) = S -- if $string_handler_trace_stage(S)
def $string_handler_trace_seek(S, n) = $string_handler_trace_seek($throwable_begin(S), $nabs($(n - 1)))
  -- if ~$string_handler_trace_stage(S)
  -- if $throwable_pending(S.COMPLETION)
  -- if ~S.COMPILESTOP
  -- if $(n > 0)
def $string_handler_trace_seek(S, n) = $string_handler_trace_seek($prune_allocations($throwable_transition(S, S_next)), $nabs($(n - 1)))
  -- if ~$string_handler_trace_stage(S)
  -- if S.COMPLETION = NORMAL
  -- if ~S.COMPILESTOP
  -- if ~$error_read_pending(S)
  -- if $(n > 0)
  -- PhpStep: S ~> S_next
dec $string_handler_step(pstate) : pstate
def $string_handler_step(S) = S_next -- PhpStep: S ~> S_next
'''
FILE_CASES.append((
    'inherited-string-handler-saved-frame-trace',
    SOURCES['inherited-string-current-handler-saved-arguments-trace'].encode(),
    'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail*\n  -- if S.CURRENT = (pcallcontext_handler)\n  -- if pcallcontext_handler.NAME = $ptascii("namedHandler210")',
    [
        'S.CURRENT = (pcallcontext_handler)',
        'pcallcontext_handler.NAME = $ptascii("namedHandler210")',
        'pcallcontext_handler.ARGC = 4',
        'S.FRAMES = pframe_emitter :: pframe_tail*',
        'pframe_emitter.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_emitter*',
        'pframe_emitter.CONTEXT = (pcallcontext_emitter)',
        'pframe_emitter.LOCALS = (psymboltable_emitter)',
        'perrorcall.CALLBACK = PSTRING $ptascii("namedHandler210")',
        'perrorcall.LEVEL = 512',
        'perrorcall.MESSAGE = $ptascii("warning")',
        'perrorcall.TARGET = (pcallcontext_handler.TARGET)',
        'perrorcall.RESUME = ERROR_TRIGGER_PHASE pconfigcall 2',
        '$arginfo_values(S, pcallcontext_handler) = $error_handler_values(S, perrorcall)',
        '$error_context_valid(S, pcallcontext_handler)',
        'S.ERRORHANDLER.CALLBACK = eps',
        'pcallcontext_emitter.TARGET = STRING_METHOD_TARGET pcalltarget pstringselection',
        'pcalltarget = STATIC_METHOD_TARGET porigin_called porigin_method',
        'pcallcontext_emitter.FUNCTION = porigin_method',
        'pcallcontext_emitter.RECEIVER = eps',
        'pcallcontext_emitter.INSTANCE = eps',
        'pcallcontext_emitter.ARGC = 1',
        'pcallcontext_emitter.PARAMS = [$ptascii("x")]',
        '$arginfo_values(S[.ENV = psymboltable_emitter.ENV], pcallcontext_emitter) = [PINT 7]',
        'pcallcontext_emitter.LEXICAL_CLASS = (porigin_owner)',
        'pcallcontext_emitter.CALLED_CLASS = (porigin_called)',
        'porigin_owner =/= porigin_called',
        'pstringselection.REQUESTED = porigin_called',
        'pstringselection.ORIGINAL = $ptascii("Child::run")',
        '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
        'pmethoddesc.OWNER = porigin_owner',
        'pmethoddesc.STATIC',
        '$string_target_identity(S, pcalltarget, pstringselection)',
        '$string_site_valid(S, pstringselection, false)',
        '$call_selected_valid(S, pcallcontext_emitter.TARGET, pcallcontext_emitter.CALLSITE)',
        '$target_nodes(pcallcontext_emitter.TARGET) = eps',
        '$call_saved_context_valid(S, pframe_emitter)',
        '~$string_target_identity(S, pcalltarget, pstringselection[.REQUESTED = porigin_owner])',
        '~$string_site_valid(S, pstringselection[.SITE = perrorcall.SITE], false)',
        '~$string_site_valid(S, pstringselection[.INIT = $(pstringselection.INIT + 100)], false)',
        '~$string_site_valid(S, pstringselection[.LINE = $(pstringselection.LINE + 100)], false)',
        '~$call_saved_context_valid(S, pframe_emitter[.CONTEXT = (pcallcontext_emitter[.CALLED_CLASS = (porigin_owner)])])',
        '~$call_saved_context_valid(S, pframe_emitter[.CONTEXT = (pcallcontext_emitter[.RECEIVER = (0)])])',
        '~$error_context_valid(S[.CURRENT = (pcallcontext_handler[.ARGC = 3])], pcallcontext_handler[.ARGC = 3])',
        '~$error_context_valid(S[.CURRENT = (pcallcontext_handler[.CALLSITE = (pstringselection.SITE)])], pcallcontext_handler[.CALLSITE = (pstringselection.SITE)])',
        '$call_descriptors_valid(S)',
        '$heap_valid($heap_graph(S))',
        'S_trace = $string_handler_trace_seek(S[.COMPLETION = NORMAL], 1000)',
        'S_trace.COMPLETION = NORMAL',
        'S_trace.TODO = (GETTER_INVOKE pgettercall) :: ptask_trace*',
        'pgettercall.METHOD = GET_TRACE_STRING',
        'n_error = pgettercall.RECEIVER',
        '(HOBJECT n_error) <- S_trace.ALLOCATIONS',
        '$getter_invoke_valid(S_trace, pgettercall)',
        'S_trace.CURRENT = (pcallcontext_after)',
        'pcallcontext_after.TARGET = pcallcontext_emitter.TARGET',
        'pcallcontext_after.ARGC = 1',
        '$arginfo_values(S_trace, pcallcontext_after) = [PINT 7]',
        'S_trace.ERRORHANDLER.CALLBACK = (perrorcall.CALLBACK)',
        '$throwable_field(S_trace, n_error, "trace") = PARRAY n_trace',
        '$trace_graph_valid(S_trace, n_trace)',
        'S_trace.ARRAYS[n_trace].ITEMS = [ENTRY (KINT 0) (DIRECT (PARRAY n_handler_frame)), ENTRY (KINT 1) (DIRECT (PARRAY n_trigger_frame)), ENTRY (KINT 2) (DIRECT (PARRAY n_method_frame))]',
        '$trace_array_field(S_trace, n_handler_frame, $ptascii("function")) = PSTRING $ptascii("namedHandler210")',
        '$entry_lookup(S_trace.ARRAYS[n_handler_frame].ITEMS, KSTRING $ptascii("file")) = eps',
        '$entry_lookup(S_trace.ARRAYS[n_handler_frame].ITEMS, KSTRING $ptascii("line")) = eps',
        '$trace_array_field(S_trace, n_handler_frame, $ptascii("args")) = PARRAY n_handler_args',
        '|S_trace.ARRAYS[n_handler_args].ITEMS| = 4',
        '$trace_array_field(S_trace, n_trigger_frame, $ptascii("function")) = PSTRING $ptascii("trigger_error")',
        '$trace_array_field(S_trace, n_trigger_frame, $ptascii("args")) = PARRAY n_trigger_args',
        'S_trace.ARRAYS[n_trigger_args].ITEMS = [ENTRY (KINT 0) (DIRECT (PSTRING $ptascii("warning"))), ENTRY (KINT 1) (DIRECT (PINT 512))]',
        '$trace_array_field(S_trace, n_method_frame, $ptascii("function")) = PSTRING $ptascii("run")',
        '$trace_array_field(S_trace, n_method_frame, $ptascii("class")) = PSTRING $ptascii("Owner")',
        '$trace_array_field(S_trace, n_method_frame, $ptascii("type")) = PSTRING $ptascii("::")',
        '$trace_array_field(S_trace, n_method_frame, $ptascii("args")) = PARRAY n_method_args',
        'S_trace.ARRAYS[n_method_args].ITEMS = [ENTRY (KINT 0) (DIRECT (PINT 7))]',
        '$call_descriptors_valid(S_trace)',
        '$heap_valid($heap_graph(S_trace))',
        '$outputs(S_trace.EVENTS) = $ptascii("Owner/Child:1:7|h4|")',
        'S_one = $string_handler_step(S_trace)',
        'S_one.COMPLETION = NORMAL',
        'S_one.TODO = ptask_trace*',
        'S_one.RESULT = KNOWN (PSTRING n_trace_text*)',
        'n_trace_text* = $trace_array_string(S_trace, n_trace)',
        'S_one.STORE = S_trace.STORE',
        'S_one.EVENTS = S_trace.EVENTS',
        'S_one.ALLOCATIONS = S_trace.ALLOCATIONS',
        'S_done = $drive(S_one, 3000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.TODO = eps',
        'S_done.FRAMES = eps',
        'S_done.CURRENT = eps',
        'S_done.TRACE = eps',
        'S_done.ERRORHANDLER.CALLBACK = eps',
        'S_done.ERRORHANDLERS = eps',
        '~((HOBJECT n_error) <- S_done.ALLOCATIONS)',
        '~((HARRAY n_trace) <- S_done.ALLOCATIONS)',
        '$outputs(S_done.EVENTS) = $ptascii("Owner/Child:1:7|h4|") ++ n_trace_text* ++ $ptascii("|1:7")',
        '$call_descriptors_valid(S_done)',
        '$heap_valid($heap_graph(S_done))',
    ],
))


def main():
    protocol.run(CASES, (Path(__file__), CATALOGUE))
    warnings.filterwarnings('ignore', category=SyntaxWarning, message='invalid escape sequence')
    import include_mutable_protocol
    include_mutable_protocol.PREFIX += INI_OPTION_PREFIX
    include_mutable_protocol.main(FILE_CASES, (Path(__file__), CATALOGUE))


if __name__ == '__main__':
    main()
