#!/usr/bin/env python3
"""Real closure source, object ownership and paused invocation guards."""
from pathlib import Path
import base64,json,os,subprocess,tempfile
import request_environment as q
import request_environment_state as rs
from recorded_worker import Worker
R=Path(__file__).resolve().parents[2]
SOURCES = {'closure-factory-captured-array-cow': 'PD9waHAgJHg9WzFdOyRmPShmdW5jdGlvbigkYSl7cmV0dXJuIGZ1bmN0aW9uKCl1c2UoJGEpeyRhWzBdKys7cmV0dXJuICRhO307fSkoJHgpOyR4WzBdPTk7JHI9JGYoKTskclswXT03O2VjaG8gJGYoKVswXSwkeFswXSwkclswXTs=',
 'closure-instance-static-counters': 'PD9waHAgZnVuY3Rpb24gbWFrZSgpe3JldHVybiBmdW5jdGlvbigpe3N0YXRpYyAkeD0wO3JldHVybiArKyR4O307fSRhPW1ha2UoKTskYj1tYWtlKCk7JGM9JGE7ZWNobyAkYSgpLCRjKCksJGIoKSwkYSgpOw==',
 'closure-named-default-signature': 'PD9waHAgJGY9ZnVuY3Rpb24oaW50ICRhPTIsaW50ICRiPTMpOmludHtyZXR1cm4gJGErJGI7fTtlY2hvICRmKGI6NCk7',
 'closure-nested-named-scope': 'PD9waHAgJGY9ZnVuY3Rpb24oKXtzdGF0aWMgJHg9MjtmdW5jdGlvbiBpbm5lcigpe3N0YXRpYyAkeD00O3JldHVybiAkeCsrO31yZXR1cm4gaW5uZXIoKSskeCsrO307ZWNobyAkZigpOw==',
 'closure-selected-target-global-argument-unset': 'PD9waHAgJGY9ZnVuY3Rpb24oJHgpe3N0YXRpYyAkcz0wO2VjaG8gKyskcywkeDt9O2Z1bmN0aW9uIHdpcGUoKXt1bnNldCgkR0xPQkFMU1siZiJdKTtyZXR1cm4gNzt9JGYod2lwZSgpKTtlY2hvIGlzc2V0KCRmKTs=',
 'closure-unpack-reference-signature': 'PD9waHAgJGY9ZnVuY3Rpb24oJiRhLC4uLiR4cyl7KyskYTtyZXR1cm4gJHhzWzBdO307JHg9MTskYT1bJiR4LDVdO2VjaG8gJGYoLi4uJGEpLCR4Ow=='}
PREFIX = '\ndec $resume_destructuring(pstate, nat) : pstate\ndef $resume_destructuring(S, n) = $drive(S[.COMPLETION = NORMAL], n) -- if S.COMPLETION = BUDGET\ndef $resume_destructuring(S, n) = S -- if S.COMPLETION =/= BUDGET\n\nvar U : pcunit\ndec $outputs(pevent*) : nat*\ndef $outputs(eps) = eps\ndef $outputs((OUTPUT n*) :: pevent*) = n* ++ $outputs(pevent*)\ndef $outputs((WARNING n* z) :: pevent*) = $outputs(pevent*)\ndef $outputs((DIAGNOSTIC text n* z) :: pevent*) = $outputs(pevent*)\ndec $messages(pevent*) : pevent*\ndef $messages(eps) = eps\ndef $messages((OUTPUT n*) :: pevent*) = $messages(pevent*)\ndef $messages((WARNING n* z) :: pevent*) = (WARNING n* z) :: $messages(pevent*)\ndef $messages((DIAGNOSTIC text n* z) :: pevent*) = (DIAGNOSTIC text n* z) :: $messages(pevent*)\n\ndec $review_stage(pstate, nat) : bool\ndef $review_stage(S, 0) = true\n  -- if S.TODO = (CLOSURE_CAPTURE 1 0) :: ptask*\ndef $review_stage(S, 1) = true\n  -- if S.TODO = (CALL_ARGS (CLOSURE_TARGET n) phpType7* n_arg poperand* porigin? z) :: ptask*\ndef $review_stage(S, 2) = true\n  -- if S.TODO = (CLOSURE_RECEIVE porigin 0) :: ptask*\ndef $review_stage(S, 3) = true\n  -- if S.CURRENT = (pcallcontext)\n  -- if pcallcontext.NAME = [119,105,112,101]\n  -- if S_global = $global_table_view(S)\n  -- if $lookup(S_global.ENV, [102]) = eps\ndef $review_stage(S, 4) = true\n  -- if S.CURRENT = (pcallcontext)\n  -- if pcallcontext.INSTANCE = (0)\n  -- if S.OBJECTS[0] = REALCLOSURE porigin pitem* pstaticcell*\n  -- if pstaticcell* = [pstaticcell_one]\ndef $review_stage(S, 5) = true\n  -- if S.TODO = (NAMED_PREFLIGHT porigin n) :: ptask*\ndef $review_stage(S, n) = false -- otherwise\ndec $review_seek(pstate, nat, nat) : pstate\ndef $review_seek(S, n_kind, n_left) = S -- if $review_stage(S, n_kind)\ndef $review_seek(S, n_kind, n_left) = $review_seek($drive_steps(S[.COMPLETION = NORMAL], 1), n_kind, n_rest)\n  -- if ~$review_stage(S, n_kind)\n  -- if $(n_left > 0)\n  -- if n_rest = $(n_left - 1)\n\n'
CASES = [{'id': 'legitimate-arbitrary-capture-value',
  'source': 'closure-factory-captured-array-cow',
  'checks': ['S = __FULL__',
             'S.COMPLETION = NORMAL',
             '$outputs(S.EVENTS) = ([50,57,55])',
             'S.OBJECTS = [pobject_dead,REALCLOSURE porigin pitem* pstaticcell*]',
             '~((HOBJECT 0) <- S.ALLOCATIONS)',
             '(HOBJECT 1) <- S.ALLOCATIONS',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S_changed = S[.OBJECTS = [pobject_dead,REALCLOSURE porigin ([DIRECT (PINT 99)]) '
             'pstaticcell*]]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': '2c211abfd7f2ef2d211cd08c0a11a7cdb64b018feca6121cd5a54ac02082e908'},
 {'id': 'legitimate-stale-dead-backing',
  'source': 'closure-factory-captured-array-cow',
  'checks': ['S = __FULL__',
             'S.COMPLETION = NORMAL',
             '$outputs(S.EVENTS) = ([50,57,55])',
             'S.OBJECTS = [pobject_dead,REALCLOSURE porigin pitem* pstaticcell*]',
             '~((HOBJECT 0) <- S.ALLOCATIONS)',
             '(HOBJECT 1) <- S.ALLOCATIONS',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S_changed = S[.OBJECTS = [REALCLOSURE (PORIGIN 999 eps) ([ALIAS 999]) eps,REALCLOSURE '
             'porigin pitem* pstaticcell*]]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': '31578dcd1b145f35b4ca03e415b43046da750e89e47f39bf54b6e72d9b187baa'},
 {'id': 'reject-non-template-live-origin',
  'source': 'closure-factory-captured-array-cow',
  'checks': ['S = __FULL__',
             'S.COMPLETION = NORMAL',
             '$outputs(S.EVENTS) = ([50,57,55])',
             'S.OBJECTS = [pobject_dead,REALCLOSURE porigin pitem* pstaticcell*]',
             '~((HOBJECT 0) <- S.ALLOCATIONS)',
             '(HOBJECT 1) <- S.ALLOCATIONS',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S_changed = S[.OBJECTS = [pobject_dead,REALCLOSURE (PORIGIN 0 eps) pitem* pstaticcell*]]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '~$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': '23ece9f375294ce353b69b909a6b3a98adb242162a55d134a841f4432e1aff4a'},
 {'id': 'reject-incomplete-finished-capture',
  'source': 'closure-factory-captured-array-cow',
  'checks': ['S = __FULL__',
             'S.COMPLETION = NORMAL',
             '$outputs(S.EVENTS) = ([50,57,55])',
             'S.OBJECTS = [pobject_dead,REALCLOSURE porigin pitem* pstaticcell*]',
             '~((HOBJECT 0) <- S.ALLOCATIONS)',
             '(HOBJECT 1) <- S.ALLOCATIONS',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S_changed = S[.OBJECTS = [pobject_dead,REALCLOSURE porigin ([UNINITIALIZED]) '
             'pstaticcell*]]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '~$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': '885d5d6a14947ef8e9c2c8aee1292f93e60200de8ed9371d8b565687c80526c6'},
 {'id': 'reject-extra-capture-slot',
  'source': 'closure-factory-captured-array-cow',
  'checks': ['S = __FULL__',
             'S.COMPLETION = NORMAL',
             '$outputs(S.EVENTS) = ([50,57,55])',
             'S.OBJECTS = [pobject_dead,REALCLOSURE porigin pitem* pstaticcell*]',
             '~((HOBJECT 0) <- S.ALLOCATIONS)',
             '(HOBJECT 1) <- S.ALLOCATIONS',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S_changed = S[.OBJECTS = [pobject_dead,REALCLOSURE porigin (pitem* ++ [DIRECT (PINT 99)]) '
             'pstaticcell*]]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '~$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': '62773fa0c494b05637d4e45c77e3343146349bfbd7ce02c4f6f12017438bbe08'},
 {'id': 'reject-capture-source-origin',
  'source': 'closure-factory-captured-array-cow',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_seek(S_initial[.COMPLETION = NORMAL], 0, 512)',
             '$review_stage(S, 0)',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S.TODO = (CLOSURE_CAPTURE 1 0) :: ptask_tail*',
             'S.OBJECTS[1] = REALCLOSURE porigin_template pitem* pstaticcell*',
             'pitem* = [UNINITIALIZED]',
             'S_changed = S[.ORIGIN = (PORIGIN 0 eps)]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '~$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': '96e8ad3018c57951ed736689696c6a73afc107881fa734277568918cb806c931'},
 {'id': 'reject-skipped-capture-cursor',
  'source': 'closure-factory-captured-array-cow',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_seek(S_initial[.COMPLETION = NORMAL], 0, 512)',
             '$review_stage(S, 0)',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S.TODO = (CLOSURE_CAPTURE 1 0) :: ptask_tail*',
             'S.OBJECTS[1] = REALCLOSURE porigin_template pitem* pstaticcell*',
             'pitem* = [UNINITIALIZED]',
             'S_changed = S[.TODO = (CLOSURE_CAPTURE 1 1) :: ptask_tail*]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '~$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': '751d5a9a2636e87e35a65fdb502ba35b3ccb862b6e7ffa7cbb06ad6ecc82fca7'},
 {'id': 'legitimate-completed-capture-value',
  'source': 'closure-factory-captured-array-cow',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_seek(S_initial[.COMPLETION = NORMAL], 0, 512)',
             '$review_stage(S, 0)',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S.TODO = (CLOSURE_CAPTURE 1 0) :: ptask_tail*',
             'S.OBJECTS[1] = REALCLOSURE porigin_template pitem* pstaticcell*',
             'pitem* = [UNINITIALIZED]',
             'S_changed = S[.OBJECTS = $object_set(S.OBJECTS, 1, REALCLOSURE porigin_template ([DIRECT '
             '(PINT 99)]) pstaticcell*)][.TODO = (CLOSURE_CAPTURE 1 1) :: ptask_tail*]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': 'e6b81d5307a1ab7722a30331309036c60d8e11e94d0119433d130b84f0119622'},
 {'id': 'reject-plain-template-pending-target',
  'source': 'closure-selected-target-global-argument-unset',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_seek(S_initial[.COMPLETION = NORMAL], 1, 512)',
             '$review_stage(S, 1)',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S.TODO = (CALL_ARGS (CLOSURE_TARGET n_object) phpType7* n_arg poperand* porigin_site? z) '
             ':: ptask_tail*',
             'S.OBJECTS[n_object] = REALCLOSURE porigin_template pitem* pstaticcell*',
             'S_changed = S[.TODO = (CALL_ARGS porigin_template phpType7* n_arg poperand* porigin_site? '
             'z) :: ptask_tail*]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '~$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': 'c6e1a20bb1eee2eaab51bdfd1a912305e683d46b89d2788c4feadc3e124f38b3'},
 {'id': 'legitimate-alternative-live-instance',
  'source': 'closure-selected-target-global-argument-unset',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_seek(S_initial[.COMPLETION = NORMAL], 1, 512)',
             '$review_stage(S, 1)',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S.TODO = (CALL_ARGS (CLOSURE_TARGET n_object) phpType7* n_arg poperand* porigin_site? z) '
             ':: ptask_tail*',
             'S.OBJECTS[n_object] = REALCLOSURE porigin_template pitem* pstaticcell*',
             'n_new = |S.OBJECTS|',
             'S_changed = S[.OBJECTS = S.OBJECTS ++ [S.OBJECTS[n_object]]][.ALLOCATIONS = S.ALLOCATIONS '
             '++ [HOBJECT n_new]][.TODO = (CALL_ARGS (CLOSURE_TARGET n_new) phpType7* n_arg poperand* '
             'porigin_site? z) :: ptask_tail*]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': '257a366a9e6ca8cf858d955b69b95ea2d9d0ccf0e5915c502d51bf7731a1f06e'},
 {'id': 'reject-current-instance-absent',
  'source': 'closure-selected-target-global-argument-unset',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_seek(S_initial[.COMPLETION = NORMAL], 2, 512)',
             '$review_stage(S, 2)',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S.CURRENT = (pcallcontext)',
             'pcallcontext.INSTANCE = (n_object)',
             'S_changed = S[.CURRENT = (pcallcontext[.INSTANCE = eps])]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '~$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': 'a63c5975e67dc9731cb1346f35d8745e486ba0d6ce2f79817deb743b8e4f6788'},
 {'id': 'legitimate-saved-target-after-global-unset',
  'source': 'closure-selected-target-global-argument-unset',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_seek(S_initial[.COMPLETION = NORMAL], 3, 512)',
             '$review_stage(S, 3)',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S.CURRENT = (pcallcontext)',
             'pcallcontext.INSTANCE = eps',
             '(HOBJECT 0) <- S.ALLOCATIONS',
             'S.FRAMES =/= eps'],
  'predicate': '$call_descriptors_valid(S)',
  'original_fixture_sha256': '25e6970e87fbec26b15b69f9cc42c3e0ff607f07cffa94d46b5d4bd9072023ff'},
 {'id': 'reject-named-context-instance',
  'source': 'closure-selected-target-global-argument-unset',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_seek(S_initial[.COMPLETION = NORMAL], 3, 512)',
             '$review_stage(S, 3)',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S.CURRENT = (pcallcontext)',
             'pcallcontext.INSTANCE = eps',
             'S_changed = S[.CURRENT = (pcallcontext[.INSTANCE = (0)])]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '~$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': '4d37703fcda7f94935b7c082f47349aca4a3e3fbf20fcf4cf74defdb57c6cfe3'},
 {'id': 'reject-closure-static-as-main-source',
  'source': 'closure-selected-target-global-argument-unset',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_seek(S_initial[.COMPLETION = NORMAL], 4, 512)',
             '$review_stage(S, 4)',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S.STATICS = eps',
             'S.OBJECTS[0] = REALCLOSURE porigin_template pitem* pstaticcell*',
             'pstaticcell* = [pstaticcell_one]'],
  'predicate': '~$main_static_origin(S, pstaticcell_one.ORIGIN)',
  'original_fixture_sha256': '0388fada7b74d33eeef93b70e898eb79f31329a41251d5e9f3f28c0987bdba52'},
 {'id': 'reject-instance-slot-as-request-static',
  'source': 'closure-selected-target-global-argument-unset',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_seek(S_initial[.COMPLETION = NORMAL], 4, 512)',
             '$review_stage(S, 4)',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S.STATICS = eps',
             'S.OBJECTS[0] = REALCLOSURE porigin_template pitem* pstaticcell*',
             'pstaticcell* = [pstaticcell_one]',
             'S_changed = S[.STATICS = [pstaticcell_one]]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '~$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': '04c43a3a780febfe443cd9cda0001e58cbf3ad698e2923e3c06f227817785d6d'},
 {'id': 'reject-shared-wrapper-between-instances',
  'source': 'closure-instance-static-counters',
  'checks': ['S = __FULL__',
             'S.COMPLETION = NORMAL',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S.CURRENT = eps',
             'S.OBJECTS[0] = REALCLOSURE porigin_a pitem_a* pstaticcell_a*',
             'pstaticcell_a* = [pstaticcell_first]',
             'S.OBJECTS[1] = REALCLOSURE porigin_b pitem_b* pstaticcell_b*',
             'pstaticcell_b* = [pstaticcell_second]',
             'pstaticcell_first.CELL =/= pstaticcell_second.CELL',
             'pstaticcell_forged = pstaticcell_second[.CELL = pstaticcell_first.CELL]',
             'S_changed = $prune_allocations(S[.OBJECTS = $object_set(S.OBJECTS, 1, REALCLOSURE '
             'porigin_b pitem_b* ([pstaticcell_forged]))])',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '~$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': '4493c9d6277dbee20e89681b28c3e1a6caed9d1b25463877b965cdcf6a055eb6'},
 {'id': 'legitimate-equal-values-distinct-static-wrappers',
  'source': 'closure-instance-static-counters',
  'checks': ['S = __FULL__',
             'S.COMPLETION = NORMAL',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S.CURRENT = eps',
             'S.OBJECTS[0] = REALCLOSURE porigin_a pitem_a* pstaticcell_a*',
             'pstaticcell_a* = [pstaticcell_first]',
             'S.OBJECTS[1] = REALCLOSURE porigin_b pitem_b* pstaticcell_b*',
             'pstaticcell_b* = [pstaticcell_second]',
             'pstaticcell_first.CELL =/= pstaticcell_second.CELL',
             'S_changed = S[.STORE = $set_cell(S.STORE, pstaticcell_second.CELL, '
             'S.STORE[pstaticcell_first.CELL])]',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': '171cf3e9c3ed6c109c019f8542bd06111df9b9a429e6e03a14e7d2362e67cdbe'},
 {'id': 'reject-instance-wrapper-shared-with-request',
  'source': 'closure-nested-named-scope',
  'checks': ['S = __FULL__',
             'S.COMPLETION = NORMAL',
             '$heap_valid($heap_graph(S))',
             '$call_descriptors_valid(S)',
             'S.CURRENT = eps',
             'S.OBJECTS[0] = REALCLOSURE porigin_a pitem_a* pstaticcell_a*',
             'pstaticcell_a* = [pstaticcell_first]',
             'S.STATICS = [pstaticcell_named]',
             'pstaticcell_first.CELL =/= pstaticcell_named.CELL',
             'pstaticcell_forged = pstaticcell_first[.CELL = pstaticcell_named.CELL]',
             'S_changed = $prune_allocations(S[.OBJECTS = $object_set(S.OBJECTS, 0, REALCLOSURE '
             'porigin_a pitem_a* ([pstaticcell_forged]))])',
             '$heap_valid($heap_graph(S_changed))'],
  'predicate': '~$call_descriptors_valid(S_changed)',
  'original_fixture_sha256': '52f04671dd1f296ea11517ab690cbe29c288034c5df6bf4c4eaa9eeabbba3479'},
 {'id': 'closure-named-default-signature',
  'source': 'closure-named-default-signature',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_seek(S_initial[.COMPLETION = NORMAL], 5, 512)',
             '$heap_valid($heap_graph(S))',
             'S.CURRENT = (pcallcontext)',
             'pcallcontext.INSTANCE = (n_object)',
             'S.TODO = (NAMED_PREFLIGHT porigin n) :: ptask*',
             'pcallcontext.FUNCTION = porigin',
             'S.OBJECTS[n_object] = REALCLOSURE porigin pitem* pstaticcell*'],
  'predicate': '$call_descriptors_valid(S)',
  'original_fixture_sha256': 'c67afae6a37c450585444d756e8f60623879775546e3367159fb640fbd470aad'},
 {'id': 'closure-unpack-reference-signature',
  'source': 'closure-unpack-reference-signature',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_seek(S_initial[.COMPLETION = NORMAL], 5, 512)',
             '$heap_valid($heap_graph(S))',
             'S.CURRENT = (pcallcontext)',
             'pcallcontext.INSTANCE = (n_object)',
             'S.TODO = (NAMED_PREFLIGHT porigin n) :: ptask*',
             'pcallcontext.FUNCTION = porigin',
             'S.OBJECTS[n_object] = REALCLOSURE porigin pitem* pstaticcell*'],
  'predicate': '$call_descriptors_valid(S)',
  'original_fixture_sha256': 'ad6b9d65b9ba101c5baff46b5c72748ef256c0cbcf75b414ebe0288911ab245e'}]
D=Path(tempfile.mkdtemp(prefix='closures-protocol-',dir=R/'.tools'))
(D/'producer.py').write_bytes(Path(__file__).read_bytes())
before=q.t.syntax_validation.implementation_fingerprint()
(D/'inputs.json').write_text(json.dumps({'fingerprint':before},indent=2));print(D,flush=True)
modules=[R/p for p in json.loads((R/'spec/semantics/modules.json').read_text())]
runner=R/'tests/semantics/_build/default/numeric_runner.exe'
f=a=None;initials={};fulls={};originals=[];records=[]
try:
 f=Worker([str(q.t.PHP),'-n',*q.t.FLAGS,'-d','extension='+str(R/'.tools/php-file.so'),str(R/'frontend/worker.php')],D/'frontend-wire')
 a=Worker([str(R/'_build/default/adapter/main.exe'),str(R)],D/'adapter-wire')
 for name,source64 in SOURCES.items():
  directory=D/name;directory.mkdir();path=directory/'source.php';path.write_bytes(base64.b64decode(source64))
  payload=directory/'request.input';payload.write_bytes(q.packet(1700000000,125000,[b'LC_ALL=C',b'TZ=UTC',b'FIRST=one']))
  request={'env':[[q.b64(k),q.b64(v)] for k,v in [(b'LC_ALL',b'C'),(b'TZ',b'UTC'),(b'FIRST',b'one')]],'argv':[q.b64(os.fsencode(path))],'file':q.b64(os.fsencode(path)),'seconds':'1700000000','microseconds':125000,'variables':q.b64(b'EGPCS'),'jit':True,'cwd':q.b64(os.fsencode(directory))}
  parsed=f.request({'op':'parse','source':source64});assert parsed['accepted']
  checked=a.request({'op':'check','ast':parsed['ast'],'fixture':True});(directory/'checked.json').write_text(json.dumps(checked))
  originals.append({'id':name,'source_base64':source64,'context':str(path),'request':request});(D/'originals.json').write_text(json.dumps(originals,indent=2))
  initials[name]='$php_request_run('+checked['fixture']+', 0, '+json.dumps(q.b64(os.fsencode(path)))+', '+rs.request_fixture(request)+')'
  fulls[name]='$php_request_run('+checked['fixture']+', 10000, '+json.dumps(q.b64(os.fsencode(path)))+', '+rs.request_fixture(request)+')'
finally:
 try:
  if f:f.close()
 finally:
  if a:a.close()
for case in CASES:
 checks=[s.replace('__INITIAL__',initials[case['source']]).replace('__FULL__',fulls[case['source']]) for s in case['checks']]
 fixture=D/(case['id']+'.watsup');fixture.write_text(PREFIX+'\ndec $main() : bool\ndef $main() = '+case['predicate']+'\n'+''.join('  -- if '+s+'\n' for s in checks))
 command=[str(runner),*map(str,modules),str(fixture)];(D/(case['id']+'.command.json')).write_text(json.dumps(command))
 try:
  z=subprocess.run(command,capture_output=True,timeout=900)
 except subprocess.TimeoutExpired as e:
  (D/(case['id']+'.stdout')).write_bytes(e.stdout or b'');(D/(case['id']+'.stderr')).write_bytes(e.stderr or b'');(D/(case['id']+'.status.json')).write_text(json.dumps({'status':'timeout','seconds':900}));raise
 (D/(case['id']+'.stdout')).write_bytes(z.stdout);(D/(case['id']+'.stderr')).write_bytes(z.stderr);(D/(case['id']+'.status.json')).write_text(json.dumps({'status':'exit','exit_status':z.returncode}))
 record={'id':case['id'],'source':case['source'],'assertions':len(checks)+1,'pass':z.returncode==0 and z.stdout.strip()==b'true' and not z.stderr};records.append(record);(D/'results.json').write_text(json.dumps(records,indent=2));print(record,flush=True)
assert before==q.t.syntax_validation.implementation_fingerprint()
report={'result':'pass' if all(r['pass'] for r in records) else 'fail','scope':'Twenty real-closure finite source/object/capture/target/static/preflight controls, retaining original predicates and replacing only checked source/request initializers. Arbitrary consistent values, dead backing and independently selected instances remain valid. No native execution or history reconstruction','fingerprint':before,'raw':str(D),'sources':len(originals),'cases':len(records),'assertions':sum(r['assertions'] for r in records),'records':records}
(D/'report.json').write_text(json.dumps(report,indent=2));target=R/'coverage/semantics/closures-protocol.json';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(json.dumps(report,indent=2));assert report['result']=='pass'
