#!/usr/bin/env python3
"""Nested receiver-free creation, retained receivers, and borrowed clone evidence."""
from pathlib import Path
import json

import closure_call_protocol as protocol
import closure_static_owner_protocol as retained
import rebound_called_class_protocol as methods

ROOT = Path(__file__).resolve().parents[2]
CATALOGUE = ROOT / 'tests/semantics/closure_receiver_creation_cases.json'
SOURCES = {row['id']: row['source'] for row in json.loads(CATALOGUE.read_text())}
CAPTURE = ('S.TODO = (CLOSURE_CAPTURE n_child n_slot) :: ptask_tail* '
           '-- if S.CURRENT = (pcallcontext) '
           '-- if $function_at(S.CLOSURETEMPLATES, pcallcontext.FUNCTION) = (pfunction_parent) '
           '-- if S.OBJECTS[n_child] = REALCLOSURE porigin_child pitem* pstaticcell* '
           '-- if $closure_nearest_owner(S, $closure_creation_owners($all_functions(S), porigin_child), eps) = (pcallcontext.FUNCTION)')
CALL = ('S.TODO = (CALL_ARGS (CLOSURE_TARGET n_child) phpType7* n_arg '
        'poperand* porigin_site? z) :: ptask_tail* '
        '-- if $closure_scope_at(S.CLOSURESCOPES, n_child) = (pclosurescope)')

CASES = {
    'nested-free-active-creation': {
        'source': SOURCES['nested-free-clone-retired'], 'stage': CAPTURE,
        'checks': [
            '$function_at(S.CLOSURETEMPLATES, porigin_child) = (pfunction_child)',
            '~$closure_static(S, pfunction_child)',
            'pcallcontext.INSTANCE = (n_parent)',
            '$closure_scope_at(S.CLOSURESCOPES, n_parent) = (pclosurescope_parent)',
            '$closure_scope_at(S.CLOSURESCOPES, n_child) = (pclosurescope)',
            'S.CLOSURESCOPES = [pclosurescope_parent, pclosurescope]',
            'pclosurescope.CREATION = (pclosurecreation)',
            'pclosurecreation.FUNCTION = pcallcontext.FUNCTION',
            'pcallcontext.CALLSITE = (pclosurecreation.CALLSITE)',
            '~pclosurecreation.RECEIVER',
            'pclosurescope.RECEIVER = eps',
            'pclosurescope_parent.CREATION = eps',
            '$closure_static_method_owner(S, pfunction_parent.ORIGIN)',
            '$closure_receiver_free_ancestry(S, porigin_child)',
            '$closure_nearest_owner(S, $closure_creation_owners($all_functions(S), pfunction_parent.ORIGIN), eps) = (porigin_method)',
            '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
            '~$closure_receiver_free_ancestry(S, porigin_method)',
            '$closure_bound_receiver(S, pfunction_child) = eps',
            '$closure_creation_stamp(S, pfunction_child) = (pclosurecreation)',
            '$closure_scope_creation_valid(S, porigin_child, pclosurescope)',
            '$closure_capture_scope_valid(S, pfunction_child, n_child)',
            '$call_task_valid(S, CLOSURE_CAPTURE n_child n_slot)',
            '$call_current_valid(S)', '$closure_state_valid(S)',
            '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))',
            '$node_children(S, HOBJECT n_child) = eps',
            'pclosurescope_bad = pclosurescope[.CREATION = eps]',
            'S_bad = S[.CLOSURESCOPES = [pclosurescope_parent, pclosurescope_bad]]',
            '$heap_valid($heap_graph(S_bad))',
            '~$closure_scope_row_valid(S_bad, pclosurescope_bad)',
            '~$call_task_valid(S_bad, CLOSURE_CAPTURE n_child n_slot)',
            '~$call_descriptors_valid(S_bad)',
            '~$closure_scope_creation_valid(S, porigin_child, pclosurescope[.CREATION = (pclosurecreation[.RECEIVER = true])])',
            '~$closure_scope_creation_valid(S, porigin_child, pclosurescope[.CREATION = (pclosurecreation[.FUNCTION = porigin_child])])',
            '~$closure_scope_creation_valid(S, porigin_child, pclosurescope[.CREATION = (pclosurecreation[.CALLSITE = porigin_child])])',
            '~$closure_capture_scope_valid(S[.CURRENT = eps], pfunction_child, n_child)',
            'S_forged = S_bad[.CURRENT = (pcallcontext[.NAME = $ptascii("forged")])]',
            '~$call_current_valid(S_forged)',
            '$closure_creation_scope(S_forged, porigin_child)',
            '$closure_creation_stamp(S_forged, pfunction_child) = eps',
            '~$closure_capture_scope_valid(S_forged, pfunction_child, n_child)',
            '~$call_task_valid(S_forged, CLOSURE_CAPTURE n_child n_slot)',
        ],
    },
    'nested-free-clone-retirement': {
        'source': SOURCES['nested-free-clone-retired'],
        'stage': 'S.TODO = (CLONE_RESULT porigin_clone z_clone) :: ptask_tail*',
        'checks': [
            'S_read = $resolve(S, S.RESULT)',
            'S_read.RESULT = KNOWN (POBJECT n_old)',
            '$closure_scope_at(S.CLOSURESCOPES, n_old) = (pclosurescope)',
            'pclosurescope.CREATION = (pclosurecreation)',
            '~pclosurecreation.RECEIVER', 'pclosurescope.RECEIVER = eps',
            '$lookup(S.ENV, $ptascii("c")) = (n_cell_c)',
            'S.STORE[n_cell_c] = DEFINED (POBJECT n_parent)',
            '$closure_scope_row_valid(S, pclosurescope)',
            '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))',
            'S_copy = $drive_steps(S, 1)[.COMPLETION = NORMAL]',
            'S_copy.RESULT = KNOWN (POBJECT n_copy)', 'n_copy =/= n_old',
            '$clone_same_kind(S.OBJECTS[n_old], S_copy.OBJECTS[n_copy])',
            '$closure_scope_at(S_copy.CLOSURESCOPES, n_copy) = (pclosurescope[.OBJECT = n_copy])',
            '$node_children(S_copy, HOBJECT n_copy) = eps',
            '$closure_state_valid(S_copy)', '$call_descriptors_valid(S_copy)',
            '$heap_valid($heap_graph(S_copy))',
            'S_done = $drive(S_copy, 1000)', 'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT ([49])]',
            '$lookup(S_done.ENV, $ptascii("copy")) = (n_cell_copy)',
            'S_done.STORE[n_cell_copy] = DEFINED (POBJECT n_copy)',
            '$lookup(S_done.ENV, $ptascii("inner")) = (n_cell_inner)',
            'S_done.STORE[n_cell_inner] = DEFINED PNULL',
            'S_done.STORE[n_cell_c] = DEFINED PNULL',
            '~((HOBJECT n_old) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_parent) <- S_done.ALLOCATIONS)',
            '$closure_scope_at(S_done.CLOSURESCOPES, n_copy) = (pclosurescope[.OBJECT = n_copy])',
            '$node_children(S_done, HOBJECT n_copy) = eps',
            '$closure_scope_row_valid(S_done, pclosurescope[.OBJECT = n_copy])',
            '~$closure_scope_row_valid(S_done, pclosurescope[.OBJECT = n_copy][.CREATION = eps])',
            '~$closure_scope_row_valid(S_done, pclosurescope[.OBJECT = n_copy][.CREATION = (pclosurecreation[.RECEIVER = true])])',
            '$closure_state_valid(S_done)', '$call_descriptors_valid(S_done)',
            '$heap_valid($heap_graph(S_done))',
        ],
    },
    'arrow-ancestry-after-retirement': {
        'source': SOURCES['nested-free-arrow-chain'],
        'stage': (CALL + ' -- if pclosurescope.CREATION = (pclosurecreation) '
                  '-- if $origin_node(S.SOURCES, pclosurecreation.FUNCTION) = (NExprArrowFunction phpType14 (BOOLEAN false) phpType4_ref phpType16 phpType18 expression metadata)'),
        'checks': [
            'S.OBJECTS[n_child] = REALCLOSURE porigin_child pitem* pstaticcell*',
            'pclosurescope.CREATION = (pclosurecreation)',
            'pclosurescope.RECEIVER = eps', '~pclosurecreation.RECEIVER',
            '$closure_nearest_owner(S, $closure_creation_owners($all_functions(S), porigin_child), eps) = (pclosurecreation.FUNCTION)',
            '$function_at(S.CLOSURETEMPLATES, pclosurecreation.FUNCTION) = (pfunction_parent)',
            '$origin_node(S.SOURCES, pfunction_parent.ORIGIN) = (NExprArrowFunction phpType14 (BOOLEAN false) phpType4_ref phpType16 phpType18 expression metadata)',
            '$closure_nearest_owner(S, $closure_creation_owners($all_functions(S), pfunction_parent.ORIGIN), eps) = (porigin_outer)',
            '$closure_static_method_owner(S, porigin_outer)',
            '~$closure_static_method_owner(S, porigin_child)',
            '~$closure_receiver_forbidden(S, porigin_child)',
            '$closure_receiver_free_ancestry(S, porigin_child)',
            '$lookup(S.ENV, $ptascii("c")) = (n_cell_c)',
            'S.STORE[n_cell_c] = DEFINED PNULL',
            '$lookup(S.ENV, $ptascii("middle")) = (n_cell_middle)',
            'S.STORE[n_cell_middle] = DEFINED PNULL',
            'S.CLOSURESCOPES = [pclosurescope]',
            '$node_children(S, HOBJECT n_child) = eps',
            '$closure_scope_row_valid(S, pclosurescope)',
            '$call_task_valid(S, CALL_ARGS (CLOSURE_TARGET n_child) phpType7* n_arg poperand* porigin_site? z)',
            '$closure_state_valid(S)', '$call_descriptors_valid(S)',
            '$heap_valid($heap_graph(S))',
            '~$closure_scope_creation_valid(S, porigin_child, pclosurescope[.CREATION = eps])',
            '~$closure_scope_creation_valid(S, porigin_child, pclosurescope[.CREATION = (pclosurecreation[.FUNCTION = porigin_outer])])',
        ],
    },
    'static-child-effective-receiver-at-creation': {
        'source': SOURCES['static-child-discards-active-receiver'], 'stage': CAPTURE,
        'checks': [
            '$function_at(S.CLOSURETEMPLATES, porigin_child) = (pfunction_child)',
            '$closure_static(S, pfunction_child)',
            '~$closure_static(S, pfunction_parent)',
            'pcallcontext.RECEIVER = (n_receiver)',
            'S.OBJECTS[n_receiver] = INSTANCE porigin_class',
            '(HOBJECT n_receiver) <- S.ALLOCATIONS',
            '$closure_bound_receiver(S, pfunction_child) = eps',
            '$closure_scope_at(S.CLOSURESCOPES, n_child) = (pclosurescope)',
            'pclosurescope.RECEIVER = eps',
            'pclosurescope.CREATION = (pclosurecreation)',
            '~pclosurecreation.RECEIVER',
            'pclosurecreation.FUNCTION = pcallcontext.FUNCTION',
            'pcallcontext.CALLSITE = (pclosurecreation.CALLSITE)',
            '$closure_creation_stamp(S, pfunction_child) = (pclosurecreation)',
            '$closure_receiver_forbidden(S, porigin_child)',
            '$node_children(S, HOBJECT n_child) = eps',
            '$closure_scope_creation_valid(S, porigin_child, pclosurescope)',
            '$closure_scope_row_valid(S, pclosurescope)',
            '$closure_capture_scope_valid(S, pfunction_child, n_child)',
            '$call_task_valid(S, CLOSURE_CAPTURE n_child n_slot)',
            '$call_current_valid(S)', '$closure_state_valid(S)',
            '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))',
            '~$closure_scope_creation_valid(S, porigin_child, pclosurescope[.CREATION = (pclosurecreation[.RECEIVER = true])])',
            '~$closure_capture_scope_valid(S[.CLOSURESCOPES = $closure_scopes_prune(S.CLOSURESCOPES, [HOBJECT n_receiver])], pfunction_child, n_child)',
        ],
    },
    'static-child-after-receiver-retirement': {
        'source': SOURCES['static-child-discards-active-receiver'], 'stage': CALL,
        'checks': [
            'S.OBJECTS[n_child] = REALCLOSURE porigin_child pitem* pstaticcell*',
            '$function_at(S.CLOSURETEMPLATES, porigin_child) = (pfunction_child)',
            '$closure_static(S, pfunction_child)',
            'pclosurescope.CREATION = (pclosurecreation)',
            '~pclosurecreation.RECEIVER', 'pclosurescope.RECEIVER = eps',
            'S.OBJECTS[0] = INSTANCE pclosurescope.CALLED',
            '~((HOBJECT 0) <- S.ALLOCATIONS)',
            '$lookup(S.ENV, $ptascii("r")) = (n_cell_r)',
            'S.STORE[n_cell_r] = DEFINED (PSTRING ([115]))',
            '$propref_at(S.PROPREFS, n_cell_r) = eps',
            '$lookup(S.ENV, $ptascii("a")) = (n_cell_a)',
            'S.STORE[n_cell_a] = DEFINED PNULL',
            '$lookup(S.ENV, $ptascii("bound")) = (n_cell_bound)',
            'S.STORE[n_cell_bound] = DEFINED PNULL',
            '$lookup(S.ENV, $ptascii("c")) = (n_cell_c)',
            'S.STORE[n_cell_c] = DEFINED PNULL',
            'S.EVENTS = [OUTPUT ([87])]',
            'S.CLOSURESCOPES = [pclosurescope]',
            '$node_children(S, HOBJECT n_child) = eps',
            '$closure_scope_row_valid(S, pclosurescope)',
            '$call_task_valid(S, CALL_ARGS (CLOSURE_TARGET n_child) phpType7* n_arg poperand* porigin_site? z)',
            '$closure_state_valid(S)', '$call_descriptors_valid(S)',
            '$heap_valid($heap_graph(S))',
        ],
    },
    'instance-owned-nested-receiver': {
        'source': SOURCES['instance-owned-nested-receiver'],
        'stage': (CALL + ' -- if pclosurescope.CREATION = (pclosurecreation)'),
        'checks': [
            'S.OBJECTS[n_child] = REALCLOSURE porigin_child pitem* pstaticcell*',
            'pclosurescope.RECEIVER = (n_receiver)', 'pclosurecreation.RECEIVER',
            '$function_at(S.CLOSURETEMPLATES, pclosurecreation.FUNCTION) = (pfunction_parent)',
            '$closure_nearest_owner(S, $closure_creation_owners($all_functions(S), pfunction_parent.ORIGIN), eps) = (porigin_method)',
            '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
            '~pmethoddesc.STATIC',
            '~$closure_receiver_free_ancestry(S, porigin_child)',
            '~$closure_receiver_forbidden(S, porigin_child)',
            '$lookup(S.ENV, $ptascii("c")) = (n_cell_c)',
            'S.STORE[n_cell_c] = DEFINED (POBJECT n_parent)',
            '$closure_scope_at(S.CLOSURESCOPES, n_parent) = (pclosurescope_parent)',
            'pclosurescope_parent.RECEIVER = (n_receiver)',
            'pclosurescope_parent.CREATION = eps',
            'S.CLOSURESCOPES = [pclosurescope_parent, pclosurescope]',
            '$node_children(S, HOBJECT n_child) = [HOBJECT n_receiver]',
            '$closure_scope_row_valid(S, pclosurescope)',
            '$call_task_valid(S, CALL_ARGS (CLOSURE_TARGET n_child) phpType7* n_arg poperand* porigin_site? z)',
            '$closure_state_valid(S)', '$call_descriptors_valid(S)',
            '$heap_valid($heap_graph(S))',
            'pclosurescope_bad = pclosurescope[.RECEIVER = eps]',
            'S_bad = S[.CLOSURESCOPES = [pclosurescope_parent, pclosurescope_bad]]',
            '$heap_valid($heap_graph(S_bad))',
            '~$closure_scope_creation_valid(S_bad, porigin_child, pclosurescope_bad)',
            '~$closure_scope_row_valid(S_bad, pclosurescope_bad)',
            '~$closure_state_valid(S_bad)', '~$call_descriptors_valid(S_bad)',
        ],
    },
    **retained.CASES,
    'method-wrapper-rejects-creation-tuple': {
        'source': methods.CASES['eps-lexical-keeps-called-class']['source'],
        'stage': methods.CASES['eps-lexical-keeps-called-class']['stage'],
        'checks': [
            *methods.CASES['eps-lexical-keeps-called-class']['checks'],
            'pclosurescope.CREATION = eps',
            'S_after.CLOSURESCOPES = [pclosurescope]',
            'pclosurescope_bad_creation = pclosurescope[.CREATION = ({FUNCTION pcallcontext.FUNCTION, CALLSITE porigin_call, RECEIVER false})]',
            'S_bad_creation = S_after[.CLOSURESCOPES = [pclosurescope_bad_creation]]',
            '$target_function(S_bad_creation, CLOSURE_TARGET n_capture) = (pmethoddesc.FUNCTION)',
            '$heap_valid($heap_graph(S_bad_creation))',
            '~$closure_scope_row_valid(S_bad_creation, pclosurescope_bad_creation)',
            '~$closure_state_valid(S_bad_creation)',
            '~$call_descriptors_valid(S_bad_creation)',
        ],
    },
}

if __name__ == '__main__':
    protocol.run(CASES, (Path(__file__), CATALOGUE, Path(retained.__file__), retained.CATALOGUE,
                        Path(methods.__file__), methods.CATALOGUE,
                        ROOT / 'tests/semantics/profile.json', ROOT / '.tools/request-clock.so'))
