#!/usr/bin/env python3
"""Compound assignment values, captured locations, diagnostics and resumption."""
import base64, json, re, subprocess, sys, tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'tests/semantics'))
import static_types as types

NORMAL_CASES = {
    'rebased-+=-5-2': b'<?php $a=5;echo ($a += 2);echo ":",$a;',
    'rebased-+=-"5"-"2"': b'<?php $a="5";echo ($a += "2");echo ":",$a;',
    'rebased-+=-null-2': b'<?php $a=null;echo ($a += 2);echo ":",$a;',
    'rebased-+=-1.5-2': b'<?php $a=1.5;echo ($a += 2);echo ":",$a;',
    'rebased--=-5-2': b'<?php $a=5;echo ($a -= 2);echo ":",$a;',
    'rebased--=-"5"-"2"': b'<?php $a="5";echo ($a -= "2");echo ":",$a;',
    'rebased--=-null-2': b'<?php $a=null;echo ($a -= 2);echo ":",$a;',
    'rebased--=-1.5-2': b'<?php $a=1.5;echo ($a -= 2);echo ":",$a;',
    'rebased-*=-5-2': b'<?php $a=5;echo ($a *= 2);echo ":",$a;',
    'rebased-*=-"5"-"2"': b'<?php $a="5";echo ($a *= "2");echo ":",$a;',
    'rebased-*=-null-2': b'<?php $a=null;echo ($a *= 2);echo ":",$a;',
    'rebased-*=-1.5-2': b'<?php $a=1.5;echo ($a *= 2);echo ":",$a;',
    'rebased-/=-5-2': b'<?php $a=5;echo ($a /= 2);echo ":",$a;',
    'rebased-/=-"5"-"2"': b'<?php $a="5";echo ($a /= "2");echo ":",$a;',
    'rebased-/=-null-2': b'<?php $a=null;echo ($a /= 2);echo ":",$a;',
    'rebased-/=-1.5-2': b'<?php $a=1.5;echo ($a /= 2);echo ":",$a;',
    'rebased-%=-5-2': b'<?php $a=5;echo ($a %= 2);echo ":",$a;',
    'rebased-%=-"5"-"2"': b'<?php $a="5";echo ($a %= "2");echo ":",$a;',
    'rebased-%=-null-2': b'<?php $a=null;echo ($a %= 2);echo ":",$a;',
    'rebased-%=-1.5-2': b'<?php $a=1.5;echo ($a %= 2);echo ":",$a;',
    'rebased-**=-5-2': b'<?php $a=5;echo ($a **= 2);echo ":",$a;',
    'rebased-**=-"5"-"2"': b'<?php $a="5";echo ($a **= "2");echo ":",$a;',
    'rebased-**=-null-2': b'<?php $a=null;echo ($a **= 2);echo ":",$a;',
    'rebased-**=-1.5-2': b'<?php $a=1.5;echo ($a **= 2);echo ":",$a;',
    'rebased-<<=-5-2': b'<?php $a=5;echo ($a <<= 2);echo ":",$a;',
    'rebased-<<=-"5"-"2"': b'<?php $a="5";echo ($a <<= "2");echo ":",$a;',
    'rebased-<<=-null-2': b'<?php $a=null;echo ($a <<= 2);echo ":",$a;',
    'rebased-<<=-1.5-2': b'<?php $a=1.5;echo ($a <<= 2);echo ":",$a;',
    'rebased->>=-5-2': b'<?php $a=5;echo ($a >>= 2);echo ":",$a;',
    'rebased->>=-"5"-"2"': b'<?php $a="5";echo ($a >>= "2");echo ":",$a;',
    'rebased->>=-null-2': b'<?php $a=null;echo ($a >>= 2);echo ":",$a;',
    'rebased->>=-1.5-2': b'<?php $a=1.5;echo ($a >>= 2);echo ":",$a;',
    'rebased-&=-5-2': b'<?php $a=5;echo ($a &= 2);echo ":",$a;',
    'rebased-&=-"5"-"2"': b'<?php $a="5";echo ($a &= "2");echo ":",$a;',
    'rebased-&=-null-2': b'<?php $a=null;echo ($a &= 2);echo ":",$a;',
    'rebased-&=-1.5-2': b'<?php $a=1.5;echo ($a &= 2);echo ":",$a;',
    'rebased-|=-5-2': b'<?php $a=5;echo ($a |= 2);echo ":",$a;',
    'rebased-|=-"5"-"2"': b'<?php $a="5";echo ($a |= "2");echo ":",$a;',
    'rebased-|=-null-2': b'<?php $a=null;echo ($a |= 2);echo ":",$a;',
    'rebased-|=-1.5-2': b'<?php $a=1.5;echo ($a |= 2);echo ":",$a;',
    'rebased-^=-5-2': b'<?php $a=5;echo ($a ^= 2);echo ":",$a;',
    'rebased-^=-"5"-"2"': b'<?php $a="5";echo ($a ^= "2");echo ":",$a;',
    'rebased-^=-null-2': b'<?php $a=null;echo ($a ^= 2);echo ":",$a;',
    'rebased-^=-1.5-2': b'<?php $a=1.5;echo ($a ^= 2);echo ":",$a;',
    'rebased-.=-5-2': b'<?php $a=5;echo ($a .= 2);echo ":",$a;',
    'rebased-.=-"5"-"2"': b'<?php $a="5";echo ($a .= "2");echo ":",$a;',
    'rebased-.=-null-2': b'<?php $a=null;echo ($a .= 2);echo ":",$a;',
    'rebased-.=-1.5-2': b'<?php $a=1.5;echo ($a .= 2);echo ":",$a;',
    'rebased-location-0': b'<?php $a+=1;echo $a;',
    'rebased-location-1': b'<?php $a+=$a;echo $a;',
    'rebased-location-2': b'<?php ${($n="a")}+=$a;echo $a;',
    'rebased-location-3': b'<?php $a[0]+=1;echo $a[0];',
    'rebased-location-4': b'<?php $a[0]+=$a;',
    'rebased-location-5': b'<?php $a[0]+=$b;echo $a[0];',
    'rebased-location-6': b'<?php $a=false;$r=&$a;$a[0]+=1;echo $a[0];',
    'rebased-location-7': b'<?php $a=false;$r=&$a;$a[0][0]+=1;echo $a[0][0];',
    'rebased-location-8': b'<?php $a=[1];$b=$a;echo ($a[0]+=2);echo $b[0],$a[0];',
    'rebased-location-9': b'<?php $a=[NAN];$b=$a;$a+=$a;echo $a===$b;',
    'rebased-location-10': b'<?php $a=[NAN];$b=$a;$a+=[];echo $a===$b;',
    'rebased-location-11': b'<?php $a=[1];$r=&$a;$a += [1=>2];echo $a[1],$r[1];',
    'rebased-location-12': b'<?php $a=[1];echo ($a[0]+=($a=[3])[0]);echo $a[0];',
    'rebased-location-13': b'<?php $a=[[1]];echo ($a[0][0]+=($a=[[3]])[0][0]);echo $a[0][0];',
    'rebased-location-14': b'<?php $a="abc";$a[0]+=1;',
    'rebased-location-15': b'<?php $a="abc";$a[1.5].="x";',
    'rebased-location-16': b'<?php $a=1;$a[$missing]+=1;',
    'rebased-location-17': b'<?php $a=[];$a[]+=1;echo $a[0];',
    'rebased-location-18': b'<?php $a=2;$a/=0;',
    'rebased-location-19': b'<?php $a=2;$a%=0;',
    'rebased-location-20': b'<?php $a=2;$a<<=-1;',
    'rebased-ownership-0': b'<?php $x=1;$a=[&$x];unset($x);$a += [1=>2];$b=$a;$b[0]=3;echo $a[0],$b[0];',
    'rebased-ownership-1': b'<?php $x=1;$a=[&$x];unset($x);$b=$a;$a += [1=>2];$a[0]=3;echo $b[0],$a[0];',
    'rebased-ownership-2': b'<?php $x=1;$rhs=[&$x];unset($x);$a=[];$a+=$rhs;$a[0]=2;echo $rhs[0],$a[0];',
    'rebased-ownership-3': b'<?php $a=[];$x=1;$rhs=[&$x];$a+=$rhs;$a[0]=2;echo $x,$rhs[0];',
    'rebased-ownership-4': b'<?php $a=[];$a[0]=&$a;$b=$a;$a+=$b;echo $a===$b;',
    'rebased-ownership-5': b'<?php $a=[NAN];$b=$a;$a+=$b;echo $a===$b;',
    'rebased-ownership-6': b'<?php $a=[1];$r=&$a[0];echo ($r+=($a[0]=3));echo $r,$a[0];',
    'rebased-ownership-7': b'<?php $a=1;$b=2;echo ($a+=($a=&$b));echo $a,$b;',
    'rebased-ownership-8': b'<?php $a=[1];$b=[2];echo ($a[0]+=($a=&$b)[0]);echo $a[0],$b[0];',
    'rebased-ownership-9': b'<?php $a=false;$r=&$a;unset($r);$a[0][0]+=1;echo $a[0][0];',
    'loop-rebased-compound': b'<?php $a=[1];$i=0;while($i++<3){$b=$a;$b[0]+=1;echo $a[0],$b[0];$a+=[1=>2];}',
    'loop-rebased-compound-ref': b'<?php $a=false;$r=&$a;for($i=0;$i<3;$i++){$a=false;$a[0][0]+=1;echo $r[0][0];}',
    'values-+=-null-null': b'<?php $a=null;echo ($a += null);echo ":",$a;',
    'values-+=-null-true': b'<?php $a=null;echo ($a += true);echo ":",$a;',
    'values-+=-null-1.5': b'<?php $a=null;echo ($a += 1.5);echo ":",$a;',
    'values-+=-null-"2"': b'<?php $a=null;echo ($a += "2");echo ":",$a;',
    'values-+=-null-"x"': b'<?php $a=null;echo ($a += "x");echo ":",$a;',
    'values-+=-null-[]': b'<?php $a=null;echo ($a += []);echo ":",$a;',
    'values-+=-true-null': b'<?php $a=true;echo ($a += null);echo ":",$a;',
    'values-+=-true-true': b'<?php $a=true;echo ($a += true);echo ":",$a;',
    'values-+=-true-2': b'<?php $a=true;echo ($a += 2);echo ":",$a;',
    'values-+=-true-1.5': b'<?php $a=true;echo ($a += 1.5);echo ":",$a;',
    'values-+=-true-"2"': b'<?php $a=true;echo ($a += "2");echo ":",$a;',
    'values-+=-true-"x"': b'<?php $a=true;echo ($a += "x");echo ":",$a;',
    'values-+=-true-[]': b'<?php $a=true;echo ($a += []);echo ":",$a;',
    'values-+=-2-null': b'<?php $a=2;echo ($a += null);echo ":",$a;',
    'values-+=-2-true': b'<?php $a=2;echo ($a += true);echo ":",$a;',
    'values-+=-2-2': b'<?php $a=2;echo ($a += 2);echo ":",$a;',
    'values-+=-2-1.5': b'<?php $a=2;echo ($a += 1.5);echo ":",$a;',
    'values-+=-2-"2"': b'<?php $a=2;echo ($a += "2");echo ":",$a;',
    'values-+=-2-"x"': b'<?php $a=2;echo ($a += "x");echo ":",$a;',
    'values-+=-2-[]': b'<?php $a=2;echo ($a += []);echo ":",$a;',
    'values-+=-1.5-null': b'<?php $a=1.5;echo ($a += null);echo ":",$a;',
    'values-+=-1.5-true': b'<?php $a=1.5;echo ($a += true);echo ":",$a;',
    'values-+=-1.5-1.5': b'<?php $a=1.5;echo ($a += 1.5);echo ":",$a;',
    'values-+=-1.5-"2"': b'<?php $a=1.5;echo ($a += "2");echo ":",$a;',
    'values-+=-1.5-"x"': b'<?php $a=1.5;echo ($a += "x");echo ":",$a;',
    'values-+=-1.5-[]': b'<?php $a=1.5;echo ($a += []);echo ":",$a;',
    'values-+=-"2"-null': b'<?php $a="2";echo ($a += null);echo ":",$a;',
    'values-+=-"2"-true': b'<?php $a="2";echo ($a += true);echo ":",$a;',
    'values-+=-"2"-2': b'<?php $a="2";echo ($a += 2);echo ":",$a;',
    'values-+=-"2"-1.5': b'<?php $a="2";echo ($a += 1.5);echo ":",$a;',
    'values-+=-"2"-"2"': b'<?php $a="2";echo ($a += "2");echo ":",$a;',
    'values-+=-"2"-"x"': b'<?php $a="2";echo ($a += "x");echo ":",$a;',
    'values-+=-"2"-[]': b'<?php $a="2";echo ($a += []);echo ":",$a;',
    'values-+=-"x"-null': b'<?php $a="x";echo ($a += null);echo ":",$a;',
    'values-+=-"x"-true': b'<?php $a="x";echo ($a += true);echo ":",$a;',
    'values-+=-"x"-2': b'<?php $a="x";echo ($a += 2);echo ":",$a;',
    'values-+=-"x"-1.5': b'<?php $a="x";echo ($a += 1.5);echo ":",$a;',
    'values-+=-"x"-"2"': b'<?php $a="x";echo ($a += "2");echo ":",$a;',
    'values-+=-"x"-"x"': b'<?php $a="x";echo ($a += "x");echo ":",$a;',
    'values-+=-"x"-[]': b'<?php $a="x";echo ($a += []);echo ":",$a;',
    'values-+=-[]-null': b'<?php $a=[];echo ($a += null);echo ":",$a;',
    'values-+=-[]-true': b'<?php $a=[];echo ($a += true);echo ":",$a;',
    'values-+=-[]-2': b'<?php $a=[];echo ($a += 2);echo ":",$a;',
    'values-+=-[]-1.5': b'<?php $a=[];echo ($a += 1.5);echo ":",$a;',
    'values-+=-[]-"2"': b'<?php $a=[];echo ($a += "2");echo ":",$a;',
    'values-+=-[]-"x"': b'<?php $a=[];echo ($a += "x");echo ":",$a;',
    'values-+=-[]-[]': b'<?php $a=[];echo ($a += []);echo ":",$a;',
    'values--=-null-null': b'<?php $a=null;echo ($a -= null);echo ":",$a;',
    'values--=-null-true': b'<?php $a=null;echo ($a -= true);echo ":",$a;',
    'values--=-null-1.5': b'<?php $a=null;echo ($a -= 1.5);echo ":",$a;',
    'values--=-null-"2"': b'<?php $a=null;echo ($a -= "2");echo ":",$a;',
    'values--=-null-"x"': b'<?php $a=null;echo ($a -= "x");echo ":",$a;',
    'values--=-null-[]': b'<?php $a=null;echo ($a -= []);echo ":",$a;',
    'values--=-true-null': b'<?php $a=true;echo ($a -= null);echo ":",$a;',
    'values--=-true-true': b'<?php $a=true;echo ($a -= true);echo ":",$a;',
    'values--=-true-2': b'<?php $a=true;echo ($a -= 2);echo ":",$a;',
    'values--=-true-1.5': b'<?php $a=true;echo ($a -= 1.5);echo ":",$a;',
    'values--=-true-"2"': b'<?php $a=true;echo ($a -= "2");echo ":",$a;',
    'values--=-true-"x"': b'<?php $a=true;echo ($a -= "x");echo ":",$a;',
    'values--=-true-[]': b'<?php $a=true;echo ($a -= []);echo ":",$a;',
    'values--=-2-null': b'<?php $a=2;echo ($a -= null);echo ":",$a;',
    'values--=-2-true': b'<?php $a=2;echo ($a -= true);echo ":",$a;',
    'values--=-2-2': b'<?php $a=2;echo ($a -= 2);echo ":",$a;',
    'values--=-2-1.5': b'<?php $a=2;echo ($a -= 1.5);echo ":",$a;',
    'values--=-2-"2"': b'<?php $a=2;echo ($a -= "2");echo ":",$a;',
    'values--=-2-"x"': b'<?php $a=2;echo ($a -= "x");echo ":",$a;',
    'values--=-2-[]': b'<?php $a=2;echo ($a -= []);echo ":",$a;',
    'values--=-1.5-null': b'<?php $a=1.5;echo ($a -= null);echo ":",$a;',
    'values--=-1.5-true': b'<?php $a=1.5;echo ($a -= true);echo ":",$a;',
    'values--=-1.5-1.5': b'<?php $a=1.5;echo ($a -= 1.5);echo ":",$a;',
    'values--=-1.5-"2"': b'<?php $a=1.5;echo ($a -= "2");echo ":",$a;',
    'values--=-1.5-"x"': b'<?php $a=1.5;echo ($a -= "x");echo ":",$a;',
    'values--=-1.5-[]': b'<?php $a=1.5;echo ($a -= []);echo ":",$a;',
    'values--=-"2"-null': b'<?php $a="2";echo ($a -= null);echo ":",$a;',
    'values--=-"2"-true': b'<?php $a="2";echo ($a -= true);echo ":",$a;',
    'values--=-"2"-2': b'<?php $a="2";echo ($a -= 2);echo ":",$a;',
    'values--=-"2"-1.5': b'<?php $a="2";echo ($a -= 1.5);echo ":",$a;',
    'values--=-"2"-"2"': b'<?php $a="2";echo ($a -= "2");echo ":",$a;',
    'values--=-"2"-"x"': b'<?php $a="2";echo ($a -= "x");echo ":",$a;',
    'values--=-"2"-[]': b'<?php $a="2";echo ($a -= []);echo ":",$a;',
    'values--=-"x"-null': b'<?php $a="x";echo ($a -= null);echo ":",$a;',
    'values--=-"x"-true': b'<?php $a="x";echo ($a -= true);echo ":",$a;',
    'values--=-"x"-2': b'<?php $a="x";echo ($a -= 2);echo ":",$a;',
    'values--=-"x"-1.5': b'<?php $a="x";echo ($a -= 1.5);echo ":",$a;',
    'values--=-"x"-"2"': b'<?php $a="x";echo ($a -= "2");echo ":",$a;',
    'values--=-"x"-"x"': b'<?php $a="x";echo ($a -= "x");echo ":",$a;',
    'values--=-"x"-[]': b'<?php $a="x";echo ($a -= []);echo ":",$a;',
    'values--=-[]-null': b'<?php $a=[];echo ($a -= null);echo ":",$a;',
    'values--=-[]-true': b'<?php $a=[];echo ($a -= true);echo ":",$a;',
    'values--=-[]-2': b'<?php $a=[];echo ($a -= 2);echo ":",$a;',
    'values--=-[]-1.5': b'<?php $a=[];echo ($a -= 1.5);echo ":",$a;',
    'values--=-[]-"2"': b'<?php $a=[];echo ($a -= "2");echo ":",$a;',
    'values--=-[]-"x"': b'<?php $a=[];echo ($a -= "x");echo ":",$a;',
    'values--=-[]-[]': b'<?php $a=[];echo ($a -= []);echo ":",$a;',
    'values-*=-null-null': b'<?php $a=null;echo ($a *= null);echo ":",$a;',
    'values-*=-null-true': b'<?php $a=null;echo ($a *= true);echo ":",$a;',
    'values-*=-null-1.5': b'<?php $a=null;echo ($a *= 1.5);echo ":",$a;',
    'values-*=-null-"2"': b'<?php $a=null;echo ($a *= "2");echo ":",$a;',
    'values-*=-null-"x"': b'<?php $a=null;echo ($a *= "x");echo ":",$a;',
    'values-*=-null-[]': b'<?php $a=null;echo ($a *= []);echo ":",$a;',
    'values-*=-true-null': b'<?php $a=true;echo ($a *= null);echo ":",$a;',
    'values-*=-true-true': b'<?php $a=true;echo ($a *= true);echo ":",$a;',
    'values-*=-true-2': b'<?php $a=true;echo ($a *= 2);echo ":",$a;',
    'values-*=-true-1.5': b'<?php $a=true;echo ($a *= 1.5);echo ":",$a;',
    'values-*=-true-"2"': b'<?php $a=true;echo ($a *= "2");echo ":",$a;',
    'values-*=-true-"x"': b'<?php $a=true;echo ($a *= "x");echo ":",$a;',
    'values-*=-true-[]': b'<?php $a=true;echo ($a *= []);echo ":",$a;',
    'values-*=-2-null': b'<?php $a=2;echo ($a *= null);echo ":",$a;',
    'values-*=-2-true': b'<?php $a=2;echo ($a *= true);echo ":",$a;',
    'values-*=-2-2': b'<?php $a=2;echo ($a *= 2);echo ":",$a;',
    'values-*=-2-1.5': b'<?php $a=2;echo ($a *= 1.5);echo ":",$a;',
    'values-*=-2-"2"': b'<?php $a=2;echo ($a *= "2");echo ":",$a;',
    'values-*=-2-"x"': b'<?php $a=2;echo ($a *= "x");echo ":",$a;',
    'values-*=-2-[]': b'<?php $a=2;echo ($a *= []);echo ":",$a;',
    'values-*=-1.5-null': b'<?php $a=1.5;echo ($a *= null);echo ":",$a;',
    'values-*=-1.5-true': b'<?php $a=1.5;echo ($a *= true);echo ":",$a;',
    'values-*=-1.5-1.5': b'<?php $a=1.5;echo ($a *= 1.5);echo ":",$a;',
    'values-*=-1.5-"2"': b'<?php $a=1.5;echo ($a *= "2");echo ":",$a;',
    'values-*=-1.5-"x"': b'<?php $a=1.5;echo ($a *= "x");echo ":",$a;',
    'values-*=-1.5-[]': b'<?php $a=1.5;echo ($a *= []);echo ":",$a;',
    'values-*=-"2"-null': b'<?php $a="2";echo ($a *= null);echo ":",$a;',
    'values-*=-"2"-true': b'<?php $a="2";echo ($a *= true);echo ":",$a;',
    'values-*=-"2"-2': b'<?php $a="2";echo ($a *= 2);echo ":",$a;',
    'values-*=-"2"-1.5': b'<?php $a="2";echo ($a *= 1.5);echo ":",$a;',
    'values-*=-"2"-"2"': b'<?php $a="2";echo ($a *= "2");echo ":",$a;',
    'values-*=-"2"-"x"': b'<?php $a="2";echo ($a *= "x");echo ":",$a;',
    'values-*=-"2"-[]': b'<?php $a="2";echo ($a *= []);echo ":",$a;',
    'values-*=-"x"-null': b'<?php $a="x";echo ($a *= null);echo ":",$a;',
    'values-*=-"x"-true': b'<?php $a="x";echo ($a *= true);echo ":",$a;',
    'values-*=-"x"-2': b'<?php $a="x";echo ($a *= 2);echo ":",$a;',
    'values-*=-"x"-1.5': b'<?php $a="x";echo ($a *= 1.5);echo ":",$a;',
    'values-*=-"x"-"2"': b'<?php $a="x";echo ($a *= "2");echo ":",$a;',
    'values-*=-"x"-"x"': b'<?php $a="x";echo ($a *= "x");echo ":",$a;',
    'values-*=-"x"-[]': b'<?php $a="x";echo ($a *= []);echo ":",$a;',
    'values-*=-[]-null': b'<?php $a=[];echo ($a *= null);echo ":",$a;',
    'values-*=-[]-true': b'<?php $a=[];echo ($a *= true);echo ":",$a;',
    'values-*=-[]-2': b'<?php $a=[];echo ($a *= 2);echo ":",$a;',
    'values-*=-[]-1.5': b'<?php $a=[];echo ($a *= 1.5);echo ":",$a;',
    'values-*=-[]-"2"': b'<?php $a=[];echo ($a *= "2");echo ":",$a;',
    'values-*=-[]-"x"': b'<?php $a=[];echo ($a *= "x");echo ":",$a;',
    'values-*=-[]-[]': b'<?php $a=[];echo ($a *= []);echo ":",$a;',
    'values-/=-null-null': b'<?php $a=null;echo ($a /= null);echo ":",$a;',
    'values-/=-null-true': b'<?php $a=null;echo ($a /= true);echo ":",$a;',
    'values-/=-null-1.5': b'<?php $a=null;echo ($a /= 1.5);echo ":",$a;',
    'values-/=-null-"2"': b'<?php $a=null;echo ($a /= "2");echo ":",$a;',
    'values-/=-null-"x"': b'<?php $a=null;echo ($a /= "x");echo ":",$a;',
    'values-/=-null-[]': b'<?php $a=null;echo ($a /= []);echo ":",$a;',
    'values-/=-true-null': b'<?php $a=true;echo ($a /= null);echo ":",$a;',
    'values-/=-true-true': b'<?php $a=true;echo ($a /= true);echo ":",$a;',
    'values-/=-true-2': b'<?php $a=true;echo ($a /= 2);echo ":",$a;',
    'values-/=-true-1.5': b'<?php $a=true;echo ($a /= 1.5);echo ":",$a;',
    'values-/=-true-"2"': b'<?php $a=true;echo ($a /= "2");echo ":",$a;',
    'values-/=-true-"x"': b'<?php $a=true;echo ($a /= "x");echo ":",$a;',
    'values-/=-true-[]': b'<?php $a=true;echo ($a /= []);echo ":",$a;',
    'values-/=-2-null': b'<?php $a=2;echo ($a /= null);echo ":",$a;',
    'values-/=-2-true': b'<?php $a=2;echo ($a /= true);echo ":",$a;',
    'values-/=-2-2': b'<?php $a=2;echo ($a /= 2);echo ":",$a;',
    'values-/=-2-1.5': b'<?php $a=2;echo ($a /= 1.5);echo ":",$a;',
    'values-/=-2-"2"': b'<?php $a=2;echo ($a /= "2");echo ":",$a;',
    'values-/=-2-"x"': b'<?php $a=2;echo ($a /= "x");echo ":",$a;',
    'values-/=-2-[]': b'<?php $a=2;echo ($a /= []);echo ":",$a;',
    'values-/=-1.5-null': b'<?php $a=1.5;echo ($a /= null);echo ":",$a;',
    'values-/=-1.5-true': b'<?php $a=1.5;echo ($a /= true);echo ":",$a;',
    'values-/=-1.5-1.5': b'<?php $a=1.5;echo ($a /= 1.5);echo ":",$a;',
    'values-/=-1.5-"2"': b'<?php $a=1.5;echo ($a /= "2");echo ":",$a;',
    'values-/=-1.5-"x"': b'<?php $a=1.5;echo ($a /= "x");echo ":",$a;',
    'values-/=-1.5-[]': b'<?php $a=1.5;echo ($a /= []);echo ":",$a;',
    'values-/=-"2"-null': b'<?php $a="2";echo ($a /= null);echo ":",$a;',
    'values-/=-"2"-true': b'<?php $a="2";echo ($a /= true);echo ":",$a;',
    'values-/=-"2"-2': b'<?php $a="2";echo ($a /= 2);echo ":",$a;',
    'values-/=-"2"-1.5': b'<?php $a="2";echo ($a /= 1.5);echo ":",$a;',
    'values-/=-"2"-"2"': b'<?php $a="2";echo ($a /= "2");echo ":",$a;',
    'values-/=-"2"-"x"': b'<?php $a="2";echo ($a /= "x");echo ":",$a;',
    'values-/=-"2"-[]': b'<?php $a="2";echo ($a /= []);echo ":",$a;',
    'values-/=-"x"-null': b'<?php $a="x";echo ($a /= null);echo ":",$a;',
    'values-/=-"x"-true': b'<?php $a="x";echo ($a /= true);echo ":",$a;',
    'values-/=-"x"-2': b'<?php $a="x";echo ($a /= 2);echo ":",$a;',
    'values-/=-"x"-1.5': b'<?php $a="x";echo ($a /= 1.5);echo ":",$a;',
    'values-/=-"x"-"2"': b'<?php $a="x";echo ($a /= "2");echo ":",$a;',
    'values-/=-"x"-"x"': b'<?php $a="x";echo ($a /= "x");echo ":",$a;',
    'values-/=-"x"-[]': b'<?php $a="x";echo ($a /= []);echo ":",$a;',
    'values-/=-[]-null': b'<?php $a=[];echo ($a /= null);echo ":",$a;',
    'values-/=-[]-true': b'<?php $a=[];echo ($a /= true);echo ":",$a;',
    'values-/=-[]-2': b'<?php $a=[];echo ($a /= 2);echo ":",$a;',
    'values-/=-[]-1.5': b'<?php $a=[];echo ($a /= 1.5);echo ":",$a;',
    'values-/=-[]-"2"': b'<?php $a=[];echo ($a /= "2");echo ":",$a;',
    'values-/=-[]-"x"': b'<?php $a=[];echo ($a /= "x");echo ":",$a;',
    'values-/=-[]-[]': b'<?php $a=[];echo ($a /= []);echo ":",$a;',
    'values-%=-null-null': b'<?php $a=null;echo ($a %= null);echo ":",$a;',
    'values-%=-null-true': b'<?php $a=null;echo ($a %= true);echo ":",$a;',
    'values-%=-null-1.5': b'<?php $a=null;echo ($a %= 1.5);echo ":",$a;',
    'values-%=-null-"2"': b'<?php $a=null;echo ($a %= "2");echo ":",$a;',
    'values-%=-null-"x"': b'<?php $a=null;echo ($a %= "x");echo ":",$a;',
    'values-%=-null-[]': b'<?php $a=null;echo ($a %= []);echo ":",$a;',
    'values-%=-true-null': b'<?php $a=true;echo ($a %= null);echo ":",$a;',
    'values-%=-true-true': b'<?php $a=true;echo ($a %= true);echo ":",$a;',
    'values-%=-true-2': b'<?php $a=true;echo ($a %= 2);echo ":",$a;',
    'values-%=-true-1.5': b'<?php $a=true;echo ($a %= 1.5);echo ":",$a;',
    'values-%=-true-"2"': b'<?php $a=true;echo ($a %= "2");echo ":",$a;',
    'values-%=-true-"x"': b'<?php $a=true;echo ($a %= "x");echo ":",$a;',
    'values-%=-true-[]': b'<?php $a=true;echo ($a %= []);echo ":",$a;',
    'values-%=-2-null': b'<?php $a=2;echo ($a %= null);echo ":",$a;',
    'values-%=-2-true': b'<?php $a=2;echo ($a %= true);echo ":",$a;',
    'values-%=-2-2': b'<?php $a=2;echo ($a %= 2);echo ":",$a;',
    'values-%=-2-1.5': b'<?php $a=2;echo ($a %= 1.5);echo ":",$a;',
    'values-%=-2-"2"': b'<?php $a=2;echo ($a %= "2");echo ":",$a;',
    'values-%=-2-"x"': b'<?php $a=2;echo ($a %= "x");echo ":",$a;',
    'values-%=-2-[]': b'<?php $a=2;echo ($a %= []);echo ":",$a;',
    'values-%=-1.5-null': b'<?php $a=1.5;echo ($a %= null);echo ":",$a;',
    'values-%=-1.5-true': b'<?php $a=1.5;echo ($a %= true);echo ":",$a;',
    'values-%=-1.5-1.5': b'<?php $a=1.5;echo ($a %= 1.5);echo ":",$a;',
    'values-%=-1.5-"2"': b'<?php $a=1.5;echo ($a %= "2");echo ":",$a;',
    'values-%=-1.5-"x"': b'<?php $a=1.5;echo ($a %= "x");echo ":",$a;',
    'values-%=-1.5-[]': b'<?php $a=1.5;echo ($a %= []);echo ":",$a;',
    'values-%=-"2"-null': b'<?php $a="2";echo ($a %= null);echo ":",$a;',
    'values-%=-"2"-true': b'<?php $a="2";echo ($a %= true);echo ":",$a;',
    'values-%=-"2"-2': b'<?php $a="2";echo ($a %= 2);echo ":",$a;',
    'values-%=-"2"-1.5': b'<?php $a="2";echo ($a %= 1.5);echo ":",$a;',
    'values-%=-"2"-"2"': b'<?php $a="2";echo ($a %= "2");echo ":",$a;',
    'values-%=-"2"-"x"': b'<?php $a="2";echo ($a %= "x");echo ":",$a;',
    'values-%=-"2"-[]': b'<?php $a="2";echo ($a %= []);echo ":",$a;',
    'values-%=-"x"-null': b'<?php $a="x";echo ($a %= null);echo ":",$a;',
    'values-%=-"x"-true': b'<?php $a="x";echo ($a %= true);echo ":",$a;',
    'values-%=-"x"-2': b'<?php $a="x";echo ($a %= 2);echo ":",$a;',
    'values-%=-"x"-1.5': b'<?php $a="x";echo ($a %= 1.5);echo ":",$a;',
    'values-%=-"x"-"2"': b'<?php $a="x";echo ($a %= "2");echo ":",$a;',
    'values-%=-"x"-"x"': b'<?php $a="x";echo ($a %= "x");echo ":",$a;',
    'values-%=-"x"-[]': b'<?php $a="x";echo ($a %= []);echo ":",$a;',
    'values-%=-[]-null': b'<?php $a=[];echo ($a %= null);echo ":",$a;',
    'values-%=-[]-true': b'<?php $a=[];echo ($a %= true);echo ":",$a;',
    'values-%=-[]-2': b'<?php $a=[];echo ($a %= 2);echo ":",$a;',
    'values-%=-[]-1.5': b'<?php $a=[];echo ($a %= 1.5);echo ":",$a;',
    'values-%=-[]-"2"': b'<?php $a=[];echo ($a %= "2");echo ":",$a;',
    'values-%=-[]-"x"': b'<?php $a=[];echo ($a %= "x");echo ":",$a;',
    'values-%=-[]-[]': b'<?php $a=[];echo ($a %= []);echo ":",$a;',
    'values-**=-null-null': b'<?php $a=null;echo ($a **= null);echo ":",$a;',
    'values-**=-null-true': b'<?php $a=null;echo ($a **= true);echo ":",$a;',
    'values-**=-null-1.5': b'<?php $a=null;echo ($a **= 1.5);echo ":",$a;',
    'values-**=-null-"2"': b'<?php $a=null;echo ($a **= "2");echo ":",$a;',
    'values-**=-null-"x"': b'<?php $a=null;echo ($a **= "x");echo ":",$a;',
    'values-**=-null-[]': b'<?php $a=null;echo ($a **= []);echo ":",$a;',
    'values-**=-true-null': b'<?php $a=true;echo ($a **= null);echo ":",$a;',
    'values-**=-true-true': b'<?php $a=true;echo ($a **= true);echo ":",$a;',
    'values-**=-true-2': b'<?php $a=true;echo ($a **= 2);echo ":",$a;',
    'values-**=-true-1.5': b'<?php $a=true;echo ($a **= 1.5);echo ":",$a;',
    'values-**=-true-"2"': b'<?php $a=true;echo ($a **= "2");echo ":",$a;',
    'values-**=-true-"x"': b'<?php $a=true;echo ($a **= "x");echo ":",$a;',
    'values-**=-true-[]': b'<?php $a=true;echo ($a **= []);echo ":",$a;',
    'values-**=-2-null': b'<?php $a=2;echo ($a **= null);echo ":",$a;',
    'values-**=-2-true': b'<?php $a=2;echo ($a **= true);echo ":",$a;',
    'values-**=-2-2': b'<?php $a=2;echo ($a **= 2);echo ":",$a;',
    'values-**=-2-1.5': b'<?php $a=2;echo ($a **= 1.5);echo ":",$a;',
    'values-**=-2-"2"': b'<?php $a=2;echo ($a **= "2");echo ":",$a;',
    'values-**=-2-"x"': b'<?php $a=2;echo ($a **= "x");echo ":",$a;',
    'values-**=-2-[]': b'<?php $a=2;echo ($a **= []);echo ":",$a;',
    'values-**=-1.5-null': b'<?php $a=1.5;echo ($a **= null);echo ":",$a;',
    'values-**=-1.5-true': b'<?php $a=1.5;echo ($a **= true);echo ":",$a;',
    'values-**=-1.5-1.5': b'<?php $a=1.5;echo ($a **= 1.5);echo ":",$a;',
    'values-**=-1.5-"2"': b'<?php $a=1.5;echo ($a **= "2");echo ":",$a;',
    'values-**=-1.5-"x"': b'<?php $a=1.5;echo ($a **= "x");echo ":",$a;',
    'values-**=-1.5-[]': b'<?php $a=1.5;echo ($a **= []);echo ":",$a;',
    'values-**=-"2"-null': b'<?php $a="2";echo ($a **= null);echo ":",$a;',
    'values-**=-"2"-true': b'<?php $a="2";echo ($a **= true);echo ":",$a;',
    'values-**=-"2"-2': b'<?php $a="2";echo ($a **= 2);echo ":",$a;',
    'values-**=-"2"-1.5': b'<?php $a="2";echo ($a **= 1.5);echo ":",$a;',
    'values-**=-"2"-"2"': b'<?php $a="2";echo ($a **= "2");echo ":",$a;',
    'values-**=-"2"-"x"': b'<?php $a="2";echo ($a **= "x");echo ":",$a;',
    'values-**=-"2"-[]': b'<?php $a="2";echo ($a **= []);echo ":",$a;',
    'values-**=-"x"-null': b'<?php $a="x";echo ($a **= null);echo ":",$a;',
    'values-**=-"x"-true': b'<?php $a="x";echo ($a **= true);echo ":",$a;',
    'values-**=-"x"-2': b'<?php $a="x";echo ($a **= 2);echo ":",$a;',
    'values-**=-"x"-1.5': b'<?php $a="x";echo ($a **= 1.5);echo ":",$a;',
    'values-**=-"x"-"2"': b'<?php $a="x";echo ($a **= "2");echo ":",$a;',
    'values-**=-"x"-"x"': b'<?php $a="x";echo ($a **= "x");echo ":",$a;',
    'values-**=-"x"-[]': b'<?php $a="x";echo ($a **= []);echo ":",$a;',
    'values-**=-[]-null': b'<?php $a=[];echo ($a **= null);echo ":",$a;',
    'values-**=-[]-true': b'<?php $a=[];echo ($a **= true);echo ":",$a;',
    'values-**=-[]-2': b'<?php $a=[];echo ($a **= 2);echo ":",$a;',
    'values-**=-[]-1.5': b'<?php $a=[];echo ($a **= 1.5);echo ":",$a;',
    'values-**=-[]-"2"': b'<?php $a=[];echo ($a **= "2");echo ":",$a;',
    'values-**=-[]-"x"': b'<?php $a=[];echo ($a **= "x");echo ":",$a;',
    'values-**=-[]-[]': b'<?php $a=[];echo ($a **= []);echo ":",$a;',
    'values-<<=-null-null': b'<?php $a=null;echo ($a <<= null);echo ":",$a;',
    'values-<<=-null-true': b'<?php $a=null;echo ($a <<= true);echo ":",$a;',
    'values-<<=-null-1.5': b'<?php $a=null;echo ($a <<= 1.5);echo ":",$a;',
    'values-<<=-null-"2"': b'<?php $a=null;echo ($a <<= "2");echo ":",$a;',
    'values-<<=-null-"x"': b'<?php $a=null;echo ($a <<= "x");echo ":",$a;',
    'values-<<=-null-[]': b'<?php $a=null;echo ($a <<= []);echo ":",$a;',
    'values-<<=-true-null': b'<?php $a=true;echo ($a <<= null);echo ":",$a;',
    'values-<<=-true-true': b'<?php $a=true;echo ($a <<= true);echo ":",$a;',
    'values-<<=-true-2': b'<?php $a=true;echo ($a <<= 2);echo ":",$a;',
    'values-<<=-true-1.5': b'<?php $a=true;echo ($a <<= 1.5);echo ":",$a;',
    'values-<<=-true-"2"': b'<?php $a=true;echo ($a <<= "2");echo ":",$a;',
    'values-<<=-true-"x"': b'<?php $a=true;echo ($a <<= "x");echo ":",$a;',
    'values-<<=-true-[]': b'<?php $a=true;echo ($a <<= []);echo ":",$a;',
    'values-<<=-2-null': b'<?php $a=2;echo ($a <<= null);echo ":",$a;',
    'values-<<=-2-true': b'<?php $a=2;echo ($a <<= true);echo ":",$a;',
    'values-<<=-2-2': b'<?php $a=2;echo ($a <<= 2);echo ":",$a;',
    'values-<<=-2-1.5': b'<?php $a=2;echo ($a <<= 1.5);echo ":",$a;',
    'values-<<=-2-"2"': b'<?php $a=2;echo ($a <<= "2");echo ":",$a;',
    'values-<<=-2-"x"': b'<?php $a=2;echo ($a <<= "x");echo ":",$a;',
    'values-<<=-2-[]': b'<?php $a=2;echo ($a <<= []);echo ":",$a;',
    'values-<<=-1.5-null': b'<?php $a=1.5;echo ($a <<= null);echo ":",$a;',
    'values-<<=-1.5-true': b'<?php $a=1.5;echo ($a <<= true);echo ":",$a;',
    'values-<<=-1.5-1.5': b'<?php $a=1.5;echo ($a <<= 1.5);echo ":",$a;',
    'values-<<=-1.5-"2"': b'<?php $a=1.5;echo ($a <<= "2");echo ":",$a;',
    'values-<<=-1.5-"x"': b'<?php $a=1.5;echo ($a <<= "x");echo ":",$a;',
    'values-<<=-1.5-[]': b'<?php $a=1.5;echo ($a <<= []);echo ":",$a;',
    'values-<<=-"2"-null': b'<?php $a="2";echo ($a <<= null);echo ":",$a;',
    'values-<<=-"2"-true': b'<?php $a="2";echo ($a <<= true);echo ":",$a;',
    'values-<<=-"2"-2': b'<?php $a="2";echo ($a <<= 2);echo ":",$a;',
    'values-<<=-"2"-1.5': b'<?php $a="2";echo ($a <<= 1.5);echo ":",$a;',
    'values-<<=-"2"-"2"': b'<?php $a="2";echo ($a <<= "2");echo ":",$a;',
    'values-<<=-"2"-"x"': b'<?php $a="2";echo ($a <<= "x");echo ":",$a;',
    'values-<<=-"2"-[]': b'<?php $a="2";echo ($a <<= []);echo ":",$a;',
    'values-<<=-"x"-null': b'<?php $a="x";echo ($a <<= null);echo ":",$a;',
    'values-<<=-"x"-true': b'<?php $a="x";echo ($a <<= true);echo ":",$a;',
    'values-<<=-"x"-2': b'<?php $a="x";echo ($a <<= 2);echo ":",$a;',
    'values-<<=-"x"-1.5': b'<?php $a="x";echo ($a <<= 1.5);echo ":",$a;',
    'values-<<=-"x"-"2"': b'<?php $a="x";echo ($a <<= "2");echo ":",$a;',
    'values-<<=-"x"-"x"': b'<?php $a="x";echo ($a <<= "x");echo ":",$a;',
    'values-<<=-"x"-[]': b'<?php $a="x";echo ($a <<= []);echo ":",$a;',
    'values-<<=-[]-null': b'<?php $a=[];echo ($a <<= null);echo ":",$a;',
    'values-<<=-[]-true': b'<?php $a=[];echo ($a <<= true);echo ":",$a;',
    'values-<<=-[]-2': b'<?php $a=[];echo ($a <<= 2);echo ":",$a;',
    'values-<<=-[]-1.5': b'<?php $a=[];echo ($a <<= 1.5);echo ":",$a;',
    'values-<<=-[]-"2"': b'<?php $a=[];echo ($a <<= "2");echo ":",$a;',
    'values-<<=-[]-"x"': b'<?php $a=[];echo ($a <<= "x");echo ":",$a;',
    'values-<<=-[]-[]': b'<?php $a=[];echo ($a <<= []);echo ":",$a;',
    'values->>=-null-null': b'<?php $a=null;echo ($a >>= null);echo ":",$a;',
    'values->>=-null-true': b'<?php $a=null;echo ($a >>= true);echo ":",$a;',
    'values->>=-null-1.5': b'<?php $a=null;echo ($a >>= 1.5);echo ":",$a;',
    'values->>=-null-"2"': b'<?php $a=null;echo ($a >>= "2");echo ":",$a;',
    'values->>=-null-"x"': b'<?php $a=null;echo ($a >>= "x");echo ":",$a;',
    'values->>=-null-[]': b'<?php $a=null;echo ($a >>= []);echo ":",$a;',
    'values->>=-true-null': b'<?php $a=true;echo ($a >>= null);echo ":",$a;',
    'values->>=-true-true': b'<?php $a=true;echo ($a >>= true);echo ":",$a;',
    'values->>=-true-2': b'<?php $a=true;echo ($a >>= 2);echo ":",$a;',
    'values->>=-true-1.5': b'<?php $a=true;echo ($a >>= 1.5);echo ":",$a;',
    'values->>=-true-"2"': b'<?php $a=true;echo ($a >>= "2");echo ":",$a;',
    'values->>=-true-"x"': b'<?php $a=true;echo ($a >>= "x");echo ":",$a;',
    'values->>=-true-[]': b'<?php $a=true;echo ($a >>= []);echo ":",$a;',
    'values->>=-2-null': b'<?php $a=2;echo ($a >>= null);echo ":",$a;',
    'values->>=-2-true': b'<?php $a=2;echo ($a >>= true);echo ":",$a;',
    'values->>=-2-2': b'<?php $a=2;echo ($a >>= 2);echo ":",$a;',
    'values->>=-2-1.5': b'<?php $a=2;echo ($a >>= 1.5);echo ":",$a;',
    'values->>=-2-"2"': b'<?php $a=2;echo ($a >>= "2");echo ":",$a;',
    'values->>=-2-"x"': b'<?php $a=2;echo ($a >>= "x");echo ":",$a;',
    'values->>=-2-[]': b'<?php $a=2;echo ($a >>= []);echo ":",$a;',
    'values->>=-1.5-null': b'<?php $a=1.5;echo ($a >>= null);echo ":",$a;',
    'values->>=-1.5-true': b'<?php $a=1.5;echo ($a >>= true);echo ":",$a;',
    'values->>=-1.5-1.5': b'<?php $a=1.5;echo ($a >>= 1.5);echo ":",$a;',
    'values->>=-1.5-"2"': b'<?php $a=1.5;echo ($a >>= "2");echo ":",$a;',
    'values->>=-1.5-"x"': b'<?php $a=1.5;echo ($a >>= "x");echo ":",$a;',
    'values->>=-1.5-[]': b'<?php $a=1.5;echo ($a >>= []);echo ":",$a;',
    'values->>=-"2"-null': b'<?php $a="2";echo ($a >>= null);echo ":",$a;',
    'values->>=-"2"-true': b'<?php $a="2";echo ($a >>= true);echo ":",$a;',
    'values->>=-"2"-2': b'<?php $a="2";echo ($a >>= 2);echo ":",$a;',
    'values->>=-"2"-1.5': b'<?php $a="2";echo ($a >>= 1.5);echo ":",$a;',
    'values->>=-"2"-"2"': b'<?php $a="2";echo ($a >>= "2");echo ":",$a;',
    'values->>=-"2"-"x"': b'<?php $a="2";echo ($a >>= "x");echo ":",$a;',
    'values->>=-"2"-[]': b'<?php $a="2";echo ($a >>= []);echo ":",$a;',
    'values->>=-"x"-null': b'<?php $a="x";echo ($a >>= null);echo ":",$a;',
    'values->>=-"x"-true': b'<?php $a="x";echo ($a >>= true);echo ":",$a;',
    'values->>=-"x"-2': b'<?php $a="x";echo ($a >>= 2);echo ":",$a;',
    'values->>=-"x"-1.5': b'<?php $a="x";echo ($a >>= 1.5);echo ":",$a;',
    'values->>=-"x"-"2"': b'<?php $a="x";echo ($a >>= "2");echo ":",$a;',
    'values->>=-"x"-"x"': b'<?php $a="x";echo ($a >>= "x");echo ":",$a;',
    'values->>=-"x"-[]': b'<?php $a="x";echo ($a >>= []);echo ":",$a;',
    'values->>=-[]-null': b'<?php $a=[];echo ($a >>= null);echo ":",$a;',
    'values->>=-[]-true': b'<?php $a=[];echo ($a >>= true);echo ":",$a;',
    'values->>=-[]-2': b'<?php $a=[];echo ($a >>= 2);echo ":",$a;',
    'values->>=-[]-1.5': b'<?php $a=[];echo ($a >>= 1.5);echo ":",$a;',
    'values->>=-[]-"2"': b'<?php $a=[];echo ($a >>= "2");echo ":",$a;',
    'values->>=-[]-"x"': b'<?php $a=[];echo ($a >>= "x");echo ":",$a;',
    'values->>=-[]-[]': b'<?php $a=[];echo ($a >>= []);echo ":",$a;',
    'values-&=-null-null': b'<?php $a=null;echo ($a &= null);echo ":",$a;',
    'values-&=-null-true': b'<?php $a=null;echo ($a &= true);echo ":",$a;',
    'values-&=-null-1.5': b'<?php $a=null;echo ($a &= 1.5);echo ":",$a;',
    'values-&=-null-"2"': b'<?php $a=null;echo ($a &= "2");echo ":",$a;',
    'values-&=-null-"x"': b'<?php $a=null;echo ($a &= "x");echo ":",$a;',
    'values-&=-null-[]': b'<?php $a=null;echo ($a &= []);echo ":",$a;',
    'values-&=-true-null': b'<?php $a=true;echo ($a &= null);echo ":",$a;',
    'values-&=-true-true': b'<?php $a=true;echo ($a &= true);echo ":",$a;',
    'values-&=-true-2': b'<?php $a=true;echo ($a &= 2);echo ":",$a;',
    'values-&=-true-1.5': b'<?php $a=true;echo ($a &= 1.5);echo ":",$a;',
    'values-&=-true-"2"': b'<?php $a=true;echo ($a &= "2");echo ":",$a;',
    'values-&=-true-"x"': b'<?php $a=true;echo ($a &= "x");echo ":",$a;',
    'values-&=-true-[]': b'<?php $a=true;echo ($a &= []);echo ":",$a;',
    'values-&=-2-null': b'<?php $a=2;echo ($a &= null);echo ":",$a;',
    'values-&=-2-true': b'<?php $a=2;echo ($a &= true);echo ":",$a;',
    'values-&=-2-2': b'<?php $a=2;echo ($a &= 2);echo ":",$a;',
    'values-&=-2-1.5': b'<?php $a=2;echo ($a &= 1.5);echo ":",$a;',
    'values-&=-2-"2"': b'<?php $a=2;echo ($a &= "2");echo ":",$a;',
    'values-&=-2-"x"': b'<?php $a=2;echo ($a &= "x");echo ":",$a;',
    'values-&=-2-[]': b'<?php $a=2;echo ($a &= []);echo ":",$a;',
    'values-&=-1.5-null': b'<?php $a=1.5;echo ($a &= null);echo ":",$a;',
    'values-&=-1.5-true': b'<?php $a=1.5;echo ($a &= true);echo ":",$a;',
    'values-&=-1.5-1.5': b'<?php $a=1.5;echo ($a &= 1.5);echo ":",$a;',
    'values-&=-1.5-"2"': b'<?php $a=1.5;echo ($a &= "2");echo ":",$a;',
    'values-&=-1.5-"x"': b'<?php $a=1.5;echo ($a &= "x");echo ":",$a;',
    'values-&=-1.5-[]': b'<?php $a=1.5;echo ($a &= []);echo ":",$a;',
    'values-&=-"2"-null': b'<?php $a="2";echo ($a &= null);echo ":",$a;',
    'values-&=-"2"-true': b'<?php $a="2";echo ($a &= true);echo ":",$a;',
    'values-&=-"2"-2': b'<?php $a="2";echo ($a &= 2);echo ":",$a;',
    'values-&=-"2"-1.5': b'<?php $a="2";echo ($a &= 1.5);echo ":",$a;',
    'values-&=-"2"-"2"': b'<?php $a="2";echo ($a &= "2");echo ":",$a;',
    'values-&=-"2"-"x"': b'<?php $a="2";echo ($a &= "x");echo ":",$a;',
    'values-&=-"2"-[]': b'<?php $a="2";echo ($a &= []);echo ":",$a;',
    'values-&=-"x"-null': b'<?php $a="x";echo ($a &= null);echo ":",$a;',
    'values-&=-"x"-true': b'<?php $a="x";echo ($a &= true);echo ":",$a;',
    'values-&=-"x"-2': b'<?php $a="x";echo ($a &= 2);echo ":",$a;',
    'values-&=-"x"-1.5': b'<?php $a="x";echo ($a &= 1.5);echo ":",$a;',
    'values-&=-"x"-"2"': b'<?php $a="x";echo ($a &= "2");echo ":",$a;',
    'values-&=-"x"-"x"': b'<?php $a="x";echo ($a &= "x");echo ":",$a;',
    'values-&=-"x"-[]': b'<?php $a="x";echo ($a &= []);echo ":",$a;',
    'values-&=-[]-null': b'<?php $a=[];echo ($a &= null);echo ":",$a;',
    'values-&=-[]-true': b'<?php $a=[];echo ($a &= true);echo ":",$a;',
    'values-&=-[]-2': b'<?php $a=[];echo ($a &= 2);echo ":",$a;',
    'values-&=-[]-1.5': b'<?php $a=[];echo ($a &= 1.5);echo ":",$a;',
    'values-&=-[]-"2"': b'<?php $a=[];echo ($a &= "2");echo ":",$a;',
    'values-&=-[]-"x"': b'<?php $a=[];echo ($a &= "x");echo ":",$a;',
    'values-&=-[]-[]': b'<?php $a=[];echo ($a &= []);echo ":",$a;',
    'values-|=-null-null': b'<?php $a=null;echo ($a |= null);echo ":",$a;',
    'values-|=-null-true': b'<?php $a=null;echo ($a |= true);echo ":",$a;',
    'values-|=-null-1.5': b'<?php $a=null;echo ($a |= 1.5);echo ":",$a;',
    'values-|=-null-"2"': b'<?php $a=null;echo ($a |= "2");echo ":",$a;',
    'values-|=-null-"x"': b'<?php $a=null;echo ($a |= "x");echo ":",$a;',
    'values-|=-null-[]': b'<?php $a=null;echo ($a |= []);echo ":",$a;',
    'values-|=-true-null': b'<?php $a=true;echo ($a |= null);echo ":",$a;',
    'values-|=-true-true': b'<?php $a=true;echo ($a |= true);echo ":",$a;',
    'values-|=-true-2': b'<?php $a=true;echo ($a |= 2);echo ":",$a;',
    'values-|=-true-1.5': b'<?php $a=true;echo ($a |= 1.5);echo ":",$a;',
    'values-|=-true-"2"': b'<?php $a=true;echo ($a |= "2");echo ":",$a;',
    'values-|=-true-"x"': b'<?php $a=true;echo ($a |= "x");echo ":",$a;',
    'values-|=-true-[]': b'<?php $a=true;echo ($a |= []);echo ":",$a;',
    'values-|=-2-null': b'<?php $a=2;echo ($a |= null);echo ":",$a;',
    'values-|=-2-true': b'<?php $a=2;echo ($a |= true);echo ":",$a;',
    'values-|=-2-2': b'<?php $a=2;echo ($a |= 2);echo ":",$a;',
    'values-|=-2-1.5': b'<?php $a=2;echo ($a |= 1.5);echo ":",$a;',
    'values-|=-2-"2"': b'<?php $a=2;echo ($a |= "2");echo ":",$a;',
    'values-|=-2-"x"': b'<?php $a=2;echo ($a |= "x");echo ":",$a;',
    'values-|=-2-[]': b'<?php $a=2;echo ($a |= []);echo ":",$a;',
    'values-|=-1.5-null': b'<?php $a=1.5;echo ($a |= null);echo ":",$a;',
    'values-|=-1.5-true': b'<?php $a=1.5;echo ($a |= true);echo ":",$a;',
    'values-|=-1.5-1.5': b'<?php $a=1.5;echo ($a |= 1.5);echo ":",$a;',
    'values-|=-1.5-"2"': b'<?php $a=1.5;echo ($a |= "2");echo ":",$a;',
    'values-|=-1.5-"x"': b'<?php $a=1.5;echo ($a |= "x");echo ":",$a;',
    'values-|=-1.5-[]': b'<?php $a=1.5;echo ($a |= []);echo ":",$a;',
    'values-|=-"2"-null': b'<?php $a="2";echo ($a |= null);echo ":",$a;',
    'values-|=-"2"-true': b'<?php $a="2";echo ($a |= true);echo ":",$a;',
    'values-|=-"2"-2': b'<?php $a="2";echo ($a |= 2);echo ":",$a;',
    'values-|=-"2"-1.5': b'<?php $a="2";echo ($a |= 1.5);echo ":",$a;',
    'values-|=-"2"-"2"': b'<?php $a="2";echo ($a |= "2");echo ":",$a;',
    'values-|=-"2"-"x"': b'<?php $a="2";echo ($a |= "x");echo ":",$a;',
    'values-|=-"2"-[]': b'<?php $a="2";echo ($a |= []);echo ":",$a;',
    'values-|=-"x"-null': b'<?php $a="x";echo ($a |= null);echo ":",$a;',
    'values-|=-"x"-true': b'<?php $a="x";echo ($a |= true);echo ":",$a;',
    'values-|=-"x"-2': b'<?php $a="x";echo ($a |= 2);echo ":",$a;',
    'values-|=-"x"-1.5': b'<?php $a="x";echo ($a |= 1.5);echo ":",$a;',
    'values-|=-"x"-"2"': b'<?php $a="x";echo ($a |= "2");echo ":",$a;',
    'values-|=-"x"-"x"': b'<?php $a="x";echo ($a |= "x");echo ":",$a;',
    'values-|=-"x"-[]': b'<?php $a="x";echo ($a |= []);echo ":",$a;',
    'values-|=-[]-null': b'<?php $a=[];echo ($a |= null);echo ":",$a;',
    'values-|=-[]-true': b'<?php $a=[];echo ($a |= true);echo ":",$a;',
    'values-|=-[]-2': b'<?php $a=[];echo ($a |= 2);echo ":",$a;',
    'values-|=-[]-1.5': b'<?php $a=[];echo ($a |= 1.5);echo ":",$a;',
    'values-|=-[]-"2"': b'<?php $a=[];echo ($a |= "2");echo ":",$a;',
    'values-|=-[]-"x"': b'<?php $a=[];echo ($a |= "x");echo ":",$a;',
    'values-|=-[]-[]': b'<?php $a=[];echo ($a |= []);echo ":",$a;',
    'values-^=-null-null': b'<?php $a=null;echo ($a ^= null);echo ":",$a;',
    'values-^=-null-true': b'<?php $a=null;echo ($a ^= true);echo ":",$a;',
    'values-^=-null-1.5': b'<?php $a=null;echo ($a ^= 1.5);echo ":",$a;',
    'values-^=-null-"2"': b'<?php $a=null;echo ($a ^= "2");echo ":",$a;',
    'values-^=-null-"x"': b'<?php $a=null;echo ($a ^= "x");echo ":",$a;',
    'values-^=-null-[]': b'<?php $a=null;echo ($a ^= []);echo ":",$a;',
    'values-^=-true-null': b'<?php $a=true;echo ($a ^= null);echo ":",$a;',
    'values-^=-true-true': b'<?php $a=true;echo ($a ^= true);echo ":",$a;',
    'values-^=-true-2': b'<?php $a=true;echo ($a ^= 2);echo ":",$a;',
    'values-^=-true-1.5': b'<?php $a=true;echo ($a ^= 1.5);echo ":",$a;',
    'values-^=-true-"2"': b'<?php $a=true;echo ($a ^= "2");echo ":",$a;',
    'values-^=-true-"x"': b'<?php $a=true;echo ($a ^= "x");echo ":",$a;',
    'values-^=-true-[]': b'<?php $a=true;echo ($a ^= []);echo ":",$a;',
    'values-^=-2-null': b'<?php $a=2;echo ($a ^= null);echo ":",$a;',
    'values-^=-2-true': b'<?php $a=2;echo ($a ^= true);echo ":",$a;',
    'values-^=-2-2': b'<?php $a=2;echo ($a ^= 2);echo ":",$a;',
    'values-^=-2-1.5': b'<?php $a=2;echo ($a ^= 1.5);echo ":",$a;',
    'values-^=-2-"2"': b'<?php $a=2;echo ($a ^= "2");echo ":",$a;',
    'values-^=-2-"x"': b'<?php $a=2;echo ($a ^= "x");echo ":",$a;',
    'values-^=-2-[]': b'<?php $a=2;echo ($a ^= []);echo ":",$a;',
    'values-^=-1.5-null': b'<?php $a=1.5;echo ($a ^= null);echo ":",$a;',
    'values-^=-1.5-true': b'<?php $a=1.5;echo ($a ^= true);echo ":",$a;',
    'values-^=-1.5-1.5': b'<?php $a=1.5;echo ($a ^= 1.5);echo ":",$a;',
    'values-^=-1.5-"2"': b'<?php $a=1.5;echo ($a ^= "2");echo ":",$a;',
    'values-^=-1.5-"x"': b'<?php $a=1.5;echo ($a ^= "x");echo ":",$a;',
    'values-^=-1.5-[]': b'<?php $a=1.5;echo ($a ^= []);echo ":",$a;',
    'values-^=-"2"-null': b'<?php $a="2";echo ($a ^= null);echo ":",$a;',
    'values-^=-"2"-true': b'<?php $a="2";echo ($a ^= true);echo ":",$a;',
    'values-^=-"2"-2': b'<?php $a="2";echo ($a ^= 2);echo ":",$a;',
    'values-^=-"2"-1.5': b'<?php $a="2";echo ($a ^= 1.5);echo ":",$a;',
    'values-^=-"2"-"2"': b'<?php $a="2";echo ($a ^= "2");echo ":",$a;',
    'values-^=-"2"-"x"': b'<?php $a="2";echo ($a ^= "x");echo ":",$a;',
    'values-^=-"2"-[]': b'<?php $a="2";echo ($a ^= []);echo ":",$a;',
    'values-^=-"x"-null': b'<?php $a="x";echo ($a ^= null);echo ":",$a;',
    'values-^=-"x"-true': b'<?php $a="x";echo ($a ^= true);echo ":",$a;',
    'values-^=-"x"-2': b'<?php $a="x";echo ($a ^= 2);echo ":",$a;',
    'values-^=-"x"-1.5': b'<?php $a="x";echo ($a ^= 1.5);echo ":",$a;',
    'values-^=-"x"-"2"': b'<?php $a="x";echo ($a ^= "2");echo ":",$a;',
    'values-^=-"x"-"x"': b'<?php $a="x";echo ($a ^= "x");echo ":",$a;',
    'values-^=-"x"-[]': b'<?php $a="x";echo ($a ^= []);echo ":",$a;',
    'values-^=-[]-null': b'<?php $a=[];echo ($a ^= null);echo ":",$a;',
    'values-^=-[]-true': b'<?php $a=[];echo ($a ^= true);echo ":",$a;',
    'values-^=-[]-2': b'<?php $a=[];echo ($a ^= 2);echo ":",$a;',
    'values-^=-[]-1.5': b'<?php $a=[];echo ($a ^= 1.5);echo ":",$a;',
    'values-^=-[]-"2"': b'<?php $a=[];echo ($a ^= "2");echo ":",$a;',
    'values-^=-[]-"x"': b'<?php $a=[];echo ($a ^= "x");echo ":",$a;',
    'values-^=-[]-[]': b'<?php $a=[];echo ($a ^= []);echo ":",$a;',
    'values-.=-null-null': b'<?php $a=null;echo ($a .= null);echo ":",$a;',
    'values-.=-null-true': b'<?php $a=null;echo ($a .= true);echo ":",$a;',
    'values-.=-null-1.5': b'<?php $a=null;echo ($a .= 1.5);echo ":",$a;',
    'values-.=-null-"2"': b'<?php $a=null;echo ($a .= "2");echo ":",$a;',
    'values-.=-null-"x"': b'<?php $a=null;echo ($a .= "x");echo ":",$a;',
    'values-.=-null-[]': b'<?php $a=null;echo ($a .= []);echo ":",$a;',
    'values-.=-true-null': b'<?php $a=true;echo ($a .= null);echo ":",$a;',
    'values-.=-true-true': b'<?php $a=true;echo ($a .= true);echo ":",$a;',
    'values-.=-true-2': b'<?php $a=true;echo ($a .= 2);echo ":",$a;',
    'values-.=-true-1.5': b'<?php $a=true;echo ($a .= 1.5);echo ":",$a;',
    'values-.=-true-"2"': b'<?php $a=true;echo ($a .= "2");echo ":",$a;',
    'values-.=-true-"x"': b'<?php $a=true;echo ($a .= "x");echo ":",$a;',
    'values-.=-true-[]': b'<?php $a=true;echo ($a .= []);echo ":",$a;',
    'values-.=-2-null': b'<?php $a=2;echo ($a .= null);echo ":",$a;',
    'values-.=-2-true': b'<?php $a=2;echo ($a .= true);echo ":",$a;',
    'values-.=-2-2': b'<?php $a=2;echo ($a .= 2);echo ":",$a;',
    'values-.=-2-1.5': b'<?php $a=2;echo ($a .= 1.5);echo ":",$a;',
    'values-.=-2-"2"': b'<?php $a=2;echo ($a .= "2");echo ":",$a;',
    'values-.=-2-"x"': b'<?php $a=2;echo ($a .= "x");echo ":",$a;',
    'values-.=-2-[]': b'<?php $a=2;echo ($a .= []);echo ":",$a;',
    'values-.=-1.5-null': b'<?php $a=1.5;echo ($a .= null);echo ":",$a;',
    'values-.=-1.5-true': b'<?php $a=1.5;echo ($a .= true);echo ":",$a;',
    'values-.=-1.5-1.5': b'<?php $a=1.5;echo ($a .= 1.5);echo ":",$a;',
    'values-.=-1.5-"2"': b'<?php $a=1.5;echo ($a .= "2");echo ":",$a;',
    'values-.=-1.5-"x"': b'<?php $a=1.5;echo ($a .= "x");echo ":",$a;',
    'values-.=-1.5-[]': b'<?php $a=1.5;echo ($a .= []);echo ":",$a;',
    'values-.=-"2"-null': b'<?php $a="2";echo ($a .= null);echo ":",$a;',
    'values-.=-"2"-true': b'<?php $a="2";echo ($a .= true);echo ":",$a;',
    'values-.=-"2"-2': b'<?php $a="2";echo ($a .= 2);echo ":",$a;',
    'values-.=-"2"-1.5': b'<?php $a="2";echo ($a .= 1.5);echo ":",$a;',
    'values-.=-"2"-"2"': b'<?php $a="2";echo ($a .= "2");echo ":",$a;',
    'values-.=-"2"-"x"': b'<?php $a="2";echo ($a .= "x");echo ":",$a;',
    'values-.=-"2"-[]': b'<?php $a="2";echo ($a .= []);echo ":",$a;',
    'values-.=-"x"-null': b'<?php $a="x";echo ($a .= null);echo ":",$a;',
    'values-.=-"x"-true': b'<?php $a="x";echo ($a .= true);echo ":",$a;',
    'values-.=-"x"-2': b'<?php $a="x";echo ($a .= 2);echo ":",$a;',
    'values-.=-"x"-1.5': b'<?php $a="x";echo ($a .= 1.5);echo ":",$a;',
    'values-.=-"x"-"2"': b'<?php $a="x";echo ($a .= "2");echo ":",$a;',
    'values-.=-"x"-"x"': b'<?php $a="x";echo ($a .= "x");echo ":",$a;',
    'values-.=-"x"-[]': b'<?php $a="x";echo ($a .= []);echo ":",$a;',
    'values-.=-[]-null': b'<?php $a=[];echo ($a .= null);echo ":",$a;',
    'values-.=-[]-true': b'<?php $a=[];echo ($a .= true);echo ":",$a;',
    'values-.=-[]-2': b'<?php $a=[];echo ($a .= 2);echo ":",$a;',
    'values-.=-[]-1.5': b'<?php $a=[];echo ($a .= 1.5);echo ":",$a;',
    'values-.=-[]-"2"': b'<?php $a=[];echo ($a .= "2");echo ":",$a;',
    'values-.=-[]-"x"': b'<?php $a=[];echo ($a .= "x");echo ":",$a;',
    'values-.=-[]-[]': b'<?php $a=[];echo ($a .= []);echo ":",$a;',
    'numeric-+=-PHP_INT_MAX-1': b'<?php $a=PHP_INT_MAX;echo ($a += 1);echo ":",$a;',
    'numeric-+=-PHP_INT_MIN--1': b'<?php $a=PHP_INT_MIN;echo ($a += -1);echo ":",$a;',
    'numeric-+=-INF-1': b'<?php $a=INF;echo ($a += 1);echo ":",$a;',
    'numeric-+=-NAN-1': b'<?php $a=NAN;echo ($a += 1);echo ":",$a;',
    'numeric-+=-"1.5tail"-2': b'<?php $a="1.5tail";echo ($a += 2);echo ":",$a;',
    'numeric-+=-"2tail"-1.5': b'<?php $a="2tail";echo ($a += 1.5);echo ":",$a;',
    'numeric-+=-"1.5tail"-[]': b'<?php $a="1.5tail";echo ($a += []);echo ":",$a;',
    'numeric-+=-[]-"1.5tail"': b'<?php $a=[];echo ($a += "1.5tail");echo ":",$a;',
    'numeric-+=-"1e400"-1': b'<?php $a="1e400";echo ($a += 1);echo ":",$a;',
    'numeric-+=-"9223372036854775808"-1': b'<?php $a="9223372036854775808";echo ($a += 1);echo ":",$a;',
    'numeric-+=-"-9223372036854775809"-1': b'<?php $a="-9223372036854775809";echo ($a += 1);echo ":",$a;',
    'numeric--=-PHP_INT_MAX-1': b'<?php $a=PHP_INT_MAX;echo ($a -= 1);echo ":",$a;',
    'numeric--=-PHP_INT_MIN--1': b'<?php $a=PHP_INT_MIN;echo ($a -= -1);echo ":",$a;',
    'numeric--=-INF-1': b'<?php $a=INF;echo ($a -= 1);echo ":",$a;',
    'numeric--=-NAN-1': b'<?php $a=NAN;echo ($a -= 1);echo ":",$a;',
    'numeric--=-"1.5tail"-2': b'<?php $a="1.5tail";echo ($a -= 2);echo ":",$a;',
    'numeric--=-"2tail"-1.5': b'<?php $a="2tail";echo ($a -= 1.5);echo ":",$a;',
    'numeric--=-"1.5tail"-[]': b'<?php $a="1.5tail";echo ($a -= []);echo ":",$a;',
    'numeric--=-[]-"1.5tail"': b'<?php $a=[];echo ($a -= "1.5tail");echo ":",$a;',
    'numeric--=-"1e400"-1': b'<?php $a="1e400";echo ($a -= 1);echo ":",$a;',
    'numeric--=-"9223372036854775808"-1': b'<?php $a="9223372036854775808";echo ($a -= 1);echo ":",$a;',
    'numeric--=-"-9223372036854775809"-1': b'<?php $a="-9223372036854775809";echo ($a -= 1);echo ":",$a;',
    'numeric-*=-PHP_INT_MAX-1': b'<?php $a=PHP_INT_MAX;echo ($a *= 1);echo ":",$a;',
    'numeric-*=-PHP_INT_MIN--1': b'<?php $a=PHP_INT_MIN;echo ($a *= -1);echo ":",$a;',
    'numeric-*=-INF-1': b'<?php $a=INF;echo ($a *= 1);echo ":",$a;',
    'numeric-*=-NAN-1': b'<?php $a=NAN;echo ($a *= 1);echo ":",$a;',
    'numeric-*=-"1.5tail"-2': b'<?php $a="1.5tail";echo ($a *= 2);echo ":",$a;',
    'numeric-*=-"2tail"-1.5': b'<?php $a="2tail";echo ($a *= 1.5);echo ":",$a;',
    'numeric-*=-"1.5tail"-[]': b'<?php $a="1.5tail";echo ($a *= []);echo ":",$a;',
    'numeric-*=-[]-"1.5tail"': b'<?php $a=[];echo ($a *= "1.5tail");echo ":",$a;',
    'numeric-*=-"1e400"-1': b'<?php $a="1e400";echo ($a *= 1);echo ":",$a;',
    'numeric-*=-"9223372036854775808"-1': b'<?php $a="9223372036854775808";echo ($a *= 1);echo ":",$a;',
    'numeric-*=-"-9223372036854775809"-1': b'<?php $a="-9223372036854775809";echo ($a *= 1);echo ":",$a;',
    'numeric-/=-PHP_INT_MAX-1': b'<?php $a=PHP_INT_MAX;echo ($a /= 1);echo ":",$a;',
    'numeric-/=-PHP_INT_MIN--1': b'<?php $a=PHP_INT_MIN;echo ($a /= -1);echo ":",$a;',
    'numeric-/=-INF-1': b'<?php $a=INF;echo ($a /= 1);echo ":",$a;',
    'numeric-/=-NAN-1': b'<?php $a=NAN;echo ($a /= 1);echo ":",$a;',
    'numeric-/=-"1.5tail"-2': b'<?php $a="1.5tail";echo ($a /= 2);echo ":",$a;',
    'numeric-/=-"2tail"-1.5': b'<?php $a="2tail";echo ($a /= 1.5);echo ":",$a;',
    'numeric-/=-"1.5tail"-[]': b'<?php $a="1.5tail";echo ($a /= []);echo ":",$a;',
    'numeric-/=-[]-"1.5tail"': b'<?php $a=[];echo ($a /= "1.5tail");echo ":",$a;',
    'numeric-/=-"1e400"-1': b'<?php $a="1e400";echo ($a /= 1);echo ":",$a;',
    'numeric-/=-"9223372036854775808"-1': b'<?php $a="9223372036854775808";echo ($a /= 1);echo ":",$a;',
    'numeric-/=-"-9223372036854775809"-1': b'<?php $a="-9223372036854775809";echo ($a /= 1);echo ":",$a;',
    'numeric-%=-PHP_INT_MAX-1': b'<?php $a=PHP_INT_MAX;echo ($a %= 1);echo ":",$a;',
    'numeric-%=-PHP_INT_MIN--1': b'<?php $a=PHP_INT_MIN;echo ($a %= -1);echo ":",$a;',
    'numeric-%=-INF-1': b'<?php $a=INF;echo ($a %= 1);echo ":",$a;',
    'numeric-%=-NAN-1': b'<?php $a=NAN;echo ($a %= 1);echo ":",$a;',
    'numeric-%=-"1.5tail"-2': b'<?php $a="1.5tail";echo ($a %= 2);echo ":",$a;',
    'numeric-%=-"2tail"-1.5': b'<?php $a="2tail";echo ($a %= 1.5);echo ":",$a;',
    'numeric-%=-"1.5tail"-[]': b'<?php $a="1.5tail";echo ($a %= []);echo ":",$a;',
    'numeric-%=-[]-"1.5tail"': b'<?php $a=[];echo ($a %= "1.5tail");echo ":",$a;',
    'numeric-%=-"1e400"-1': b'<?php $a="1e400";echo ($a %= 1);echo ":",$a;',
    'numeric-%=-"9223372036854775808"-1': b'<?php $a="9223372036854775808";echo ($a %= 1);echo ":",$a;',
    'numeric-%=-"-9223372036854775809"-1': b'<?php $a="-9223372036854775809";echo ($a %= 1);echo ":",$a;',
    'numeric-**=-PHP_INT_MAX-1': b'<?php $a=PHP_INT_MAX;echo ($a **= 1);echo ":",$a;',
    'numeric-**=-PHP_INT_MIN--1': b'<?php $a=PHP_INT_MIN;echo ($a **= -1);echo ":",$a;',
    'numeric-**=-INF-1': b'<?php $a=INF;echo ($a **= 1);echo ":",$a;',
    'numeric-**=-NAN-1': b'<?php $a=NAN;echo ($a **= 1);echo ":",$a;',
    'numeric-**=-"1.5tail"-2': b'<?php $a="1.5tail";echo ($a **= 2);echo ":",$a;',
    'numeric-**=-"2tail"-1.5': b'<?php $a="2tail";echo ($a **= 1.5);echo ":",$a;',
    'numeric-**=-"1.5tail"-[]': b'<?php $a="1.5tail";echo ($a **= []);echo ":",$a;',
    'numeric-**=-[]-"1.5tail"': b'<?php $a=[];echo ($a **= "1.5tail");echo ":",$a;',
    'numeric-**=-"1e400"-1': b'<?php $a="1e400";echo ($a **= 1);echo ":",$a;',
    'numeric-**=-"9223372036854775808"-1': b'<?php $a="9223372036854775808";echo ($a **= 1);echo ":",$a;',
    'numeric-**=-"-9223372036854775809"-1': b'<?php $a="-9223372036854775809";echo ($a **= 1);echo ":",$a;',
    'numeric-<<=-PHP_INT_MAX-1': b'<?php $a=PHP_INT_MAX;echo ($a <<= 1);echo ":",$a;',
    'numeric-<<=-PHP_INT_MIN--1': b'<?php $a=PHP_INT_MIN;echo ($a <<= -1);echo ":",$a;',
    'numeric-<<=-INF-1': b'<?php $a=INF;echo ($a <<= 1);echo ":",$a;',
    'numeric-<<=-NAN-1': b'<?php $a=NAN;echo ($a <<= 1);echo ":",$a;',
    'numeric-<<=-"1.5tail"-2': b'<?php $a="1.5tail";echo ($a <<= 2);echo ":",$a;',
    'numeric-<<=-"2tail"-1.5': b'<?php $a="2tail";echo ($a <<= 1.5);echo ":",$a;',
    'numeric-<<=-"1.5tail"-[]': b'<?php $a="1.5tail";echo ($a <<= []);echo ":",$a;',
    'numeric-<<=-[]-"1.5tail"': b'<?php $a=[];echo ($a <<= "1.5tail");echo ":",$a;',
    'numeric-<<=-"1e400"-1': b'<?php $a="1e400";echo ($a <<= 1);echo ":",$a;',
    'numeric-<<=-"9223372036854775808"-1': b'<?php $a="9223372036854775808";echo ($a <<= 1);echo ":",$a;',
    'numeric-<<=-"-9223372036854775809"-1': b'<?php $a="-9223372036854775809";echo ($a <<= 1);echo ":",$a;',
    'numeric->>=-PHP_INT_MAX-1': b'<?php $a=PHP_INT_MAX;echo ($a >>= 1);echo ":",$a;',
    'numeric->>=-PHP_INT_MIN--1': b'<?php $a=PHP_INT_MIN;echo ($a >>= -1);echo ":",$a;',
    'numeric->>=-INF-1': b'<?php $a=INF;echo ($a >>= 1);echo ":",$a;',
    'numeric->>=-NAN-1': b'<?php $a=NAN;echo ($a >>= 1);echo ":",$a;',
    'numeric->>=-"1.5tail"-2': b'<?php $a="1.5tail";echo ($a >>= 2);echo ":",$a;',
    'numeric->>=-"2tail"-1.5': b'<?php $a="2tail";echo ($a >>= 1.5);echo ":",$a;',
    'numeric->>=-"1.5tail"-[]': b'<?php $a="1.5tail";echo ($a >>= []);echo ":",$a;',
    'numeric->>=-[]-"1.5tail"': b'<?php $a=[];echo ($a >>= "1.5tail");echo ":",$a;',
    'numeric->>=-"1e400"-1': b'<?php $a="1e400";echo ($a >>= 1);echo ":",$a;',
    'numeric->>=-"9223372036854775808"-1': b'<?php $a="9223372036854775808";echo ($a >>= 1);echo ":",$a;',
    'numeric->>=-"-9223372036854775809"-1': b'<?php $a="-9223372036854775809";echo ($a >>= 1);echo ":",$a;',
    'numeric-&=-PHP_INT_MAX-1': b'<?php $a=PHP_INT_MAX;echo ($a &= 1);echo ":",$a;',
    'numeric-&=-PHP_INT_MIN--1': b'<?php $a=PHP_INT_MIN;echo ($a &= -1);echo ":",$a;',
    'numeric-&=-INF-1': b'<?php $a=INF;echo ($a &= 1);echo ":",$a;',
    'numeric-&=-NAN-1': b'<?php $a=NAN;echo ($a &= 1);echo ":",$a;',
    'numeric-&=-"1.5tail"-2': b'<?php $a="1.5tail";echo ($a &= 2);echo ":",$a;',
    'numeric-&=-"2tail"-1.5': b'<?php $a="2tail";echo ($a &= 1.5);echo ":",$a;',
    'numeric-&=-"1.5tail"-[]': b'<?php $a="1.5tail";echo ($a &= []);echo ":",$a;',
    'numeric-&=-[]-"1.5tail"': b'<?php $a=[];echo ($a &= "1.5tail");echo ":",$a;',
    'numeric-&=-"1e400"-1': b'<?php $a="1e400";echo ($a &= 1);echo ":",$a;',
    'numeric-&=-"9223372036854775808"-1': b'<?php $a="9223372036854775808";echo ($a &= 1);echo ":",$a;',
    'numeric-&=-"-9223372036854775809"-1': b'<?php $a="-9223372036854775809";echo ($a &= 1);echo ":",$a;',
    'numeric-|=-PHP_INT_MAX-1': b'<?php $a=PHP_INT_MAX;echo ($a |= 1);echo ":",$a;',
    'numeric-|=-PHP_INT_MIN--1': b'<?php $a=PHP_INT_MIN;echo ($a |= -1);echo ":",$a;',
    'numeric-|=-INF-1': b'<?php $a=INF;echo ($a |= 1);echo ":",$a;',
    'numeric-|=-NAN-1': b'<?php $a=NAN;echo ($a |= 1);echo ":",$a;',
    'numeric-|=-"1.5tail"-2': b'<?php $a="1.5tail";echo ($a |= 2);echo ":",$a;',
    'numeric-|=-"2tail"-1.5': b'<?php $a="2tail";echo ($a |= 1.5);echo ":",$a;',
    'numeric-|=-"1.5tail"-[]': b'<?php $a="1.5tail";echo ($a |= []);echo ":",$a;',
    'numeric-|=-[]-"1.5tail"': b'<?php $a=[];echo ($a |= "1.5tail");echo ":",$a;',
    'numeric-|=-"1e400"-1': b'<?php $a="1e400";echo ($a |= 1);echo ":",$a;',
    'numeric-|=-"9223372036854775808"-1': b'<?php $a="9223372036854775808";echo ($a |= 1);echo ":",$a;',
    'numeric-|=-"-9223372036854775809"-1': b'<?php $a="-9223372036854775809";echo ($a |= 1);echo ":",$a;',
    'numeric-^=-PHP_INT_MAX-1': b'<?php $a=PHP_INT_MAX;echo ($a ^= 1);echo ":",$a;',
    'numeric-^=-PHP_INT_MIN--1': b'<?php $a=PHP_INT_MIN;echo ($a ^= -1);echo ":",$a;',
    'numeric-^=-INF-1': b'<?php $a=INF;echo ($a ^= 1);echo ":",$a;',
    'numeric-^=-NAN-1': b'<?php $a=NAN;echo ($a ^= 1);echo ":",$a;',
    'numeric-^=-"1.5tail"-2': b'<?php $a="1.5tail";echo ($a ^= 2);echo ":",$a;',
    'numeric-^=-"2tail"-1.5': b'<?php $a="2tail";echo ($a ^= 1.5);echo ":",$a;',
    'numeric-^=-"1.5tail"-[]': b'<?php $a="1.5tail";echo ($a ^= []);echo ":",$a;',
    'numeric-^=-[]-"1.5tail"': b'<?php $a=[];echo ($a ^= "1.5tail");echo ":",$a;',
    'numeric-^=-"1e400"-1': b'<?php $a="1e400";echo ($a ^= 1);echo ":",$a;',
    'numeric-^=-"9223372036854775808"-1': b'<?php $a="9223372036854775808";echo ($a ^= 1);echo ":",$a;',
    'numeric-^=-"-9223372036854775809"-1': b'<?php $a="-9223372036854775809";echo ($a ^= 1);echo ":",$a;',
    'numeric-.=-PHP_INT_MAX-1': b'<?php $a=PHP_INT_MAX;echo ($a .= 1);echo ":",$a;',
    'numeric-.=-PHP_INT_MIN--1': b'<?php $a=PHP_INT_MIN;echo ($a .= -1);echo ":",$a;',
    'numeric-.=-INF-1': b'<?php $a=INF;echo ($a .= 1);echo ":",$a;',
    'numeric-.=-NAN-1': b'<?php $a=NAN;echo ($a .= 1);echo ":",$a;',
    'numeric-.=-"1.5tail"-2': b'<?php $a="1.5tail";echo ($a .= 2);echo ":",$a;',
    'numeric-.=-"2tail"-1.5': b'<?php $a="2tail";echo ($a .= 1.5);echo ":",$a;',
    'numeric-.=-"1.5tail"-[]': b'<?php $a="1.5tail";echo ($a .= []);echo ":",$a;',
    'numeric-.=-[]-"1.5tail"': b'<?php $a=[];echo ($a .= "1.5tail");echo ":",$a;',
    'numeric-.=-"1e400"-1': b'<?php $a="1e400";echo ($a .= 1);echo ":",$a;',
    'numeric-.=-"9223372036854775808"-1': b'<?php $a="9223372036854775808";echo ($a .= 1);echo ":",$a;',
    'numeric-.=-"-9223372036854775809"-1': b'<?php $a="-9223372036854775809";echo ($a .= 1);echo ":",$a;',
    'numeric-power-0--1': b'<?php $a=0;echo ($a **= -1);echo ":",$a;',
    'numeric-power--0.0--1': b'<?php $a=-0.0;echo ($a **= -1);echo ":",$a;',
    'numeric-power--2-0.5': b'<?php $a=-2;echo ($a **= 0.5);echo ":",$a;',
    'numeric-power-2-1024': b'<?php $a=2;echo ($a **= 1024);echo ":",$a;',
    'numeric-power--1-NAN': b'<?php $a=-1;echo ($a **= NAN);echo ":",$a;',
    'numeric-<<=count63': b'<?php $a=-1;echo ($a <<= 63);',
    'numeric-<<=count64': b'<?php $a=-1;echo ($a <<= 64);',
    'numeric-<<=count65': b'<?php $a=-1;echo ($a <<= 65);',
    'numeric-<<=countPHP_INT_MAX': b'<?php $a=-1;echo ($a <<= PHP_INT_MAX);',
    'numeric-<<=countINF': b'<?php $a=-1;echo ($a <<= INF);',
    'numeric->>=count63': b'<?php $a=-1;echo ($a >>= 63);',
    'numeric->>=count64': b'<?php $a=-1;echo ($a >>= 64);',
    'numeric->>=count65': b'<?php $a=-1;echo ($a >>= 65);',
    'numeric->>=countPHP_INT_MAX': b'<?php $a=-1;echo ($a >>= PHP_INT_MAX);',
    'numeric->>=countINF': b'<?php $a=-1;echo ($a >>= INF);',
    'numeric-&=bytes"\\0\\xffA"': b'<?php $a="\\0\\xffA";echo ($a &= "\\x80B");echo ":",$a;',
    'numeric-&=bytes""': b'<?php $a="";echo ($a &= "abc");echo ":",$a;',
    'numeric-|=bytes"\\0\\xffA"': b'<?php $a="\\0\\xffA";echo ($a |= "\\x80B");echo ":",$a;',
    'numeric-|=bytes""': b'<?php $a="";echo ($a |= "abc");echo ":",$a;',
    'numeric-^=bytes"\\0\\xffA"': b'<?php $a="\\0\\xffA";echo ($a ^= "\\x80B");echo ":",$a;',
    'numeric-^=bytes""': b'<?php $a="";echo ($a ^= "abc");echo ":",$a;',
    'locations-location-0': b'<?php $n="a";$a=1;$b=2;echo ($$n += (($n="b")=="b"));echo $a,$b;',
    'locations-location-1': b'<?php $n="a";$a=1;$b=2;echo (${($n="a")} += (($n="b")=="b"));echo $a,$b;',
    'locations-location-2': b'<?php $n="a";$r=&$n;$a=1;$b=2;echo (${($q=&$r)} += (($n="b")=="b"));echo $a,$b;',
    'locations-location-3': b'<?php $a=[1,2];$k=0;echo ($a[$k] += ($k=1));echo $a[0],$a[1];',
    'locations-location-4': b'<?php $a=[1,2];$k=0;echo ($a[$k+0] += ($k=1));echo $a[0],$a[1];',
    'locations-location-5': b'<?php $a=[1,2];$k=0;echo ($a[($r=&$k)] += ($k=1));echo $a[0],$a[1];',
    'locations-location-7': b'<?php $a=[1];$r=&$a[0];echo ($a[0] += ($r=4));echo $r;',
    'locations-location-8': b'<?php $a=[1];$r=&$a[0];$b=[2];echo ($r += ($a=&$b)[0]);echo $r,$a[0];',
    'locations-location-9': b'<?php $a=[[1]];$b=$a;echo ($a[0][0] += ($a[0]=[4])[0]);echo $a[0][0],$b[0][0];',
    'locations-location-10': b'<?php $a=false;$r=&$a;$n="a";$$n[0][0]+=1;echo $a[0][0];',
    'locations-location-11': b'<?php $a=false;$r=&$a;$n="a";$$n[0]+=1;echo $a[0];',
    'locations-location-12': b'<?php $a=false;$r=&$a;unset($r);$n="a";$$n[0][0]+=1;echo $a[0][0];',
    'locations-location-13': b'<?php $n="a";$$n=false;$$n[0][0]+=1;echo $a[0][0];',
    'locations-location-14': b'<?php $a=[0];$b=($a += [1=>1]);$b[0]=2;echo $a[0],$b[0];',
    'locations-location-15': b'<?php $x=1;$a=[&$x];$b=($a += []);$b[0]=2;echo $x,$a[0];',
    'locations-location-16': b'<?php $x=1;$a=[&$x];unset($x);$b=($a += []);$b[0]=2;echo $a[0],$b[0];',
    'locations-location-17': b'<?php $a=[];$a[0]=&$a;$b=($a += []);$b[1]=2;echo $a===$b;',
    'locations-location-18': b'<?php $a=[NAN];$b=($a += $a);echo $a===$b;',
    'locations-location-19': b'<?php $a=[NAN];$b=($a += []);echo $a===$b;',
    'locations-location-20': b'<?php $a=1;$r=($a+=2);$a=4;echo $r,$a;',
    'locations-location-21': b'<?php $a="a";$r=($a.="b");$a="c";echo $r,$a;',
    'locations-location-22': b'<?php $a=[];$a[] .= "x";echo $a[0];',
    'locations-location-23': b'<?php $a=[];$a[][0] |= 1;echo $a[0][0];',
    'locations-location-24': b'<?php $a=[PHP_INT_MAX=>1];$a[]+=($missing+1);',
    'locations-location-25': b'<?php $a="abc";$a[$missing]+=($rhs+1);',
    'locations-location-26': b'<?php $a="abc";$a[1.5]+=($rhs+1);',
    'locations-location-27': b'<?php $a="abc";$a[[]][0]+=($rhs+1);',
    'locations-location-28': b'<?php $a=1;$a[$missing]+=($rhs+1);',
    'locations-location-29': b'<?php $a[0]+=$this;',
    'locations-location-30': b'<?php $n="this";$$n+=($missing+1);',
    'locations-location-31': b'<?php $n="this";$$n[$missing]+=($rhs+1);',
    'locations-location-32': b'<?php $n="this";$$n[($missing+1)]+=($rhs+1);',
    'locations-location-33': b'<?php\n$n="a";\n$$n +=\n1;',
    'locations-location-34': b'<?php\n$n="this";\n$$n +=\n1;',
    'locations-location-35': b'<?php\n$n="a";\n$$n[\n0\n] +=\n1;',
    'locations-location-36': b'<?php\n$a[\n$k\n][\n$j\n] +=\n$rhs+1;',
    'loop-locations-name-capture': b'<?php $n="a";$a=1;$b=2;for($i=0;$i<3;$i++){$n="a";echo ($$n += (($n="b")=="b"));echo $a,$b;}',
    'loop-locations-reference-return': b'<?php $x=1;$a=[&$x];for($i=0;$i<3;$i++){$b=($a += []);$b[0]+=1;echo $x,$a[0];}',
    'timing-0': b'<?php $n="this";$$n += ($missing+1);',
    'timing-1': b'<?php $n="a";$$n += ($missing+1);',
    'timing-2': b'<?php $a[0] += ($missing+1);',
    'timing-3': b'<?php $a[0][0] += ($missing+1);',
    'original-this-0': b'<?php use A; $this += 1; use B;',
    'original-this-2': b'<?php use A; ${"this"} += 1; use B;',
    'original-this-4': b'<?php use A; ${true?"this":"other"} += 1; use B;',
    'original-this-6': b'<?php use A; $this -= 1; use B;',
    'original-this-8': b'<?php use A; ${"this"} -= 1; use B;',
    'original-this-10': b'<?php use A; ${true?"this":"other"} -= 1; use B;',
    'original-this-12': b'<?php use A; $this *= 1; use B;',
    'original-this-14': b'<?php use A; ${"this"} *= 1; use B;',
    'original-this-16': b'<?php use A; ${true?"this":"other"} *= 1; use B;',
    'original-this-18': b'<?php use A; $this /= 1; use B;',
    'original-this-20': b'<?php use A; ${"this"} /= 1; use B;',
    'original-this-22': b'<?php use A; ${true?"this":"other"} /= 1; use B;',
    'original-this-24': b'<?php use A; $this %= 1; use B;',
    'original-this-26': b'<?php use A; ${"this"} %= 1; use B;',
    'original-this-28': b'<?php use A; ${true?"this":"other"} %= 1; use B;',
    'original-this-30': b'<?php use A; $this **= 1; use B;',
    'original-this-32': b'<?php use A; ${"this"} **= 1; use B;',
    'original-this-34': b'<?php use A; ${true?"this":"other"} **= 1; use B;',
    'original-this-36': b'<?php use A; $this .= 1; use B;',
    'original-this-38': b'<?php use A; ${"this"} .= 1; use B;',
    'original-this-40': b'<?php use A; ${true?"this":"other"} .= 1; use B;',
    'original-this-42': b'<?php use A; $this &= 1; use B;',
    'original-this-44': b'<?php use A; ${"this"} &= 1; use B;',
    'original-this-46': b'<?php use A; ${true?"this":"other"} &= 1; use B;',
    'original-this-48': b'<?php use A; $this |= 1; use B;',
    'original-this-50': b'<?php use A; ${"this"} |= 1; use B;',
    'original-this-52': b'<?php use A; ${true?"this":"other"} |= 1; use B;',
    'original-this-54': b'<?php use A; $this ^= 1; use B;',
    'original-this-56': b'<?php use A; ${"this"} ^= 1; use B;',
    'original-this-58': b'<?php use A; ${true?"this":"other"} ^= 1; use B;',
    'original-this-60': b'<?php use A; $this <<= 1; use B;',
    'original-this-62': b'<?php use A; ${"this"} <<= 1; use B;',
    'original-this-64': b'<?php use A; ${true?"this":"other"} <<= 1; use B;',
    'original-this-66': b'<?php use A; $this >>= 1; use B;',
    'original-this-68': b'<?php use A; ${"this"} >>= 1; use B;',
    'original-this-70': b'<?php use A; ${true?"this":"other"} >>= 1; use B;',
    'original-line-0': b'<?php $a=[1];\necho $a[\n0\n]\n+=\n"2x";',
    'original-line-1': b'<?php $a=[1];\necho $a[\n0\n]\n+=\n$a;',
    'original-line-2': b'<?php $a=1;\necho $a\n+=\n"2x";',
    'original-line-3': b'<?php $a=1;\necho $a\n+=\n$a;',
    'original-line-4': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n+=\n"2x";',
    'original-line-5': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n+=\n$a;',
    'original-line-6': b'<?php $a=[1];\necho $a[\n0\n]\n-=\n"2x";',
    'original-line-7': b'<?php $a=[1];\necho $a[\n0\n]\n-=\n$a;',
    'original-line-8': b'<?php $a=1;\necho $a\n-=\n"2x";',
    'original-line-9': b'<?php $a=1;\necho $a\n-=\n$a;',
    'original-line-10': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n-=\n"2x";',
    'original-line-11': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n-=\n$a;',
    'original-line-12': b'<?php $a=[1];\necho $a[\n0\n]\n*=\n"2x";',
    'original-line-13': b'<?php $a=[1];\necho $a[\n0\n]\n*=\n$a;',
    'original-line-14': b'<?php $a=1;\necho $a\n*=\n"2x";',
    'original-line-15': b'<?php $a=1;\necho $a\n*=\n$a;',
    'original-line-16': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n*=\n"2x";',
    'original-line-17': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n*=\n$a;',
    'original-line-18': b'<?php $a=[1];\necho $a[\n0\n]\n/=\n"2x";',
    'original-line-19': b'<?php $a=[1];\necho $a[\n0\n]\n/=\n$a;',
    'original-line-20': b'<?php $a=1;\necho $a\n/=\n"2x";',
    'original-line-21': b'<?php $a=1;\necho $a\n/=\n$a;',
    'original-line-22': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n/=\n"2x";',
    'original-line-23': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n/=\n$a;',
    'original-line-24': b'<?php $a=[1];\necho $a[\n0\n]\n%=\n"2x";',
    'original-line-25': b'<?php $a=[1];\necho $a[\n0\n]\n%=\n$a;',
    'original-line-26': b'<?php $a=1;\necho $a\n%=\n"2x";',
    'original-line-27': b'<?php $a=1;\necho $a\n%=\n$a;',
    'original-line-28': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n%=\n"2x";',
    'original-line-29': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n%=\n$a;',
    'original-line-30': b'<?php $a=[1];\necho $a[\n0\n]\n**=\n"2x";',
    'original-line-31': b'<?php $a=[1];\necho $a[\n0\n]\n**=\n$a;',
    'original-line-32': b'<?php $a=1;\necho $a\n**=\n"2x";',
    'original-line-33': b'<?php $a=1;\necho $a\n**=\n$a;',
    'original-line-34': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n**=\n"2x";',
    'original-line-35': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n**=\n$a;',
    'original-line-36': b'<?php $a=[1];\necho $a[\n0\n]\n.=\n[];',
    'original-line-37': b'<?php $a=[1];\necho $a[\n0\n]\n.=\n$a;',
    'original-line-38': b'<?php $a=1;\necho $a\n.=\n[];',
    'original-line-39': b'<?php $a=1;\necho $a\n.=\n$a;',
    'original-line-40': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n.=\n[];',
    'original-line-41': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n.=\n$a;',
    'original-line-42': b'<?php $a=[1];\necho $a[\n0\n]\n&=\n"2x";',
    'original-line-43': b'<?php $a=[1];\necho $a[\n0\n]\n&=\n$a;',
    'original-line-44': b'<?php $a=1;\necho $a\n&=\n"2x";',
    'original-line-45': b'<?php $a=1;\necho $a\n&=\n$a;',
    'original-line-46': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n&=\n"2x";',
    'original-line-47': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n&=\n$a;',
    'original-line-48': b'<?php $a=[1];\necho $a[\n0\n]\n|=\n"2x";',
    'original-line-49': b'<?php $a=[1];\necho $a[\n0\n]\n|=\n$a;',
    'original-line-50': b'<?php $a=1;\necho $a\n|=\n"2x";',
    'original-line-51': b'<?php $a=1;\necho $a\n|=\n$a;',
    'original-line-52': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n|=\n"2x";',
    'original-line-53': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n|=\n$a;',
    'original-line-54': b'<?php $a=[1];\necho $a[\n0\n]\n^=\n"2x";',
    'original-line-55': b'<?php $a=[1];\necho $a[\n0\n]\n^=\n$a;',
    'original-line-56': b'<?php $a=1;\necho $a\n^=\n"2x";',
    'original-line-57': b'<?php $a=1;\necho $a\n^=\n$a;',
    'original-line-58': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n^=\n"2x";',
    'original-line-59': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n^=\n$a;',
    'original-line-60': b'<?php $a=[1];\necho $a[\n0\n]\n<<=\n"2x";',
    'original-line-61': b'<?php $a=[1];\necho $a[\n0\n]\n<<=\n$a;',
    'original-line-62': b'<?php $a=1;\necho $a\n<<=\n"2x";',
    'original-line-63': b'<?php $a=1;\necho $a\n<<=\n$a;',
    'original-line-64': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n<<=\n"2x";',
    'original-line-65': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n<<=\n$a;',
    'original-line-66': b'<?php $a=[1];\necho $a[\n0\n]\n>>=\n"2x";',
    'original-line-67': b'<?php $a=[1];\necho $a[\n0\n]\n>>=\n$a;',
    'original-line-68': b'<?php $a=1;\necho $a\n>>=\n"2x";',
    'original-line-69': b'<?php $a=1;\necho $a\n>>=\n$a;',
    'original-line-70': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n>>=\n"2x";',
    'original-line-71': b'<?php $a=1;$n="a";\necho ${\n$n\n}\n>>=\n$a;',
    'original-runtime-line-0': b'<?php $a=[1];\necho $a[\n0\n] +=\n"2x";',
    'original-runtime-line-1': b'<?php $a=[1];\necho $a[\n0\n] +=\n$missing;',
    'original-runtime-line-2': b'<?php $a=1;\necho $a +=\n"2x";',
}
CASES = {"compound-"+name:source for name,source in NORMAL_CASES.items()}
CASES.update({
    'compound-original-this-1': b'<?php use A; $this += [&$q[]]; use B;',
    'compound-original-this-3': b'<?php use A; ${"this"} += [&$q[]]; use B;',
    'compound-original-this-5': b'<?php use A; ${true?"this":"other"} += [&$q[]]; use B;',
    'compound-original-this-7': b'<?php use A; $this -= [&$q[]]; use B;',
    'compound-original-this-9': b'<?php use A; ${"this"} -= [&$q[]]; use B;',
    'compound-original-this-11': b'<?php use A; ${true?"this":"other"} -= [&$q[]]; use B;',
    'compound-original-this-13': b'<?php use A; $this *= [&$q[]]; use B;',
    'compound-original-this-15': b'<?php use A; ${"this"} *= [&$q[]]; use B;',
    'compound-original-this-17': b'<?php use A; ${true?"this":"other"} *= [&$q[]]; use B;',
    'compound-original-this-19': b'<?php use A; $this /= [&$q[]]; use B;',
    'compound-original-this-21': b'<?php use A; ${"this"} /= [&$q[]]; use B;',
    'compound-original-this-23': b'<?php use A; ${true?"this":"other"} /= [&$q[]]; use B;',
    'compound-original-this-25': b'<?php use A; $this %= [&$q[]]; use B;',
    'compound-original-this-27': b'<?php use A; ${"this"} %= [&$q[]]; use B;',
    'compound-original-this-29': b'<?php use A; ${true?"this":"other"} %= [&$q[]]; use B;',
    'compound-original-this-31': b'<?php use A; $this **= [&$q[]]; use B;',
    'compound-original-this-33': b'<?php use A; ${"this"} **= [&$q[]]; use B;',
    'compound-original-this-35': b'<?php use A; ${true?"this":"other"} **= [&$q[]]; use B;',
    'compound-original-this-37': b'<?php use A; $this .= [&$q[]]; use B;',
    'compound-original-this-39': b'<?php use A; ${"this"} .= [&$q[]]; use B;',
    'compound-original-this-41': b'<?php use A; ${true?"this":"other"} .= [&$q[]]; use B;',
    'compound-original-this-43': b'<?php use A; $this &= [&$q[]]; use B;',
    'compound-original-this-45': b'<?php use A; ${"this"} &= [&$q[]]; use B;',
    'compound-original-this-47': b'<?php use A; ${true?"this":"other"} &= [&$q[]]; use B;',
    'compound-original-this-49': b'<?php use A; $this |= [&$q[]]; use B;',
    'compound-original-this-51': b'<?php use A; ${"this"} |= [&$q[]]; use B;',
    'compound-original-this-53': b'<?php use A; ${true?"this":"other"} |= [&$q[]]; use B;',
    'compound-original-this-55': b'<?php use A; $this ^= [&$q[]]; use B;',
    'compound-original-this-57': b'<?php use A; ${"this"} ^= [&$q[]]; use B;',
    'compound-original-this-59': b'<?php use A; ${true?"this":"other"} ^= [&$q[]]; use B;',
    'compound-original-this-61': b'<?php use A; $this <<= [&$q[]]; use B;',
    'compound-original-this-63': b'<?php use A; ${"this"} <<= [&$q[]]; use B;',
    'compound-original-this-65': b'<?php use A; ${true?"this":"other"} <<= [&$q[]]; use B;',
    'compound-original-this-67': b'<?php use A; $this >>= [&$q[]]; use B;',
    'compound-original-this-69': b'<?php use A; ${"this"} >>= [&$q[]]; use B;',
    'compound-original-this-71': b'<?php use A; ${true?"this":"other"} >>= [&$q[]]; use B;',
})

# Additional exact compiler phase and emission originals.
CASES.update({
    'compound-phase-+=/$x/1': b'<?php use A; $x += 1; use B;',
    'compound-phase-+=/$x/[&$q[]]': b'<?php use A; $x += [&$q[]]; use B;',
    'compound-phase-+=/$a[]/1': b'<?php use A; $a[] += 1; use B;',
    'compound-phase-+=/$a[]/[&$q[]]': b'<?php use A; $a[] += [&$q[]]; use B;',
    'compound-phase-+=/foo()/1': b'<?php use A; foo() += 1; use B;',
    'compound-phase-+=/foo()/[&$q[]]': b'<?php use A; foo() += [&$q[]]; use B;',
    'compound-phase-+=/$o?->p/1': b'<?php use A; $o?->p += 1; use B;',
    'compound-phase-+=/$o?->p/[&$q[]]': b'<?php use A; $o?->p += [&$q[]]; use B;',
    'compound-phase-deep-+=-false': b'<?php use A; echo [false && ($a += [[[]=>1]])][0]; use B;',
    'compound-phase-deep-+=-true': b'<?php use A; echo [true && ($a += [[[]=>1]])][0]; use B;',
    'compound-phase-array-value-+=': b'<?php $a=1;$b=[($a += 1)];echo $b[0];',
    'compound-phase-array-key-+=': b'<?php $a=1;$b=[($a += 1)=>2];echo $a;',
    'compound-phase--=/$x/1': b'<?php use A; $x -= 1; use B;',
    'compound-phase--=/$x/[&$q[]]': b'<?php use A; $x -= [&$q[]]; use B;',
    'compound-phase--=/$a[]/1': b'<?php use A; $a[] -= 1; use B;',
    'compound-phase--=/$a[]/[&$q[]]': b'<?php use A; $a[] -= [&$q[]]; use B;',
    'compound-phase--=/foo()/1': b'<?php use A; foo() -= 1; use B;',
    'compound-phase--=/foo()/[&$q[]]': b'<?php use A; foo() -= [&$q[]]; use B;',
    'compound-phase--=/$o?->p/1': b'<?php use A; $o?->p -= 1; use B;',
    'compound-phase--=/$o?->p/[&$q[]]': b'<?php use A; $o?->p -= [&$q[]]; use B;',
    'compound-phase-deep--=-false': b'<?php use A; echo [false && ($a -= [[[]=>1]])][0]; use B;',
    'compound-phase-deep--=-true': b'<?php use A; echo [true && ($a -= [[[]=>1]])][0]; use B;',
    'compound-phase-array-value--=': b'<?php $a=1;$b=[($a -= 1)];echo $b[0];',
    'compound-phase-array-key--=': b'<?php $a=1;$b=[($a -= 1)=>2];echo $a;',
    'compound-phase-*=/$x/1': b'<?php use A; $x *= 1; use B;',
    'compound-phase-*=/$x/[&$q[]]': b'<?php use A; $x *= [&$q[]]; use B;',
    'compound-phase-*=/$a[]/1': b'<?php use A; $a[] *= 1; use B;',
    'compound-phase-*=/$a[]/[&$q[]]': b'<?php use A; $a[] *= [&$q[]]; use B;',
    'compound-phase-*=/foo()/1': b'<?php use A; foo() *= 1; use B;',
    'compound-phase-*=/foo()/[&$q[]]': b'<?php use A; foo() *= [&$q[]]; use B;',
    'compound-phase-*=/$o?->p/1': b'<?php use A; $o?->p *= 1; use B;',
    'compound-phase-*=/$o?->p/[&$q[]]': b'<?php use A; $o?->p *= [&$q[]]; use B;',
    'compound-phase-deep-*=-false': b'<?php use A; echo [false && ($a *= [[[]=>1]])][0]; use B;',
    'compound-phase-deep-*=-true': b'<?php use A; echo [true && ($a *= [[[]=>1]])][0]; use B;',
    'compound-phase-array-value-*=': b'<?php $a=1;$b=[($a *= 1)];echo $b[0];',
    'compound-phase-array-key-*=': b'<?php $a=1;$b=[($a *= 1)=>2];echo $a;',
    'compound-phase-/=/$x/1': b'<?php use A; $x /= 1; use B;',
    'compound-phase-/=/$x/[&$q[]]': b'<?php use A; $x /= [&$q[]]; use B;',
    'compound-phase-/=/$a[]/1': b'<?php use A; $a[] /= 1; use B;',
    'compound-phase-/=/$a[]/[&$q[]]': b'<?php use A; $a[] /= [&$q[]]; use B;',
    'compound-phase-/=/foo()/1': b'<?php use A; foo() /= 1; use B;',
    'compound-phase-/=/foo()/[&$q[]]': b'<?php use A; foo() /= [&$q[]]; use B;',
    'compound-phase-/=/$o?->p/1': b'<?php use A; $o?->p /= 1; use B;',
    'compound-phase-/=/$o?->p/[&$q[]]': b'<?php use A; $o?->p /= [&$q[]]; use B;',
    'compound-phase-deep-/=-false': b'<?php use A; echo [false && ($a /= [[[]=>1]])][0]; use B;',
    'compound-phase-deep-/=-true': b'<?php use A; echo [true && ($a /= [[[]=>1]])][0]; use B;',
    'compound-phase-array-value-/=': b'<?php $a=1;$b=[($a /= 1)];echo $b[0];',
    'compound-phase-array-key-/=': b'<?php $a=1;$b=[($a /= 1)=>2];echo $a;',
    'compound-phase-%=/$x/1': b'<?php use A; $x %= 1; use B;',
    'compound-phase-%=/$x/[&$q[]]': b'<?php use A; $x %= [&$q[]]; use B;',
    'compound-phase-%=/$a[]/1': b'<?php use A; $a[] %= 1; use B;',
    'compound-phase-%=/$a[]/[&$q[]]': b'<?php use A; $a[] %= [&$q[]]; use B;',
    'compound-phase-%=/foo()/1': b'<?php use A; foo() %= 1; use B;',
    'compound-phase-%=/foo()/[&$q[]]': b'<?php use A; foo() %= [&$q[]]; use B;',
    'compound-phase-%=/$o?->p/1': b'<?php use A; $o?->p %= 1; use B;',
    'compound-phase-%=/$o?->p/[&$q[]]': b'<?php use A; $o?->p %= [&$q[]]; use B;',
    'compound-phase-deep-%=-false': b'<?php use A; echo [false && ($a %= [[[]=>1]])][0]; use B;',
    'compound-phase-deep-%=-true': b'<?php use A; echo [true && ($a %= [[[]=>1]])][0]; use B;',
    'compound-phase-array-value-%=': b'<?php $a=1;$b=[($a %= 1)];echo $b[0];',
    'compound-phase-array-key-%=': b'<?php $a=1;$b=[($a %= 1)=>2];echo $a;',
    'compound-phase-**=/$x/1': b'<?php use A; $x **= 1; use B;',
    'compound-phase-**=/$x/[&$q[]]': b'<?php use A; $x **= [&$q[]]; use B;',
    'compound-phase-**=/$a[]/1': b'<?php use A; $a[] **= 1; use B;',
    'compound-phase-**=/$a[]/[&$q[]]': b'<?php use A; $a[] **= [&$q[]]; use B;',
    'compound-phase-**=/foo()/1': b'<?php use A; foo() **= 1; use B;',
    'compound-phase-**=/foo()/[&$q[]]': b'<?php use A; foo() **= [&$q[]]; use B;',
    'compound-phase-**=/$o?->p/1': b'<?php use A; $o?->p **= 1; use B;',
    'compound-phase-**=/$o?->p/[&$q[]]': b'<?php use A; $o?->p **= [&$q[]]; use B;',
    'compound-phase-deep-**=-false': b'<?php use A; echo [false && ($a **= [[[]=>1]])][0]; use B;',
    'compound-phase-deep-**=-true': b'<?php use A; echo [true && ($a **= [[[]=>1]])][0]; use B;',
    'compound-phase-array-value-**=': b'<?php $a=1;$b=[($a **= 1)];echo $b[0];',
    'compound-phase-array-key-**=': b'<?php $a=1;$b=[($a **= 1)=>2];echo $a;',
    'compound-phase-<<=/$x/1': b'<?php use A; $x <<= 1; use B;',
    'compound-phase-<<=/$x/[&$q[]]': b'<?php use A; $x <<= [&$q[]]; use B;',
    'compound-phase-<<=/$a[]/1': b'<?php use A; $a[] <<= 1; use B;',
    'compound-phase-<<=/$a[]/[&$q[]]': b'<?php use A; $a[] <<= [&$q[]]; use B;',
    'compound-phase-<<=/foo()/1': b'<?php use A; foo() <<= 1; use B;',
    'compound-phase-<<=/foo()/[&$q[]]': b'<?php use A; foo() <<= [&$q[]]; use B;',
    'compound-phase-<<=/$o?->p/1': b'<?php use A; $o?->p <<= 1; use B;',
    'compound-phase-<<=/$o?->p/[&$q[]]': b'<?php use A; $o?->p <<= [&$q[]]; use B;',
    'compound-phase-deep-<<=-false': b'<?php use A; echo [false && ($a <<= [[[]=>1]])][0]; use B;',
    'compound-phase-deep-<<=-true': b'<?php use A; echo [true && ($a <<= [[[]=>1]])][0]; use B;',
    'compound-phase-array-value-<<=': b'<?php $a=1;$b=[($a <<= 1)];echo $b[0];',
    'compound-phase-array-key-<<=': b'<?php $a=1;$b=[($a <<= 1)=>2];echo $a;',
    'compound-phase->>=/$x/1': b'<?php use A; $x >>= 1; use B;',
    'compound-phase->>=/$x/[&$q[]]': b'<?php use A; $x >>= [&$q[]]; use B;',
    'compound-phase->>=/$a[]/1': b'<?php use A; $a[] >>= 1; use B;',
    'compound-phase->>=/$a[]/[&$q[]]': b'<?php use A; $a[] >>= [&$q[]]; use B;',
    'compound-phase->>=/foo()/1': b'<?php use A; foo() >>= 1; use B;',
    'compound-phase->>=/foo()/[&$q[]]': b'<?php use A; foo() >>= [&$q[]]; use B;',
    'compound-phase->>=/$o?->p/1': b'<?php use A; $o?->p >>= 1; use B;',
    'compound-phase->>=/$o?->p/[&$q[]]': b'<?php use A; $o?->p >>= [&$q[]]; use B;',
    'compound-phase-deep->>=-false': b'<?php use A; echo [false && ($a >>= [[[]=>1]])][0]; use B;',
    'compound-phase-deep->>=-true': b'<?php use A; echo [true && ($a >>= [[[]=>1]])][0]; use B;',
    'compound-phase-array-value->>=': b'<?php $a=1;$b=[($a >>= 1)];echo $b[0];',
    'compound-phase-array-key->>=': b'<?php $a=1;$b=[($a >>= 1)=>2];echo $a;',
    'compound-phase-&=/$x/1': b'<?php use A; $x &= 1; use B;',
    'compound-phase-&=/$x/[&$q[]]': b'<?php use A; $x &= [&$q[]]; use B;',
    'compound-phase-&=/$a[]/1': b'<?php use A; $a[] &= 1; use B;',
    'compound-phase-&=/$a[]/[&$q[]]': b'<?php use A; $a[] &= [&$q[]]; use B;',
    'compound-phase-&=/foo()/1': b'<?php use A; foo() &= 1; use B;',
    'compound-phase-&=/foo()/[&$q[]]': b'<?php use A; foo() &= [&$q[]]; use B;',
    'compound-phase-&=/$o?->p/1': b'<?php use A; $o?->p &= 1; use B;',
    'compound-phase-&=/$o?->p/[&$q[]]': b'<?php use A; $o?->p &= [&$q[]]; use B;',
    'compound-phase-deep-&=-false': b'<?php use A; echo [false && ($a &= [[[]=>1]])][0]; use B;',
    'compound-phase-deep-&=-true': b'<?php use A; echo [true && ($a &= [[[]=>1]])][0]; use B;',
    'compound-phase-array-value-&=': b'<?php $a=1;$b=[($a &= 1)];echo $b[0];',
    'compound-phase-array-key-&=': b'<?php $a=1;$b=[($a &= 1)=>2];echo $a;',
    'compound-phase-|=/$x/1': b'<?php use A; $x |= 1; use B;',
    'compound-phase-|=/$x/[&$q[]]': b'<?php use A; $x |= [&$q[]]; use B;',
    'compound-phase-|=/$a[]/1': b'<?php use A; $a[] |= 1; use B;',
    'compound-phase-|=/$a[]/[&$q[]]': b'<?php use A; $a[] |= [&$q[]]; use B;',
    'compound-phase-|=/foo()/1': b'<?php use A; foo() |= 1; use B;',
    'compound-phase-|=/foo()/[&$q[]]': b'<?php use A; foo() |= [&$q[]]; use B;',
    'compound-phase-|=/$o?->p/1': b'<?php use A; $o?->p |= 1; use B;',
    'compound-phase-|=/$o?->p/[&$q[]]': b'<?php use A; $o?->p |= [&$q[]]; use B;',
    'compound-phase-deep-|=-false': b'<?php use A; echo [false && ($a |= [[[]=>1]])][0]; use B;',
    'compound-phase-deep-|=-true': b'<?php use A; echo [true && ($a |= [[[]=>1]])][0]; use B;',
    'compound-phase-array-value-|=': b'<?php $a=1;$b=[($a |= 1)];echo $b[0];',
    'compound-phase-array-key-|=': b'<?php $a=1;$b=[($a |= 1)=>2];echo $a;',
    'compound-phase-^=/$x/1': b'<?php use A; $x ^= 1; use B;',
    'compound-phase-^=/$x/[&$q[]]': b'<?php use A; $x ^= [&$q[]]; use B;',
    'compound-phase-^=/$a[]/1': b'<?php use A; $a[] ^= 1; use B;',
    'compound-phase-^=/$a[]/[&$q[]]': b'<?php use A; $a[] ^= [&$q[]]; use B;',
    'compound-phase-^=/foo()/1': b'<?php use A; foo() ^= 1; use B;',
    'compound-phase-^=/foo()/[&$q[]]': b'<?php use A; foo() ^= [&$q[]]; use B;',
    'compound-phase-^=/$o?->p/1': b'<?php use A; $o?->p ^= 1; use B;',
    'compound-phase-^=/$o?->p/[&$q[]]': b'<?php use A; $o?->p ^= [&$q[]]; use B;',
    'compound-phase-deep-^=-false': b'<?php use A; echo [false && ($a ^= [[[]=>1]])][0]; use B;',
    'compound-phase-deep-^=-true': b'<?php use A; echo [true && ($a ^= [[[]=>1]])][0]; use B;',
    'compound-phase-array-value-^=': b'<?php $a=1;$b=[($a ^= 1)];echo $b[0];',
    'compound-phase-array-key-^=': b'<?php $a=1;$b=[($a ^= 1)=>2];echo $a;',
    'compound-phase-.=/$x/1': b'<?php use A; $x .= 1; use B;',
    'compound-phase-.=/$x/[&$q[]]': b'<?php use A; $x .= [&$q[]]; use B;',
    'compound-phase-.=/$a[]/1': b'<?php use A; $a[] .= 1; use B;',
    'compound-phase-.=/$a[]/[&$q[]]': b'<?php use A; $a[] .= [&$q[]]; use B;',
    'compound-phase-.=/foo()/1': b'<?php use A; foo() .= 1; use B;',
    'compound-phase-.=/foo()/[&$q[]]': b'<?php use A; foo() .= [&$q[]]; use B;',
    'compound-phase-.=/$o?->p/1': b'<?php use A; $o?->p .= 1; use B;',
    'compound-phase-.=/$o?->p/[&$q[]]': b'<?php use A; $o?->p .= [&$q[]]; use B;',
    'compound-phase-deep-.=-false': b'<?php use A; echo [false && ($a .= [[[]=>1]])][0]; use B;',
    'compound-phase-deep-.=-true': b'<?php use A; echo [true && ($a .= [[[]=>1]])][0]; use B;',
    'compound-phase-array-value-.=': b'<?php $a=1;$b=[($a .= 1)];echo $b[0];',
    'compound-phase-array-key-.=': b'<?php $a=1;$b=[($a .= 1)=>2];echo $a;',
    'compound-phase-temporary-write-rhs': b'<?php $a=[1];$b=[2];echo ($a[0] += (($a=&$b)[0]=3));echo $a[0],$b[0];',
    'compound-phase-emission-0': b'<?php $a=null;\necho ($a +=\n($missing+1));',
    'compound-phase-emission-2': b'<?php $a=null;\necho ($a -=\n($missing+1));',
    'compound-phase-emission-3': b'<?php $a=[1];\necho $a[\n0\n] -=\n"2x";',
    'compound-phase-emission-4': b'<?php $a=null;\necho ($a *=\n($missing+1));',
    'compound-phase-emission-5': b'<?php $a=[1];\necho $a[\n0\n] *=\n"2x";',
    'compound-phase-emission-6': b'<?php $a=null;\necho ($a /=\n($missing+1));',
    'compound-phase-emission-7': b'<?php $a=[1];\necho $a[\n0\n] /=\n"2x";',
    'compound-phase-emission-8': b'<?php $a=null;\necho ($a %=\n($missing+1));',
    'compound-phase-emission-9': b'<?php $a=[1];\necho $a[\n0\n] %=\n"2x";',
    'compound-phase-emission-10': b'<?php $a=null;\necho ($a **=\n($missing+1));',
    'compound-phase-emission-11': b'<?php $a=[1];\necho $a[\n0\n] **=\n"2x";',
    'compound-phase-emission-12': b'<?php $a=null;\necho ($a <<=\n($missing+1));',
    'compound-phase-emission-13': b'<?php $a=[1];\necho $a[\n0\n] <<=\n"2x";',
    'compound-phase-emission-14': b'<?php $a=null;\necho ($a >>=\n($missing+1));',
    'compound-phase-emission-15': b'<?php $a=[1];\necho $a[\n0\n] >>=\n"2x";',
    'compound-phase-emission-16': b'<?php $a=null;\necho ($a &=\n($missing+1));',
    'compound-phase-emission-17': b'<?php $a=[1];\necho $a[\n0\n] &=\n"2x";',
    'compound-phase-emission-18': b'<?php $a=null;\necho ($a |=\n($missing+1));',
    'compound-phase-emission-19': b'<?php $a=[1];\necho $a[\n0\n] |=\n"2x";',
    'compound-phase-emission-20': b'<?php $a=null;\necho ($a ^=\n($missing+1));',
    'compound-phase-emission-21': b'<?php $a=[1];\necho $a[\n0\n] ^=\n"2x";',
    'compound-phase-emission-22': b'<?php $a=null;\necho ($a .=\n($missing+1));',
    'compound-phase-emission-23': b'<?php $a=[1];\necho $a[\n0\n] .=\n[];',
})

PREFIX = '''
var U : pcunit
dec $outputs(pevent*) : nat*
def $outputs(eps) = eps
def $outputs((OUTPUT n*) :: pevent*) = n* ++ $outputs(pevent*)
def $outputs((WARNING n* z) :: pevent*) = $outputs(pevent*)
def $outputs((DIAGNOSTIC text n* z) :: pevent*) = $outputs(pevent*)
dec $messages(pevent*) : pevent*
def $messages(eps) = eps
def $messages((OUTPUT n*) :: pevent*) = $messages(pevent*)
def $messages((WARNING n* z) :: pevent*) = (WARNING n* z) :: $messages(pevent*)
def $messages((DIAGNOSTIC text n* z) :: pevent*) = (DIAGNOSTIC text n* z) :: $messages(pevent*)
'''

def byte_sequence(value):
    return '(['+','.join(map(str,value))+'])'

def main():
    subprocess.run([str(ROOT/'scripts/opam-exec.sh'),'dune','build','--root',str(ROOT/'tests/semantics'),'numeric_runner.exe'],cwd=ROOT,check=True,timeout=120)
    runner=ROOT/'tests/semantics/_build/default/numeric_runner.exe'
    specs=[ROOT/p for p in json.loads((ROOT/'spec/semantics/modules.json').read_text())]
    before=types.syntax_validation.implementation_fingerprint()
    frontend=types.Worker([str(types.PHP),'-n',*types.FLAGS,'-d','extension='+str(ROOT/'.tools/php-file.so'),str(ROOT/'frontend/worker.php')])
    adapter=types.Worker([str(ROOT/'_build/default/adapter/main.exe'),str(ROOT)])
    records=[]; assertions=[]
    try:
        with tempfile.TemporaryDirectory(dir=ROOT/'.tools') as tmp:
            source_path=Path(tmp)/'compound.php'
            for name,source in NORMAL_CASES.items():
                source_path.write_bytes(source)
                native=subprocess.run([str(types.PHP),'-n',*types.FLAGS,str(source_path)],capture_output=True,env=types.ENV,timeout=10)
                assert native.returncode in (0,255),(name,native.stdout,native.stderr)
                completion='NORMAL'
                if native.returncode==255:
                    match=re.search(rb'Uncaught (Error|TypeError|DivisionByZeroError|ArithmeticError): (.*?) in '+re.escape(str(source_path).encode())+rb':(\d+)',native.stderr);assert match,native.stderr
                    completion='THROWN '+json.dumps(match[1].decode())+' '+byte_sequence(match[2])+' '+match[3].decode()
                parsed=frontend.request({'op':'parse','source':base64.b64encode(source).decode()});assert parsed['accepted'],parsed
                checked=adapter.request({'op':'check','ast':parsed['ast'],'fixture':True});assert checked['ok'],checked
                events=[]
                for severity,message,line in re.findall(rb'(Warning|Deprecated): (.*) in .* on line (\d+)',native.stderr):
                    if message.startswith(b'Undefined variable $'):
                        events.append('WARNING '+byte_sequence(message.removeprefix(b'Undefined variable $'))+' '+line.decode())
                    else:
                        events.append('DIAGNOSTIC "'+severity.decode()+'" '+byte_sequence(message)+' '+line.decode())
                checks=['U = $pcsource(0, '+checked['fixture']+')',
                        'S_initial = $php_run('+checked['fixture']+', 0, '+json.dumps(base64.b64encode(str(source_path).encode()).decode())+')',
                        'S_initial.COMPLETION = BUDGET','S = S_initial[.COMPLETION = NORMAL]',
                        'S.SOURCES = [U]','S_out = $drive(S, 10000)',
                        '$outputs(S_out.EVENTS) = '+byte_sequence(native.stdout),
                        '$messages(S_out.EVENTS) = ['+', '.join(events)+']',
                        'S_out.COMPLETION = '+completion,'S_out.ORIGIN = eps','S_out.HELD = eps',
                        'S_out.POOLS = S.POOLS','S_out.CODE = S.CODE',
                        '$heap_valid($heap_graph(S_out))']
                if name.startswith('loop-'):
                    for budget in (1,2,5,9,17,31,63):
                        checks += [f'S_budget{budget} = $drive(S, {budget})',
                                   f'$drive(S_budget{budget}[.COMPLETION = NORMAL], 10000) = S_out',
                                   f'S_budget{budget}.POOLS = S.POOLS',
                                   f'S_budget{budget}.CODE = S.CODE',
                                   f'$heap_valid($heap_graph(S_budget{budget}))']
                assertions.append(checks)
                records.append({'id':name,'source_base64':base64.b64encode(source).decode(),'ast':checked['ast'],
                                'oracle_exit_status':native.returncode,'oracle_stdout':base64.b64encode(native.stdout).decode(),
                                'oracle_stderr':base64.b64encode(native.stderr).decode()})
            for index,checks in enumerate(assertions):
                fixture=Path(tmp)/'compound.watsup'
                fixture.write_text(PREFIX+'dec $main() : bool\ndef $main() = true\n'+''.join('  -- if '+check+'\n' for check in checks))
                run=subprocess.run([str(runner),*map(str,specs),str(fixture)],capture_output=True,text=True,cwd=ROOT,timeout=120)
                if run.returncode or run.stdout.strip()!='true':
                    (ROOT/'.tools/compound-source-failure.watsup').write_text(fixture.read_text())
                    raise AssertionError((index,run.stdout,run.stderr))
    finally:
        frontend.close();adapter.close()
    assert before==types.syntax_validation.implementation_fingerprint(),'inputs changed during compound gate'
    report={'result':'pass','classification':'checked-source twelve compound assignments, captured locations and numeric/byte value operations; current scalar and array forms',
            'source_cases':len(records),'state_cases':len(assertions),'assertions':sum(map(len,assertions)),
            'records':records,'fingerprint':before}
    (ROOT/'coverage/semantics/compound.json').write_text(json.dumps(report,indent=2)+'\n')
    print({key:report[key] for key in ('result','source_cases','state_cases','assertions')})

if __name__=='__main__':
    main()
