"""Reached false/key sequencing, delayed reference demand and typed COW state."""
from error_handler_protocol import PREFIX as BASE_PREFIX

PREFIX = BASE_PREFIX + r'''
dec $author_tail_stage(pstate) : bool
def $author_tail_stage(S) = true
  -- if S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail*
  -- if pkeywrite.READ.PHASE = KEY_FLOAT PRECISIONLOSS eps
def $author_tail_stage(S) = false -- otherwise
dec $author_seek_tail(pstate, nat) : pstate
def $author_seek_tail(S, n) = S -- if $author_tail_stage(S)
def $author_seek_tail(S, n) = $author_seek_tail($drive_steps(S[.COMPLETION = NORMAL], 1), $nabs($(n - 1)))
  -- if ~$author_tail_stage(S)
  -- if S.COMPLETION = NORMAL \/ S.COMPLETION = BUDGET
  -- if $(n > 0)
def $author_seek_tail(S, n) = S -- if S.COMPLETION =/= NORMAL /\ S.COMPLETION =/= BUDGET
dec $author_cow_stage(pstate) : bool
def $author_cow_stage(S) = true -- if S.TODO = (KEY_WRITE_DIM (KNOWN (PINT 2)) z false) :: ptask_tail*
def $author_cow_stage(S) = false -- otherwise
dec $author_seek_cow(pstate, nat) : pstate
def $author_seek_cow(S, n) = S -- if $author_cow_stage(S)
def $author_seek_cow(S, n) = $author_seek_cow($drive_steps(S[.COMPLETION = NORMAL], 1), $nabs($(n - 1)))
  -- if ~$author_cow_stage(S)
  -- if S.COMPLETION = NORMAL \/ S.COMPLETION = BUDGET
  -- if $(n > 0)
def $author_seek_cow(S, n) = S -- if S.COMPLETION =/= NORMAL /\ S.COMPLETION =/= BUDGET
'''

GUARDS = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
          '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))']
FINISH = ['S_done.COMPLETION = NORMAL', 'S_done.TODO = eps',
          'S_done.CURRENT = eps', 'S_done.FRAMES = eps', 'S_done.HELD = eps',
          'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
          '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))']

CASES = [
    ('false-fetch-releases-before-ordered-nan-key-notices',
     'false-fetch-before-ordered-nan-key-notices',
     'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail* -- if pkeywrite.READ.PHASE = KEY_FLOAT RANGEWARNING ([PRECISIONLOSS])', [
        'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail*',
        'pkeyread = pkeywrite.READ',
        'pkeyread.PHASE = KEY_FLOAT RANGEWARNING ([PRECISIONLOSS])',
        'pkeyread.LINE = 4', 'pkeyread.INPUT = VARIABLE $ptascii("key276") 4',
        'pkeyread.VALUE = PFLOAT n_bits',
        '$float_long(n_bits, true) = (0, [RANGEWARNING, PRECISIONLOSS])',
        'pkeyread.KEY = KINT 0', 'pkeyread.BASE = PARRAY n_array',
        'pkeyread.MODE = KEY_R', '~pkeyread.GLOBAL', '~pkeywrite.RW',
        'pkeyread.OWNERS = BASE_VALUE (KNOWN PNULL)',
        '$lookup(S.ENV, $ptascii("a276")) = (n_a)',
        'pkeywrite.PLACE = ROOT n_a', 'S.STORE[n_a] = DEFINED (PARRAY n_array)',
        '~(n_a <- S.REFCELLS)', 'S.ARRAYS[n_array].ITEMS = eps',
        '$task_nodes(KEY_WRITE_RESULT pkeywrite) = [HARRAY n_array]',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_array) = 2',
        '~((HARRAY n_array) <- $pools_nodes(S.POOLS))',
        '$lookup(S.ENV, $ptascii("key276")) = (n_key)',
        'S.STORE[n_key] = DEFINED (PFLOAT 4620130267728707584)',
        '$key_write_valid(S, pkeywrite)', '$outputs(S.EVENTS) = $ptascii("F;W;")',
        '~$key_write_valid(S, pkeywrite[.READ.LINE = 5])',
        '~$key_write_valid(S, pkeywrite[.READ.KEY = KINT 7])',
        '~$key_write_valid(S, pkeywrite[.READ.PHASE = KEY_FLOAT RANGEWARNING eps])',
        '~$key_write_valid(S, pkeywrite[.READ.PHASE = KEY_FLOAT PRECISIONLOSS ([RANGEWARNING])])',
        '~$key_write_valid(S, pkeywrite[.READ.OWNERS = BASE_VALUE (KNOWN (PARRAY n_array))])',
        '~$key_write_valid(S, pkeywrite[.RW = true])', *GUARDS,
        'PhpStep: S ~> S_dispatched',
        'S_dispatched.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = KEY_WRITE_RESULT p_tail',
        'p_tail = pkeywrite[.READ.PHASE = KEY_FLOAT PRECISIONLOSS eps]',
        'perrorcall.LEVEL = 8192', 'perrorcall.LINE = 4',
        '$task_nodes(perrorcall.RESUME) = [HARRAY n_array]',
        '$heap_owners($heap_prune($heap_graph(S_dispatched)), HARRAY n_array) = 2',
        'S_tail = $author_seek_tail(S_dispatched, 2000)',
        'S_tail.TODO = (KEY_WRITE_RESULT p_tail) :: ptask_tail*',
        '$outputs(S_tail.EVENTS) = $ptascii("F;W;D;")',
        '$key_write_valid(S_tail, p_tail)',
        'PhpStep: S_tail ~> S_selected',
        'S_selected.TODO = ptask_tail*',
        'S_selected.LOCATION = ELEMENT n_array (KINT 0)',
        '$entry_lookup(S_selected.ARRAYS[n_array].ITEMS, KINT 0) = (DIRECT PNULL)',
        '$heap_owners($heap_prune($heap_graph(S_selected)), HARRAY n_array) = 1',
        'S_done = $drive(S_selected, 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("r276")) = (n_ref)',
        '$entry_lookup(S_done.ARRAYS[n_array].ITEMS, KINT 0) = (ALIAS n_ref)',
        'S_done.STORE[n_ref] = DEFINED (PINT 19)',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_ref) = 2',
    ]),
    ('array-reference-target-converts-before-delayed-source-cv',
     'reference-target-key-before-delayed-source-cv',
     'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail* -- if pkeywrite.READ.PHASE = KEY_FLOAT PRECISIONLOSS eps', [
        'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail*',
        'pkeyread = pkeywrite.READ',
        'pkeyread.PHASE = KEY_FLOAT PRECISIONLOSS eps',
        'pkeyread.LINE = 4', 'pkeyread.INPUT = VARIABLE $ptascii("key276") 4',
        'pkeyread.VALUE = PFLOAT 4609434218613702656',
        'pkeyread.KEY = KINT 1', 'pkeyread.BASE = PARRAY n_array',
        '~pkeyread.GLOBAL', '~pkeywrite.RW', 'pkeyread.MODE = KEY_R',
        '$container_writer(S.TODO) = (pkeywriter)',
        'pkeywriter.TASK = REF_ARRAY_CV pkeywriter.BASE $ptascii("source276") 4',
        'pkeywriter.RHS = KNOWN PNULL', 'pkeywriter.TEMP = eps',
        '$task_nodes(KEY_WRITE_FINISH pkeywriter) = eps',
        '$lookup(S.ENV, $ptascii("a276")) = (n_a)',
        'pkeywrite.PLACE = ROOT n_a', 'S.STORE[n_a] = DEFINED (PARRAY n_array)',
        'S.ARRAYS[n_array].ITEMS = eps',
        '$lookup(S.ENV, $ptascii("source276")) = (n_new)',
        'S.STORE[n_new] = DEFINED (PINT 17)', '~(n_new <- S.REFCELLS)',
        '$lookup(S.ENV, $ptascii("alias276")) = (n_old)', 'n_new =/= n_old',
        'S.STORE[n_old] = DEFINED (PINT 9)', 'n_old <- S.REFCELLS',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_old) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_new) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_array) = 2',
        '$key_write_valid(S, pkeywrite)', '$outputs(S.EVENTS) = $ptascii("D;")',
        '~$key_write_valid(S, pkeywrite[.READ.LINE = 5])',
        '~$key_write_valid(S, pkeywrite[.READ.KEY = KINT 7])',
        '~$key_write_valid(S, pkeywrite[.RW = true])',
        '$key_write_writer(S, pkeywriter.SITE, REF_ARRAY_CV pkeywriter.BASE $ptascii("alias276") 4, pkeywriter.BASE, KNOWN PNULL) = eps',
        '$key_write_writer(S, pkeywriter.SITE, REF_ARRAY pkeywriter.BASE n_old 4, pkeywriter.BASE, REFERENCE n_old) = eps',
        *GUARDS, 'PhpStep: S ~> S_selected',
        'S_selected.TODO = ptask_tail*',
        'S_selected.LOCATION = ELEMENT n_array (KINT 1)',
        '$entry_lookup(S_selected.ARRAYS[n_array].ITEMS, KINT 1) = (DIRECT PNULL)',
        '$heap_owners($heap_prune($heap_graph(S_selected)), HARRAY n_array) = 1',
        'S_selected.STORE[n_new] = DEFINED (PINT 17)', '~(n_new <- S_selected.REFCELLS)',
        'S_done = $drive(S_selected, 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("source276")) = (n_new)',
        'n_new <- S_done.REFCELLS', 'S_done.STORE[n_new] = DEFINED (PINT 19)',
        '$entry_lookup(S_done.ARRAYS[n_array].ITEMS, KINT 1) = (ALIAS n_new)',
        '$entry_lookup(S_done.ARRAYS[n_array].ITEMS, KINT 7) = eps',
        'S_done.STORE[n_old] = DEFINED (PINT 9)',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_new) = 2',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_old) = 1',
    ]),
    ('typed-compound-array-allowance-transports-through-cow-and-clears',
     'typed-bool-compound-array-cow-survives-until-whole-cell-write',
     'S.TODO = (CONTAINER_WRITE_RESULT pcontainerwrite) :: ptask_tail* -- if pcontainerwrite.PHASE = CONTAINER_FALSE n', [
        'S.TODO = (CONTAINER_WRITE_RESULT pcontainerwrite) :: ptask_tail*',
        'pcontainerwrite.PHASE = CONTAINER_FALSE n_array',
        'pcontainerwrite.KIND = CONTAINER_COMPOUND', 'pcontainerwrite.RW',
        'pcontainerwrite.LINE = 4', 'pcontainerwrite.INPUT = KNOWN (PINT 1)',
        'pcontainerwrite.BINDING = eps', 'pcontainerwrite.PLACE = ROOT n_cell',
        '$lookup(S.ENV, $ptascii("a276")) = (n_cell)', 'n_cell <- S.REFCELLS',
        'S.STORE[n_cell] = DEFINED (PARRAY n_array)', 'S.ARRAYS[n_array].ITEMS = eps',
        'S.CONTAINERINITS = [pcontainerinit]',
        'pcontainerinit.CELL = n_cell', 'pcontainerinit.ARRAY = n_array',
        'pcontainerinit.SITE = pcontainerwrite.WRITER.SITE', 'pcontainerinit.LINE = 4',
        '$container_inits_valid(S)', '$container_init_value(S, n_cell, PARRAY n_array)',
        '$container_valid(S, pcontainerwrite)', '$container_live(S, pcontainerwrite)',
        '$propref_at(S.PROPREFS, n_cell) = (ppropref)',
        '$propref_nonarray_source(S, ppropref.SOURCES) = (pproptypesource)',
        '$propref_descriptor(S, pproptypesource) = (ppropertydesc)',
        '$propref_class(S, ppropertydesc.TYPE, PARRAY n_array, $property_strict(S)) = PROP_IMPOSSIBLE',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_cell) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_array) = 2',
        '$task_nodes(CONTAINER_WRITE_RESULT pcontainerwrite) = [HARRAY n_array]',
        '$task_nodes(KEY_WRITE_FINISH pcontainerwrite.WRITER) = eps',
        '$outputs(S.EVENTS) = $ptascii("D;")',
        '~$container_init_row_valid(S, pcontainerinit[.SITE = pcontainerwrite.SITE])',
        '~$container_init_row_valid(S, pcontainerinit[.LINE = 5])',
        '~$container_init_row_valid(S, pcontainerinit[.CELL = |S.STORE|])',
        '~$container_init_row_valid(S, pcontainerinit[.ARRAY = |S.ARRAYS|])',
        '~$container_inits_valid(S[.CONTAINERINITS = [pcontainerinit, pcontainerinit]])',
        '~$container_inits_valid(S[.STORE = $set_cell(S.STORE, n_cell, DEFINED (PBOOL false))])',
        '~$property_state_valid(S[.CONTAINERINITS = eps])',
        '~$container_init_value(S, n_cell, PNULL)',
        '~$container_valid(S, pcontainerwrite[.KIND = CONTAINER_FETCH])', *GUARDS,
        'PhpStep: S ~> S_missing',
        'S_missing.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = KEY_WRITE_RESULT pkeywrite',
        'pkeywrite.READ.PHASE = KEY_MISSING', 'pkeywrite.RW',
        '$heap_owners($heap_prune($heap_graph(S_missing)), HARRAY n_array) = 2',
        'S_cow = $author_seek_cow(S_missing, 2500)',
        'S_cow.TODO = (KEY_WRITE_DIM (KNOWN (PINT 2)) 4 false) :: ptask_cow_tail*',
        'S_cow.STORE[n_cell] = DEFINED (PARRAY n_array)',
        '$entry_lookup(S_cow.ARRAYS[n_array].ITEMS, KINT 1) = (DIRECT (PINT 3))',
        '$lookup(S_cow.ENV, $ptascii("copy276")) = (n_copy)',
        'S_cow.STORE[n_copy] = DEFINED (PARRAY n_array)',
        'S_cow.CONTAINERINITS = [pcontainerinit]',
        '$outputs(S_cow.EVENTS) = $ptascii("D;M;")',
        '$heap_owners($heap_prune($heap_graph(S_cow)), HARRAY n_array) = 2',
        'PhpStep: S_cow ~> S_separated',
        'S_separated.TODO = ptask_cow_tail*',
        'S_separated.STORE[n_cell] = DEFINED (PARRAY n_new)', 'n_new =/= n_array',
        'S_separated.LOCATION = ELEMENT n_new (KINT 2)',
        'S_separated.STORE[n_copy] = DEFINED (PARRAY n_array)',
        'S_separated.CONTAINERINITS = [pcontainerinit[.ARRAY = n_new]]',
        '$container_init_value(S_separated, n_cell, PARRAY n_new)',
        '$property_state_valid(S_separated)',
        '$entry_lookup(S_separated.ARRAYS[n_array].ITEMS, KINT 2) = eps',
        '$entry_lookup(S_separated.ARRAYS[n_new].ITEMS, KINT 2) = (DIRECT PNULL)',
        '$heap_owners($heap_prune($heap_graph(S_separated)), HARRAY n_new) = 1',
        '$heap_owners($heap_prune($heap_graph(S_separated)), HARRAY n_array) = 1',
        'S_done = $drive(S_separated, 3000)', *FINISH,
        'S_done.STORE[n_cell] = DEFINED (PBOOL false)', 'S_done.CONTAINERINITS = eps',
        'S_done.STORE[n_copy] = DEFINED (PARRAY n_array)',
        '$entry_lookup(S_done.ARRAYS[n_array].ITEMS, KINT 1) = (DIRECT (PINT 3))',
        '$entry_lookup(S_done.ARRAYS[n_array].ITEMS, KINT 2) = eps',
        '$heap_owners($heap_prune($heap_graph(S_done)), HARRAY n_new) = 0',
        '$heap_owners($heap_prune($heap_graph(S_done)), HARRAY n_array) = 1',
    ]),
]
