"""Reached null-base capture, dereferenced row and real ignored-key ownership."""
from error_handler_protocol import PREFIX

GUARDS = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
          '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))']
FINISH = ['S_done.COMPLETION = NORMAL', 'S_done.TODO = eps',
          'S_done.CURRENT = eps', 'S_done.FRAMES = eps', 'S_done.HELD = eps',
          'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
          '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))']

CASES = [
    ('missing-base-return-latches-null-before-offset-warning',
     'missing-base-definition-does-not-refetch-array',
     'S.TODO = (CONTAINER_READ_RESULT pcontainerread) :: ptask_tail* -- if pcontainerread.PHASE = READ_BASE_CV n_name*', [
        'S.TODO = (CONTAINER_READ_RESULT pcontainerread) :: ptask_tail*',
        'pcontainerread.PHASE = READ_BASE_CV $ptascii("base282")',
        'pkeyread = pcontainerread.READ', 'pkeyread.LINE = 4',
        'pkeyread.MODE = KEY_R', '~pkeyread.GLOBAL',
        'pkeyread.INPUT = KNOWN (PINT 0)', 'pkeyread.VALUE = PNULL',
        'pkeyread.BASE = PNULL', 'pkeyread.PHASE = KEY_NULL',
        'pkeyread.KEY = KSTRING eps', 'pkeyread.NAME = eps',
        'pkeyread.OWNERS = BASE_VALUE (VARIABLE $ptascii("base282") 4)',
        'pcontainerread.SELECTED = KNOWN PNULL',
        '$lookup(S.ENV, $ptascii("base282")) = (n_base)',
        'S.STORE[n_base] = DEFINED (PARRAY n_array)',
        '$entry_lookup(S.ARRAYS[n_array].ITEMS, KINT 0) = (DIRECT (PINT 17))',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_base) = 1',
        '$task_nodes(CONTAINER_READ_RESULT pcontainerread) = eps',
        '$outputs(S.EVENTS) = $ptascii("B;")', '$rcontainer_valid(S, pcontainerread)',
        '~$rcontainer_valid(S, pcontainerread[.READ.LINE = 5])',
        '~$rcontainer_valid(S, pcontainerread[.READ.SITE = PORIGIN 999 eps])',
        '~$rcontainer_valid(S, pcontainerread[.READ.INPUT = KNOWN (PINT 1)])',
        '~$rcontainer_valid(S, pcontainerread[.READ.KEY = KINT 0])',
        '~$rcontainer_valid(S, pcontainerread[.READ.MODE = KEY_IS])',
        '~$rcontainer_valid(S, pcontainerread[.READ.GLOBAL = true])',
        '~$rcontainer_valid(S, pcontainerread[.SELECTED = VARIABLE $ptascii("base282") 4])',
        '~$rcontainer_valid(S, pcontainerread[.READ.OWNERS = BASE_VALUE (KNOWN PNULL)])',
        '~$rcontainer_valid(S, pcontainerread[.PHASE = READ_BASE_CV $ptascii("other282")])',
        '~$rcontainer_valid(S[.TODO = eps], pcontainerread)', *GUARDS,
        'PhpStep: S ~> S_offset',
        'S_offset.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = CONTAINER_READ_RESULT pcontainerread_offset',
        'pcontainerread_offset = pcontainerread[.READ.VALUE = PINT 0][.PHASE = READ_OFFSET PNULL]',
        'perrorcall.LEVEL = 2', 'perrorcall.LINE = 4',
        'perrorcall.SITE = pkeyread.SITE',
        'perrorcall.MESSAGE = $ptascii("Trying to access array offset on null")',
        'perrorcall.EVENT = DIAGNOSTIC "Warning" perrorcall.MESSAGE 4',
        '$error_call_valid(S_offset, perrorcall)',
        '~$error_call_valid(S_offset, perrorcall[.MESSAGE = $ptascii("Trying to access array offset on array")])',
        '~$rcontainer_valid(S_offset, pcontainerread_offset[.PHASE = READ_OFFSET (PARRAY n_array)])',
        '$task_nodes(perrorcall.RESUME) = eps',
        'S_offset.STORE[n_base] = DEFINED (PARRAY n_array)',
        '$heap_owners($heap_prune($heap_graph(S_offset)), HCELL n_base) = 1',
        'S_done = $drive(S_offset, 2500)', *FINISH,
        'S_done.STORE[n_base] = DEFINED (PARRAY n_array)',
        '$lookup(S_done.ENV, $ptascii("r282")) = (n_result)',
        'S_done.STORE[n_result] = DEFINED PNULL',
    ]),
    ('nested-row-copy-stays-int-after-real-cell-mutation',
     'nested-scalar-row-is-dereferenced-before-key-warning',
     'S.TODO = (CONTAINER_READ_RESULT pcontainerread) :: ptask_tail* -- if pcontainerread.PHASE = READ_KEY_CV n_name*', [
        'S.TODO = (CONTAINER_READ_RESULT pcontainerread) :: ptask_tail*',
        'pcontainerread.PHASE = READ_KEY_CV $ptascii("key282")',
        'pkeyread = pcontainerread.READ', 'pkeyread.LINE = 4',
        'pkeyread.MODE = KEY_R', '~pkeyread.GLOBAL',
        'pkeyread.INPUT = VARIABLE $ptascii("key282") 4',
        'pkeyread.VALUE = PNULL', 'pkeyread.BASE = PINT 9',
        'pkeyread.PHASE = KEY_CV', 'pkeyread.NAME = $ptascii("key282")',
        'pkeyread.OWNERS = BASE_VALUE (KNOWN (PINT 9))',
        'pcontainerread.SELECTED = KNOWN (PINT 9)',
        '$lookup(S.ENV, $ptascii("cell282")) = (n_cell)',
        'S.STORE[n_cell] = DEFINED (PBOOL false)', 'n_cell <- S.REFCELLS',
        '$lookup(S.ENV, $ptascii("held282")) = (n_held)',
        'S.STORE[n_held] = DEFINED (PARRAY n_old)',
        '$entry_lookup(S.ARRAYS[n_old].ITEMS, KINT 0) = (ALIAS n_cell)',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_old) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_cell) = 2',
        '$lookup(S.ENV, $ptascii("a282")) = (n_a)',
        'S.STORE[n_a] = DEFINED (PARRAY n_new)', 'n_new =/= n_old',
        '$lookup(S.ENV, $ptascii("key282")) = (n_key)',
        'S.STORE[n_key] = DEFINED (PINT 0)',
        '$task_nodes(CONTAINER_READ_RESULT pcontainerread) = eps',
        '$outputs(S.EVENTS) = $ptascii("K;")', '$rcontainer_valid(S, pcontainerread)',
        '~$rcontainer_valid(S, pcontainerread[.READ.LINE = 5])',
        '~$rcontainer_valid(S, pcontainerread[.READ.NAME = $ptascii("cell282")])',
        '~$rcontainer_valid(S, pcontainerread[.READ.INPUT = VARIABLE $ptascii("cell282") 4])',
        '~$rcontainer_valid(S, pcontainerread[.SELECTED = VARIABLE $ptascii("cell282") 4])',
        '~$rcontainer_valid(S, pcontainerread[.READ.OWNERS = BASE_VALUE (KNOWN (PBOOL false))])',
        '~$rcontainer_valid(S, pcontainerread[.READ.OWNERS = BASE_VALUE (VARIABLE $ptascii("cell282") 4)])',
        '~$rcontainer_valid(S, pcontainerread[.READ.GLOBAL = true])', *GUARDS,
        'PhpStep: S ~> S_offset',
        'S_offset.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = CONTAINER_READ_RESULT pcontainerread_offset',
        'pcontainerread_offset = pcontainerread[.READ.PHASE = KEY_NULL][.READ.NAME = eps][.PHASE = READ_OFFSET (PINT 9)]',
        'perrorcall.MESSAGE = $ptascii("Trying to access array offset on int")',
        'perrorcall.LINE = 4', '$error_call_valid(S_offset, perrorcall)',
        '~$rcontainer_valid(S_offset, pcontainerread_offset[.PHASE = READ_OFFSET (PBOOL false)])',
        '$task_nodes(perrorcall.RESUME) = eps',
        '$heap_owners($heap_prune($heap_graph(S_offset)), HCELL n_cell) = 2',
        'S_done = $drive(S_offset, 2500)', *FINISH,
        'S_done.STORE[n_cell] = DEFINED (PBOOL false)',
        'S_done.STORE[n_held] = DEFINED (PARRAY n_old)',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_cell) = 2',
        '$heap_owners($heap_prune($heap_graph(S_done)), HARRAY n_old) = 1',
        '$lookup(S_done.ENV, $ptascii("r282")) = (n_result)',
        'S_done.STORE[n_result] = DEFINED PNULL',
    ]),
    ('ignored-key-temporary-releases-real-cell-at-budget-boundary',
     'scalar-offset-retains-real-key-temporary-through-handler',
     'S.TODO = (CONTAINER_READ_RESULT pcontainerread) :: ptask_tail* -- if pcontainerread.PHASE = READ_OFFSET pvalue', [
        'S.TODO = (CONTAINER_READ_RESULT pcontainerread) :: ptask_tail*',
        'pcontainerread.PHASE = READ_OFFSET (PINT 13)',
        'pkeyread = pcontainerread.READ', 'pkeyread.LINE = 4',
        'pkeyread.MODE = KEY_R', '~pkeyread.GLOBAL',
        'pkeyread.INPUT = KNOWN (PARRAY n_key)', 'pkeyread.VALUE = PARRAY n_key',
        'pkeyread.BASE = PINT 13', 'pkeyread.PHASE = KEY_NULL',
        'pkeyread.KEY = KSTRING eps', 'pkeyread.NAME = eps',
        'pkeyread.OWNERS = BASE_VALUE (VARIABLE $ptascii("scalar282") 4)',
        'pcontainerread.SELECTED = VARIABLE $ptascii("scalar282") 4',
        '$lookup(S.ENV, $ptascii("scalar282")) = (n_base)',
        'S.STORE[n_base] = DEFINED (PINT 13)',
        '$lookup(S.ENV, $ptascii("cell282")) = eps',
        '$lookup(S.ENV, $ptascii("held282")) = eps',
        'S.ARRAYS[n_key].ITEMS = [ENTRY (KINT 0) (ALIAS n_cell)]',
        'S.STORE[n_cell] = DEFINED (PINT 9)', 'n_cell <- S.REFCELLS',
        '~((HARRAY n_key) <- $pools_nodes(S.POOLS))',
        '$task_nodes(CONTAINER_READ_RESULT pcontainerread) = [HARRAY n_key]',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_key) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_cell) = 1',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_base) = 1',
        '$outputs(S.EVENTS) = $ptascii("O:1;")', '$rcontainer_valid(S, pcontainerread)',
        '~$rcontainer_valid(S, pcontainerread[.READ.LINE = 5])',
        '~$rcontainer_valid(S, pcontainerread[.READ.MODE = KEY_IS])',
        '~$rcontainer_valid(S, pcontainerread[.READ.PHASE = KEY_CV])',
        '~$rcontainer_valid(S, pcontainerread[.PHASE = READ_KEY_CV $ptascii("cell282")])',
        '~$rcontainer_valid(S, pcontainerread[.READ.NAME = $ptascii("cell282")])',
        '~$rcontainer_valid(S, pcontainerread[.READ.INPUT = VARIABLE $ptascii("cell282") 4])',
        '~$rcontainer_valid(S, pcontainerread[.READ.BASE = PARRAY n_key])',
        '~$rcontainer_valid(S, pcontainerread[.READ.OWNERS = BASE_VALUE (KNOWN (PINT 13))])',
        '~$rcontainer_valid(S, pcontainerread[.SELECTED = KNOWN (PINT 13)])',
        '~$rcontainer_valid(S, pcontainerread[.READ.KEY = KINT 0])', *GUARDS,
        'S_pause = $drive_steps(S, 1)', 'S_pause.COMPLETION = BUDGET',
        'S_pause.TODO = ptask_tail*', 'S_pause.RESULT = KNOWN PNULL',
        'S_pause.STORE[n_base] = DEFINED (PINT 13)',
        '$heap_owners($heap_prune($heap_graph(S_pause)), HARRAY n_key) = 0',
        '$heap_owners($heap_prune($heap_graph(S_pause)), HCELL n_cell) = 0',
        '~((HARRAY n_key) <- S_pause.ALLOCATIONS)',
        '~((HCELL n_cell) <- S_pause.ALLOCATIONS)',
        '$heap_valid($heap_graph(S_pause))',
        'S_done = $drive(S_pause[.COMPLETION = NORMAL], 2500)', *FINISH,
        'S_done.STORE[n_base] = DEFINED (PINT 13)',
        '$lookup(S_done.ENV, $ptascii("r282")) = (n_result)',
        'S_done.STORE[n_result] = DEFINED PNULL',
    ]),
]
