#!/usr/bin/env python3
"""Independent source-reached request destructor and pending-owner checks."""
import argparse
import json
from pathlib import Path

import shutdown_state_review as runner

SOURCES = {row['id']: row['source'] for row in json.loads(
    Path(__file__).with_name('destructor_review_cases.json').read_text())}
VALID = ['$destruction_state_valid(S)', '$call_current_valid(S)',
         '$call_frames_valid(S, S.FRAMES)', '$call_descriptors_valid(S)',
         '$class_state_valid(S)', '$heap_valid($heap_graph(S))']
DONE = ['S_done.TODO = eps', 'S_done.FRAMES = eps', 'S_done.CURRENT = eps',
        'S_done.HELD = eps', 'S_done.CONSTCONTEXT = eps',
        'S_done.DESTRUCTION.PHASE = DESTRUCTION_DONE',
        'S_done.DESTRUCTION.CALLS = eps', 'S_done.DESTRUCTION.RELEASES = eps',
        'S_done.DESTRUCTION.FRAMES = eps', '$call_descriptors_valid(S_done)',
        '$heap_valid($heap_graph(S_done))']
REPLAY = ['S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
          'S_paused.DESTRUCTION = S.DESTRUCTION',
          'S_paused.ALLOCATIONS = S.ALLOCATIONS',
          'S_done = $drive(S, 2000)', 'S_done.COMPLETION = NORMAL', *DONE,
          '$drive(S_paused[.COMPLETION = NORMAL], 2000) = S_done']

CASES = {
    'global-selected-receiver-before-entry': {
        'source': SOURCES['normal-direct-global-reverse'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail* -- if pdestructorcall.OBJECT = 1',
        'checks': [
            'S.DESTRUCTION.PHASE = DESTRUCTION_GLOBALS',
            'S.DESTRUCTION.CALLS = [pdestructorcall]',
            'S.DESTRUCTION.CALLED = [1]',
            'pdestructorcall.CALLER = eps', 'pdestructorcall.ORIGIN = eps',
            'pdestructorcall.CONSTCONTEXT = eps', '~pdestructorcall.STORE',
            'S.CURRENT = eps', 'S.FRAMES = eps', 'S.CONSTCONTEXT = eps',
            '$lookup(S.ENV, $ptascii("b")) = eps',
            '$destructor_method(S, 1) = (pmethoddesc)',
            'pdestructorcall.TARGET = METHOD_TARGET 1 pmethoddesc.FUNCTION.ORIGIN',
            '$heap_owners($heap_graph(S), HOBJECT 1) = 2',
            '$destructor_enter_valid(S, pdestructorcall)',
            '~$destructor_enter_valid(S[.DESTRUCTION.CALLED = eps], pdestructorcall)',
            '~$call_task_valid(S, DESTRUCTOR_ENTER (pdestructorcall[.OBJECT = 0][.TARGET = METHOD_TARGET 0 pmethoddesc.FUNCTION.ORIGIN]))',
            '~$destructor_enter_valid(S, pdestructorcall[.STORE = true])',
            '~$destructor_pass_valid(S[.DESTRUCTION.NAMES = eps])',
            *VALID, *REPLAY,
            '~((HOBJECT 0) <- S_done.ALLOCATIONS)',
            '~((HOBJECT 1) <- S_done.ALLOCATIONS)',
        ],
    },
    'live-recycled-handle-selects-new-object': {
        'source': SOURCES['store-reused-handle'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail* -- if pdestructorcall.STORE',
        'checks': [
            'S.DESTRUCTION.PHASE = DESTRUCTION_STORE',
            'S.DESTRUCTION.HANDLES = [1,2,1]',
            'S.DESTRUCTION.FREE = eps', 'S.DESTRUCTION.NEXT = 3',
            'S.DESTRUCTION.INDEX = 2', 'S.DESTRUCTION.NOREUSE',
            'pdestructorcall.OBJECT = 2', 'pdestructorcall.CALLER = eps',
            'pdestructorcall.RELEASE = eps',
            '~((HOBJECT 0) <- S.ALLOCATIONS)',
            '$destructor_handle(S, 1, 0) = (2)',
            '$destructor_handle(S, 2, 0) = (1)',
            '$heap_owners($heap_graph(S), HOBJECT 2) = 3',
            '~$destruction_state_valid(S[.DESTRUCTION.HANDLES = [1,1,1]])',
            '~$destruction_state_valid(S[.DESTRUCTION.FREE = [1]])',
            '~$destruction_state_valid(S[.DESTRUCTION.NOREUSE = false])',
            '~$destructor_call_live(S[.DESTRUCTION.INDEX = 3], pdestructorcall)',
            *VALID, *REPLAY,
            '$heap_owners($heap_graph(S_done), HOBJECT 1) = 1',
            '$heap_owners($heap_graph(S_done), HOBJECT 2) = 1',
        ],
    },
    'repeated-child-slots-retain-unconsumed-owners': {
        'source': SOURCES['global-parent-repeated-child-slot-release-order'],
        'stage': 'S.TODO = (DESTRUCTOR_RELEASE pdestructionrelease) :: ptask_tail* -- if pdestructionrelease.JOBS = [DESTRUCTION_VALUE (HOBJECT 0), DESTRUCTION_VALUE (HOBJECT 1), DESTRUCTION_VALUE (HOBJECT 0), DESTRUCTION_HANDLE 2]',
        'checks': [
            'S.DESTRUCTION.PHASE = DESTRUCTION_GLOBALS',
            'S.DESTRUCTION.CALLS = eps', '2 <- S.DESTRUCTION.CALLED',
            '~((HOBJECT 2) <- S.ALLOCATIONS)',
            '$heap_owners($heap_graph(S), HOBJECT 0) = 2',
            '$heap_owners($heap_graph(S), HOBJECT 1) = 1',
            '$destructor_release_valid(S, pdestructionrelease)',
            '~$destruction_state_valid(S[.DESTRUCTION.FREE = S.DESTRUCTION.HANDLES[2] :: S.DESTRUCTION.FREE])',
            '~$destructor_release_live(S, pdestructionrelease[.JOBS = [DESTRUCTION_VALUE (HOBJECT 1), DESTRUCTION_VALUE (HOBJECT 0), DESTRUCTION_HANDLE 2]])',
            *VALID,
            'PhpStep: S ~> S_step',
            'S_step.TODO = (DESTRUCTOR_RELEASE pdestructionrelease_next) :: ptask_tail*',
            'pdestructionrelease_next.JOBS = [DESTRUCTION_VALUE (HOBJECT 1), DESTRUCTION_VALUE (HOBJECT 0), DESTRUCTION_HANDLE 2]',
            '$heap_owners($heap_graph(S_step), HOBJECT 0) = 1',
            '$heap_owners($heap_graph(S_step), HOBJECT 1) = 1',
            'S_step.DESTRUCTION.CALLED = S.DESTRUCTION.CALLED',
            '$destructor_release_valid(S_step, pdestructionrelease_next)',
            *REPLAY,
            'S_done.EVENTS = [OUTPUT $ptascii("P;"), OUTPUT $ptascii("D:"), OUTPUT $ptascii("middle"), OUTPUT $ptascii(";"), OUTPUT $ptascii("D:"), OUTPUT $ptascii("shared"), OUTPUT $ptascii(";")]',
        ],
    },
    'saved-destructor-context-with-ordinary-helper': {
        'source': '<?php function f(){error_reporting();}class D{function __destruct(){f();}}$d=new D;',
        'stage': 'S.TODO = (CONFIG_INVOKE pconfigcall) :: ptask_tail* -- if pconfigcall.KIND = INTRINSIC_ERROR_REPORTING -- if S.FRAMES = [pframe_saved, pframe_global]',
        'checks': [
            'S.CURRENT = (pcallcontext)',
            'pframe_saved.CONTEXT = (pcallcontext_destructor)',
            'pframe_global.TODO = (DESTRUCTOR_RESULT pdestructorcall) :: ptask_global*',
            'pframe_global.CONTEXT = eps', 'pframe_global.LOCALS = eps',
            'pframe_global.ORIGIN = eps', 'pframe_global.CONSTCONTEXT = eps',
            'pcallcontext_destructor.TARGET = pdestructorcall.TARGET',
            'pcallcontext_destructor.CALLSITE = eps',
            'pcallcontext_destructor.LINE = $(-1)',
            'pcallcontext_destructor.ARGC = 0',
            '$destructor_context_valid(S, pcallcontext_destructor)',
            '$call_saved_context_valid(S, pframe_saved)',
            '~$destructor_context_kind(S, pcallcontext)',
            '$heap_owners($heap_graph(S), HOBJECT pdestructorcall.OBJECT) = 2',
            '~$destructor_context_valid(S, pcallcontext_destructor[.ARGC = 1])',
            '~$destructor_context_valid(S, pcallcontext_destructor[.LINE = 0])',
            '~$destructor_context_valid(S, pcallcontext_destructor[.EXTRA = [KNOWN PNULL]])',
            '~$destructor_context_valid(S, pcallcontext_destructor[.HOLES = [0]])',
            '~$destructor_context_valid(S[.FRAMES = [pframe_saved, pframe_global[.CONSTCONTEXT = ({ORIGIN pcallcontext_destructor.FUNCTION, LINE 1, FACTS eps})]]], pcallcontext_destructor)',
            *VALID, *REPLAY,
        ],
    },
    'ignored-private-warning-retains-one-receiver': {
        'source': '<?php function w($n,$m,$f,$l){error_reporting();return true;}class C{private function __destruct(){}}set_error_handler("w");$c=new C;',
        'stage': 'S.TODO = (CONFIG_INVOKE pconfigcall) :: ptask_tail* -- if pconfigcall.KIND = INTRINSIC_ERROR_REPORTING -- if S.FRAMES = [pframe_global] -- if pframe_global.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_global* -- if perrorcall.RESUME = DESTRUCTOR_WARNING pdestructorcall',
        'checks': [
            'pdestructorcall.CALLER = eps',
            'pframe_global.CONTEXT = eps', 'pframe_global.LOCALS = eps',
            'pframe_global.CONSTCONTEXT = eps',
            'perrorcall.LEVEL = 2', 'perrorcall.LINE = 0',
            'perrorcall.EVENT = DIAGNOSTIC_INTERNAL "Warning" perrorcall.MESSAGE 0',
            '$error_entered_call_valid(S, perrorcall)',
            '$destructor_call_live(S, pdestructorcall)',
            '$heap_owners($heap_graph(S), HOBJECT pdestructorcall.OBJECT) = 1',
            '~$error_entered_call_valid(S, perrorcall[.LINE = 1])',
            '~$error_entered_call_valid(S, perrorcall[.EVENT = DIAGNOSTIC "Warning" perrorcall.MESSAGE 0])',
            *VALID, *REPLAY,
            '~((HOBJECT pdestructorcall.OBJECT) <- S_done.ALLOCATIONS)',
        ],
    },
    'failed-constructor-retained-this-is-already-marked': {
        'source': SOURCES['failed-constructor-resurrected-object-skips-destructor'],
        'stage': 'S.TODO = (CATCH_BIND porigin n_index n_exception) :: ptask_tail*',
        'checks': [
            'S.DESTRUCTION.PHASE = DESTRUCTION_PENDING',
            '0 <- S.DESTRUCTION.CALLED',
            '$lookup(S.ENV, $ptascii("saved")) = (n_saved)',
            'S.STORE[n_saved] = DEFINED (POBJECT 0)',
            '$heap_owners($heap_graph(S), HOBJECT 0) = 1',
            'S.DESTRUCTION.CALLS = eps', 'S.DESTRUCTION.RELEASES = eps',
            *VALID, *REPLAY,
            'S_done.EVENTS = [OUTPUT $ptascii("C;")]',
        ],
    },
    'suspended-throw-child-return-keeps-original-parent': {
        'source': SOURCES['pending-throw-normal-nested-destructor-restores'],
        'stage': 'S.TODO = (DESTRUCTOR_RELEASE pdestructionrelease) :: (DESTRUCTOR_FRAME_EXIT pdestructionframe) :: (DESTRUCTOR_RESULT pdestructorcall) :: ptask_tail* -- if pdestructionframe.PENDING = eps -- if pdestructorcall.PENDING =/= eps',
        'checks': [
            'S.DESTRUCTION.FRAMES = [pdestructionframe, pdestructionframe_parent]',
            'pdestructionframe.CALLER = pdestructionframe_parent.CALLER',
            'S.CURRENT = pdestructionframe.CALLER',
            'pdestructorcall.CALLER = S.CURRENT',
            'pdestructorcall.PENDING = pdestructionframe_parent.PENDING',
            'pdestructorcall.PENDING = (n_parent)',
            'pdestructorcall.FRAME = (pdestructionframe_parent)',
            '$heap_owners($heap_graph(S), HOBJECT n_parent) = 1',
            '$task_nodes(DESTRUCTOR_FRAME_EXIT pdestructionframe) = eps',
            '$task_nodes(DESTRUCTOR_FRAME_EXIT pdestructionframe_parent) = [HOBJECT n_parent]',
            '$destructor_call_live(S, pdestructorcall)',
            '~$destructor_call_live(S, pdestructorcall[.FRAME = (pdestructionframe)])',
            '~$destructor_call_live(S, pdestructorcall[.PENDING = eps])',
            '$destructor_release_valid(S, pdestructionrelease)',
            '$destructor_frame_valid(S, pdestructionframe)',
            '~$destructor_frame_valid(S, pdestructionframe[.CALLER = eps])',
            *VALID, *REPLAY,
        ],
    },
    'returned-object-owner-survives-ordered-local-release': {
        'source': SOURCES['normal-frame-return-owner-survives-local-destructor'],
        'stage': 'S.TODO = (DESTRUCTOR_RELEASE pdestructionrelease) :: (DESTRUCTOR_FRAME_EXIT pdestructionframe) :: ptask_tail* -- if pdestructionframe.VALUE = KNOWN (POBJECT n_returned)',
        'checks': [
            'S.DESTRUCTION.FRAMES = [pdestructionframe]',
            'S.CURRENT = (pcallcontext)',
            'pdestructionframe.CALLER = S.CURRENT',
            'pdestructionframe.PENDING = eps',
            'S.RESULT = KNOWN PNULL',
            '$function_at($all_functions(S), pdestructionframe.FUNCTION) = (pfunction)',
            'pfunction.NAME = $ptascii("get")',
            'pdestructionrelease.JOBS = [DESTRUCTION_VALUE (HCELL n_first), DESTRUCTION_VALUE (HCELL n_second)]',
            'S.STORE[n_first] = DEFINED (POBJECT n_local)',
            'S.STORE[n_second] = DEFINED (POBJECT n_returned)',
            'n_local =/= n_returned',
            '$heap_owners($heap_graph(S), HOBJECT n_local) = 1',
            '$heap_owners($heap_graph(S), HOBJECT n_returned) = 2',
            '$task_nodes(DESTRUCTOR_FRAME_EXIT pdestructionframe) = [HOBJECT n_returned]',
            '$destructor_frame_valid(S, pdestructionframe)',
            '~$destructor_frame_valid(S, pdestructionframe[.VALUE = KNOWN PNULL])',
            '~$destructor_frame_valid(S, pdestructionframe[.CALLER = eps])',
            '~$destructor_frame_valid(S, pdestructionframe[.ORIGIN = eps])',
            *VALID, *REPLAY,
            '~((HOBJECT n_local) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_returned) <- S_done.ALLOCATIONS)',
        ],
    },
    'extra-arguments-precede-the-receiver-release': {
        'source': SOURCES['method-frame-extra-arguments-release-before-receiver'],
        'stage': 'S.TODO = (DESTRUCTOR_RELEASE pdestructionrelease) :: (DESTRUCTOR_FRAME_EXIT pdestructionframe) :: ptask_tail* -- if pdestructionrelease.JOBS = [DESTRUCTION_VALUE (HOBJECT n_extra), DESTRUCTION_VALUE (HOBJECT n_receiver)] -- if pdestructionframe.PENDING = eps',
        'checks': [
            'S.DESTRUCTION.FRAMES = [pdestructionframe]',
            'S.CURRENT = (pcallcontext)',
            'pdestructionframe.CALLER = S.CURRENT',
            'pdestructionrelease.CALLER = S.CURRENT',
            'S.RESULT = KNOWN PNULL',
            '$class_method_origin(S.CLASSES, pdestructionframe.FUNCTION) = (pmethoddesc)',
            'pmethoddesc.NAME = $ptascii("f")',
            'n_extra =/= n_receiver',
            '$heap_owners($heap_graph(S), HOBJECT n_extra) = 1',
            '$heap_owners($heap_graph(S), HOBJECT n_receiver) = 1',
            '$destructor_release_valid(S, pdestructionrelease)',
            '~$destructor_release_live(S, pdestructionrelease[.JOBS = [DESTRUCTION_VALUE (HOBJECT n_receiver), DESTRUCTION_VALUE (HOBJECT n_extra)]])',
            '$destructor_frame_valid(S, pdestructionframe)',
            *VALID,
            'PhpStep: S ~> S_step',
            'S_step.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_next*',
            'pdestructorcall.OBJECT = n_extra',
            'pdestructorcall.CALLER = S.CURRENT',
            '$destructor_enter_valid(S_step, pdestructorcall)',
            '$heap_owners($heap_graph(S_step), HOBJECT n_receiver) = 1',
            *REPLAY,
            '~((HOBJECT n_extra) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
        ],
    },
    'private-nested-destructor-retains-api-producer-scope': {
        'source': SOURCES['nested-private-destructor-registers-private-keyword-callback'],
        'stage': 'S.SHUTDOWN.ENTRIES = [pshutdownentry] -- if S.CURRENT = (pcallcontext) -- if $destructor_context_kind(S, pcallcontext) -- if $class_method_origin(S.CLASSES, pcallcontext.FUNCTION) = (pmethoddesc) -- if pmethoddesc.VISIBILITY = PROPERTY_PRIVATE',
        'checks': [
            'S.SHUTDOWN.PHASE = SHUTDOWN_DONE',
            'S.DESTRUCTION.PHASE = DESTRUCTION_GLOBALS',
            'pcallcontext.CALLSITE = (porigin_release)',
            '$destructor_context_valid(S, pcallcontext)',
            'pshutdownentry.CAPTURE = (pmethodcapture)',
            'pmethodcapture.FUNCTION = pcallcontext.FUNCTION',
            'pmethodcapture.CALLSITE = (porigin_release)',
            'pshutdownentry.PRODUCER = (pshutdownproducer)',
            'pshutdownproducer.TARGET = pcallcontext.TARGET',
            'pshutdownproducer.SITE = (porigin_release)',
            'pshutdownproducer.INTERNAL',
            '$consumer_destructor_target(S, pshutdownproducer.TARGET)',
            '$consumer_producer_capture(S, pshutdownentry)',
            '$shutdown_entry_valid(S, pshutdownentry)',
            '$shutdown_roots(S.SHUTDOWN.ENTRIES) = eps',
            '~$shutdown_entry_valid(S, pshutdownentry[.CAPTURE = (pmethodcapture[.CALLSITE = eps])])',
            '~$shutdown_entry_valid(S, pshutdownentry[.PRODUCER = (pshutdownproducer[.SITE = eps])])',
            *VALID, *REPLAY,
            'S_done.SHUTDOWN.INDEX = 0',
            '|S_done.SHUTDOWN.ENTRIES| = 1',
            '$shutdown_entry_valid(S_done, S_done.SHUTDOWN.ENTRIES[0])',
        ],
    },
    'eval-publication-retains-authentic-request-history': {
        'source': SOURCES['destructor-eval-publication-and-new-global'],
        'eval': 'class E{function __destruct(){echo "E;";}}$GLOBALS["late"]=new E;',
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail* -- if $class_named(S.CLASSNAMES, $ptascii("e")) = (porigin_late) -- if S.OBJECTS[pdestructorcall.OBJECT] = INSTANCE porigin_late',
        'checks': [
            'S.DESTRUCTION.PHASE = DESTRUCTION_GLOBALS',
            'S.DESTRUCTION.COMPLETION = NORMAL',
            'S.CURRENT = eps', 'S.FRAMES = eps', 'S.CONSTCONTEXT = eps',
            'S.EVALCONTEXTS = eps', '~S.COMPILESTOP',
            'porigin_late = PORIGIN 1 pcpath',
            'pdestructorcall.CALLER = eps', '~pdestructorcall.STORE',
            '$destructor_enter_valid(S, pdestructorcall)',
            '$eval_state_valid(S)', '$declaration_history_valid(S)',
            *VALID, *REPLAY,
            '$declaration_history_valid(S_done)',
            '~((HOBJECT pdestructorcall.OBJECT) <- S_done.ALLOCATIONS)',
        ],
    },
}

runner.CASES = CASES

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--case', action='append')
    args = parser.parse_args()
    raise SystemExit(0 if runner.run(args.case) else 1)
