"""Source-reached writable key ownership, notice order and abort demand."""
from error_handler_protocol import PREFIX

GUARDS = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
          '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))']
FINISH = ['S_done = $drive(S_resume, 3000)', 'S_done.COMPLETION = NORMAL',
          'S_done.TODO = eps', 'S_done.CURRENT = eps', 'S_done.FRAMES = eps',
          'S_done.HELD = eps', 'S_done.BORROWEDREAD = eps', 'S_done.TRACE = eps',
          'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
          '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))']
RESUME = ['PhpStep: S ~> S_resume', 'S_resume.TODO = ptask_tail*',
          'S_resume.RESULT = KNOWN PNULL', 'S_resume.ENV = S.ENV',
          'S_resume.STORE = S.STORE', 'S_resume.ARRAYS = S.ARRAYS']
COMMON = ['S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail*',
          'pkeyread = pkeywrite.READ', '~pkeyread.GLOBAL', '~pkeywrite.RW',
          'pkeyread.MODE = KEY_R', 'pkeyread.OWNERS = BASE_VALUE (KNOWN PNULL)',
          'pkeyread.BASE = PARRAY n_selected', 'S.ORIGIN = (pkeyread.SITE)',
          'ptask_tail* = (ORIGIN_RETURN porigin_before?) :: (KEY_WRITE_FINISH pkeywriter) :: ptask_after*',
          'porigin_before? = (pkeywriter.SITE)', 'pkeywriter.SITE = pkeyread.SITE',
          'pkeywriter.TARGET = pkeyread.SITE', 'pkeywriter.TEMP = eps',
          '$key_writer_valid(S, pkeywriter, ptask_after*)',
          '$key_write_valid(S, pkeywrite)', '$call_task_valid(S, KEY_WRITE_RESULT pkeywrite)',
          '$task_nodes(KEY_WRITE_RESULT pkeywrite) = [HARRAY n_selected]',
          '$task_nodes(KEY_WRITE_FINISH pkeywriter) = eps',
          '~((HARRAY n_selected) <- $pools_nodes(S.POOLS))',
          '$lookup(S.ENV, $ptascii("a242")) = (n_a)', 'pkeywrite.PLACE = ROOT n_a',
          'S.STORE[n_a] = DEFINED (PARRAY n_selected)',
          '~$key_write_valid(S, pkeywrite[.READ.SITE = PORIGIN 999 eps])',
          '~$key_write_valid(S, pkeywrite[.READ.LINE = 999])',
          '~$key_write_valid(S, pkeywrite[.READ.MODE = KEY_IS])',
          '~$key_write_valid(S, pkeywrite[.READ.GLOBAL = true])',
          '~$key_write_valid(S, pkeywrite[.RW = true])',
          '~$key_write_valid(S[.ORIGIN = eps], pkeywrite)',
          '~$key_write_valid(S, pkeywrite[.READ.OWNERS = BASE_VALUE (KNOWN pkeyread.BASE)])',
          '~$key_writer_valid(S, pkeywriter[.TEMP = ((pkeyread.SITE, n_a))], ptask_after*)',
          '~$key_writer_valid(S, pkeywriter[.BASE = BASE_DIM (BASE_VALUE (KNOWN pkeyread.BASE)) pkeyread.INPUT pkeyread.LINE], ptask_after*)']

CASES = [
    ('null-reference-separates-before-callback',
     'null-key-reference-separates-before-conversion',
     'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail* -- if pkeywrite.READ.PHASE = KEY_NULL', [
        *COMMON, 'pkeywriter.TASK = ACQUIRE_ARRAY 4', 'pkeywriter.RHS = KNOWN PNULL',
        'pkeyread.PHASE = KEY_NULL', 'pkeyread.INPUT = VARIABLE $ptascii("key242") 4',
        'pkeyread.VALUE = PNULL', 'pkeyread.KEY = KSTRING eps', 'pkeyread.NAME = eps', 'pkeyread.LINE = 4',
        '$lookup(S.ENV, $ptascii("old242")) = (n_old_cell)',
        'S.STORE[n_old_cell] = DEFINED (PARRAY n_old)', 'n_old =/= n_selected',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_selected) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_old) = 1', '$key_write_single(S, pkeywrite)',
        '$entry_lookup(S.ARRAYS[n_selected].ITEMS, KSTRING eps) = (DIRECT (PINT 5))',
        '$entry_lookup(S.ARRAYS[n_old].ITEMS, KSTRING eps) = (DIRECT (PINT 5))',
        '$lookup(S.ENV, $ptascii("key242")) = (n_key)', 'S.STORE[n_key] = DEFINED (PSTRING $ptascii("changed"))',
        '~$key_write_valid(S, pkeywrite[.READ.KEY = KINT 0])',
        '~$key_write_valid(S, pkeywrite[.READ.VALUE = PSTRING eps])',
        '~$key_write_valid(S, pkeywrite[.READ.INPUT = KNOWN PNULL])',
        '$outputs(S.EVENTS) = $ptascii("D;")', *GUARDS, *RESUME,
        'S_resume.LOCATION = ELEMENT n_selected (KSTRING eps)',
        '$heap_owners($heap_prune($heap_graph(S_resume)), HARRAY n_selected) = 1', *FINISH,
        '$lookup(S_done.ENV, $ptascii("ref242")) = (n_ref)', 'n_ref <- S_done.REFCELLS',
        'S_done.STORE[n_ref] = DEFINED (PINT 17)',
        '$entry_lookup(S_done.ARRAYS[n_selected].ITEMS, KSTRING eps) = (ALIAS n_ref)',
        '$entry_lookup(S_done.ARRAYS[n_old].ITEMS, KSTRING eps) = (DIRECT (PINT 5))',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_ref) = 2',
     ]),
    ('nan-write-retains-selected-table-through-notice-tail',
     'nan-key-reference-keeps-protection-and-real-cell-through-tail',
     'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail* -- if $key_float_phase(pkeywrite.READ.PHASE)', [
        *COMMON, 'pkeywriter.TASK = ACQUIRE_ARRAY 7', 'pkeywriter.RHS = KNOWN PNULL',
        'pkeyread.PHASE = KEY_FLOAT RANGEWARNING ([PRECISIONLOSS])',
        'pkeyread.INPUT = VARIABLE $ptascii("key242") 7', 'pkeyread.VALUE = PFLOAT n_bits',
        '$float_long(n_bits, true) = (0, [RANGEWARNING, PRECISIONLOSS])',
        'pkeyread.KEY = KINT 0', 'pkeyread.NAME = eps', 'pkeyread.LINE = 7',
        '$lookup(S.ENV, $ptascii("old242")) = (n_old_cell)',
        'S.STORE[n_old_cell] = DEFINED (PARRAY n_old)', 'n_old =/= n_selected',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_selected) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_old) = 1',
        '$lookup(S.ENV, $ptascii("cell242")) = (n_cell)',
        '$entry_lookup(S.ARRAYS[n_selected].ITEMS, KINT 0) = (ALIAS n_cell)',
        '$entry_lookup(S.ARRAYS[n_old].ITEMS, KINT 0) = (ALIAS n_cell)',
        'S.STORE[n_cell] = DEFINED (PINT 17)', '$heap_owners($heap_prune($heap_graph(S)), HCELL n_cell) = 3',
        '$outputs(S.EVENTS) = $ptascii("W;")', '$key_write_single(S, pkeywrite)',
        '~$key_write_valid(S, pkeywrite[.READ.PHASE = KEY_FLOAT RANGEWARNING eps])',
        '~$key_write_valid(S, pkeywrite[.READ.PHASE = KEY_FLOAT PRECISIONLOSS ([RANGEWARNING])])',
        '~$key_write_valid(S, pkeywrite[.READ.PHASE = KEY_FLOAT RANGEWARNING (RANGEWARNING :: [PRECISIONLOSS])])',
        '~$key_write_valid(S, pkeywrite[.READ.KEY = KINT 1])',
        '~$key_write_valid(S, pkeywrite[.READ.INPUT = KNOWN pkeyread.VALUE])',
        *GUARDS, 'PhpStep: S ~> S_next',
        'S_next.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = KEY_WRITE_RESULT pkeywrite_next',
        'pkeywrite_next = pkeywrite[.READ.PHASE = KEY_FLOAT PRECISIONLOSS eps]',
        'perrorcall.LEVEL = 8192', 'perrorcall.MESSAGE = $key_read_message(pkeywrite_next.READ)',
        '$error_call_valid(S_next, perrorcall)', '$heap_owners($heap_prune($heap_graph(S_next)), HARRAY n_selected) = 2',
        'S_final_reached = $seek(S_next, 1500)', 'S_final = S_final_reached[.COMPLETION = NORMAL]',
        'S_final.TODO = (KEY_WRITE_RESULT pkeywrite_next) :: ptask_tail*',
        'S_final.STORE[n_cell] = DEFINED (PINT 19)', '$outputs(S_final.EVENTS) = $ptascii("W;D;")',
        '$heap_owners($heap_prune($heap_graph(S_final)), HARRAY n_selected) = 2',
        'PhpStep: S_final ~> S_resume', 'S_resume.TODO = ptask_tail*',
        'S_resume.LOCATION = ELEMENT n_selected (KINT 0)',
        '$heap_owners($heap_prune($heap_graph(S_resume)), HARRAY n_selected) = 1', *FINISH,
        'S_done.STORE[n_cell] = DEFINED (PINT 23)', '$lookup(S_done.ENV, $ptascii("ref242")) = (n_cell)',
        '$entry_lookup(S_done.ARRAYS[n_selected].ITEMS, KINT 0) = (ALIAS n_cell)',
        '$entry_lookup(S_done.ARRAYS[n_old].ITEMS, KINT 0) = (ALIAS n_cell)',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_cell) = 4',
     ]),
    ('throw-discards-writable-protection-before-reference-bind',
     'nan-first-notice-throw-keeps-old-typed-destination-binding',
     'S.TODO = (THROW_SEARCH n_throw) :: ptask_tail* -- if S.FRAMES = pframe :: pframe_tail* -- if pframe.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_saved* -- if perrorcall.RESUME = KEY_WRITE_RESULT pkeywrite', [
        'S.TODO = (THROW_SEARCH n_throw) :: ptask_tail*', 'S.FRAMES = pframe :: pframe_tail*',
        'pframe.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_saved*',
        'perrorcall.RESUME = KEY_WRITE_RESULT pkeywrite', 'pkeyread = pkeywrite.READ',
        'pkeyread.PHASE = KEY_FLOAT RANGEWARNING ([PRECISIONLOSS])',
        '~pkeyread.GLOBAL', '~pkeywrite.RW', 'pkeyread.MODE = KEY_R',
        'pkeyread.INPUT = VARIABLE $ptascii("key242") 10', 'pkeyread.LINE = 10',
        'pkeyread.BASE = PARRAY n_selected', 'pkeyread.OWNERS = BASE_VALUE (KNOWN PNULL)',
        '$task_nodes(KEY_WRITE_RESULT pkeywrite) = [HARRAY n_selected]',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_selected) = 1',
        'S_saved = $constant_frame_scope(S, pframe, pframe_tail*)',
        '$key_write_valid(S_saved, pkeywrite)', '$error_entered_call_valid(S_saved, perrorcall)',
        '$lookup(S_saved.ENV, $ptascii("a242")) = eps', '$lookup(S_saved.ENV, $ptascii("key242")) = eps',
        '$lookup(S_saved.ENV, $ptascii("older242")) = eps',
        '$lookup(S_saved.ENV, $ptascii("destination242")) = (n_destination)',
        'S.STORE[n_destination] = DEFINED (PINT 9)', 'n_destination <- S.REFCELLS',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_destination) = 2',
        '$propref_at(S.PROPREFS, n_destination) = (ppropref)',
        'ppropref.SOURCES = [CLASS_PROP_SOURCE ppropertyid]',
        '$propref_source_valid(S, n_destination, CLASS_PROP_SOURCE ppropertyid)',
        '$lookup(S_saved.ENV, $ptascii("pending242")) = (n_pending)',
        'S.STORE[n_pending] = DEFINED (POBJECT n_throw)',
        '$throwable_field(S, n_throw, "previous") = POBJECT n_older',
        '$throwable_field(S, n_older, "message") = PSTRING $ptascii("older")',
        '$throwable_chain_valid(S, n_throw)', '(HOBJECT n_older) <- S.ALLOCATIONS',
        '~$key_write_valid(S_saved, pkeywrite[.READ.LINE = 999])',
        '~$key_write_valid(S_saved, pkeywrite[.READ.PHASE = KEY_FLOAT RANGEWARNING eps])',
        '$outputs(S.EVENTS) = $ptascii("W;")', *GUARDS,
        'S_done = $drive(S, 3000)', 'S_done.COMPLETION = NORMAL', 'S_done.TODO = eps',
        'S_done.CURRENT = eps', 'S_done.FRAMES = eps', 'S_done.HELD = eps', 'S_done.TRACE = eps',
        'S_done.BORROWEDREAD = eps', 'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
        '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))',
        '~((HARRAY n_selected) <- S_done.ALLOCATIONS)', 'S_done.STORE[n_destination] = DEFINED (PINT 19)',
        '$lookup(S_done.ENV, $ptascii("destination242")) = (n_destination)',
        '$propref_source_valid(S_done, n_destination, CLASS_PROP_SOURCE ppropertyid)',
        '$lookup(S_done.ENV, $ptascii("pending242")) = eps', '$lookup(S_done.ENV, $ptascii("e")) = (n_e)',
        'S_done.STORE[n_e] = DEFINED (POBJECT n_throw)',
        '$throwable_field(S_done, n_throw, "previous") = POBJECT n_older',
        '$throwable_chain_valid(S_done, n_throw)',
     ]),
    ('constant-null-abort-does-not-demand-delayed-rhs',
     'constant-null-compound-abort-skips-delayed-rhs-cv-demand',
     'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail* -- if pkeywrite.READ.PHASE = KEY_NULL', [
        'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail*', 'pkeyread = pkeywrite.READ',
        '~pkeyread.GLOBAL', 'pkeywrite.RW', 'pkeyread.MODE = KEY_R', 'pkeyread.PHASE = KEY_NULL',
        'pkeyread.INPUT = KNOWN PNULL', 'pkeyread.VALUE = PNULL', 'pkeyread.KEY = KSTRING eps',
        'pkeyread.LINE = 4', 'pkeyread.BASE = PARRAY n_selected',
        'pkeyread.OWNERS = BASE_VALUE (KNOWN PNULL)', 'S.ORIGIN = (pkeyread.SITE)',
        'ptask_tail* = (ORIGIN_RETURN porigin_before?) :: (KEY_WRITE_FINISH pkeywriter) :: ptask_after*',
        'porigin_before? = (pkeywriter.SITE)', 'pkeywriter.TARGET = pkeyread.SITE',
        'pkeywriter.TASK = COMPOUND_APPLY ADD pkeywriter.BASE false 4',
        'pkeywriter.RHS = VARIABLE $ptascii("missingRhs242") 4', 'pkeywriter.TEMP = eps',
        '$key_writer_valid(S, pkeywriter, ptask_after*)', '$key_write_valid(S, pkeywrite)',
        '$origin_child((pkeyread.SITE), [PCFIELD 1]) = (porigin_key)', '$compiled_read(S, porigin_key) = (PNULL)',
        '$task_nodes(KEY_WRITE_RESULT pkeywrite) = [HARRAY n_selected]', '$task_nodes(KEY_WRITE_FINISH pkeywriter) = eps',
        '~((HARRAY n_selected) <- $pools_nodes(S.POOLS))',
        '$lookup(S.ENV, $ptascii("a242")) = (n_a)', 'pkeywrite.PLACE = ROOT n_a',
        'S.STORE[n_a] = DEFINED (PARRAY n_selected)', '$lookup(S.ENV, $ptascii("held242")) = (n_held)',
        'S.STORE[n_held] = DEFINED (PARRAY n_selected)', 'n_a =/= n_held',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_selected) = 3', '~$key_write_single(S, pkeywrite)',
        '$lookup(S.ENV, $ptascii("missingRhs242")) = eps',
        '~$key_write_valid(S, pkeywrite[.READ.INPUT = KNOWN (PINT 0)])',
        '~$key_write_valid(S, pkeywrite[.READ.VALUE = PINT 0])',
        '~$key_write_valid(S, pkeywrite[.READ.KEY = KINT 0])',
        '~$key_write_valid(S, pkeywrite[.READ.LINE = 999])',
        '~$key_write_valid(S, pkeywrite[.RW = false])',
        '~$key_write_valid(S, pkeywrite[.READ.MODE = KEY_IS])',
        '~$key_writer_valid(S, pkeywriter[.RHS = KNOWN PNULL], ptask_after*)',
        '~$key_writer_valid(S, pkeywriter[.TEMP = ((pkeyread.SITE, n_a))], ptask_after*)',
        '$outputs(S.EVENTS) = $ptascii("D;")', *GUARDS, *RESUME, 'S_resume.LOCATION = NOWHERE',
        '$lookup(S_resume.ENV, $ptascii("missingRhs242")) = eps',
        '$heap_owners($heap_prune($heap_graph(S_resume)), HARRAY n_selected) = 2', *FINISH,
        '$lookup(S_done.ENV, $ptascii("missingRhs242")) = eps',
        '$lookup(S_done.ENV, $ptascii("result242")) = (n_result)', 'S_done.STORE[n_result] = DEFINED PNULL',
        '$entry_lookup(S_done.ARRAYS[n_selected].ITEMS, KSTRING eps) = (DIRECT (PINT 5))',
        'S_done.STORE[n_a] = DEFINED (PARRAY n_selected)', 'S_done.STORE[n_held] = DEFINED (PARRAY n_selected)',
     ]),
]
