from error_handler_protocol import PREFIX
GUARDS=['$call_current_valid(S)','$call_frames_valid(S, S.FRAMES)','$call_descriptors_valid(S)','$heap_valid($heap_graph(S))']
FINISH=['S_done = $drive(S, 3000)','S_done.COMPLETION = NORMAL','S_done.TODO = eps','S_done.CURRENT = eps','S_done.FRAMES = eps','S_done.HELD = eps','S_done.BORROWEDREAD = eps','S_done.ERRORHANDLER.CALLBACK = eps','S_done.ERRORHANDLERS = eps','$call_descriptors_valid(S_done)','$heap_valid($heap_graph(S_done))']
CASES=[
 ('global-name-resume-has-no-cv-key-owner','global-array-name-conversion-keeps-selected-name',
  'S.TODO = (KEY_READ_RESULT pkeyread) :: ptask_tail*\n  -- if pkeyread.GLOBAL\n  -- if pkeyread.PHASE = KEY_ARRAY_NAME',[
    'S.TODO = (KEY_READ_RESULT pkeyread) :: ptask_tail*','pkeyread.GLOBAL','pkeyread.MODE = KEY_R','pkeyread.PHASE = KEY_ARRAY_NAME',
    'pkeyread.INPUT = VARIABLE $ptascii("key233") 8','pkeyread.VALUE = PARRAY n_original','pkeyread.BASE = PNULL','pkeyread.OWNERS = BASE_VALUE (KNOWN PNULL)',
    'pkeyread.NAME = $ptascii("Array")','pkeyread.LINE = 8','S.ORIGIN = (pkeyread.SITE)','$key_read_valid(S, pkeyread)','$call_task_valid(S, KEY_READ_RESULT pkeyread)',
    '~$key_read_protect(pkeyread)','$task_nodes(KEY_READ_RESULT pkeyread) = eps',
    '$lookup(S.ENV, $ptascii("copy233")) = (n_copy)','S.STORE[n_copy] = DEFINED (PARRAY n_original)','$heap_owners($heap_graph(S), HARRAY n_original) = 1',
    '$lookup(S.ENV, $ptascii("key233")) = (n_key)','S.STORE[n_key] = DEFINED (PSTRING $ptascii("other233"))',
    '$entry_lookup(S.ARRAYS[n_original].ITEMS, KINT 0) = (ALIAS n_cell)','$lookup(S.ENV, $ptascii("cell233")) = (n_cell)',
    'S.STORE[n_cell] = DEFINED (PINT 19)','$heap_owners($heap_graph(S), HCELL n_cell) = 2',
    '~$key_read_valid(S, pkeyread[.LINE = 999])','~$key_read_valid(S, pkeyread[.SITE = PORIGIN 999 eps])','~$key_read_valid(S[.ORIGIN = eps], pkeyread)',
    '~$key_read_valid(S, pkeyread[.NAME = $ptascii("other233")])','~$key_read_valid(S, pkeyread[.GLOBAL = false])','~$key_read_valid(S, pkeyread[.MODE = KEY_TEST false])',
    '~$key_read_valid(S, pkeyread[.INPUT = KNOWN pkeyread.VALUE])','~$key_read_valid(S, pkeyread[.INPUT = REFERENCE n_cell])',
    '~$key_read_valid(S, pkeyread[.OWNERS = BASE_VALUE (KNOWN pkeyread.VALUE)])','~$key_read_valid(S[.TODO = [KEY_READ_RESULT pkeyread]], pkeyread)',
    *GUARDS,'PhpStep: S ~> S_resumed','S_resumed.RESULT = KNOWN (PINT 17)','S_resumed.TODO = ptask_tail*','S_resumed.BASE = BASE_VALUE (KNOWN PNULL)',
    'S_resumed.ENV = S.ENV','S_resumed.STORE = S.STORE','S_resumed.GLOBALTABLE = S.GLOBALTABLE',
    *FINISH,
  ]),
 ('constant-null-missing-warning-captures-null','constant-null-conversion-then-missing-keeps-captured-null',
  'S.TODO = (KEY_READ_RESULT pkeyread) :: ptask_tail*\n  -- if ~pkeyread.GLOBAL\n  -- if pkeyread.PHASE = KEY_MISSING',[
    'S.TODO = (KEY_READ_RESULT pkeyread) :: ptask_tail*','~pkeyread.GLOBAL','pkeyread.PHASE = KEY_MISSING','pkeyread.MODE = KEY_R',
    'pkeyread.INPUT = KNOWN PNULL','pkeyread.VALUE = PNULL','pkeyread.KEY = KSTRING eps','pkeyread.BASE = PARRAY n_original',
    'pkeyread.OWNERS = BASE_VALUE (VARIABLE $ptascii("a233") 8)','pkeyread.LINE = 8','$key_read_valid(S, pkeyread)',
    '$origin_child((pkeyread.SITE), [PCFIELD 1]) = (porigin_key)','$compiled_read(S, porigin_key) = (PNULL)',
    '~$key_read_protect(pkeyread)','$task_nodes(KEY_READ_RESULT pkeyread) = eps',
    '$lookup(S.ENV, $ptascii("keep233")) = (n_keep)','S.STORE[n_keep] = DEFINED (PARRAY n_original)',
    '$heap_owners($heap_graph(S), HARRAY n_original) = 1','$entry_lookup(S.ARRAYS[n_original].ITEMS, KSTRING eps) = (DIRECT (PINT 31))',
    '$lookup(S.ENV, $ptascii("a233")) = (n_a)','S.STORE[n_a] = DEFINED (PARRAY n_current)','n_current =/= n_original',
    '$entry_lookup(S.ARRAYS[n_current].ITEMS, KSTRING eps) = (DIRECT (PINT 17))',
    '~$key_read_valid(S, pkeyread[.KEY = KINT 0])','~$key_read_valid(S, pkeyread[.VALUE = PSTRING eps])',
    '~$key_read_valid(S, pkeyread[.INPUT = KNOWN (PINT 0)])','~$key_read_valid(S, pkeyread[.OWNERS = BASE_VALUE (KNOWN pkeyread.BASE)])',
    '~$key_read_valid(S, pkeyread[.OWNERS = BASE_VALUE (REFERENCE n_keep)])','~$key_read_valid(S, pkeyread[.GLOBAL = true])',
    '~$key_read_valid(S, pkeyread[.MODE = KEY_IS])','~$key_read_valid(S, pkeyread[.LINE = 999])',
    *GUARDS,'PhpStep: S ~> S_resumed','S_resumed.RESULT = KNOWN PNULL','S_resumed.TODO = ptask_tail*','S_resumed.BASE = BASE_VALUE (KNOWN PNULL)',
    'S_resumed.ENV = S.ENV','S_resumed.STORE = S.STORE','S_resumed.ARRAYS = S.ARRAYS',*FINISH,
  ]),
 ('throw-retirement-releases-genuine-key-temporary','global-conversion-throw-releases-real-key-temporary',
  'S.TODO = (THROW_SEARCH n_throw) :: ptask_tail*\n  -- if S.FRAMES = pframe :: pframe_tail*\n  -- if pframe.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_saved*\n  -- if perrorcall.RESUME = KEY_READ_RESULT pkeyread',[
    'S.TODO = (THROW_SEARCH n_throw) :: ptask_tail*','S.FRAMES = pframe :: pframe_tail*','pframe.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_saved*',
    'perrorcall.RESUME = KEY_READ_RESULT pkeyread','pkeyread.GLOBAL','pkeyread.PHASE = KEY_ARRAY_NAME','pkeyread.MODE = KEY_R','pkeyread.INPUT = KNOWN (PARRAY n_temporary)',
    'pkeyread.VALUE = PARRAY n_temporary','pkeyread.OWNERS = BASE_VALUE (KNOWN PNULL)','~$key_read_protect(pkeyread)',
    '$task_nodes(KEY_READ_RESULT pkeyread) = [HARRAY n_temporary]','$heap_owners($heap_graph(S), HARRAY n_temporary) = 1',
    '$entry_lookup(S.ARRAYS[n_temporary].ITEMS, KINT 0) = (ALIAS n_cell)','S.STORE[n_cell] = DEFINED (PINT 37)','$heap_owners($heap_graph(S), HCELL n_cell) = 2',
    'S_saved = $constant_frame_scope(S, pframe, pframe_tail*)','$key_read_valid(S_saved, pkeyread)','$error_entered_call_valid(S_saved, perrorcall)',
    '$lookup(S_saved.ENV, $ptascii("cell233")) = eps','$lookup(S_saved.ENV, $ptascii("retained233")) = (n_cell)',
    '$lookup(S_saved.ENV, $ptascii("destination233")) = (n_destination)','S.STORE[n_destination] = DEFINED (PINT 9)',
    '$lookup(S_saved.ENV, $ptascii("pending233")) = (n_pending)','S.STORE[n_pending] = DEFINED (POBJECT n_throw)',
    '$lookup(S_saved.ENV, $ptascii("older233")) = eps',
    *GUARDS,*FINISH,
    'S_done.STORE[n_destination] = DEFINED (PINT 9)','S_done.STORE[n_cell] = DEFINED (PINT 37)',
    '~((HARRAY n_temporary) <- S_done.ALLOCATIONS)','$heap_owners($heap_graph(S_done), HCELL n_cell) = 1',
    '$lookup(S_done.ENV, $ptascii("pending233")) = eps','$lookup(S_done.ENV, $ptascii("e")) = (n_e)',
    'S_done.STORE[n_e] = DEFINED (POBJECT n_throw)','(HOBJECT n_throw) <- S_done.ALLOCATIONS',
  ]),
]
