"""Reached nested unset selection, shared deletion and append notice owners."""
from error_handler_protocol import PREFIX as BASE_PREFIX

PREFIX = BASE_PREFIX + r'''
dec $append_tail_stage(pstate) : bool
def $append_tail_stage(S) = true
  -- if S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail*
  -- if pkeywrite.READ.PHASE = KEY_FLOAT PRECISIONLOSS eps
def $append_tail_stage(S) = false -- otherwise
dec $seek_append_tail(pstate, nat) : pstate
def $seek_append_tail(S, n) = S -- if $append_tail_stage(S) -- if S.COMPLETION = NORMAL \/ S.COMPLETION = BUDGET
def $seek_append_tail(S, n) = $seek_append_tail($drive_steps(S[.COMPLETION = NORMAL], 1), $nabs($(n - 1)))
  -- if ~$append_tail_stage(S)
  -- if S.COMPLETION = NORMAL \/ S.COMPLETION = BUDGET
  -- if $(n > 0)
def $seek_append_tail(S, n) = S -- if S.COMPLETION =/= NORMAL /\ S.COMPLETION =/= BUDGET
'''

GUARDS = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
          '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))']
FINISH = ['S_done.COMPLETION = NORMAL', 'S_done.TODO = eps',
          'S_done.CURRENT = eps', 'S_done.FRAMES = eps', 'S_done.HELD = eps',
          'S_done.BORROWEDREAD = eps', 'S_done.TRACE = eps',
          'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
          '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))']
READ = ['S.ORIGIN = (pkeyread.SITE)', 'pkeyread.LINE = 4',
        '~pkeyread.GLOBAL', 'pkeyread.OWNERS = BASE_VALUE (KNOWN PNULL)',
        'pkeyread.BASE = PARRAY n_selected',
        '~((HARRAY n_selected) <- $pools_nodes(S.POOLS))']

CASES = [
    ('nested-null-prefix-retains-selected-parent-after-cow',
     'nested-unset-null-keeps-selected-parent-after-callback-cow',
     'S.TODO = (KEY_UNSET_FETCH_RESULT pkeyread) :: ptask_tail* -- if pkeyread.PHASE = KEY_NULL', [
        'S.TODO = (KEY_UNSET_FETCH_RESULT pkeyread) :: ptask_tail*', *READ,
        'pkeyread.MODE = KEY_IS', 'pkeyread.PHASE = KEY_NULL',
        'pkeyread.INPUT = VARIABLE $ptascii("key255") 4',
        'pkeyread.VALUE = PNULL', 'pkeyread.KEY = KSTRING eps', 'pkeyread.NAME = eps',
        '$key_unset_fetch_valid(S, pkeyread)', '$call_task_valid(S, KEY_UNSET_FETCH_RESULT pkeyread)',
        '$task_nodes(KEY_UNSET_FETCH_RESULT pkeyread) = [HARRAY n_selected]',
        '$key_read_live(S, pkeyread)',
        '~$key_unset_fetch_valid(S, pkeyread[.SITE = PORIGIN 999 eps])',
        '~$key_unset_fetch_valid(S, pkeyread[.LINE = 999])',
        '~$key_unset_fetch_valid(S, pkeyread[.MODE = KEY_R])',
        '~$key_unset_valid(S, pkeyread[.MODE = KEY_R])',
        '~$key_unset_fetch_valid(S, pkeyread[.GLOBAL = true])',
        '~$key_unset_fetch_valid(S[.ORIGIN = eps], pkeyread)',
        '~$key_unset_fetch_valid(S[.TODO = [KEY_UNSET_FETCH_RESULT pkeyread]], pkeyread)',
        '~$key_unset_fetch_valid(S, pkeyread[.OWNERS = BASE_VALUE (KNOWN pkeyread.BASE)])',
        '~$key_unset_fetch_valid(S, pkeyread[.VALUE = PSTRING eps])',
        '$lookup(S.ENV, $ptascii("a255")) = (n_a)',
        'S.STORE[n_a] = DEFINED (PARRAY n_current)', 'n_current =/= n_selected',
        '$lookup(S.ENV, $ptascii("copy255")) = (n_copy)',
        'S.STORE[n_copy] = DEFINED (PARRAY n_selected)',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_selected) = 2',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_current) = 1',
        '$entry_lookup(S.ARRAYS[n_selected].ITEMS, KSTRING eps) = (DIRECT (PARRAY n_child))',
        '$entry_lookup(S.ARRAYS[n_child].ITEMS, KINT 1) = (DIRECT (PINT 5))',
        '$entry_lookup(S.ARRAYS[n_current].ITEMS, KSTRING eps) = (DIRECT (PARRAY n_changed))',
        'n_changed =/= n_child',
        '$entry_lookup(S.ARRAYS[n_changed].ITEMS, KINT 1) = (DIRECT (PINT 17))',
        '$lookup(S.ENV, $ptascii("key255")) = (n_key)',
        'S.STORE[n_key] = DEFINED (PSTRING $ptascii("changed"))',
        '$outputs(S.EVENTS) = $ptascii("D;")', *GUARDS,
        'PhpStep: S ~> S_selected', 'S_selected.TODO = ptask_tail*',
        'S_selected.RESULT = KNOWN PNULL',
        'S_selected.LOCATION = ELEMENT n_selected (KSTRING eps)',
        'S_selected.STORE = S.STORE', 'S_selected.ARRAYS = S.ARRAYS',
        '$heap_owners($heap_prune($heap_graph(S_selected)), HARRAY n_selected) = 1',
        'S_done = $drive(S_selected, 3000)', *FINISH,
        'S_done.STORE[n_a] = DEFINED (PARRAY n_current)',
        'S_done.STORE[n_copy] = DEFINED (PARRAY n_selected)',
        '$entry_lookup(S_done.ARRAYS[n_child].ITEMS, KINT 1) = eps',
        '$entry_lookup(S_done.ARRAYS[n_changed].ITEMS, KINT 1) = (DIRECT (PINT 17))',
        'S_done.STORE[n_key] = DEFINED (PSTRING $ptascii("changed"))',
     ]),
    ('nested-final-float-deletes-copied-child-without-exact-one-gate',
     'nested-unset-final-copy-deletes-both-selected-rows-keeps-old-real-cell',
     'S.TODO = (KEY_UNSET_RESULT pkeyread) :: ptask_tail* -- if $key_float_phase(pkeyread.PHASE)', [
        'S.TODO = (KEY_UNSET_RESULT pkeyread) :: ptask_tail*', *READ,
        'ptask_tail* = (KEY_UNSET_FINISH pkeyread.SITE pbase) :: ptask_after*',
        'pkeyread.MODE = KEY_R', 'pkeyread.PHASE = KEY_FLOAT PRECISIONLOSS eps',
        'pkeyread.INPUT = VARIABLE $ptascii("key255") 4', 'pkeyread.VALUE = PFLOAT 4609434218613702656',
        'pkeyread.KEY = KINT 1', 'pkeyread.NAME = eps',
        '$key_unset_source(S, pkeyread.SITE, pbase)', '$key_unset_valid(S, pkeyread)',
        '$call_task_valid(S, KEY_UNSET_RESULT pkeyread)',
        '$task_nodes(KEY_UNSET_RESULT pkeyread) = [HARRAY n_selected]',
        '$task_nodes(KEY_UNSET_FINISH pkeyread.SITE pbase) = eps',
        '~$key_unset_valid(S, pkeyread[.SITE = PORIGIN 999 eps])',
        '~$key_unset_valid(S, pkeyread[.LINE = 999])',
        '~$key_unset_valid(S, pkeyread[.MODE = KEY_IS])',
        '~$key_unset_fetch_valid(S, pkeyread[.MODE = KEY_IS])',
        '~$key_unset_valid(S, pkeyread[.OWNERS = BASE_VALUE (KNOWN pkeyread.BASE)])',
        '~$key_unset_valid(S, pkeyread[.KEY = KINT 7])',
        '~$key_unset_valid(S, pkeyread[.INPUT = KNOWN pkeyread.VALUE])',
        '$lookup(S.ENV, $ptascii("a255")) = (n_a)', 'S.STORE[n_a] = DEFINED (PARRAY n_parent)',
        '$entry_lookup(S.ARRAYS[n_parent].ITEMS, KSTRING $ptascii("row")) = (DIRECT (PARRAY n_selected))',
        '$lookup(S.ENV, $ptascii("child255")) = (n_child)', 'S.STORE[n_child] = DEFINED (PARRAY n_selected)',
        '$lookup(S.ENV, $ptascii("old255")) = (n_old)', 'S.STORE[n_old] = DEFINED (PARRAY n_old_parent)',
        'n_old_parent =/= n_parent',
        '$entry_lookup(S.ARRAYS[n_old_parent].ITEMS, KSTRING $ptascii("row")) = (DIRECT (PARRAY n_old_child))',
        'n_old_child =/= n_selected', '$lookup(S.ENV, $ptascii("cell255")) = (n_cell)',
        '$entry_lookup(S.ARRAYS[n_old_child].ITEMS, KINT 1) = (ALIAS n_cell)',
        '$entry_lookup(S.ARRAYS[n_selected].ITEMS, KINT 1) = (ALIAS n_cell)',
        'S.STORE[n_cell] = DEFINED (PINT 17)',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_selected) = 3',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_cell) = 3',
        '$key_unset_live(S, pkeyread)', '$outputs(S.EVENTS) = $ptascii("D;")', *GUARDS,
        'PhpStep: S ~> S_deleted', 'S_deleted.TODO = ptask_tail*',
        'S_deleted.RESULT = KNOWN PNULL', 'S_deleted.LOCATION = NOWHERE',
        'S_deleted.STORE = S.STORE',
        '$entry_lookup(S_deleted.ARRAYS[n_selected].ITEMS, KINT 1) = eps',
        '$entry_lookup(S_deleted.ARRAYS[n_old_child].ITEMS, KINT 1) = (ALIAS n_cell)',
        '$heap_owners($heap_prune($heap_graph(S_deleted)), HARRAY n_selected) = 2',
        '$heap_owners($heap_prune($heap_graph(S_deleted)), HCELL n_cell) = 2',
        'S_done = $drive(S_deleted, 3000)', *FINISH,
        'S_done.STORE[n_cell] = DEFINED (PINT 17)',
        '$entry_lookup(S_done.ARRAYS[n_selected].ITEMS, KINT 1) = eps',
        '$entry_lookup(S_done.ARRAYS[n_old_child].ITEMS, KINT 1) = (ALIAS n_cell)',
     ]),
    ('append-nan-tail-keeps-selected-moved-parent-and-real-row',
     'append-nan-tail-keeps-moved-parent-and-real-row',
     'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail* -- if pkeywrite.READ.PHASE = KEY_FLOAT RANGEWARNING ([PRECISIONLOSS])', [
        'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail*',
        'pkeyread = pkeywrite.READ', *READ, 'pkeyread.MODE = KEY_R', '~pkeywrite.RW',
        'pkeyread.PHASE = KEY_FLOAT RANGEWARNING ([PRECISIONLOSS])',
        'pkeyread.INPUT = VARIABLE $ptascii("key255") 4', 'pkeyread.VALUE = PFLOAT n_bits',
        '$float_long(n_bits, true) = (0, [RANGEWARNING, PRECISIONLOSS])',
        'pkeyread.KEY = KINT 0', 'pkeyread.NAME = eps',
        'ptask_tail* = (ORIGIN_RETURN (porigin_root)) :: (KEY_WRITE_FINISH pkeywriter) :: ptask_after*',
        'pkeywriter.SITE = porigin_root', 'pkeywriter.TARGET = pkeyread.SITE',
        'pkeywriter.TASK = ASSIGN_ARRAY (BASE_APPEND pkeywriter.BASE 4) 4 false',
        'pkeywriter.RHS = KNOWN (PINT 17)', 'pkeywriter.TEMP = eps',
        '$key_writer_valid(S, pkeywriter, ptask_after*)', '$key_write_valid(S, pkeywrite)',
        '$call_task_valid(S, KEY_WRITE_RESULT pkeywrite)',
        '$task_nodes(KEY_WRITE_RESULT pkeywrite) = [HARRAY n_selected]',
        '$task_nodes(KEY_WRITE_FINISH pkeywriter) = eps',
        '~$key_write_valid(S, pkeywrite[.READ.SITE = PORIGIN 999 eps])',
        '~$key_write_valid(S, pkeywrite[.READ.LINE = 999])',
        '~$key_write_valid(S, pkeywrite[.READ.MODE = KEY_IS])',
        '~$key_write_valid(S, pkeywrite[.READ.GLOBAL = true])',
        '~$key_write_valid(S, pkeywrite[.RW = true])',
        '~$key_write_valid(S, pkeywrite[.READ.PHASE = KEY_FLOAT RANGEWARNING eps])',
        '~$key_write_valid(S, pkeywrite[.READ.PHASE = KEY_FLOAT PRECISIONLOSS ([RANGEWARNING])])',
        '~$key_write_valid(S, pkeywrite[.READ.KEY = KINT 1])',
        '~$key_writer_valid(S, pkeywriter[.RHS = KNOWN (PINT 19)], ptask_after*)',
        '~$key_writer_valid(S, pkeywriter[.TEMP = ((pkeyread.SITE, n_selected))], ptask_after*)',
        '$lookup(S.ENV, $ptascii("a255")) = eps',
        'pkeywrite.PLACE = ROOT n_retired', '~((HCELL n_retired) <- S.ALLOCATIONS)',
        '$lookup(S.ENV, $ptascii("held255")) = (n_held)', 'S.STORE[n_held] = DEFINED (PARRAY n_selected)',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_selected) = 2',
        '$key_write_single(S, pkeywrite)',
        '$lookup(S.ENV, $ptascii("row255")) = (n_row)',
        '$entry_lookup(S.ARRAYS[n_selected].ITEMS, KINT 0) = (ALIAS n_row)',
        'S.STORE[n_row] = DEFINED (PARRAY n_child)',
        '$entry_lookup(S.ARRAYS[n_child].ITEMS, KINT 0) = (DIRECT (PINT 5))',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_row) = 2',
        '$outputs(S.EVENTS) = $ptascii("W;")', *GUARDS,
        'PhpStep: S ~> S_next',
        'S_next.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = KEY_WRITE_RESULT pkeywrite_next',
        'pkeywrite_next = pkeywrite[.READ.PHASE = KEY_FLOAT PRECISIONLOSS eps]',
        'perrorcall.LEVEL = 8192', 'perrorcall.LINE = 4', '$error_call_valid(S_next, perrorcall)',
        '$heap_owners($heap_prune($heap_graph(S_next)), HARRAY n_selected) = 2',
        'S_tail_reached = $seek_append_tail(S_next, 1500)', 'S_tail = S_tail_reached[.COMPLETION = NORMAL]',
        'S_tail.TODO = (KEY_WRITE_RESULT pkeywrite_next) :: ptask_tail*',
        '$key_write_valid(S_tail, pkeywrite_next)', '$outputs(S_tail.EVENTS) = $ptascii("W;D;")',
        'PhpStep: S_tail ~> S_selected', 'S_selected.TODO = ptask_tail*',
        'S_selected.LOCATION = ELEMENT n_selected (KINT 0)',
        '$heap_owners($heap_prune($heap_graph(S_selected)), HARRAY n_selected) = 1',
        'S_done = $drive(S_selected, 3000)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("a255")) = eps',
        'S_done.STORE[n_held] = DEFINED (PARRAY n_selected)',
        '$entry_lookup(S_done.ARRAYS[n_selected].ITEMS, KINT 0) = (ALIAS n_row)',
        '$entry_lookup(S_done.ARRAYS[n_child].ITEMS, KINT 1) = (DIRECT (PINT 17))',
        '$heap_owners($heap_prune($heap_graph(S_done)), HCELL n_row) = 2',
     ]),
]
