#!/usr/bin/env python3
"""Ordinary dynamic-property warning continuation and operand lifetime controls."""
import argparse
import base64
import json
import os
from pathlib import Path
import tempfile

import typed_static_ini_prefix_protocol as cross
from recorded_worker import Worker

ROOT = Path(__file__).resolve().parents[2]
CASES = {
    'review-instance-future-unset-dynamic-inherited19': b"<?php\nclass FutureUnsetReceiver359 { public $x = 2; }\nclass FutureUnsetBase359 { public ?int $number = 7; }\nclass FutureUnsetDerived359 extends FutureUnsetBase359 {}\nclass FutureUnsetDynamic359 { public function __destruct() {\n    echo 'A/', (int) ($GLOBALS['wp']->get() === null), '|';\n    try { echo $GLOBALS['value']->number; }\n    catch (Error $error) { echo get_class($error), ':', $error->getMessage(), '|'; }\n} }\n$object = new FutureUnsetReceiver359(); $value = new FutureUnsetDerived359();\nunset($value->number); $child = new FutureUnsetDynamic359();\n@($value->dynamic = $child); unset($child); $wp = WeakReference::create($value);\necho 'C|';\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\n$value = 12; echo $value, '/', $object->x, '/', (int) ($wp->get() === null), '|done';\n",
    'review-instance-future-unset-visibility-alias19': b"<?php\nclass FutureUnsetVisibilityReceiver359 { public $x = 2; }\nclass FutureUnsetVisibilityParent359 {\n    public $first; private int $secret = 5; public int $number = 7;\n    public function clear() { unset($this->secret, $this->number); }\n}\nclass FutureUnsetVisibilityFirst359 { public function __destruct() {\n    echo 'A/', $GLOBALS['r'], '|';\n    try { echo $GLOBALS['value']->secret; }\n    catch (Error $denied) { echo 'denied=', $denied->getMessage(), '|'; }\n    try { echo $GLOBALS['value']->number; }\n    catch (Error $uninit) { echo 'uninit=', $uninit->getMessage(), '|'; }\n} }\n$object = new FutureUnsetVisibilityReceiver359(); $value = new FutureUnsetVisibilityParent359();\n$value->first = new FutureUnsetVisibilityFirst359(); $r =& $value->number;\n$value->clear(); $r = 'free'; echo 'C|';\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\n$value = 12; echo $value, '/', $object->x, '/', $r, '|done';\n",
    'review-instance-future-unset-pending19': b"<?php\nclass FutureUnsetPendingReceiver359 { public $x = 2; }\nclass FutureUnsetPendingParent359 { public $first; public int $number = 7; public $second; }\nclass FutureUnsetPendingFirst359 { public function __destruct() {\n    echo 'A|'; echo $GLOBALS['value']->number;\n} }\nclass FutureUnsetPendingSecond359 { public function __destruct() {\n    echo 'B/', get_class($GLOBALS['value']), '/', (int) ($GLOBALS['wp']->get() === null), '|';\n    throw new Exception('B');\n} }\n$object = new FutureUnsetPendingReceiver359(); $value = new FutureUnsetPendingParent359();\n$value->first = new FutureUnsetPendingFirst359(); $value->second = new FutureUnsetPendingSecond359();\nunset($value->number); $wp = WeakReference::create($value); echo 'C|';\ntry { foreach ($object as $key => &$value) { echo 'unexpected|'; } }\ncatch (Throwable $error) {\n    echo get_class($error), '/', $error->getMessage(), '/previous=',\n        get_class($error->getPrevious()), ':', $error->getPrevious()->getMessage(), '|';\n}\n$value = 12; echo $value, '/', $object->x, '/', (int) ($wp->get() === null), '|done';\n",
    'review-instance-future-initial-inherited19': b"<?php\nclass FutureInitialReceiver359 { public $x = 2; }\nclass FutureInitialBase359 { public $first; public int $number; }\nclass FutureInitialDerived359 extends FutureInitialBase359 {}\nclass FutureInitialFirst359 { public function __destruct() {\n    echo 'A/', (int) ($GLOBALS['wp']->get() === null), '|';\n    try { echo $GLOBALS['value']->number; }\n    catch (Error $error) { echo get_class($error), ':', $error->getMessage(), '|'; }\n} }\n$object = new FutureInitialReceiver359(); $value = new FutureInitialDerived359();\n$value->first = new FutureInitialFirst359(); $wp = WeakReference::create($value);\necho 'C|';\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\n$value = 12; echo $value, '/', $object->x, '/', (int) ($wp->get() === null), '|done';\n",
    'review-instance-future-initial-visibility19': b"<?php\nclass FutureInitialVisibilityReceiver359 { public $x = 2; }\nclass FutureInitialVisibilityParent359 { public $first; private int $secret; public int $number; }\nclass FutureInitialVisibilityFirst359 { public function __destruct() {\n    echo 'A|';\n    try { echo $GLOBALS['value']->secret; }\n    catch (Error $denied) { echo 'denied=', $denied->getMessage(), '|'; }\n    try { echo $GLOBALS['value']->number; }\n    catch (Error $uninit) { echo 'uninit=', $uninit->getMessage(), '|'; }\n} }\n$object = new FutureInitialVisibilityReceiver359(); $value = new FutureInitialVisibilityParent359();\n$value->first = new FutureInitialVisibilityFirst359();\necho 'C|';\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\n$value = 12; echo $value, '/', $object->x, '|done';\n",
    'review-instance-future-initial-pending19': b"<?php\nclass FutureInitialPendingReceiver359 { public $x = 2; }\nclass FutureInitialPendingParent359 { public $first; public int $number; public $second; }\nclass FutureInitialPendingFirst359 { public function __destruct() {\n    echo 'A|'; echo $GLOBALS['value']->number;\n} }\nclass FutureInitialPendingSecond359 { public function __destruct() {\n    echo 'B/', get_class($GLOBALS['value']), '/', (int) ($GLOBALS['wp']->get() === null), '|';\n    throw new Exception('B');\n} }\n$object = new FutureInitialPendingReceiver359(); $value = new FutureInitialPendingParent359();\n$value->first = new FutureInitialPendingFirst359(); $value->second = new FutureInitialPendingSecond359();\n$wp = WeakReference::create($value); echo 'C|';\ntry { foreach ($object as $key => &$value) { echo 'unexpected|'; } }\ncatch (Throwable $error) {\n    echo get_class($error), '/', $error->getMessage(), '/previous=',\n        get_class($error->getPrevious()), ':', $error->getPrevious()->getMessage(), '|';\n}\n$value = 12; echo $value, '/', $object->x, '/', (int) ($wp->get() === null), '|done';\n",
    'review-instance-future-heap-object19': b"<?php\nclass FutureHeapReceiver359 { public $x = 2; }\nclass FutureHeapLeaf359 { public function __destruct() {\n    echo 'B/', (int) ($GLOBALS['wp']->get() === null), '|';\n} }\nclass FutureHeapFirst359 { public function __destruct() {\n    echo 'A|', get_class($GLOBALS['value']->later), '|';\n    $GLOBALS['kept'] = $GLOBALS['value']->later;\n    echo 'kept|';\n} }\nclass FutureHeapParent359 { public $first; public $later; }\n$object = new FutureHeapReceiver359(); $value = new FutureHeapParent359();\n$value->first = new FutureHeapFirst359(); $value->later = new FutureHeapLeaf359();\n$wp = WeakReference::create($value); $wl = WeakReference::create($value->later);\necho 'C|';\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\necho (int) ($wp->get() === null), '/', (int) ($wl->get() !== null), '|';\nunset($kept); echo (int) ($wl->get() === null), '|done';\n",
    'review-instance-future-heap-alias19': b"<?php\nclass FutureAliasHeapReceiver359 { public $x = 2; }\nclass FutureAliasHeapLeaf359 { public function __destruct() {\n    echo 'B/', (int) ($GLOBALS['wp']->get() === null), '|';\n} }\nclass FutureAliasHeapFirst359 { public function __destruct() {\n    echo 'A|';\n    $GLOBALS['kept'] = $GLOBALS['value']->later;\n    $GLOBALS['r'] = null;\n    echo get_class($GLOBALS['kept']), '/',\n        (int) ($GLOBALS['value']->later === null), '|';\n} }\nclass FutureAliasHeapParent359 { public $first; public ?FutureAliasHeapLeaf359 $later; }\n$object = new FutureAliasHeapReceiver359(); $value = new FutureAliasHeapParent359();\n$r = new FutureAliasHeapLeaf359(); $value->later =& $r;\n$value->first = new FutureAliasHeapFirst359();\n$wp = WeakReference::create($value); $wl = WeakReference::create($r);\necho 'C|';\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\n$r = 'free'; echo $r, '/', (int) ($wp->get() === null), '/', (int) ($wl->get() !== null), '|';\nunset($kept); echo (int) ($wl->get() === null), '|done';\n",
    'review-instance-future-heap-array-cow19': b"<?php\nclass FutureCowHeapReceiver359 { public $x = 2; }\nclass FutureCowHeapLeaf359 { public function __destruct() {\n    echo 'B/', (int) ($GLOBALS['wp']->get() === null), '|';\n} }\nclass FutureCowHeapFirst359 { public function __destruct() {\n    echo 'A|';\n    $GLOBALS['kept'] = $GLOBALS['value']->later;\n    $GLOBALS['kept']['tag'] = 'new';\n    echo $GLOBALS['value']->later['tag'], '/', $GLOBALS['kept']['tag'], '|';\n} }\nclass FutureCowHeapParent359 { public $first; public array $later; }\n$object = new FutureCowHeapReceiver359(); $value = new FutureCowHeapParent359();\n$value->first = new FutureCowHeapFirst359();\n$value->later = ['tag' => 'old', 'leaf' => new FutureCowHeapLeaf359()];\n$wp = WeakReference::create($value); $wl = WeakReference::create($value->later['leaf']);\necho 'C|';\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\necho $kept['tag'], '/', (int) ($wp->get() === null), '/', (int) ($wl->get() !== null), '|';\nunset($kept); echo (int) ($wl->get() === null), '|done';\n",
    'review-instance-future-scalar19': b"<?php\nclass FutureReadReceiver359 { public $x = 2; }\nclass FutureReadLeaf359 { public function __destruct() {\n    echo 'C|', $GLOBALS['value']->number, '/', $GLOBALS['value']->text, '/',\n        (int) $GLOBALS['value']->truth, '/', (int) ($GLOBALS['value']->nothing === null), '|';\n} }\nclass FutureReadParent359 {\n    public $child;\n    public int $number = 7;\n    public string $text = 'future';\n    public bool $truth = true;\n    public $nothing = null;\n}\n$object = new FutureReadReceiver359(); $value = new FutureReadParent359();\n$value->child = new FutureReadLeaf359(); $wp = WeakReference::create($value);\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\n$value = 12; echo $value, '/', (int) ($wp->get() === null), '|done';\n",
    'review-instance-future-typed-alias19': b"<?php\nclass FutureAliasReceiver359 { public $x = 2; }\nclass FutureAliasLeaf359 { public function __destruct() {\n    $GLOBALS['r'] = 9;\n    echo 'C|', $GLOBALS['value']->number, '|';\n    try { $GLOBALS['r'] = 'bad'; }\n    catch (TypeError $error) { echo 'type|'; }\n} }\nclass FutureAliasParent359 { public $child; public int $number; }\n$object = new FutureAliasReceiver359(); $value = new FutureAliasParent359();\n$r = 7; $value->number =& $r; $value->child = new FutureAliasLeaf359();\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\n$r = 'free'; echo $r, '/', $value, '|done';\n",
    'review-instance-future-visibility19': b"<?php\nclass FutureVisibilityReceiver359 { public $x = 2; }\nclass FutureVisibilityLeaf359 { public function __destruct() {\n    echo 'C|', $GLOBALS['value']->visible, '|';\n    try { echo $GLOBALS['value']->secret; }\n    catch (Error $error) { echo 'denied|'; }\n} }\nclass FutureVisibilityParent359 {\n    public $child;\n    public int $visible = 7;\n    private int $secret = 41;\n}\n$object = new FutureVisibilityReceiver359(); $value = new FutureVisibilityParent359();\n$value->child = new FutureVisibilityLeaf359();\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\n$value = 12; echo $value, '|done';\n",
    'review-stdinstance-storage-table-reinsert-throws19': b"<?php\nclass StdStorageReceiver359 { public $x = 2; }\nclass StdStorageOrderLeaf359 {\n    public $name;\n    public function __construct($name) { $this->name = $name; }\n    public function __destruct() {\n        echo $this->name, '/', get_class($GLOBALS['value']), '/', (int) ($GLOBALS['wp']->get() === null), '|';\n        throw new Exception($this->name);\n    }\n}\n$object = new StdStorageReceiver359(); $value = new stdClass();\n$value->first = 0; $value->second = new StdStorageOrderLeaf359('B');\n$materialized = (array) $value; unset($materialized);\nunset($value->first); $value->first = new StdStorageOrderLeaf359('A');\n$wp = WeakReference::create($value); echo 'C|';\ntry { foreach ($object as $key => &$value) { echo 'unexpected|'; } }\ncatch (Exception $error) { echo 'caught=', $error->getMessage(), '/previous=', $error->getPrevious()->getMessage(), '|'; }\n$value = 12;\necho $value, '/', $object->x, '/', (int) ($wp->get() === null), '|done';\n",
    'review-stdinstance-storage-generator-return19': b"<?php\nclass StdStorageReturnLeaf359 { public function __destruct() {\n    echo 'L', get_class($GLOBALS['wg']->get()->getReturn()), '/', (int) ($GLOBALS['wp']->get() === null);\n} }\nfunction stdStorageReturn359($value) { yield 1; return $value; }\n$value = new stdClass(); $value->leaf = new StdStorageReturnLeaf359();\n$wp = WeakReference::create($value);\n$generator = stdStorageReturn359($value); unset($value);\n$generator->current(); $generator->next();\n$wg = WeakReference::create($generator); echo 'C|';\nunset($generator); echo '|', (int) ($wg->get() === null);\n",
    'review-stdinstance-storage-metadata19': b"<?php\nclass StdStorageReceiver359 { public $x = 2; }\nclass StdStorageMetadataLeaf359 { public function __destruct() {\n    echo 'C|', get_class($GLOBALS['value']), '/', (int) ($GLOBALS['wp']->get() === null), '|';\n} }\n$object = new StdStorageReceiver359();\n$value = new stdClass(); $value->leaf = new StdStorageMetadataLeaf359();\n$wp = WeakReference::create($value);\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\necho $value, '/', (int) ($wp->get() === null), '|done';\n",
    'review-stdinstance-storage-reinsert-throws19': b"<?php\nclass StdStorageReceiver359 { public $x = 2; }\nclass StdStorageOrderLeaf359 {\n    public $name;\n    public function __construct($name) { $this->name = $name; }\n    public function __destruct() {\n        echo $this->name, '/', get_class($GLOBALS['value']), '/', (int) ($GLOBALS['wp']->get() === null), '|';\n        throw new Exception($this->name);\n    }\n}\n$object = new StdStorageReceiver359(); $value = new stdClass();\n$value->first = 0; $value->second = new StdStorageOrderLeaf359('B');\nunset($value->first); $value->first = new StdStorageOrderLeaf359('A');\n$wp = WeakReference::create($value); echo 'C|';\ntry { foreach ($object as $key => &$value) { echo 'unexpected|'; } }\ncatch (Exception $error) { echo 'caught=', $error->getMessage(), '/previous=', $error->getPrevious()->getMessage(), '|'; }\n$value = 12;\necho $value, '/', $object->x, '/', (int) ($wp->get() === null), '|done';\n",
    'review-stdinstance-storage-shared-table19': b"<?php\nclass StdStorageSharedLeaf359 { public function __destruct() {\n    echo 'L/', (int) ($GLOBALS['wp']->get() === null), '|';\n} }\n$value = (object) ['leaf' => new StdStorageSharedLeaf359()];\n$copy = (array) $value; $wp = WeakReference::create($value);\necho 'C|'; unset($value);\necho (int) ($wp->get() === null), '|held|';\nunset($copy); echo 'done';\n",
    'review-generator-typed-slot-fiber19': b"<?php\nclass ReviewGeneratorTypedFiberHolder19 { public $child; public int $number; }\nclass ReviewGeneratorTypedFiberChild19 { public function __destruct() {\n    echo 'A|';\n    Fiber::suspend();\n    echo 'back|';\n} }\nfunction review_typed_fiber_generator19(&$r) {\n    $holder = new ReviewGeneratorTypedFiberHolder19();\n    $holder->number =& $r;\n    $holder->child = new ReviewGeneratorTypedFiberChild19();\n    yield 1;\n}\n$r = 7;\n$fiber = new Fiber(function () use (&$r) {\n    $generator = review_typed_fiber_generator19($r);\n    $generator->rewind();\n    unset($generator);\n    echo 'closed|';\n});\n$fiber->start();\ntry { $r = 'bad'; echo 'bad|'; }\ncatch (TypeError $error) { echo 'type|'; }\n$fiber->resume();\n$r = 'free';\necho $r, '|done';\n",
    'review-generator-typed-slot-before19': b"<?php\nclass ReviewGeneratorTypedHolder19 { public $child; public int $number; }\nclass ReviewGeneratorTypedChild19 { public function __destruct() {\n    echo 'A|';\n    try { $GLOBALS['r'] = 'bad'; echo 'free|'; }\n    catch (TypeError $error) { echo 'type|'; }\n} }\nfunction review_typed_generator19(&$r) {\n    $holder = new ReviewGeneratorTypedHolder19();\n    $holder->number =& $r;\n    $holder->child = new ReviewGeneratorTypedChild19();\n    yield 1;\n}\n$r = 7;\n$generator = review_typed_generator19($r);\n$generator->rewind();\nunset($generator);\n$r = 'after';\necho $r, '|done';\n",
    'review-generator-typed-slot-after19': b"<?php\nclass ReviewGeneratorTypedHolder19 { public int $number; public $child; }\nclass ReviewGeneratorTypedChild19 { public function __destruct() {\n    echo 'A|';\n    try { $GLOBALS['r'] = 'bad'; echo 'free|'; }\n    catch (TypeError $error) { echo 'type|'; }\n} }\nfunction review_typed_generator19(&$r) {\n    $holder = new ReviewGeneratorTypedHolder19();\n    $holder->child = new ReviewGeneratorTypedChild19();\n    $holder->number =& $r;\n    yield 1;\n}\n$r = 7;\n$generator = review_typed_generator19($r);\n$generator->rewind();\nunset($generator);\n$r = 'after';\necho $r, '|done';\n",
    'review-generator-typed-slot-throw19': b"<?php\nclass ReviewGeneratorTypedTwoHolder19 {\n    public $childA; public int $first; public $childB; public int $second;\n}\nclass ReviewGeneratorTypedTwoA19 { public function __destruct() {\n    echo 'A|'; throw new Exception('A');\n} }\nclass ReviewGeneratorTypedTwoB19 { public function __destruct() {\n    echo 'B|';\n    try { $GLOBALS['r'] = 'bad'; echo 'bad|'; }\n    catch (TypeError $error) { echo 'type|'; }\n    throw new Exception('B');\n} }\nfunction review_typed_two_generator19(&$r) {\n    $holder = new ReviewGeneratorTypedTwoHolder19();\n    $holder->second =& $r;\n    $holder->childB = new ReviewGeneratorTypedTwoB19();\n    $holder->first =& $r;\n    $holder->childA = new ReviewGeneratorTypedTwoA19();\n    yield 1;\n}\n$r = 7;\n$generator = review_typed_two_generator19($r);\n$generator->rewind();\ntry {\n    unset($generator);\n} catch (Exception $error) {\n    echo 'caught=', $error->getMessage(), '/previous=', $error->getPrevious()->getMessage(), '|';\n}\n$r = 'free';\necho $r, '|done';\n",
    'review-typed-slot-two-sources-throw19': b"<?php\nclass ReviewTypedTwoSourceReceiver19 { public $x = 2; public $y = 3; }\nclass ReviewTypedTwoSourceHolder19 {\n    public $childA; public int $first; public $childB; public int $second;\n}\nclass ReviewTypedTwoSourceA19 { public function __destruct() {\n    echo 'A|'; throw new Exception('A');\n} }\nclass ReviewTypedTwoSourceB19 { public function __destruct() {\n    echo 'B|';\n    try { $GLOBALS['r'] = 'bad'; echo 'bad|'; }\n    catch (TypeError $error) { echo 'type|'; }\n    throw new Exception('B');\n} }\n$object = new ReviewTypedTwoSourceReceiver19();\n$r = 7;\n$value = new ReviewTypedTwoSourceHolder19();\n$value->second =& $r;\n$value->childB = new ReviewTypedTwoSourceB19();\n$value->first =& $r;\n$value->childA = new ReviewTypedTwoSourceA19();\ntry {\n    foreach ($object as &$value) { echo 'unexpected|'; }\n} catch (Exception $error) {\n    echo 'caught=', $error->getMessage(), '/previous=', $error->getPrevious()->getMessage(), '|';\n}\n$r = 'free';\necho $r, '/', $value, '|done';\n",
    'review-typed-slot-fiber19': b"<?php\nclass ReviewTypedFiberReceiver19 { public $x = 2; }\nclass ReviewTypedFiberHolder19 { public $child; public int $number; }\nclass ReviewTypedFiberChild19 { public function __destruct() {\n    echo 'A|';\n    Fiber::suspend();\n    echo 'back|';\n} }\n$r = 7;\n$fiber = new Fiber(function () use (&$r) {\n    $object = new ReviewTypedFiberReceiver19();\n    $value = new ReviewTypedFiberHolder19();\n    $value->number =& $r;\n    $value->child = new ReviewTypedFiberChild19();\n    foreach ($object as &$value) { echo $value, '|'; }\n});\n$fiber->start();\ntry { $r = 'bad'; echo 'bad|'; }\ncatch (TypeError $error) { echo 'type|'; }\n$fiber->resume();\n$r = 'free';\necho $r, '|done';\n",
    'review-typed-slot-child-before19': b"<?php\nclass ReviewTypedSlotReceiver19 { public $x = 2; public $y = 3; }\nclass ReviewTypedSlotHolder19 { public $child; public int $number; }\nclass ReviewTypedSlotChild19 { public function __destruct() {\n    echo 'A|';\n    try { $GLOBALS['r'] = 'bad'; echo 'free|'; }\n    catch (TypeError $error) { echo 'type|'; }\n} }\n$object = new ReviewTypedSlotReceiver19();\n$r = 7;\n$value = new ReviewTypedSlotHolder19();\n$value->number =& $r;\n$value->child = new ReviewTypedSlotChild19();\nforeach ($object as $key => &$value) { echo $key, '=', $value, '/', $r, '|'; }\n$r = 'after';\necho $r, '/', $value, '|done';\n",
    'review-typed-slot-child-after19': b"<?php\nclass ReviewTypedSlotReceiver19 { public $x = 2; public $y = 3; }\nclass ReviewTypedSlotHolder19 { public int $number; public $child; }\nclass ReviewTypedSlotChild19 { public function __destruct() {\n    echo 'A|';\n    try { $GLOBALS['r'] = 'bad'; echo 'free|'; }\n    catch (TypeError $error) { echo 'type|'; }\n} }\n$object = new ReviewTypedSlotReceiver19();\n$r = 7;\n$value = new ReviewTypedSlotHolder19();\n$value->child = new ReviewTypedSlotChild19();\n$value->number =& $r;\nforeach ($object as $key => &$value) { echo $key, '=', $value, '/', $r, '|'; }\n$r = 'after';\necho $r, '/', $value, '|done';\n",
    'review-descendant-typed-source19': b"<?php\nclass ReviewTypedDescendantReceiver19 { public $x = 2; public $y = 3; }\nclass ReviewTypedDescendantHolder19 { public int $number; }\nclass ReviewTypedDescendantChild19 { public function __destruct() {\n    echo 'B|';\n    try { $GLOBALS['r'] = 'bad'; echo 'bad|'; }\n    catch (TypeError $error) { echo 'type|'; }\n} }\n$object = new ReviewTypedDescendantReceiver19();\n$r = 7;\n$value = new ReviewTypedDescendantHolder19();\n$value->number =& $r;\n$dynamic = new ReviewTypedDescendantChild19();\n@$value->dynamic = $dynamic;\nunset($dynamic);\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\n$r = 'free';\necho $r, '/', $value, '|done';\n",
    'review-descendant-nested-typed-source19': b"<?php\nclass ReviewTypedDescendantReceiver19 { public $x = 2; public $y = 3; }\nclass ReviewTypedDescendantOuter19 { public $nested; }\nclass ReviewTypedDescendantHolder19 { public int $number; }\nclass ReviewTypedDescendantChild19 { public function __destruct() {\n    echo 'B|';\n    try { $GLOBALS['r'] = 'bad'; echo 'bad|'; }\n    catch (TypeError $error) { echo 'type|'; }\n} }\n$object = new ReviewTypedDescendantReceiver19();\n$r = 7;\n$typed = new ReviewTypedDescendantHolder19();\n$typed->number =& $r;\n$dynamic = new ReviewTypedDescendantChild19();\n@$typed->dynamic = $dynamic;\nunset($dynamic);\n$value = new ReviewTypedDescendantOuter19();\n$value->nested = $typed;\nunset($typed);\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\n$r = 'free';\necho $r, '/', $value, '|done';\n",
    'review-descendant-order19': b"<?php\nclass ReviewDescendantReceiver19 { public $x = 2; public $y = 3; }\nclass ReviewDescendantHolder19 { public $declared; }\nclass ReviewDescendantA19 { public function __destruct() { echo 'A|'; } }\nclass ReviewDescendantB19 { public function __destruct() { echo 'B|'; } }\n$object = new ReviewDescendantReceiver19();\n$value = new ReviewDescendantHolder19();\n$value->declared = new ReviewDescendantA19();\n$dynamic = new ReviewDescendantB19();\n@$value->dynamic = $dynamic;\nunset($dynamic);\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\necho $value, '|done';\n",
    'review-descendant-shared-parent19': b"<?php\nclass ReviewDescendantReceiver19 { public $x = 2; public $y = 3; }\nclass ReviewDescendantHolder19 { public $first; public $second; }\nclass ReviewDescendantA19 { public function __destruct() { echo 'A|'; } }\nclass ReviewDescendantB19 { public function __destruct() { echo 'B|'; } }\n$object = new ReviewDescendantReceiver19();\n$value = new ReviewDescendantHolder19();\n$value->first = new ReviewDescendantA19();\n$value->second = new ReviewDescendantB19();\n$held = $value;\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\necho $value, '|held|';\nunset($held);\necho 'done';\n",
    'review-descendant-shared-reference19': b"<?php\nclass ReviewDescendantReceiver19 { public $x = 2; public $y = 3; }\nclass ReviewDescendantHolder19 { public $first; public $second; }\nclass ReviewDescendantA19 { public function __destruct() { echo 'A|'; } }\nclass ReviewDescendantB19 { public function __destruct() { echo 'B|'; } }\n$object = new ReviewDescendantReceiver19();\n$child = new ReviewDescendantA19();\n$held =& $child;\n$value = new ReviewDescendantHolder19();\n$value->first =& $child;\n$value->second = new ReviewDescendantB19();\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\nunset($child, $held);\necho 'done';\n",
    'review-descendant-two-throws19': b"<?php\nclass ReviewDescendantReceiver19 { public $x = 2; public $y = 3; }\nclass ReviewDescendantHolder19 { public $first; public $second; }\nclass ReviewDescendantA19 { public function __destruct() {\n    echo 'A|'; unset($GLOBALS['object']->x); throw new Exception('A');\n} }\nclass ReviewDescendantB19 { public function __destruct() { echo 'B|'; throw new Exception('B'); } }\n$object = new ReviewDescendantReceiver19();\n$value = new ReviewDescendantHolder19();\n$value->first = new ReviewDescendantA19();\n$value->second = new ReviewDescendantB19();\ntry {\n    foreach ($object as $key => &$value) { echo 'unexpected|'; }\n} catch (Exception $error) { echo 'caught=', $error->getMessage(), '/previous=', $error->getPrevious()->getMessage(), '|'; }\necho $value, '|';\necho isset($object->x) ? 'present|' : 'absent|';\necho 'done';\n",
    'review-container-mutate-selected19': b"<?php\nclass ReviewContainerReceiver19 { public $x = 2; public $y = 3; }\n\nclass ReviewContainerA19 { public function __destruct() { echo 'A|'; } }\nclass ReviewContainerB19 { public function __destruct() {\n    echo 'B|'; $GLOBALS['object']->x = 9;\n} }\n\n$object = new ReviewContainerReceiver19();\n$value = [new ReviewContainerA19(), new ReviewContainerB19()];\n\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\necho $value, '|done';\n",
    'review-container-nested19': b"<?php\nclass ReviewContainerReceiver19 { public $x = 2; public $y = 3; }\n\nclass ReviewContainerA19 { public function __destruct() { echo 'A|'; } }\nclass ReviewContainerB19 { public function __destruct() { echo 'B|'; } }\n\nclass ReviewContainerC19 { public function __destruct() { echo 'C|'; } }\n\n$object = new ReviewContainerReceiver19();\n$value = [new ReviewContainerA19(), [new ReviewContainerB19(), new ReviewContainerC19()]];\n\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\necho $value, '|done';\n",
    'review-container-shared-outer19': b"<?php\nclass ReviewContainerReceiver19 { public $x = 2; public $y = 3; }\n\nclass ReviewContainerA19 { public function __destruct() { echo 'A|'; } }\nclass ReviewContainerB19 { public function __destruct() { echo 'B|'; } }\n\n$object = new ReviewContainerReceiver19();\n$value = [new ReviewContainerA19(), new ReviewContainerB19()];\n$held = $value;\n\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\necho $value, '|held|';\nunset($held);\necho 'done';\n",
    'review-container-shared-reference19': b"<?php\nclass ReviewContainerReceiver19 { public $x = 2; public $y = 3; }\n\nclass ReviewContainerA19 { public function __destruct() { echo 'A|'; } }\nclass ReviewContainerB19 { public function __destruct() { echo 'B|'; } }\n\n$object = new ReviewContainerReceiver19();\n$child = new ReviewContainerA19();\n$held =& $child;\n$value = [&$child, new ReviewContainerB19()];\n\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\nunset($child, $held);\necho 'done';\n",
    'review-container-two-throws19': b"<?php\nclass ReviewContainerReceiver19 { public $x = 2; public $y = 3; }\n\nclass ReviewContainerA19 { public function __destruct() { echo 'A|'; throw new Exception('A'); } }\nclass ReviewContainerB19 { public function __destruct() { echo 'B|'; throw new Exception('B'); } }\n\n$object = new ReviewContainerReceiver19();\n\n$value = [new ReviewContainerA19(), new ReviewContainerB19()];\ntry {\n    foreach ($object as $key => &$value) { echo 'unexpected|'; }\n} catch (Exception $error) { echo 'caught=', $error->getMessage(), '/previous=', $error->getPrevious()->getMessage(), '|'; }\necho $value, '|done';\n",
    'review-container-first-throw19': b"<?php\nclass ReviewContainerReceiver19 { public $x = 2; public $y = 3; }\n\nclass ReviewContainerA19 { public function __destruct() {\n    echo 'A|'; unset($GLOBALS['object']->x); throw new Exception('A');\n} }\nclass ReviewContainerB19 { public function __destruct() { echo 'B|'; } }\n\n$object = new ReviewContainerReceiver19();\n\n$value = [new ReviewContainerA19(), new ReviewContainerB19()];\ntry {\n    foreach ($object as $key => &$value) { echo 'unexpected|'; }\n} catch (Exception $error) { echo 'caught=', $error->getMessage(), '|'; }\necho $value, '|';\necho isset($object->x) ? 'present|' : 'absent|';\necho 'done';\n",
    'dynamic-reentry-table': b"<?php\nclass DynamicReentryTable18 {}\n$object = new DynamicReentryTable18();\nset_error_handler(function ($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\nforeach ($object as $key => $value) {\n    echo $key, '=', $value, '|';\n}\necho $object->x, '|done';\n",
    'dynamic-borrowed-rhs': b"<?php\nclass DynamicBorrowedRhs18 {}\n$object = new DynamicBorrowedRhs18();\n$rhs = 7;\nset_error_handler(function ($level, $message, $file, $line) {\n    echo 'warning|';\n    $GLOBALS['rhs'] = 9;\n    return true;\n});\necho ($object->x = $rhs), '|', $object->x, '|', $rhs, '|done';\n",
    'dynamic-computed-rhs': b"<?php\nclass DynamicComputedRhs18 {}\n$object = new DynamicComputedRhs18();\n$rhs = 7;\nset_error_handler(function ($level, $message, $file, $line) {\n    echo 'warning|';\n    $GLOBALS['rhs'] = 9;\n    return true;\n});\necho ($object->x = $rhs + 0), '|', $object->x, '|', $rhs, '|done';\n",
    'dynamic-reference-rhs-rebind': b"<?php\nclass DynamicReferenceRhsRebind18 {}\n$object = new DynamicReferenceRhsRebind18();\n$rhs = 7;\n$anchor =& $rhs;\n$replacement = 9;\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'warning|';\n    $GLOBALS['rhs'] =& $GLOBALS['replacement'];\n    $GLOBALS['anchor'] = 11;\n    return true;\n});\necho ($object->x = $rhs), '|', $object->x, '|', $rhs, '|', $anchor, '|done';\n",
    'dynamic-plain-rhs-promoted-reference': b"<?php\nclass DynamicPlainRhsPromotedReference18 {}\n$object = new DynamicPlainRhsPromotedReference18();\n$rhs = 7;\n$replacement = 9;\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'warning|';\n    $GLOBALS['rhs'] =& $GLOBALS['replacement'];\n    return true;\n});\necho ($object->x = $rhs), '|', $object->x, '|', $rhs, '|';\n$replacement = 13;\necho $object->x, '/', $rhs, '|done';\n",
    'dynamic-handler-throw-live': b"<?php\nclass DynamicThrowProbe16 {}\n$object = new DynamicThrowProbe16();\nset_error_handler(function ($level, $message, $file, $line) {\n    echo 'warning|';\n    throw new Exception('stop');\n});\ntry {\n    $object->x = 7;\n    echo 'returned|';\n} catch (Exception $error) {\n    echo isset($object->x) ? 'inserted|' : 'absent|';\n}\necho 'done';\n",
    'dynamic-handler-retires-destination': b"<?php\nclass DynamicRetirementProbe16 {\n    public function __destruct() { echo 'drop|'; }\n}\n$object = new DynamicRetirementProbe16();\nset_error_handler(function ($level, $message, $file, $line) {\n    echo 'warning|';\n    unset($GLOBALS['object']);\n    echo 'released|';\n    return true;\n});\ntry {\n    $object->x = 7;\n    echo 'returned|';\n} catch (Error $error) {\n    echo 'error|';\n}\necho 'done';\n",
    'dynamic-handler-retires-and-throws': b"<?php\nclass DynamicRetiredThrow18 { public function __destruct() { echo 'drop|'; } }\n$object = new DynamicRetiredThrow18();\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'warning|'; unset($GLOBALS['object']); echo 'released|';\n    throw new Exception('stop');\n});\ntry { $object->x = 7; echo 'returned|'; }\ncatch (Exception $error) { echo $error->getMessage(), '|'; }\ncatch (Error $error) { echo 'replacement|'; }\necho 'done';\n",
    'dynamic-computed-receiver': b"<?php\nclass DynamicComputedReceiver18 { public function __destruct() { echo 'drop|'; } }\n$object = new DynamicComputedReceiver18();\nfunction selected_receiver18() { return $GLOBALS['object']; }\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'warning|'; unset($GLOBALS['object']); echo 'released|'; return true;\n});\nselected_receiver18()->x = 7;\necho 'done';\n",
    'dynamic-promoted-rhs-used-result': b"<?php\nclass DynamicPlainRhsPromotedReference18 {}\n$object = new DynamicPlainRhsPromotedReference18();\n$rhs = 7;\n$replacement = 9;\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'warning|';\n    $GLOBALS['rhs'] =& $GLOBALS['replacement'];\n    return true;\n});\n$assigned = ($object->x = $rhs);\necho $assigned, '|', $object->x, '|', $rhs, '|';\n$replacement = 13;\necho $assigned, '/', $object->x, '/', $rhs, '|done';\n",
    'dynamic-duplicate-latest-write-unset': b"<?php\nclass DynamicDuplicateLatestWriteUnset18 {}\n$object = new DynamicDuplicateLatestWriteUnset18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$object->x = 9;\nforeach ($object as $key => $value) {\n    echo $key, '=', $value, '|';\n}\nunset($object->x);\nforeach ($object as $key => $value) {\n    echo $key, '=', $value, '|';\n}\necho $object->x, '|done';\n",
    'dynamic-retired-receiver-resurrects': b"<?php\nclass DynamicRetiredReceiverResurrects18 {\n    public function __destruct() {\n        echo 'drop|';\n        $GLOBALS['revived'] = $this;\n    }\n}\n$object = new DynamicRetiredReceiverResurrects18();\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'warning|';\n    unset($GLOBALS['object']);\n    echo 'released|';\n    return true;\n});\ntry {\n    $object->x = 7;\n    echo 'returned|';\n} catch (Error $error) {\n    echo 'error|';\n}\necho isset($revived->x) ? 'inserted|' : 'absent|';\necho 'done';\n",
    'dynamic-retired-receiver-resurrects-pending': b"<?php\nclass DynamicRetiredReceiverResurrectsPending18 {\n    public function __destruct() {\n        echo 'drop|';\n        $GLOBALS['revived'] = $this;\n    }\n}\n$object = new DynamicRetiredReceiverResurrectsPending18();\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'warning|';\n    unset($GLOBALS['object']);\n    echo 'released|';\n    throw new Exception('stop');\n});\ntry {\n    $object->x = 7;\n    echo 'returned|';\n} catch (Exception $error) {\n    echo $error->getMessage(), '|';\n} catch (Error $error) {\n    echo 'replacement|';\n}\necho isset($revived->x) ? 'inserted|' : 'absent|';\necho 'done';\n",
    'dynamic-unused-computed-receiver-rhs-cleanup': b"<?php\nclass DynamicUnusedComputedReceiverCleanup18 {\n    public function __destruct() {\n        echo 'receiver|';\n        unset($this->x);\n        echo 'receiver-end|';\n    }\n}\nclass DynamicUnusedComputedRhsCleanup18 {\n    public function __destruct() { echo 'rhs|'; }\n}\nfunction selected_cleanup_receiver18() { return new DynamicUnusedComputedReceiverCleanup18(); }\nfunction selected_cleanup_rhs18() { return new DynamicUnusedComputedRhsCleanup18(); }\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'warning|';\n    return true;\n});\nselected_cleanup_receiver18()->x = selected_cleanup_rhs18();\necho 'done';\n",
    'dynamic-used-computed-receiver-rhs-cleanup': b"<?php\nclass DynamicUnusedComputedReceiverCleanup18 {\n    public function __destruct() {\n        echo 'receiver|';\n        unset($this->x);\n        echo 'receiver-end|';\n    }\n}\nclass DynamicUnusedComputedRhsCleanup18 {\n    public function __destruct() { echo 'rhs|'; }\n}\nfunction selected_cleanup_receiver18() { return new DynamicUnusedComputedReceiverCleanup18(); }\nfunction selected_cleanup_rhs18() { return new DynamicUnusedComputedRhsCleanup18(); }\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'warning|';\n    return true;\n});\n$assigned = (selected_cleanup_receiver18()->x = selected_cleanup_rhs18());\necho 'retained|';\nunset($assigned);\necho 'done';\n",
    'dynamic-warning-gc-protected-resurrection': b"<?php\nclass DynamicWarningGcProtectedResurrection18 {\n    public function __destruct() {\n        echo 'drop|';\n        $GLOBALS['revived'] = $this;\n    }\n}\n$object = new DynamicWarningGcProtectedResurrection18();\n$weak = WeakReference::create($object);\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'warning|';\n    unset($GLOBALS['object']);\n    echo $GLOBALS['weak']->get() !== null ? 'held|' : 'gone|';\n    echo gc_collect_cycles(), '|';\n    return true;\n});\ntry {\n    $object->x = 7;\n    echo 'returned|';\n} catch (Error $error) {\n    echo 'error|';\n}\necho isset($revived->x) ? 'inserted|' : 'absent|';\necho $weak->get() === $revived ? 'same|' : 'different|';\necho 'done';\n",
    'dynamic-reentry-reference-foreach': b"<?php\nclass DynamicReentryReferenceForeach18 {}\n$object = new DynamicReentryReferenceForeach18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    $value = $value + 10;\n}\nunset($value);\nforeach ($object as $key => $value) {\n    echo $key, '=', $value, '|';\n}\necho $object->x, '|done';\n",
    'duplicate-reference-foreach-escaped-first18': b"<?php\nclass DuplicateReferenceForeachEscapedFirst18 {}\n$object = new DuplicateReferenceForeachEscapedFirst18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$first = null;\n$index = 0;\nforeach ($object as $key => &$value) {\n    if ($index === 0) { $first =& $value; }\n    $index = $index + 1;\n}\nunset($value);\necho $first, '/', $object->x, '|';\n$object->x = 9;\necho $first, '/', $object->x, '|';\n$first = 12;\nforeach ($object as $key => $value) { echo $key, '=', $value, '|'; }\nunset($object->x);\necho $first, '/', $object->x, '|';\n$first = 14;\necho $object->x, '|done';\n",
    'duplicate-reference-foreach-delete-next18': b"<?php\nclass DuplicateReferenceForeachDeleteNext18 {}\n$object = new DuplicateReferenceForeachDeleteNext18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$first = null;\n$index = 0;\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    if ($index === 0) {\n        $first =& $value;\n        unset($object->x);\n        $value = 12;\n    }\n    $index = $index + 1;\n}\nunset($value);\necho $index, '/', $first, '/', $object->x, '|done';\n",
    'duplicate-reference-foreach-binding-destructor18': b"<?php\nclass DuplicateReferenceForeachBindingObject18 {}\nclass DuplicateReferenceForeachBindingDestructor18 {\n    public function __destruct() {\n        echo 'drop|';\n        unset($GLOBALS['object']->x);\n        unset($GLOBALS['object']->x);\n    }\n}\n$object = new DuplicateReferenceForeachBindingObject18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$value = new DuplicateReferenceForeachBindingDestructor18();\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    $value = 12;\n}\necho $value, '/';\necho isset($object->x) ? 'present|' : 'absent|';\nunset($value);\necho 'done';\n",
    'duplicate-reference-foreach-readonly18': b"<?php\nclass DuplicateReferenceForeachReadonly18 {\n    public readonly int $locked;\n    public function __construct() { $this->locked = 3; }\n}\n$object = new DuplicateReferenceForeachReadonly18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\ntry {\n    foreach ($object as $key => &$value) { echo 'unexpected|'; }\n} catch (Error $error) {\n    echo 'readonly|';\n}\nforeach ($object as $key => $value) { echo $key, '=', $value, '|'; }\necho 'done';\n",
    'duplicate-reference-foreach-typed-setter18': b"<?php\nclass DuplicateReferenceForeachTypedSetter18 {\n    public protected(set) int $sealed = 3;\n}\n$object = new DuplicateReferenceForeachTypedSetter18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\nforeach ($object as $key => &$value) {\n    if ($key === 'sealed') {\n        try { $value = 'bad'; } catch (TypeError $error) { echo 'typed|'; }\n    }\n    $value = $value + 10;\n}\nunset($value);\nforeach ($object as $key => $value) { echo $key, '=', $value, '|'; }\necho $object->sealed, '/', $object->x, '|done';\n",
    'duplicate-reference-foreach-binding-observation18': b"<?php\nclass DuplicateReferenceForeachBindingObservationObject18 {}\nclass DuplicateReferenceForeachBindingObservationDestructor18 {\n    public function __destruct() {\n        echo $GLOBALS['value'] instanceof DuplicateReferenceForeachBindingObservationDestructor18 ? 'old|' : 'new|';\n        unset($GLOBALS['object']->x);\n        unset($GLOBALS['object']->x);\n    }\n}\n$object = new DuplicateReferenceForeachBindingObservationObject18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$value = new DuplicateReferenceForeachBindingObservationDestructor18();\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    $value = 12;\n}\necho $value, '/';\necho isset($object->x) ? 'present|' : 'absent|';\nunset($value);\necho 'done';\n",
    'duplicate-reference-foreach-binding-throw18': b"<?php\nclass DuplicateReferenceForeachBindingThrowObject18 {}\nclass DuplicateReferenceForeachBindingThrowDestructor18 {\n    public function __destruct() {\n        echo $GLOBALS['value'] instanceof DuplicateReferenceForeachBindingThrowDestructor18 ? 'old|' : 'new|';\n        unset($GLOBALS['object']->x);\n        unset($GLOBALS['object']->x);\n        throw new Exception('bind-stop');\n    }\n}\n$object = new DuplicateReferenceForeachBindingThrowObject18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$value = new DuplicateReferenceForeachBindingThrowDestructor18();\ntry {\n    foreach ($object as $key => &$value) { echo 'unexpected|'; }\n} catch (Exception $error) {\n    echo 'caught=', $value, '|', $error->getMessage(), '|';\n}\necho isset($object->x) ? 'present|' : 'absent|';\nunset($value);\necho 'done';\n",
    'duplicate-reference-foreach-shared-prior-wrapper18': b"<?php\nclass DuplicateReferenceForeachSharedPriorWrapper18 {}\nclass DuplicateReferenceForeachSharedPriorWrapperValue18 {\n    public function __destruct() { echo 'drop|'; }\n}\n$object = new DuplicateReferenceForeachSharedPriorWrapper18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$anchor = new DuplicateReferenceForeachSharedPriorWrapperValue18();\n$value =& $anchor;\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\nunset($value);\necho 'retained|';\nunset($anchor);\necho 'done';\n",
    'duplicate-reference-foreach-binding-escape18': b"<?php\nclass DuplicateReferenceForeachBindingEscapeObject18 {}\nclass DuplicateReferenceForeachBindingEscapeDestructor18 {\n    public function __destruct() {\n        echo $GLOBALS['value'] instanceof DuplicateReferenceForeachBindingEscapeDestructor18 ? 'old|' : 'new|';\n        $GLOBALS['saved'] = $GLOBALS['value'];\n        unset($GLOBALS['object']->x);\n        unset($GLOBALS['object']->x);\n    }\n}\n$object = new DuplicateReferenceForeachBindingEscapeObject18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$value = new DuplicateReferenceForeachBindingEscapeDestructor18();\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    $value = 12;\n}\necho $saved instanceof DuplicateReferenceForeachBindingEscapeDestructor18 ? 'saved|' : 'lost|';\necho $value, '/';\necho isset($object->x) ? 'present|' : 'absent|';\nunset($value, $saved);\necho 'done';\n",
    'duplicate-reference-foreach-prior-scalar-array18': b"<?php\nclass DuplicateReferenceForeachPriorScalarArray18 {\n    public $x = 2;\n}\nclass DuplicateReferenceForeachUnrelatedDestructor18 {\n    public function __destruct() { echo 'unexpected|'; }\n}\n$object = new DuplicateReferenceForeachPriorScalarArray18();\n$value = [1, 2];\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n}\necho $value, '|done';\n",
    'duplicate-reference-foreach-prior-singleton-shared-payload18': b"<?php\nclass DuplicateReferenceForeachPriorSingletonObject18 {\n    public $x = 2;\n}\nclass DuplicateReferenceForeachPriorSingletonValue18 {\n    public function __destruct() { echo 'drop|'; }\n}\n$object = new DuplicateReferenceForeachPriorSingletonObject18();\n$anchor = new DuplicateReferenceForeachPriorSingletonValue18();\n$value = $anchor;\n$alias =& $value;\nunset($alias);\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n}\nunset($value);\necho 'retained|';\nunset($anchor);\necho 'done';\n",
    'reference-foreach-receiver-rebind18': b"<?php\nclass PreviousReceiver18 {\n    public $x = 1;\n    public $y = 2;\n    public function __destruct() { echo 'receiver-drop|'; }\n}\nclass NextReceiver18 {\n    public $z = 3;\n    public $w = 4;\n}\n$object = new PreviousReceiver18();\n$value = 0;\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    if ($key === 'x') { $object = new NextReceiver18(); }\n}\necho 'done';\n",
    'reference-foreach-receiver-alias-write18': b"<?php\nclass PreviousReceiverControl18 {\n    public $x = 1;\n    public $y = 2;\n    public function __destruct() { echo 'receiver-drop|'; }\n}\nclass NextReceiverControl18 {\n    public $z = 3;\n    public $w = 4;\n}\n$object = new PreviousReceiverControl18();\n$alias =& $object;\n$value = 0;\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    if ($key === 'x') { $alias = new NextReceiverControl18(); }\n}\necho 'done';\n",
    'reference-foreach-receiver-unset-recreate18': b"<?php\nclass PreviousReceiverControl18 {\n    public $x = 1;\n    public $y = 2;\n    public function __destruct() { echo 'receiver-drop|'; }\n}\nclass NextReceiverControl18 {\n    public $z = 3;\n    public $w = 4;\n}\n$object = new PreviousReceiverControl18();\n$value = 0;\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    if ($key === 'x') {\n        unset($object);\n        $object = new NextReceiverControl18();\n    }\n}\necho 'done';\n",
    'reference-foreach-receiver-object-array18': b"<?php\nclass PreviousReceiverControl18 {\n    public $x = 1;\n    public $y = 2;\n    public function __destruct() { echo 'receiver-drop|'; }\n}\nclass NextReceiverControl18 {\n    public $z = 3;\n    public $w = 4;\n}\n$object = new PreviousReceiverControl18();\n$value = 0;\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    if ($key === 'x') { $object = ['z' => 3, 'w' => 4]; }\n}\necho 'done';\n",
    'reference-foreach-receiver-object-scalar18': b"<?php\nclass PreviousReceiverControl18 {\n    public $x = 1;\n    public $y = 2;\n    public function __destruct() { echo 'receiver-drop|'; }\n}\nclass NextReceiverControl18 {\n    public $z = 3;\n    public $w = 4;\n}\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'fetch-warning|';\n    return true;\n});\n$object = new PreviousReceiverControl18();\n$value = 0;\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    if ($key === 'x') { $object = 7; }\n}\necho 'done';\n",
    'reference-foreach-receiver-array-object18': b"<?php\nclass ArrayNextReceiverControl18 {\n    public $z = 3;\n    public $w = 4;\n}\n$object = ['a' => 1, 'b' => 2];\n$value = 0;\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    if ($key === 'a') { $object = new ArrayNextReceiverControl18(); }\n}\necho 'done';\n",
    'reference-foreach-receiver-cleanup-rebind18': b"<?php\nclass CallbackPreviousReceiver18 {\n    public $x = 1;\n    public $y = 2;\n    public function __destruct() { echo 'receiver-drop|'; }\n}\nclass CallbackNextReceiver18 {\n    public $z = 3;\n    public $w = 4;\n}\nclass CallbackPreviousValue18 {\n    public function __destruct() {\n        echo $GLOBALS['value'] instanceof CallbackPreviousValue18 ? 'old|' : 'new|';\n        $GLOBALS['object'] = new CallbackNextReceiver18();\n    }\n}\n$object = new CallbackPreviousReceiver18();\n$value = new CallbackPreviousValue18();\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n}\necho 'done';\n",
    'reference-foreach-late-shared-table18': b"<?php\nclass SharedTablePreviousReceiver18 { public $x = 1; }\n$array = [];\n$array['z'] = 3;\n$replacement = (object) $array;\n$object = new SharedTablePreviousReceiver18();\n$value = 0;\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    if ($key === 'x') { $object = $replacement; }\n    $value = $value + 10;\n}\nunset($value);\necho $array['z'], '/', $replacement->z, '|done';\n",
    'reference-foreach-scalar-handler-retirement18': b"<?php\nclass ScalarWarningPreviousReceiver18 {\n    public $x = 1;\n    public $y = 2;\n    public function __destruct() { echo 'receiver-drop|'; }\n}\nclass ScalarWarningReplacementReceiver18 {\n    public $z = 3;\n    public function __destruct() { echo 'replacement-drop|'; }\n}\nset_error_handler(function($level, $message, $file, $line) {\n    echo $level === 2 ? 'level|' : 'wrong-level|';\n    echo $message === 'foreach() argument must be of type array|object, int given' ? 'captured|' : 'wrong-message|';\n    $GLOBALS['object'] = new ScalarWarningReplacementReceiver18();\n    unset($GLOBALS['object']);\n    return true;\n});\n$object = new ScalarWarningPreviousReceiver18();\n$value = 0;\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    if ($key === 'x') { $object = 7; }\n}\necho $value, '/';\necho isset($object) ? 'present|' : 'absent|';\necho 'done';\n",
    'reference-foreach-scalar-handler-throw18': b"<?php\nclass ScalarWarningThrowReceiver18 {\n    public $x = 1;\n    public $y = 2;\n    public function __destruct() { echo 'receiver-drop|'; }\n}\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'fetch-warning|';\n    throw new Exception('scalar-stop');\n});\n$object = new ScalarWarningThrowReceiver18();\n$value = 0;\ntry {\n    foreach ($object as $key => &$value) {\n        echo $key, '=', $value, '|';\n        if ($key === 'x') { $object = 7; }\n    }\n} catch (Exception $error) {\n    echo 'caught=', $error->getMessage(), '|';\n}\necho $value, '|done';\n",
    'reference-foreach-invalid-key-unset-receiver-key-observer18': b'<?php\n$object = (object) ["\\0" => 2, \'x\' => 3];\nset_error_handler(function($level, $message, $file, $line) {\n    echo \'notice|\';\n    unset($GLOBALS[\'object\']);\n    return true;\n});\n$value = 0;\nforeach ($object as $key => &$value) {\n    echo ($key === "\\0" ? \'nul\' : $key), \'=\', $value, \'|\';\n}\necho $value, \'|done\';\n',
    'reference-foreach-invalid-key-retained-table-key-observer18': b'<?php\n$object = (object) ["\\0" => 2];\nset_error_handler(function($level, $message, $file, $line) {\n    echo \'notice|\';\n    $GLOBALS[\'held\'] = (array) $GLOBALS[\'object\'];\n    $GLOBALS[\'object\'] = (object) [\'z\' => 4];\n    return true;\n});\n$value = 0;\nforeach ($object as $key => &$value) {\n    echo ($key === "\\0" ? \'nul\' : $key), \'=\', $value, \'|\';\n    $value = $value + 10;\n}\nunset($value);\necho $held["\\0"], \'/\', $object->z, \'|done\';\n',
    'duplicate-reference-foreach-binding-gc18': b"<?php\nclass DuplicateReferenceForeachBindingObservationObject18 {}\nclass DuplicateReferenceForeachBindingObservationDestructor18 {\n    public function __destruct() {\n        echo $GLOBALS['value'] instanceof DuplicateReferenceForeachBindingObservationDestructor18 ? 'old|' : 'new|';\n        unset($GLOBALS['object']->x);\n        unset($GLOBALS['object']->x);\n        echo gc_collect_cycles(), '|';\n    }\n}\n$object = new DuplicateReferenceForeachBindingObservationObject18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$value = new DuplicateReferenceForeachBindingObservationDestructor18();\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    $value = 12;\n}\necho $value, '/';\necho isset($object->x) ? 'present|' : 'absent|';\nunset($value);\necho 'done';\n",
    'review-prior-wrapper-live-read19': b"<?php\nclass WrapperReceiver19 { public $x = 2; public $y = 3; }\nclass WrapperOld19 { public function __destruct() {\n    echo $GLOBALS['value'] instanceof WrapperOld19 ? 'old|' : 'new|';\n    unset($GLOBALS['object']->x);\n} }\n$object = new WrapperReceiver19();\n$value = new WrapperOld19(); $alias =& $value; unset($alias);\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|'; $value = 12;\n}\necho $value, '/'; echo isset($object->x) ? 'present|' : 'absent|';\necho 'done';\n",
    'review-prior-wrapper-live-throw19': b"<?php\nclass WrapperReceiver19 { public $x = 2; public $y = 3; }\nclass WrapperOld19 { public function __destruct() {\n    echo $GLOBALS['value'] instanceof WrapperOld19 ? 'old|' : 'new|';\n    unset($GLOBALS['object']->x); throw new Exception('A');\n} }\n$object = new WrapperReceiver19();\n$value = new WrapperOld19(); $alias =& $value; unset($alias);\ntry {\n    foreach ($object as $key => &$value) { echo 'unexpected|'; }\n} catch (Exception $error) { echo 'caught=', $error->getMessage(), '|'; }\necho $value, '/'; echo isset($object->x) ? 'present|' : 'absent|';\n$value = 12; echo $value, '/', $object->y, '|done';\n",
    'review-prior-wrapper-array-throws19': b"<?php\nclass WrapperReceiver19 { public $x = 2; public $y = 3; }\nclass WrapperChildA19 { public function __destruct() {\n    echo 'A|'; unset($GLOBALS['object']->x); throw new Exception('A');\n} }\nclass WrapperChildB19 { public function __destruct() {\n    echo 'B|'; throw new Exception('B');\n} }\n$object = new WrapperReceiver19();\n$value = [new WrapperChildA19(), new WrapperChildB19()];\n$alias =& $value; unset($alias);\ntry {\n    foreach ($object as $key => &$value) { echo 'unexpected|'; }\n} catch (Exception $error) {\n    echo 'caught=', $error->getMessage(), '/previous=', $error->getPrevious()->getMessage(), '|';\n}\necho $value, '/'; echo isset($object->x) ? 'present|' : 'absent|';\necho 'done';\n",
    'review-prior-wrapper-shared19': b"<?php\nclass WrapperReceiver19 { public $x = 2; public $y = 3; }\nclass WrapperOld19 { public function __destruct() {\n    echo $GLOBALS['value'] instanceof WrapperOld19 ? 'old|' : 'new|';\n} }\n$object = new WrapperReceiver19();\n$value = new WrapperOld19(); $alias =& $value;\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\necho 'held|'; unset($alias); echo 'done';\n",
    'review-prior-wrapper-typed-child19': b"<?php\nclass WrapperReceiver19 { public $x = 2; public $y = 3; }\nclass WrapperHolder19 { public $child; public int $number; }\nclass WrapperTypedChild19 { public function __destruct() {\n    echo 'B|';\n    try { $GLOBALS['r'] = 'bad'; echo 'free|'; }\n    catch (TypeError $error) { echo 'type|'; }\n} }\n$object = new WrapperReceiver19(); $r = 7;\n$value = new WrapperHolder19();\n$value->number =& $r; $value->child = new WrapperTypedChild19();\n$alias =& $value; unset($alias);\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\n$r = 'free'; echo $r, '|done';\n",
    'review-instance-storage-metadata19': b"<?php\nclass InstanceStorageReceiver359 { public $x = 2; }\nclass InstanceStorageParent359 { public $leaf; }\nclass InstanceStorageLeaf359 { public function __destruct() {\n    echo 'C|', get_class($GLOBALS['value']), '/', (int) ($GLOBALS['wp']->get() === null), '|';\n} }\n$object = new InstanceStorageReceiver359();\n$value = new InstanceStorageParent359(); $value->leaf = new InstanceStorageLeaf359();\n$wp = WeakReference::create($value);\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\necho $value, '/', (int) ($wp->get() === null), '|done';\n",
    'review-instance-storage-typed-order19': b"<?php\nclass InstanceStorageReceiver359 { public $x = 2; }\nclass InstanceStorageParent359 { public $first; public int $number; public $second; }\nclass InstanceStorageFirst359 { public function __destruct() {\n    echo 'A|', get_class($GLOBALS['value']), '/', (int) ($GLOBALS['wp']->get() === null), '|';\n    try { $GLOBALS['r'] = 'bad'; echo 'free|'; }\n    catch (TypeError $error) { echo 'type|'; }\n} }\nclass InstanceStorageSecond359 { public function __destruct() {\n    echo 'B|', get_class($GLOBALS['value']), '/', (int) ($GLOBALS['wp']->get() === null), '|';\n    $GLOBALS['r'] = 'free'; echo $GLOBALS['r'], '|';\n} }\n$object = new InstanceStorageReceiver359(); $r = 7;\n$value = new InstanceStorageParent359();\n$value->number =& $r; $value->first = new InstanceStorageFirst359(); $value->second = new InstanceStorageSecond359();\n$wp = WeakReference::create($value);\nforeach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\necho $r, '/', (int) ($wp->get() === null), '|done';\n",
    'review-instance-storage-typed-throws19': b"<?php\nclass InstanceStorageReceiver359 { public $x = 2; }\nclass InstanceStorageParent359 { public $first; public int $number; public $second; }\nclass InstanceStorageFirst359 { public function __destruct() {\n    echo 'A|', get_class($GLOBALS['value']), '/', (int) ($GLOBALS['wp']->get() === null), '|';\n    try { $GLOBALS['r'] = 'bad'; echo 'free|'; }\n    catch (TypeError $error) { echo 'type|'; }\n    throw new Exception('A');\n} }\nclass InstanceStorageSecond359 { public function __destruct() {\n    echo 'B|', get_class($GLOBALS['value']), '/', (int) ($GLOBALS['wp']->get() === null), '|';\n    $GLOBALS['r'] = 'free'; echo $GLOBALS['r'], '|';\n    throw new Exception('B');\n} }\n$object = new InstanceStorageReceiver359(); $r = 7;\n$value = new InstanceStorageParent359();\n$value->number =& $r; $value->first = new InstanceStorageFirst359(); $value->second = new InstanceStorageSecond359();\n$wp = WeakReference::create($value);\ntry { foreach ($object as $key => &$value) { echo 'unexpected|'; } }\ncatch (Exception $error) { echo 'caught=', $error->getMessage(), '/previous=', $error->getPrevious()->getMessage(), '|'; }\n$value = 12;\necho $value, '/', $object->x, '/', $r, '/', (int) ($wp->get() === null), '|done';\n",
    'review-instance-storage-generator-return19': b'<?php\nclass ReturnLeaf355{function __destruct(){global $wg;echo "L",get_class($wg->get()->getReturn());}}\nclass ReturnParent355{public $leaf;}\nfunction returnParent355($value){yield 1;return $value;}\n$value=new ReturnParent355;$value->leaf=new ReturnLeaf355;\n$g=returnParent355($value);unset($value);$g->current();$g->next();\n$wg=WeakReference::create($g);echo "C|";unset($g);echo "|",(int)($wg->get()===null);\n',
    'review-instance-storage-fiber19': b"<?php\nclass InstanceStorageReceiver359 { public $x = 2; }\nclass InstanceStorageParent359 { public $leaf; public int $number; }\nclass InstanceStorageLeaf359 { public function __destruct() {\n    echo 'C|'; Fiber::suspend('paused'); echo 'resume|';\n} }\n$r = 7;\n$fiber = new Fiber(function() use (&$r) {\n    $object = new InstanceStorageReceiver359();\n    $value = new InstanceStorageParent359();\n    $value->leaf = new InstanceStorageLeaf359(); $value->number =& $r;\n    $GLOBALS['wp'] = WeakReference::create($value);\n    foreach ($object as $key => &$value) { echo $key, '=', $value, '|'; }\n});\necho $fiber->start(), '|', (int) ($wp->get() === null), '|';\ntry { $r = 'bad'; echo 'free|'; }\ncatch (TypeError $error) { echo 'type|'; }\n$fiber->resume(); $r = 'free';\necho $r, '/', (int) ($wp->get() === null), '|done';\n",
}

EXPECTED = {
    'review-instance-future-unset-dynamic-inherited19': 'C|A/1|Error:Typed property FutureUnsetBase359::$number must not be accessed before initialization|x=2|12/12/1|done',
    'review-instance-future-unset-visibility-alias19': 'C|A/free|denied=Cannot access private property FutureUnsetVisibilityParent359::$secret|uninit=Typed property FutureUnsetVisibilityParent359::$number must not be accessed before initialization|x=2|12/12/free|done',
    'review-instance-future-unset-pending19': 'C|A|B/FutureUnsetPendingParent359/1|Exception/B/previous=Error:Typed property FutureUnsetPendingParent359::$number must not be accessed before initialization|12/12/1|done',
    'review-instance-future-initial-inherited19': 'C|A/1|Error:Typed property FutureInitialBase359::$number must not be accessed before initialization|x=2|12/12/1|done',
    'review-instance-future-initial-visibility19': 'C|A|denied=Cannot access private property FutureInitialVisibilityParent359::$secret|uninit=Typed property FutureInitialVisibilityParent359::$number must not be accessed before initialization|x=2|12/12|done',
    'review-instance-future-initial-pending19': 'C|A|B/FutureInitialPendingParent359/1|Exception/B/previous=Error:Typed property FutureInitialPendingParent359::$number must not be accessed before initialization|12/12/1|done',
    'review-instance-future-heap-object19': 'C|A|FutureHeapLeaf359|kept|x=2|1/1|B/1|1|done',
    'review-instance-future-heap-alias19': 'C|A|FutureAliasHeapLeaf359/1|x=2|free/1/1|B/1|1|done',
    'review-instance-future-heap-array-cow19': 'C|A|old/new|x=2|new/1/1|B/1|1|done',
    'review-instance-future-scalar19': 'C|7/future/1/1|x=2|12/1|done',
    'review-instance-future-typed-alias19': 'C|9|type|x=2|free/2|done',
    'review-instance-future-visibility19': 'C|7|denied|x=2|12|done',
    'review-stdinstance-storage-table-reinsert-throws19': "C|B/stdClass/1|A/stdClass/1|caught=A/previous=B|12/12/1|done",
    'review-stdinstance-storage-generator-return19': "C|LstdClass/1|1",
    'review-stdinstance-storage-metadata19': "C|stdClass/1|x=2|2/1|done",
    'review-stdinstance-storage-reinsert-throws19': "C|B/stdClass/1|A/stdClass/1|caught=A/previous=B|12/12/1|done",
    'review-stdinstance-storage-shared-table19': "C|1|held|L/1|done",
    'review-generator-typed-slot-fiber19': "A|type|back|closed|free|done",
    'review-generator-typed-slot-before19': "A|type|after|done",
    'review-generator-typed-slot-after19': "A|free|after|done",
    'review-generator-typed-slot-throw19': "A|B|type|caught=B/previous=A|free|done",
    'review-typed-slot-two-sources-throw19': 'A|B|type|caught=B/previous=A|free/2|done',
    'review-typed-slot-fiber19': 'A|type|back|2|free|done',
    'review-typed-slot-child-before19': 'A|type|x=2/7|y=3/7|after/3|done',
    'review-typed-slot-child-after19': 'A|free|x=2/bad|y=3/bad|after/3|done',
    'review-descendant-typed-source19': 'B|type|x=2|y=3|free/3|done',
    'review-descendant-nested-typed-source19': 'B|type|x=2|y=3|free/3|done',
    'review-descendant-order19': 'B|A|x=2|y=3|3|done',
    'review-descendant-shared-parent19': 'x=2|y=3|3|held|A|B|done',
    'review-descendant-shared-reference19': 'B|x=2|y=3|A|done',
    'review-descendant-two-throws19': 'A|B|caught=B/previous=A|2|absent|done',
    'review-container-mutate-selected19': 'A|B|x=9|y=3|3|done',
    'review-container-nested19': 'A|B|C|x=2|y=3|3|done',
    'review-container-shared-outer19': 'x=2|y=3|3|held|A|B|done',
    'review-container-shared-reference19': 'B|x=2|y=3|A|done',
    'review-container-two-throws19': 'A|B|caught=B/previous=A|2|done',
    'review-container-first-throw19': 'A|B|caught=A|2|absent|done',
    'dynamic-reentry-table': 'warning|x=2|x=7|7|done',
    'dynamic-borrowed-rhs': 'warning|9|9|9|done',
    'dynamic-computed-rhs': 'warning|7|7|9|done',
    'dynamic-reference-rhs-rebind': 'warning|11|11|9|11|done',
    'dynamic-plain-rhs-promoted-reference': 'warning|9|9|9|13/13|done',
    'dynamic-handler-throw-live': 'warning|inserted|done',
    'dynamic-handler-retires-destination': 'warning|released|drop|error|done',
    'dynamic-handler-retires-and-throws': 'warning|released|drop|stop|done',
    'dynamic-computed-receiver': 'warning|released|drop|done',
    'dynamic-promoted-rhs-used-result': 'warning|9|9|9|9/13/13|done',
    'dynamic-duplicate-latest-write-unset': 'warning|x=2|x=9|x=2|2|done',
    'dynamic-retired-receiver-resurrects': 'warning|released|drop|error|absent|done',
    'dynamic-retired-receiver-resurrects-pending': 'warning|released|drop|stop|absent|done',
    'dynamic-unused-computed-receiver-rhs-cleanup': 'warning|receiver|rhs|receiver-end|done',
    'dynamic-used-computed-receiver-rhs-cleanup': 'warning|receiver|receiver-end|retained|rhs|done',
    'dynamic-warning-gc-protected-resurrection': 'warning|held|0|drop|error|absent|same|done',
    'dynamic-reentry-reference-foreach': 'warning|x=2|x=7|x=12|x=17|17|done',
    'duplicate-reference-foreach-escaped-first18': 'warning|2/7|2/9|x=12|x=9|12/12|14|done',
    'duplicate-reference-foreach-delete-next18': 'warning|x=2|1/12/12|done',
    'duplicate-reference-foreach-binding-destructor18': 'warning|drop|x=2|12/absent|done',
    'duplicate-reference-foreach-readonly18': 'warning|readonly|locked=3|x=2|x=7|done',
    'duplicate-reference-foreach-typed-setter18': 'warning|typed|sealed=13|x=12|x=17|13/17|done',
    'duplicate-reference-foreach-binding-observation18': 'warning|old|x=2|12/absent|done',
    'duplicate-reference-foreach-binding-throw18': 'warning|old|caught=2|bind-stop|absent|done',
    'duplicate-reference-foreach-shared-prior-wrapper18': 'warning|x=2|x=7|retained|drop|done',
    'duplicate-reference-foreach-binding-escape18': 'warning|old|x=2|saved|12/absent|done',
    'duplicate-reference-foreach-prior-scalar-array18': 'x=2|2|done',
    'duplicate-reference-foreach-prior-singleton-shared-payload18': 'x=2|retained|drop|done',
    'reference-foreach-receiver-rebind18': 'x=1|receiver-drop|z=3|w=4|done',
    'reference-foreach-receiver-alias-write18': 'x=1|receiver-drop|z=3|w=4|done',
    'reference-foreach-receiver-unset-recreate18': 'x=1|y=2|receiver-drop|done',
    'reference-foreach-receiver-object-array18': 'x=1|receiver-drop|z=3|w=4|done',
    'reference-foreach-receiver-object-scalar18': 'x=1|receiver-drop|fetch-warning|done',
    'reference-foreach-receiver-array-object18': 'a=1|z=3|w=4|done',
    'reference-foreach-receiver-cleanup-rebind18': 'old|receiver-drop|x=1|z=3|w=4|done',
    'reference-foreach-late-shared-table18': 'x=1|z=3|13/13|done',
    'reference-foreach-scalar-handler-retirement18': 'x=1|receiver-drop|level|captured|replacement-drop|1/absent|done',
    'reference-foreach-scalar-handler-throw18': 'x=1|receiver-drop|fetch-warning|caught=scalar-stop|1|done',
    'reference-foreach-invalid-key-unset-receiver-key-observer18': 'notice|nul=2|x=3|3|done',
    'reference-foreach-invalid-key-retained-table-key-observer18': 'notice|nul=2|z=4|12/14|done',
    'duplicate-reference-foreach-binding-gc18': 'warning|old|0|x=2|12/absent|done',
    'review-prior-wrapper-live-read19': 'old|x=2|y=3|12/absent|done',
    'review-prior-wrapper-live-throw19': 'old|caught=A|2/absent|12/3|done',
    'review-prior-wrapper-array-throws19': 'A|B|caught=B/previous=A|2/absent|done',
    'review-prior-wrapper-shared19': 'x=2|y=3|held|new|done',
    'review-prior-wrapper-typed-child19': 'B|type|x=2|y=3|free|done',
    'review-instance-storage-metadata19': 'C|InstanceStorageParent359/1|x=2|2/1|done',
    'review-instance-storage-typed-order19': 'A|InstanceStorageParent359/1|type|B|InstanceStorageParent359/1|free|x=2|free/1|done',
    'review-instance-storage-typed-throws19': 'A|InstanceStorageParent359/1|type|B|InstanceStorageParent359/1|free|caught=B/previous=A|12/12/free/1|done',
    'review-instance-storage-generator-return19': 'C|LReturnParent355|1',
    'review-instance-storage-fiber19': 'C|paused|1|type|resume|x=2|free/1|done',
}

BOUNDARIES = {
    'dynamic-handler-exit-shutdown': (
        b"<?php\nclass DynamicHandlerExitShutdown18 {}\n$object = new DynamicHandlerExitShutdown18();\nregister_shutdown_function(function() use ($object) {\n    echo isset($object->x) ? 'inserted|' : 'absent|';\n});\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'warning|';\n    exit(0);\n});\n$object->x = 7;\necho 'unreachable|';\n",
        'dynamic property warning exit continuation'),
    'dynamic-reentry-cast': (
        b"<?php\nclass DynamicReentryCast18 {}\n$object = new DynamicReentryCast18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$array = (array) $object;\nforeach ($array as $key => $value) {\n    echo $key, '=', $value, '|';\n}\necho $array['x'], '|done';\n",
        'array cast of duplicate dynamic property buckets'),
    'dynamic-plain-rhs-unset': (
        b"<?php\nclass DynamicPlainRhsUnset18 {}\n$object = new DynamicPlainRhsUnset18();\n$rhs = 7;\nset_error_handler(function($level, $message, $file, $line) {\n    echo 'warning|';\n    unset($GLOBALS['rhs']);\n    return true;\n});\n$object->x = $rhs;\nrestore_error_handler();\necho isset($object->x) ? 'set|' : 'unset|';\nforeach ($object as $key => $value) {\n    echo $key, '=', $value, '|';\n}\necho 'done';\n",
        'dynamic property warning RHS pointer lifetime or undefined CV'),
    'duplicate-reference-foreach-binding-exit18': (b"<?php\nclass DuplicateReferenceForeachBindingExitObject18 {}\nclass DuplicateReferenceForeachBindingExitDestructor18 {\n    public function __destruct() {\n        echo $GLOBALS['value'] instanceof DuplicateReferenceForeachBindingExitDestructor18 ? 'old|' : 'new|';\n        unset($GLOBALS['object']->x);\n        unset($GLOBALS['object']->x);\n        exit(0);\n    }\n}\n$object = new DuplicateReferenceForeachBindingExitObject18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\nregister_shutdown_function(function() {\n    echo 'shutdown=', $GLOBALS['value'], '|';\n    echo isset($GLOBALS['object']->x) ? 'present|' : 'absent|';\n    echo 'done';\n});\n$value = new DuplicateReferenceForeachBindingExitDestructor18();\nforeach ($object as $key => &$value) { echo 'unexpected|'; }\necho 'unreachable|';\n", 'foreach reference binding exit continuation'),
    'duplicate-reference-foreach-binding-same-value18': (b"<?php\nclass DuplicateReferenceForeachBindingSamevalueObject18 {}\nclass DuplicateReferenceForeachBindingSamevalueDestructor18 {\n    public function __destruct() {\n        echo $GLOBALS['value'] instanceof DuplicateReferenceForeachBindingSamevalueDestructor18 ? 'old|' : 'new|';\n        $GLOBALS['value'] = $this;\n        unset($GLOBALS['object']->x);\n        unset($GLOBALS['object']->x);\n    }\n}\n$object = new DuplicateReferenceForeachBindingSamevalueObject18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$value = new DuplicateReferenceForeachBindingSamevalueDestructor18();\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    $value = 12;\n}\necho $value, '/';\necho isset($object->x) ? 'present|' : 'absent|';\nunset($value);\necho 'done';\n", 'mutation of released foreach CV', b'warning|old|'),
    'duplicate-reference-foreach-binding-unset18': (b"<?php\nclass DuplicateReferenceForeachBindingUnsetObject18 {}\nclass DuplicateReferenceForeachBindingUnsetDestructor18 {\n    public function __destruct() {\n        echo $GLOBALS['value'] instanceof DuplicateReferenceForeachBindingUnsetDestructor18 ? 'old|' : 'new|';\n        unset($GLOBALS['value']);\n        unset($GLOBALS['object']->x);\n        unset($GLOBALS['object']->x);\n    }\n}\n$object = new DuplicateReferenceForeachBindingUnsetObject18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$value = new DuplicateReferenceForeachBindingUnsetDestructor18();\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    $value = 12;\n}\necho $value, '/';\necho isset($object->x) ? 'present|' : 'absent|';\nunset($value);\necho 'done';\n", 'mutation of released foreach CV', b'warning|old|'),
    'duplicate-reference-foreach-binding-promote18': (b"<?php\nclass DuplicateReferenceForeachBindingPromoteObject18 {}\nclass DuplicateReferenceForeachBindingPromoteDestructor18 {\n    public function __destruct() {\n        echo $GLOBALS['value'] instanceof DuplicateReferenceForeachBindingPromoteDestructor18 ? 'old|' : 'new|';\n        $GLOBALS['alias'] =& $GLOBALS['value'];\n        unset($GLOBALS['object']->x);\n        unset($GLOBALS['object']->x);\n    }\n}\n$object = new DuplicateReferenceForeachBindingPromoteObject18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$value = new DuplicateReferenceForeachBindingPromoteDestructor18();\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    $value = 12;\n}\necho $value, '/';\necho isset($object->x) ? 'present|' : 'absent|';\nunset($value);\necho 'done';\n", 'mutation of released foreach CV', b'warning|old|'),
    'duplicate-reference-foreach-binding-rebind18': (b"<?php\nclass DuplicateReferenceForeachBindingRebindObject18 {}\nclass DuplicateReferenceForeachBindingRebindDestructor18 {\n    public function __destruct() {\n        echo $GLOBALS['value'] instanceof DuplicateReferenceForeachBindingRebindDestructor18 ? 'old|' : 'new|';\n        $GLOBALS['value'] =& $GLOBALS['object'];\n        unset($GLOBALS['object']->x);\n        unset($GLOBALS['object']->x);\n    }\n}\n$object = new DuplicateReferenceForeachBindingRebindObject18();\nset_error_handler(function($level, $message, $file, $line) use ($object) {\n    echo 'warning|';\n    @$object->x = 2;\n    return true;\n});\n$object->x = 7;\n$value = new DuplicateReferenceForeachBindingRebindDestructor18();\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n    $value = 12;\n}\necho $value, '/';\necho isset($object->x) ? 'present|' : 'absent|';\nunset($value);\necho 'done';\n", 'mutation of released foreach CV', b'warning|old|'),
    'duplicate-reference-foreach-prior-callback-array18': (b"<?php\nclass DuplicateReferenceForeachPriorCallbackArray18 {\n    public $x = 2;\n}\nclass DuplicateReferenceForeachPriorCallbackArrayValue18 {\n    public function __destruct() {\n        echo is_array($GLOBALS['value']) ? 'old|' : 'new|';\n    }\n}\n$object = new DuplicateReferenceForeachPriorCallbackArray18();\n$value = [new DuplicateReferenceForeachPriorCallbackArrayValue18()];\nforeach ($object as $key => &$value) {\n    echo $key, '=', $value, '|';\n}\necho 'done';\n", 'registered builtin call', b''),
}


def prepare(directory, source):
    frontend = adapter = None
    try:
        frontend = Worker([str(ROOT/'.tools/php/bin/php'), '-n', *cross.invoke.types.FLAGS,
            '-d', 'extension='+str(ROOT/'.tools/php-file.so'), str(ROOT/'frontend/worker.php')], directory/'frontend')
        adapter = Worker([str(ROOT/'_build/default/adapter/main.exe'), str(ROOT)], directory/'adapter')
        parsed = frontend.request({'op':'parse', 'source':base64.b64encode(source.read_bytes()).decode()})
        assert parsed['accepted'] is True
        checked = adapter.request({'op':'check', 'ast':parsed['ast'], 'fixture':True})
        assert checked['ok'] is True
        (directory/'program.watsup').write_text(checked['fixture']+'\n')
        return {'frontend':'accepted', 'checked':'program', 'model_evaluations':0}
    finally:
        if adapter: adapter.close()
        if frontend: frontend.close()


def boundary(directory, source, reason, expected_stdout=b'warning|', native_stdout=None):
    if native_stdout is not None:
        observed = cross.invoke.process([str(ROOT/'.tools/php/bin/php'), '-n', *cross.invoke.types.FLAGS, str(source)],
                                        directory/'native', 30, directory)
        assert observed.returncode == 0 and observed.stdout == native_stdout and not observed.stderr
    result = cross.invoke.process([str(ROOT/'bin/php-semantics'), str(source),
        '--steps', '100000', '--timeout', '60'], directory/'model', 90, directory)
    assert result.returncode == 1 and not result.stderr
    outcome = json.loads(result.stdout)
    assert outcome['frontend'] == 'accepted' and outcome['checked'] == 'program'
    assert outcome['status'] == 'unsupported' and outcome['reason'] == reason
    assert outcome['exit_status'] is None and outcome['diagnostic'] is None
    assert base64.b64decode(outcome['stdout'], validate=True) == expected_stdout
    assert not base64.b64decode(outcome['stderr'], validate=True)
    result = {'status':outcome['status'], 'reason':reason, 'agreement_claim':False}
    if native_stdout is not None:
        result['native_observation'] = {'exit_status':0, 'stdout':native_stdout.decode()}
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('mode', choices=['prepare','source','boundary'])
    parser.add_argument('--select', help='Comma-separated exact case IDs')
    args = parser.parse_args()
    candidates = BOUNDARIES if args.mode=='boundary' else CASES
    if args.mode=='prepare': candidates = CASES | BOUNDARIES
    selected = args.select.split(',') if args.select else list(candidates)
    assert selected and len(selected)==len(set(selected)) and all(name in candidates for name in selected)
    os.environ.update(LC_ALL='C', TZ='UTC', GIT_OPTIONAL_LOCKS='0')
    before = cross.snapshot(None)
    out = Path(tempfile.mkdtemp(prefix='dynamic-property-warning-'+args.mode+'-', dir=ROOT/'.tools'))
    report = {'mode':args.mode, 'before':before, 'profile':cross.invoke.types.PROFILE,
              'jobs':1, 'caps':{'native':30,'model_cli':60,'process':90},
              'passed':False, 'completed':False, 'records':[]}
    print(out, flush=True)
    try:
        for name in selected:
            directory = out/name; directory.mkdir()
            original = CASES[name] if name in CASES else BOUNDARIES[name][0]
            source = directory/'source.php'; source.write_bytes(original)
            row = {'case':name, 'source_sha256':cross.invoke.sha(source), 'completed':False}
            report['records'].append(row)
            if args.mode=='prepare': row['outcome'] = prepare(directory, source)
            elif args.mode=='boundary': row['outcome'] = boundary(directory, source, BOUNDARIES[name][1],
                BOUNDARIES[name][2] if len(BOUNDARIES[name])>=3 else
                (b'warning|old|' if name=='duplicate-reference-foreach-binding-exit18' else b'warning|'),
                BOUNDARIES[name][3] if len(BOUNDARIES[name])==4 else None)
            else: row['outcome'] = cross.source(
                {'abrupt':False, 'expected_exit_status':0, 'expected_stdout':EXPECTED[name]}, directory, source)
            assert cross.snapshot(None)==before
            assert source.read_bytes()==original
            row['completed']=True
            print(name, row['outcome'], flush=True)
        report.update(passed=True, completed=True)
    except BaseException as error:
        report['failure']={'type':type(error).__name__, 'message':str(error)}
        raise
    finally:
        report['after']=cross.snapshot(None)
        report['passed']=report['passed'] and report['before']==report['after']
        (out/'report.json').write_text(json.dumps(report, indent=2)+'\n')
        print(out/'report.json', report['passed'], flush=True)
    assert report['passed'] and report['completed']


if __name__=='__main__':
    main()
