#!/usr/bin/env python3
"""Independent reached owners, source scopes and eager destruction continuations."""
import argparse
import json
from pathlib import Path

import shutdown_state_review as runner

SOURCES = {row['id']: row['source'] for row in json.loads(
    Path(__file__).with_name('eager_destructor_review_cases.json').read_text())}
VALID = ['$destruction_state_valid(S)', '$call_current_valid(S)',
         '$call_frames_valid(S, S.FRAMES)', '$call_descriptors_valid(S)',
         '$class_state_valid(S)', '$heap_valid($heap_graph(S))']
DONE = ['S_done.TODO = eps', 'S_done.FRAMES = eps', 'S_done.CURRENT = eps',
        'S_done.HELD = eps', 'S_done.CONSTCONTEXT = eps',
        'S_done.DESTRUCTION.PHASE = DESTRUCTION_DONE',
        'S_done.DESTRUCTION.CALLS = eps',
        'S_done.DESTRUCTION.RELEASES = eps',
        'S_done.DESTRUCTION.FRAMES = eps',
        'S_done.DESTRUCTION.OPERATIONS = eps',
        'S_done.DESTRUCTION.CLEANUPS = eps',
        '$destruction_state_valid(S_done)',
        '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))']


def replay(completion='NORMAL'):
    return ['S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
            'S_paused.DESTRUCTION = S.DESTRUCTION',
            'S_paused.ALLOCATIONS = S.ALLOCATIONS',
            'S_done = $drive(S, 2000)', 'S_done.COMPLETION = ' + completion,
            *DONE, '$drive(S_paused[.COMPLETION = NORMAL], 2000) = S_done']


RETIRED_EXCEPTION_SOURCE = (
    '<?php function other($e){}class E extends Exception{function __destruct(){echo "E;";}}'
    '$other=new Exception("other");set_exception_handler(function($e){'
    'restore_exception_handler();restore_exception_handler();});'
    'register_shutdown_function(static function(){echo "S;";});throw new E("original");')


CASES = {
    'terminal-bailout-retains-two-receiver-counts': {
        'source': SOURCES['terminal-destructor-bailout-keeps-previous-owner'],
        'stage': 'S.TODO = [SHUTDOWN_SEND 0 0 eps]',
        'checks': [
            'S.CURRENT = eps', 'S.FRAMES = eps', 'S.ORIGIN = eps',
            'S.CONSTCONTEXT = eps',
            'S.SHUTDOWN.PHASE = SHUTDOWN_RUNNING',
            'S.DESTRUCTION.PHASE = DESTRUCTION_PENDING',
            'S.DESTRUCTION.CALLS = eps', 'S.DESTRUCTION.RELEASES = eps',
            'S.DESTRUCTION.FRAMES = eps', 'S.DESTRUCTION.OPERATIONS = eps',
            'S.DESTRUCTION.CLEANUPS = eps',
            'S.DESTRUCTION.ABANDONED = [pdestructioncleanup]',
            'pdestructioncleanup.SOURCE = DESTRUCTOR_RESULT pdestructorcall',
            '~pdestructioncleanup.RELEASED',
            '~pdestructorcall.USER', '~pdestructorcall.STORE',
            'pdestructorcall.CALLER = eps', 'pdestructorcall.ORIGIN = eps',
            'pdestructorcall.SITE = eps', 'pdestructorcall.CONSTCONTEXT = eps',
            'pdestructorcall.PENDING = eps',
            'pdestructorcall.RELEASE = (pdestructionrelease)',
            'pdestructionrelease.JOBS = [DESTRUCTION_VALUE (HOBJECT pdestructorcall.OBJECT)]',
            '$eager_bailout_extra(pdestructorcall) = eps',
            '$eager_abandoned_roots(S.DESTRUCTION.ABANDONED) = [HOBJECT pdestructorcall.OBJECT, HOBJECT pdestructorcall.OBJECT]',
            '$heap_owners($heap_graph(S), HOBJECT pdestructorcall.OBJECT) = 2',
            '$throwable_previous_id(S, pdestructorcall.OBJECT) = (n_previous)',
            '$heap_owners($heap_graph(S), HOBJECT n_previous) = 1',
            'pdestructorcall.OBJECT <- S.DESTRUCTION.CALLED',
            '~(n_previous <- S.DESTRUCTION.CALLED)',
            '$destructor_method(S, n_previous) = (pmethoddesc_previous)',
            '$eager_cleanup_valid(S, pdestructioncleanup)',
            '~$eager_abandoned_valid(S, [pdestructioncleanup[.RELEASED = true]])',
            '~$eager_cleanup_valid(S[.DESTRUCTION.CALLED = eps], pdestructioncleanup)',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.SOURCE = DESTRUCTOR_WARNING pdestructorcall])',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.SOURCE = DESTRUCTOR_RESULT pdestructorcall[.USER = true]])',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.SOURCE = DESTRUCTOR_RESULT pdestructorcall[.STORE = true]])',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.SOURCE = DESTRUCTOR_RESULT pdestructorcall[.RELEASE = eps]])',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.SOURCE = DESTRUCTOR_RESULT pdestructorcall[.LINE = $(pdestructorcall.LINE + 1)]])',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.SOURCE = DESTRUCTOR_RESULT pdestructorcall[.SITE = (pmethoddesc_previous.FUNCTION.ORIGIN)]])',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.SOURCE = DESTRUCTOR_RESULT pdestructorcall[.TARGET = METHOD_TARGET pdestructorcall.OBJECT pmethoddesc_previous.FUNCTION.ORIGIN]])',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.SOURCE = DESTRUCTOR_RESULT pdestructorcall[.OBJECT = n_previous][.TARGET = METHOD_TARGET n_previous pmethoddesc_previous.FUNCTION.ORIGIN]])',
            *VALID, *replay('REQUESTFATAL $ptascii("Exception") $ptascii("inner") 1'),
            'S_done.EVENTS = S.EVENTS ++ [OUTPUT $ptascii("S;"), OUTPUT $ptascii("P;")]',
            'S_done.DESTRUCTION.ABANDONED = S.DESTRUCTION.ABANDONED',
            '$heap_owners($heap_graph(S_done), HOBJECT pdestructorcall.OBJECT) = 2',
            '$heap_owners($heap_graph(S_done), HOBJECT n_previous) = 1',
            'n_previous <- S_done.DESTRUCTION.CALLED',
        ],
    },
    'terminal-exit-retains-two-receiver-counts': {
        'source': SOURCES['terminal-destructor-exit-keeps-previous-owner'],
        'stage': 'S.TODO = [SHUTDOWN_SEND 0 0 eps]',
        'checks': [
            'S.CURRENT = eps', 'S.FRAMES = eps', 'S.ORIGIN = eps',
            'S.SHUTDOWN.PHASE = SHUTDOWN_RUNNING',
            'S.SHUTDOWN.COMPLETION = EXITED 7',
            'S.DESTRUCTION.CALLS = eps', 'S.DESTRUCTION.RELEASES = eps',
            'S.DESTRUCTION.FRAMES = eps', 'S.DESTRUCTION.OPERATIONS = eps',
            'S.DESTRUCTION.CLEANUPS = eps',
            'S.DESTRUCTION.ABANDONED = [pdestructioncleanup]',
            'pdestructioncleanup.SOURCE = DESTRUCTOR_RESULT pdestructorcall',
            '~pdestructioncleanup.RELEASED', '~pdestructorcall.USER',
            '$eager_bailout_extra(pdestructorcall) = eps',
            '$eager_abandoned_roots(S.DESTRUCTION.ABANDONED) = [HOBJECT pdestructorcall.OBJECT, HOBJECT pdestructorcall.OBJECT]',
            '$heap_owners($heap_graph(S), HOBJECT pdestructorcall.OBJECT) = 2',
            '$throwable_previous_id(S, pdestructorcall.OBJECT) = (n_previous)',
            '$heap_owners($heap_graph(S), HOBJECT n_previous) = 1',
            '~(n_previous <- S.DESTRUCTION.CALLED)',
            '$eager_cleanup_valid(S, pdestructioncleanup)',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.SOURCE = DESTRUCTOR_WARNING pdestructorcall])',
            '~$eager_abandoned_valid(S, [pdestructioncleanup[.RELEASED = true]])',
            *VALID, *replay('EXITED 7'),
            'S_done.EVENTS = [OUTPUT $ptascii("H;"), OUTPUT $ptascii("E;"), OUTPUT $ptascii("S;"), OUTPUT $ptascii("P;")]',
            'S_done.DESTRUCTION.ABANDONED = S.DESTRUCTION.ABANDONED',
            '$heap_owners($heap_graph(S_done), HOBJECT pdestructorcall.OBJECT) = 2',
            'n_previous <- S_done.DESTRUCTION.CALLED',
        ],
    },
    'terminal-visibility-warning-retains-one-receiver-count': {
        'source': SOURCES['terminal-private-warning-bailout-keeps-previous-owner'],
        'stage': 'S.TODO = [SHUTDOWN_SEND 0 0 eps]',
        'checks': [
            'S.CURRENT = eps', 'S.FRAMES = eps', 'S.ORIGIN = eps',
            'S.SHUTDOWN.PHASE = SHUTDOWN_RUNNING',
            'S.DESTRUCTION.CALLS = eps', 'S.DESTRUCTION.RELEASES = eps',
            'S.DESTRUCTION.FRAMES = eps', 'S.DESTRUCTION.OPERATIONS = eps',
            'S.DESTRUCTION.CLEANUPS = eps',
            'S.DESTRUCTION.ABANDONED = [pdestructioncleanup, pdestructioncleanup_error]',
            'pdestructioncleanup.SOURCE = DESTRUCTOR_WARNING pdestructorcall',
            'pdestructioncleanup_error.SOURCE = ERROR_HANDLER_RESULT perrorcall',
            'perrorcall.RESUME = DESTRUCTOR_WARNING pdestructorcall',
            '~pdestructioncleanup.RELEASED', '~pdestructioncleanup_error.RELEASED',
            '~pdestructorcall.USER', 'pdestructorcall.CALLER = eps',
            '$destructor_method(S, pdestructorcall.OBJECT) = (pmethoddesc)',
            'pmethoddesc.VISIBILITY = PROPERTY_PRIVATE',
            '$eager_bailout_extra(pdestructorcall) = eps',
            'perrorcall.CALLBACK = POBJECT n_callback',
            '$eager_abandoned_roots(S.DESTRUCTION.ABANDONED) = [HOBJECT pdestructorcall.OBJECT, HOBJECT n_callback]',
            '$heap_owners($heap_graph(S), HOBJECT pdestructorcall.OBJECT) = 1',
            '$heap_owners($heap_graph(S), HOBJECT n_callback) = 1',
            '$throwable_previous_id(S, pdestructorcall.OBJECT) = (n_previous)',
            '$heap_owners($heap_graph(S), HOBJECT n_previous) = 1',
            '~(n_previous <- S.DESTRUCTION.CALLED)',
            '$eager_cleanup_valid(S, pdestructioncleanup)',
            '$eager_cleanup_valid(S, pdestructioncleanup_error)',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.SOURCE = DESTRUCTOR_RESULT pdestructorcall])',
            '~$eager_cleanup_valid(S, pdestructioncleanup_error[.SOURCE = ERROR_HANDLER_RESULT perrorcall[.LEVEL = 8192]])',
            '~$eager_cleanup_valid(S, pdestructioncleanup_error[.SOURCE = ERROR_HANDLER_RESULT perrorcall[.LINE = 1]])',
            '~$eager_cleanup_valid(S, pdestructioncleanup_error[.SOURCE = ERROR_HANDLER_RESULT perrorcall[.SITE = S.SHUTDOWN.ENTRIES[0].CALL.SITE]])',
            '~$eager_abandoned_valid(S, [pdestructioncleanup[.RELEASED = true], pdestructioncleanup_error])',
            *VALID, *replay('REQUESTFATAL $ptascii("Exception") $ptascii("warning") 1'),
            'S_done.EVENTS = S.EVENTS ++ [OUTPUT $ptascii("S;"), OUTPUT $ptascii("P;")]',
            'S_done.DESTRUCTION.ABANDONED = S.DESTRUCTION.ABANDONED',
            '$heap_owners($heap_graph(S_done), HOBJECT pdestructorcall.OBJECT) = 1',
            'n_previous <- S_done.DESTRUCTION.CALLED',
        ],
    },
    'main-source-unset-before-entry': {
        'source': SOURCES['main-unset-removes-binding-first'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail*',
        'checks': [
            'S.DESTRUCTION.PHASE = DESTRUCTION_PENDING',
            'S.SHUTDOWN.PHASE = SHUTDOWN_PENDING',
            'S.CURRENT = eps', 'S.FRAMES = eps',
            'pdestructorcall.USER', 'pdestructorcall.CALLER = eps',
            'pdestructorcall.SITE = pdestructorcall.ORIGIN',
            'pdestructorcall.SITE = (porigin_source)',
            '$eager_source_origin(S, (porigin_source))',
            '$lookup(S.ENV, $ptascii("d")) = eps',
            '$heap_owners($heap_graph(S), HOBJECT pdestructorcall.OBJECT) = 2',
            '$destructor_enter_valid(S, pdestructorcall)',
            '~$destructor_boundary_valid(S, pdestructorcall[.USER = false])',
            '~$destructor_boundary_valid(S, pdestructorcall[.SITE = eps])',
            '~$destructor_boundary_valid(S, pdestructorcall[.LINE = $(pdestructorcall.LINE + 1)])',
            '~$destructor_enter_valid(S, pdestructorcall[.USER = false])',
            '~$destructor_enter_valid(S, pdestructorcall[.SITE = eps])',
            '~$destructor_enter_valid(S, pdestructorcall[.LINE = $(pdestructorcall.LINE + 1)])',
            'pdestructorcall.TARGET = METHOD_TARGET pdestructorcall.OBJECT porigin_method',
            '~$destructor_boundary_valid(S, pdestructorcall[.SITE = (porigin_method)])',
            '~$destructor_enter_valid(S, pdestructorcall[.SITE = (porigin_method)])',
            '~$destructor_enter_valid(S[.DESTRUCTION.CALLED = eps], pdestructorcall)',
            '~$call_task_valid(S, DESTRUCTOR_ENTER pdestructorcall[.OBJECT = |S.OBJECTS|])',
            *VALID, *replay(),
            'S_done.EVENTS = [OUTPUT $ptascii("M;"), OUTPUT $ptascii("gone;"), OUTPUT $ptascii("T;")]',
            '~((HOBJECT pdestructorcall.OBJECT) <- S_done.ALLOCATIONS)',
        ],
    },
    'main-private-denial-remains-catchable': {
        'source': SOURCES['main-private-error-caught'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail*',
        'checks': [
            'S.CURRENT = eps', 'pdestructorcall.USER',
            'pdestructorcall.SITE = (porigin_source)',
            '$eager_source_origin(S, (porigin_source))',
            '$destructor_method(S, pdestructorcall.OBJECT) = (pmethoddesc)',
            'pmethoddesc.VISIBILITY = PROPERTY_PRIVATE',
            '~$method_accessible(S, pmethoddesc, eps)',
            '~$throwable_marker(DESTRUCTOR_RESULT pdestructorcall)',
            '$destructor_enter_valid(S, pdestructorcall)',
            '~$destructor_boundary_valid(S, pdestructorcall[.USER = false][.SITE = eps])',
            '~$destructor_enter_valid(S, pdestructorcall[.USER = false][.SITE = eps])',
            *VALID, *replay(),
            'S_done.EVENTS = [OUTPUT $ptascii("Call to private C::__destruct() from global scope"), OUTPUT $ptascii(";"), OUTPUT $ptascii("T;")]',
        ],
    },
    'binary-left-free-keeps-right-owner': {
        'source': SOURCES['binary-independent-drops-left-first'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail* -- if pdestructorcall.OBJECT = 1',
        'checks': [
            'S.DESTRUCTION.PHASE = DESTRUCTION_PENDING',
            'pdestructorcall.USER', 'pdestructorcall.CALLER = eps',
            'S.DESTRUCTION.OPERATIONS = [pdestructionoperation]',
            'pdestructorcall.OPERATION = (pdestructionoperation)',
            'pdestructionoperation.SOURCE = BINARY_RIGHT IDENTICAL poperand z',
            'pdestructionoperation.PENDING = eps',
            'S.DESTRUCTION.RELEASES = [pdestructionrelease]',
            'pdestructionrelease.JOBS = [DESTRUCTION_VALUE (HOBJECT 0)]',
            '$heap_owners($heap_graph(S), HOBJECT 1) = 2',
            '$heap_owners($heap_graph(S), HOBJECT 0) = 1',
            '$destructor_operation_live(S, pdestructionoperation)',
            '~$destructor_call_live(S, pdestructorcall[.OPERATION = eps])',
            '~$destructor_release_live(S, pdestructionrelease[.JOBS = eps])',
            *VALID, *replay(),
            'S_done.DESTRUCTION.CALLED = [1,0]',
            '~((HOBJECT 0) <- S_done.ALLOCATIONS)',
            '~((HOBJECT 1) <- S_done.ALLOCATIONS)',
        ],
    },
    'binary-replacement-before-second-drop': {
        'source': SOURCES['binary-left-throw-keeps-right-drop'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail* -- if pdestructorcall.OBJECT = 0',
        'checks': [
            'S.CURRENT = eps', 'pdestructorcall.USER',
            'S.DESTRUCTION.OPERATIONS = [pdestructionoperation]',
            'pdestructorcall.OPERATION = (pdestructionoperation)',
            'pdestructionoperation.PENDING = (n_pending)',
            'pdestructorcall.PENDING = (n_pending)',
            '$throwable_field(S, n_pending, "message") = PSTRING $ptascii("a")',
            '$heap_owners($heap_graph(S), HOBJECT n_pending) = 1',
            '~((HOBJECT 1) <- S.ALLOCATIONS)',
            '$heap_owners($heap_graph(S), HOBJECT 0) = 2',
            '1 <- S.DESTRUCTION.CALLED', '0 <- S.DESTRUCTION.CALLED',
            '$destructor_call_pending_valid(S, pdestructorcall)',
            '~$destructor_call_pending_valid(S, pdestructorcall[.PENDING = eps])',
            '~$destructor_call_live(S, pdestructorcall[.PENDING = eps])',
            *VALID, *replay(),
            'S_done.DESTRUCTION.CALLED = [1,0]',
            '$lookup(S_done.ENV, $ptascii("e")) = eps',
            '~((HOBJECT n_pending) <- S_done.ALLOCATIONS)',
            'S_done.EVENTS = [OUTPUT $ptascii("D:"), OUTPUT $ptascii("a"), OUTPUT $ptascii(";"), OUTPUT $ptascii("D:"), OUTPUT $ptascii("b"), OUTPUT $ptascii(";"), OUTPUT $ptascii("C:"), OUTPUT $ptascii("b"), OUTPUT $ptascii(":"), OUTPUT $ptascii("a"), OUTPUT $ptascii(";"), OUTPUT $ptascii("T;")]',
        ],
    },
    'binary-right-cv-remains-borrowed': {
        'source': SOURCES['binary-right-cv-borrowed-during-left-destructor'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail* -- if pdestructorcall.OBJECT = 1',
        'checks': [
            'S.CURRENT = eps', 'pdestructorcall.USER',
            'S.DESTRUCTION.OPERATIONS = [pdestructionoperation]',
            'pdestructorcall.OPERATION = (pdestructionoperation)',
            'pdestructionoperation.SOURCE = BINARY_RIGHT IDENTICAL poperand z',
            'pdestructionoperation.VALUE = KNOWN (PBOOL false)',
            'S.DESTRUCTION.RELEASES = [pdestructionrelease]',
            'pdestructionrelease.JOBS = eps',
            '$lookup(S.ENV, $ptascii("x")) = (n_x)',
            'S.STORE[n_x] = DEFINED (POBJECT 0)',
            '$heap_owners($heap_graph(S), HOBJECT 0) = 1',
            '$heap_owners($heap_graph(S), HOBJECT 1) = 2',
            *VALID, *replay(),
            'S_done.EVENTS = [OUTPUT $ptascii("M;"), OUTPUT $ptascii("A;"), OUTPUT $ptascii("R;"), OUTPUT $ptascii("Aend;"), OUTPUT $ptascii("T;")]',
            'S_done.DESTRUCTION.CALLED = [1,0]',
            '~((HOBJECT 0) <- S_done.ALLOCATIONS)',
            '~((HOBJECT 1) <- S_done.ALLOCATIONS)',
        ],
    },
    'used-write-owns-copied-result': {
        'source': SOURCES['used-assignment-retains-rhs-result'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail* -- if pdestructorcall.OBJECT = 0',
        'checks': [
            'S.CURRENT = eps', 'pdestructorcall.USER',
            'S.DESTRUCTION.OPERATIONS = [pdestructionoperation]',
            'pdestructorcall.OPERATION = (pdestructionoperation)',
            'pdestructionoperation.VALUE = KNOWN (POBJECT 1)',
            'pdestructionoperation.BASE = BASE_VALUE (KNOWN PNULL)',
            'pdestructionoperation.SOURCE = WRITE_NAME $ptascii("x") z',
            '$lookup(S.ENV, $ptascii("x")) = (n_x)',
            'S.STORE[n_x] = DEFINED (POBJECT 1)',
            '$heap_owners($heap_graph(S), HOBJECT 1) = 2',
            '$heap_owners($heap_graph(S), HOBJECT 0) = 2',
            *VALID, *replay(),
            'S_done.EVENTS = [OUTPUT $ptascii("M;"), OUTPUT $ptascii("A;"), OUTPUT $ptascii("Aend;"), OUTPUT $ptascii("T;"), OUTPUT $ptascii("R;")]',
            '~((HOBJECT 1) <- S_done.ALLOCATIONS)',
        ],
    },
    'unused-write-has-no-copied-result': {
        'source': SOURCES['unused-assignment-no-rhs-extra-owner'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail* -- if pdestructorcall.OBJECT = 0',
        'checks': [
            'S.CURRENT = eps', 'pdestructorcall.USER',
            'S.DESTRUCTION.OPERATIONS = [pdestructionoperation]',
            'pdestructionoperation.VALUE = KNOWN PNULL',
            'pdestructionoperation.BASE = BASE_VALUE (KNOWN PNULL)',
            'pdestructionoperation.SOURCE = WRITE_NAME $ptascii("x") z',
            '$lookup(S.ENV, $ptascii("x")) = (n_x)',
            'S.STORE[n_x] = DEFINED (POBJECT 1)',
            '$heap_owners($heap_graph(S), HOBJECT 1) = 1',
            *VALID, *replay(),
            'S_done.EVENTS = [OUTPUT $ptascii("M;"), OUTPUT $ptascii("A;"), OUTPUT $ptascii("R;"), OUTPUT $ptascii("Aend;"), OUTPUT $ptascii("T;")]',
            '~((HOBJECT 1) <- S_done.ALLOCATIONS)',
        ],
    },
    'property-holder-dies-with-rhs-temp-retained': {
        'source': SOURCES['property-rhs-temp-survives-cv-receiver-drop'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail* -- if pdestructorcall.OBJECT = 0',
        'checks': [
            'S.CURRENT = (pcallcontext)',
            'pcallcontext.TARGET = METHOD_TARGET 1 porigin_old',
            'pdestructorcall.USER', 'pdestructorcall.CALLER = (pcallcontext)',
            'S.DESTRUCTION.OPERATIONS = pdestructionoperation_nested :: pdestructionoperation_original :: pdestructionoperation_tail*',
            'pdestructionoperation_original.VALUE = KNOWN (POBJECT 2)',
            'pdestructionoperation_original.BASE = BASE_VALUE (KNOWN PNULL)',
            'pdestructionoperation_original.SOURCE = ASSIGN_ARRAY pbase z b',
            '$lookup($global_table_view(S).ENV, $ptascii("b")) = eps',
            '$heap_owners($heap_graph(S), HOBJECT 0) = 2',
            '$heap_owners($heap_graph(S), HOBJECT 2) = 2',
            '$destructor_context_valid(S, pcallcontext)',
            '$destructor_operation_live(S, pdestructionoperation_original)',
            *VALID, *replay(),
            'S_done.EVENTS = [OUTPUT $ptascii("M;"), OUTPUT $ptascii("A;"), OUTPUT $ptascii("B;"), OUTPUT $ptascii("Aend;"), OUTPUT $ptascii("R;"), OUTPUT $ptascii("T;")]',
            '~((HOBJECT 0) <- S_done.ALLOCATIONS)',
            '~((HOBJECT 1) <- S_done.ALLOCATIONS)',
            '~((HOBJECT 2) <- S_done.ALLOCATIONS)',
        ],
    },
    'error-retval-internal-trace-real-main-caller': {
        'source': SOURCES['error-handler-retval-internal-trace-main-catch'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail*',
        'checks': [
            'S.CURRENT = eps', 'pdestructorcall.USER',
            'pdestructorcall.CALLER = eps', 'pdestructorcall.SITE = eps',
            'pdestructorcall.ORIGIN = (porigin_source)',
            '$eager_source_origin(S, (porigin_source))',
            'S.DESTRUCTION.OPERATIONS = [pdestructionoperation]',
            'pdestructionoperation.SOURCE = ERROR_HANDLER_RESULT perrorcall',
            'pdestructionoperation.CLEANUP = (pdestructioncleanup)',
            'S.DESTRUCTION.CLEANUPS = [pdestructioncleanup]',
            'pdestructioncleanup.SOURCE = ERROR_HANDLER_RESULT perrorcall',
            'S.ERRORHANDLER.CALLBACK = eps',
            '$eager_operation_source_valid(S, pdestructionoperation)',
            '~$eager_operation_source_valid(S, pdestructionoperation[.CLEANUP = eps])',
            '~$eager_operation_source_valid(S[.DESTRUCTION.CLEANUPS = eps], pdestructionoperation)',
            '~$destructor_boundary_valid(S, pdestructorcall[.USER = false])',
            '~$destructor_enter_valid(S, pdestructorcall[.USER = false])',
            '~$throwable_marker(DESTRUCTOR_RESULT pdestructorcall)',
            *VALID, *replay(),
            'S_done.ERRORHANDLER.CALLBACK = (PSTRING $ptascii("w"))',
        ],
    },
    'retired-exception-selection-before-original-release': {
        'source': RETIRED_EXCEPTION_SOURCE,
        'stage': 'S.TODO = (EXCEPTION_HANDLER_CLEAN pexceptioncall false) :: ptask_tail*',
        'checks': [
            'S.CURRENT = eps', 'S.FRAMES = eps', 'S.ORIGIN = eps',
            'S.CONSTCONTEXT = eps', 'S.EXCEPTIONHANDLER = eps',
            'S.DESTRUCTION.CLEANUPS = [pdestructioncleanup]',
            'pdestructioncleanup.SOURCE = EXCEPTION_HANDLER_RESULT pexceptioncall',
            '~pdestructioncleanup.RELEASED',
            'pexceptioncall.TARGET = (pcalltarget)',
            '$target_instance(pcalltarget) = (n_handler)',
            '~((HOBJECT n_handler) <- S.ALLOCATIONS)',
            '$heap_owners($heap_graph(S), HOBJECT pexceptioncall.OBJECT) = 1',
            'pexceptioncall.SENT = (KNOWN (POBJECT pexceptioncall.OBJECT))',
            'pexceptioncall.RECEIVED = pexceptioncall.SENT',
            '$eager_cleanup_valid(S, pdestructioncleanup)',
            '$exception_cleanup_valid(S, pexceptioncall, false)',
            '$exception_result_valid($eager_cleanup_history(S, pdestructioncleanup), pexceptioncall)',
            '~$exception_result_valid(S, pexceptioncall)',
            '$lookup(S.ENV, $ptascii("other")) = (n_other_cell)',
            'S.STORE[n_other_cell] = DEFINED (POBJECT n_other)',
            'n_other =/= pexceptioncall.OBJECT', '$throwable_member(S, n_other)',
            '~$exception_cleanup_valid(S, pexceptioncall[.OBJECT = n_other], false)',
            '~$exception_cleanup_valid(S, pexceptioncall[.OBJECT = n_other][.SENT = (KNOWN (POBJECT n_other))][.RECEIVED = (KNOWN (POBJECT n_other))], false)',
            '$call_target(S, $ptascii("other"), eps) = (pfunction_other)',
            '~$exception_cleanup_valid(S, pexceptioncall[.TARGET = (pfunction_other.ORIGIN)][.CALLBACK = PSTRING $ptascii("other")], false)',
            '~$exception_cleanup_valid(S, pexceptioncall[.SENT = (KNOWN PNULL)], false)',
            '~$exception_cleanup_valid(S, pexceptioncall, true)',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.SOURCE = EXCEPTION_HANDLER_RESULT pexceptioncall[.TARGET = (pfunction_other.ORIGIN)]])',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.ORIGIN = (pfunction_other.ORIGIN)])',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.CONSTCONTEXT = ({ORIGIN pfunction_other.ORIGIN, LINE 1, FACTS eps})])',
            '~$exception_cleanup_valid(S[.DESTRUCTION.CLEANUPS = eps], pexceptioncall, false)',
            *VALID, *replay(),
            '~((HOBJECT pexceptioncall.OBJECT) <- S_done.ALLOCATIONS)',
            'pexceptioncall.OBJECT <- S_done.DESTRUCTION.CALLED',
            'S_done.EVENTS = [OUTPUT $ptascii("E;"), OUTPUT $ptascii("S;")]',
        ],
    },
    'retired-exception-original-after-own-release': {
        'source': RETIRED_EXCEPTION_SOURCE,
        'stage': 'S.TODO = (EXCEPTION_HANDLER_CLEAN pexceptioncall true) :: ptask_tail*',
        'checks': [
            'S.CURRENT = eps', 'S.FRAMES = eps', 'S.ORIGIN = eps',
            'S.CONSTCONTEXT = eps',
            'S.DESTRUCTION.CLEANUPS = [pdestructioncleanup]',
            'pdestructioncleanup.SOURCE = EXCEPTION_HANDLER_RESULT pexceptioncall',
            'pdestructioncleanup.RELEASED',
            '~((HOBJECT pexceptioncall.OBJECT) <- S.ALLOCATIONS)',
            '$task_nodes(EXCEPTION_HANDLER_CLEAN pexceptioncall true) = eps',
            '$heap_owners($heap_graph(S), HOBJECT pexceptioncall.OBJECT) = 0',
            '$eager_cleanup_valid(S, pdestructioncleanup)',
            '$exception_cleanup_valid(S, pexceptioncall, true)',
            '~$exception_cleanup_valid(S, pexceptioncall, false)',
            '~$exception_cleanup_valid(S, pexceptioncall[.OBJECT = |S.OBJECTS|], true)',
            '~$exception_cleanup_valid(S[.DESTRUCTION.CLEANUPS = eps], pexceptioncall, true)',
            *VALID, *replay(),
            'S_done.EVENTS = [OUTPUT $ptascii("E;"), OUTPUT $ptascii("S;")]',
            '~((HOBJECT pexceptioncall.OBJECT) <- S_done.ALLOCATIONS)',
        ],
    },
    'retval-bailout-keeps-unreleased-original-c-count': {
        'source': SOURCES['exception-handler-retval-drops-before-handler-restore'],
        'stage': 'S.TODO = [SHUTDOWN_SEND 0 0 eps]',
        'checks': [
            'S.SHUTDOWN.PHASE = SHUTDOWN_RUNNING',
            'S.DESTRUCTION.PHASE = DESTRUCTION_PENDING',
            'S.DESTRUCTION.CLEANUPS = eps',
            'S.DESTRUCTION.OPERATIONS = eps',
            'S.DESTRUCTION.ABANDONED = [pdestructioncleanup, pdestructioncleanup_retval]',
            '~pdestructioncleanup.RELEASED',
            'pdestructioncleanup.SOURCE = EXCEPTION_HANDLER_RESULT pexceptioncall',
            'pdestructioncleanup_retval.SOURCE = DESTRUCTOR_RESULT pdestructorcall',
            '~pdestructioncleanup_retval.RELEASED',
            '~pdestructorcall.USER', 'pdestructorcall.CALLER = eps',
            'pdestructorcall.ORIGIN = eps', 'pdestructorcall.SITE = eps',
            '$eager_bailout_extra(pdestructorcall) = eps',
            '$eager_abandoned_roots(S.DESTRUCTION.ABANDONED) = [HOBJECT pexceptioncall.OBJECT, HOBJECT pdestructorcall.OBJECT, HOBJECT pdestructorcall.OBJECT]',
            '$heap_owners($heap_graph(S), HOBJECT pexceptioncall.OBJECT) = 1',
            '$heap_owners($heap_graph(S), HOBJECT pdestructorcall.OBJECT) = 2',
            '~(pexceptioncall.OBJECT <- S.DESTRUCTION.CALLED)',
            'pdestructorcall.OBJECT <- S.DESTRUCTION.CALLED',
            '$eager_abandoned_valid(S, S.DESTRUCTION.ABANDONED)',
            '$eager_cleanup_valid(S, pdestructioncleanup_retval)',
            '~$eager_abandoned_valid(S, [pdestructioncleanup[.RELEASED = true]])',
            '~$eager_cleanup_valid(S, pdestructioncleanup_retval[.SOURCE = DESTRUCTOR_WARNING pdestructorcall])',
            '~$eager_cleanup_valid(S, pdestructioncleanup_retval[.SOURCE = DESTRUCTOR_RESULT pdestructorcall[.USER = true]])',
            '$call_target(S, $ptascii("not_registered"), eps) = eps',
            '~$eager_cleanup_valid(S, pdestructioncleanup[.SOURCE = EXCEPTION_HANDLER_RESULT pexceptioncall[.CALLBACK = PSTRING $ptascii("not_registered")]])',
            'S.EXCEPTIONHANDLER = eps',
            'S.SHUTDOWN.COMPLETION = REQUESTFATAL $ptascii("Exception") $ptascii("retval") 1',
            *VALID, *replay('REQUESTFATAL $ptascii("Exception") $ptascii("retval") 1'),
            'S_done.DESTRUCTION.ABANDONED = S.DESTRUCTION.ABANDONED',
            'pexceptioncall.OBJECT <- S_done.DESTRUCTION.CALLED',
            '$heap_owners($heap_graph(S_done), HOBJECT pexceptioncall.OBJECT) = 1',
            '$heap_owners($heap_graph(S_done), HOBJECT pdestructorcall.OBJECT) = 2',
            'S_done.EVENTS = S.EVENTS ++ [OUTPUT $ptascii("S;"), OUTPUT $ptascii("E;")]',
        ],
    },
    'frozen-empty-queue-precedes-global-pass': {
        'source': SOURCES['terminal-original-empty-queue-before-stage2'],
        'stage': 'S.TODO = [DESTRUCTOR_PREQUEUE pcompletion]',
        'checks': [
            'S.CURRENT = eps', 'S.FRAMES = eps', 'S.ORIGIN = eps',
            'S.CONSTCONTEXT = eps',
            'S.SHUTDOWN.PHASE = SHUTDOWN_PENDING', 'S.SHUTDOWN.ENTRIES = eps',
            'S.DESTRUCTION.PHASE = DESTRUCTION_PENDING',
            'S.DESTRUCTION.COMPLETION = pcompletion',
            'pcompletion = REQUESTFATAL $ptascii("E") $ptascii("original") 1',
            '$lookup(S.ENV, $ptascii("g")) = (n_global)',
            'S.STORE[n_global] = DEFINED (POBJECT 0)',
            '$heap_owners($heap_graph(S), HOBJECT 0) = 1',
            '~((HOBJECT 1) <- S.ALLOCATIONS)',
            'S.DESTRUCTION.CALLED = [1]',
            'S.EVENTS = [STDERR ptbytes_frozen, OUTPUT $ptascii("E;")]',
            '$call_task_valid(S, DESTRUCTOR_PREQUEUE pcompletion)',
            '~$call_task_valid(S, DESTRUCTOR_PREQUEUE (REQUESTFATAL $ptascii("Other") $ptascii("original") 1))',
            '~$call_task_valid(S, DESTRUCTOR_PREQUEUE (REQUESTFATAL $ptascii("E") $ptascii("later") 1))',
            '~$call_task_valid(S, DESTRUCTOR_PREQUEUE (REQUESTFATAL $ptascii("E") $ptascii("original") 2))',
            '~$call_task_valid(S, DESTRUCTOR_PREQUEUE NORMAL)',
            *VALID, *replay('pcompletion'),
            'S_done.EVENTS = [STDERR ptbytes_frozen, OUTPUT $ptascii("E;"), OUTPUT $ptascii("G;")]',
            'S_done.DESTRUCTION.CALLED = [1,0]',
            '~((HOBJECT 0) <- S_done.ALLOCATIONS)',
        ],
    },
    'cold-used-property-keeps-opdata-and-result-copy': {
        'source': SOURCES['used-property-assignment-owns-result-not-cv-receiver'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail* -- if pdestructorcall.OBJECT = 1',
        'checks': [
            'S.CURRENT = eps', 'pdestructorcall.USER',
            'S.DESTRUCTION.OPERATIONS = [pdestructionoperation]',
            'pdestructionoperation.VALUE = KNOWN (POBJECT 2)',
            'pdestructionoperation.BASE = BASE_VALUE (KNOWN PNULL)',
            'pdestructionoperation.SOURCE = ASSIGN_ARRAY pbase z b',
            'pdestructionoperation.ORIGIN = (porigin_write)',
            'S.DESTRUCTION.RELEASES = [pdestructionrelease]',
            'pdestructionrelease.JOBS = [DESTRUCTION_VALUE (HOBJECT 2)]',
            '$heap_owners($heap_graph(S), HOBJECT 2) = 3',
            '$heap_owners($heap_graph(S), HOBJECT 0) = 1',
            '$eager_property_cache_at(S.DESTRUCTION.PROPCACHE, porigin_write) = (S.OBJECTS[0])',
            '$destructor_operation_live(S, pdestructionoperation)',
            *VALID, *replay(),
            '~((HOBJECT 2) <- S_done.ALLOCATIONS)',
        ],
    },
    'warm-unused-property-moves-tmp-before-old-release': {
        'source': SOURCES['same-property-site-cold-and-warm-unused'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail* -- if pdestructorcall.OBJECT = 4',
        'checks': [
            'S.CURRENT = eps', 'pdestructorcall.USER',
            'S.DESTRUCTION.OPERATIONS = [pdestructionoperation]',
            'pdestructionoperation.VALUE = KNOWN PNULL',
            'pdestructionoperation.BASE = BASE_VALUE (KNOWN PNULL)',
            'pdestructionoperation.SOURCE = ASSIGN_ARRAY pbase z b',
            'pdestructionoperation.ORIGIN = (porigin_write)',
            '$eager_property_cache_at(S.DESTRUCTION.PROPCACHE, porigin_write) = (S.OBJECTS[3])',
            'S.DESTRUCTION.RELEASES = [pdestructionrelease]',
            'pdestructionrelease.JOBS = eps',
            '$heap_owners($heap_graph(S), HOBJECT 5) = 1',
            '$heap_owners($heap_graph(S), HOBJECT 3) = 1',
            '~((HOBJECT 0) <- S.ALLOCATIONS)',
            '~((HOBJECT 1) <- S.ALLOCATIONS)',
            '~((HOBJECT 2) <- S.ALLOCATIONS)',
            '$eager_property_caches_valid(S, S.DESTRUCTION.PROPCACHE)',
            '~$eager_property_caches_valid(S, [(porigin_write, INTRINSICCLOSURE INTRINSIC_ERROR_REPORTING)])',
            '$destructor_method(S, 4) = (pmethoddesc)',
            '~$eager_property_caches_valid(S, [(pmethoddesc.FUNCTION.ORIGIN, S.OBJECTS[3])])',
            '~$eager_property_caches_valid(S, [(porigin_write, INSTANCE pmethoddesc.FUNCTION.ORIGIN)])',
            *VALID, *replay(),
            '~((HOBJECT 5) <- S_done.ALLOCATIONS)',
        ],
    },
}

warning_exit = CASES['terminal-visibility-warning-retains-one-receiver-count']
CASES['terminal-visibility-warning-exit-retains-one-receiver-count'] = {
    'source': SOURCES['terminal-private-warning-exit-keeps-previous-owner'],
    'stage': warning_exit['stage'],
    'checks': [clause.replace(
        'REQUESTFATAL $ptascii("Exception") $ptascii("warning") 1', 'EXITED 7')
        for clause in warning_exit['checks']],
}

CASES['array-warning-cleanup-retains-exact-source-marker'] = {
    'source': Path(__file__).with_name('source-arrays').joinpath('core/lifetime-pending.php').read_text(),
    'startup': '{REPORTING ($ptascii("30719")), INCLUDEPATH $ptascii(".:")}',
    'stage': ('S.TODO = (DESTRUCTOR_OPERATION_EXIT pdestructionoperation) :: (ERROR_HANDLER_CLEAN perrorcall) :: ptask_tail* '
              '-- if pdestructionoperation.SOURCE = ERROR_HANDLER_RESULT perrorcall '
              '-- if perrorcall.RESUME = SOURCE_ARRAY_RESULT psourceoperand '
              '-- if psourceoperand.LINE = 24'),
    'checks': [
        'pdestructionoperation.CLEANUP = (pdestructioncleanup)',
        'ptask_tail* = psourceoperand.TAIL',
        '$source_operand_marker(ERROR_HANDLER_CLEAN perrorcall) = SOURCE_ARRAY_RESULT psourceoperand',
        '$source_operand_suffix((ERROR_HANDLER_CLEAN perrorcall) :: ptask_tail*, SOURCE_ARRAY_RESULT psourceoperand, psourceoperand.TAIL)',
        '$eager_cleanup_valid(S, pdestructioncleanup)',
        '$destructor_operation_valid(S, pdestructionoperation)',
        '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))',
        'S_forged = S[.TODO = (DESTRUCTOR_OPERATION_EXIT pdestructionoperation) :: (ERROR_HANDLER_CLEAN perrorcall) :: (SOURCE_ARRAY_RESULT psourceoperand) :: ptask_tail*]',
        '~$source_operand_suffix((ERROR_HANDLER_CLEAN perrorcall) :: (SOURCE_ARRAY_RESULT psourceoperand) :: ptask_tail*, SOURCE_ARRAY_RESULT psourceoperand, psourceoperand.TAIL)',
        '~$eager_cleanup_valid(S_forged, pdestructioncleanup)',
        '~$eager_operation_source_valid(S_forged, pdestructionoperation)',
        '~$call_descriptors_valid(S_forged)',
        'S_paused = $drive_steps(S, 0)', 'S_paused.COMPLETION = BUDGET',
        'S_paused[.COMPLETION = NORMAL] = S',
        'S_next = $drive_steps(S, 1)', 'S_next.DESTRUCTION.OPERATIONS = eps',
        'S_next.TODO = (ERROR_HANDLER_CLEAN perrorcall) :: ptask_tail*',
        '$call_descriptors_valid(S_next)', '$heap_valid($heap_graph(S_next))',
    ],
}

runner.CASES = CASES

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--case', action='append')
    args = parser.parse_args()
    raise SystemExit(0 if runner.run(args.case) else 1)
