#!/usr/bin/env python3
"""Reached API method selections, raw callback values and abrupt retirement."""
import json
from pathlib import Path

import closure_call_protocol as protocol

CATALOGUE = Path(__file__).with_name('error_handler_callables_cases.json')
SOURCES = {row['id']: row['source'] for row in json.loads(CATALOGUE.read_text())}
VALID = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
         '$call_descriptors_valid(S)', '$class_state_valid(S)',
         '$heap_valid($heap_graph(S))']
FINISH = ['S_done = $drive(S, 5000)', 'S_done.COMPLETION = NORMAL',
          'S_done.TODO = eps', 'S_done.FRAMES = eps', 'S_done.CURRENT = eps',
          'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
          '$call_descriptors_valid(S_done)', '$class_state_valid(S_done)',
          '$heap_valid($heap_graph(S_done))']

CASES = {
    'copied-array-after-cow-replacement': {
        'source': SOURCES['raw-array-copy-on-write-keeps-original-members'],
        'stage': ('S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* '
                  '-- if S.CURRENT = (pcallcontext) '
                  '-- if pcallcontext.TARGET = HANDLER_METHOD_TARGET false porigin_requested ptbytes pcalltarget'),
        'checks': [
            'S.CURRENT = (pcallcontext)',
            'S.FRAMES = pframe :: pframe_tail*',
            'pframe.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_saved*',
            'perrorcall.CALLBACK = PARRAY n_raw',
            'pcallcontext.TARGET = HANDLER_METHOD_TARGET false porigin_requested $ptascii("first") pcalltarget',
            'pcalltarget = SCOPED_TARGET porigin_requested porigin_method porigin_requested (n_receiver) (KNOWN (PSTRING $ptascii("Owner")))',
            'pcallcontext.FUNCTION = porigin_method',
            'pcallcontext.RECEIVER = (n_receiver)',
            'pcallcontext.LEXICAL_CLASS = (porigin_requested)',
            'pcallcontext.CALLED_CLASS = (porigin_requested)',
            'pcallcontext.ARGC = 4',
            '$arginfo_values(S, pcallcontext) = [PINT 512, PSTRING $ptascii("copy"), PSTRING ptbytes_file, PINT perrorcall.LINE]',
            'S.ARRAYS[n_raw].ITEMS = [ENTRY (KINT 0) (DIRECT (POBJECT n_receiver)), ENTRY (KINT 1) (DIRECT (PSTRING $ptascii("first")))]',
            'S.GLOBALTABLE = (psymboltable)',
            '$lookup(psymboltable.ENV, $ptascii("raw")) = eps',
            '$lookup(psymboltable.ENV, $ptascii("receiver")) = eps',
            'S.ERRORHANDLER.CALLBACK = eps',
            '$error_handler_selected(S, perrorcall.CALLBACK, pcallcontext.TARGET)',
            '$error_context_valid(S, pcallcontext)',
            '$target_nodes(pcallcontext.TARGET) = [HOBJECT n_receiver]',
            'HOBJECT n_receiver <- $task_nodes(ERROR_HANDLER_RESULT perrorcall)',
            'HARRAY n_raw <- $task_nodes(ERROR_HANDLER_RESULT perrorcall)',
            '(HOBJECT n_receiver) <- S.ALLOCATIONS',
            '(HARRAY n_raw) <- S.ALLOCATIONS',
            *VALID,
            '~$handler_target_valid(S, porigin_requested, $ptascii("second"), pcalltarget)',
            '~$error_context_valid(S, pcallcontext[.CALLSITE = (porigin_method)])',
            '~$error_context_valid(S, pcallcontext[.LINE = $(perrorcall.LINE + 1)])',
            '~$error_context_valid(S, pcallcontext[.ARGC = 3])',
            'S_bad = S[.ARRAYS = $array_replace(S.ARRAYS, n_raw, S.ARRAYS[n_raw][.ITEMS = [ENTRY (KINT 1) (DIRECT (PSTRING $ptascii("first")))]])]',
            '~$error_handler_selected(S_bad, perrorcall.CALLBACK, pcallcontext.TARGET)',
            *FINISH,
            '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
            '~((HARRAY n_raw) <- S_done.ALLOCATIONS)',
        ],
    },
    'delayed-invalid-reference-and-api-trace': {
        'source': SOURCES['raw-reference-invalid-shape-restores-and-recovers'],
        'stage': ('S.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail* '
                  '-- if perrorcall.MESSAGE = $ptascii("method")'),
        'checks': [
            'S.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
            'perrorcall.CALLBACK = PARRAY n_raw',
            'perrorcall.TARGET = eps',
            'perrorcall.RESUME = ERROR_TRIGGER_PHASE pconfigcall 2',
            'S.ERRORHANDLER.CALLBACK = (perrorcall.CALLBACK)',
            '$lookup(S.ENV, $ptascii("method")) = (n_method_cell)',
            'S.STORE[n_method_cell] = DEFINED (PINT 17)',
            'S.ARRAYS[n_raw].ITEMS = [ENTRY (KINT 0) (ALIAS n_receiver_cell), ENTRY (KINT 1) (ALIAS n_method_cell)]',
            '$error_handler_retained(S, perrorcall.CALLBACK)',
            '$error_handler_resolution(S, perrorcall.CALLBACK) = HANDLERINVALID ($ptascii("second array member is not a valid method"))',
            '$error_handler_target(S, perrorcall.CALLBACK) = eps',
            '$call_task_valid(S, ERROR_HANDLER_INVOKE perrorcall)',
            '~$call_task_valid(S, ERROR_HANDLER_INVOKE perrorcall[.LINE = $(perrorcall.LINE + 1)])',
            '~$call_task_valid(S, ERROR_HANDLER_INVOKE perrorcall[.SITE = PORIGIN 999 eps])',
            *VALID,
            'PhpStep: S ~> S_one',
            'S_one.COMPLETION = THROWING n_error',
            'S_one.ERRORHANDLER.CALLBACK = (perrorcall.CALLBACK)',
            'S_one.FRAMES = S.FRAMES',
            'S_one.CURRENT = S.CURRENT',
            'S_one.OBJECTS[n_error] = THROWABLE pthrowable',
            'pthrowable.KIND = "Error"',
            '$throwable_field(S_one, n_error, "message") = PSTRING ($ptascii("Invalid callback Array, second array member is not a valid method"))',
            '$throwable_field(S_one, n_error, "trace") = PARRAY n_trace',
            'S_one.ARRAYS[n_trace].ITEMS = [ENTRY (KINT 0) (DIRECT (PARRAY n_trigger))]',
            '$trace_array_field(S_one, n_trigger, $ptascii("function")) = PSTRING ($ptascii("trigger_error"))',
            '$trace_array_field(S_one, n_trigger, $ptascii("args")) = PARRAY n_arguments',
            'S_one.ARRAYS[n_arguments].ITEMS = [ENTRY (KINT 0) (DIRECT (PSTRING $ptascii("method"))), ENTRY (KINT 1) (DIRECT (PINT 512))]',
            '$trace_graph_valid(S_one, n_trace)',
            *FINISH,
            '~((HARRAY n_raw) <- S_done.ALLOCATIONS)',
        ],
    },
    'api-static-parent-forwards-emitting-child': {
        'source': SOURCES['api-static-parent-descriptor-forwards-active-child'],
        'stage': ('S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* '
                  '-- if S.CURRENT = (pcallcontext) '
                  '-- if pcallcontext.TARGET = HANDLER_METHOD_TARGET true porigin_requested ptbytes pcalltarget'),
        'checks': [
            'S.CURRENT = (pcallcontext)',
            'S.FRAMES = pframe :: pframe_tail*',
            'pframe.CONTEXT = (pcallcontext_emitter)',
            'pframe.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_saved*',
            'pcallcontext.TARGET = HANDLER_METHOD_TARGET true porigin_requested $ptascii("sTaT") pcalltarget',
            'pcalltarget = SCOPED_TARGET porigin_requested porigin_method porigin_called eps (KNOWN (PSTRING $ptascii("Owner")))',
            'perrorcall.CALLBACK = PARRAY n_raw',
            'perrorcall.TARGET = (pcallcontext.TARGET)',
            'S.ARRAYS[n_raw].ITEMS = [ENTRY (KINT 0) (DIRECT (PSTRING $ptascii("Owner"))), ENTRY (KINT 1) (DIRECT (PSTRING $ptascii("sTaT")))]',
            'pcallcontext.RECEIVER = eps',
            'pcallcontext.LEXICAL_CLASS = (porigin_requested)',
            'pcallcontext.CALLED_CLASS = (porigin_called)',
            'pcallcontext.ARGC = 4',
            '$arginfo_values(S, pcallcontext) = [PINT 512, PSTRING $ptascii("forward"), PSTRING ptbytes_file, PINT perrorcall.LINE]',
            'pcallcontext_emitter.RECEIVER = (n_receiver)',
            'pcallcontext_emitter.LEXICAL_CLASS = (porigin_requested)',
            'pcallcontext_emitter.CALLED_CLASS = (porigin_called)',
            'pcallcontext_emitter.ARGC = 1',
            'pframe.LOCALS = (psymboltable)',
            '$arginfo_values(S[.ENV = psymboltable.ENV], pcallcontext_emitter) = [PSTRING $ptascii("x")]',
            'S.OBJECTS[n_receiver] = INSTANCE porigin_called',
            'porigin_requested =/= porigin_called',
            '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
            'pmethoddesc.STATIC',
            'pmethoddesc.OWNER = porigin_requested',
            '$effective_method(S, porigin_called, $ptascii("stat"), |S.CLASSES|) = (pmethoddesc_child)',
            'pmethoddesc_child.FUNCTION.ORIGIN =/= porigin_method',
            '$target_function(S, STATIC_METHOD_TARGET porigin_called porigin_method) = eps',
            'S_emitter = S[.CURRENT = pframe.CONTEXT][.FRAMES = pframe_tail*][.ORIGIN = pframe.ORIGIN][.TODO = pframe.TODO]',
            '$error_entered_call_valid(S_emitter, perrorcall)',
            '~$error_entered_call_valid(S_emitter, perrorcall[.TARGET = (HANDLER_METHOD_TARGET true porigin_requested $ptascii("sTaT") (SCOPED_TARGET porigin_requested porigin_method porigin_requested eps (KNOWN (PSTRING $ptascii("Owner")))))])',
            '$error_context_valid(S, pcallcontext)',
            '$target_nodes(pcallcontext.TARGET) = eps',
            '$error_selected_roots(perrorcall.TARGET) = eps',
            '$handler_implicit_receiver(S, porigin_requested) = eps',
            '$error_handler_target(S, perrorcall.CALLBACK) = (pcalltarget_current)',
            'pcalltarget_current =/= pcallcontext.TARGET',
            *VALID,
            '~$handler_kind_valid(false, pcalltarget)',
            '~$call_context_valid(S, pcallcontext[.CALLED_CLASS = (porigin_requested)], S.CVS)',
            '~$call_context_valid(S, pcallcontext[.RECEIVER = (n_receiver)], S.CVS)',
            *FINISH,
            '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
            '((HARRAY n_raw) <- $pools_nodes(S_done.POOLS) /\\ (HARRAY n_raw) <- S_done.ALLOCATIONS)',
        ],
    },
    'static-string-throw-keeps-replacement-and-trace': {
        'source': SOURCES['static-string-throw-trace-and-replacement'],
        'stage': ('S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* '
                  '-- if S.CURRENT = (pcallcontext) '
                  '-- if pcallcontext.TARGET = HANDLER_METHOD_TARGET true porigin_requested ptbytes pcalltarget'),
        'checks': [
            'S.CURRENT = (pcallcontext)',
            'S.FRAMES = pframe :: pframe_tail*',
            'pframe.CONTEXT = (pcallcontext_emitter)',
            'pframe.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_saved*',
            'perrorcall.CALLBACK = PSTRING ($ptascii("Child::rUn"))',
            'pcallcontext.TARGET = HANDLER_METHOD_TARGET true porigin_requested $ptascii("rUn") pcalltarget',
            'pcalltarget = SCOPED_TARGET porigin_requested porigin_method porigin_requested eps (KNOWN (PSTRING $ptascii("Child")))',
            'pcallcontext.LEXICAL_CLASS = (porigin_owner)',
            'porigin_owner =/= porigin_requested',
            'pcallcontext.CALLED_CLASS = (porigin_requested)',
            'pcallcontext.RECEIVER = eps',
            'pcallcontext.ARGC = 4',
            '$arginfo_values(S, pcallcontext) = [PINT 512, PSTRING $ptascii("outer"), PSTRING ptbytes_file, PINT perrorcall.LINE]',
            'pcallcontext_emitter.ARGC = 1',
            'pframe.LOCALS = (psymboltable)',
            '$arginfo_values(S[.ENV = psymboltable.ENV], pcallcontext_emitter) = [PINT 7]',
            'S.ERRORHANDLER.CALLBACK = (PARRAY n_replacement)',
            'S.ERRORHANDLER.LEVELS = 512',
            'S.ARRAYS[n_replacement].ITEMS = [ENTRY (KINT 0) (DIRECT (PSTRING $ptascii("Replacement"))), ENTRY (KINT 1) (DIRECT (PSTRING $ptascii("run")))]',
            '$error_handler_selected(S, perrorcall.CALLBACK, pcallcontext.TARGET)',
            '~$error_handler_selected(S, PSTRING $ptascii("Owner::rUn"), pcallcontext.TARGET)',
            '~$error_handler_selected(S, perrorcall.CALLBACK, HANDLER_METHOD_TARGET false porigin_requested $ptascii("rUn") pcalltarget)',
            '$error_context_valid(S, pcallcontext)',
            '$trace_context(S, S.ENV, S.CURRENT) = [ptraceframe_handler, ptraceframe_trigger]',
            'ptraceframe_handler.FUNCTION = $ptascii("run")',
            'ptraceframe_handler.CLASS = ($ptascii("Owner"))',
            'ptraceframe_handler.TYPE = ($ptascii("::"))',
            'ptraceframe_handler.FILE = eps',
            'ptraceframe_handler.ARGS = [(KINT 0, PINT 512), (KINT 1, PSTRING $ptascii("outer")), (KINT 2, PSTRING ptbytes_file), (KINT 3, PINT perrorcall.LINE)]',
            'ptraceframe_trigger.FUNCTION = $ptascii("trigger_error")',
            'ptraceframe_trigger.ARGS = [(KINT 0, PSTRING $ptascii("outer")), (KINT 1, PINT 512)]',
            *VALID,
            '~$error_context_valid(S, pcallcontext[.ARGC = 3])',
            '~$error_context_valid(S, pcallcontext[.CALLSITE = (porigin_method)])',
            '~$error_context_valid(S, pcallcontext[.LINE = $(perrorcall.LINE + 1)])',
            *FINISH,
            '$lookup(S_done.ENV, $ptascii("e")) = (n_error_cell)',
            'S_done.STORE[n_error_cell] = DEFINED (POBJECT n_error)',
            '$throwable_field(S_done, n_error, "trace") = PARRAY n_trace',
            '$trace_graph_valid(S_done, n_trace)',
            'S_done.ARRAYS[n_trace].ITEMS = [ENTRY (KINT 0) (DIRECT (PARRAY n_handler)), ENTRY (KINT 1) (DIRECT (PARRAY n_trigger)), ENTRY (KINT 2) (DIRECT (PARRAY n_emitter))]',
            '$trace_array_field(S_done, n_handler, $ptascii("class")) = PSTRING ($ptascii("Owner"))',
            '$trace_array_field(S_done, n_handler, $ptascii("type")) = PSTRING ($ptascii("::"))',
            '$trace_array_field(S_done, n_emitter, $ptascii("function")) = PSTRING ($ptascii("cause"))',
            '((HARRAY n_replacement) <- $pools_nodes(S_done.POOLS) /\\ (HARRAY n_replacement) <- S_done.ALLOCATIONS)',
        ],
    },
    'false-fallback-preserves-replacement-mask': {
        'source': SOURCES['method-array-false-fallback-keeps-live-replacement-mask'],
        'stage': 'S.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail*',
        'checks': [
            'S.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail*',
            'S.RESULT = KNOWN (PBOOL false)',
            'S.REPORTING = 0',
            'perrorcall.CALLBACK = PARRAY n_raw',
            'perrorcall.TARGET = (HANDLER_METHOD_TARGET false porigin_requested $ptascii("run") pcalltarget)',
            'pcalltarget = SCOPED_TARGET porigin_requested porigin_method porigin_requested (n_receiver) (KNOWN (PSTRING $ptascii("Owner")))',
            'S.ERRORHANDLER.CALLBACK = (PSTRING $ptascii("Replacement::run"))',
            'S.ERRORHANDLER.LEVELS = 1024',
            '~$error_handler_eligible(S, 512)',
            '$error_handler_eligible(S, 1024)',
            '$call_task_valid(S, ERROR_HANDLER_RESULT perrorcall)',
            '$error_handler_retained(S, perrorcall.CALLBACK)',
            'HOBJECT n_receiver <- $task_nodes(ERROR_HANDLER_RESULT perrorcall)',
            *VALID,
            '~$call_task_valid(S, ERROR_HANDLER_RESULT perrorcall[.LEVEL = 1024])',
            'PhpStep: S ~> S_one',
            'S_one.COMPLETION = NORMAL',
            'S_one.ERRORHANDLER = S.ERRORHANDLER',
            'S_one.EVENTS = S.EVENTS',
            'S_one.TODO = perrorcall.RESUME :: ptask_tail*',
            'S_one.RESULT = KNOWN PNULL',
            *FINISH,
            '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
            '~((HARRAY n_raw) <- S_done.ALLOCATIONS)',
        ],
    },
}


INI_OPTION_PREFIX = ""
FILE_CASES = [(
    'handler-pipe-null-selected-static', SOURCES['current-owned-restore-pipe-null-static-handler'].encode(),
    'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* -- if S.CURRENT = (pcallcontext) -- if S.FRAMES = pframe :: pframe_tail* -- if pframe.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_saved* -- if perrorcall.RESUME = CONFIG_INI_NULL_RESULT pconfigcall',
    [
        'S.CURRENT = (pcallcontext)',
        'S.FRAMES = pframe :: pframe_tail*',
        'pframe.CONTEXT = (pcallcontext_emitter)',
        'pframe.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_saved*',
        'pframe.BORROWEDREAD = eps',
        'perrorcall.RESUME = CONFIG_INI_NULL_RESULT pconfigcall',
        'perrorcall.LEVEL = 8192',
        'perrorcall.MESSAGE = $config_ini_null_message(pconfigcall)',
        'perrorcall.SITE = pconfigcall.SITE',
        'perrorcall.LINE = pconfigcall.LINE',
        'perrorcall.CALLBACK = PARRAY n_raw',
        'S.ARRAYS[n_raw].ITEMS = [ENTRY (KINT 0) (DIRECT (PSTRING $ptascii("Owner"))), ENTRY (KINT 1) (DIRECT (PSTRING $ptascii("handler")))]',
        'pcallcontext.TARGET = HANDLER_METHOD_TARGET true porigin_requested $ptascii("handler") pcalltarget',
        'pcalltarget = SCOPED_TARGET porigin_requested porigin_method porigin_called eps (KNOWN (PSTRING $ptascii("Owner")))',
        'perrorcall.TARGET = (pcallcontext.TARGET)',
        'pcallcontext.RECEIVER = eps',
        'pcallcontext.LEXICAL_CLASS = (porigin_requested)',
        'pcallcontext.CALLED_CLASS = (porigin_called)',
        'porigin_requested =/= porigin_called',
        'pcallcontext.ARGC = 4',
        '$arginfo_values(S, pcallcontext) = [PSTRING $ptascii("8192"), PSTRING perrorcall.MESSAGE, PSTRING ptbytes_file, PINT perrorcall.LINE]',
        'S.ERRORHANDLER.CALLBACK = eps',
        'pcallcontext_emitter.RECEIVER = (n_receiver)',
        'pcallcontext_emitter.LEXICAL_CLASS = (porigin_requested)',
        'pcallcontext_emitter.CALLED_CLASS = (porigin_called)',
        'S.OBJECTS[n_receiver] = INSTANCE porigin_called',
        'pframe.LOCALS = (psymboltable)',
        '$arginfo_values(S[.ENV = psymboltable.ENV], pcallcontext_emitter) = [PSTRING $ptascii("x")]',
        'pcallcontext_emitter.ARGC = 1',
        'pconfigcall.KIND = INTRINSIC_INI_RESTORE',
        'pconfigcall.INDEX = 1',
        'pconfigcall.SENT = [NAMED_SENT (KNOWN PNULL)]',
        '~pconfigcall.NAMED',
        'pconfigcall.PACKS = eps',
        'pconfigcall.SELECTION = eps',
        'pconfigcall.OWNER = (n_owner)',
        'S.OBJECTS[n_owner] = INTRINSICCLOSURE INTRINSIC_INI_RESTORE',
        '(HOBJECT n_owner) <- S.ALLOCATIONS',
        '(HOBJECT n_owner) <- $task_nodes(CONFIG_INI_NULL_RESULT pconfigcall)',
        '(HOBJECT n_owner) <- $task_nodes(ERROR_HANDLER_RESULT perrorcall)',
        'pconfigcall.SITE = PORIGIN n_unit pcpath',
        '$pipe_site(S, pconfigcall.SITE)',
        'porigin_child = PORIGIN n_unit (pcpath ++ [PCFIELD 0])',
        'z_send = $pipe_send_line(S, pconfigcall.SITE)',
        '$pipe_lines_valid(S[.ORIGIN = (pconfigcall.SITE)], pconfigcall.SITE, z_send, pconfigcall.LINE)',
        '$config_selected_valid(S, pconfigcall)',
        'S_emitter = S[.CURRENT = pframe.CONTEXT][.FRAMES = pframe_tail*][.ORIGIN = pframe.ORIGIN][.TODO = pframe.TODO][.BORROWEDREAD = pframe.BORROWEDREAD]',
        '$config_ini_null_valid(S_emitter, pconfigcall)',
        '$error_entered_call_valid(S_emitter, perrorcall)',
        '$error_context_valid(S, pcallcontext)',
        '$error_handler_selected(S, perrorcall.CALLBACK, pcallcontext.TARGET)',
        '$error_selected_roots(perrorcall.TARGET) = eps',
        '$target_nodes(pcallcontext.TARGET) = eps',
        '$error_context_trigger(S, pcallcontext) = (pconfigcall)',
        '~$typed_caller_strict(S)',
        '$trace_context(S, S.ENV, S.CURRENT) = [ptraceframe_handler, ptraceframe_restore]',
        'ptraceframe_handler.FUNCTION = $ptascii("handler")',
        'ptraceframe_handler.CLASS = ($ptascii("Owner"))',
        'ptraceframe_handler.TYPE = ($ptascii("::"))',
        'ptraceframe_handler.ARGS = [(KINT 0, PSTRING $ptascii("8192")), (KINT 1, PSTRING perrorcall.MESSAGE), (KINT 2, PSTRING ptbytes_file), (KINT 3, PINT perrorcall.LINE)]',
        'ptraceframe_restore.FUNCTION = $ptascii("ini_restore")',
        'ptraceframe_restore.ARGS = [(KINT 0, PNULL)]',
        '$call_descriptors_valid(S)',
        '$call_current_valid(S)',
        '$call_frames_valid(S, S.FRAMES)',
        '$class_state_valid(S)',
        '$heap_valid($heap_graph(S))',
        '~$config_ini_null_valid(S_emitter, pconfigcall[.OWNER = eps])',
        '~$config_ini_null_valid(S_emitter, pconfigcall[.LINE = $(pconfigcall.LINE + 1)])',
        '~$config_ini_null_valid(S_emitter, pconfigcall[.SENT = [NAMED_SENT (KNOWN (PBOOL false))]])',
        '~$config_ini_null_valid(S_emitter, pconfigcall[.SITE = porigin_child])',
        '~$pipe_lines_valid(S[.ORIGIN = (pconfigcall.SITE)], pconfigcall.SITE, $(z_send + 1), pconfigcall.LINE)',
        '~$error_entered_call_valid(S_emitter, perrorcall[.TARGET = (HANDLER_METHOD_TARGET true porigin_requested $ptascii("handler") (SCOPED_TARGET porigin_requested porigin_method porigin_requested eps (KNOWN (PSTRING $ptascii("Owner")))))])',
        '~$error_context_valid(S, pcallcontext[.ARGC = 3])',
        '~$error_context_valid(S, pcallcontext[.LINE = $(perrorcall.LINE + 1)])',
        '~$error_context_valid(S, pcallcontext[.RECEIVER = (n_receiver)])',
        'S_done = $drive(S, 5000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.TODO = eps',
        'S_done.CURRENT = eps',
        'S_done.FRAMES = eps',
        'S_done.BORROWEDREAD = eps',
        'S_done.ERRORHANDLER.CALLBACK = eps',
        'S_done.ERRORHANDLERS = eps',
        '~((HOBJECT n_owner) <- S_done.ALLOCATIONS)',
        '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
        '((HARRAY n_raw) <- $pools_nodes(S_done.POOLS) /\\ (HARRAY n_raw) <- S_done.ALLOCATIONS)',
        '$call_descriptors_valid(S_done)',
        '$class_state_valid(S_done)',
        '$heap_valid($heap_graph(S_done))',
        '$outputs(S_done.EVENTS) = $ptascii("Owner/Child:1:x|H4:8192:Owner/ChildZT|1:x")',
    ],
)]


def main():
    protocol.run(CASES, extra_inputs=(Path(__file__), CATALOGUE))
    import warnings
    warnings.filterwarnings("ignore", message="invalid escape sequence", category=SyntaxWarning)
    import include_mutable_protocol
    include_mutable_protocol.main(FILE_CASES, extra_inputs=(Path(__file__), CATALOGUE))


if __name__ == '__main__':
    main()
