"""Original-source ordinary Fiber retirement ownership and transfer checks."""
import argparse
import json
from pathlib import Path

import fiber_state_review as review

SOURCES = {row['id']: row['source'] for row in json.loads(
    Path(__file__).with_name('fiber_review_cases.json').read_text())}
VALID = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
         '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))']
PAUSE = ['S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
         'S_paused.TODO = S.TODO', 'S_paused.FIBERCALLERS = S.FIBERCALLERS',
         'S_paused.FIBERCLOSERS = S.FIBERCLOSERS',
         'S_paused.OBJECTS = S.OBJECTS', 'S_paused.ALLOCATIONS = S.ALLOCATIONS',
         'S_paused.DESTRUCTION = S.DESTRUCTION', 'S_paused.FIBERSEQ = S.FIBERSEQ',
         'S_done = $drive(S, 4000)',
         '$drive(S_paused[.COMPLETION = NORMAL], 4000) = S_done']
DONE = ['S_done.COMPLETION = NORMAL', 'S_done.TODO = eps',
        'S_done.CURRENT = eps', 'S_done.FRAMES = eps', 'S_done.HELD = eps',
        'S_done.ACTIVEFIBER = eps', 'S_done.FIBERCALLERS = eps',
        'S_done.FIBERCLOSERS = eps', 'S_done.DESTRUCTION.CALLS = eps',
        'S_done.DESTRUCTION.RELEASES = eps', 'S_done.DESTRUCTION.FRAMES = eps',
        'S_done.DESTRUCTION.OPERATIONS = eps', 'S_done.DESTRUCTION.CLEANUPS = eps',
        '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))']

CASES = {
    'return-owner-is-stored-before-raw-retirement': {
        'source': SOURCES['review-fiber-ordinary-return-owner-through-capture-suspension'],
        'stage': 'S.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_RETURN_FINISH pfiberfinish] -- if S.ACTIVEFIBER = (pfiberfinish.OBJECT) -- if $fiber_at(S, pfiberfinish.OBJECT) = (pfiber) -- if pfiber.VALUE = POBJECT n_result',
        'checks': [
            'n = pfiberfinish.OBJECT', 'pfiber.RETURNED',
            'pfiber.STATUS = FIBER_RUNNING', 'pfiber.FINISH = (pfiberfinish)',
            'pfiber.CALL = eps', 'pfiber.RAW = PNULL', 'pfiber.TARGET = eps',
            'pfiber.ENTRY = eps', 'pfiber.VM = eps',
            'pfiberfinish.PENDING = eps', 'pfiberfinish.SEQUENCE = pfiber.SEQUENCE',
            'S.CURRENT = eps', 'S.FRAMES = eps', 'S.ORIGIN = eps',
            'S.FIBERCLOSERS = eps', 'S.FIBERCALLERS = [pfibercaller]',
            'pfibercaller.API.SEQUENCE = pfiber.SEQUENCE',
            'pdestructionrelease.USER',
            'pdestructionrelease.JOBS = [DESTRUCTION_VALUE (HOBJECT n_callback)]',
            '$object_body(S.OBJECTS[n_callback]) = REALCLOSURE porigin_callback ([DIRECT (POBJECT n_capture)]) pstaticcell*',
            '$heap_owners($heap_graph(S), HOBJECT n_capture) = 1',
            '$heap_count(HOBJECT n_callback, $destruction_job_nodes(pdestructionrelease.JOBS)) = 1',
            '$heap_count(HOBJECT n_callback, $node_children(S, HOBJECT n)) = 0',
            '$heap_owners($heap_graph(S), HOBJECT n_callback) = 1',
            '$heap_count(HOBJECT n_result, $node_children(S, HOBJECT n)) = 1',
            '$heap_owners($heap_graph(S), HOBJECT n_result) = 1',
            '$task_nodes(FIBER_RETURN_FINISH pfiberfinish) = eps',
            '$destructor_release_valid(S, pdestructionrelease)',
            '$fiber_ordinary_finish_live(S, pfiberfinish)',
            '$fiber_ordinary_vm($fiber_vm(S), pfiberfinish, true)',
            '~$fiber_ordinary_vm($fiber_vm(S), pfiberfinish, false)',
            'S_kind = S[.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_THROW_FINISH pfiberfinish]]',
            '~$fiber_ordinary_finish_live(S_kind, pfiberfinish)',
            '~$call_descriptors_valid(S_kind)',
            'S_mixed = S[.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_RETURN_FINISH pfiberfinish, FIBER_THROW_FINISH pfiberfinish]]',
            '$fiber_finish_task_count(S_mixed.TODO, pfiberfinish) = 2',
            '~$fiber_ordinary_finish_live(S_mixed, pfiberfinish)',
            '~$call_descriptors_valid(S_mixed)',
            'S_mixed_close = S[.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_RETURN_FINISH pfiberfinish, FIBER_CALLBACK_FINISH pfiberfinish]]',
            '$fiber_finish_task_count(S_mixed_close.TODO, pfiberfinish) = 2',
            '~$fiber_ordinary_finish_live(S_mixed_close, pfiberfinish)',
            '~$call_descriptors_valid(S_mixed_close)',
            '~$fiber_ordinary_tasks([FIBER_RETURN_FINISH pfiberfinish, DISCARD], pfiberfinish, true)',
            '~$fiber_ordinary_carrier($fiber_put(S, n, pfiber[.RETURNED = false]), pfiberfinish)',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_callback) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_result) <- S_done.ALLOCATIONS)',
        ],
    },
    'pending-body-owner-survives-ordinary-resume-stamp': {
        'source': SOURCES['review-fiber-ordinary-body-error-capture-suspension-replacement'],
        'stage': 'S.TODO = (FIBER_CONTINUE pfiberapi) :: ptask_tail* -- if S.RESULT = KNOWN (PSTRING $ptascii("resumed")) -- if S.ACTIVEFIBER = (n) -- if $fiber_at(S, n) = (pfiber) -- if pfiber.FINISH = (pfiberfinish)',
        'checks': [
            '~pfiber.RETURNED', 'pfiber.VALUE = PNULL',
            'pfiber.STATUS = FIBER_RUNNING', 'pfiber.VM = eps',
            'pfiber.RAW = PNULL', 'pfiber.ENTRY = eps',
            'S.FIBERCLOSERS = eps', 'S.FIBERCALLERS = [pfibercaller]',
            'pfibercaller.API.KIND = (INTRINSIC_FIBER_RESUME)',
            'pfibercaller.API.SEQUENCE = pfiber.SEQUENCE',
            'pfiberfinish.SEQUENCE = pfiber.SEQUENCE',
            '$(pfiberapi.SEQUENCE < pfiberfinish.SEQUENCE)',
            'pfiberfinish.PENDING = (n_body)', '$throwable_member(S, n_body)',
            '$throwable_field(S, n_body, "message") = PSTRING $ptascii("body")',
            '$throwable_previous_id(S, n_body) = eps',
            '$task_nodes(FIBER_THROW_FINISH pfiberfinish) = [HOBJECT n_body]',
            '$fiber_finish_task_count(S.TODO, pfiberfinish) = 0',
            '$fiber_finish_frame_count(S.FRAMES, pfiberfinish) = 1',
            '$heap_owners($heap_graph(S), HOBJECT n_body) = 1',
            '$fiber_ordinary_finish_live(S, pfiberfinish)',
            '$fiber_ordinary_frames(S.FRAMES, pfiberfinish, false)',
            '~$fiber_ordinary_frames(S.FRAMES, pfiberfinish, true)',
            '~$fiber_ordinary_finish_live(S, pfiberfinish[.SEQUENCE = pfiberapi.SEQUENCE])',
            '$fiber_continue_valid(S, pfiberapi)',
            'S_stale = $fiber_put(S, n, pfiber[.FINISH = (pfiberfinish[.SEQUENCE = pfiberapi.SEQUENCE])])',
            '~$fiber_ordinary_finish_live(S_stale, pfiberfinish[.SEQUENCE = pfiberapi.SEQUENCE])',
            '~$call_descriptors_valid(S_stale)',
            *VALID,
            'S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
            'S_paused[.COMPLETION = NORMAL] = S',
            'S_done = $drive(S_paused[.COMPLETION = NORMAL], 4000)',
            *DONE,
            'S_done.OBJECTS[n] = FIBER pfiber_done',
            'pfiber_done.STATUS = FIBER_TERMINATED', 'pfiber_done.FAILED',
            '~pfiber_done.RETURNED', '~pfiber_done.GRACEFUL',
            'pfiber_done.VALUE = PNULL',
            '~((HOBJECT n) <- S_done.ALLOCATIONS)',
        ],
    },
    'forced-cleanup-keeps-defined-return-and-private-retirement': {
        'source': SOURCES['review-fiber-ordinary-suspended-cleanup-force-close-keeps-return-owner'],
        'stage': 'S.TODO = [FIBER_RETURN_FINISH pfiberfinish] -- if S.FIBERCLOSERS = [pfiberclose] -- if pfiberfinish.PENDING = (pfiberclose.EXIT) -- if $fiber_at(S, pfiberfinish.OBJECT) = (pfiber)',
        'checks': [
            'n = pfiberfinish.OBJECT', 'n_exit = pfiberclose.EXIT',
            'pfiber.RETURNED', 'pfiber.STATUS = FIBER_RUNNING',
            'pfiber.VALUE = POBJECT n_result',
            'pfiber.FINISH = (pfiberfinish)', 'pfiberfinish.SEQUENCE = pfiber.SEQUENCE',
            'pfiberclose.SEQUENCE = pfiber.SEQUENCE',
            'S.ACTIVEFIBER = (n)', 'S.CURRENT = eps', 'S.FRAMES = eps',
            'pfiber.CALL = eps', 'pfiber.RAW = PNULL', 'pfiber.ENTRY = eps',
            '~pfiber.FAILED', '~pfiber.GRACEFUL',
            '$fiber_close_boundary(S)', '$fiber_graceful_live(S, n_exit)',
            '$fiber_graceful_for(S, n, pfiber.SEQUENCE, n_exit)',
            '$task_nodes(FIBER_RETURN_FINISH pfiberfinish) = [HOBJECT n_exit]',
            '$heap_owners($heap_graph(S), HOBJECT n_exit) = 2',
            '$heap_owners($heap_graph(S), HOBJECT n_result) = 1',
            '$fiber_ordinary_finish_live(S, pfiberfinish)',
            '$call_task_valid(S, FIBER_RETURN_FINISH pfiberfinish)',
            '~$fiber_callback_finish_live(S, pfiberfinish)',
            'S_old_kind = S[.TODO = [FIBER_CALLBACK_FINISH pfiberfinish]]',
            '~$fiber_callback_finish_live(S_old_kind, pfiberfinish)',
            '~$call_task_valid(S_old_kind, FIBER_CALLBACK_FINISH pfiberfinish)',
            '~$call_descriptors_valid(S_old_kind)',
            'S_back = $drive_steps(S, 1)',
            '$fiber_at(S_back, n) = (pfiber_back)',
            'pfiber_back.STATUS = FIBER_TERMINATED', 'pfiber_back.RETURNED',
            'pfiber_back.VALUE = POBJECT n_result', '~pfiber_back.GRACEFUL',
            '~pfiber_back.FAILED', 'pfiber_back.FINISH = eps',
            'S_back.FIBERCLOSERS = eps',
            '$fiber_graceful_retiring(S_back, n_exit)',
            '~$fiber_graceful_live(S_back, n_exit)',
            '~$destructor_pending_valid(S_back, (n_exit))',
            '$call_descriptors_valid(S_back)', '$heap_valid($heap_graph(S_back))',
            *VALID, *PAUSE, *DONE,
            '$drive(S_back[.COMPLETION = NORMAL], 4000) = S_done',
            '~((HOBJECT n) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_exit) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_result) <- S_done.ALLOCATIONS)',
        ],
    },
}

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--case', action='append')
    args = parser.parse_args()
    review.CASES = CASES
    review.__file__ = str(Path(__file__).resolve())
    raise SystemExit(0 if review.run(args.case) else 1)
