"""Prepared original-source callback retirement states; execution is opt-in."""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'tests/semantics'))
import fiber_state_review as review

SOURCES = {row['id']: row['source'] for row in json.loads(
    Path(__file__).with_name('fiber_review_cases.json').read_text())}
VALID = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
         '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))']
PAUSE = ['S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
         'S_paused.TODO = S.TODO', 'S_paused.FIBERCLOSERS = S.FIBERCLOSERS',
         'S_paused.FIBERCALLERS = S.FIBERCALLERS',
         'S_paused.OBJECTS = S.OBJECTS', 'S_paused.ALLOCATIONS = S.ALLOCATIONS',
         'S_paused.DESTRUCTION = S.DESTRUCTION',
         'S_paused.FIBERSEQ = S.FIBERSEQ',
         'S_done = $drive(S, 4000)',
         '$drive(S_paused[.COMPLETION = NORMAL], 4000) = S_done']
DONE = ['S_done.COMPLETION = NORMAL', 'S_done.TODO = eps',
        'S_done.CURRENT = eps', 'S_done.FRAMES = eps', 'S_done.HELD = eps',
        'S_done.ACTIVEFIBER = eps', 'S_done.FIBERCALLERS = eps',
        'S_done.FIBERCLOSERS = eps', 'S_done.DESTRUCTION.CALLS = eps',
        'S_done.DESTRUCTION.RELEASES = eps', 'S_done.DESTRUCTION.FRAMES = eps',
        'S_done.DESTRUCTION.OPERATIONS = eps', 'S_done.DESTRUCTION.CLEANUPS = eps',
        '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))']

CASES = {
    'cached-callback-dtor-keeps-private-pending': {
        'source': SOURCES['review-fiber-close-cached-callback-last-capture'],
        'stage': 'S.TODO = (CONFIG_INVOKE pconfigcall) :: ptask_tail* -- if pconfigcall.KIND = INTRINSIC_FIBER_SUSPEND -- if S.CURRENT = (pcallcontext) -- if $destructor_context_kind(S, pcallcontext) -- if S.FIBERCLOSERS = [pfiberclose] -- if S.OBJECTS[pfiberclose.OBJECT] = FIBER pfiber -- if pfiber.FINISH = (pfiberfinish)',
        'checks': [
            'n = pfiberclose.OBJECT', 'n_exit = pfiberclose.EXIT',
            'S.ACTIVEFIBER = (n)', 'S.FIBERCALLERS = eps',
            'pfiber.STATUS = FIBER_RUNNING', '~pfiber.FAILED', '~pfiber.GRACEFUL',
            'pfiber.FINISH = (pfiberfinish)', 'pfiberfinish.OBJECT = n',
            'pfiberfinish.SEQUENCE = pfiber.SEQUENCE',
            'pfiberfinish.PENDING = (n_exit)', 'pfiber.VALUE = PNULL',
            'pfiber.RAW = PNULL', 'pfiber.CALL = eps', 'pfiber.TARGET = eps',
            'pfiber.ENTRY = eps', 'pfiber.VM = eps',
            '$node_children(S, HOBJECT n) = eps',
            '~$fiber_cache_valid(S, n, pfiber)', '$fiber_record_valid(S, n, pfiber)',
            '$fiber_closing(S, (n))', '$fiber_close_boundary(S)',
            '$fiber_callback_finish_live(S, pfiberfinish)',
            '~$fiber_callback_finish_valid(S, pfiberfinish)',
            '$fiber_finishing_frames(S.FRAMES, pfiberfinish)',
            'S.FRAMES = [pframe_root]',
            'pframe_root.CONTEXT = eps', 'pframe_root.LOCALS = ($empty_table())',
            'pframe_root.TODO = (DESTRUCTOR_RESULT pdestructorcall) :: ptask_root*',
            'pdestructorcall.USER', 'pdestructorcall.CALLER = eps',
            'S_root = $constant_frame_scope(S, pframe_root, eps)',
            '$destructor_result_valid(S_root, pdestructorcall)',
            '$call_saved_context_valid(S_root, pframe_root)',
            'pframe_source = pframe_root[.ORIGIN = (pcallcontext.FUNCTION)]',
            '~$call_saved_context_valid($constant_frame_scope(S, pframe_source, eps), pframe_source)',
            '~$call_frames_valid(S, [pframe_source])',
            '~$call_saved_context_valid(S_root[.DESTRUCTION.CALLS = eps], pframe_root)',
            'pframe_no_finish = pframe_root[.TODO = [DESTRUCTOR_RESULT pdestructorcall]]',
            '~$call_saved_context_valid($constant_frame_scope(S, pframe_no_finish, eps), pframe_no_finish)',
            '~$call_frames_valid(S, [pframe_no_finish])',
            '~$fiber_finishing_tasks(S.TODO, pfiberfinish)',
            '$task_nodes(FIBER_CALLBACK_FINISH pfiberfinish) = [HOBJECT n_exit]',
            '$heap_count(HOBJECT n_exit, $fiber_close_nodes(S.FIBERCLOSERS)) = 1',
            '$heap_owners($heap_graph(S), HOBJECT n_exit) = 2',
            '$fiber_graceful_live(S, n_exit)', '$throwable_live(S, n_exit)',
            '~$throwable_member(S, n_exit)', '$destructor_pending_valid(S, (n_exit))',
            '$destructor_context_valid(S, pcallcontext)',
            '~$fiber_context_kind(S, pcallcontext)', '$fiber_caller_trace(S) = eps',
            '~$fiber_callback_finish_live(S, pfiberfinish[.SEQUENCE = S.FIBERSEQ])',
            '~$fiber_callback_finish_live(S, pfiberfinish[.PENDING = eps])',
            '~$fiber_callback_finish_live(S, pfiberfinish[.OBJECT = |S.OBJECTS|])',
            '~$fiber_finishing_tasks([FIBER_CALLBACK_FINISH pfiberfinish, FIBER_CALLBACK_FINISH pfiberfinish], pfiberfinish)',
            '~$fiber_finishing_tasks([FIBER_CALLBACK_FINISH pfiberfinish, DISCARD], pfiberfinish)',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_exit) <- S_done.ALLOCATIONS)',
        ],
    },
    'cached-callback-continues-captures-after-real-error': {
        'source': SOURCES['review-fiber-close-cached-callback-ordered-replacements'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail* -- if $object_name(S, pdestructorcall.OBJECT) = $ptascii("FiberCloseCaptureB291") -- if S.FIBERCLOSERS = [pfiberclose] -- if S.OBJECTS[pfiberclose.OBJECT] = FIBER pfiber -- if pfiber.FINISH = (pfiberfinish) -- if pfiberfinish.PENDING = (n_a)',
        'checks': [
            'n = pfiberclose.OBJECT', 'S.ACTIVEFIBER = (n)',
            'S.CURRENT = eps', 'S.FRAMES = eps', 'S.FIBERCALLERS = eps',
            'pfiber.STATUS = FIBER_RUNNING', 'pfiber.RAW = PNULL',
            'pfiber.VALUE = PNULL', '~pfiber.FAILED', '~pfiber.GRACEFUL',
            'pfiberfinish.OBJECT = n', 'pfiberfinish.SEQUENCE = pfiber.SEQUENCE',
            'pdestructorcall.CALLER = eps', 'pdestructorcall.FRAME = eps',
            'pdestructorcall.PENDING = (n_a)', '$destructor_enter_valid(S, pdestructorcall)',
            '$fiber_callback_finish_live(S, pfiberfinish)',
            '$fiber_callback_finish_valid(S, pfiberfinish)',
            '$fiber_finishing_tasks(S.TODO, pfiberfinish)',
            '$throwable_field(S, n_a, "message") = PSTRING $ptascii("A")',
            '$throwable_previous_id(S, n_a) = (n_finally)',
            '$throwable_field(S, n_finally, "message") = PSTRING $ptascii("finally")',
            '$throwable_previous_id(S, n_finally) = eps',
            '$heap_owners($heap_graph(S), HOBJECT n_a) = 1',
            '$heap_owners($heap_graph(S), HOBJECT n_finally) = 1',
            '$heap_owners($heap_graph(S), HOBJECT pfiberclose.EXIT) = 1',
            '$task_nodes(FIBER_CALLBACK_FINISH pfiberfinish) = [HOBJECT n_a]',
            'pfiberfinish_wrong = pfiberfinish[.PENDING = (n_finally)]',
            '~$fiber_callback_finish_live(S, pfiberfinish_wrong)',
            '~$fiber_callback_finish_live($fiber_put(S, n, pfiber[.FINISH = (pfiberfinish_wrong)]), pfiberfinish_wrong)',
            '~$fiber_finishing_tasks([FIBER_CALLBACK_FINISH pfiberfinish, FIBER_CALLBACK_FINISH pfiberfinish], pfiberfinish)',
            '~$fiber_finishing_tasks([FIBER_CALLBACK_FINISH pfiberfinish, DISCARD], pfiberfinish)',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n) <- S_done.ALLOCATIONS)',
            '~((HOBJECT pfiberclose.EXIT) <- S_done.ALLOCATIONS)',
        ],
    },
    'cached-callback-finish-parks-in-real-api-caller': {
        'source': SOURCES['review-fiber-close-cached-callback-other-fiber'],
        'stage': 'S.FIBERCLOSERS = [pfiberclose] -- if S.FIBERCALLERS = [pfibercaller] -- if S.CURRENT = (pcallcontext) -- if $fiber_context_kind(S, pcallcontext) -- if S.OBJECTS[pfiberclose.OBJECT] = FIBER pfiber -- if pfiber.FINISH = (pfiberfinish)',
        'checks': [
            'n_parent = pfiberclose.OBJECT', 'n_child = pfibercaller.OBJECT',
            'n_exit = pfiberclose.EXIT', 'S.ACTIVEFIBER = (n_child)',
            'n_parent =/= n_child', 'pfibercaller.PREVIOUS = (n_parent)',
            'pfiberclose.PREVIOUS = eps', 'pfiberclose.CALLERS = 0',
            'pfiber.STATUS = FIBER_RUNNING', 'pfiber.VM = eps',
            'pfiber.RAW = PNULL', 'pfiber.CALL = eps', 'pfiber.TARGET = eps',
            'pfiberfinish.OBJECT = n_parent', 'pfiberfinish.PENDING = (n_exit)',
            'pfiberfinish.SEQUENCE = pfiber.SEQUENCE',
            '$fiber_finishing_callers(S.FIBERCALLERS, pfiberfinish)',
            '$fiber_finishing_frames(pfibercaller.VM.FRAMES, pfiberfinish)',
            'pfibercaller.VM.DESTRUCTORCALLS =/= eps',
            'S.DESTRUCTION.CALLS = eps',
            '$fiber_callback_finish_live(S, pfiberfinish)',
            '~$fiber_callback_finish_valid(S, pfiberfinish)',
            '~$fiber_close_boundary(S)', '$fiber_close_valid(S, pfiberclose)',
            '$fiber_callers_valid(S, (n_child), S.FIBERCALLERS, eps)',
            '$fiber_graceful_live(S, n_exit)', '~$throwable_live(S, n_exit)',
            '$destructor_pending_valid(S, (n_exit))',
            '$heap_owners($heap_graph(S), HOBJECT n_exit) = 2',
            '$heap_owners($heap_graph(S), HOBJECT n_parent) = 2',
            '$node_children(S, HOBJECT n_parent) = eps',
            'S.OBJECTS[n_child] = FIBER pfiber_child',
            'pfiber_child.STATUS = FIBER_RUNNING', 'pfiber_child.FINISH = eps',
            '$fiber_cache_valid(S, n_child, pfiber_child)',
            'pfibervm_without_finish = pfibercaller.VM[.FRAMES = eps]',
            '~$fiber_callback_finish_live(S[.FIBERCALLERS = [pfibercaller[.VM = pfibervm_without_finish]]], pfiberfinish)',
            '~$call_descriptors_valid(S[.FIBERCALLERS = [pfibercaller[.VM = pfibervm_without_finish]]])',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n_parent) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_exit) <- S_done.ALLOCATIONS)',
        ],
    },
    'cached-callback-error-keeps-stored-result-owner': {
        'source': SOURCES['review-fiber-close-cached-callback-retains-failed-result'],
        'stage': 'S.TODO = (CONFIG_INVOKE pconfigcall) :: ptask_tail* -- if pconfigcall.KIND = INTRINSIC_FIBER_RETURN -- if pconfigcall.OWNER = (n) -- if S.OBJECTS[n] = FIBER pfiber -- if pfiber.FAILED -- if pfiber.VALUE = POBJECT n_returned',
        'checks': [
            'S.ACTIVEFIBER = eps', 'S.FIBERCALLERS = eps', 'S.FIBERCLOSERS = eps',
            'pfiber.STATUS = FIBER_TERMINATED', '~pfiber.GRACEFUL',
            'pfiber.FINISH = eps', 'pfiber.RAW = PNULL',
            'pfiber.CALL = eps', 'pfiber.TARGET = eps',
            'pfiber.ENTRY = eps', 'pfiber.VM = eps',
            'n <- S.DESTRUCTION.CALLED',
            '$object_name(S, n_returned) = $ptascii("FiberCloseReturnedObject291")',
            '~(n_returned <- S.DESTRUCTION.CALLED)',
            '(HOBJECT n) <- S.ALLOCATIONS', '(HOBJECT n_returned) <- S.ALLOCATIONS',
            '$node_children(S, HOBJECT n) = [HOBJECT n_returned]',
            '$heap_owners($heap_graph(S), HOBJECT n_returned) = 1',
            '$fiber_record_valid(S, n, pfiber)',
            '~$fiber_record_valid(S, n, pfiber[.GRACEFUL = true])',
            'pfiberfinish_forged = {OBJECT n, PENDING eps, SEQUENCE pfiber.SEQUENCE}',
            '~$fiber_record_valid(S, n, pfiber[.FINISH = (pfiberfinish_forged)])',
            '~$fiber_callback_finish_live(S, pfiberfinish_forged)',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_returned) <- S_done.ALLOCATIONS)',
            'n_returned <- S_done.DESTRUCTION.CALLED',
        ],
    },
    'cached-callback-nested-error-preserves-original-release': {
        'source': SOURCES['review-fiber-close-cached-callback-nested-pending-order'],
        'stage': 'S.TODO = (DESTRUCTOR_RELEASE pdestructionrelease) :: ptask_tail* -- if pdestructionrelease.JOBS = (DESTRUCTION_VALUE (HOBJECT n_child)) :: pdestructionjob* -- if S.OBJECTS[n_child] = FIBER pfiber_child -- if pfiber_child.STATUS = FIBER_TERMINATED -- if pfiber_child.FAILED -- if S.FIBERCLOSERS = [pfiberclose] -- if S.OBJECTS[pfiberclose.OBJECT] = FIBER pfiber -- if pfiber.FINISH = (pfiberfinish) -- if pfiberfinish.PENDING = (n_error) -- if $throwable_field(S, n_error, "message") = PSTRING $ptascii("inner")',
        'checks': [
            'n_parent = pfiberclose.OBJECT', 'n_child =/= n_parent',
            'S.ACTIVEFIBER = (n_parent)', 'S.FIBERCALLERS = eps',
            'S.CURRENT = eps', 'S.FRAMES = eps',
            'pfiber.STATUS = FIBER_RUNNING', 'pfiber.RAW = PNULL',
            'pfiberfinish.OBJECT = n_parent',
            '$fiber_callback_finish_valid(S, pfiberfinish)',
            '$fiber_release_finish(S.TODO) = (pfiberfinish)',
            'S.DESTRUCTION.RELEASES = pdestructionrelease :: pdestructionrelease_tail*',
            '$destructor_release_valid(S, pdestructionrelease)',
            'pdestructionrelease.USER',
            '(HOBJECT n_child) <- S.ALLOCATIONS',
            'n_child <- S.DESTRUCTION.CALLED',
            'pfiber_child.FINISH = eps', 'pfiber_child.RAW = PNULL',
            'pfiber_child.VM = eps', 'pfiber_child.VALUE = PNULL',
            '$fiber_record_valid(S, n_child, pfiber_child)',
            '$heap_owners($heap_graph(S), HOBJECT n_child) = 1',
            '$heap_owners($heap_graph(S), HOBJECT n_error) = 1',
            '$throwable_previous_id(S, n_error) = (n_outer)',
            '$throwable_field(S, n_outer, "message") = PSTRING $ptascii("outer")',
            '$throwable_previous_id(S, n_outer) = eps',
            '$heap_owners($heap_graph(S), HOBJECT n_outer) = 1',
            '$heap_owners($heap_graph(S), HOBJECT pfiberclose.EXIT) = 1',
            '$task_nodes(FIBER_CALLBACK_FINISH pfiberfinish) = [HOBJECT n_error]',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n_parent) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_child) <- S_done.ALLOCATIONS)',
        ],
    },
    'cached-callback-private-error-escapes-without-source': {
        'source': SOURCES['review-fiber-close-cached-callback-private-error-trace-foreach'],
        'stage': 'S.TODO = (CATCH_BIND porigin n_index n_error) :: ptask_tail* -- if S.OBJECTS[n_error] = THROWABLE pthrowable -- if pthrowable.ORIGIN = eps -- if pthrowable.FILEORIGIN = eps',
        'checks': [
            'S.ACTIVEFIBER = eps', 'S.FIBERCALLERS = eps',
            'S.FIBERCLOSERS = eps', 'S.CURRENT = eps', 'S.FRAMES = eps',
            'pthrowable.KIND = "Error"',
            '$throwable_field(S, n_error, "file") = PSTRING $ptascii("[no active file]")',
            '$throwable_field(S, n_error, "line") = PINT 0',
            '$throwable_field(S, n_error, "trace") = PARRAY n_trace',
            'S.ARRAYS[n_trace].ITEMS = eps',
            '$throwable_previous_id(S, n_error) = eps',
            '(HOBJECT n_error) <- S.ALLOCATIONS',
            '$heap_owners($heap_graph(S), HOBJECT n_error) = 1',
            '$fiber_root_error_source(S, n_error, pthrowable)',
            '$throwable_source_origin_valid(S, n_error, pthrowable)',
            '$throwable_slots_valid(S, n_error, pthrowable)',
            '$closure_live_object_valid(S, n_error)',
            '~$fiber_root_error_source(S[.FIBERSEQ = 1], n_error, pthrowable)',
            '~$closure_live_object_valid(S[.FIBERSEQ = 1], n_error)',
            '~$fiber_root_error_source(S, n_error, pthrowable[.KIND = "Exception"])',
            '~$fiber_root_error_source(S, n_error, pthrowable[.ORIGIN = (porigin)])',
            '~$fiber_root_error_source(S, n_error, pthrowable[.FILEORIGIN = (porigin)])',
            '$objectprops_record_at(S.OBJECTPROPS, n_error) = (pobjectprops)',
            'ppropertyslot_forged* = $property_slot_set(pobjectprops.SLOTS, $throwable_key("Error", "line"), PROP_VALUE (DIRECT (PINT 1)))',
            'S_forged = S[.OBJECTPROPS = $objectprops_set(S.OBJECTPROPS, n_error, ppropertyslot_forged*)]',
            '~$fiber_root_error_source(S_forged, n_error, pthrowable)',
            '~$closure_live_object_valid(S_forged, n_error)',
            *VALID, *PAUSE, *DONE,
        ],
    },
    'cached-callback-parks-real-handler-operation-and-cleanup': {
        'source': SOURCES['review-fiber-close-error-handler-result-starts-child'],
        'stage': 'S.FIBERCLOSERS = [pfiberclose] -- if S.FIBERCALLERS = [pfibercaller] -- if S.CURRENT = (pcallcontext) -- if $fiber_context_kind(S, pcallcontext) -- if S.OBJECTS[pfiberclose.OBJECT] = FIBER pfiber -- if pfiber.FINISH = (pfiberfinish)',
        'checks': [
            'n_parent = pfiberclose.OBJECT', 'n_child = pfibercaller.OBJECT',
            'S.ACTIVEFIBER = (n_child)', 'pfibercaller.PREVIOUS = (n_parent)',
            'pfiberclose.PREVIOUS = eps', 'pfiberclose.CALLERS = 0',
            'pfibercaller.VM.DESTRUCTORCALLS =/= eps',
            'pfibercaller.VM.DESTRUCTORRELEASES =/= eps',
            'pfiberclose.VM.DESTRUCTOROPERATIONS = [pdestructionoperation]',
            'pfiberclose.VM.DESTRUCTORCLEANUPS = [pdestructioncleanup]',
            'pdestructionoperation.SOURCE = ERROR_HANDLER_RESULT perrorcall',
            'pdestructionoperation.CLEANUP = (pdestructioncleanup)',
            'pdestructioncleanup.SOURCE = ERROR_HANDLER_RESULT perrorcall',
            '~pdestructioncleanup.RELEASED',
            'S.DESTRUCTION.CALLS = eps', 'S.DESTRUCTION.RELEASES = eps',
            'S.DESTRUCTION.FRAMES = eps', 'S.DESTRUCTION.OPERATIONS = eps',
            'S.DESTRUCTION.CLEANUPS = eps',
            'S.DESTRUCTION.PHASE = DESTRUCTION_PENDING',
            'S.DESTRUCTION.ABANDONED = eps', 'S.DESTRUCTION.PROPCACHE = eps',
            '$fiber_callback_finish_live(S, pfiberfinish)',
            '$fiber_vm_valid(S, pfiberclose.VM, eps, eps)',
            '$fiber_close_valid(S, pfiberclose)',
            'S_view = $fiber_vm_restore(S, pfiberclose.VM)[.ACTIVEFIBER = eps][.FIBERCALLERS = eps]',
            'S_view.DESTRUCTION.PHASE = S.DESTRUCTION.PHASE',
            'S_view.DESTRUCTION.HANDLES = S.DESTRUCTION.HANDLES',
            'S_view.DESTRUCTION.FREE = S.DESTRUCTION.FREE',
            'S_view.DESTRUCTION.NEXT = S.DESTRUCTION.NEXT',
            'S_view.DESTRUCTION.CALLED = S.DESTRUCTION.CALLED',
            'S_view.DESTRUCTION.PROPCACHE = S.DESTRUCTION.PROPCACHE',
            'S_view.DESTRUCTION.ABANDONED = S.DESTRUCTION.ABANDONED',
            '$destructor_operation_valid(S_view, pdestructionoperation)',
            '$eager_cleanup_valid(S_view, pdestructioncleanup)',
            'pfibervm_no_operation = pfiberclose.VM[.DESTRUCTOROPERATIONS = eps]',
            '~$fiber_vm_valid(S, pfibervm_no_operation, eps, eps)',
            '~$call_descriptors_valid(S[.FIBERCLOSERS = [pfiberclose[.VM = pfibervm_no_operation]]])',
            'pfibervm_no_cleanup = pfiberclose.VM[.DESTRUCTORCLEANUPS = eps]',
            '~$fiber_vm_valid(S, pfibervm_no_cleanup, eps, eps)',
            '~$call_descriptors_valid(S[.FIBERCLOSERS = [pfiberclose[.VM = pfibervm_no_cleanup]]])',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n_parent) <- S_done.ALLOCATIONS)',
            'S_done.ERRORHANDLER.CALLBACK = eps',
            'S_done.ERRORHANDLERS = eps',
        ],
    },
    'force-close-parks-real-frame-pending-owner': {
        'source': SOURCES['review-fiber-close-frame-retirement-exception-chain'],
        'stage': 'S.FIBERCLOSERS = [pfiberclose] -- if pfiberclose.VM.DESTRUCTORFRAMES = [pdestructionframe] -- if S.CURRENT = (pcallcontext) -- if $fiber_context_kind(S, pcallcontext) -- if S.OBJECTS[pfiberclose.OBJECT] = FIBER pfiber -- if pdestructionframe.PENDING = (n_outer)',
        'checks': [
            'n = pfiberclose.OBJECT', 'S.ACTIVEFIBER = (n)',
            'S.FIBERCALLERS = eps', 'pfiberclose.PREVIOUS = eps',
            'pfiberclose.CALLERS = 0', 'pfiber.STATUS = FIBER_RUNNING',
            'pfiber.FINISH = eps', '$fiber_cache_valid(S, n, pfiber)',
            'S.DESTRUCTION.FRAMES = eps',
            '$fiber_close_valid(S, pfiberclose)',
            '$fiber_vm_valid(S, pfiberclose.VM, eps, eps)',
            '$destructor_release_frame(pfiberclose.VM.TODO, pdestructionframe)',
            'pdestructionframe.VALUE = KNOWN PNULL',
            '$task_nodes(DESTRUCTOR_FRAME_EXIT pdestructionframe) = [HOBJECT n_outer]',
            '$heap_owners($heap_graph(S), HOBJECT n_outer) = 1',
            '$throwable_field(S, n_outer, "message") = PSTRING $ptascii("outer")',
            '$throwable_previous_id(S, n_outer) = eps',
            '$heap_owners($heap_graph(S), HOBJECT n) = 1',
            'S_view = $fiber_vm_restore(S, pfiberclose.VM)[.ACTIVEFIBER = eps][.FIBERCALLERS = eps]',
            '$destructor_frame_valid(S_view, pdestructionframe)',
            'S_view.DESTRUCTION.HANDLES = S.DESTRUCTION.HANDLES',
            'S_view.DESTRUCTION.CALLED = S.DESTRUCTION.CALLED',
            'S_view.DESTRUCTION.PROPCACHE = S.DESTRUCTION.PROPCACHE',
            'S_view.DESTRUCTION.ABANDONED = S.DESTRUCTION.ABANDONED',
            'pfibervm_no_frame = pfiberclose.VM[.DESTRUCTORFRAMES = eps]',
            '~$fiber_vm_valid(S, pfibervm_no_frame, eps, eps)',
            '~$call_descriptors_valid(S[.FIBERCLOSERS = [pfiberclose[.VM = pfibervm_no_frame]]])',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n) <- S_done.ALLOCATIONS)',
        ],
    },
    'cached-callback-late-resurrection-keeps-return-owner': {
        'source': SOURCES['review-fiber-close-cached-callback-late-resurrection'],
        'stage': 'S.TODO = [FIBER_CALLBACK_FINISH pfiberfinish] -- if pfiberfinish.PENDING = eps -- if S.FIBERCLOSERS = [pfiberclose] -- if S.OBJECTS[pfiberfinish.OBJECT] = FIBER pfiber',
        'checks': [
            'n = pfiberfinish.OBJECT', 'n = pfiberclose.OBJECT',
            'S.ACTIVEFIBER = (n)', 'S.CURRENT = eps', 'S.FRAMES = eps',
            'S.FIBERCALLERS = eps', 'pfiber.STATUS = FIBER_RUNNING',
            'pfiber.RAW = PNULL', 'pfiber.CALL = eps', 'pfiber.TARGET = eps',
            'pfiber.VM = eps', 'pfiber.VALUE = PINT 7',
            '~pfiber.FAILED', '~pfiber.GRACEFUL',
            '$node_children(S, HOBJECT n) = eps',
            '$task_nodes(FIBER_CALLBACK_FINISH pfiberfinish) = eps',
            '$fiber_callback_finish_valid(S, pfiberfinish)',
            '$fiber_callback_ready(S)', '$fiber_record_valid(S, n, pfiber)',
            '$heap_owners($heap_graph(S), HOBJECT n) = 2',
            '$heap_owners($heap_graph(S), HOBJECT pfiberclose.EXIT) = 1',
            'S.DESTRUCTION.CALLS = eps', 'S.DESTRUCTION.RELEASES = eps',
            'S_back = $drive_steps(S, 1)', 'S_back.COMPLETION = BUDGET',
            'S_back.ACTIVEFIBER = eps', 'S_back.FIBERCLOSERS = eps',
            'S_back.TODO = (DESTRUCTOR_RELEASE pdestructionrelease_cleanup) :: (DESTRUCTOR_OPERATION_EXIT pdestructionoperation_cleanup) :: (DESTRUCTOR_RELEASE pfiberclose.RELEASE) :: ptask_back*',
            'pdestructionoperation_cleanup.SOURCE = FIBER_CALLBACK_FINISH pfiberfinish',
            'S_back.DESTRUCTION.OPERATIONS = pdestructionoperation_cleanup :: pdestructionoperation_tail*',
            '$destructor_operation_valid(S_back, pdestructionoperation_cleanup)',
            'pdestructionrelease_cleanup.JOBS = [DESTRUCTION_VALUE (HOBJECT pfiberclose.EXIT)]',
            'S_back.DESTRUCTION.RELEASES = [pdestructionrelease_cleanup, pfiberclose.RELEASE]',
            '$destructor_release_valid(S_back, pdestructionrelease_cleanup)',
            '$destructor_release_valid(S_back, pfiberclose.RELEASE)',
            'S_back.OBJECTS[n] = FIBER pfiber_back',
            'pfiber_back.STATUS = FIBER_TERMINATED', 'pfiber_back.FINISH = eps',
            'pfiber_back.VALUE = PINT 7', '~pfiber_back.FAILED', '~pfiber_back.GRACEFUL',
            '$fiber_record_valid(S_back, n, pfiber_back)',
            '$heap_owners($heap_graph(S_back), HOBJECT n) = 2',
            '$heap_owners($heap_graph(S_back), HOBJECT pfiberclose.EXIT) = 1',
            '~$fiber_graceful_live(S_back, pfiberclose.EXIT)',
            '~$throwable_live(S_back, pfiberclose.EXIT)',
            '~$destructor_pending_valid(S_back, (pfiberclose.EXIT))',
            '$fiber_live_node_valid(S_back, HOBJECT pfiberclose.EXIT)',
            '$closure_live_object_valid(S_back, pfiberclose.EXIT)',
            'S_no_release = S_back[.DESTRUCTION.RELEASES = [pfiberclose.RELEASE]]',
            '~$fiber_live_node_valid(S_no_release, HOBJECT pfiberclose.EXIT)',
            '~$call_descriptors_valid(S_no_release)',
            'S_no_producer = S_back[.TODO = (DESTRUCTOR_RELEASE pdestructionrelease_cleanup) :: (DESTRUCTOR_RELEASE pfiberclose.RELEASE) :: ptask_back*]',
            '~$fiber_live_node_valid(S_no_producer, HOBJECT pfiberclose.EXIT)',
            '~$call_descriptors_valid(S_no_producer)',
            'pfiberfinish_wrong = pfiberfinish[.SEQUENCE = S.FIBERSEQ]',
            'pdestructionoperation_wrong = pdestructionoperation_cleanup[.SOURCE = FIBER_CALLBACK_FINISH pfiberfinish_wrong]',
            'S_wrong = S_back[.TODO = (DESTRUCTOR_RELEASE pdestructionrelease_cleanup) :: (DESTRUCTOR_OPERATION_EXIT pdestructionoperation_wrong) :: (DESTRUCTOR_RELEASE pfiberclose.RELEASE) :: ptask_back*][.DESTRUCTION.OPERATIONS = pdestructionoperation_wrong :: pdestructionoperation_tail*]',
            '~$fiber_live_node_valid(S_wrong, HOBJECT pfiberclose.EXIT)',
            '~$call_descriptors_valid(S_wrong)',
            '$call_current_valid(S_back)', '$call_frames_valid(S_back, S_back.FRAMES)',
            '$call_descriptors_valid(S_back)', '$heap_valid($heap_graph(S_back))',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n) <- S_done.ALLOCATIONS)',
            '~((HOBJECT pfiberclose.EXIT) <- S_done.ALLOCATIONS)',
        ],
    },
    'cached-callback-finish-cannot-borrow-child-private-control': {
        'source': SOURCES['review-fiber-close-cached-callback-nested-pending-order'],
        'stage': 'S.FIBERCLOSERS = [pfiberclose_child, pfiberclose_parent] -- if S.TODO = (THROW_SEARCH n_exit) :: ptask_tail* -- if n_exit = pfiberclose_child.EXIT -- if S.OBJECTS[pfiberclose_parent.OBJECT] = FIBER pfiber_parent -- if pfiber_parent.FINISH = (pfiberfinish)',
        'checks': [
            'n_parent = pfiberclose_parent.OBJECT',
            'n_child = pfiberclose_child.OBJECT', 'n_parent =/= n_child',
            'S.ACTIVEFIBER = (n_child)', 'S.FIBERCALLERS = eps',
            'pfiberclose_child.PREVIOUS = (n_parent)',
            'pfiberclose_child.CALLERS = 0', 'pfiberclose_parent.CALLERS = 0',
            'pfiberfinish.OBJECT = n_parent',
            'pfiberfinish.PENDING = (n_outer)',
            '$throwable_field(S, n_outer, "message") = PSTRING $ptascii("outer")',
            '$fiber_callback_finish_live(S, pfiberfinish)',
            '~$fiber_callback_finish_valid(S, pfiberfinish)',
            '$fiber_finishing_vm(pfiberclose_child.VM, pfiberfinish)',
            '$fiber_graceful_live(S, n_exit)', '$throwable_live(S, n_exit)',
            '$fiber_throw_pending_valid(S, n_child, n_exit)',
            '~$fiber_throw_pending_valid(S, n_child, pfiberclose_parent.EXIT)',
            '$destructor_pending_valid(S, (n_exit))',
            '$fiber_graceful_live(S, pfiberclose_parent.EXIT)',
            '~$throwable_live(S, pfiberclose_parent.EXIT)',
            '$destructor_pending_valid(S, (pfiberclose_parent.EXIT))',
            'pfiberfinish_wrong = pfiberfinish[.PENDING = (n_exit)]',
            'pfibervm_wrong = pfiberclose_child.VM[.TODO = $fiber_finish_tasks(pfiberclose_child.VM.TODO, pfiberfinish, pfiberfinish_wrong)]',
            '$fiber_finishing_vm(pfibervm_wrong, pfiberfinish_wrong)',
            'S_wrong = $fiber_put(S[.FIBERCLOSERS = [pfiberclose_child[.VM = pfibervm_wrong], pfiberclose_parent]], n_parent, pfiber_parent[.FINISH = (pfiberfinish_wrong)])',
            '~$fiber_callback_finish_live(S_wrong, pfiberfinish_wrong)',
            '~$fiber_record_valid(S_wrong, n_parent, pfiber_parent[.FINISH = (pfiberfinish_wrong)])',
            '~$call_descriptors_valid(S_wrong)',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n_parent) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_child) <- S_done.ALLOCATIONS)',
        ],
    },
    'retiring-private-control-keeps-native-release-multiplicity': {
        'source': SOURCES['review-fiber-close-cached-callback-last-capture'],
        'stage': 'S.TODO = (DESTRUCTOR_RELEASE pdestructionrelease) :: (DESTRUCTOR_OPERATION_EXIT pdestructionoperation) :: ptask_tail* -- if pdestructionoperation.SOURCE = FIBER_CALLBACK_FINISH pfiberfinish -- if pfiberfinish.PENDING = (n_exit) -- if pdestructionrelease.JOBS = [DESTRUCTION_VALUE (HOBJECT n_exit), DESTRUCTION_VALUE (HOBJECT n_exit)] -- if S.OBJECTS[pfiberfinish.OBJECT] = FIBER pfiber -- if pfiber.STATUS = FIBER_TERMINATED',
        'checks': [
            'n = pfiberfinish.OBJECT',
            'S.OBJECTS[n_exit] = FIBERGRACEFUL n pfiberfinish.SEQUENCE',
            'pfiber.SEQUENCE = pfiberfinish.SEQUENCE', 'pfiber.FINISH = eps',
            'pfiber.GRACEFUL', '~pfiber.FAILED', 'pfiber.VALUE = PNULL',
            'pfiber.RAW = PNULL', 'pfiber.CALL = eps', 'pfiber.VM = eps',
            'S.ACTIVEFIBER = eps', 'S.FIBERCALLERS = eps', 'S.FIBERCLOSERS = eps',
            'ptask_tail* = (DESTRUCTOR_RELEASE pdestructionrelease_fiber) :: ptask_rest*',
            'pdestructionrelease_fiber.JOBS = [DESTRUCTION_VALUE (HOBJECT n)]',
            'S.DESTRUCTION.RELEASES = [pdestructionrelease, pdestructionrelease_fiber]',
            'S.DESTRUCTION.OPERATIONS = pdestructionoperation :: pdestructionoperation_tail*',
            '$destructor_release_valid(S, pdestructionrelease)',
            '$destructor_operation_valid(S, pdestructionoperation)',
            '$heap_owners($heap_graph(S), HOBJECT n_exit) = 2',
            '$heap_owners($heap_graph(S), HOBJECT n) = 1',
            '~$fiber_graceful_live(S, n_exit)', '~$throwable_live(S, n_exit)',
            '~$destructor_pending_valid(S, (n_exit))',
            '$fiber_live_node_valid(S, HOBJECT n_exit)',
            '$closure_live_object_valid(S, n_exit)',
            'S_alias = S[.RESULT = KNOWN (POBJECT n_exit)]',
            '$heap_owners($heap_graph(S_alias), HOBJECT n_exit) = 3',
            '~$fiber_live_node_valid(S_alias, HOBJECT n_exit)',
            '~$call_descriptors_valid(S_alias)',
            'S_wrong = $fiber_put(S, n, pfiber[.GRACEFUL = false])',
            '~$fiber_live_node_valid(S_wrong, HOBJECT n_exit)',
            '~$call_descriptors_valid(S_wrong)',
            'S_one = $drive_steps(S, 1)', 'S_one.COMPLETION = BUDGET',
            'pdestructionrelease_one = pdestructionrelease[.JOBS = [DESTRUCTION_VALUE (HOBJECT n_exit)]]',
            'S_one.TODO = (DESTRUCTOR_RELEASE pdestructionrelease_one) :: (DESTRUCTOR_OPERATION_EXIT pdestructionoperation) :: ptask_tail*',
            'S_one.DESTRUCTION.RELEASES = [pdestructionrelease_one, pdestructionrelease_fiber]',
            'S_one.DESTRUCTION.OPERATIONS = S.DESTRUCTION.OPERATIONS',
            '(HOBJECT n_exit) <- S_one.ALLOCATIONS',
            '$heap_owners($heap_graph(S_one), HOBJECT n_exit) = 1',
            '$fiber_live_node_valid(S_one, HOBJECT n_exit)',
            '$closure_live_object_valid(S_one, n_exit)',
            '~$fiber_graceful_live(S_one, n_exit)', '~$throwable_live(S_one, n_exit)',
            '~$destructor_pending_valid(S_one, (n_exit))',
            '$call_descriptors_valid(S_one)', '$heap_valid($heap_graph(S_one))',
            *VALID, *PAUSE, *DONE,
            '$drive(S_one[.COMPLETION = NORMAL], 4000) = S_done',
            '~((HOBJECT n) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_exit) <- S_done.ALLOCATIONS)',
        ],
    },
}

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--case', action='append')
    args = parser.parse_args()
    review.CASES = CASES
    review.__file__ = str(Path(__file__).resolve())
    raise SystemExit(0 if review.run(args.case) else 1)
