"""Independent protected Fiber completion ownership and diagnostic states."""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'tests/semantics'))
import fiber_state_review as review
from fiber_retirement_review import VALID, DONE

SOURCES = {row['id']: row['source'] for row in json.loads(
    Path(__file__).with_name('fiber_review_cases.json').read_text())}
FOCUSED_FINALLY = SOURCES['review-fiber-protected-defined-result-finally-replacement-focused']
PAUSE = ['S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
         'S_paused[.COMPLETION = NORMAL] = S',
         'S_done = $drive(S_paused[.COMPLETION = NORMAL], 4000)']
PREVIOUS_STAGE = 'S.TODO = (FIBER_PROTECTED_PREVIOUS pdestructorcall n_exit) :: (DESTRUCTOR_RESULT pdestructorcall) :: ptask_tail* -- if $fiber_release_finish(ptask_tail*) = (pfiberfinish) -- if S.OBJECTS[pfiberfinish.OBJECT] = FIBER pfiber -- if pfiberfinish.PENDING = (n_old)'
ROOT_CHECKS = [
    'n = pfiberfinish.OBJECT', 'S.ACTIVEFIBER = (n)',
    'S.CURRENT = eps', 'S.FRAMES = eps', 'S.ORIGIN = eps',
    'S.CONSTCONTEXT = eps', 'S.FIBERCALLERS = eps',
    'S.FIBERCLOSERS = [pfiberclose]',
    'pfiberclose.OBJECT = n', 'pfiberclose.EXIT = n_exit',
    'pfiberclose.SEQUENCE = pfiberfinish.SEQUENCE',
    'pfiberclose.CALLERS = 0', 'pfiberclose.PREVIOUS = eps',
    'pfiberfinish.PROTECTED = eps',
    'pfiber.STATUS = FIBER_RUNNING', 'pfiber.RETURNED',
    '~pfiber.FAILED', '~pfiber.GRACEFUL', 'pfiber.VM = eps',
    'pfiber.RAW = PNULL', 'pfiber.CALL = eps', 'pfiber.TARGET = eps',
    'pfiber.ENTRY = eps', 'pfiber.FINISH = (pfiberfinish)',
    'pfiber.SEQUENCE = pfiberfinish.SEQUENCE',
    'S.OBJECTS[n_exit] = FIBERGRACEFUL n pfiber.SEQUENCE',
    'pdestructorcall.PENDING = (n_old)',
    'S.DESTRUCTION.CALLS = pdestructorcall :: pdestructorcall_tail*',
    'pdestructorcall.USER', '~pdestructorcall.STORE',
    'pdestructorcall.CALLER = eps', 'pdestructorcall.ORIGIN = eps',
    'pdestructorcall.CONSTCONTEXT = eps',
    'pdestructorcall.FRAME = eps', 'pdestructorcall.OPERATION = eps',
    '$throwable_member(S, n_old)',
    '$fiber_graceful_for(S, n, pfiber.SEQUENCE, n_exit)',
    '$fiber_ordinary_finish_live(S, pfiberfinish)',
    '$fiber_finish_task_count(S.TODO, pfiberfinish) = 1',
    '$fiber_protected_previous_valid(S, pdestructorcall, n_exit)',
    '$call_task_valid(S, FIBER_PROTECTED_PREVIOUS pdestructorcall n_exit)',
    '$task_nodes(FIBER_PROTECTED_PREVIOUS pdestructorcall n_exit) = [HOBJECT n_exit]',
    '$task_nodes(DESTRUCTOR_RESULT pdestructorcall) = [HOBJECT pdestructorcall.OBJECT]',
    '$task_nodes(FIBER_RETURN_FINISH pfiberfinish) = [HOBJECT n_old]',
    '$objectprops_at(S.OBJECTPROPS, n_exit) = eps',
    '$node_children(S, HOBJECT n_exit) = eps',
    '$heap_owners($heap_graph(S), HOBJECT n_old) = 1',
    '$heap_owners($heap_graph(S), HOBJECT n_exit) = 2',
]
COPY_CHECKS = [
    'S_copy_reached = $drive_steps(S, 1)',
    'S_copy_reached.COMPLETION = BUDGET',
    'S_copy = S_copy_reached[.COMPLETION = NORMAL]',
    'S_copy.OBJECTS[n] = FIBER pfiber_copy',
    'pfiber_copy.FINISH = (pfiberfinish_copy)',
    'pfiberfinish_copy = pfiberfinish[.PENDING = (n_exit)][.PROTECTED = ((n_exit, n_old))]',
    '$fiber_protected_receipt(S_copy, pfiberfinish_copy) = ((n_exit, n_old))',
    '$fiber_finish_protected_valid(S_copy, pfiberfinish_copy)',
    'pfiber_copy.RETURNED', 'pfiber_copy.VALUE = pfiber.VALUE',
    'S_copy.DESTRUCTION.CALLS = pdestructorcall_tail*',
    '$fiber_control_previous(S_copy, n_exit) = (n_old)',
    '$fiber_control_previous_valid(S_copy, n_exit, n_old)',
    '$node_children(S_copy, HOBJECT n_exit) = [HOBJECT n_old]',
    '$heap_owners($heap_graph(S_copy), HOBJECT n_old) = 1',
    '$heap_owners($heap_graph(S_copy), HOBJECT n_exit) = 2',
    '~$fiber_protected_previous_ready(S_copy)',
    '$call_descriptors_valid(S_copy)', '$heap_valid($heap_graph(S_copy))',
]

ORDINARY_RECEIPT_CHECKS = [
    'n = pfiberfinish.OBJECT', 'S.ACTIVEFIBER = (n)',
    'S.FIBERCLOSERS = eps', 'S.CURRENT = eps', 'S.FRAMES = eps',
    'pfiber.STATUS = FIBER_RUNNING', 'pfiber.FINISH = (pfiberfinish)',
    'pfiberfinish.PROTECTED = eps',
    '$fiber_finish_protected_valid(S, pfiberfinish)',
    '$fiber_protected_receipt(S, pfiberfinish) = eps',
    '$fiber_ordinary_finish_live(S, pfiberfinish)',
    '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))',
    '$(n < n_candidate)', '(HOBJECT n_candidate) <- S.ALLOCATIONS',
    'pfiberfinish_forged = pfiberfinish[.PROTECTED = ((n_candidate, n))]',
]


def ordinary_receipt_forgery_checks(kind):
    return [
        'S_forged = $fiber_put(S[.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, ' + kind + ' pfiberfinish_forged]], n, pfiber[.FINISH = (pfiberfinish_forged)])',
        '$fiber_finish_task_count(S_forged.TODO, pfiberfinish_forged) = 1',
        '$heap_graph(S_forged) = $heap_graph(S)',
        '$fiber_protected_receipt(S_forged, pfiberfinish_forged) = eps',
        '~$fiber_finish_protected_valid(S_forged, pfiberfinish_forged)',
        '~$fiber_ordinary_carrier(S_forged, pfiberfinish_forged)',
        '~$call_task_valid(S_forged, ' + kind + ' pfiberfinish_forged)',
        '~$call_descriptors_valid(S_forged)',
    ]


CASES = {
    'private-previous-cannot-transplant-another-live-real-throwable': {
        'source': SOURCES['review-fiber-protected-previous-real-chain-release-order'],
        'stage': 'S.TODO = [FIBER_RETURN_FINISH pfiberfinish] -- if S.FIBERCLOSERS = [pfiberclose] -- if pfiberfinish.PENDING = (pfiberclose.EXIT) -- if $fiber_control_previous(S, pfiberclose.EXIT) = (n_old) -- if $throwable_previous_id(S, n_old) = (n_root) -- if $fiber_at(S, pfiberfinish.OBJECT) = (pfiber)',
        'checks': [
            'n_exit = pfiberclose.EXIT', 'n = pfiberfinish.OBJECT',
            'pfiber.RETURNED', 'pfiber.STATUS = FIBER_RUNNING',
            'pfiber.VALUE = POBJECT n_result',
            '$throwable_member(S, n_old)', '$throwable_member(S, n_root)',
            '$throwable_field(S, n_old, "message") = PSTRING $ptascii("early")',
            '$throwable_field(S, n_root, "message") = PSTRING $ptascii("root")',
            'n_root =/= n_old', '$(n_root < n_exit)', '$(n_old < n_exit)',
            '$heap_owners($heap_graph(S), HOBJECT n_old) = 1',
            '$heap_owners($heap_graph(S), HOBJECT n_root) = 1',
            '$fiber_control_previous_valid(S, n_exit, n_old)',
            *VALID,
            'pfiberfinish_wrong_receipt = pfiberfinish[.PROTECTED = ((n_exit, n_root))]',
            'S_wrong_receipt = $fiber_put(S[.TODO = [FIBER_RETURN_FINISH pfiberfinish_wrong_receipt]], n, pfiber[.FINISH = (pfiberfinish_wrong_receipt)])',
            '~$fiber_finish_protected_valid(S_wrong_receipt, pfiberfinish_wrong_receipt)',
            '~$fiber_control_previous_valid(S_wrong_receipt, n_exit, n_old)',
            '~$call_descriptors_valid(S_wrong_receipt)',
            'pfiberfinish_no_receipt = pfiberfinish[.PROTECTED = eps]',
            'S_no_receipt = $fiber_put(S[.TODO = [FIBER_RETURN_FINISH pfiberfinish_no_receipt]], n, pfiber[.FINISH = (pfiberfinish_no_receipt)])',
            '~$fiber_control_previous_valid(S_no_receipt, n_exit, n_old)',
            '~$call_descriptors_valid(S_no_receipt)',
            'S_transplant = S[.OBJECTPROPS = $objectprops_set(S.OBJECTPROPS, n_exit, [{DECL eps, NAME $ptascii("previous"), STATE PROP_VALUE (DIRECT (POBJECT n_root))}])]',
            '~$fiber_control_previous_valid(S_transplant, n_exit, n_root)',
            '~$call_descriptors_valid(S_transplant)',
        ],
    },
    'previous-write-preserves-real-producer-and-transfers-one-owner': {
        'source': SOURCES['review-fiber-protected-previous-child-destructs-on-caller'],
        'stage': PREVIOUS_STAGE,
        'checks': [
            *ROOT_CHECKS,
            'pfiber.VALUE = POBJECT n_result',
            '$heap_owners($heap_graph(S), HOBJECT n_result) = 1',
            'pfiberfinish_forged = pfiberfinish[.PROTECTED = ((n_exit, n_old))]',
            'S_forged = $fiber_put(S[.TODO = (FIBER_PROTECTED_PREVIOUS pdestructorcall n_exit) :: (DESTRUCTOR_RESULT pdestructorcall) :: $fiber_finish_tasks(ptask_tail*, pfiberfinish, pfiberfinish_forged)], n, pfiber[.FINISH = (pfiberfinish_forged)])',
            '~$fiber_finish_protected_valid(S_forged, pfiberfinish_forged)',
            '~$fiber_protected_previous_valid(S_forged, pdestructorcall, n_exit)',
            '~$call_descriptors_valid(S_forged)',
            '~$class_instanceof(S, POBJECT n_exit, $ptascii("Throwable"))',
            '~$class_instanceof(S, POBJECT n_exit, $ptascii("Error"))',
            '~$fiber_protected_previous_valid(S[.DESTRUCTION.CALLS = eps], pdestructorcall, n_exit)',
            '~$call_descriptors_valid(S[.DESTRUCTION.CALLS = eps])',
            '~$fiber_protected_previous_valid(S[.FIBERCLOSERS = eps], pdestructorcall, n_exit)',
            '~$fiber_protected_previous_valid(S[.ACTIVEFIBER = eps], pdestructorcall, n_exit)',
            '~$fiber_protected_previous_valid(S, pdestructorcall, n_old)',
            'pdestructorcall_wrong = pdestructorcall[.RELEASE = eps]',
            'S_wrong_producer = S[.TODO = (FIBER_PROTECTED_PREVIOUS pdestructorcall_wrong n_exit) :: (DESTRUCTOR_RESULT pdestructorcall_wrong) :: ptask_tail*][.DESTRUCTION.CALLS = pdestructorcall_wrong :: pdestructorcall_tail*]',
            '~$fiber_protected_previous_valid(S_wrong_producer, pdestructorcall_wrong, n_exit)',
            '~$call_descriptors_valid(S_wrong_producer)',
            'S_wrong_stamp = $fiber_put(S, n, pfiber[.SEQUENCE = S.FIBERSEQ])',
            '~$fiber_protected_previous_valid(S_wrong_stamp, pdestructorcall, n_exit)',
            '~$call_descriptors_valid(S_wrong_stamp)',
            'S_duplicate = S[.TODO = (FIBER_PROTECTED_PREVIOUS pdestructorcall n_exit) :: (FIBER_PROTECTED_PREVIOUS pdestructorcall n_exit) :: (DESTRUCTOR_RESULT pdestructorcall) :: ptask_tail*]',
            '~$fiber_protected_previous_valid(S_duplicate, pdestructorcall, n_exit)',
            '~$call_descriptors_valid(S_duplicate)',
            *COPY_CHECKS,
            '$heap_owners($heap_graph(S_copy), HOBJECT n_result) = 1',
            'S_copy.EVENTS = S.EVENTS ++ [DIAGNOSTIC_INTERNAL "Deprecated" $ptascii("Creation of dynamic property GracefulExit::$previous is deprecated") 0]',
            'S_copy.ERRORHANDLER = S.ERRORHANDLER',
            'S_copy.ERRORHANDLERS = S.ERRORHANDLERS',
            'S_wrong_child = S_copy[.OBJECTPROPS = $objectprops_set(S_copy.OBJECTPROPS, n_exit, ([{DECL eps, NAME $ptascii("previous"), STATE PROP_VALUE (DIRECT (POBJECT n_result))}]))]',
            '~$fiber_control_previous_valid(S_wrong_child, n_exit, n_result)',
            '~$call_descriptors_valid(S_wrong_child)',
            'S_self_child = S_copy[.OBJECTPROPS = $objectprops_set(S_copy.OBJECTPROPS, n_exit, ([{DECL eps, NAME $ptascii("previous"), STATE PROP_VALUE (DIRECT (POBJECT n_exit))}]))]',
            '~$fiber_control_previous_valid(S_self_child, n_exit, n_exit)',
            '~$call_descriptors_valid(S_self_child)',
            'S_wrong_name = S_copy[.OBJECTPROPS = $objectprops_set(S_copy.OBJECTPROPS, n_exit, ([{DECL eps, NAME $ptascii("other"), STATE PROP_VALUE (DIRECT (POBJECT n_old))}]))]',
            '~$fiber_control_properties(S_wrong_name, n_exit)',
            '~$call_descriptors_valid(S_wrong_name)',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n_exit) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_old) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_result) <- S_done.ALLOCATIONS)',
        ],
    },
    'real-null-result-cannot-change-to-undefined-protected-mode': {
        'source': SOURCES['review-fiber-protected-null-result-keeps-definedness'],
        'stage': PREVIOUS_STAGE + ' -- if ptask_tail* = (DESTRUCTOR_RELEASE pdestructionrelease) :: [FIBER_RETURN_FINISH pfiberfinish]',
        'checks': [
            *ROOT_CHECKS, 'pfiber.VALUE = PNULL',
            'S_no_return = $fiber_put(S, n, pfiber[.RETURNED = false])',
            '~$fiber_protected_previous_valid(S_no_return, pdestructorcall, n_exit)',
            '~$call_descriptors_valid(S_no_return)',
            'S_mode = $fiber_put(S[.TODO = (FIBER_PROTECTED_PREVIOUS pdestructorcall n_exit) :: (DESTRUCTOR_RESULT pdestructorcall) :: (DESTRUCTOR_RELEASE pdestructionrelease) :: [FIBER_THROW_FINISH pfiberfinish]], n, pfiber[.RETURNED = false])',
            '$fiber_ordinary_finish_live(S_mode, pfiberfinish)',
            '~$fiber_protected_previous_valid(S_mode, pdestructorcall, n_exit)',
            '~$call_descriptors_valid(S_mode)',
            *COPY_CHECKS,
            'pfiber_copy.VALUE = PNULL',
            'S_private_wrong = $fiber_put(S_copy, n, pfiber_copy[.RETURNED = false])',
            '~$fiber_ordinary_carrier(S_private_wrong, pfiberfinish_copy)',
            '~$fiber_control_previous_valid(S_private_wrong, n_exit, n_old)',
            '~$call_descriptors_valid(S_private_wrong)',
            'S_missing_property = S_copy[.OBJECTPROPS = $objectprops_prune(S_copy.OBJECTPROPS, $destruction_node_delete(S_copy.ALLOCATIONS, HOBJECT n_exit))]',
            '~$fiber_control_previous_valid(S_missing_property, n_exit, n_old)',
            *VALID, *PAUSE, *DONE,
            'S_done.OBJECTS[n] = FIBER pfiber_done',
            'pfiber_done.RETURNED', '~pfiber_done.GRACEFUL', '~pfiber_done.FAILED',
            'pfiber_done.VALUE = PNULL', 'pfiber_done.FINISH = eps',
        ],
    },
    'retiring-private-control-keeps-previous-child-and-genuine-release-count': {
        'source': SOURCES['review-fiber-protected-previous-child-destructs-on-caller'],
        'stage': 'S.TODO = (DESTRUCTOR_RELEASE pdestructionrelease) :: (DESTRUCTOR_OPERATION_EXIT pdestructionoperation) :: ptask_tail* -- if pdestructionoperation.SOURCE = FIBER_RETURN_FINISH pfiberfinish -- if pfiberfinish.PENDING = (n_exit) -- if pdestructionrelease.JOBS = [DESTRUCTION_VALUE (HOBJECT n_exit), DESTRUCTION_VALUE (HOBJECT n_exit)] -- if S.OBJECTS[pfiberfinish.OBJECT] = FIBER pfiber -- if pfiber.STATUS = FIBER_TERMINATED -- if $fiber_control_previous(S, n_exit) = (n_old)',
        'checks': [
            'n = pfiberfinish.OBJECT', 'pfiber.FINISH = eps',
            'pfiber.RETURNED', '~pfiber.FAILED', '~pfiber.GRACEFUL',
            'pfiber.VALUE = POBJECT n_result',
            'S.ACTIVEFIBER = eps', 'S.FIBERCALLERS = eps', 'S.FIBERCLOSERS = eps',
            'S.OBJECTS[n_exit] = FIBERGRACEFUL n pfiber.SEQUENCE',
            '$fiber_graceful_retiring(S, n_exit)',
            '~$fiber_graceful_live(S, n_exit)', '~$throwable_live(S, n_exit)',
            '~$destructor_pending_valid(S, (n_exit))',
            '$fiber_control_previous_valid(S, n_exit, n_old)',
            'pfiberfinish.PROTECTED = ((n_exit, n_old))',
            '$fiber_finish_protected_valid(S, pfiberfinish)',
            'S.DESTRUCTION.OPERATIONS = pdestructionoperation :: pdestructionoperation_tail*',
            'pfiberfinish_wrong_receipt = pfiberfinish[.PROTECTED = ((n_old, n_exit))]',
            'pdestructionoperation_wrong = pdestructionoperation[.SOURCE = FIBER_RETURN_FINISH pfiberfinish_wrong_receipt]',
            'S_wrong_receipt = S[.TODO = (DESTRUCTOR_RELEASE pdestructionrelease) :: (DESTRUCTOR_OPERATION_EXIT pdestructionoperation_wrong) :: ptask_tail*][.DESTRUCTION.OPERATIONS = pdestructionoperation_wrong :: pdestructionoperation_tail*]',
            '~$fiber_finish_protected_valid(S_wrong_receipt, pfiberfinish_wrong_receipt)',
            '~$fiber_control_previous_valid(S_wrong_receipt, n_exit, n_old)',
            '~$call_descriptors_valid(S_wrong_receipt)',
            '$node_children(S, HOBJECT n_exit) = [HOBJECT n_old]',
            '$heap_owners($heap_graph(S), HOBJECT n_exit) = 2',
            '$heap_owners($heap_graph(S), HOBJECT n_old) = 1',
            '$heap_owners($heap_graph(S), HOBJECT n_result) = 1',
            'S_alias = S[.RESULT = KNOWN (POBJECT n_exit)]',
            '~$fiber_graceful_retiring(S_alias, n_exit)',
            '~$fiber_control_previous_valid(S_alias, n_exit, n_old)',
            '~$call_descriptors_valid(S_alias)',
            'S_one = $drive_steps(S, 1)', 'S_one.COMPLETION = BUDGET',
            '$heap_owners($heap_graph(S_one), HOBJECT n_exit) = 1',
            '$heap_owners($heap_graph(S_one), HOBJECT n_old) = 1',
            '$fiber_graceful_retiring(S_one, n_exit)',
            '$fiber_control_previous_valid(S_one, n_exit, n_old)',
            '$call_descriptors_valid(S_one)', '$heap_valid($heap_graph(S_one))',
            'S_after_control = $drive_steps(S_one[.COMPLETION = NORMAL], 1)',
            'S_after_control.COMPLETION = BUDGET',
            '~((HOBJECT n_exit) <- S_after_control.ALLOCATIONS)',
            '$fiber_finish_protected_valid(S_after_control, pfiberfinish)',
            '$call_descriptors_valid(S_after_control)',
            '$heap_valid($heap_graph(S_after_control))',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n_exit) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_old) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_result) <- S_done.ALLOCATIONS)',
        ],
    },
    'previous-exception-destructor-enters-on-restored-caller': {
        'source': SOURCES['review-fiber-protected-previous-child-destructs-on-caller'],
        'stage': 'S.TODO = (CONFIG_INVOKE pconfigcall) :: ptask_tail* -- if pconfigcall.KIND = INTRINSIC_FIBER_CURRENT -- if S.ACTIVEFIBER = eps -- if S.CURRENT = (pcallcontext) -- if $destructor_context_call(pcallcontext, S.CURRENT, S.FRAMES) = (pdestructorcall) -- if $throwable_member(S, pdestructorcall.OBJECT) -- if $throwable_field(S, pdestructorcall.OBJECT, "message") = PSTRING $ptascii("early")',
        'checks': [
            'S.FIBERCALLERS = eps', 'S.FIBERCLOSERS = eps',
            'n_old = pdestructorcall.OBJECT', 'pdestructorcall.USER',
            '~pdestructorcall.STORE', 'pdestructorcall.PENDING = eps',
            '$destructor_context_valid(S, pcallcontext)',
            '$heap_owners($heap_graph(S), HOBJECT n_old) = 2',
            'psymboltable_global = $fiber_globals(S)',
            '$lookup(psymboltable_global.ENV, $ptascii("saved")) = (n_saved)',
            'S.STORE[n_saved] = DEFINED (POBJECT n)',
            'S.OBJECTS[n] = FIBER pfiber',
            'pfiber.STATUS = FIBER_TERMINATED', 'pfiber.RETURNED',
            '~pfiber.FAILED', '~pfiber.GRACEFUL', 'pfiber.FINISH = eps',
            'pfiber.VALUE = POBJECT n_result',
            '$heap_owners($heap_graph(S), HOBJECT n_result) = 1',
            '~(n_result <- S.DESTRUCTION.CALLED)',
            'S.FRAMES = pframe :: pframe_tail*',
            'S_parent = $constant_frame_scope(S, pframe, eps)',
            '$call_saved_context_valid(S_parent, pframe)',
            '$destructor_result_valid(S_parent, pdestructorcall)',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n_old) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_result) <- S_done.ALLOCATIONS)',
        ],
    },
    'deprecation-uses-restored-fiber-mask-and-restores-caller-mask': {
        'source': SOURCES['review-fiber-protected-deprecation-restores-parked-reporting-mask'],
        'stage': PREVIOUS_STAGE,
        'checks': [
            *ROOT_CHECKS, 'pfiber.VALUE = PNULL',
            'S.REPORTING = 30719', 'pfiberclose.VM.REPORTING = 0',
            '~$error_handler_eligible(S, 8192)',
            *COPY_CHECKS,
            'S_copy.EVENTS = S.EVENTS ++ [DIAGNOSTIC_INTERNAL "Deprecated" $ptascii("Creation of dynamic property GracefulExit::$previous is deprecated") 0]',
            'S_copy.REPORTING = S.REPORTING',
            *VALID, *PAUSE, *DONE,
            'S_done.REPORTING = 0',
        ],
    },
    'reporting-zero-skips-display-without-dropping-previous-write': {
        'source': SOURCES['review-fiber-protected-deprecation-reporting-zero-no-handler'],
        'stage': PREVIOUS_STAGE,
        'checks': [
            *ROOT_CHECKS, 'S.REPORTING = 0',
            '~$error_handler_eligible(S, 8192)',
            *COPY_CHECKS, 'S_copy.EVENTS = S.EVENTS',
            'S_copy.ERRORHANDLER = S.ERRORHANDLER',
            *VALID, *PAUSE, *DONE,
        ],
    },
    'eligible-shared-handler-remains-unentered-during-private-control': {
        'source': SOURCES['review-fiber-protected-deprecation-uses-shared-late-handler'],
        'stage': PREVIOUS_STAGE,
        'checks': [
            *ROOT_CHECKS, '$error_handler_eligible(S, 8192)',
            'S.ERRORHANDLER.CALLBACK = (POBJECT n_handler)',
            '$heap_owners($heap_graph(S), HOBJECT n_handler) = 1',
            *COPY_CHECKS, 'S_copy.EVENTS = S.EVENTS',
            'S_copy.ERRORHANDLER = S.ERRORHANDLER',
            'S_copy.ERRORHANDLERS = S.ERRORHANDLERS',
            'S_copy.FRAMES = S.FRAMES', 'S_copy.CURRENT = S.CURRENT',
            '$heap_owners($heap_graph(S_copy), HOBJECT n_handler) = 1',
            *VALID, *PAUSE, *DONE,
        ],
    },
    'finally-real-replacement-filters-control-and-keeps-old-real-directly': {
        'source': FOCUSED_FINALLY,
        'stage': 'S.TODO = [FIBER_RETURN_FINISH pfiberfinish] -- if pfiberfinish.PENDING = (n_new) -- if $throwable_field(S, n_new, "message") = PSTRING $ptascii("replacement") -- if S.FIBERCLOSERS = [pfiberclose] -- if S.OBJECTS[pfiberfinish.OBJECT] = FIBER pfiber -- if $throwable_previous_id(S, n_new) = (n_old)',
        'checks': [
            'n = pfiberfinish.OBJECT', 'n_exit = pfiberclose.EXIT',
            'S.ACTIVEFIBER = (n)', 'S.CURRENT = eps', 'S.FRAMES = eps',
            'S.ORIGIN = eps', 'pfiber.STATUS = FIBER_RUNNING',
            'pfiber.RETURNED', '~pfiber.GRACEFUL', '~pfiber.FAILED',
            'pfiber.VALUE = POBJECT n_result',
            '$heap_owners($heap_graph(S), HOBJECT n_result) = 1',
            '$task_nodes(FIBER_RETURN_FINISH pfiberfinish) = [HOBJECT n_new]',
            '$throwable_field(S, n_old, "message") = PSTRING $ptascii("early")',
            '$throwable_member(S, n_old)', '$throwable_member(S, n_new)',
            'pfiberfinish.PROTECTED = eps',
            '$throwable_field(S, n_new, "trace") = PARRAY n_new_trace',
            'S.ARRAYS[n_new_trace].ITEMS = [ENTRY (KINT 0) (DIRECT (PARRAY n_new_frame))]',
            '$entry_lookup(S.ARRAYS[n_new_frame].ITEMS, KSTRING $ptascii("function")) = (DIRECT (PSTRING $ptascii("__destruct")))',
            '$entry_lookup(S.ARRAYS[n_new_frame].ITEMS, KSTRING $ptascii("file")) = eps',
            '$throwable_field(S, n_old, "trace") = PARRAY n_old_trace',
            'S.ARRAYS[n_old_trace].ITEMS = [ENTRY (KINT 0) (DIRECT (PARRAY n_old_frame)), ENTRY (KINT 1) (DIRECT (PARRAY n_api_frame))]',
            '$entry_lookup(S.ARRAYS[n_old_frame].ITEMS, KSTRING $ptascii("function")) = (DIRECT (PSTRING $ptascii("__destruct")))',
            '$entry_lookup(S.ARRAYS[n_old_frame].ITEMS, KSTRING $ptascii("file")) = eps',
            '$entry_lookup(S.ARRAYS[n_api_frame].ITEMS, KSTRING $ptascii("function")) = (DIRECT (PSTRING $ptascii("start")))',
            '$entry_lookup(S.ARRAYS[n_api_frame].ITEMS, KSTRING $ptascii("file")) = (DIRECT (PSTRING ptbytes_file))',
            '$heap_owners($heap_graph(S), HOBJECT n_old) = 1',
            '$heap_owners($heap_graph(S), HOBJECT n_new) = 1',
            '$heap_owners($heap_graph(S), HOBJECT n_exit) = 1',
            '$objectprops_at(S.OBJECTPROPS, n_exit) = eps',
            '$node_children(S, HOBJECT n_exit) = eps',
            '$fiber_ordinary_finish_live(S, pfiberfinish)',
            'S_private_previous = $throwable_set_previous_id(S, n_new, (n_exit))',
            '~$throwable_previous_slot_valid(S_private_previous, POBJECT n_exit)',
            '~$call_descriptors_valid(S_private_previous)',
            *VALID, *PAUSE, *DONE,
            'S_done.OBJECTS[n] = FIBER pfiber_done',
            'pfiber_done.STATUS = FIBER_TERMINATED', 'pfiber_done.RETURNED',
            'pfiber_done.FAILED', '~pfiber_done.GRACEFUL',
            'pfiber_done.VALUE = POBJECT n_result',
            '~((HOBJECT n_result) <- S_done.ALLOCATIONS)',
        ],
    },
    'ordinary-return-cannot-invent-protected-previous-receipt': {
        'source': SOURCES['review-fiber-ordinary-return-owner-through-capture-suspension'],
        'stage': 'S.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_RETURN_FINISH pfiberfinish] -- if $fiber_at(S, pfiberfinish.OBJECT) = (pfiber) -- if pfiber.VALUE = POBJECT n_candidate',
        'checks': [
            *ORDINARY_RECEIPT_CHECKS, 'pfiber.RETURNED', 'pfiberfinish.PENDING = eps',
            '$object_name(S, n_candidate) = $ptascii("FiberOrdinaryReturned302")',
            '$heap_owners($heap_graph(S), HOBJECT n_candidate) = 1',
            *ordinary_receipt_forgery_checks('FIBER_RETURN_FINISH'),
        ],
    },
    'ordinary-body-throw-cannot-invent-protected-previous-receipt': {
        'source': SOURCES['review-fiber-ordinary-body-error-capture-suspension-replacement'],
        'stage': 'S.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_THROW_FINISH pfiberfinish] -- if $fiber_at(S, pfiberfinish.OBJECT) = (pfiber) -- if pfiberfinish.PENDING = (n_candidate) -- if $throwable_field(S, n_candidate, "message") = PSTRING $ptascii("body")',
        'checks': [
            *ORDINARY_RECEIPT_CHECKS, '~pfiber.RETURNED', 'pfiber.VALUE = PNULL',
            '$throwable_member(S, n_candidate)',
            '$heap_owners($heap_graph(S), HOBJECT n_candidate) = 1',
            *ordinary_receipt_forgery_checks('FIBER_THROW_FINISH'),
        ],
    },
}

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--case', action='append')
    args = parser.parse_args()
    review.CASES = CASES
    review.__file__ = str(Path(__file__).resolve())
    raise SystemExit(0 if review.run(args.case) else 1)
