"""Independent ordinary callback retirement ownership, scope and VM states."""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'tests/semantics'))
import fiber_state_review as review
from fiber_retirement_review import VALID, DONE

SOURCES = {row['id']: row['source'] for row in json.loads(
    Path(__file__).with_name('fiber_review_cases.json').read_text())}
PAUSE = ['S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
         'S_paused[.COMPLETION = NORMAL] = S',
         'S_done = $drive(S_paused[.COMPLETION = NORMAL], 4000)']

ROOT_CHECKS = [
    'n = pfiberfinish.OBJECT', 'S.ACTIVEFIBER = (n)',
    'S.CURRENT = eps', 'S.FRAMES = eps', 'S.ORIGIN = eps',
    'S.FIBERCLOSERS = eps', 'S.FIBERCALLERS = [pfibercaller]',
    'pfibercaller.OBJECT = n', 'pfibercaller.PREVIOUS = eps',
    'pfiber.STATUS = FIBER_RUNNING', 'pfiber.FINISH = (pfiberfinish)',
    'pfiber.SEQUENCE = pfiberfinish.SEQUENCE',
    'pfibercaller.API.SEQUENCE = pfiber.SEQUENCE',
    'pfiber.RAW = PNULL', 'pfiber.CALL = eps', 'pfiber.TARGET = eps',
    'pfiber.BIRTH = eps', 'pfiber.CAPTURE = eps', 'pfiber.PRODUCER = eps',
    'pfiber.ENTRY = eps', 'pfiber.VM = eps',
    '~pfiber.FAILED', '~pfiber.GRACEFUL',
    '~$fiber_cache_valid(S, n, pfiber)', '$fiber_record_valid(S, n, pfiber)',
    '$fiber_ordinary_finish_live(S, pfiberfinish)',
    '$fiber_callback_finish_valid(S, pfiberfinish)',
    '~$fiber_callback_finish_live(S, pfiberfinish)',
    '$fiber_release_finish(S.TODO) = (pfiberfinish)',
    '$destructor_release_valid(S, pdestructionrelease)',
    'pdestructionrelease.USER',
    'S.DESTRUCTION.RELEASES = pdestructionrelease :: pdestructionrelease_tail*',
]

CASES = {
    'body-throw-is-owned-before-capture-entry': {
        'source': SOURCES['review-fiber-ordinary-body-error-capture-suspension-replacement'],
        'stage': 'S.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_THROW_FINISH pfiberfinish] -- if S.OBJECTS[pfiberfinish.OBJECT] = FIBER pfiber -- if pfiberfinish.PENDING = (n_body) -- if $throwable_field(S, n_body, "message") = PSTRING $ptascii("body")',
        'checks': [
            *ROOT_CHECKS,
            '~pfiber.RETURNED', 'pfiber.VALUE = PNULL',
            'pfibercaller.API.KIND = eps', '$node_children(S, HOBJECT n) = eps',
            '$task_nodes(FIBER_THROW_FINISH pfiberfinish) = [HOBJECT n_body]',
            '$heap_owners($heap_graph(S), HOBJECT n_body) = 1',
            '$throwable_previous_id(S, n_body) = eps',
            '$throwable_member(S, n_body)',
            'S_wrong_kind = S[.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_RETURN_FINISH pfiberfinish]]',
            '~$fiber_ordinary_finish_live(S_wrong_kind, pfiberfinish)',
            '~$call_descriptors_valid(S_wrong_kind)',
            'S_duplicate = S[.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_THROW_FINISH pfiberfinish, FIBER_RETURN_FINISH pfiberfinish]]',
            '$fiber_finish_task_count(S_duplicate.TODO, pfiberfinish) = 2',
            '~$fiber_ordinary_finish_live(S_duplicate, pfiberfinish)',
            '~$call_descriptors_valid(S_duplicate)',
            'S_no_pending = $fiber_put(S[.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_THROW_FINISH pfiberfinish[.PENDING = eps]]], n, pfiber[.FINISH = (pfiberfinish[.PENDING = eps])])',
            '~$fiber_ordinary_finish_live(S_no_pending, pfiberfinish[.PENDING = eps])',
            '~$call_descriptors_valid(S_no_pending)',
            'S_false_availability = $fiber_put(S, n, pfiber[.RETURNED = true])',
            '~$fiber_record_valid(S_false_availability, n, pfiber[.RETURNED = true])',
            '~$call_descriptors_valid(S_false_availability)',
            *VALID, *PAUSE[:3],
        ],
    },
    'body-throw-paused-root-completes-after-capture-replacement': {
        'source': SOURCES['review-fiber-ordinary-body-error-capture-suspension-replacement'],
        'stage': 'S.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_THROW_FINISH pfiberfinish] -- if S.OBJECTS[pfiberfinish.OBJECT] = FIBER pfiber -- if pfiberfinish.PENDING = (n_body) -- if $throwable_field(S, n_body, "message") = PSTRING $ptascii("body")',
        'checks': [
            'n = pfiberfinish.OBJECT',
            *PAUSE, *DONE,
            '~((HOBJECT n) <- S_done.ALLOCATIONS)',
        ],
    },
    'null-body-return-with-real-cleanup-error-retains-availability': {
        'source': SOURCES['review-fiber-ordinary-null-return-availability-survives-cleanup-error'],
        'stage': 'S.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_RETURN_FINISH pfiberfinish] -- if S.OBJECTS[pfiberfinish.OBJECT] = FIBER pfiber -- if pfiberfinish.PENDING = (n_capture) -- if $throwable_field(S, n_capture, "message") = PSTRING $ptascii("capture")',
        'checks': [
            *ROOT_CHECKS,
            'pfiber.RETURNED', 'pfiber.VALUE = PNULL',
            'pfibercaller.API.KIND = (INTRINSIC_FIBER_RESUME)',
            '$node_children(S, HOBJECT n) = eps',
            '$task_nodes(FIBER_RETURN_FINISH pfiberfinish) = [HOBJECT n_capture]',
            '$heap_owners($heap_graph(S), HOBJECT n_capture) = 1',
            '$throwable_previous_id(S, n_capture) = eps',
            'S_wrong_kind = S[.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_THROW_FINISH pfiberfinish]]',
            '~$fiber_ordinary_finish_live(S_wrong_kind, pfiberfinish)',
            '~$call_descriptors_valid(S_wrong_kind)',
            'S_no_availability = $fiber_put(S, n, pfiber[.RETURNED = false])',
            '~$fiber_record_valid(S_no_availability, n, pfiber[.RETURNED = false])',
            '~$call_descriptors_valid(S_no_availability)',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n) <- S_done.ALLOCATIONS)',
        ],
    },
    'captured-destructor-saves-authentic-ordinary-empty-root': {
        'source': SOURCES['review-fiber-ordinary-return-owner-through-capture-suspension'],
        'stage': 'S.TODO = (CONFIG_INVOKE pconfigcall) :: ptask_tail* -- if pconfigcall.KIND = INTRINSIC_FIBER_SUSPEND -- if S.CURRENT = (pcallcontext) -- if $destructor_context_kind(S, pcallcontext) -- if S.ACTIVEFIBER = (n) -- if S.OBJECTS[n] = FIBER pfiber -- if pfiber.FINISH = (pfiberfinish)',
        'checks': [
            'pfiber.RETURNED', 'pfiber.VALUE = POBJECT n_returned',
            'pfiber.STATUS = FIBER_RUNNING', 'pfiber.VM = eps',
            'pfiber.RAW = PNULL', 'pfiber.CALL = eps', 'pfiber.TARGET = eps',
            'pfiberfinish.OBJECT = n', 'pfiberfinish.SEQUENCE = pfiber.SEQUENCE',
            'pfiberfinish.PENDING = eps', 'S.FIBERCLOSERS = eps',
            'S.FIBERCALLERS = [pfibercaller]', 'pfibercaller.OBJECT = n',
            'pfibercaller.API.KIND = eps', 'pfibercaller.API.LINE = 16',
            'pfibercaller.API.SEQUENCE = pfiber.SEQUENCE',
            '$heap_owners($heap_graph(S), HOBJECT n_returned) = 1',
            '$fiber_ordinary_finish_live(S, pfiberfinish)',
            '~$fiber_callback_finish_valid(S, pfiberfinish)',
            '$fiber_ordinary_frames(S.FRAMES, pfiberfinish, true)',
            '$fiber_finish_frame_count(S.FRAMES, pfiberfinish) = 1',
            'S.FRAMES = [pframe_root]',
            'pframe_root.CONTEXT = eps', 'pframe_root.LOCALS = ($empty_table())',
            'pframe_root.ORIGIN = eps', 'pframe_root.CONSTCONTEXT = eps',
            'pframe_root.TODO = (DESTRUCTOR_RESULT pdestructorcall) :: ptask_root*',
            'pdestructorcall.USER', 'pdestructorcall.CALLER = eps',
            'pdestructorcall.ORIGIN = eps', 'pdestructorcall.PENDING = eps',
            '$fiber_release_finish(ptask_root*) = (pfiberfinish)',
            'S_root = $constant_frame_scope(S, pframe_root, eps)',
            '$destructor_result_valid(S_root, pdestructorcall)',
            '$call_saved_context_valid(S_root, pframe_root)',
            '$fiber_callback_base_frame(S_root, pframe_root)',
            '$fiber_callback_finish_valid(S_root, pfiberfinish)',
            '$fiber_finished_root(S_root)', '$fiber_ordinary_root(S_root)',
            '$fiber_caller_trace(S_root) = [ptraceframe_api]',
            'ptraceframe_api.CLASS = ($ptascii("Fiber"))',
            'ptraceframe_api.FUNCTION = $ptascii("start")',
            'ptraceframe_api.LINE = 16',
            '~$fiber_ordinary_root(S_root[.FIBERCALLERS = eps])',
            '~$call_descriptors_valid(S_root[.FIBERCALLERS = eps])',
            'pframe_lexical = pframe_root[.ORIGIN = (pcallcontext.FUNCTION)]',
            '~$call_saved_context_valid($constant_frame_scope(S, pframe_lexical, eps), pframe_lexical)',
            '~$call_frames_valid(S, [pframe_lexical])',
            '~$call_saved_context_valid(S_root[.DESTRUCTION.CALLS = eps], pframe_root)',
            'pframe_missing = pframe_root[.TODO = [DESTRUCTOR_RESULT pdestructorcall]]',
            '~$call_saved_context_valid($constant_frame_scope(S, pframe_missing, eps), pframe_missing)',
            '~$call_frames_valid(S, [pframe_missing])',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n_returned) <- S_done.ALLOCATIONS)',
        ],
    },
    'suspended-ordinary-cleanup-keeps-result-and-borrowed-release': {
        'source': SOURCES['review-fiber-ordinary-return-owner-through-capture-suspension'],
        'stage': 'S.TODO = (CONFIG_INVOKE pconfigcall) :: ptask_tail* -- if pconfigcall.KIND = INTRINSIC_FIBER_RETURN -- if pconfigcall.OWNER = (n) -- if S.OBJECTS[n] = FIBER pfiber -- if pfiber.STATUS = FIBER_SUSPENDED -- if pfiber.FINISH = (pfiberfinish)',
        'checks': [
            'S.ACTIVEFIBER = eps', 'S.FIBERCALLERS = eps', 'S.FIBERCLOSERS = eps',
            'pfiber.RETURNED', 'pfiber.VALUE = POBJECT n_returned',
            'pfiber.RAW = PNULL', 'pfiber.CALL = eps', 'pfiber.ENTRY = eps',
            '~pfiber.FAILED', '~pfiber.GRACEFUL',
            'pfiber.FINISH = (pfiberfinish)', 'pfiberfinish.OBJECT = n',
            'pfiberfinish.SEQUENCE = pfiber.SEQUENCE', 'pfiberfinish.PENDING = eps',
            'pfiber.VM = (pfibervm)', '~pfibervm.GLOBAL',
            'pfibervm.TODO = (FIBER_CONTINUE pfiberapi) :: ptask_vm*',
            'pfiberapi.OBJECT = n', 'pfiberapi.SEQUENCE = pfiberfinish.SEQUENCE',
            'pfiberapi.KIND = (INTRINSIC_FIBER_SUSPEND)',
            '$fiber_ordinary_vm(pfibervm, pfiberfinish, true)',
            '~$fiber_ordinary_vm(pfibervm, pfiberfinish, false)',
            '$fiber_finish_task_count(pfibervm.TODO, pfiberfinish) = 0',
            '$fiber_finish_frame_count(pfibervm.FRAMES, pfiberfinish) = 1',
            'pfibervm.DESTRUCTORCALLS =/= eps',
            'pfibervm.DESTRUCTORRELEASES =/= eps',
            '$node_children(S, HOBJECT n) = $fiber_vm_nodes(pfibervm) ++ [HOBJECT n_returned]',
            '$heap_owners($heap_graph(S), HOBJECT n_returned) = 1',
            '$fiber_ordinary_finish_live(S, pfiberfinish)',
            '~$fiber_callback_finish_valid(S, pfiberfinish)',
            '~$fiber_ordinary_root(S)', '$fiber_record_valid(S, n, pfiber)',
            '$fiber_vm_valid(S, pfibervm, (n), eps)',
            'pfibervm_missing = pfibervm[.FRAMES = eps]',
            'S_missing = $fiber_put(S, n, pfiber[.VM = (pfibervm_missing)])',
            '~$fiber_ordinary_finish_live(S_missing, pfiberfinish)',
            '~$call_descriptors_valid(S_missing)',
            'pfibervm_no_release = pfibervm[.DESTRUCTORRELEASES = eps]',
            '~$fiber_vm_valid(S, pfibervm_no_release, (n), eps)',
            'S_no_release = $fiber_put(S, n, pfiber[.VM = (pfibervm_no_release)])',
            '~$call_descriptors_valid(S_no_release)',
            'S_wrong_stamp = $fiber_put(S, n, pfiber[.FINISH = (pfiberfinish[.SEQUENCE = S.FIBERSEQ])])',
            '~$fiber_ordinary_finish_live(S_wrong_stamp, pfiberfinish[.SEQUENCE = S.FIBERSEQ])',
            '~$call_descriptors_valid(S_wrong_stamp)',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n_returned) <- S_done.ALLOCATIONS)',
        ],
    },
    'ordinary-private-error-keeps-actual-resume-api-provenance': {
        'source': SOURCES['review-fiber-ordinary-private-raw-capture-rebinds-resume-api-scope'],
        'stage': 'S.TODO = [DESTRUCTOR_RELEASE pdestructionrelease, FIBER_RETURN_FINISH pfiberfinish] -- if S.OBJECTS[pfiberfinish.OBJECT] = FIBER pfiber -- if pfiberfinish.PENDING = (n_error) -- if S.OBJECTS[n_error] = THROWABLE pthrowable -- if pthrowable.KIND = "Error"',
        'checks': [
            *ROOT_CHECKS,
            'pfiber.RETURNED', 'pfiber.VALUE = POBJECT n_returned',
            'pfibercaller.API.KIND = (INTRINSIC_FIBER_RESUME)',
            'pfibercaller.API.LINE = 22', '$(pfiber.SEQUENCE > 1)',
            'pthrowable.ORIGIN = (pfibercaller.API.SITE)',
            'pthrowable.FILEORIGIN = (pfibercaller.API.SITE)',
            '$throwable_field(S, n_error, "message") = PSTRING $ptascii("Call to private FiberOrdinaryResumePrivateMaker302::__destruct() from scope Fiber")',
            '$throwable_field(S, n_error, "file") = PSTRING ($call_sourcefile(S.FILES, pfibercaller.API.SITE))',
            '$throwable_field(S, n_error, "line") = PINT 22',
            '$throwable_previous_id(S, n_error) = eps',
            '$throwable_field(S, n_error, "trace") = PARRAY n_trace',
            'S.ARRAYS[n_trace].ITEMS = [ENTRY (KINT 0) (DIRECT (PARRAY n_trace_frame))]',
            '$entry_lookup(S.ARRAYS[n_trace_frame].ITEMS, KSTRING $ptascii("function")) = (DIRECT (PSTRING $ptascii("resume")))',
            '$entry_lookup(S.ARRAYS[n_trace_frame].ITEMS, KSTRING $ptascii("class")) = (DIRECT (PSTRING $ptascii("Fiber")))',
            '$entry_lookup(S.ARRAYS[n_trace_frame].ITEMS, KSTRING $ptascii("line")) = (DIRECT (PINT 22))',
            '$throwable_source_origin_valid(S, n_error, pthrowable)',
            '$throwable_slots_valid(S, n_error, pthrowable)',
            '$closure_live_object_valid(S, n_error)',
            '~$fiber_root_error_source(S, n_error, pthrowable)',
            '$fiber_ordinary_root(S)',
            'S_start_line = S[.FIBERCALLERS = [pfibercaller[.API = pfibercaller.API[.LINE = 21]]]]',
            '~$fiber_ordinary_root(S_start_line)',
            '~$call_descriptors_valid(S_start_line)',
            'S_stale_api = S[.FIBERCALLERS = [pfibercaller[.API = pfibercaller.API[.SEQUENCE = 1]]]]',
            '~$fiber_ordinary_root(S_stale_api)',
            '~$call_descriptors_valid(S_stale_api)',
            '$heap_owners($heap_graph(S), HOBJECT n_returned) = 1',
            '$task_nodes(FIBER_RETURN_FINISH pfiberfinish) = [HOBJECT n_error]',
            *VALID, *PAUSE, *DONE,
            'S_done.OBJECTS[n] = FIBER pfiber_done',
            'pfiber_done.FAILED', 'pfiber_done.RETURNED',
            '~((HOBJECT n_returned) <- S_done.ALLOCATIONS)',
        ],
    },
    'throw-api-cleanup-replacement-keeps-stored-object-owner': {
        'source': SOURCES['review-fiber-ordinary-returned-result-survives-throw-api-cleanup-error'],
        'stage': 'S.TODO = (CONFIG_INVOKE pconfigcall) :: ptask_tail* -- if pconfigcall.KIND = INTRINSIC_FIBER_RETURN -- if pconfigcall.OWNER = (n) -- if S.OBJECTS[n] = FIBER pfiber -- if pfiber.FAILED -- if pfiber.VALUE = POBJECT n_returned',
        'checks': [
            'S.ACTIVEFIBER = eps', 'S.FIBERCALLERS = eps', 'S.FIBERCLOSERS = eps',
            'S.CURRENT = eps', 'S.FRAMES = eps',
            'pfiber.RETURNED', 'pfiber.VALUE = POBJECT n_returned',
            'pfiber.STATUS = FIBER_TERMINATED', '~pfiber.GRACEFUL',
            'pfiber.FINISH = eps', 'pfiber.VM = eps', 'pfiber.ENTRY = eps',
            'pfiber.RAW = PNULL', 'pfiber.CALL = eps', 'pfiber.TARGET = eps',
            '$object_name(S, n_returned) = $ptascii("FiberOrdinaryInjectedReturned302")',
            '$node_children(S, HOBJECT n) = [HOBJECT n_returned]',
            '$heap_owners($heap_graph(S), HOBJECT n_returned) = 1',
            '~(n_returned <- S.DESTRUCTION.CALLED)',
            '$fiber_record_valid(S, n, pfiber)',
            '~$fiber_record_valid($fiber_put(S, n, pfiber[.GRACEFUL = true]), n, pfiber[.GRACEFUL = true])',
            'pfiberfinish_forged = {OBJECT n, PENDING eps, SEQUENCE pfiber.SEQUENCE}',
            '~$fiber_ordinary_finish_live(S, pfiberfinish_forged)',
            '~$fiber_record_valid($fiber_put(S, n, pfiber[.FINISH = (pfiberfinish_forged)]), n, pfiber[.FINISH = (pfiberfinish_forged)])',
            *VALID, *PAUSE, *DONE,
            '~((HOBJECT n_returned) <- S_done.ALLOCATIONS)',
            'n_returned <- S_done.DESTRUCTION.CALLED',
        ],
    },
    'ordinary-parent-finish-parks-under-real-handler-result-cleanup': {
        'source': SOURCES['review-fiber-ordinary-finish-parks-under-handler-result-cleanup'],
        'stage': 'S.FIBERCALLERS = [pfibercaller_child, pfibercaller_parent] -- if S.CURRENT = (pcallcontext) -- if $fiber_context_kind(S, pcallcontext) -- if S.OBJECTS[pfibercaller_parent.OBJECT] = FIBER pfiber -- if pfiber.FINISH = (pfiberfinish)',
        'checks': [
            'n_parent = pfibercaller_parent.OBJECT', 'n_child = pfibercaller_child.OBJECT',
            'n_parent =/= n_child', 'S.ACTIVEFIBER = (n_child)',
            'pfibercaller_child.PREVIOUS = (n_parent)',
            'pfibercaller_parent.PREVIOUS = eps', 'S.FIBERCLOSERS = eps',
            'pfiber.RETURNED', 'pfiber.STATUS = FIBER_RUNNING',
            'pfiber.VALUE = PINT 7', 'pfiber.VM = eps',
            'pfiber.RAW = PNULL', 'pfiber.CALL = eps',
            'pfiberfinish.OBJECT = n_parent', 'pfiberfinish.PENDING = eps',
            'pfiberfinish.SEQUENCE = pfiber.SEQUENCE',
            '$fiber_ordinary_finish_live(S, pfiberfinish)',
            '~$fiber_callback_finish_valid(S, pfiberfinish)',
            '$fiber_ordinary_callers(S.FIBERCALLERS, pfiberfinish, true)',
            '$fiber_ordinary_frames(pfibercaller_child.VM.FRAMES, pfiberfinish, true)',
            '$fiber_finish_frame_count(pfibercaller_child.VM.FRAMES, pfiberfinish) = 1',
            'pfibercaller_child.VM.DESTRUCTORCALLS =/= eps',
            'pfibercaller_child.VM.DESTRUCTORRELEASES =/= eps',
            'pfibercaller_parent.VM.DESTRUCTOROPERATIONS = [pdestructionoperation]',
            'pfibercaller_parent.VM.DESTRUCTORCLEANUPS = [pdestructioncleanup]',
            'pdestructionoperation.SOURCE = ERROR_HANDLER_RESULT perrorcall',
            'pdestructionoperation.CLEANUP = (pdestructioncleanup)',
            'pdestructioncleanup.SOURCE = ERROR_HANDLER_RESULT perrorcall',
            'S.DESTRUCTION.CALLS = eps', 'S.DESTRUCTION.RELEASES = eps',
            'S.DESTRUCTION.FRAMES = eps', 'S.DESTRUCTION.OPERATIONS = eps',
            'S.DESTRUCTION.CLEANUPS = eps',
            '$fiber_vm_valid(S, pfibercaller_child.VM, (n_parent), [pfibercaller_parent])',
            '$fiber_vm_valid(S, pfibercaller_parent.VM, eps, eps)',
            'S_parent = $fiber_vm_restore(S, pfibercaller_parent.VM)[.ACTIVEFIBER = eps][.FIBERCALLERS = eps]',
            'S_parent.CURRENT = (pcallcontext_outer)',
            'S_parent.FRAMES = [pframe_emitter]',
            'pframe_emitter.TODO = (DESTRUCTOR_RESULT pdestructorcall_outer) :: ptask_emitter*',
            'pdestructorcall_outer.OPERATION = (pdestructionoperation)',
            'pdestructorcall_outer.USER',
            'pcallcontext_outer.CALLSITE = pdestructorcall_outer.SITE',
            'pcallcontext_outer.TARGET = pdestructorcall_outer.TARGET',
            'pcallcontext_outer.INSTANCE = eps',
            'pcallcontext_outer.RECEIVER = (pdestructorcall_outer.OBJECT)',
            'pcallcontext_outer.LINE = $destructor_line(pdestructorcall_outer)',
            'pcallcontext_outer.ARGC = 0',
            'pframe_emitter.ORIGIN = pdestructorcall_outer.ORIGIN',
            '$reference_call_frame_site(pcallcontext_outer, pframe_emitter)',
            '$reference_call_frames_valid(S_parent.CURRENT, S_parent.FRAMES)',
            'S_emitter = $constant_frame_scope(S_parent, pframe_emitter, eps)',
            '$destructor_result_valid(S_emitter, pdestructorcall_outer)',
            '$destructor_operation_valid(S_emitter, pdestructionoperation)',
            '$eager_cleanup_valid(S_emitter, pdestructioncleanup)',
            'pcallcontext_no_site = pcallcontext_outer[.CALLSITE = pframe_emitter.ORIGIN]',
            '~$reference_call_frame_site(pcallcontext_no_site, pframe_emitter)',
            'pcallcontext_bad_line = pcallcontext_outer[.LINE = $(pcallcontext_outer.LINE + 1)]',
            '~$reference_call_frame_site(pcallcontext_bad_line, pframe_emitter)',
            'pcallcontext_no_receiver = pcallcontext_outer[.RECEIVER = eps]',
            '~$reference_call_frame_site(pcallcontext_no_receiver, pframe_emitter)',
            'pcallcontext_arg = pcallcontext_outer[.ARGC = 1]',
            '~$reference_call_frame_site(pcallcontext_arg, pframe_emitter)',
            'pcallcontext_instance = pcallcontext_outer[.INSTANCE = (pdestructorcall_outer.OBJECT)]',
            '~$reference_call_frame_site(pcallcontext_instance, pframe_emitter)',
            '~$call_descriptors_local_valid(S_parent[.CURRENT = (pcallcontext_no_site)])',
            '~$call_descriptors_valid(S[.FIBERCALLERS = [pfibercaller_child, pfibercaller_parent[.VM = pfibercaller_parent.VM[.CURRENT = (pcallcontext_no_site)]]]])',
            'pframe_false_origin = pframe_emitter[.ORIGIN = pdestructorcall_outer.SITE]',
            '~$reference_call_frame_site(pcallcontext_outer, pframe_false_origin)',
            '~$fiber_vm_valid(S, pfibercaller_parent.VM[.FRAMES = [pframe_false_origin]], eps, eps)',
            'S_parent.DESTRUCTION.PHASE = S.DESTRUCTION.PHASE',
            'S_parent.DESTRUCTION.CALLED = S.DESTRUCTION.CALLED',
            'S_parent.DESTRUCTION.PROPCACHE = S.DESTRUCTION.PROPCACHE',
            'S_parent.DESTRUCTION.ABANDONED = S.DESTRUCTION.ABANDONED',
            'pfibervm_no_operation = pfibercaller_parent.VM[.DESTRUCTOROPERATIONS = eps]',
            '~$fiber_vm_valid(S, pfibervm_no_operation, eps, eps)',
            '~$call_descriptors_valid(S[.FIBERCALLERS = [pfibercaller_child, pfibercaller_parent[.VM = pfibervm_no_operation]]])',
            'pfibervm_no_cleanup = pfibercaller_parent.VM[.DESTRUCTORCLEANUPS = eps]',
            '~$fiber_vm_valid(S, pfibervm_no_cleanup, eps, eps)',
            '~$call_descriptors_valid(S[.FIBERCALLERS = [pfibercaller_child, pfibercaller_parent[.VM = pfibervm_no_cleanup]]])',
            'pfibervm_no_finish = pfibercaller_child.VM[.FRAMES = eps]',
            '~$fiber_ordinary_finish_live(S[.FIBERCALLERS = [pfibercaller_child[.VM = pfibervm_no_finish], pfibercaller_parent]], pfiberfinish)',
            '~$call_descriptors_valid(S[.FIBERCALLERS = [pfibercaller_child[.VM = pfibervm_no_finish], pfibercaller_parent]])',
            *VALID, *PAUSE, *DONE,
            'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
        ],
    },
    'returned-forced-cleanup-rejects-false-body-mode-and-public-control-owner': {
        'source': SOURCES['review-fiber-ordinary-suspended-cleanup-force-close-keeps-return-owner'],
        'stage': 'S.TODO = [FIBER_RETURN_FINISH pfiberfinish] -- if S.FIBERCLOSERS = [pfiberclose] -- if pfiberfinish.PENDING = (pfiberclose.EXIT) -- if S.OBJECTS[pfiberfinish.OBJECT] = FIBER pfiber',
        'checks': [
            'n = pfiberfinish.OBJECT', 'n_exit = pfiberclose.EXIT',
            'S.ACTIVEFIBER = (n)', 'S.CURRENT = eps', 'S.FRAMES = eps',
            'pfiber.RETURNED', 'pfiber.VALUE = POBJECT n_returned',
            'pfiberfinish.SEQUENCE = pfiber.SEQUENCE',
            '$fiber_graceful_for(S, n, pfiberfinish.SEQUENCE, n_exit)',
            '$fiber_finish_pending_valid(S, pfiberfinish)',
            '~$fiber_ordinary_body_pending(S, pfiberfinish)',
            '$fiber_ordinary_carrier(S, pfiberfinish)',
            '$fiber_ordinary_finish_live(S, pfiberfinish)',
            'S_false_mode = $fiber_put(S[.TODO = [FIBER_THROW_FINISH pfiberfinish]], n, pfiber[.RETURNED = false][.VALUE = PNULL])',
            '~$fiber_ordinary_carrier(S_false_mode, pfiberfinish)',
            '~$fiber_ordinary_finish_live(S_false_mode, pfiberfinish)',
            '~$call_task_valid(S_false_mode, FIBER_THROW_FINISH pfiberfinish)',
            '~$call_descriptors_valid(S_false_mode)',
            'S_old_mode = S[.TODO = [FIBER_CALLBACK_FINISH pfiberfinish]]',
            '~$fiber_callback_finish_live(S_old_mode, pfiberfinish)',
            '~$call_descriptors_valid(S_old_mode)',
            'S_back = $drive_steps(S, 1)',
            'S_back.OBJECTS[n] = FIBER pfiber_back',
            'pfiber_back.STATUS = FIBER_TERMINATED', 'pfiber_back.RETURNED',
            '~pfiber_back.FAILED', '~pfiber_back.GRACEFUL',
            'pfiber_back.VALUE = POBJECT n_returned',
            '$heap_owners($heap_graph(S_back), HOBJECT n_returned) = 1',
            '$fiber_graceful_retiring(S_back, n_exit)',
            '~$throwable_live(S_back, n_exit)',
            '~$destructor_pending_valid(S_back, (n_exit))',
            'S_public_alias = S_back[.RESULT = KNOWN (POBJECT n_exit)]',
            '~$fiber_graceful_retiring(S_public_alias, n_exit)',
            '$call_descriptors_valid(S_back)', '$heap_valid($heap_graph(S_back))',
            *VALID, *PAUSE, *DONE,
            '$drive(S_back[.COMPLETION = NORMAL], 4000) = S_done',
            '~((HOBJECT n_returned) <- S_done.ALLOCATIONS)',
        ],
    },
}

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--case', action='append')
    args = parser.parse_args()
    review.CASES = CASES
    review.__file__ = str(Path(__file__).resolve())
    raise SystemExit(0 if review.run(args.case) else 1)
