"""Independent source-reached internal Fiber argument, producer and VM checks."""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'tests/semantics'))
import fiber_state_review as review

SOURCES = {row['id']: row['source'] for row in json.loads(
    Path(__file__).with_name('fiber_review_cases.json').read_text())}
VALID = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
         '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))']
PAUSE = ['S_paused = $drive(S, 0)', 'S_paused.COMPLETION = BUDGET',
         'S_paused[.COMPLETION = NORMAL] = S']
DONE = ['S_done.COMPLETION = NORMAL', 'S_done.TODO = eps',
        'S_done.FRAMES = eps', 'S_done.CURRENT = eps', 'S_done.HELD = eps',
        'S_done.ACTIVEFIBER = eps', 'S_done.FIBERCALLERS = eps',
        'S_done.FIBERCLOSERS = eps', '$call_descriptors_valid(S_done)',
        '$heap_valid($heap_graph(S_done))']
FLOAT = 'PFLOAT 4612811918334230528'


def config_negatives():
    return [
        '~$fiber_core_result_valid(S, n, pconfigcall[.KIND = INTRINSIC_INI_GET])',
        '~$fiber_core_result_valid(S, n, pconfigcall[.OWNER = (n)])',
        '~$fiber_core_result_valid(S, n, pconfigcall[.NAMED = true])',
        '~$fiber_core_result_valid(S, n, pconfigcall[.LINE = 0])',
        '~$fiber_core_result_valid(S, n, pconfigcall[.SENT = [NAMED_SENT (KNOWN (PINT 0))]])',
        '~$fiber_core_result_valid(S, |S.OBJECTS|, pconfigcall)',
    ]


CASES = {
    'core-config-copied-array-owner-and-borrowed-tail': {
        'source': SOURCES['review-fiber-core-reporting-type-error-no-callsite-prefix'],
        'stage': 'S.TODO = [CONFIG_INVOKE pconfigcall, FIBER_CORE_RESULT n pconfigcall, FIBER_FINISH n] -- if pconfigcall.KIND = INTRINSIC_ERROR_REPORTING -- if pconfigcall.SENT = [NAMED_SENT (KNOWN (PARRAY n_arg))]',
        'checks': [
            'S.ACTIVEFIBER = (n)', 'S.OBJECTS[n] = FIBER pfiber',
            'pfiber.TARGET = (FIBER_REPORTING_TARGET)',
            'pfiber.STATUS = FIBER_RUNNING', 'pfiber.VM = eps',
            'S.CURRENT = eps', 'S.FRAMES = eps',
            'pfiber.ENTRY = ({SLOTS pconfigcall.SENT, NAMED eps})',
            'S.FIBERCALLERS = [pfibercaller]',
            'pfibercaller.OBJECT = n', 'pfibercaller.API.START = (pnamedargs)',
            'pnamedargs.SLOTS = pconfigcall.SENT', 'pnamedargs.NAMED = eps',
            'pfibercaller.API.SITE = pconfigcall.SITE',
            'pfibercaller.API.LINE = pconfigcall.LINE',
            'pconfigcall.OWNER = eps', '~pconfigcall.NAMED', 'pconfigcall.INDEX = 1',
            '$fiber_core_config_valid(S, pconfigcall)',
            '$config_invoke_valid(S, pconfigcall)', '~$config_strict(S, pconfigcall)',
            '$task_nodes(CONFIG_INVOKE pconfigcall) = [HARRAY n_arg]',
            '$task_nodes(FIBER_CORE_RESULT n pconfigcall) = eps',
            '$heap_count(HARRAY n_arg, $pools_nodes(S.POOLS)) = 1',
            '$heap_count(HARRAY n_arg, $fiber_api_nodes(pfibercaller.API)) = 1',
            'S.GLOBALTABLE = (psymboltable)',
            '$lookup(psymboltable.ENV, $ptascii("bad")) = (n_bad)',
            'S.STORE[n_bad] = DEFINED (PARRAY n_arg)',
            '$heap_count(HCELL n_bad, $table_roots(S.GLOBALTABLE)) = 1',
            '$node_children(S, HCELL n_bad) = [HARRAY n_arg]',
            '$heap_owners($heap_graph(S), HARRAY n_arg) = 4',
            '$heap_owners($heap_graph(S), HOBJECT n) = 2',
            '$node_children(S, HOBJECT n) = eps',
            *config_negatives(),
            '~$fiber_core_result_valid(S, n, pconfigcall[.INDEX = 0])',
            'pfiber.CALL = (pconfigcall_construct)',
            '~$fiber_core_result_valid(S, n, pconfigcall[.SITE = pconfigcall_construct.SITE])',
            'S_duplicate = S[.TODO = [CONFIG_INVOKE pconfigcall, FIBER_CORE_RESULT n pconfigcall, FIBER_CORE_RESULT n pconfigcall, FIBER_FINISH n]]',
            '$heap_graph(S_duplicate) = $heap_graph(S)',
            '~$fiber_core_result_valid(S_duplicate, n, pconfigcall)',
            '~$call_descriptors_valid(S_duplicate)',
            'S_no_cache = $fiber_put(S, n, pfiber[.TARGET = eps])',
            '~$fiber_core_config_valid(S_no_cache, pconfigcall)',
            '~$call_descriptors_valid(S_no_cache)',
            *VALID, *PAUSE,
        ],
    },
    'strict-user-handler-config-is-distinct-from-weak-core-c': {
        'source': SOURCES['review-fiber-core-reporting-strict-handler-source-remains-strict'],
        'stage': 'S.CURRENT = (pcallcontext) -- if $trace_context_function(S, pcallcontext) = $ptascii("coreReportingStrictNested313") -- if S.TODO = (CONFIG_INVOKE pconfigcall_body) :: ptask_tail* -- if pconfigcall_body.KIND = INTRINSIC_ERROR_REPORTING',
        'checks': [
            '$fiber_core_tail_frames(S.FRAMES) = ((n, pconfigcall))',
            'S.ACTIVEFIBER = (n)', 'S.OBJECTS[n] = FIBER pfiber',
            'pfiber.TARGET = (FIBER_REPORTING_TARGET)',
            f'pconfigcall.SENT = [NAMED_SENT (KNOWN ({FLOAT}))]',
            'pconfigcall_body.SENT = [NAMED_SENT (KNOWN (PSTRING $ptascii("17")))]',
            'pconfigcall_body.SITE =/= pconfigcall.SITE',
            'S.ORIGIN = (pconfigcall_body.SITE)',
            'S.REPORTING = 30719', 'S.REPORTINGINI = $ptascii("30719")',
            '$fiber_core_config(S, pconfigcall)', '~$config_strict(S, pconfigcall)',
            '~$fiber_core_config(S, pconfigcall_body)', '$config_strict(S, pconfigcall_body)',
            '$config_invoke_valid(S, pconfigcall_body)',
            '~$fiber_core_config_valid(S, pconfigcall)',
            '$error_context_valid(S, pcallcontext)',
            f'$config_trace_frames(S, pconfigcall, [{FLOAT}]) = [ptraceframe_core]',
            'ptraceframe_core.FILE = eps', 'ptraceframe_core.LINE = $(-1)',
            'ptraceframe_core.FUNCTION = $ptascii("error_reporting")',
            '$config_trace_frames(S, pconfigcall_body, [PSTRING $ptascii("17")]) = [ptraceframe_body]',
            'ptraceframe_body.FILE = $call_sourcefile(S.FILES, pconfigcall_body.SITE)',
            'ptraceframe_body.LINE = pconfigcall_body.LINE',
            'S.FRAMES = [pframe_core]',
            'pframe_core.TODO = [ERROR_HANDLER_RESULT perrorcall, FIBER_CORE_RESULT n pconfigcall, FIBER_FINISH n]',
            'perrorcall.RESUME = REPORTING_LONG_RESULT pconfigcall 2',
            '$fiber_core_base_frame(S, pframe_core)',
            *config_negatives(),
            'pframe_missing = pframe_core[.TODO = [ERROR_HANDLER_RESULT perrorcall, FIBER_FINISH n]]',
            'S_missing = S[.FRAMES = [pframe_missing]]',
            '$heap_graph(S_missing) = $heap_graph(S)',
            '~$fiber_core_result_valid(S_missing, n, pconfigcall)',
            '~$call_descriptors_valid(S_missing)',
            *VALID, *PAUSE,
        ],
    },
    'suspended-handler-keeps-c-producer-after-start-buffer-returns': {
        'source': SOURCES['review-fiber-core-reporting-lossy-handler-suspends-before-old-sample'],
        'stage': 'S.TODO = (CONFIG_INVOKE pconfigcall_resume) :: ptask_tail* -- if pconfigcall_resume.KIND = INTRINSIC_FIBER_RESUME -- if pconfigcall_resume.OWNER = (n) -- if S.OBJECTS[n] = FIBER pfiber -- if pfiber.STATUS = FIBER_SUSPENDED',
        'checks': [
            'S.ACTIVEFIBER = eps', 'S.FIBERCALLERS = eps',
            'S.REPORTING = 7', 'S.REPORTINGINI = $ptascii("7")',
            'pfiber.TARGET = (FIBER_REPORTING_TARGET)', 'pfiber.VM = (pfibervm)',
            'pfibervm.REPORTING = 30719', 'pfibervm.CURRENT = (pcallcontext_handler)',
            '$fiber_core_tail_frames(pfibervm.FRAMES) = ((n, pconfigcall))',
            f'pconfigcall.SENT = [NAMED_SENT (KNOWN ({FLOAT}))]',
            'pfiber.ENTRY = ({SLOTS pconfigcall.SENT, NAMED eps})',
            'pfibervm.TODO = (FIBER_CONTINUE pfiberapi) :: ptask_handler*',
            'pfiberapi.KIND = (INTRINSIC_FIBER_SUSPEND)',
            'pfiberapi.SENT = (PSTRING $ptascii("pause"))',
            '$task_nodes(FIBER_CORE_RESULT n pconfigcall) = eps',
            '$heap_owners($heap_graph(S), HOBJECT n) = 2',
            '$fiber_vm_valid(S, pfibervm, (n), eps)',
            'S_view = $fiber_vm_restore(S, pfibervm)[.ACTIVEFIBER = (n)]',
            'S_view.FIBERCALLERS = eps', 'S_view.REPORTING = 30719',
            'S_view.REPORTINGINI = $ptascii("7")',
            '$fiber_core_result_valid(S_view, n, pconfigcall)',
            '$fiber_core_config(S_view, pconfigcall)',
            '$error_context_valid(S_view, pcallcontext_handler)',
            '~$fiber_core_result_valid(S_view, n, pconfigcall[.LINE = 0])',
            '~$fiber_core_result_valid(S_view, n, pconfigcall[.SENT = [NAMED_SENT (KNOWN (PINT 2))]])',
            'S_bad_entry = $fiber_put(S, n, pfiber[.ENTRY = ({SLOTS ([NAMED_SENT (KNOWN (PINT 2))]), NAMED eps})])',
            '~$call_descriptors_valid(S_bad_entry)',
            *VALID, *PAUSE,
            'S_done = $drive(S_paused[.COMPLETION = NORMAL], 4000)',
            *DONE,
            'S_done.OBJECTS[n] = FIBER pfiber_done',
            'pfiber_done.STATUS = FIBER_TERMINATED', 'pfiber_done.RETURNED',
            '~pfiber_done.FAILED', 'pfiber_done.VALUE = PINT 19',
            'S_done.REPORTING = 7', 'S_done.REPORTINGINI = $ptascii("2")',
        ],
    },
    'resumed-handler-trace-uses-resume-but-warning-keeps-start': {
        'source': SOURCES['review-fiber-core-reporting-lossy-handler-suspends-before-old-sample'],
        'stage': 'S.CURRENT = (pcallcontext) -- if $trace_context_function(S, pcallcontext) = $ptascii("coreReportingSuspend313") -- if S.TODO = (CONFIG_INVOKE pconfigcall_body) :: ptask_tail* -- if pconfigcall_body.KIND = INTRINSIC_ERROR_REPORTING -- if pconfigcall_body.SENT = [NAMED_SENT (KNOWN (PINT 19))]',
        'checks': [
            '$fiber_core_tail_frames(S.FRAMES) = ((n, pconfigcall))',
            'S.ACTIVEFIBER = (n)', 'S.FIBERCALLERS = [pfibercaller]',
            'pfibercaller.API.KIND = (INTRINSIC_FIBER_RESUME)',
            'pfibercaller.API.START = eps',
            'pconfigcall.SITE =/= pfibercaller.API.SITE',
            'pconfigcall.LINE = 10', 'pfibercaller.API.LINE = 11',
            'pconfigcall_body.SENT = [NAMED_SENT (KNOWN (PINT 19))]',
            'S.REPORTING = 30719', 'S.REPORTINGINI = $ptascii("7")',
            '$fiber_core_config(S, pconfigcall)',
            '~$fiber_core_config(S, pconfigcall_body)',
            '$error_context_call(S, pcallcontext) = (perrorcall)',
            'perrorcall.RESUME = REPORTING_LONG_RESULT pconfigcall 2',
            'perrorcall.SITE = pconfigcall.SITE', 'perrorcall.LINE = pconfigcall.LINE',
            '$error_context_valid(S, pcallcontext)',
            '$eval_exception_trace(S) = [ptraceframe_handler, ptraceframe_core, ptraceframe_api]',
            'ptraceframe_handler.FILE = eps', 'ptraceframe_core.FILE = eps',
            'ptraceframe_core.FUNCTION = $ptascii("error_reporting")',
            f'ptraceframe_core.ARGS = [(KINT 0, {FLOAT})]',
            'ptraceframe_api.FUNCTION = $ptascii("resume")',
            'ptraceframe_api.LINE = pfibercaller.API.LINE',
            'ptraceframe_api.FILE = $call_sourcefile(S.FILES, pfibercaller.API.SITE)',
            '~$fiber_core_result_valid(S, n, pconfigcall[.SITE = pfibercaller.API.SITE][.LINE = pfibercaller.API.LINE])',
            *config_negatives(), *VALID, *PAUSE,
        ],
    },
    'real-public-handler-destructor-keeps-reporting-c-trace': {
        'source': SOURCES['review-fiber-core-reporting-public-handler-destructor-keeps-c-trace'],
        'stage': 'S.CURRENT = (pcallcontext) -- if $trace_context_function(S, pcallcontext) = $ptascii("__destruct") -- if $destructor_context_call(pcallcontext, S.CURRENT, S.FRAMES) = (pdestructorcall) -- if $object_name(S, pdestructorcall.OBJECT) = $ptascii("CoreReportingTrace313") -- if S.TODO = (CONFIG_INVOKE pconfigcall_body) :: ptask_tail* -- if pconfigcall_body.KIND = INTRINSIC_ERROR_REPORTING',
        'checks': [
            '$fiber_core_tail_frames(S.FRAMES) = ((n, pconfigcall))',
            'S.ACTIVEFIBER = (n)', 'S.REPORTING = 17',
            'S.REPORTINGINI = $ptascii("17")',
            'pconfigcall_body.SENT = [NAMED_SENT (KNOWN (PINT 23))]',
            '$destructor_context_valid(S, pcallcontext)',
            '$fiber_core_config(S, pconfigcall)',
            '~$fiber_core_config(S, pconfigcall_body)',
            '$task_nodes(FIBER_CORE_RESULT n pconfigcall) = eps',
            'S.ERRORHANDLER.CALLBACK = (POBJECT n_replacement)',
            '$node_children(S, HOBJECT n_replacement) = eps',
            '$heap_count(HOBJECT pdestructorcall.OBJECT, $error_handler_roots(S.ERRORHANDLER)) = 0',
            '$heap_count(HOBJECT pdestructorcall.OBJECT, $error_handler_stack_roots(S.ERRORHANDLERS)) = 0',
            '$destructor_trace_suffix(S, pcallcontext) = [ptraceframe_core]',
            'ptraceframe_core.FILE = eps', 'ptraceframe_core.LINE = $(-1)',
            'ptraceframe_core.FUNCTION = $ptascii("error_reporting")',
            f'ptraceframe_core.ARGS = [(KINT 0, {FLOAT})]',
            '$eval_exception_trace(S) = [ptraceframe_dtor, ptraceframe_core, ptraceframe_api]',
            'ptraceframe_dtor.FILE = eps', 'ptraceframe_dtor.LINE = $(-1)',
            'ptraceframe_dtor.FUNCTION = $ptascii("__destruct")',
            'ptraceframe_api.FUNCTION = $ptascii("start")',
            'ptraceframe_api.LINE = pconfigcall.LINE',
            'S.FRAMES = [pframe_core]',
            'ptask_prefix* = pframe_core.TODO[0 : $nabs($(|pframe_core.TODO| - 2))]',
            'pframe_core.TODO = ptask_prefix* ++ [FIBER_CORE_RESULT n pconfigcall, FIBER_FINISH n]',
            'pframe_missing = pframe_core[.TODO = ptask_prefix* ++ [FIBER_FINISH n]]',
            'S_missing = S[.FRAMES = [pframe_missing]]',
            '$heap_graph(S_missing) = $heap_graph(S)',
            '~$fiber_core_result_valid(S_missing, n, pconfigcall)',
            '$destructor_trace_suffix(S_missing, pcallcontext) = eps',
            '~$call_descriptors_valid(S_missing)',
            'S_bad_origin = S[.FRAMES = [pframe_core[.ORIGIN = eps]]]',
            '$heap_graph(S_bad_origin) = $heap_graph(S)',
            '~$fiber_core_result_valid(S_bad_origin, n, pconfigcall)',
            '$destructor_trace_suffix(S_bad_origin, pcallcontext) = eps',
            '~$call_descriptors_valid(S_bad_origin)',
            'pcallcontext_bad = pcallcontext[.CALLSITE = (pconfigcall.SITE)][.LINE = pconfigcall.LINE]',
            'S_bad_context = S[.CURRENT = (pcallcontext_bad)]',
            '$heap_graph(S_bad_context) = $heap_graph(S)',
            '$fiber_core_result_valid(S_bad_context, n, pconfigcall)',
            '~$destructor_context_valid(S_bad_context, pcallcontext_bad)',
            '$destructor_trace_suffix(S_bad_context, pcallcontext_bad) = eps',
            '~$call_descriptors_valid(S_bad_context)',
            *config_negatives(), *VALID, *PAUSE,
        ],
    },
    'private-handler-retirement-error-is-c-root-not-user-scope': {
        'source': SOURCES['review-fiber-core-reporting-static-replacement-private-handler-fiber-scope'],
        'stage': 'S.TODO = (DESTRUCTOR_ENTER pdestructorcall) :: ptask_tail* -- if $object_name(S, pdestructorcall.OBJECT) = $ptascii("CoreReportingPrivate313")',
        'checks': [
            '$fiber_core_tail(S.TODO) = ((n, pconfigcall))',
            'S.ACTIVEFIBER = (n)', 'S.CURRENT = eps', 'S.FRAMES = eps',
            'S.REPORTING = 30719', 'S.REPORTINGINI = $ptascii("30719")',
            '$fiber_core_root(S)', '$destructor_enter_valid(S, pdestructorcall)',
            'S.FIBERCALLERS = [pfibercaller]',
            'pfibercaller.API.SITE = pconfigcall.SITE',
            'pfibercaller.API.LINE = pconfigcall.LINE',
            'S.ERRORHANDLER.CALLBACK = (POBJECT n_replacement)',
            '$node_children(S, HOBJECT n_replacement) = eps',
            *VALID, *PAUSE,
            'n_error = |S.OBJECTS|', 'S_error = $drive_steps(S, 1)',
            '$throwable_field(S_error, n_error, "message") = PSTRING $ptascii("Call to private CoreReportingPrivate313::__destruct() from scope Fiber")',
            '$throwable_field(S_error, n_error, "file") = PSTRING $call_sourcefile(S.FILES, pconfigcall.SITE)',
            '$throwable_field(S_error, n_error, "line") = PINT pconfigcall.LINE',
            '$throwable_field(S_error, n_error, "trace") = PARRAY n_trace',
            'S_error.ARRAYS[n_trace].ITEMS = [ENTRY (KINT 0) (DIRECT (PARRAY n_core_frame)), ENTRY (KINT 1) (DIRECT (PARRAY n_api_frame))]',
            '$entry_lookup(S_error.ARRAYS[n_core_frame].ITEMS, KSTRING $ptascii("function")) = (DIRECT (PSTRING $ptascii("error_reporting")))',
            '$entry_lookup(S_error.ARRAYS[n_core_frame].ITEMS, KSTRING $ptascii("args")) = (DIRECT (PARRAY n_args))',
            f'S_error.ARRAYS[n_args].ITEMS = [ENTRY (KINT 0) (DIRECT ({FLOAT}))]',
            '$trace_graph_valid(S_error, n_trace)',
            'S_error.REPORTINGINI = $ptascii("30719")',
            'S_done = $drive(S_paused[.COMPLETION = NORMAL], 4000)', *DONE,
            'S_done.REPORTINGINI = $ptascii("30719")',
            'S_done.OBJECTS[n] = FIBER pfiber_done',
            'pfiber_done.FAILED', '~pfiber_done.RETURNED',
        ],
    },
}


# The complete 63-premise public fixture remains an explicit selection.
# Its whole-source model and literal drive(S, 0) run timed out; the eight
# bounded selections retain physical checks without claiming whole execution.
PUBLIC = CASES['real-public-handler-destructor-keeps-reporting-c-trace']
PUBLIC_STAGE = 'S.TODO = (CONFIG_INVOKE pconfigcall_body) :: ptask_tail* -- if pconfigcall_body.KIND = INTRINSIC_ERROR_REPORTING -- if S.CURRENT = (pcallcontext) -- if $trace_context_function(S, pcallcontext) = $ptascii("__destruct") -- if $destructor_context_call(pcallcontext, S.CURRENT, S.FRAMES) = (pdestructorcall) -- if $object_name(S, pdestructorcall.OBJECT) = $ptascii("CoreReportingTrace313")'
PUBLIC_PARTITIONS = {
    'public-destructor-real-c-trace-and-owner-projections': [
        '$fiber_core_tail_frames(S.FRAMES) = ((n, pconfigcall))',
        'S.ACTIVEFIBER = (n)',
        'S.REPORTING = 17',
        'S.REPORTINGINI = $ptascii("17")',
        'pconfigcall_body.SENT = [NAMED_SENT (KNOWN (PINT 23))]',
        '$destructor_context_valid(S, pcallcontext)',
        '$fiber_core_config(S, pconfigcall)',
        '~$fiber_core_config(S, pconfigcall_body)',
        '$task_nodes(FIBER_CORE_RESULT n pconfigcall) = eps',
        'S.ERRORHANDLER.CALLBACK = (POBJECT n_replacement)',
        '$node_children(S, HOBJECT n_replacement) = eps',
        '$heap_count(HOBJECT pdestructorcall.OBJECT, $error_handler_roots(S.ERRORHANDLER)) = 0',
        '$heap_count(HOBJECT pdestructorcall.OBJECT, $error_handler_stack_roots(S.ERRORHANDLERS)) = 0',
        '$destructor_trace_suffix(S, pcallcontext) = [ptraceframe_core]',
        'ptraceframe_core.FILE = eps',
        'ptraceframe_core.LINE = $(-1)',
        'ptraceframe_core.FUNCTION = $ptascii("error_reporting")',
        'ptraceframe_core.ARGS = [(KINT 0, PFLOAT 4612811918334230528)]',
        '$eval_exception_trace(S) = [ptraceframe_dtor, ptraceframe_core, ptraceframe_api]',
        'ptraceframe_dtor.FILE = eps',
        'ptraceframe_dtor.LINE = $(-1)',
        'ptraceframe_dtor.FUNCTION = $ptascii("__destruct")',
        'ptraceframe_api.FUNCTION = $ptascii("start")',
        'ptraceframe_api.LINE = pconfigcall.LINE',
        'S.FRAMES = [pframe_core]',
        'ptask_prefix* = pframe_core.TODO[0 : $nabs($(|pframe_core.TODO| - 2))]',
        'pframe_core.TODO = ptask_prefix* ++ [FIBER_CORE_RESULT n pconfigcall, FIBER_FINISH n]',
    ],
    'public-destructor-missing-core-tail-rejects': [
        '$fiber_core_tail_frames(S.FRAMES) = ((n, pconfigcall))',
        'S.FRAMES = [pframe_core]',
        'ptask_prefix* = pframe_core.TODO[0 : $nabs($(|pframe_core.TODO| - 2))]',
        'pframe_core.TODO = ptask_prefix* ++ [FIBER_CORE_RESULT n pconfigcall, FIBER_FINISH n]',
        'pframe_missing = pframe_core[.TODO = ptask_prefix* ++ [FIBER_FINISH n]]',
        'S_missing = S[.FRAMES = [pframe_missing]]',
        '$heap_graph(S_missing) = $heap_graph(S)',
        '~$fiber_core_result_valid(S_missing, n, pconfigcall)',
        '$destructor_trace_suffix(S_missing, pcallcontext) = eps',
        '~$call_descriptors_valid(S_missing)',
    ],
    'public-destructor-missing-saved-origin-rejects': [
        '$fiber_core_tail_frames(S.FRAMES) = ((n, pconfigcall))',
        'S.FRAMES = [pframe_core]',
        'S_bad_origin = S[.FRAMES = [pframe_core[.ORIGIN = eps]]]',
        '$heap_graph(S_bad_origin) = $heap_graph(S)',
        '~$fiber_core_result_valid(S_bad_origin, n, pconfigcall)',
        '$destructor_trace_suffix(S_bad_origin, pcallcontext) = eps',
        '~$call_descriptors_valid(S_bad_origin)',
    ],
    'public-destructor-forged-callsite-rejects': [
        '$fiber_core_tail_frames(S.FRAMES) = ((n, pconfigcall))',
        'pcallcontext_bad = pcallcontext[.CALLSITE = (pconfigcall.SITE)][.LINE = pconfigcall.LINE]',
        'S_bad_context = S[.CURRENT = (pcallcontext_bad)]',
        '$heap_graph(S_bad_context) = $heap_graph(S)',
        '$fiber_core_result_valid(S_bad_context, n, pconfigcall)',
        '~$destructor_context_valid(S_bad_context, pcallcontext_bad)',
        '$destructor_trace_suffix(S_bad_context, pcallcontext_bad) = eps',
        '~$call_descriptors_valid(S_bad_context)',
    ],
    'public-destructor-core-fields-current-and-frame-admission': [
        '$fiber_core_tail_frames(S.FRAMES) = ((n, pconfigcall))',
        '~$fiber_core_result_valid(S, n, pconfigcall[.KIND = INTRINSIC_INI_GET])',
        '~$fiber_core_result_valid(S, n, pconfigcall[.OWNER = (n)])',
        '~$fiber_core_result_valid(S, n, pconfigcall[.NAMED = true])',
        '~$fiber_core_result_valid(S, n, pconfigcall[.LINE = 0])',
        '~$fiber_core_result_valid(S, n, pconfigcall[.SENT = [NAMED_SENT (KNOWN (PINT 0))]])',
        '~$fiber_core_result_valid(S, |S.OBJECTS|, pconfigcall)',
        '$call_current_valid(S)',
        '$call_frames_valid(S, S.FRAMES)',
    ],
    'public-destructor-descriptor-and-heap-admission': [
        '$fiber_core_tail_frames(S.FRAMES) = ((n, pconfigcall))',
        '$call_descriptors_valid(S)',
        '$heap_valid($heap_graph(S))',
    ],
    'public-destructor-rich-body-scope-code-admission': [
        '$fiber_core_tail_frames(S.FRAMES) = ((n, pconfigcall))',
        '$scope_codes_valid(S, S.CODE)',
    ],
    'public-destructor-guarded-zero-transition-preserves-budget-state': [
        '$fiber_core_tail_frames(S.FRAMES) = ((n, pconfigcall))',
        '~S.COMPILESTOP',
        'S_paused = $drive_steps(S, 0)',
        'S_paused.COMPLETION = BUDGET',
        'S_paused[.COMPLETION = NORMAL] = S',
    ],
}

for name, checks in PUBLIC_PARTITIONS.items():
    CASES[name] = {'source': PUBLIC['source'], 'stage': PUBLIC_STAGE, 'checks': checks}

DEFAULT_CASES = [name for name in CASES
                 if name != 'real-public-handler-destructor-keeps-reporting-c-trace' and name not in PUBLIC_PARTITIONS]

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--case', action='append')
    args = parser.parse_args()
    assert not args.case or set(args.case) <= CASES.keys(), 'unknown core Fiber case'
    review.CASES = CASES
    review.__file__ = str(Path(__file__).resolve())
    selected = args.case or DEFAULT_CASES
    raise SystemExit(0 if all(review.run([name]) for name in selected) else 1)
