"""Paused finally source stages and assertions."""

CASES = [('normal-resume',
  b'<?php try{echo "T";}finally{echo "F";}echo "D";',
  'S.TODO = (FINALLY_RESUME porigin eps) :: ptask*',
  ['S.TODO = (FINALLY_RESUME porigin eps) :: ptask*',
   '$call_task_valid(S,FINALLY_RESUME porigin eps)',
   '~$call_task_valid(S[.ORIGIN = (porigin)],FINALLY_RESUME porigin eps)',
   '~$call_task_valid(S,FINALLY_ONLY porigin)',
   '~$call_task_valid(S,FINALLY_RESUME (PORIGIN 999 eps) eps)',
   '~$call_task_valid(S[.TODO = (FINALLY_RESUME porigin eps) :: S.TODO],FINALLY_RESUME porigin eps)',
   '$call_descriptors_valid(S)',
   '$heap_valid($heap_graph(S))',
   'S_done = $drive(S,1000)',
   '$heap_valid($heap_graph(S_done))',
   'S_done = $drive(S_initial[.COMPLETION = NORMAL],1000)',
   'S_done.COMPLETION = NORMAL',
   '$outputs(S_done.EVENTS) = $ptascii("TFD")']),
 ('throw-resume',
  b'<?php try{1/0;}finally{echo "F";}',
  'S.TODO = (FINALLY_RESUME porigin (n)) :: ptask*',
  ['S.TODO = (FINALLY_RESUME porigin (n)) :: ptask*',
   '$call_task_valid(S,FINALLY_RESUME porigin (n))',
   'S.OBJECTS[n] = THROWABLE pthrowable',
   '$throwable_chain(S,n,eps) = THROWCHAIN ([n])',
   '$($heap_owners($heap_graph(S),HOBJECT n) > 0)',
   '~$call_task_valid(S,FINALLY_RESUME porigin (999))',
   '~$throwable_chain_valid(S[.OBJECTS[n] = THROWABLE (pthrowable[.PREVIOUS = (n)])],n)',
   '~$closure_live_object_valid(S[.OBJECTS[n] = THROWABLE (pthrowable[.PREVIOUS = (n)])],n)',
   '$call_descriptors_valid(S)',
   '$heap_valid($heap_graph(S))',
   'S_done = $drive(S,1000)',
   '$heap_valid($heap_graph(S_done))',
   'S_done = $drive(S_initial[.COMPLETION = NORMAL],1000)',
   'S_done.COMPLETION = UNCAUGHT n',
   '$outputs(S_done.EVENTS) = $ptascii("F")']),
 ('replacement',
  b'<?php try{first();}finally{second();}',
  'S.TODO = (THROW_SEARCH n_new) :: (FINALLY_RESUME porigin (n_old)) :: ptask*',
  ['S.TODO = (THROW_SEARCH n_new) :: (FINALLY_RESUME porigin (n_old)) :: ptask*',
   'n_new =/= n_old',
   '$throwable_chain(S,n_new,eps) = THROWCHAIN ([n_new])',
   '$throwable_chain(S,n_old,eps) = THROWCHAIN ([n_old])',
   '$call_descriptors_valid(S)',
   '$heap_valid($heap_graph(S))',
   'S_done = $drive(S,1000)',
   '$heap_valid($heap_graph(S_done))',
   'S_done = $drive(S_initial[.COMPLETION = NORMAL],1000)',
   'S_done.COMPLETION = UNCAUGHT n_new',
   '$throwable_chain(S_done,n_new,eps) = THROWCHAIN ([n_new,n_old])',
   '$throwable_previous(S_done,n_old,n_new) = S_done',
   '$throwable_previous(S_done,n_new,n_old) = S_done',
   '$throwable_previous(S_done,n_new,n_new) = S_done',
   '$($heap_owners($heap_graph(S_done),HOBJECT n_old) > 0)']),
 ('binding-finalizer',
  b'<?php class C{public string $p="old";}$c=new C;$e=&$c->p;try{try{1/0;}catch(Error $e){echo "BAD";}finall'
  b'y{echo "F";}}catch(TypeError){echo $c->p;}',
  'S.TODO = (CATCH_BIND porigin n_index n) :: (FINALLY_ONLY porigin) :: ptask*',
  ['S.TODO = (CATCH_BIND porigin n_index n) :: (FINALLY_ONLY porigin) :: ptask*',
   '$call_task_valid(S,CATCH_BIND porigin n_index n)',
   '~$call_task_valid(S[.TODO = (CATCH_BIND porigin n_index n) :: ptask*],CATCH_BIND porigin n_index n)',
   '~$call_task_valid(S[.TODO = (CATCH_BIND porigin n_index n) :: (TRY_END porigin) :: ptask*],CATCH_BIND '
   'porigin n_index n)',
   '$call_descriptors_valid(S)',
   '$heap_valid($heap_graph(S))',
   'S_done = $drive(S,1000)',
   '$heap_valid($heap_graph(S_done))',
   'S_done = $drive(S_initial[.COMPLETION = NORMAL],1000)',
   'S_done.COMPLETION = NORMAL',
   '$outputs(S_done.EVENTS) = $ptascii("Fold")']),
 ('saved-frame-owner',
  b'<?php function boom($x){1/0;}function step(){echo "S";}try{boom(new stdClass);}finally{step();}',
  'S.FRAMES = [pframe]\n  -- if $pending_finalizer(pframe.TODO) = ((porigin,n))',
  ['S.FRAMES = [pframe]',
   '$pending_finalizer(pframe.TODO) = ((porigin,n))',
   '$call_frames_valid(S,S.FRAMES)',
   'S.OBJECTS[n] = THROWABLE pthrowable',
   'pthrowable.TRACE = [ptraceframe]',
   'ptraceframe.VALUES = [POBJECT n_arg]',
   '$($heap_owners($heap_graph(S),HOBJECT n_arg) > 0)',
   'S_bad = S[.FRAMES = [pframe[.TODO = $wrong_finalizer_origin(pframe.TODO,porigin)]]]',
   '~$call_frames_valid(S_bad,S_bad.FRAMES)',
   '~$call_descriptors_valid(S_bad)',
   'S_unowned = $prune_allocations(S[.FRAMES = [pframe[.TODO = $drop_finalizer(pframe.TODO)]]])',
   '~((HOBJECT n) <- S_unowned.ALLOCATIONS)',
   '~((HOBJECT n_arg) <- S_unowned.ALLOCATIONS)',
   '$call_descriptors_valid(S)',
   '$heap_valid($heap_graph(S))',
   'S_done = $drive(S,1000)',
   '$heap_valid($heap_graph(S_done))',
   'S_done = $drive(S_initial[.COMPLETION = NORMAL],1000)',
   'S_done.COMPLETION = UNCAUGHT n',
   '$($heap_owners($heap_graph(S_done),HOBJECT n_arg) > 0)']),
 ('exit-pending-release',
  b'<?php function boom($x){1/0;}try{boom(new stdClass);}finally{exit(7);}',
  'S.TODO = (EXIT_INVOKE pexitcall) :: ptask*',
  ['S.TODO = (EXIT_INVOKE pexitcall) :: ptask*',
   '$pending_finalizer(S.TODO) = ((porigin,n))',
   'S.OBJECTS[n] = THROWABLE pthrowable',
   'pthrowable.TRACE = [ptraceframe]',
   'ptraceframe.VALUES = [POBJECT n_arg]',
   '$($heap_owners($heap_graph(S),HOBJECT n) > 0)',
   '$($heap_owners($heap_graph(S),HOBJECT n_arg) > 0)',
   '$call_descriptors_valid(S)',
   '$heap_valid($heap_graph(S))',
   'S_done = $drive(S,1000)',
   'S_done.COMPLETION = EXITED 7',
   'S_done.TODO = eps',
   'S_done.FRAMES = eps',
   '~((HOBJECT n) <- S_done.ALLOCATIONS)',
   '~((HOBJECT n_arg) <- S_done.ALLOCATIONS)',
   '$heap_valid($heap_graph(S_done))',
   'S_done = $drive(S_initial[.COMPLETION = NORMAL],1000)'])]

PREFIX = 'dec $pending_finalizer(ptask*) : (porigin,nat)?\n\ndec $stage(pstate) : bool\ndef $stage(S) = true -- if STAGE\ndef $stage(S) = false -- otherwise\ndec $seek(pstate, nat) : pstate\ndef $seek(S, n) = S -- if $stage(S)\ndef $seek(S, n) = $seek($drive_steps(S[.COMPLETION = NORMAL], 1), $nabs($(n - 1)))\n  -- if ~$stage(S)\n  -- if $(n > 0)\ndec $outputs(pevent*) : nat*\ndef $outputs(eps) = eps\ndef $outputs((OUTPUT n*) :: pevent*) = n* ++ $outputs(pevent*)\ndef $outputs((WARNING n* z) :: pevent*) = $outputs(pevent*)\ndef $outputs((DIAGNOSTIC text n* z) :: pevent*) = $outputs(pevent*)\ndec $pending_task(ptask) : (porigin,nat)?\ndef $pending_task(FINALLY_RESUME porigin (n)) = ((porigin,n))\ndef $pending_task(ptask) = eps -- otherwise\ndef $pending_finalizer(eps) = eps\ndef $pending_finalizer(ptask :: ptask_tail*) = ((porigin,n))\n  -- if $pending_task(ptask) = ((porigin,n))\ndef $pending_finalizer(ptask :: ptask_tail*) = $pending_finalizer(ptask_tail*)\n  -- if $pending_task(ptask) = eps\ndec $wrong_finalizer_task(ptask,porigin) : ptask\ndef $wrong_finalizer_task(ORIGIN_RETURN porigin_old?,porigin) = ORIGIN_RETURN (porigin)\ndef $wrong_finalizer_task(ptask,porigin) = ptask -- otherwise\ndec $wrong_finalizer_origin(ptask*,porigin) : ptask*\ndef $wrong_finalizer_origin(eps,porigin) = eps\ndef $wrong_finalizer_origin(ptask :: ptask_tail*,porigin) = $wrong_finalizer_task(ptask,porigin) :: $wrong_finalizer_origin(ptask_tail*,porigin)\n\ndec $drop_finalizer_task(ptask) : ptask*\ndef $drop_finalizer_task(FINALLY_RESUME porigin n?) = eps\ndef $drop_finalizer_task(ptask) = [ptask] -- otherwise\ndec $drop_finalizer(ptask*) : ptask*\ndef $drop_finalizer(eps) = eps\ndef $drop_finalizer(ptask :: ptask_tail*) = $drop_finalizer_task(ptask) ++ $drop_finalizer(ptask_tail*)\n'

from finally_transfer_protocol_cases import CASES as TRANSFER_CASES, PREFIX as TRANSFER_PREFIX
CASES += TRANSFER_CASES
PREFIX = TRANSFER_PREFIX + PREFIX
