#!/usr/bin/env python3
"""Durable capture permission, entered frames, ownership and factory unwinding."""
from pathlib import Path
import argparse
import json

import closure_call_protocol as protocol

CATALOGUE = Path(__file__).with_name('from_callable_cases.json')
SOURCES = {row['id']: row['source'] for row in json.loads(CATALOGUE.read_text())}

VALID = ['$call_descriptors_valid(S)', '$closure_state_valid(S)', '$heap_valid($heap_graph(S))']
AFTER = ['$call_descriptors_valid(S_done)', '$closure_state_valid(S_done)', '$heap_valid($heap_graph(S_done))']
COMMON = [
    'S.OBJECTS[n_capture] = FROMCALLABLECLOSURE pfrommethod',
    '$from_valid(S, pfrommethod)',
    '$closure_callable(S, n_capture)',
    '$target_nodes(CLOSURE_TARGET n_capture) = [HOBJECT n_capture]',
    '$class_method_origin(S.CLASSES, pfrommethod.FUNCTION) = (pmethoddesc)',
    'pcallcontext.FUNCTION = pmethoddesc.FUNCTION.ORIGIN',
    'pcallcontext.LEXICAL_CLASS = (pmethoddesc.OWNER)',
    'pcallcontext.CALLED_CLASS = (pfrommethod.CLASS.CALLED)',
    'pcallcontext.INSTANCE = (n_capture)',
    'S.FRAMES = pframe_global :: pframe_tail*',
    'pframe_global.CONTEXT = eps',
    'pframe_global.LOCALS = eps',
    'S.GLOBALTABLE = (psymboltable_global)',
    '$lookup(psymboltable_global.ENV, $ptascii("copy")) = (n_copy_cell)',
    'S.STORE[n_copy_cell] = DEFINED (POBJECT n_copy)',
    'S.OBJECTS[n_copy] = FROMCALLABLECLOSURE pfrommethod',
    'n_copy =/= n_capture',
    '$closure_callable(S, n_copy)',
    *VALID,
    '~$from_valid(S, pfrommethod[.STATIC = ~pfrommethod.STATIC])',
    '~$from_valid(S, pfrommethod[.NAME = $ptascii("missing")])',
    '~$from_valid(S, pfrommethod[.WIDTH = $(pfrommethod.WIDTH + 1)])',
    '~$call_current_valid(S[.CURRENT = (pcallcontext[.LEXICAL_CLASS = eps])])',
    '~$call_current_valid(S[.CURRENT = (pcallcontext[.CALLED_CLASS = eps])])',
    '~$call_current_valid(S[.CURRENT = (pcallcontext[.INSTANCE = (n_copy)])])',
]
RESUME = [
    'S_budget = $drive(S, 0)',
    'S_budget.COMPLETION = BUDGET',
    '$call_descriptors_valid(S_budget)',
    '$closure_state_valid(S_budget)',
    '$heap_valid($heap_graph(S_budget))',
    'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
    'S_done.COMPLETION = NORMAL',
    'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
    '~((HOBJECT n_capture) <- S_done.ALLOCATIONS)',
    '~((HOBJECT n_copy) <- S_done.ALLOCATIONS)',
    *AFTER,
]

CASES = {
 'capture-static-foreign-called-retired-maker': {
  'source': SOURCES['static-foreign-called'] + 'unset($first, $copy);\n',
  'stage': 'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* -- if pargcall.KIND = INTRINSIC_GET_CALLED_CLASS -- if S.CURRENT = (pcallcontext) -- if pcallcontext.TARGET = CLOSURE_TARGET n_capture -- if S.OBJECTS[n_capture] = FROMCALLABLECLOSURE pfrommethod',
  'checks': [
    *COMMON,
    'pfrommethod.STATIC',
    'pfrommethod.CLASS.RECEIVER = (n_maker)',
    'S.OBJECTS[n_maker] = INSTANCE pfrommethod.CLASS.CALLED',
    '~((HOBJECT n_maker) <- S.ALLOCATIONS)',
    '$node_children(S, HOBJECT n_capture) = eps',
    '$node_children(S, HOBJECT n_copy) = eps',
    '$heap_owners($heap_graph(S), HOBJECT n_maker) = 0',
    'pcallcontext.RECEIVER = eps',
    'pmethoddesc.OWNER = pfrommethod.CLASS.REQUESTED',
    'pfrommethod.CLASS.CALLED =/= pfrommethod.CLASS.REQUESTED',
    '$calledclass_name(S, pargcall) = ($ptascii("StaticForeign"))',
    'pfrommethod.METHOD = $ptascii("self::run")',
    'pfrommethod.PREFIX = 6 /\\ pfrommethod.WIDTH = 3',
    '~$from_valid(S, pfrommethod[.ARRAY = false])',
    '~$from_valid(S, pfrommethod[.INVOKE = true])',
    '~$from_valid(S, pfrommethod[.METHOD = $ptascii("self::bad")])',
    '~$call_current_valid(S[.CURRENT = (pcallcontext[.RECEIVER = (n_maker)])])',
    *RESUME,
    '$capture_outputs(S_done.EVENTS) = $ptascii("D|0:StaticRequested:StaticForeign:StaticForeign:1|0:StaticRequested:StaticForeign:StaticForeign:2|")',
  ],
 },
 'capture-instance-foreign-frame-clone-owners': {
  'source': SOURCES['foreign-run-cache'],
  'stage': 'S.CURRENT = (pcallcontext) -- if pcallcontext.TARGET = CLOSURE_TARGET n_capture -- if S.OBJECTS[n_capture] = FROMCALLABLECLOSURE pfrommethod -- if pfrommethod.NAME = $ptascii("run")',
  'checks': [
    *COMMON,
    '~pfrommethod.STATIC',
    'pfrommethod.CLASS.RECEIVER = (n_receiver)',
    'S.OBJECTS[n_receiver] = INSTANCE pfrommethod.CLASS.CALLED',
    'pfrommethod.CLASS.CALLED =/= pfrommethod.CLASS.REQUESTED',
    'pfrommethod.SCOPE = (pfrommethod.CLASS.CALLED)',
    'pcallcontext.RECEIVER = (n_receiver)',
    'pmethoddesc.OWNER = pfrommethod.CLASS.REQUESTED',
    '$node_children(S, HOBJECT n_capture) = [HOBJECT n_receiver]',
    '$node_children(S, HOBJECT n_copy) = [HOBJECT n_receiver]',
    '$($heap_owners($heap_graph(S), HOBJECT n_receiver) >= 2)',
    '~$scoped_receiver_valid(S, pfrommethod.CLASS.REQUESTED, pmethoddesc, (n_receiver))',
    '$target_function(S, SCOPED_TARGET pfrommethod.CLASS.REQUESTED pfrommethod.FUNCTION pfrommethod.CLASS.CALLED (n_receiver) (KNOWN (PSTRING $ptascii("RequestedRun")))) = eps',
    '~$from_valid(S, pfrommethod[.SCOPE = (pfrommethod.CLASS.REQUESTED)])',
    '~$from_valid(S, pfrommethod[.CLASS = pfrommethod.CLASS[.CALLED = pfrommethod.CLASS.REQUESTED]])',
    '~$call_current_valid(S[.CURRENT = (pcallcontext[.RECEIVER = eps])])',
    *RESUME,
    '$capture_outputs(S_done.EVENTS) = $ptascii("D|ForeignRun:RequestedRun:ForeignRun|ForeignRun:RequestedRun:ForeignRun|")',
    '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
  ],
 },
 'capture-compound-frozen-leaf-after-alias-retirement': {
  'source': SOURCES['compound-held-cache'] + 'unset($first, $copy);\n',
  'stage': 'S.CURRENT = (pcallcontext) -- if pcallcontext.TARGET = CLOSURE_TARGET n_capture -- if S.OBJECTS[n_capture] = FROMCALLABLECLOSURE pfrommethod -- if pfrommethod.NAME = $ptascii("ok")',
  'checks': [
    *COMMON,
    'pfrommethod.STATIC /\\ pfrommethod.ARRAY',
    'pfrommethod.INPUT = PSTRING $ptascii("self")',
    'pfrommethod.METHOD = $ptascii("YYYYYY::ok")',
    'pfrommethod.ORIGINAL = $ptascii("parent::ok")',
    'pfrommethod.PREFIX = 8 /\\ pfrommethod.WIDTH = 2',
    '~$from_valid(S, pfrommethod[.ARRAY = false])',
    'pfrommethod.NAME = $ptascii("ok")',
    'pfrommethod.OUTER = (papiclass_outer)',
    'papiclass_outer.REQUESTED = pfrommethod.CLASS.CALLED',
    'pmethoddesc.OWNER = pfrommethod.CLASS.REQUESTED',
    'pfrommethod.CLASS.CALLED =/= pfrommethod.CLASS.REQUESTED',
    '$lookup(psymboltable_global.ENV, $ptascii("method")) = eps',
    '$capture_retired_refs(S, S.REFCELLS)',
    '$node_children(S, HOBJECT n_capture) = eps',
    '$node_children(S, HOBJECT n_copy) = eps',
    'pcallcontext.RECEIVER = eps',
    '~$from_valid(S, pfrommethod[.METHOD = $ptascii("parent::xx")])',
    '~$from_valid(S, pfrommethod[.PREFIX = 0][.WIDTH = 0])',
    '~$from_valid(S, pfrommethod[.INPUT = PSTRING $ptascii("MissingHeld")])',
    *RESUME,
    '$capture_outputs(S_done.EVENTS) = $ptascii("D1|D2|BaseHeld:OwnerHeld|BaseHeld:OwnerHeld|")',
  ],
 },
 'capture-rebound-maker-permission-after-retirement': {
  'source': SOURCES['rebound-maker-permission'],
  'stage': 'S.CURRENT = (pcallcontext) -- if pcallcontext.TARGET = CLOSURE_TARGET n_capture -- if S.OBJECTS[n_capture] = FROMCALLABLECLOSURE pfrommethod -- if pfrommethod.NAME = $ptascii("only")',
  'checks': [
    *COMMON,
    '~pfrommethod.STATIC /\\ pfrommethod.ARRAY',
    'pfrommethod.INPUT = PSTRING $ptascii("self")',
    'pfrommethod.CLASS.RECEIVER = (n_receiver)',
    'pfrommethod.SCOPE = (pmethoddesc.OWNER)',
    'pmethoddesc.VISIBILITY = PROPERTY_PRIVATE',
    '$closure_source_class(S, pfrommethod.SITE) = eps',
    'pfrommethod.CREATION = (pmethodcapture)',
    'pmethodcapture.LEXICAL_CLASS = pfrommethod.SCOPE',
    'pmethodcapture.CALLED_CLASS = pfrommethod.CALLED',
    '$method_capture_template(S, pmethodcapture.FUNCTION)',
    '$from_permission(S, pfrommethod)',
    '$lookup(psymboltable_global.ENV, $ptascii("maker")) = eps',
    '$lookup(psymboltable_global.ENV, $ptascii("template")) = eps',
    '$lookup(psymboltable_global.ENV, $ptascii("receiver")) = eps',
    'S.OBJECTS[n_receiver] = INSTANCE pfrommethod.CLASS.CALLED',
    'pcallcontext.RECEIVER = (n_receiver)',
    '$node_children(S, HOBJECT n_capture) = [HOBJECT n_receiver]',
    '$node_children(S, HOBJECT n_copy) = [HOBJECT n_receiver]',
    '~$from_valid(S, pfrommethod[.CREATION = eps])',
    '~$from_valid(S, pfrommethod[.SCOPE = eps])',
    '~$from_valid(S, pfrommethod[.CREATION = (pmethodcapture[.LEXICAL_CLASS = eps])])',
    *RESUME,
    '$capture_outputs(S_done.EVENTS) = $ptascii("D|ReboundOwner:ReboundChild:ReboundChild|ReboundOwner:ReboundChild:ReboundChild|")',
    '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
  ],
 },
}

DEFAULT_VALID = ['$call_descriptors_valid(S)', '$class_state_valid(S)',
                 '$closure_state_valid(S)', '$heap_valid($heap_graph(S))']
DEFAULT_AFTER = ['$call_descriptors_valid(S_done)', '$class_state_valid(S_done)',
                 '$closure_state_valid(S_done)', '$heap_valid($heap_graph(S_done))']

CASES.update({
    'capture-static-private-default-after-raw-retirement': {
        'source': SOURCES['cached-static-default'],
        'stage': ('S.CURRENT = (pcallcontext) '
                  '-- if pcallcontext.TARGET = CLOSURE_TARGET n_capture '
                  '-- if S.OBJECTS[n_capture] = FROMCALLABLECLOSURE pfrommethod '
                  '-- if pfrommethod.NAME = $ptascii("probe") '
                  '-- if $lookup(S.ENV, $ptascii("value")) = (n_value) '
                  '-- if S.STORE[n_value] = DEFINED (PSTRING $ptascii("value"))'),
        'checks': [
            'pfrommethod.STATIC /\\ pfrommethod.ARRAY /\\ ~pfrommethod.INVOKE',
            'pfrommethod.INPUT = PSTRING $ptascii("self")',
            'pfrommethod.METHOD = $ptascii("probe")',
            'pfrommethod.ORIGINAL = $ptascii("gone")',
            'pfrommethod.PREFIX = 0 /\\ pfrommethod.WIDTH = 0',
            'pfrommethod.OUTER = eps /\\ pfrommethod.CREATION = eps',
            'pfrommethod.THIS = (n_maker)',
            'pfrommethod.CLASS.RECEIVER = (n_maker)',
            'pfrommethod.SCOPE = (pfrommethod.CLASS.REQUESTED)',
            'S.OBJECTS[n_maker] = INSTANCE pfrommethod.CLASS.CALLED',
            '~((HOBJECT n_maker) <- S.ALLOCATIONS)',
            '$heap_owners($heap_graph(S), HOBJECT n_maker) = 0',
            '$class_method_origin(S.CLASSES, pfrommethod.FUNCTION) = (pmethoddesc)',
            'pmethoddesc.VISIBILITY = PROPERTY_PRIVATE /\\ pmethoddesc.STATIC',
            'pmethoddesc.OWNER = pfrommethod.CLASS.REQUESTED',
            '$class_at(S.CLASSES, pmethoddesc.OWNER) = (pclassdesc_owner)',
            'pclassdesc_owner.NAME = $ptascii("FromDefaultOwner")',
            '$class_at(S.CLASSES, pfrommethod.CLASS.CALLED) = (pclassdesc_child)',
            'pclassdesc_child.NAME = $ptascii("FromDefaultChild")',
            'pcallcontext.LEXICAL_CLASS = (pmethoddesc.OWNER)',
            'pcallcontext.CALLED_CLASS = (pfrommethod.CLASS.CALLED)',
            'pcallcontext.RECEIVER = eps /\\ pcallcontext.INSTANCE = (n_capture)',
            'pcallcontext.ARGC = 0 /\\ pcallcontext.HOLES = eps',
            '~$fixed_parameter_supplied(S, 0)',
            '$fixed_parameter_defaulted(S, 0)',
            'pmethoddesc.FUNCTION.DEFAULTS = [pdefault]',
            'pdefault.INDEX = 0 /\\ pdefault.KIND = PDDEFERRED',
            '$from_valid(S, pfrommethod)',
            '$closure_callable(S, n_capture)',
            '$node_children(S, HOBJECT n_capture) = eps',
            'S.FRAMES = pframe_global :: pframe_tail*',
            'pframe_global.CONTEXT = eps /\\ pframe_global.LOCALS = eps',
            'S.GLOBALTABLE = (psymboltable_global)',
            '$lookup(psymboltable_global.ENV, $ptascii("maker")) = eps',
            '$lookup(psymboltable_global.ENV, $ptascii("copy")) = (n_copy_cell)',
            'S.STORE[n_copy_cell] = DEFINED (POBJECT n_copy)',
            'S.OBJECTS[n_copy] = FROMCALLABLECLOSURE pfrommethod',
            'n_copy =/= n_capture /\\ $closure_callable(S, n_copy)',
            '$node_children(S, HOBJECT n_copy) = eps',
            'S.ERRORHANDLER.CALLBACK = eps /\\ S.ERRORHANDLERS = eps',
            *DEFAULT_VALID,
            '~$from_valid(S, pfrommethod[.STATIC = false])',
            '~$from_valid(S, pfrommethod[.INVOKE = true])',
            '~$from_valid(S, pfrommethod[.METHOD = $ptascii("gone")])',
            '~$from_valid(S, pfrommethod[.SCOPE = eps])',
            '~$call_current_valid(S[.CURRENT = (pcallcontext[.RECEIVER = (n_maker)])])',
            'S_budget = $drive_steps(S, 0)',
            'S_budget.COMPLETION = BUDGET',
            'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
            'S_done.COMPLETION = NORMAL',
            '$capture_outputs(S_done.EVENTS) = $ptascii("D|V|1:FromDefaultOwner:FromDefaultChild:FromDefaultChild:value|V|2:FromDefaultOwner:FromDefaultChild:FromDefaultChild:value|")',
            'S_done.STATICS = [pstaticcell]',
            'S_done.STORE[pstaticcell.CELL] = DEFINED (PINT 2)',
            '(HCELL pstaticcell.CELL) <- S_done.ALLOCATIONS',
            '$heap_owners($heap_graph(S_done), HCELL pstaticcell.CELL) = 1',
            '~((HOBJECT n_capture) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_copy) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_maker) <- S_done.ALLOCATIONS)',
            'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
            *DEFAULT_AFTER,
        ],
    },
    'capture-warning-finally-chain-after-handler-restoration': {
        'source': SOURCES['late-chain'],
        'stage': ('S.TODO = (THROW_SEARCH n_outer) :: ptask_tail* '
                  '-- if S.OBJECTS[n_outer] = THROWABLE pthrowable '
                  '-- if pthrowable.KIND = "TypeError" '
                  '-- if S.CURRENT = (pcallcontext)'),
        'checks': [
            'pcallcontext.TARGET = METHOD_TARGET n_maker porigin_make',
            'pcallcontext.RECEIVER = (n_maker)',
            'S.OBJECTS[n_maker] = INSTANCE porigin_owner',
            '$class_at(S.CLASSES, porigin_owner) = (pclassdesc)',
            'pclassdesc.NAME = $ptascii("FromThrowOwner")',
            'pcallcontext.LEXICAL_CLASS = (porigin_owner)',
            'pcallcontext.CALLED_CLASS = (porigin_owner)',
            '$lookup(S.ENV, $ptascii("callback")) = (n_callback)',
            'S.STORE[n_callback] = DEFINED (PARRAY n_array)',
            '$entry_lookup(S.ARRAYS[n_array].ITEMS, KINT 1) = (ALIAS n_method)',
            'S.STORE[n_method] = DEFINED (PSTRING $ptascii("run"))',
            'S.ERRORHANDLER.CALLBACK = (POBJECT n_handler)',
            '$closure_callable(S, n_handler)',
            '~$api_pending_tasks(ptask_tail*)',
            '$throwable_field(S, n_outer, "message") = PSTRING $ptascii("Failed to create closure from callable")',
            '$throwable_previous_id(S, n_outer) = (n_new)',
            'S.OBJECTS[n_new] = THROWABLE pthrowable_new',
            'pthrowable_new.KIND = "Exception"',
            '$throwable_field(S, n_new, "message") = PSTRING $ptascii("new")',
            '$throwable_previous_id(S, n_new) = (n_old)',
            'S.OBJECTS[n_old] = THROWABLE pthrowable_old',
            'pthrowable_old.KIND = "Exception"',
            '$throwable_field(S, n_old, "message") = PSTRING $ptascii("old")',
            '$throwable_field(S, n_old, "previous") = PNULL',
            '$throwable_chain_valid(S, n_outer)',
            '$heap_owners($heap_graph(S), HOBJECT n_new) = 1',
            '$heap_owners($heap_graph(S), HOBJECT n_old) = 1',
            *DEFAULT_VALID,
            'S_budget = $drive_steps(S, 0)',
            'S_budget.COMPLETION = BUDGET',
            'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
            'S_done.COMPLETION = NORMAL',
            '$capture_outputs(S_done.EVENTS) = $ptascii("Failed to create closure from callable|new:old|")',
            'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
            'S_done.ERRORHANDLER.CALLBACK = eps /\\ S_done.ERRORHANDLERS = eps',
            '~((HOBJECT n_outer) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_new) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_old) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_handler) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_maker) <- S_done.ALLOCATIONS)',
            '~((HARRAY n_array) <- S_done.ALLOCATIONS)',
            '~((HCELL n_method) <- S_done.ALLOCATIONS)',
            *DEFAULT_AFTER,
        ],
    },
})

CREATOR_VALID = ['$call_descriptors_valid(S)', '$class_state_valid(S)', '$closure_state_valid(S)', '$heap_valid($heap_graph(S))']
CREATOR_AFTER = ['$call_descriptors_valid(S_done)', '$class_state_valid(S_done)', '$closure_state_valid(S_done)', '$heap_valid($heap_graph(S_done))']
CREATOR_COMMON = [
 '$closure_scope_at(S.CLOSURESCOPES, n_child) = (pclosurescope)',
 'pclosurescope.CREATION = (pclosurecreation)',
 'pclosurecreation.EVIDENCE = (pclosurecreator)',
 'pclosurecreator.SCOPE = CLOSURE_SCOPE pclosurescope_parent',
 'n_parent = pclosurescope_parent.OBJECT',
 'S.OBJECTS[n_parent] = FROMCALLABLECLOSURE pfrommethod',
 '$class_method_origin(S.CLASSES, pfrommethod.FUNCTION) = (pmethoddesc)',
 'pclosurecreation.FUNCTION = pfrommethod.FUNCTION',
 'pclosurecreation.CALLSITE = pclosurecreator.CALLSITE',
 '~pclosurecreation.RECEIVER',
 'pclosurescope.LEXICAL = pmethoddesc.OWNER',
 'pclosurescope.CALLED = pfrommethod.CLASS.CALLED',
 'pclosurescope.RECEIVER = eps',
 'pclosurescope_parent.LEXICAL = pmethoddesc.OWNER',
 'pclosurescope_parent.CALLED = pfrommethod.CLASS.CALLED',
 'pclosurescope_parent.CREATION = eps',
 'pclosurescope_parent.RECEIVER = $from_receiver(pfrommethod)',
 '$node_children(S, HOBJECT n_child) = eps',
 '$from_valid($from_history(S, pfrommethod), pfrommethod)',
 '$closure_evidence_valid(S, pclosurecreator.SCOPE)',
 '$closure_evidence_body(S, n_parent) = (pfrommethod.FUNCTION)',
 '$from_child_valid(S, porigin, pclosurescope)',
 '$closure_creator_valid(S, porigin, pclosurescope, pclosurecreation, pclosurecreator)',
 '$closure_callable(S, n_child)',
 'pcallcontext.INSTANCE = (n_child) /\\ pcallcontext.RECEIVER = eps',
 'pcallcontext.LEXICAL_CLASS = (pmethoddesc.OWNER)',
 'pcallcontext.CALLED_CLASS = (pfrommethod.CLASS.CALLED)',
 *CREATOR_VALID,
 '~$closure_evidence_valid(S, CLOSURE_SCOPE (pclosurescope_parent[.CREATION = (pclosurecreation)]))',
 '~$closure_evidence_valid(S[.OBJECTS[n_parent] = FROMCALLABLECLOSURE (pfrommethod[.NAME = $ptascii("missing")])], pclosurecreator.SCOPE)',
 '~$closure_evidence_valid(S[.OBJECTS[n_parent] = FROMCALLABLECLOSURE (pfrommethod[.STATIC = ~pfrommethod.STATIC])], pclosurecreator.SCOPE)',
 '~$from_child_valid(S, porigin, pclosurescope[.CREATION = eps])',
 '~$from_child_valid(S, porigin, pclosurescope[.CREATION = (pclosurecreation[.EVIDENCE = eps])])',
 '~$from_child_valid(S, porigin, pclosurescope[.CREATION = (pclosurecreation[.FUNCTION = porigin])])',
 '~$from_child_valid(S, porigin, pclosurescope[.CREATION = (pclosurecreation[.CALLSITE = eps])])',
 '~$call_current_valid(S[.CURRENT = (pcallcontext[.LEXICAL_CLASS = eps])])',
 '~$call_current_valid(S[.CURRENT = (pcallcontext[.CALLED_CLASS = eps])])',
]
CREATOR_RESUME = [
 'S_budget = $drive(S, 0)', 'S_budget.COMPLETION = BUDGET',
 '$call_descriptors_valid(S_budget)', '$closure_state_valid(S_budget)', '$heap_valid($heap_graph(S_budget))',
 'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)', 'S_done.COMPLETION = NORMAL',
 'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
 '~((HOBJECT n_child) <- S_done.ALLOCATIONS)', '~((HOBJECT n_parent) <- S_done.ALLOCATIONS)', *CREATOR_AFTER,
]
CREATOR_CASES = {
 'capture-static-child-creator-retired-parent': {
  'source': SOURCES['current-creator'],
  'stage': 'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* -- if pargcall.KIND = INTRINSIC_GET_CALLED_CLASS -- if S.CURRENT = (pcallcontext) -- if pcallcontext.TARGET = CLOSURE_TARGET n_child -- if $object_body(S.OBJECTS[n_child]) = REALCLOSURE porigin pitem* pstaticcell* -- if $closure_source_class(S, porigin) = (porigin_owner) -- if $class_at(S.CLASSES, porigin_owner) = (pclassdesc) -- if pclassdesc.NAME = $ptascii("FromNestedRequested")',
  'checks': [*CREATOR_COMMON,
   'pclosurescope_parent.RECEIVER = (n_maker)',
   'S.OBJECTS[n_maker] = INSTANCE pfrommethod.CLASS.CALLED',
   'pfrommethod.CLASS.CALLED =/= pmethoddesc.OWNER', '~pfrommethod.STATIC',
   '~((HOBJECT n_parent) <- S.ALLOCATIONS)', '~((HOBJECT n_maker) <- S.ALLOCATIONS)',
   '$closure_scope_at(S.CLOSURESCOPES, n_parent) = eps',
   '$heap_owners($heap_graph(S), HOBJECT n_parent) = 0', '$heap_owners($heap_graph(S), HOBJECT n_maker) = 0',
   '~$from_valid(S, pfrommethod)', '~$closure_scope_original_classes(S, porigin, pclosurescope)',
   '~$closure_evidence_valid(S, CLOSURE_SCOPE (pclosurescope_parent[.LEXICAL = pfrommethod.CLASS.CALLED]))',
   '~$closure_evidence_valid(S, CLOSURE_SCOPE (pclosurescope_parent[.CALLED = pmethoddesc.OWNER]))',
   '~$closure_evidence_valid(S, CLOSURE_SCOPE (pclosurescope_parent[.RECEIVER = eps]))',
   '~$closure_scope_row_valid(S, pclosurescope[.RECEIVER = (n_maker)])',
   *CREATOR_RESUME,
   '~((HOBJECT n_maker) <- S_done.ALLOCATIONS)',
   '$capture_outputs(S_done.EVENTS) = $ptascii("D|FromNestedRequested:FromNestedForeign:FromNestedForeign|")',
  ],
 },
 'capture-trait-cold-reference-callback-import-proof': {
  'source': SOURCES['current-trait-cold-v4'],
  'stage': 'S.CURRENT = (pcallcontext) -- if pcallcontext.TARGET = CLOSURE_TARGET n_child -- if $object_body(S.OBJECTS[n_child]) = REALCLOSURE porigin pitem* pstaticcell* -- if $closure_scope_at(S.CLOSURESCOPES, n_child) = (pclosurescope) -- if pclosurescope.CREATION = (pclosurecreation) -- if pclosurecreation.EVIDENCE = (pclosurecreator) -- if pclosurecreator.SCOPE = CLOSURE_SCOPE pclosurescope_parent -- if n_parent = pclosurescope_parent.OBJECT -- if S.OBJECTS[n_parent] = FROMCALLABLECLOSURE pfrommethod -- if pfrommethod.NAME = $ptascii("run") -- if $class_at(S.CLASSES, pfrommethod.CLASS.CALLED) = (pclassdesc) -- if pclassdesc.NAME = $ptascii("FromTraitA")',
  'checks': [*CREATOR_COMMON,
   'pfrommethod.CREATION = (pmethodcapture)', '$trait_imported_origin(pmethodcapture.FUNCTION)',
   '$method_capture_certificate_valid(S, pfrommethod.SITE, (pmethodcapture))',
   '$trait_imported_origin(pfrommethod.FUNCTION)',
   'pfrommethod.FUNCTION = TRAIT_ORIGIN pmethoddesc.OWNER porigin_source ptbytes',
   'pfrommethod.STATIC /\\ pmethoddesc.STATIC', 'pfrommethod.CLASS.CALLED = pmethoddesc.OWNER',
   'pfrommethod.THIS = eps /\\ pfrommethod.CLASS.RECEIVER = eps', '$from_valid(S, pfrommethod)',
   '$node_children(S, HOBJECT n_parent) = eps',
   '$closure_nearest_owner(S, $closure_creation_owners($all_functions(S), porigin), eps) = ($origin_source(pfrommethod.FUNCTION))',
   '$closure_scope_original_classes(S, porigin, pclosurescope)',
   '~$from_valid(S, pfrommethod[.CREATION = eps])',
   '~$from_valid(S, pfrommethod[.FUNCTION = $origin_source(pfrommethod.FUNCTION)])',
   '~$from_child_valid(S, porigin, pclosurescope[.CREATION = (pclosurecreation[.FUNCTION = $origin_source(pclosurecreation.FUNCTION)])])',
   *CREATOR_RESUME,
   '$capture_outputs(S_done.EVENTS) = $ptascii("D|D|W|a2048:FromTraitA:FromTraitA:1|a2048:FromTraitA:FromTraitA:2|W|b2048:FromTraitB:FromTraitB:1|")',
   'S_done.STATICS = [pstaticcell_a, pstaticcell_b]',
   '$trait_imported_origin(pstaticcell_a.ORIGIN)', '$trait_imported_origin(pstaticcell_b.ORIGIN)',
   '$origin_source(pstaticcell_a.ORIGIN) = $origin_source(pstaticcell_b.ORIGIN)',
   'pstaticcell_a.ORIGIN =/= pstaticcell_b.ORIGIN',
   'S_done.STORE[pstaticcell_a.CELL] = DEFINED (PINT 2)', 'S_done.STORE[pstaticcell_b.CELL] = DEFINED (PINT 1)',
  ],
 },
}

CASES.update(CREATOR_CASES)

NESTED_CASES = {
    'capture-nested-instance-child-keeps-foreign-receiver': {
        'source': SOURCES['foreign-nested-instance-child'],
        'stage': ('S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* '
                  '-- if pargcall.KIND = INTRINSIC_GET_CALLED_CLASS '
                  '-- if S.CURRENT = (pcallcontext) '
                  '-- if pcallcontext.TARGET = CLOSURE_TARGET n_child '
                  '-- if S.OBJECTS[n_child] = REALCLOSURE porigin_child pitem* pstaticcell*'),
        'checks': [
            '$closure_scope_at(S.CLOSURESCOPES, n_child) = (pclosurescope_child)',
            'pclosurescope_child.CREATION = (pclosurecreation)',
            'pclosurecreation.EVIDENCE = (pclosurecreator)',
            'n_parent = $closure_evidence_object(pclosurecreator.SCOPE)',
            'S.OBJECTS[n_parent] = FROMCALLABLECLOSURE pfrommethod',
            '~pfrommethod.STATIC',
            'pfrommethod.NAME = $ptascii("make")',
            '$class_method_origin(S.CLASSES, pfrommethod.FUNCTION) = (pmethoddesc)',
            'pclosurecreation.FUNCTION = pfrommethod.FUNCTION',
            'pclosurecreation.CALLSITE = pclosurecreator.CALLSITE',
            'pclosurecreation.RECEIVER',
            '$closure_evidence_body(S, n_parent) = (pfrommethod.FUNCTION)',
            '$closure_evidence_valid(S, pclosurecreator.SCOPE)',
            '$closure_creator_valid(S, porigin_child, pclosurescope_child, pclosurecreation, pclosurecreator)',
            'pclosurescope_child.LEXICAL = pmethoddesc.OWNER',
            'pclosurescope_child.CALLED = pfrommethod.CLASS.CALLED',
            'pclosurescope_child.LEXICAL =/= pclosurescope_child.CALLED',
            'pclosurescope_child.RECEIVER = (n_receiver)',
            '$from_receiver(pfrommethod) = (n_receiver)',
            'S.OBJECTS[n_receiver] = INSTANCE pclosurescope_child.CALLED',
            '(HOBJECT n_receiver) <- S.ALLOCATIONS',
            '$closure_evidence_receiver(pclosurecreator.SCOPE) = (n_receiver)',
            'pcallcontext.LEXICAL_CLASS = (pclosurescope_child.LEXICAL)',
            'pcallcontext.CALLED_CLASS = (pclosurescope_child.CALLED)',
            'pcallcontext.RECEIVER = (n_receiver)',
            'pcallcontext.FUNCTION = porigin_child',
            'pcallcontext.INSTANCE = (n_child)',
            'S.FRAMES = pframe_global :: pframe_tail*',
            'pframe_global.CONTEXT = eps /\\ pframe_global.LOCALS = eps',
            'S.GLOBALTABLE = (psymboltable_global)',
            '$lookup(psymboltable_global.ENV, $ptascii("maker")) = eps',
            '$lookup(psymboltable_global.ENV, $ptascii("parent")) = eps',
            '$lookup(psymboltable_global.ENV, $ptascii("copy")) = (n_copy_cell)',
            'S.STORE[n_copy_cell] = DEFINED (POBJECT n_copy)',
            'n_copy =/= n_child',
            '$closure_scope_at(S.CLOSURESCOPES, n_copy) = (pclosurescope_copy)',
            'pclosurescope_copy.LEXICAL = pclosurescope_child.LEXICAL',
            'pclosurescope_copy.CALLED = pclosurescope_child.CALLED',
            'pclosurescope_copy.RECEIVER = pclosurescope_child.RECEIVER',
            'pclosurescope_copy.CREATION = pclosurescope_child.CREATION',
            '~((HOBJECT n_parent) <- S.ALLOCATIONS)',
            '$closure_scope_at(S.CLOSURESCOPES, n_parent) = eps',
            '$heap_owners($heap_graph(S), HOBJECT n_parent) = 0',
            '$node_children(S, HOBJECT n_child) = [HOBJECT n_receiver]',
            '$node_children(S, HOBJECT n_copy) = [HOBJECT n_receiver]',
            '$($heap_owners($heap_graph(S), HOBJECT n_receiver) >= 2)',
            '$calledclass_name(S, pargcall) = ($ptascii("NestedForeign234"))',
            '$call_descriptors_valid(S)',
            '$class_state_valid(S)',
            '$closure_state_valid(S)',
            '$heap_valid($heap_graph(S))',
            '~$closure_scope_row_valid(S, pclosurescope_child[.CREATION = eps])',
            '~$closure_scope_row_valid(S, pclosurescope_child[.LEXICAL = pclosurescope_child.CALLED])',
            '~$closure_scope_row_valid(S, pclosurescope_child[.CALLED = pclosurescope_child.LEXICAL])',
            '~$closure_scope_row_valid(S, pclosurescope_child[.RECEIVER = eps])',
            '~$closure_creator_valid(S, porigin_child, pclosurescope_child, pclosurecreation[.FUNCTION = porigin_child], pclosurecreator)',
            '~$closure_creator_valid(S, porigin_child, pclosurescope_child, pclosurecreation, pclosurecreator[.CALLSITE = eps])',
            '~$closure_creator_valid(S, porigin_child, pclosurescope_child, pclosurecreation[.RECEIVER = false], pclosurecreator)',
            '~$closure_creator_valid(S, porigin_child, pclosurescope_child, pclosurecreation, pclosurecreator[.SCOPE = CLOSURE_SCOPE pclosurescope_child])',
            '~$call_current_valid(S[.CURRENT = (pcallcontext[.LEXICAL_CLASS = eps])])',
            '~$call_current_valid(S[.CURRENT = (pcallcontext[.CALLED_CLASS = eps])])',
            '~$call_current_valid(S[.CURRENT = (pcallcontext[.RECEIVER = eps])])',
            'S_budget = $drive(S, 0)',
            'S_budget.COMPLETION = BUDGET',
            '$call_descriptors_valid(S_budget)',
            '$closure_state_valid(S_budget)',
            '$heap_valid($heap_graph(S_budget))',
            'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
            'S_done.COMPLETION = NORMAL',
            'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
            '$capture_outputs(S_done.EVENTS) = $ptascii("D|NestedForeign234:NestedRequested234:NestedForeign234:NestedForeign234|NestedForeign234:NestedRequested234:NestedForeign234:NestedForeign234|")',
            '~((HOBJECT n_parent) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_child) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_copy) <- S_done.ALLOCATIONS)',
            '~((HOBJECT n_receiver) <- S_done.ALLOCATIONS)',
            '$call_descriptors_valid(S_done)',
            '$class_state_valid(S_done)',
            '$closure_state_valid(S_done)',
            '$heap_valid($heap_graph(S_done))',
        ],
    },
}

CASES.update(NESTED_CASES)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--match', default='')
    args = parser.parse_args()
    protocol.MODULES.append(Path(__file__).with_suffix('.watsup'))
    selected = {name: case for name, case in CASES.items() if args.match in name}
    assert selected, 'no capture state selected'
    protocol.run(selected, extra_inputs=(Path(__file__), CATALOGUE))
