#!/usr/bin/env python3
"""Named-function static source, persistent-cell and active operand invariants."""
from pathlib import Path
import base64,json,os,subprocess,tempfile
import request_environment as q
import request_environment_state as rs
from recorded_worker import Worker
R=Path(__file__).resolve().parents[2]
SOURCES = {'static-suppressed-null-cache-restoration': 'PD9waHAKZnVuY3Rpb24gZigpe3N0YXRpYyAkeD1AJG1pc3Npbmc7ZWNobyAkeD09PW51bGw7fQpmKCk7ZigpO2VjaG8gJG91dHNpZGU7',
 'static-comma-order': 'PD9waHAgZnVuY3Rpb24gbigkeCl7ZWNobyAkeDtyZXR1cm4gJHg7fWZ1bmN0aW9uIGYoKXtzdGF0aWMgJGE9bigiQSIpLCRiPW4oIkIiKTtlY2hvICRhLCRiO31mKCk7ZigpOw==',
 'static-bare-cv-current-parameter': 'PD9waHAgZnVuY3Rpb24gZigkeCl7c3RhdGljICR4PSR4O2VjaG8gJHg7fWYoMik7Zig5KTs=',
 'static-saved-suppression-typed-initializer-error': 'PD9waHAKZnVuY3Rpb24gZyhpbnQgJHgpe2VjaG8gInVucmVhY2hlZCI7cmV0dXJuICR4O30KZnVuY3Rpb24gZigpe3N0YXRpYyAkYT0wO2VjaG8gKyskYTtzdGF0aWMgJGI9CiBnKFtdKTt9CmZ1bmN0aW9uIHJlbGF5KCl7cmV0dXJuIEBmKCk7fQpyZWxheSgpOw=='}
PREFIXES = {'stage0': 'dec $review_stage(pstate) : bool\n'
           'def $review_stage(S) = true -- if S.TODO = (STATIC_BIND porigin) :: ptask_tail*\n'
           'def $review_stage(S) = false -- otherwise\n'
           'dec $review_find(pstate, nat) : pstate\n'
           'def $review_find(S, n) = S -- if $review_stage(S)\n'
           'def $review_find(S, n) = $review_find(S_next[.COMPLETION = NORMAL], n_rest)\n'
           '  -- if ~$review_stage(S)\n'
           '  -- if $(n > 0)\n'
           '  -- if n_rest = $(n - 1)\n'
           '  -- if S_next = $drive_steps(S, 1)\n',
 'stage1': 'dec $review_stage(pstate) : bool\n'
           'def $review_stage(S) = true -- if S.TODO = (STATIC_BIND porigin) :: ptask_tail*\n'
           'def $review_stage(S) = false -- otherwise\n'
           'dec $review_find(pstate, nat) : pstate\n'
           'def $review_find(S, n) = S -- if $review_stage(S)\n'
           'def $review_find(S, n) = $review_find(S_next[.COMPLETION = NORMAL], n_rest)\n'
           '  -- if ~$review_stage(S)\n'
           '  -- if $(n > 0)\n'
           '  -- if n_rest = $(n - 1)\n'
           '  -- if S_next = $drive_steps(S, 1)\n'
           '\n'
           'dec $review_markers(pcodeexpr*, pcpath, ptbytes, int, int, bool) : pcodeexpr*\n'
           'def $review_markers(eps, pcpath, ptbytes, z_begin, z_bind, b) = eps\n'
           'def $review_markers((CODESTATIC pcpath ptbytes_old z_oldbegin z_oldbind b_old) :: '
           'pcodeexpr_tail*, pcpath, ptbytes, z_begin, z_bind, b) = (CODESTATIC pcpath ptbytes z_begin '
           'z_bind b) :: pcodeexpr_tail*\n'
           'def $review_markers((CODESTATIC pcpath_other ptbytes_old z_oldbegin z_oldbind b_old) :: '
           'pcodeexpr_tail*, pcpath, ptbytes, z_begin, z_bind, b) = (CODESTATIC pcpath_other ptbytes_old '
           'z_oldbegin z_oldbind b_old) :: $review_markers(pcodeexpr_tail*, pcpath, ptbytes, z_begin, '
           'z_bind, b) -- if pcpath_other =/= pcpath\n'
           'def $review_markers((CODEEXPR pcpath_other z_old b_old) :: pcodeexpr_tail*, pcpath, ptbytes, '
           'z_begin, z_bind, b) = (CODEEXPR pcpath_other z_old b_old) :: $review_markers(pcodeexpr_tail*, '
           'pcpath, ptbytes, z_begin, z_bind, b)\n'
           'def $review_markers((CODEARG pcpath_other) :: pcodeexpr_tail*, pcpath, ptbytes, z_begin, z_bind, '
           'b) = (CODEARG pcpath_other) :: $review_markers(pcodeexpr_tail*, pcpath, ptbytes, z_begin, '
           'z_bind, b)\n'
           'def $review_markers((CODEWRITE pcpath_other z_old) :: pcodeexpr_tail*, pcpath, ptbytes, z_begin, '
           'z_bind, b) = (CODEWRITE pcpath_other z_old) :: $review_markers(pcodeexpr_tail*, pcpath, ptbytes, '
           'z_begin, z_bind, b)\n'
           'def $review_markers((CODEEFFECT pcpath_other) :: pcodeexpr_tail*, pcpath, ptbytes, z_begin, '
           'z_bind, b) = (CODEEFFECT pcpath_other) :: $review_markers(pcodeexpr_tail*, pcpath, ptbytes, '
           'z_begin, z_bind, b)\n'
           'def $review_markers((CODECALL_INIT pcpath_other z_old) :: pcodeexpr_tail*, pcpath, ptbytes, '
           'z_begin, z_bind, b) = (CODECALL_INIT pcpath_other z_old) :: $review_markers(pcodeexpr_tail*, '
           'pcpath, ptbytes, z_begin, z_bind, b)\n'
           '\n',
 'stage2': 'dec $review_stage(pstate) : bool\n'
           'def $review_stage(S) = true -- if S.STATICS = [pstaticcell_a, pstaticcell_b]\n'
           'def $review_stage(S) = false -- otherwise\n'
           'dec $review_find(pstate, nat) : pstate\n'
           'def $review_find(S, n) = S -- if $review_stage(S)\n'
           'def $review_find(S, n) = $review_find(S_next[.COMPLETION = NORMAL], n_rest)\n'
           '  -- if ~$review_stage(S)\n'
           '  -- if $(n > 0)\n'
           '  -- if n_rest = $(n - 1)\n'
           '  -- if S_next = $drive_steps(S, 1)\n',
 'receive-stage': 'dec $review_receive_stage(pstate) : bool\n'
                  'def $review_receive_stage(S) = true\n'
                  '  -- if S.TODO = (TYPE_RECEIVE porigin 0) :: ptask*\n'
                  '  -- if S.CURRENT = (pcallcontext)\n'
                  '  -- if pcallcontext.NAME = [103]\n'
                  'def $review_receive_stage(S) = false -- otherwise\n'
                  'dec $review_receive_cut(pstate, nat, nat) : nat\n'
                  'def $review_receive_cut(S, n, n_left) = n -- if $review_receive_stage(S)\n'
                  'def $review_receive_cut(S, n, n_left) = $review_receive_cut($drive_steps(S[.COMPLETION = '
                  'NORMAL], 1), $(n + 1), n_rest)\n'
                  '  -- if ~$review_receive_stage(S)\n'
                  '  -- if $(n_left > 0)\n'
                  '  -- if n_rest = $(n_left - 1)\n'
                  'dec $review_receive_resume(pstate, nat) : pstate\n'
                  'def $review_receive_resume(S, n) = $drive(S[.COMPLETION = NORMAL], n) -- if S.COMPLETION '
                  '= BUDGET\n'
                  'def $review_receive_resume(S, n) = $drive(S, n) -- if S.COMPLETION =/= BUDGET\n'}
CASES = [{'id': 'control-bind',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': True,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S_changed = S',
             '$heap_valid($heap_graph(S_changed))',
             '$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = BUDGET'],
  'original_fixture_sha256': '9ad9fa56b74a9b170b83292dd5ff3cbe529ec5e302a233245004985697b82d75'},
 {'id': 'wrong-bind-origin',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': False,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S_changed = S[.TODO = (STATIC_BIND porigin_other) :: ptask_tail*]',
             '$heap_valid($heap_graph(S_changed))',
             '~$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"'],
  'original_fixture_sha256': '1a1b8467110ebc894c5f25243102bee121874f5e162233d1429af4ba04886521'},
 {'id': 'arbitrary-bind-owned-value',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': True,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S_changed = S[.RESULT = KNOWN (PINT 99)]',
             '$heap_valid($heap_graph(S_changed))',
             '$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = BUDGET'],
  'original_fixture_sha256': '96036e55652a761f2490184d31d085cd5e2bb429750dbd39478f678fc3be3d15'},
 {'id': 'control-initialized',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': True,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S_changed = S_post',
             '$heap_valid($heap_graph(S_changed))',
             '$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = BUDGET'],
  'original_fixture_sha256': 'd206ea6069119da3a8a14d78b4cea38fa3115ccc5b24a38d92f59667ed3ba13e'},
 {'id': 'wrong-entry-origin',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': False,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S_changed = S_post[.STATICS = [pstaticcell[.ORIGIN = porigin_other]]]',
             '$heap_valid($heap_graph(S_changed))',
             '~$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"'],
  'original_fixture_sha256': 'a6f29b119b1b8dfcda40ee6c8de20244506f579dcb828fa26ade847be5f3749c'},
 {'id': 'duplicate-entry',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': False,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S_changed = S_post[.STATICS = [pstaticcell, pstaticcell]]',
             '$heap_valid($heap_graph(S_changed))',
             '~$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"'],
  'original_fixture_sha256': '7192d136add0687ed9c09bc8eeb87df2c324ab2a7cebd3a167bd5e8927399293'},
 {'id': 'missing-reference-class',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': False,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S_changed = S_post[.REFCELLS = eps]',
             '$heap_valid($heap_graph(S_changed))',
             '~$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"'],
  'original_fixture_sha256': 'aac6a32994a2d5186f6dacd9f397894c7ccc5d7f8296296f515a039dda05313b'},
 {'id': 'undefined-persistent-cell',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': False,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S_changed = S_post[.STORE = $set_cell(S_post.STORE, n_cell, UNDEFINED)]',
             '$heap_valid($heap_graph(S_changed))',
             '~$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"'],
  'original_fixture_sha256': '75c4337693709f61fafa966ba3b4d346d8db1f4a75370a3b30b6b54c82b61303'},
 {'id': 'arbitrary-initialized-value',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': True,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S_changed = S_post[.STORE = $set_cell(S_post.STORE, n_cell, DEFINED (PINT 99))]',
             '$heap_valid($heap_graph(S_changed))',
             '$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = BUDGET'],
  'original_fixture_sha256': '7f4c9d2696c179d6415c2ce0858bb92b0757a27252a0cd2ebc131d25270c905e'},
 {'id': 'marker-control',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': True,
  'prefix': 'stage1',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S.CODE = [pcode]',
             'porigin = PORIGIN 0 pcpath',
             '$static_descriptor(S, porigin) = ((ptbytes, z_begin, z_bind, false))',
             'ptbytes_other = [121]',
             'S_changed = S',
             '$heap_valid($heap_graph(S_changed))',
             '$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = BUDGET'],
  'original_fixture_sha256': 'e9f9700db221a8bb7f7c5400e5a9637b0baa019dd2d04de0658103aceaf92c4c'},
 {'id': 'wrong-marker-name',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': False,
  'prefix': 'stage1',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S.CODE = [pcode]',
             'porigin = PORIGIN 0 pcpath',
             '$static_descriptor(S, porigin) = ((ptbytes, z_begin, z_bind, false))',
             'ptbytes_other = [121]',
             'S_changed = S[.CODE = [pcode[.EXPRESSIONS = $review_markers(pcode.EXPRESSIONS, pcpath, '
             'ptbytes_other, z_begin, z_bind, false)]]]',
             '$heap_valid($heap_graph(S_changed))',
             '~$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"'],
  'original_fixture_sha256': '2d19357709d748a17caa9df47b41b5e40517d5efaa1e5641eca3a6fc67cb8b37'},
 {'id': 'wrong-marker-begin-line',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': False,
  'prefix': 'stage1',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S.CODE = [pcode]',
             'porigin = PORIGIN 0 pcpath',
             '$static_descriptor(S, porigin) = ((ptbytes, z_begin, z_bind, false))',
             'ptbytes_other = [121]',
             'S_changed = S[.CODE = [pcode[.EXPRESSIONS = $review_markers(pcode.EXPRESSIONS, pcpath, '
             'ptbytes, $(z_begin + 100), z_bind, false)]]]',
             '$heap_valid($heap_graph(S_changed))',
             '~$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"'],
  'original_fixture_sha256': '5414b755827b24f79f34977271fb1846a70297d6420129edade58a7d71bda4f2'},
 {'id': 'wrong-marker-bind-line',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': False,
  'prefix': 'stage1',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S.CODE = [pcode]',
             'porigin = PORIGIN 0 pcpath',
             '$static_descriptor(S, porigin) = ((ptbytes, z_begin, z_bind, false))',
             'ptbytes_other = [121]',
             'S_changed = S[.CODE = [pcode[.EXPRESSIONS = $review_markers(pcode.EXPRESSIONS, pcpath, '
             'ptbytes, z_begin, $(z_bind + 100), false)]]]',
             '$heap_valid($heap_graph(S_changed))',
             '~$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"'],
  'original_fixture_sha256': 'a08838b909a930f68ea578663473df30799b091db75266cd418f0c7f4957dd8f'},
 {'id': 'wrong-marker-stored-mode',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': False,
  'prefix': 'stage1',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'S.CODE = [pcode]',
             'porigin = PORIGIN 0 pcpath',
             '$static_descriptor(S, porigin) = ((ptbytes, z_begin, z_bind, false))',
             'ptbytes_other = [121]',
             'S_changed = S[.CODE = [pcode[.EXPRESSIONS = $review_markers(pcode.EXPRESSIONS, pcpath, '
             'ptbytes, z_begin, z_bind, true)]]]',
             '$heap_valid($heap_graph(S_changed))',
             '~$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"'],
  'original_fixture_sha256': 'a4295bcdf9ee6d78cc05a78155d3a70537cd7acffc9c0c386a50a39010e1c6f3'},
 {'id': 'two-cell-control',
  'source': 'static-comma-order',
  'valid': True,
  'prefix': 'stage2',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.STATICS = [pstaticcell_a, pstaticcell_b]',
             'n_a = pstaticcell_a.CELL',
             'n_b = pstaticcell_b.CELL',
             'n_a =/= n_b',
             'n_name_b* = [98]',
             '$lookup(S.ENV, n_name_b*) = (n_b)',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_changed = S',
             '$heap_valid($heap_graph(S_changed))',
             '$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = BUDGET'],
  'original_fixture_sha256': '71e7e28b8a957e486d4cab7f1f0af408e5dd0dff5a7098cdf60bfd1c4afa3551'},
 {'id': 'arbitrary-distinct-cell-values',
  'source': 'static-comma-order',
  'valid': True,
  'prefix': 'stage2',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.STATICS = [pstaticcell_a, pstaticcell_b]',
             'n_a = pstaticcell_a.CELL',
             'n_b = pstaticcell_b.CELL',
             'n_a =/= n_b',
             'n_name_b* = [98]',
             '$lookup(S.ENV, n_name_b*) = (n_b)',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_changed = S[.STORE = $set_cell($set_cell(S.STORE, n_a, DEFINED (PINT 99)), n_b, DEFINED '
             '(PINT 99))]',
             '$heap_valid($heap_graph(S_changed))',
             '$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = BUDGET'],
  'original_fixture_sha256': '0e62ee358414fd378aeeada25930577c2fcc491e88508a61502e4d9423fb7679'},
 {'id': 'local-alias-retains-distinct-static-cells',
  'source': 'static-comma-order',
  'valid': True,
  'prefix': 'stage2',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.STATICS = [pstaticcell_a, pstaticcell_b]',
             'n_a = pstaticcell_a.CELL',
             'n_b = pstaticcell_b.CELL',
             'n_a =/= n_b',
             'n_name_b* = [98]',
             '$lookup(S.ENV, n_name_b*) = (n_b)',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_changed = $prune_allocations(S[.ENV = (BIND n_name_b* n_a) :: $unbind(S.ENV, n_name_b*)])',
             '$heap_valid($heap_graph(S_changed))',
             '$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = BUDGET'],
  'original_fixture_sha256': 'c65de3f43685f4ee6cfcb25b73293aeb72710a8cf578c42d443ef9e95c8bedce'},
 {'id': 'two-static-entries-share-cell',
  'source': 'static-comma-order',
  'valid': False,
  'prefix': 'stage2',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.STATICS = [pstaticcell_a, pstaticcell_b]',
             'n_a = pstaticcell_a.CELL',
             'n_b = pstaticcell_b.CELL',
             'n_a =/= n_b',
             'n_name_b* = [98]',
             '$lookup(S.ENV, n_name_b*) = (n_b)',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_changed = $prune_allocations(S[.ENV = (BIND n_name_b* n_a) :: $unbind(S.ENV, '
             'n_name_b*)][.STATICS = [pstaticcell_a, pstaticcell_b[.CELL = n_a]]])',
             '$heap_valid($heap_graph(S_changed))',
             '~$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"'],
  'original_fixture_sha256': 'f7bddd8d93931d1c71857a11f0c13b5ac094699b6f6404939cbfbb6079b6882a'},
 {'id': 'owning-result-control',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': True,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'n_other* = [111,117,116,115,105,100,101]',
             'S_changed = S',
             '$heap_valid($heap_graph(S_changed))',
             '$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = BUDGET'],
  'original_fixture_sha256': '8a3eec5238efbf627df9d598972572d0fad21ae13784d81a0e802c8ccc5bbd3f'},
 {'id': 'arbitrary-owning-result',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': True,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'n_other* = [111,117,116,115,105,100,101]',
             'S_changed = S[.RESULT = KNOWN (PINT 99)]',
             '$heap_valid($heap_graph(S_changed))',
             '$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = BUDGET'],
  'original_fixture_sha256': 'cdd12cecd2a7183268444a0869c4ed6264d264edc9ac79ff669b930e820f5454'},
 {'id': 'suppression-result-forged-deferred-name',
  'source': 'static-suppressed-null-cache-restoration',
  'valid': False,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = KNOWN PNULL',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED PNULL',
             'porigin_other = PORIGIN 0 eps',
             'n_other* = [111,117,116,115,105,100,101]',
             'S_changed = S[.RESULT = VARIABLE n_other* 2]',
             '$heap_valid($heap_graph(S_changed))',
             '~$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"'],
  'original_fixture_sha256': '1f9c0f2fcceb08bbc41f4328e54be32fc547ca8623ffc043b558b49c9db94646'},
 {'id': 'deferred-cv-control',
  'source': 'static-bare-cv-current-parameter',
  'valid': True,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = VARIABLE n_name* z_read',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED (PINT 2)',
             'porigin_other = PORIGIN 0 eps',
             'n_name* = [120]',
             'n_other* = [121]',
             '$lookup(S.ENV, n_name*) = (n_parameter)',
             'S_changed = S',
             '$heap_valid($heap_graph(S_changed))',
             '$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = BUDGET'],
  'original_fixture_sha256': '4bd778e6c6a402404527491e3d59352309cc82a45a1572d3cd94502d4fd84d7e'},
 {'id': 'arbitrary-deferred-cv-value',
  'source': 'static-bare-cv-current-parameter',
  'valid': True,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = VARIABLE n_name* z_read',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED (PINT 2)',
             'porigin_other = PORIGIN 0 eps',
             'n_name* = [120]',
             'n_other* = [121]',
             '$lookup(S.ENV, n_name*) = (n_parameter)',
             'S_changed = S[.STORE = $set_cell(S.STORE, n_parameter, DEFINED (PINT 99))]',
             '$heap_valid($heap_graph(S_changed))',
             '$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = BUDGET'],
  'original_fixture_sha256': '597202a0dc2102aaa07f85eb8e9946e8659755b5d86ee0eb4f41f310ed06353d'},
 {'id': 'wrong-deferred-cv-name',
  'source': 'static-bare-cv-current-parameter',
  'valid': False,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = VARIABLE n_name* z_read',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED (PINT 2)',
             'porigin_other = PORIGIN 0 eps',
             'n_name* = [120]',
             'n_other* = [121]',
             '$lookup(S.ENV, n_name*) = (n_parameter)',
             'S_changed = S[.RESULT = VARIABLE n_other* z_read]',
             '$heap_valid($heap_graph(S_changed))',
             '~$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"'],
  'original_fixture_sha256': 'e5a4dffe4a2806730797a5c0abe57712034ebfdc6320fdd93cc1ef52983e632f'},
 {'id': 'deferred-cv-forged-owning-result',
  'source': 'static-bare-cv-current-parameter',
  'valid': False,
  'prefix': 'stage0',
  'checks': ['S_initial = __INITIAL__',
             'S = $review_find(S_initial[.COMPLETION = NORMAL], 400)',
             'S.TODO = (STATIC_BIND porigin) :: ptask_tail*',
             'S.STATICS = eps',
             'S.RESULT = VARIABLE n_name* z_read',
             '$call_descriptors_valid(S)',
             '$heap_valid($heap_graph(S))',
             'S_post = $drive_steps(S, 1)',
             'S_post.STATICS = [pstaticcell]',
             'n_cell = pstaticcell.CELL',
             'S_post.STORE[n_cell] = DEFINED (PINT 2)',
             'porigin_other = PORIGIN 0 eps',
             'n_name* = [120]',
             'n_other* = [121]',
             '$lookup(S.ENV, n_name*) = (n_parameter)',
             'S_changed = S[.RESULT = KNOWN (PINT 99)]',
             '$heap_valid($heap_graph(S_changed))',
             '~$call_descriptors_valid(S_changed)',
             'S_zero = $drive(S_changed[.COMPLETION = NORMAL], 0)',
             'S_zero.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"'],
  'original_fixture_sha256': 'a071b5c95ce2845ba3e183d8bf5e082cd983b4addb581cfc589d8dda418f16e7'},
 {'id': 'typed-initializer-receive-resumption',
  'source': 'static-saved-suppression-typed-initializer-error',
  'valid': True,
  'prefix': 'receive-stage',
  'checks': ['S_initial = __INITIAL__',
             'S = S_initial[.COMPLETION = NORMAL]',
             'n = $review_receive_cut(S, 0, 512)',
             'S_typed = $drive(S, n)',
             '$review_receive_stage(S_typed)',
             '$call_descriptors_valid(S_typed)',
             'S_typed.REPORTING = 4437',
             'S_typed.FRAMES =/= eps',
             'S_typed.STATICS = [pstaticcell]',
             'S_typed.STORE[pstaticcell.CELL] = DEFINED (PINT 1)',
             'S_out = $drive(S, 10000)',
             'S_out.COMPLETION = THROWN "TypeError" n_message* 2',
             'S_out.STATICS = [pstaticcell]',
             'S_out.REPORTING = 30719',
             'S_out.SILENCES = eps',
             'S_out.FRAMES = eps',
             'n_before = $(n - 1)',
             'S_before = $drive(S, n_before)',
             '$heap_valid($heap_graph(S_before))',
             '$call_descriptors_valid(S_before)',
             '$review_receive_resume(S_before, 1) = $drive(S, $(n_before + 1))',
             '$review_receive_resume(S_before, 10000) = S_out',
             'n_at = $(n + 0)',
             'S_at = $drive(S, n_at)',
             '$heap_valid($heap_graph(S_at))',
             '$call_descriptors_valid(S_at)',
             '$review_receive_resume(S_at, 1) = $drive(S, $(n_at + 1))',
             '$review_receive_resume(S_at, 10000) = S_out',
             'n_after = $(n + 1)',
             'S_after = $drive(S, n_after)',
             '$heap_valid($heap_graph(S_after))',
             '$call_descriptors_valid(S_after)',
             '$review_receive_resume(S_after, 1) = $drive(S, $(n_after + 1))',
             '$review_receive_resume(S_after, 10000) = S_out'],
  'original_fixture_sha256': 'cefc18b5f82be8abffee09a3ade8b063a08b13502fd524603009f460ca4aeef7'}]
D=Path(tempfile.mkdtemp(prefix='function-statics-protocol-',dir=R/'.tools'))
(D/'producer.py').write_bytes(Path(__file__).read_bytes())
before=q.t.syntax_validation.implementation_fingerprint()
(D/'inputs.json').write_text(json.dumps({'fingerprint':before},indent=2));print(D,flush=True)
modules=[R/p for p in json.loads((R/'spec/semantics/modules.json').read_text())]
runner=R/'tests/semantics/_build/default/numeric_runner.exe'
f=a=None;initials={};originals=[];records=[]
try:
 f=Worker([str(q.t.PHP),'-n',*q.t.FLAGS,'-d','extension='+str(R/'.tools/php-file.so'),str(R/'frontend/worker.php')],D/'frontend-wire')
 a=Worker([str(R/'_build/default/adapter/main.exe'),str(R)],D/'adapter-wire')
 for name,source64 in SOURCES.items():
  directory=D/name;directory.mkdir();path=directory/'source.php';path.write_bytes(base64.b64decode(source64))
  payload=directory/'request.input';payload.write_bytes(q.packet(1700000000,125000,[b'LC_ALL=C',b'TZ=UTC',b'FIRST=one']))
  request={'env':[[q.b64(k),q.b64(v)] for k,v in [(b'LC_ALL',b'C'),(b'TZ',b'UTC'),(b'FIRST',b'one')]],'argv':[q.b64(os.fsencode(path))],'file':q.b64(os.fsencode(path)),'seconds':'1700000000','microseconds':125000,'variables':q.b64(b'EGPCS'),'jit':True,'cwd':q.b64(os.fsencode(directory))}
  parsed=f.request({'op':'parse','source':source64});assert parsed['accepted']
  checked=a.request({'op':'check','ast':parsed['ast'],'fixture':True});(directory/'checked.json').write_text(json.dumps(checked))
  originals.append({'id':name,'source_base64':source64,'context':str(path),'request':request});(D/'originals.json').write_text(json.dumps(originals,indent=2))
  initials[name]='$php_request_run('+checked['fixture']+', 0, '+json.dumps(q.b64(os.fsencode(path)))+', '+rs.request_fixture(request)+')'
finally:
 try:
  if f:f.close()
 finally:
  if a:a.close()
for case in CASES:
 checks=[s.replace('__INITIAL__',initials[case['source']]) for s in case['checks']]
 fixture=D/(case['id']+'.watsup');fixture.write_text(PREFIXES[case['prefix']]+'\ndec $main() : bool\ndef $main() = true\n'+''.join('  -- if '+s+'\n' for s in checks))
 command=[str(runner),*map(str,modules),str(fixture)];(D/(case['id']+'.command.json')).write_text(json.dumps(command))
 try:
  z=subprocess.run(command,capture_output=True,timeout=90)
 except subprocess.TimeoutExpired as e:
  (D/(case['id']+'.stdout')).write_bytes(e.stdout or b'');(D/(case['id']+'.stderr')).write_bytes(e.stderr or b'');(D/(case['id']+'.status.json')).write_text(json.dumps({'status':'timeout','seconds':90}));raise
 (D/(case['id']+'.stdout')).write_bytes(z.stdout);(D/(case['id']+'.stderr')).write_bytes(z.stderr);(D/(case['id']+'.status.json')).write_text(json.dumps({'status':'exit','exit_status':z.returncode}))
 record={'id':case['id'],'source':case['source'],'valid':case['valid'],'assertions':len(checks),'pass':z.returncode==0 and z.stdout.strip()==b'true' and not z.stderr};records.append(record);(D/'results.json').write_text(json.dumps(records,indent=2));print(record,flush=True)
assert before==q.t.syntax_validation.implementation_fingerprint()
report={'result':'pass' if all(r['pass'] for r in records) else 'fail','scope':'Twenty-six source/stage/persistent-cell controls: thirteen invalid states reject; twelve arbitrary-value/local-alias controls and one typed-initializer paused-receive regression accept. Checked-source protocol only; native source comparisons remain separate','fingerprint':before,'raw':str(D),'sources':len(originals),'cases':len(records),'assertions':sum(r['assertions'] for r in records),'records':records}
(D/'report.json').write_text(json.dumps(report,indent=2));target=R/'coverage/semantics/function-statics-protocol.json';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(json.dumps(report,indent=2));assert report['result']=='pass'
