"""Reached GLOBALS name demand, lookup replacement and nested RW abort."""
from error_handler_protocol import PREFIX

GUARDS = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
          '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))']
FINISH = ['S_done.COMPLETION = NORMAL', 'S_done.TODO = eps',
          'S_done.CURRENT = eps', 'S_done.FRAMES = eps', 'S_done.HELD = eps',
          'S_done.BORROWEDREAD = eps', 'S_done.TRACE = eps',
          'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
          '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))']

CASES = [
    ('global-rw-name-cv-rereads-real-caller',
     'missing-name-cv-rereads-caller-after-warning-for-rw',
     'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail* -- if pkeywrite.READ.PHASE = KEY_CV', [
        'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail*',
        'S.ORIGIN = (pkeywrite.READ.SITE)', 'S.REQUEST = eps',
        'pkeywrite.RW', 'pkeywrite.READ.GLOBAL', 'pkeywrite.READ.MODE = KEY_R',
        'pkeywrite.READ.PHASE = KEY_CV', 'pkeywrite.READ.LINE = 5',
        'pkeywrite.READ.INPUT = VARIABLE $ptascii("key269") 5',
        'pkeywrite.READ.NAME = $ptascii("key269")', 'pkeywrite.READ.VALUE = PNULL',
        'pkeywrite.READ.KEY = KSTRING eps', 'pkeywrite.READ.BASE = PNULL',
        'pkeywrite.READ.OWNERS = BASE_VALUE (KNOWN PNULL)', 'pkeywrite.PLACE = NOWHERE',
        '$key_write_valid(S, pkeywrite)', '$call_task_valid(S, KEY_WRITE_RESULT pkeywrite)',
        '$task_nodes(KEY_WRITE_RESULT pkeywrite) = eps',
        '~$key_write_valid(S, pkeywrite[.RW = false])',
        '~$key_write_valid(S, pkeywrite[.READ.GLOBAL = false])',
        '~$key_write_valid(S, pkeywrite[.READ.MODE = KEY_IS])',
        '~$key_write_valid(S, pkeywrite[.READ.SITE = PORIGIN 999 eps])',
        '~$key_write_valid(S, pkeywrite[.READ.LINE = 6])',
        '~$key_write_valid(S, pkeywrite[.READ.NAME = $ptascii("chosen269")])',
        '~$key_write_valid(S, pkeywrite[.READ.INPUT = KNOWN PNULL])',
        '~$key_write_valid(S, pkeywrite[.READ.OWNERS = BASE_VALUE (KNOWN (PINT 1))])',
        '$lookup(S.ENV, $ptascii("key269")) = (n_key)',
        'S.STORE[n_key] = DEFINED (PSTRING $ptascii("chosen269"))',
        '$lookup(S.ENV, $ptascii("chosen269")) = (n_chosen)',
        'S.STORE[n_chosen] = DEFINED (PINT 9)',
        '$lookup(S.ENV, eps) = eps', '$outputs(S.EVENTS) = $ptascii("U;")',
        *GUARDS, 'PhpStep: S ~> S_selected',
        'S_selected.TODO = ptask_tail*', 'S_selected.LOCATION = ROOT n_chosen',
        'S_selected.RESULT = KNOWN PNULL', 'S_selected.BASE = BASE_VALUE (KNOWN PNULL)',
        'S_selected.STORE[n_chosen] = DEFINED (PINT 9)', 'S_selected.ENV = S.ENV',
        'S_selected.STORE = S.STORE', 'S_selected.EVENTS = S.EVENTS',
        'S_done = $drive(S_selected, 1500)', *FINISH,
        'S_done.STORE[n_chosen] = DEFINED (PINT 13)', '$lookup(S_done.ENV, eps) = eps',
    ]),
    ('global-rw-converted-name-retains-fetch-and-operation-lines',
     'multiline-array-name-before-missing-global-and-delayed-rhs',
     'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail* -- if pkeywrite.READ.PHASE = KEY_MISSING', [
        'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail*',
        'S.ORIGIN = (pkeywrite.READ.SITE)', 'S.REQUEST = eps',
        'pkeywrite.RW', 'pkeywrite.READ.GLOBAL', 'pkeywrite.READ.MODE = KEY_R',
        'pkeywrite.READ.PHASE = KEY_MISSING', 'pkeywrite.READ.LINE = 6',
        'pkeywrite.READ.INPUT = VARIABLE $ptascii("key269") 6',
        'pkeywrite.READ.NAME = $ptascii("Array")',
        'pkeywrite.READ.VALUE = PSTRING $ptascii("Array")',
        'pkeywrite.READ.KEY = KSTRING eps', 'pkeywrite.READ.BASE = PNULL',
        'pkeywrite.READ.OWNERS = BASE_VALUE (KNOWN PNULL)', 'pkeywrite.PLACE = NOWHERE',
        'ptask_tail* = (ORIGIN_RETURN (porigin_assign)) :: (KEY_WRITE_FINISH pkeywriter) :: ptask_after*',
        'pkeywriter.SITE = porigin_assign', 'pkeywriter.TARGET = pkeywrite.READ.SITE',
        'pkeywriter.BASE = BASE_GLOBAL (VARIABLE $ptascii("key269") 6) 6',
        'pkeywriter.RHS = VARIABLE $ptascii("rhs269") 7', 'pkeywriter.TEMP = eps',
        'pkeywriter.TASK = COMPOUND_APPLY ADD pkeywriter.BASE false 7',
        '$key_writer_valid(S, pkeywriter, ptask_after*)', '$key_write_valid(S, pkeywrite)',
        '$call_task_valid(S, KEY_WRITE_RESULT pkeywrite)',
        '$task_nodes(KEY_WRITE_RESULT pkeywrite) = eps',
        '~$key_writer_valid(S, pkeywriter[.TASK = COMPOUND_APPLY ADD pkeywriter.BASE false 6], ptask_after*)',
        '~$key_writer_valid(S, pkeywriter[.BASE = BASE_GLOBAL (VARIABLE $ptascii("key269") 6) 7], ptask_after*)',
        '~$key_write_valid(S, pkeywrite[.READ.LINE = 7])',
        '~$key_write_valid(S, pkeywrite[.READ.SITE = porigin_assign])',
        '~$key_write_valid(S, pkeywrite[.READ.NAME = $ptascii("chosen269")])',
        '~$key_write_valid(S, pkeywrite[.READ.VALUE = PNULL])',
        '~$key_write_valid(S, pkeywrite[.READ.INPUT = KNOWN (PSTRING $ptascii("Array"))])',
        '~$key_write_valid(S, pkeywrite[.RW = false])',
        '~$key_write_valid(S, pkeywrite[.READ.GLOBAL = false])',
        '~$key_write_valid(S, pkeywrite[.READ.MODE = KEY_IS])',
        '~$key_write_valid(S, pkeywrite[.READ.KEY = KINT 0])',
        '$lookup(S.ENV, $ptascii("key269")) = (n_key)',
        'S.STORE[n_key] = DEFINED (PSTRING $ptascii("chosen269"))',
        '$lookup(S.ENV, $ptascii("rhs269")) = (n_rhs)', 'S.STORE[n_rhs] = DEFINED (PINT 17)',
        '$lookup(S.ENV, $ptascii("Array")) = (n_old)', 'S.STORE[n_old] = DEFINED (PINT 37)',
        '$lookup(S.ENV, $ptascii("stage269")) = (n_stage)', 'S.STORE[n_stage] = DEFINED (PINT 2)',
        '$outputs(S.EVENTS) = $ptascii("C:6;G:6;")', *GUARDS,
        'n_new = |S.STORE|', 'PhpStep: S ~> S_bound',
        'S_bound.TODO = ptask_tail*', 'S_bound.LOCATION = ROOT n_new',
        'S_bound.RESULT = KNOWN PNULL', 'S_bound.BASE = BASE_VALUE (KNOWN PNULL)',
        'S_bound.ENV = (BIND $ptascii("Array") n_new) :: $unbind(S.ENV, $ptascii("Array"))',
        'S_bound.STORE = S.STORE ++ [DEFINED PNULL]', 'S_bound.CELL = n_new',
        'S_bound.ALLOCATIONS = S.ALLOCATIONS ++ [HCELL n_new]',
        '~(n_new <- S_bound.REFCELLS)', 'n_new =/= n_old',
        '$heap_owners($heap_prune($heap_graph(S_bound)), HCELL n_new) = 1',
        '$heap_owners($heap_prune($heap_graph(S_bound)), HCELL n_old) = 0',
        'S_bound.STORE[n_rhs] = DEFINED (PINT 17)', 'S_bound.EVENTS = S.EVENTS',
        'S_done = $drive(S_bound, 1500)', *FINISH,
        '$lookup(S_done.ENV, $ptascii("Array")) = (n_new)',
        'S_done.STORE[n_new] = DEFINED (PINT 17)',
    ]),
    ('global-nested-rw-copy-aborts-without-owning-borrowed-place',
     'nested-global-rw-copy-abort-keeps-shared-typed-cell',
     'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail* -- if pkeywrite.READ.PHASE = KEY_FLOAT PRECISIONLOSS eps', [
        'S.TODO = (KEY_WRITE_RESULT pkeywrite) :: ptask_tail*',
        'S.ORIGIN = (pkeywrite.READ.SITE)', 'S.REQUEST = eps',
        'pkeywrite.RW', '~pkeywrite.READ.GLOBAL', 'pkeywrite.READ.MODE = KEY_R',
        'pkeywrite.READ.PHASE = KEY_FLOAT PRECISIONLOSS eps', 'pkeywrite.READ.LINE = 6',
        'pkeywrite.READ.INPUT = VARIABLE $ptascii("key269") 6',
        'pkeywrite.READ.VALUE = PFLOAT 4609434218613702656', 'pkeywrite.READ.KEY = KINT 1',
        'pkeywrite.READ.BASE = PARRAY n_array', 'pkeywrite.READ.OWNERS = BASE_VALUE (KNOWN PNULL)',
        '$lookup(S.ENV, $ptascii("box269")) = (n_box)', 'S.STORE[n_box] = DEFINED (PARRAY n_array)',
        '$lookup(S.ENV, $ptascii("held269")) = (n_held)', 'S.STORE[n_held] = DEFINED (PARRAY n_array)',
        'pkeywrite.PLACE = ROOT n_box', '$task_nodes(KEY_WRITE_RESULT pkeywrite) = [HARRAY n_array]',
        '$lookup(S.ENV, $ptascii("cell269")) = (n_cell)', 'n_cell <- S.REFCELLS',
        'S.ARRAYS[n_array].ITEMS = [ENTRY (KINT 1) (ALIAS n_cell)]',
        'S.STORE[n_cell] = DEFINED (PINT 17)', '~((HARRAY n_array) <- $pools_nodes(S.POOLS))',
        '$lookup(S.ENV, $ptascii("key269")) = (n_key)',
        'S.STORE[n_key] = DEFINED (PFLOAT 4620130267728707584)',
        '$key_write_valid(S, pkeywrite)', '$call_task_valid(S, KEY_WRITE_RESULT pkeywrite)',
        '~$key_write_valid(S, pkeywrite[.READ.LINE = 7])',
        '~$key_write_valid(S, pkeywrite[.READ.KEY = KINT 7])',
        '~$key_write_valid(S, pkeywrite[.RW = false])',
        '~$key_write_valid(S, pkeywrite[.READ.GLOBAL = true])',
        '~$key_write_valid(S, pkeywrite[.READ.MODE = KEY_IS])',
        '~$key_write_valid(S, pkeywrite[.READ.OWNERS = BASE_VALUE (KNOWN pkeywrite.READ.BASE)])',
        '~$key_write_valid(S, pkeywrite[.PLACE = NOWHERE])',
        '~$key_write_valid(S, pkeywrite[.READ.PHASE = KEY_FLOAT RANGEWARNING eps])',
        '$heap_owners($heap_prune($heap_graph(S)), HARRAY n_array) = 3',
        '$heap_owners($heap_prune($heap_graph(S)), HCELL n_cell) = 3',
        '~$key_write_single(S, pkeywrite)', '$outputs(S.EVENTS) = $ptascii("H:8192;")',
        *GUARDS, 'PhpStep: S ~> S_aborted',
        'S_aborted.TODO = ptask_tail*', 'S_aborted.LOCATION = NOWHERE',
        'S_aborted.RESULT = KNOWN PNULL', 'S_aborted.BASE = BASE_VALUE (KNOWN PNULL)',
        'S_aborted.ARRAYS = S.ARRAYS', 'S_aborted.STORE = S.STORE',
        '$heap_owners($heap_prune($heap_graph(S_aborted)), HARRAY n_array) = 2',
        '$heap_owners($heap_prune($heap_graph(S_aborted)), HCELL n_cell) = 3',
        'S_done = $drive(S_aborted, 1500)', *FINISH,
        'S_done.STORE[n_cell] = DEFINED (PINT 17)',
        '$entry_lookup(S_done.ARRAYS[n_array].ITEMS, KINT 1) = (ALIAS n_cell)',
    ]),
]
