"""Source-reached global fetch, throw cleanup and full-table ownership states."""
from error_handler_protocol import PREFIX

GUARDS = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
          '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))']
FINISH = [
    'S_done = $drive(S, 3000)', 'S_done.COMPLETION = NORMAL',
    'S_done.TODO = eps', 'S_done.CURRENT = eps', 'S_done.FRAMES = eps',
    'S_done.BORROWEDREAD = eps', 'S_done.HELD = eps', 'S_done.TRACE = eps',
    'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
    '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))',
    'S_done = $drive(S_initial[.COMPLETION = NORMAL], 3000)',
    'S_budget = $drive(S_initial[.COMPLETION = NORMAL], 7)',
    'S_budget.COMPLETION = BUDGET', '$heap_valid($heap_graph(S_budget))',
    'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
]

CASES = [
    ('captured-dynamic-name-resumes-null', 'computed-name-is-captured-before-handler-rebind',
     'S.TODO = (GLOBAL_READ_RESULT pglobalread) :: ptask_tail*', [
        'S.TODO = (GLOBAL_READ_RESULT pglobalread) :: ptask_tail*',
        'S.ORIGIN = (pglobalread.SITE)', 'S.CURRENT = eps', 'S.FRAMES = eps',
        'pglobalread.NAME = $ptascii("missing226")', 'pglobalread.LINE = 10',
        '$global_read_valid(S, pglobalread)', '$global_read_source(S, pglobalread)',
        '$call_task_valid(S, GLOBAL_READ_RESULT pglobalread)',
        '$origin_node(S.SOURCES, pglobalread.SITE) = (NExprArrayDimFetch expression_base expression_key metadata)',
        '$ppglobals_base(expression_base)',
        '$origin_child((pglobalread.SITE), [PCFIELD 1]) = (porigin_key)',
        '$compiled_read(S, porigin_key) = eps',
        '$error_variable_source(S, (pglobalread.SITE), [PCFIELD 1], $ptascii("key226"))',
        '$lookup(S.ENV, $ptascii("key226")) = (n_key)',
        'S.STORE[n_key] = DEFINED (PSTRING $ptascii("other226"))',
        '$lookup(S.ENV, $ptascii("missing226")) = (n_cell)',
        '$lookup(S.ENV, $ptascii("other226")) = (n_cell)',
        'n_cell <- S.REFCELLS', 'S.STORE[n_cell] = DEFINED (PINT 7)',
        '$heap_owners($heap_graph(S), HCELL n_cell) = 2',
        '$lookup(S.ENV, $ptascii("hits226")) = (n_hits)',
        'S.STORE[n_hits] = DEFINED (PINT 1)',
        '$lookup(S.ENV, $ptascii("result226")) = eps',
        '$global_read_plan(S) = eps', '$task_nodes(GLOBAL_READ_RESULT pglobalread) = eps',
        '~$global_read_valid(S, pglobalread[.LINE = 999])',
        '~$global_read_valid(S, pglobalread[.SITE = PORIGIN 999 eps])',
        '~$global_read_valid(S[.ORIGIN = eps], pglobalread)',
        'PhpStep: S ~> S_resumed', 'S_resumed.COMPLETION = NORMAL',
        'S_resumed.TODO = ptask_tail*', 'S_resumed.RESULT = KNOWN PNULL',
        'S_resumed.BASE = BASE_VALUE (KNOWN PNULL)',
        'S_resumed.STORE = S.STORE', 'S_resumed.ENV = S.ENV',
        'S_resumed.GLOBALTABLE = S.GLOBALTABLE', 'S_resumed.ORIGIN = S.ORIGIN',
        'S_resumed.ERRORHANDLER = S.ERRORHANDLER', 'S_resumed.EVENTS = S.EVENTS',
        '$heap_valid($heap_graph(S_resumed))', *GUARDS, *FINISH,
     ]),
    ('global-throw-discards-before-write', 'throw-skips-assignment-and-retires-selected-caller',
     'S.TODO = (THROW_SEARCH n_pending) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail* -- if S.CURRENT = eps -- if S.FRAMES = eps', [
        'S.TODO = (THROW_SEARCH n_pending) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail*',
        'S.CURRENT = eps', 'S.FRAMES = eps', 'S.BORROWEDREAD = eps',
        'perrorcall.RESUME = GLOBAL_READ_RESULT pglobalread',
        'pglobalread.NAME = $ptascii("missing226")',
        'perrorcall.MESSAGE = $ptascii("Undefined global variable $missing226")',
        'perrorcall.LEVEL = 2', 'perrorcall.LINE = pglobalread.LINE',
        '$global_read_valid(S, pglobalread)', '$error_entered_call_valid(S, perrorcall)',
        '$call_task_valid(S, ERROR_HANDLER_RESULT perrorcall)',
        '$origin_child((pglobalread.SITE), [PCFIELD 1]) = (porigin_key)',
        '$compiled_read(S, porigin_key) = (PSTRING $ptascii("missing226"))',
        '~$global_read_valid(S, pglobalread[.NAME = $ptascii("forged226")])',
        '~$global_read_valid(S, pglobalread[.LINE = 999])',
        '~$error_call_valid(S, perrorcall[.MESSAGE = $ptascii("forged226")])',
        '~$error_call_valid(S, perrorcall[.EVENT = WARNING $ptascii("missing226") pglobalread.LINE])',
        '$lookup(S.ENV, $ptascii("destination226")) = (n_destination)',
        'S.STORE[n_destination] = DEFINED (PINT 37)',
        '$lookup(S.ENV, $ptascii("missing226")) = (n_missing)',
        'S.STORE[n_missing] = DEFINED (PINT 41)',
        '$lookup(S.ENV, $ptascii("pending226")) = eps',
        '$lookup(S.ENV, $ptascii("older226")) = eps',
        '$throwable_field(S, n_pending, "previous") = POBJECT n_older',
        '$throwable_chain(S, n_pending, eps) = THROWCHAIN ([n_pending,n_older])',
        '$throwable_live(S, n_pending)', '$throwable_live(S, n_older)',
        '$return_discard(S, GLOBAL_READ_RESULT pglobalread) = S',
        'PhpStep: S ~> S_discarded', 'S_discarded.COMPLETION = NORMAL',
        'S_discarded.TODO = (THROW_SEARCH n_pending) :: ptask_tail*',
        'S_discarded.STORE = S.STORE', 'S_discarded.OBJECTS = S.OBJECTS',
        'S_discarded.STORE[n_destination] = DEFINED (PINT 37)',
        'S_discarded.ERRORHANDLER.CALLBACK = (perrorcall.CALLBACK)',
        '$throwable_chain(S_discarded, n_pending, eps) = THROWCHAIN ([n_pending,n_older])',
        '$heap_valid($heap_graph(S_discarded))', *GUARDS, *FINISH,
     ]),
    ('genuine-numeric-snapshot-has-real-cell-owners', 'snapshot-numeric-keys-cow-and-retained-reference-cell',
     'S.TODO = (WRITE_NAME n* z) :: ptask_tail* -- if n* = $ptascii("snapshot226")', [
        'S.TODO = (WRITE_NAME n* z) :: ptask_tail*', 'n* = $ptascii("snapshot226")',
        'S.REQUEST = (Q)', '$request_valid(Q)', 'S.GLOBALTABLE = eps',
        'S.CURRENT = eps', 'S.FRAMES = eps', 'S.RESULT = KNOWN (PARRAY n_snapshot)',
        '$lookup(S.ENV, [49,50]) = (n_shared)',
        '$lookup(S.ENV, $ptascii("r226")) = (n_shared)',
        'S.STORE[n_shared] = DEFINED (PINT 2)', 'n_shared <- S.REFCELLS',
        '$entry_lookup(S.ARRAYS[n_snapshot].ITEMS, KINT 12) = (ALIAS n_shared)',
        '$entry_lookup(S.ARRAYS[n_snapshot].ITEMS, KSTRING ([48,49,50])) = (DIRECT (PINT 3))',
        '$entry_lookup(S.ARRAYS[n_snapshot].ITEMS, KSTRING ([49,50])) = eps',
        '$heap_owners($heap_graph(S), HCELL n_shared) = 4',
        '$lookup(S.ENV, $ptascii("single226")) = (n_single)',
        'n_single <- S.REFCELLS', 'S.STORE[n_single] = DEFINED (PINT 5)',
        '$heap_owners($heap_graph(S), HCELL n_single) = 1',
        '$merge_item(S, ALIAS n_single) = DIRECT (PINT 5)',
        '$entry_lookup(S.ARRAYS[n_snapshot].ITEMS, KSTRING $ptascii("single226")) = (DIRECT (PINT 5))',
        '$lookup(S.ENV, $ptascii("alias226")) = eps',
        '$lookup(S.ENV, $ptascii("snapshot226")) = eps',
        '$entry_lookup(S.ARRAYS[n_snapshot].ITEMS, KSTRING $ptascii("snapshot226")) = eps',
        '$entry_lookup(S.ARRAYS[n_snapshot].ITEMS, KSTRING $ptascii("copy226")) = eps',
        '$lookup(S.ENV, $ptascii("n226")) = (n_array_cell)',
        'S.STORE[n_array_cell] = DEFINED (PARRAY n_original)',
        '$entry_lookup(S.ARRAYS[n_snapshot].ITEMS, KSTRING $ptascii("n226")) = (DIRECT (PARRAY n_original))',
        '$heap_owners($heap_graph(S), HARRAY n_original) = 2',
        '$entry_lookup(S.ARRAYS[n_snapshot].ITEMS, KSTRING $ptascii("argv")) = (DIRECT (PARRAY n_argv))',
        '$entry_lookup(S.ARRAYS[n_snapshot].ITEMS, KSTRING $ptascii("_SERVER")) = (DIRECT (PARRAY n_server))',
        '(HARRAY n_argv) <- S.ALLOCATIONS', '(HARRAY n_server) <- S.ALLOCATIONS',
        '$global_table_view($global_table_view(S)) = S',
        *GUARDS, *FINISH,
        'S_done.REQUEST = S.REQUEST', 'S_done.HTTPROOTS = S.HTTPROOTS',
        '$lookup(S_done.ENV, [49,50]) = eps', '$lookup(S_done.ENV, $ptascii("r226")) = eps',
        '$lookup(S_done.ENV, $ptascii("snapshot226")) = eps',
        'S_done.STORE[n_shared] = DEFINED (PINT 17)',
        '$heap_owners($heap_graph(S_done), HCELL n_shared) = 1',
        '$lookup(S_done.ENV, $ptascii("copy226")) = (n_copy_cell)',
        'S_done.STORE[n_copy_cell] = DEFINED (PARRAY n_copy)',
        '$entry_lookup(S_done.ARRAYS[n_copy].ITEMS, KINT 12) = (ALIAS n_shared)',
        '$entry_lookup(S_done.ARRAYS[n_copy].ITEMS, KSTRING $ptascii("single226")) = (DIRECT (PINT 5))',
     ]),
]
