#!/usr/bin/env python3
"""Live callable member reads, held class branches and authentic API receivers."""
from pathlib import Path
import json

import closure_call_protocol as protocol

CATALOGUE = Path(__file__).with_name('keyword_compound_callables_cases.json')
SOURCES = {row['id']: row['source'] for row in json.loads(CATALOGUE.read_text())}
VALID = ['$call_descriptors_valid(S)', '$class_state_valid(S)',
         '$closure_state_valid(S)', '$heap_valid($heap_graph(S))']
AFTER = ['$call_descriptors_valid(S_done)', '$class_state_valid(S_done)',
         '$closure_state_valid(S_done)', '$heap_valid($heap_graph(S_done))']

CASES = {
    'keyword-method-alias-live-after-warning': {
        'source': SOURCES['method-alias'],
        'stage': 'S.TODO = (API_CALLABLE_RESULT papiquery 0) :: ptask_tail*',
        'checks': [
            'papiquery.SOURCE = TYPE_RECEIVE porigin_receive n_parameter',
            'papiquery.INPUT = PSTRING $ptascii("self")',
            'papiquery.VALUE = PARRAY n_array',
            'papiquery.METHOD = ALIAS n_method',
            'papiquery.ORIGINAL = $ptascii("missing")',
            'papiquery.PREFIX = 0 /\\ papiquery.WIDTH = 0',
            'papiquery.OUTER = eps',
            'papiquery.SCOPE = (papiquery.CLASS.REQUESTED)',
            '~papiquery.CLASS.STRICT',
            'S.STORE[n_method] = DEFINED (PSTRING $ptascii("ok"))',
            '$entry_value(S, papiquery.METHOD) = PSTRING $ptascii("ok")',
            '$api_query_valid(S, papiquery, 0)',
            '$task_nodes(API_CALLABLE_RESULT papiquery 0) = eps',
            '$typed_callable(S, papiquery.VALUE) = (true)',
            '$function_at($all_functions(S), porigin_receive) = (pfunction)',
            '$typed_conversion_at(S, pfunction.SIGNATURE.PARAMETERS[n_parameter].TYPE, papiquery.VALUE, false) = TYPEDEPENDENT "deprecated callable admission continuation"',
            *VALID,
            '~$api_query_valid(S, papiquery[.LINE = $(papiquery.LINE + 100)], 0)',
            '~$api_query_valid(S, papiquery[.SCOPE = eps], 0)',
            '~$api_query_valid(S, papiquery[.CLASS = papiquery.CLASS[.STRICT = true]], 0)',
            '~$api_query_valid(S, papiquery[.SOURCE = TYPE_RECEIVE porigin_receive $(n_parameter + 1)], 0)',
            '~$api_query_valid(S, papiquery[.METHOD = DIRECT (PSTRING $ptascii("ok"))], 0)',
            '~$api_query_valid(S, papiquery, 1)',
            'S_bad = $drive(S[.TODO = [API_CALLABLE_RESULT papiquery[.LINE = $(papiquery.LINE + 100)] 0]], 5)',
            'S_bad.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"',
            'S_budget = $drive_steps(S, 1)',
            'S_budget.COMPLETION = BUDGET',
            'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
            'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT ($api_keyword_message(PSTRING $ptascii("self"))), OUTPUT $ptascii(":"), OUTPUT $ptascii("missing"), OUTPUT $ptascii("|"), OUTPUT $ptascii("admitted:"), OUTPUT $ptascii("ok")]',
            'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
            'S_done.ERRORHANDLER.CALLBACK = eps /\\ S_done.ERRORHANDLERS = eps',
            '~((HARRAY n_array) <- S_done.ALLOCATIONS)',
            '~((HCELL n_method) <- S_done.ALLOCATIONS)',
            *AFTER,
        ],
    },
    'keyword-class-branch-held-before-registration': {
        'source': SOURCES['class-alias-registration'],
        'stage': 'S.TODO = (API_CALLABLE_RESULT papiquery 0) :: ptask_tail*',
        'checks': [
            'papiquery.SOURCE = CONFIG_INVOKE pconfigcall',
            'papiquery.INPUT = PSTRING $ptascii("self")',
            'papiquery.VALUE = PARRAY n_array',
            '$entry_lookup(S.ARRAYS[n_array].ITEMS, KINT 0) = (ALIAS n_class)',
            'S.STORE[n_class] = DEFINED (PSTRING $ptascii("Other"))',
            '$class_at(S.CLASSES, papiquery.CLASS.REQUESTED) = (pclassdesc)',
            'pclassdesc.NAME = $ptascii("Owner")',
            'papiquery.METHOD = DIRECT (PSTRING $ptascii("handle"))',
            '$api_query_valid(S, papiquery, 0)',
            '$error_handler_resolution(S, papiquery.VALUE) = HANDLERINVALID ($ptascii("class Other does not have a method ") ++ [34] ++ $ptascii("handle") ++ [34])',
            *VALID,
            '~$api_query_valid(S, papiquery[.INPUT = PSTRING $ptascii("Other")], 0)',
            '~$api_query_valid(S, papiquery[.SOURCE = CONFIG_INVOKE pconfigcall[.LINE = $(pconfigcall.LINE + 100)]], 0)',
            'PhpStep: S ~> S_one',
            'S_one.COMPLETION = NORMAL',
            'S_one.ERRORHANDLER.CALLBACK = (PARRAY n_array)',
            '$error_handler_retained(S_one, PARRAY n_array)',
            '$call_descriptors_valid(S_one)',
            'S_done = $drive(S_one, 3000)',
            'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT $ptascii("deprecation|"), OUTPUT $ptascii("registered:"), OUTPUT $ptascii("Other"), OUTPUT $ptascii("|"), OUTPUT ($ptascii("Invalid callback Other::handle, class Other does not have a method ") ++ [34] ++ $ptascii("handle") ++ [34])]',
            *AFTER,
        ],
    },
    'compound-prefix-held-leaf-live': {
        'source': '''<?php
class Base { public static function ok() {} public static function xx() {} }
class Child extends Base { public function test() {
 $method='Base::xx'; $cb=['Child', &$method];
 set_error_handler(function($n,$s) use (&$method) {echo 'D|';$method='Nope::ok';return true;});
 $take=function(callable $cb) {echo 'A|',$cb[1];};$take($cb);restore_error_handler();
} }
(new Child)->test();
''',
        'stage': 'S.TODO = (API_CALLABLE_RESULT papiquery 1) :: ptask_tail*',
        'checks': [
            'papiquery.VALUE = PARRAY n_array',
            'papiquery.METHOD = ALIAS n_method',
            'papiquery.ORIGINAL = $ptascii("Base::xx")',
            'papiquery.PREFIX = 6 /\\ papiquery.WIDTH = 2',
            'papiquery.OUTER = (papiclass_outer)',
            '$class_at(S.CLASSES, papiclass_outer.REQUESTED) = (pclassdesc_outer)',
            'pclassdesc_outer.NAME = $ptascii("Child")',
            '$class_at(S.CLASSES, papiquery.CLASS.REQUESTED) = (pclassdesc_inner)',
            'pclassdesc_inner.NAME = $ptascii("Base")',
            'S.STORE[n_method] = DEFINED (PSTRING $ptascii("Nope::ok"))',
            '$api_query_valid(S, papiquery, 1)',
            *VALID,
            '~$api_query_valid(S, papiquery[.PREFIX = 4], 1)',
            '~$api_query_valid(S, papiquery[.WIDTH = 1], 1)',
            '~$api_query_valid(S, papiquery[.CLASS = papiclass_outer], 1)',
            'S_done = $drive(S, 3000)',
            'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT $ptascii("D|"), OUTPUT $ptascii("A|"), OUTPUT $ptascii("Nope::ok")]',
            '~((HARRAY n_array) <- S_done.ALLOCATIONS)',
            '~((HCELL n_method) <- S_done.ALLOCATIONS)',
            *AFTER,
        ],
    },
    'foreign-this-entered-api-authentication': {
        'source': '''<?php
class Child { public function run($n,$s,$f,$l) {echo func_num_args(),':',($this instanceof Foreign)?'Foreign':'wrong',':',self::class,':',static::class;return true;}public function other($n,$s,$f,$l) {return true;} }
class Foreign {public function test() {error_reporting(0);set_error_handler(function($n,$s){return true;});set_error_handler(['Child','self::run']);echo $missing;restore_error_handler();restore_error_handler();} }
(new Foreign)->test();
''',
        'stage': ('S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* '
                  '-- if S.CURRENT = (pcallcontext) '
                  '-- if pcallcontext.TARGET = API_METHOD_TARGET papiquery porigin_run ptbytes_method b_static'),
        'checks': [
            '~b_static',
            'ptbytes_method = $ptascii("run")',
            'papiquery.METHOD = DIRECT (PSTRING $ptascii("self::run"))',
            'papiquery.PREFIX = 6 /\\ papiquery.WIDTH = 3',
            'papiquery.CLASS.RECEIVER = (n_foreign)',
            'papiquery.CLASS.CALLED = porigin_foreign',
            'papiquery.CLASS.REQUESTED = porigin_child',
            'papiquery.SCOPE = (porigin_foreign)',
            'papiquery.THIS = (n_foreign)',
            'S.OBJECTS[n_foreign] = INSTANCE porigin_foreign',
            'pcallcontext.LEXICAL_CLASS = (porigin_child)',
            'pcallcontext.CALLED_CLASS = (porigin_foreign)',
            'pcallcontext.RECEIVER = (n_foreign)',
            'pcallcontext.ARGC = 4',
            '$api_carrier_valid(S, papiquery, porigin_run, ptbytes_method, false)',
            '$target_nodes(pcallcontext.TARGET) = [HOBJECT n_foreign]',
            '$class_method_origin(S.CLASSES, porigin_run) = (pmethoddesc)',
            '~$scoped_receiver_valid(S, porigin_child, pmethoddesc, (n_foreign))',
            '$target_function(S, SCOPED_TARGET porigin_child porigin_run porigin_foreign (n_foreign) (KNOWN (PSTRING $ptascii("Child")))) = eps',
            'S.FRAMES = pframe_emitter :: pframe_tail*',
            'pframe_emitter.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_emitter*',
            'perrorcall.TARGET = (pcallcontext.TARGET)',
            'S_emitter = S[.CURRENT = pframe_emitter.CONTEXT][.FRAMES = pframe_tail*][.ORIGIN = pframe_emitter.ORIGIN][.TODO = pframe_emitter.TODO][.BORROWEDREAD = pframe_emitter.BORROWEDREAD]',
            '$handler_emitter_valid(S_emitter, pcallcontext.TARGET)',
            '$error_entered_call_valid(S_emitter, perrorcall)',
            '$error_context_valid(S, pcallcontext)',
            '$arginfo_values(S, pcallcontext) = $error_handler_values(S, perrorcall)',
            'S.ERRORHANDLER.CALLBACK = eps',
            *VALID,
            '$effective_method(S, porigin_child, $ptascii("other"), |S.CLASSES|) = (pmethoddesc_other)',
            '~$api_carrier_valid(S, papiquery, pmethoddesc_other.FUNCTION.ORIGIN, $ptascii("other"), false)',
            '~$api_carrier_valid(S, papiquery, porigin_run, ptbytes_method, true)',
            '~$handler_emitter_valid(S_emitter, API_METHOD_TARGET papiquery[.SCOPE = (porigin_child)] porigin_run ptbytes_method false)',
            '~$error_entered_call_valid(S_emitter, perrorcall[.TARGET = (API_METHOD_TARGET papiquery porigin_run ptbytes_method true)])',
            '~$error_context_valid(S, pcallcontext[.CALLED_CLASS = (porigin_child)])',
            '~$error_context_valid(S, pcallcontext[.ARGC = 0])',
            '~$call_descriptors_valid(S[.CURRENT = (pcallcontext[.TARGET = API_METHOD_TARGET papiquery pmethoddesc_other.FUNCTION.ORIGIN $ptascii("other") false])])',
            'S_done = $drive(S, 3000)',
            'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT $ptascii("4"), OUTPUT $ptascii(":"), OUTPUT $ptascii("Foreign"), OUTPUT $ptascii(":"), OUTPUT $ptascii("Child"), OUTPUT $ptascii(":"), OUTPUT $ptascii("Foreign"), OUTPUT eps]',
            'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
            'S_done.ERRORHANDLER.CALLBACK = eps /\\ S_done.ERRORHANDLERS = eps',
            '~((HOBJECT n_foreign) <- S_done.ALLOCATIONS)',
            *AFTER,
        ],
    },
}

CASES['active-handler-original-receiving-table'] = {
    'source': SOURCES['byref-string-prefix'],
    'stage': 'S.CURRENT = (pcallcontext_handler) -- if pcallcontext_handler.NAME = $ptascii("warn") -- if S.FRAMES = pframe_receive :: pframe_tail* -- if pframe_receive.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_receive* -- if perrorcall.RESUME = API_CALLABLE_RESULT papiquery 1 -- if papiquery.SOURCE = TYPE_RECEIVE porigin_receive n_parameter -- if papiquery.METHOD = ALIAS n_formal -- if S.STORE[n_formal] = DEFINED (PSTRING $ptascii("Nope::ok"))',
    'checks': [
        'pframe_receive.CONTEXT = (pcallcontext_receive)',
        'pcallcontext_receive.FUNCTION = porigin_receive',
        'pframe_receive.LOCALS = (psymboltable_receive)',
        '$lookup(psymboltable_receive.ENV, $ptascii("value")) = (n_formal)',
        '$lookup(S.ENV, $ptascii("value")) = eps',
        '$lookup(S.ENV, $ptascii("n")) = (n_warning)',
        'papiquery.ORIGINAL = $ptascii("self::xx")',
        'papiquery.INPUT = PSTRING $ptascii("self")',
        'papiquery.PREFIX = 6 /\\ papiquery.WIDTH = 2',
        'papiquery.CLASS.RECEIVER = eps',
        '$class_at(S.CLASSES, papiquery.CLASS.REQUESTED) = (pclassdesc)',
        'pclassdesc.NAME = $ptascii("A")',
        'S_receive = $api_saved_frame_scope(S, pframe_receive, pframe_tail*)',
        'S_receive.ENV = psymboltable_receive.ENV',
        'S_receive.FRAMES = pframe_tail*',
        '$api_query_valid(S_receive, papiquery, 1)',
        '~$api_query_valid(S, papiquery, 1)',
        '$call_descriptors_valid(S)',
        '$class_state_valid(S)',
        '$closure_state_valid(S)',
        '$heap_valid($heap_graph(S))',
        '~$api_query_valid(S_receive, papiquery[.METHOD = ALIAS n_warning], 1)',
        '~$api_query_valid(S_receive, papiquery[.WIDTH = 1], 1)',
        '~$api_query_valid(S_receive, papiquery[.LINE = $(papiquery.LINE + 1)], 1)',
        'S_budget = $drive_steps(S, 0)',
        'S_budget.COMPLETION = BUDGET',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.EVENTS = [OUTPUT ($api_keyword_message(PSTRING $ptascii("self"))), OUTPUT $ptascii("|"), OUTPUT $ptascii("admitted:"), OUTPUT $ptascii("Nope::ok")]',
        'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
        '$lookup(S_done.ENV, $ptascii("cb")) = (n_cb)',
        'S_done.STORE[n_cb] = DEFINED (PSTRING $ptascii("Nope::ok"))',
        '$call_descriptors_valid(S_done)',
        '$class_state_valid(S_done)',
        '$closure_state_valid(S_done)',
        '$heap_valid($heap_graph(S_done))',
    ],
}

CASES['replaced-reference-array-retained-original'] = {
    'source': SOURCES['byref-array-replaced'],
    'stage': 'S.TODO = (API_CALLABLE_RESULT papiquery 0) :: ptask_tail*',
    'checks': [
        'papiquery.SOURCE = TYPE_RECEIVE porigin_receive n_parameter',
        'papiquery.VALUE = PARRAY n_original',
        'papiquery.METHOD = DIRECT (PSTRING $ptascii("run"))',
        'papiquery.INPUT = PSTRING $ptascii("self")',
        '$lookup(S.ENV, $ptascii("value")) = (n_formal)',
        'S.STORE[n_formal] = DEFINED PNULL',
        'S.GLOBALTABLE = (psymboltable_global)',
        '$lookup(psymboltable_global.ENV, $ptascii("keep")) = (n_keep)',
        'S.STORE[n_keep] = DEFINED papiquery.VALUE',
        '(HARRAY n_original) <- S.ALLOCATIONS',
        '$api_query_valid(S, papiquery, 0)',
        '$call_descriptors_valid(S)',
        '$class_state_valid(S)',
        '$closure_state_valid(S)',
        '$heap_valid($heap_graph(S))',
        '~$api_query_valid(S, papiquery[.VALUE = PNULL], 0)',
        '~$api_query_valid(S, papiquery[.METHOD = DIRECT (PSTRING $ptascii("other"))], 0)',
        '~$api_query_valid(S[.ALLOCATIONS = $call_remove_owner(S.ALLOCATIONS, HARRAY n_original)], papiquery, 0)',
        '~$api_query_valid(S[.ALLOCATIONS = $call_remove_owner(S.ALLOCATIONS, HCELL n_formal)], papiquery, 0)',
        '~$api_query_valid(S[.REFCELLS = eps], papiquery, 0)',
        '~$api_query_valid(S[.STORE = $set_cell(S.STORE, n_formal, UNDEFINED)], papiquery, 0)',
        'n_outside = |S.ARRAYS|',
        '~$api_query_valid(S, papiquery[.VALUE = PARRAY n_outside], 0)',
        '~$api_query_valid(S, papiquery[.SOURCE = TYPE_RECEIVE porigin_receive $(n_parameter + 1)], 0)',
        'S_budget = $drive_steps(S, 0)',
        'S_budget.COMPLETION = BUDGET',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.EVENTS = [OUTPUT $ptascii("deprecation|"), OUTPUT $ptascii("null-body|"), OUTPUT $ptascii("null-caller")]',
        'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
        '$lookup(S_done.ENV, $ptascii("cb")) = (n_cb)',
        'S_done.STORE[n_cb] = DEFINED PNULL',
        '$call_descriptors_valid(S_done)',
        '$class_state_valid(S_done)',
        '$closure_state_valid(S_done)',
        '$heap_valid($heap_graph(S_done))',
    ],
}

CASES['static-parent-carrier-called-scope-and-owners'] = {
    'source': SOURCES['static-keyword-ownership'],
    'stage': 'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* -- if S.CURRENT = (pcallcontext) -- if pcallcontext.TARGET = API_METHOD_TARGET papiquery porigin_run ptbytes_method true -- if papiquery.INPUT = PSTRING $ptascii("parent")',
    'checks': [
        'ptbytes_method = $ptascii("run")',
        'papiquery.CLASS.RECEIVER = (n_child)',
        'papiquery.CLASS.REQUESTED = porigin_base',
        'papiquery.CLASS.CALLED = porigin_child',
        'papiquery.CLASS.STRICT',
        'S.OBJECTS[n_child] = INSTANCE porigin_child',
        '$class_at(S.CLASSES, porigin_base) = (pclassdesc_base)',
        'pclassdesc_base.NAME = $ptascii("Base")',
        '$class_at(S.CLASSES, porigin_child) = (pclassdesc_child)',
        'pclassdesc_child.NAME = $ptascii("Child")',
        'pcallcontext.RECEIVER = eps',
        'pcallcontext.LEXICAL_CLASS = (porigin_base)',
        'pcallcontext.CALLED_CLASS = (porigin_child)',
        'pcallcontext.ARGC = 4',
        '$target_nodes(pcallcontext.TARGET) = eps',
        '$api_carrier_valid(S, papiquery, porigin_run, ptbytes_method, true)',
        '~$api_carrier_valid(S, papiquery, porigin_run, ptbytes_method, false)',
        '$target_function(S, API_METHOD_TARGET papiquery porigin_run ptbytes_method false) = eps',
        '$call_descriptors_valid(S)',
        '$class_state_valid(S)',
        '$closure_state_valid(S)',
        '$heap_valid($heap_graph(S))',
        '~$call_descriptors_valid(S[.CURRENT = (pcallcontext[.TARGET = API_METHOD_TARGET papiquery porigin_run ptbytes_method false])])',
        'S_done = $drive(S, 3000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
        'S_done.ERRORHANDLER.CALLBACK = eps /\\ S_done.ERRORHANDLERS = eps',
        '~((HOBJECT n_child) <- S_done.ALLOCATIONS)',
        '$call_descriptors_valid(S_done)',
        '$class_state_valid(S_done)',
        '$closure_state_valid(S_done)',
        '$heap_valid($heap_graph(S_done))',
    ],
}

CASES['compound-warning-throw-restores-and-retires'] = {
    'source': SOURCES['compound-throw'],
    'stage': ('S.TODO = (THROW_SEARCH n_exception) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail* '
              '-- if perrorcall.RESUME = API_CALLABLE_RESULT papiquery 1'),
    'checks': [
        'papiquery.SOURCE = CONFIG_INVOKE pconfigcall',
        'pconfigcall.KIND = INTRINSIC_SET_ERROR_HANDLER',
        'papiquery.VALUE = PARRAY n_array',
        'papiquery.METHOD = DIRECT (PSTRING $ptascii("Base::ok"))',
        'papiquery.OUTER = (papiclass_outer)',
        'papiquery.PREFIX = 6 /\\ papiquery.WIDTH = 2',
        'perrorcall.CALLBACK = POBJECT n_handler',
        'S.ERRORHANDLER.CALLBACK = eps',
        '$api_query_valid(S, papiquery, 1)',
        '$error_entered_call_valid(S, perrorcall)',
        '$throwable_live(S, n_exception)',
        *VALID,
        'S_budget = $drive_steps(S, 0)',
        'S_budget.COMPLETION = BUDGET',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.EVENTS = [OUTPUT $ptascii("deprecation|"), OUTPUT $ptascii("stop")]',
        'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
        'S_done.ERRORHANDLER.CALLBACK = eps /\\ S_done.ERRORHANDLERS = eps',
        '(HARRAY n_array) <- $pools_nodes(S_done.POOLS)',
        '$heap_owners($heap_graph(S_done), HARRAY n_array) = 1',
        '~((HOBJECT n_handler) <- S_done.ALLOCATIONS)',
        *AFTER,
    ],
}

CASES['named-default-hole-cannot-enter-supplied-api-stage'] = {
    'source': SOURCES['default-callable-hole-control'],
    'stage': 'S.TODO = [TYPE_RECEIVE porigin_receive 1]',
    'checks': [
        'S.CURRENT = (pcallcontext)',
        'pcallcontext.FUNCTION = porigin_receive',
        'pcallcontext.ARGC = 3 /\\ pcallcontext.HOLES = [0, 1]',
        '$call_holes_valid(S, pcallcontext)',
        '$fixed_parameter_defaulted(S, 1)',
        '~$fixed_parameter_supplied(S, 1)',
        '$fixed_parameter_supplied(S, 2)',
        '~$call_holes_valid(S, pcallcontext[.HOLES = eps])',
        '~$fixed_parameter_supplied(S[.CURRENT = (pcallcontext[.HOLES = eps])], 1)',
        '~$api_receive_candidate(S)',
        '$lookup(S.ENV, $ptascii("text")) = (n_text)',
        'S.STORE[n_text] = DEFINED (PSTRING $ptascii("str"))',
        '$lookup(S.ENV, $ptascii("cb")) = (n_cb)',
        'S.STORE[n_cb] = DEFINED (PARRAY n_array)',
        '$api_initial_class(S, PARRAY n_array) = API_CLASS papiclass',
        'papiquery = $api_query(S, TYPE_RECEIVE porigin_receive 1, PARRAY n_array, PSTRING $ptascii("self"), DIRECT (PSTRING $ptascii("run")), papiclass, $ptascii("run"), 0, 0)',
        '$api_query_shape(S, papiquery, 0)',
        '~$api_source_valid(S, papiquery)',
        '~$api_query_valid(S, papiquery, 0)',
        '~$call_task_valid(S, API_CALLABLE_RESULT papiquery 0)',
        'S.EVENTS = [OUTPUT $ptascii("S|")]',
        *VALID,
        'S_done = $drive(S, 3000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.EVENTS = [OUTPUT $ptascii("S|"), OUTPUT $ptascii("D|"), OUTPUT $ptascii("body")]',
        *AFTER,
    ],
}

CASES['foreign-declared-fallback-entered-authentication'] = {
    'source': SOURCES['foreign-declared-method-fallback'],
    'stage': ('S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* '
              '-- if pargcall.KIND = INTRINSIC_GET_CALLED_CLASS '
              '-- if S.CURRENT = (pcallcontext) '
              '-- if pcallcontext.TARGET = API_METHOD_TARGET papiquery porigin_handle ptbytes_method false'),
    'checks': [
        'ptbytes_method = $ptascii("handle")',
        'papiquery.METHOD = DIRECT (PSTRING $ptascii("self::handle"))',
        'papiquery.PREFIX = 6 /\\ papiquery.WIDTH = 6',
        'papiquery.OUTER = (papiclass_outer)',
        'papiclass_outer.REQUESTED = papiquery.CLASS.REQUESTED',
        'papiquery.CLASS.REQUESTED = porigin_child',
        'papiquery.CLASS.RECEIVER = (n_foreign)',
        'papiquery.CLASS.CALLED = porigin_foreign',
        '~papiquery.CLASS.STRICT',
        'papiquery.SCOPE = (porigin_foreign)',
        'S.OBJECTS[n_foreign] = INSTANCE porigin_foreign',
        '$scope_method(S, porigin_child, ptbytes_method, true, papiquery.SCOPE) = eps',
        '$api_object_class(S, papiquery) = (porigin_foreign)',
        '$api_selected_method(S, papiquery, ptbytes_method) = (pmethoddesc)',
        'pmethoddesc.OWNER = porigin_foreign',
        'pmethoddesc.FUNCTION.ORIGIN = porigin_handle',
        'pcallcontext.LEXICAL_CLASS = (porigin_foreign)',
        'pcallcontext.CALLED_CLASS = (porigin_foreign)',
        'pcallcontext.RECEIVER = (n_foreign)',
        '$calledclass_name(S, pargcall) = ($ptascii("Foreign"))',
        '$api_carrier_valid(S, papiquery, porigin_handle, ptbytes_method, false)',
        '$target_nodes(pcallcontext.TARGET) = [HOBJECT n_foreign]',
        '$target_function(S, SCOPED_TARGET porigin_child porigin_handle porigin_foreign (n_foreign) (KNOWN (PSTRING $ptascii("Child")))) = eps',
        '~$api_target_valid(S, papiquery, porigin_handle, $ptascii("test"))',
        '~$api_carrier_valid(S, papiquery, porigin_handle, ptbytes_method, true)',
        'S.FRAMES = pframe_emitter :: pframe_tail*',
        'pframe_emitter.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_emitter*',
        'S_emitter = $constant_frame_scope(S, pframe_emitter, pframe_tail*)',
        '$handler_emitter_valid(S_emitter, pcallcontext.TARGET)',
        '~$handler_emitter_valid(S_emitter, API_METHOD_TARGET papiquery[.SCOPE = (porigin_child)] porigin_handle ptbytes_method false)',
        '~$error_context_valid(S, pcallcontext[.LEXICAL_CLASS = (porigin_child)])',
        *VALID,
        'S_budget = $drive_steps(S, 0)',
        'S_budget.COMPLETION = BUDGET',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.EVENTS = [OUTPUT $ptascii("D|"), OUTPUT $ptascii("body:"), OUTPUT $ptascii("Foreign"), OUTPUT $ptascii(":"), OUTPUT $ptascii("Foreign"), OUTPUT eps]',
        'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
        'S_done.ERRORHANDLER.CALLBACK = eps /\\ S_done.ERRORHANDLERS = eps',
        '~((HOBJECT n_foreign) <- S_done.ALLOCATIONS)',
        *AFTER,
    ],
}

CASES['foreign-private-fallback-entered-emitter-and-priority'] = {'source': '<?php\n'
           "function warn($n,$s,$f,$l) { echo 'D|'; return true; }\n"
           'class Base {}\n'
           'class Child extends Base {\n'
           " public function existing($n,$s,$f,$l) { echo 'Child:',get_called_class(),'|'; return true; }\n"
           '}\n'
           'class Foreign {\n'
           " public function existing($n,$s,$f,$l) { echo 'wrong-existing|'; return true; }\n"
           " private function only($n,$s,$f,$l) { echo 'Foreign:',get_called_class(),'|'; return true; }\n"
           ' public function test() {\n'
           "  error_reporting(0); set_error_handler('warn');\n"
           "  set_error_handler(['Child','self::existing']); echo $a; restore_error_handler();\n"
           "  set_error_handler(['Child','self::only']); echo $b; restore_error_handler();\n"
           "  try { set_error_handler(['Child','parent::only']); } catch (TypeError $e) { echo 'parent-rejected|'; }\n"
           '  restore_error_handler();\n'
           ' }\n'
           '}\n'
           '(new Foreign)->test();\n',
 'stage': 'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* -- if pargcall.KIND = INTRINSIC_GET_CALLED_CLASS -- if '
          'S.CURRENT = (pcallcontext) -- if pcallcontext.TARGET = API_METHOD_TARGET papiquery porigin_only '
          'ptbytes_method false -- if ptbytes_method = $ptascii("only")',
 'checks': ['papiquery.METHOD = DIRECT (PSTRING $ptascii("self::only"))',
            'papiquery.PREFIX = 6 /\\ papiquery.WIDTH = 4',
            'papiquery.OUTER = (papiclass_outer)',
            'papiquery.CLASS.REQUESTED = porigin_child',
            'papiclass_outer.REQUESTED = porigin_child',
            'papiclass_outer.RECEIVER = eps',
            'papiquery.CLASS.RECEIVER = (n_foreign)',
            'papiquery.CLASS.CALLED = porigin_foreign',
            '~papiquery.CLASS.STRICT',
            'papiquery.SCOPE = (porigin_foreign)',
            'S.OBJECTS[n_foreign] = INSTANCE porigin_foreign',
            '$scope_method(S, porigin_child, ptbytes_method, true, papiquery.SCOPE) = eps',
            '$api_object_class(S, papiquery) = (porigin_foreign)',
            '$api_selected_method(S, papiquery, ptbytes_method) = (pmethoddesc)',
            'pmethoddesc.OWNER = porigin_foreign /\\ pmethoddesc.VISIBILITY = PROPERTY_PRIVATE',
            'pmethoddesc.FUNCTION.ORIGIN = porigin_only',
            '$api_getter_error(S, papiquery, ptbytes_method) = eps',
            '$api_getter_error(S, papiquery[.SCOPE = (porigin_child)], ptbytes_method) = ($ptascii("Call to private '
            'method Foreign::only() from scope Child"))',
            'pcallcontext.LEXICAL_CLASS = (porigin_foreign)',
            'pcallcontext.CALLED_CLASS = (porigin_foreign)',
            'pcallcontext.RECEIVER = (n_foreign)',
            '$calledclass_name(S, pargcall) = ($ptascii("Foreign"))',
            '$api_carrier_valid(S, papiquery, porigin_only, ptbytes_method, false)',
            '$target_nodes(pcallcontext.TARGET) = [HOBJECT n_foreign]',
            '$target_function(S, SCOPED_TARGET porigin_child porigin_only porigin_foreign (n_foreign) (KNOWN (PSTRING '
            '$ptascii("Child")))) = eps',
            '~$api_target_valid(S, papiquery, porigin_only, $ptascii("existing"))',
            '~$api_carrier_valid(S, papiquery, porigin_only, ptbytes_method, true)',
            '~$api_carrier_valid(S, papiquery[.SCOPE = (porigin_child)], porigin_only, ptbytes_method, false)',
            '$class_link_at(S.LINKEDPARENTS, porigin_child) = (SOURCE_PARENT porigin_base)',
            '$api_object_class(S, papiquery[.OUTER = (papiclass_outer[.REQUESTED = porigin_base])]) = eps',
            '$api_selected_method(S, papiquery, $ptascii("existing")) = (pmethoddesc_existing)',
            'pmethoddesc_existing.OWNER = porigin_child',
            'S.FRAMES = pframe_emitter :: pframe_tail*',
            'pframe_emitter.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_emitter*',
            'S_emitter = $constant_frame_scope(S, pframe_emitter, pframe_tail*)',
            '$handler_emitter_valid(S_emitter, pcallcontext.TARGET)',
            '~$handler_emitter_valid(S_emitter, API_METHOD_TARGET papiquery[.SCOPE = (porigin_child)] porigin_only '
            'ptbytes_method false)',
            '~$error_context_valid(S, pcallcontext[.LEXICAL_CLASS = (porigin_child)])',
            '$call_descriptors_valid(S)',
            '$class_state_valid(S)',
            '$closure_state_valid(S)',
            '$heap_valid($heap_graph(S))',
            'S_budget = $drive_steps(S, 0)',
            'S_budget.COMPLETION = BUDGET',
            'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
            'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT $ptascii("D|"), OUTPUT $ptascii("Child:"), OUTPUT $ptascii("Foreign"), OUTPUT '
            '$ptascii("|"), OUTPUT eps, OUTPUT $ptascii("D|"), OUTPUT $ptascii("Foreign:"), OUTPUT '
            '$ptascii("Foreign"), OUTPUT $ptascii("|"), OUTPUT eps, OUTPUT $ptascii("D|"), OUTPUT '
            '$ptascii("parent-rejected|")]',
            'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
            'S_done.ERRORHANDLER.CALLBACK = eps /\\ S_done.ERRORHANDLERS = eps',
            '~((HOBJECT n_foreign) <- S_done.ALLOCATIONS)',
            '$call_descriptors_valid(S_done)',
            '$class_state_valid(S_done)',
            '$closure_state_valid(S_done)',
            '$heap_valid($heap_graph(S_done))']}

CASES['foreign-dispatch-getter-error-chain-and-restoration'] = {
    'source': SOURCES['foreign-dispatch-getter-error-restores-raw'],
    'stage': ('S.TODO = (THROW_SEARCH n_new) :: ptask_tail* '
              '-- if $throwable_previous_id(S, n_new) = (n_old) '
              '-- if S.CURRENT = (pcallcontext)'),
    'checks': [
        '$lookup(S.ENV, $ptascii("raw")) = (n_raw)',
        'S.STORE[n_raw] = DEFINED (PARRAY n_array)',
        '$entry_lookup(S.ARRAYS[n_array].ITEMS, KINT 1) = (ALIAS n_method)',
        'S.STORE[n_method] = DEFINED (PSTRING $ptascii("self::only"))',
        'pcallcontext.LEXICAL_CLASS = (porigin_child)',
        '$class_at(S.CLASSES, porigin_child) = (pclassdesc_child)',
        'pclassdesc_child.NAME = $ptascii("Child")',
        'pcallcontext.CALLED_CLASS = (porigin_foreign)',
        'pcallcontext.RECEIVER = (n_foreign)',
        'S.OBJECTS[n_foreign] = INSTANCE porigin_foreign',
        'S.ERRORHANDLER.CALLBACK = (PARRAY n_array)',
        '~$api_pending_tasks(ptask_tail*)',
        'pcallcontext.TARGET = API_METHOD_TARGET papiquery_outer porigin_run ptbytes_run false',
        '$api_carrier_valid(S, papiquery_outer, porigin_run, ptbytes_run, false)',
        '$throwable_previous_id(S, n_new) = (n_old)',
        'ptbytes_outer = $ptascii("Invalid callback Child::self::only, class Child does not have a method ") ++ [34] ++ $ptascii("only") ++ [34]',
        '$throwable_field(S, n_new, "message") = PSTRING ptbytes_outer',
        '$throwable_field(S, n_old, "message") = PSTRING $ptascii("Call to private method Foreign::only() from scope Child")',
        '$throwable_field(S, n_old, "previous") = PNULL',
        '$throwable_chain_valid(S, n_new)',
        '$heap_owners($heap_graph(S), HOBJECT n_old) = 1',
        'S.EVENTS = [OUTPUT $ptascii("D|"), OUTPUT $ptascii("D|")]',
        *VALID,
        'S_budget = $drive_steps(S, 0)',
        'S_budget.COMPLETION = BUDGET',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.EVENTS = [OUTPUT $ptascii("D|"), OUTPUT $ptascii("D|"), OUTPUT ptbytes_outer, OUTPUT $ptascii("|"), OUTPUT $ptascii("Call to private method Foreign::only() from scope Child"), OUTPUT $ptascii("|"), OUTPUT $ptascii("self::only"), OUTPUT eps]',
        'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
        'S_done.ERRORHANDLER.CALLBACK = eps /\\ S_done.ERRORHANDLERS = eps',
        '~((HOBJECT n_foreign) <- S_done.ALLOCATIONS)',
        '~((HOBJECT n_old) <- S_done.ALLOCATIONS)',
        '~((HOBJECT n_new) <- S_done.ALLOCATIONS)',
        '~((HARRAY n_array) <- S_done.ALLOCATIONS)',
        '~((HCELL n_method) <- S_done.ALLOCATIONS)',
        *AFTER,
    ],
}

CASES['constant-owner-keeps-real-user-api-emitter'] = {
    'source': SOURCES['constant-owner-keeps-real-user-api-scope'],
    'stage': ('S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* '
              '-- if pargcall.KIND = INTRINSIC_GET_CALLED_CLASS '
              '-- if S.CURRENT = (pcallcontext) '
              '-- if pcallcontext.TARGET = API_METHOD_TARGET papiquery porigin_handle ptbytes_method true'),
    'checks': [
        'ptbytes_method = $ptascii("handle")',
        'papiquery.INPUT = PSTRING $ptascii("self")',
        'papiquery.SCOPE = (porigin_b)',
        'papiquery.CLASS.REQUESTED = porigin_b /\\ papiquery.CLASS.CALLED = porigin_b',
        'papiquery.THIS = eps /\\ papiquery.CLASS.RECEIVER = eps',
        '$class_at(S.CLASSES, porigin_b) = (pclassdesc_b)',
        'pclassdesc_b.NAME = $ptascii("B")',
        'pcallcontext.LEXICAL_CLASS = (porigin_b) /\\ pcallcontext.CALLED_CLASS = (porigin_b)',
        'pcallcontext.RECEIVER = eps',
        '$target_nodes(pcallcontext.TARGET) = eps',
        '$class_method_origin(S.CLASSES, porigin_handle) = (pmethoddesc)',
        'pmethoddesc.VISIBILITY = PROPERTY_PRIVATE /\\ pmethoddesc.STATIC',
        '$api_carrier_valid(S, papiquery, porigin_handle, ptbytes_method, true)',
        'S.FRAMES = pframe_emitter :: pframe_tail*',
        'pframe_emitter.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_emitter*',
        'S_emitter = $constant_frame_scope(S, pframe_emitter, pframe_tail*)',
        'S_emitter.CLASSCONSTANTINIT = pclassconstantcontext :: pclassconstantcontext_tail*',
        '$class_constant_origin(S.CLASSES, pclassconstantcontext.DECL) = (pclassconstantdesc)',
        'pclassconstantdesc.OWNER = porigin_a',
        '$class_at(S.CLASSES, porigin_a) = (pclassdesc_a)',
        'pclassdesc_a.NAME = $ptascii("A")',
        '$method_current_scope(S_emitter) = (porigin_a)',
        '$api_frame_scope(S_emitter) = (porigin_b)',
        '$class_constant_location(S) = (pconstantlocation)',
        'pconstantlocation.CLASS = porigin_a /\\ pconstantlocation.ROOT = pclassconstantdesc.ORIGIN',
        '$constant_location_valid(S, pconstantlocation, |S.SOURCES|)',
        '$handler_emitter_valid(S_emitter, pcallcontext.TARGET)',
        '$error_entered_call_valid(S_emitter, perrorcall)',
        '$error_context_valid(S, pcallcontext)',
        '$class_constant_state_valid(S)',
        *VALID,
        '~$handler_emitter_valid(S_emitter, API_METHOD_TARGET papiquery[.SCOPE = (porigin_a)] porigin_handle ptbytes_method true)',
        '~$error_context_valid(S, pcallcontext[.LEXICAL_CLASS = (porigin_a)])',
        'S_budget = $drive_steps(S, 0)',
        'S_budget.COMPLETION = BUDGET',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.EVENTS = [OUTPUT $ptascii("D|"), OUTPUT $ptascii("B"), OUTPUT $ptascii(":"), OUTPUT $ptascii("B"), OUTPUT $ptascii("|"), OUTPUT $ptascii("2049"), OUTPUT $ptascii("|")]',
        'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
        'S_done.CONSTCONTEXT = eps /\\ S_done.CLASSCONSTANTINIT = eps',
        'S_done.ERRORHANDLER.CALLBACK = eps /\\ S_done.ERRORHANDLERS = eps',
        '$class_constant_state_valid(S_done)',
        *AFTER,
    ],
}

if __name__ == '__main__':
    protocol.run(CASES, extra_inputs=[Path(__file__), CATALOGUE])
