#!/usr/bin/env python3
"""Live callable member reads, held class branches and authentic API receivers."""
from pathlib import Path
import json

import closure_call_protocol as protocol

CATALOGUE = Path(__file__).with_name('keyword_compound_callables_cases.json')
SOURCES = {row['id']: row['source'] for row in json.loads(CATALOGUE.read_text())}
VALID = ['$call_descriptors_valid(S)', '$class_state_valid(S)',
         '$closure_state_valid(S)', '$heap_valid($heap_graph(S))']
AFTER = ['$call_descriptors_valid(S_done)', '$class_state_valid(S_done)',
         '$closure_state_valid(S_done)', '$heap_valid($heap_graph(S_done))']

CASES = {
    'keyword-method-alias-live-after-warning': {
        'source': SOURCES['method-alias'],
        'stage': 'S.TODO = (API_CALLABLE_RESULT papiquery 0) :: ptask_tail*',
        'checks': [
            'papiquery.SOURCE = TYPE_RECEIVE porigin_receive n_parameter',
            'papiquery.INPUT = PSTRING $ptascii("self")',
            'papiquery.VALUE = PARRAY n_array',
            'papiquery.METHOD = ALIAS n_method',
            'papiquery.ORIGINAL = $ptascii("missing")',
            'papiquery.PREFIX = 0 /\\ papiquery.WIDTH = 0',
            'papiquery.OUTER = eps',
            'papiquery.SCOPE = (papiquery.CLASS.REQUESTED)',
            '~papiquery.CLASS.STRICT',
            'S.STORE[n_method] = DEFINED (PSTRING $ptascii("ok"))',
            '$entry_value(S, papiquery.METHOD) = PSTRING $ptascii("ok")',
            '$api_query_valid(S, papiquery, 0)',
            '$task_nodes(API_CALLABLE_RESULT papiquery 0) = eps',
            '$typed_callable(S, papiquery.VALUE) = (true)',
            '$function_at($all_functions(S), porigin_receive) = (pfunction)',
            '$typed_conversion_at(S, pfunction.SIGNATURE.PARAMETERS[n_parameter].TYPE, papiquery.VALUE, false) = TYPEDEPENDENT "deprecated callable admission continuation"',
            *VALID,
            '~$api_query_valid(S, papiquery[.LINE = $(papiquery.LINE + 100)], 0)',
            '~$api_query_valid(S, papiquery[.SCOPE = eps], 0)',
            '~$api_query_valid(S, papiquery[.CLASS = papiquery.CLASS[.STRICT = true]], 0)',
            '~$api_query_valid(S, papiquery[.SOURCE = TYPE_RECEIVE porigin_receive $(n_parameter + 1)], 0)',
            '~$api_query_valid(S, papiquery[.METHOD = DIRECT (PSTRING $ptascii("ok"))], 0)',
            '~$api_query_valid(S, papiquery, 1)',
            'S_bad = $drive(S[.TODO = [API_CALLABLE_RESULT papiquery[.LINE = $(papiquery.LINE + 100)] 0]], 5)',
            'S_bad.COMPLETION = UNSUPPORTED "invalid compiled function descriptor"',
            'S_budget = $drive_steps(S, 1)',
            'S_budget.COMPLETION = BUDGET',
            'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
            'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT ($api_keyword_message(PSTRING $ptascii("self"))), OUTPUT $ptascii(":"), OUTPUT $ptascii("missing"), OUTPUT $ptascii("|"), OUTPUT $ptascii("admitted:"), OUTPUT $ptascii("ok")]',
            'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
            'S_done.ERRORHANDLER.CALLBACK = eps /\\ S_done.ERRORHANDLERS = eps',
            '~((HARRAY n_array) <- S_done.ALLOCATIONS)',
            '~((HCELL n_method) <- S_done.ALLOCATIONS)',
            *AFTER,
        ],
    },
    'keyword-class-branch-held-before-registration': {
        'source': SOURCES['class-alias-registration'],
        'stage': 'S.TODO = (API_CALLABLE_RESULT papiquery 0) :: ptask_tail*',
        'checks': [
            'papiquery.SOURCE = CONFIG_INVOKE pconfigcall',
            'papiquery.INPUT = PSTRING $ptascii("self")',
            'papiquery.VALUE = PARRAY n_array',
            '$entry_lookup(S.ARRAYS[n_array].ITEMS, KINT 0) = (ALIAS n_class)',
            'S.STORE[n_class] = DEFINED (PSTRING $ptascii("Other"))',
            '$class_at(S.CLASSES, papiquery.CLASS.REQUESTED) = (pclassdesc)',
            'pclassdesc.NAME = $ptascii("Owner")',
            'papiquery.METHOD = DIRECT (PSTRING $ptascii("handle"))',
            '$api_query_valid(S, papiquery, 0)',
            '$error_handler_resolution(S, papiquery.VALUE) = HANDLERINVALID ($ptascii("class Other does not have a method ") ++ [34] ++ $ptascii("handle") ++ [34])',
            *VALID,
            '~$api_query_valid(S, papiquery[.INPUT = PSTRING $ptascii("Other")], 0)',
            '~$api_query_valid(S, papiquery[.SOURCE = CONFIG_INVOKE pconfigcall[.LINE = $(pconfigcall.LINE + 100)]], 0)',
            'PhpStep: S ~> S_one',
            'S_one.COMPLETION = NORMAL',
            'S_one.ERRORHANDLER.CALLBACK = (PARRAY n_array)',
            '$error_handler_retained(S_one, PARRAY n_array)',
            '$call_descriptors_valid(S_one)',
            'S_done = $drive(S_one, 3000)',
            'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT $ptascii("deprecation|"), OUTPUT $ptascii("registered:"), OUTPUT $ptascii("Other"), OUTPUT $ptascii("|"), OUTPUT ($ptascii("Invalid callback Other::handle, class Other does not have a method ") ++ [34] ++ $ptascii("handle") ++ [34])]',
            *AFTER,
        ],
    },
    'compound-prefix-held-leaf-live': {
        'source': '''<?php
class Base { public static function ok() {} public static function xx() {} }
class Child extends Base { public function test() {
 $method='Base::xx'; $cb=['Child', &$method];
 set_error_handler(function($n,$s) use (&$method) {echo 'D|';$method='Nope::ok';return true;});
 $take=function(callable $cb) {echo 'A|',$cb[1];};$take($cb);restore_error_handler();
} }
(new Child)->test();
''',
        'stage': 'S.TODO = (API_CALLABLE_RESULT papiquery 1) :: ptask_tail*',
        'checks': [
            'papiquery.VALUE = PARRAY n_array',
            'papiquery.METHOD = ALIAS n_method',
            'papiquery.ORIGINAL = $ptascii("Base::xx")',
            'papiquery.PREFIX = 6 /\\ papiquery.WIDTH = 2',
            'papiquery.OUTER = (papiclass_outer)',
            '$class_at(S.CLASSES, papiclass_outer.REQUESTED) = (pclassdesc_outer)',
            'pclassdesc_outer.NAME = $ptascii("Child")',
            '$class_at(S.CLASSES, papiquery.CLASS.REQUESTED) = (pclassdesc_inner)',
            'pclassdesc_inner.NAME = $ptascii("Base")',
            'S.STORE[n_method] = DEFINED (PSTRING $ptascii("Nope::ok"))',
            '$api_query_valid(S, papiquery, 1)',
            *VALID,
            '~$api_query_valid(S, papiquery[.PREFIX = 4], 1)',
            '~$api_query_valid(S, papiquery[.WIDTH = 1], 1)',
            '~$api_query_valid(S, papiquery[.CLASS = papiclass_outer], 1)',
            'S_done = $drive(S, 3000)',
            'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT $ptascii("D|"), OUTPUT $ptascii("A|"), OUTPUT $ptascii("Nope::ok")]',
            '~((HARRAY n_array) <- S_done.ALLOCATIONS)',
            '~((HCELL n_method) <- S_done.ALLOCATIONS)',
            *AFTER,
        ],
    },
    'foreign-this-entered-api-authentication': {
        'source': '''<?php
class Child { public function run($n,$s,$f,$l) {echo func_num_args(),':',($this instanceof Foreign)?'Foreign':'wrong',':',self::class,':',static::class;return true;}public function other($n,$s,$f,$l) {return true;} }
class Foreign {public function test() {error_reporting(0);set_error_handler(function($n,$s){return true;});set_error_handler(['Child','self::run']);echo $missing;restore_error_handler();restore_error_handler();} }
(new Foreign)->test();
''',
        'stage': ('S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* '
                  '-- if S.CURRENT = (pcallcontext) '
                  '-- if pcallcontext.TARGET = API_METHOD_TARGET papiquery porigin_run ptbytes_method b_static'),
        'checks': [
            '~b_static',
            'ptbytes_method = $ptascii("run")',
            'papiquery.METHOD = DIRECT (PSTRING $ptascii("self::run"))',
            'papiquery.PREFIX = 6 /\\ papiquery.WIDTH = 3',
            'papiquery.CLASS.RECEIVER = (n_foreign)',
            'papiquery.CLASS.CALLED = porigin_foreign',
            'papiquery.CLASS.REQUESTED = porigin_child',
            'papiquery.SCOPE = (porigin_foreign)',
            'papiquery.THIS = (n_foreign)',
            'S.OBJECTS[n_foreign] = INSTANCE porigin_foreign',
            'pcallcontext.LEXICAL_CLASS = (porigin_child)',
            'pcallcontext.CALLED_CLASS = (porigin_foreign)',
            'pcallcontext.RECEIVER = (n_foreign)',
            'pcallcontext.ARGC = 4',
            '$api_carrier_valid(S, papiquery, porigin_run, ptbytes_method, false)',
            '$target_nodes(pcallcontext.TARGET) = [HOBJECT n_foreign]',
            '$class_method_origin(S.CLASSES, porigin_run) = (pmethoddesc)',
            '~$scoped_receiver_valid(S, porigin_child, pmethoddesc, (n_foreign))',
            '$target_function(S, SCOPED_TARGET porigin_child porigin_run porigin_foreign (n_foreign) (KNOWN (PSTRING $ptascii("Child")))) = eps',
            'S.FRAMES = pframe_emitter :: pframe_tail*',
            'pframe_emitter.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_emitter*',
            'perrorcall.TARGET = (pcallcontext.TARGET)',
            'S_emitter = S[.CURRENT = pframe_emitter.CONTEXT][.FRAMES = pframe_tail*][.ORIGIN = pframe_emitter.ORIGIN][.TODO = pframe_emitter.TODO][.BORROWEDREAD = pframe_emitter.BORROWEDREAD]',
            '$handler_emitter_valid(S_emitter, pcallcontext.TARGET)',
            '$error_entered_call_valid(S_emitter, perrorcall)',
            '$error_context_valid(S, pcallcontext)',
            '$arginfo_values(S, pcallcontext) = $error_handler_values(S, perrorcall)',
            'S.ERRORHANDLER.CALLBACK = eps',
            *VALID,
            '$effective_method(S, porigin_child, $ptascii("other"), |S.CLASSES|) = (pmethoddesc_other)',
            '~$api_carrier_valid(S, papiquery, pmethoddesc_other.FUNCTION.ORIGIN, $ptascii("other"), false)',
            '~$api_carrier_valid(S, papiquery, porigin_run, ptbytes_method, true)',
            '~$handler_emitter_valid(S_emitter, API_METHOD_TARGET papiquery[.SCOPE = (porigin_child)] porigin_run ptbytes_method false)',
            '~$error_entered_call_valid(S_emitter, perrorcall[.TARGET = (API_METHOD_TARGET papiquery porigin_run ptbytes_method true)])',
            '~$error_context_valid(S, pcallcontext[.CALLED_CLASS = (porigin_child)])',
            '~$error_context_valid(S, pcallcontext[.ARGC = 0])',
            '~$call_descriptors_valid(S[.CURRENT = (pcallcontext[.TARGET = API_METHOD_TARGET papiquery pmethoddesc_other.FUNCTION.ORIGIN $ptascii("other") false])])',
            'S_done = $drive(S, 3000)',
            'S_done.COMPLETION = NORMAL',
            'S_done.EVENTS = [OUTPUT $ptascii("4"), OUTPUT $ptascii(":"), OUTPUT $ptascii("Foreign"), OUTPUT $ptascii(":"), OUTPUT $ptascii("Child"), OUTPUT $ptascii(":"), OUTPUT $ptascii("Foreign"), OUTPUT eps]',
            'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
            'S_done.ERRORHANDLER.CALLBACK = eps /\\ S_done.ERRORHANDLERS = eps',
            '~((HOBJECT n_foreign) <- S_done.ALLOCATIONS)',
            *AFTER,
        ],
    },
}

CASES['active-handler-original-receiving-table'] = {
    'source': SOURCES['byref-string-prefix'],
    'stage': 'S.CURRENT = (pcallcontext_handler) -- if pcallcontext_handler.NAME = $ptascii("warn") -- if S.FRAMES = pframe_receive :: pframe_tail* -- if pframe_receive.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_receive* -- if perrorcall.RESUME = API_CALLABLE_RESULT papiquery 1 -- if papiquery.SOURCE = TYPE_RECEIVE porigin_receive n_parameter -- if papiquery.METHOD = ALIAS n_formal -- if S.STORE[n_formal] = DEFINED (PSTRING $ptascii("Nope::ok"))',
    'checks': [
        'pframe_receive.CONTEXT = (pcallcontext_receive)',
        'pcallcontext_receive.FUNCTION = porigin_receive',
        'pframe_receive.LOCALS = (psymboltable_receive)',
        '$lookup(psymboltable_receive.ENV, $ptascii("value")) = (n_formal)',
        '$lookup(S.ENV, $ptascii("value")) = eps',
        '$lookup(S.ENV, $ptascii("n")) = (n_warning)',
        'papiquery.ORIGINAL = $ptascii("self::xx")',
        'papiquery.INPUT = PSTRING $ptascii("self")',
        'papiquery.PREFIX = 6 /\\ papiquery.WIDTH = 2',
        'papiquery.CLASS.RECEIVER = eps',
        '$class_at(S.CLASSES, papiquery.CLASS.REQUESTED) = (pclassdesc)',
        'pclassdesc.NAME = $ptascii("A")',
        'S_receive = $api_saved_frame_scope(S, pframe_receive, pframe_tail*)',
        'S_receive.ENV = psymboltable_receive.ENV',
        'S_receive.FRAMES = pframe_tail*',
        '$api_query_valid(S_receive, papiquery, 1)',
        '~$api_query_valid(S, papiquery, 1)',
        '$call_descriptors_valid(S)',
        '$class_state_valid(S)',
        '$closure_state_valid(S)',
        '$heap_valid($heap_graph(S))',
        '~$api_query_valid(S_receive, papiquery[.METHOD = ALIAS n_warning], 1)',
        '~$api_query_valid(S_receive, papiquery[.WIDTH = 1], 1)',
        '~$api_query_valid(S_receive, papiquery[.LINE = $(papiquery.LINE + 1)], 1)',
        'S_budget = $drive_steps(S, 0)',
        'S_budget.COMPLETION = BUDGET',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.EVENTS = [OUTPUT ($api_keyword_message(PSTRING $ptascii("self"))), OUTPUT $ptascii("|"), OUTPUT $ptascii("admitted:"), OUTPUT $ptascii("Nope::ok")]',
        'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
        '$lookup(S_done.ENV, $ptascii("cb")) = (n_cb)',
        'S_done.STORE[n_cb] = DEFINED (PSTRING $ptascii("Nope::ok"))',
        '$call_descriptors_valid(S_done)',
        '$class_state_valid(S_done)',
        '$closure_state_valid(S_done)',
        '$heap_valid($heap_graph(S_done))',
    ],
}

CASES['replaced-reference-array-retained-original'] = {
    'source': SOURCES['byref-array-replaced'],
    'stage': 'S.TODO = (API_CALLABLE_RESULT papiquery 0) :: ptask_tail*',
    'checks': [
        'papiquery.SOURCE = TYPE_RECEIVE porigin_receive n_parameter',
        'papiquery.VALUE = PARRAY n_original',
        'papiquery.METHOD = DIRECT (PSTRING $ptascii("run"))',
        'papiquery.INPUT = PSTRING $ptascii("self")',
        '$lookup(S.ENV, $ptascii("value")) = (n_formal)',
        'S.STORE[n_formal] = DEFINED PNULL',
        'S.GLOBALTABLE = (psymboltable_global)',
        '$lookup(psymboltable_global.ENV, $ptascii("keep")) = (n_keep)',
        'S.STORE[n_keep] = DEFINED papiquery.VALUE',
        '(HARRAY n_original) <- S.ALLOCATIONS',
        '$api_query_valid(S, papiquery, 0)',
        '$call_descriptors_valid(S)',
        '$class_state_valid(S)',
        '$closure_state_valid(S)',
        '$heap_valid($heap_graph(S))',
        '~$api_query_valid(S, papiquery[.VALUE = PNULL], 0)',
        '~$api_query_valid(S, papiquery[.METHOD = DIRECT (PSTRING $ptascii("other"))], 0)',
        '~$api_query_valid(S[.ALLOCATIONS = $call_remove_owner(S.ALLOCATIONS, HARRAY n_original)], papiquery, 0)',
        '~$api_query_valid(S[.ALLOCATIONS = $call_remove_owner(S.ALLOCATIONS, HCELL n_formal)], papiquery, 0)',
        '~$api_query_valid(S[.REFCELLS = eps], papiquery, 0)',
        '~$api_query_valid(S[.STORE = $set_cell(S.STORE, n_formal, UNDEFINED)], papiquery, 0)',
        'n_outside = |S.ARRAYS|',
        '~$api_query_valid(S, papiquery[.VALUE = PARRAY n_outside], 0)',
        '~$api_query_valid(S, papiquery[.SOURCE = TYPE_RECEIVE porigin_receive $(n_parameter + 1)], 0)',
        'S_budget = $drive_steps(S, 0)',
        'S_budget.COMPLETION = BUDGET',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.EVENTS = [OUTPUT $ptascii("deprecation|"), OUTPUT $ptascii("null-body|"), OUTPUT $ptascii("null-caller")]',
        'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
        '$lookup(S_done.ENV, $ptascii("cb")) = (n_cb)',
        'S_done.STORE[n_cb] = DEFINED PNULL',
        '$call_descriptors_valid(S_done)',
        '$class_state_valid(S_done)',
        '$closure_state_valid(S_done)',
        '$heap_valid($heap_graph(S_done))',
    ],
}

CASES['static-parent-carrier-called-scope-and-owners'] = {
    'source': SOURCES['static-keyword-ownership'],
    'stage': 'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* -- if S.CURRENT = (pcallcontext) -- if pcallcontext.TARGET = API_METHOD_TARGET papiquery porigin_run ptbytes_method true -- if papiquery.INPUT = PSTRING $ptascii("parent")',
    'checks': [
        'ptbytes_method = $ptascii("run")',
        'papiquery.CLASS.RECEIVER = (n_child)',
        'papiquery.CLASS.REQUESTED = porigin_base',
        'papiquery.CLASS.CALLED = porigin_child',
        'papiquery.CLASS.STRICT',
        'S.OBJECTS[n_child] = INSTANCE porigin_child',
        '$class_at(S.CLASSES, porigin_base) = (pclassdesc_base)',
        'pclassdesc_base.NAME = $ptascii("Base")',
        '$class_at(S.CLASSES, porigin_child) = (pclassdesc_child)',
        'pclassdesc_child.NAME = $ptascii("Child")',
        'pcallcontext.RECEIVER = eps',
        'pcallcontext.LEXICAL_CLASS = (porigin_base)',
        'pcallcontext.CALLED_CLASS = (porigin_child)',
        'pcallcontext.ARGC = 4',
        '$target_nodes(pcallcontext.TARGET) = eps',
        '$api_carrier_valid(S, papiquery, porigin_run, ptbytes_method, true)',
        '~$api_carrier_valid(S, papiquery, porigin_run, ptbytes_method, false)',
        '$target_function(S, API_METHOD_TARGET papiquery porigin_run ptbytes_method false) = eps',
        '$call_descriptors_valid(S)',
        '$class_state_valid(S)',
        '$closure_state_valid(S)',
        '$heap_valid($heap_graph(S))',
        '~$call_descriptors_valid(S[.CURRENT = (pcallcontext[.TARGET = API_METHOD_TARGET papiquery porigin_run ptbytes_method false])])',
        'S_done = $drive(S, 3000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
        'S_done.ERRORHANDLER.CALLBACK = eps /\\ S_done.ERRORHANDLERS = eps',
        '~((HOBJECT n_child) <- S_done.ALLOCATIONS)',
        '$call_descriptors_valid(S_done)',
        '$class_state_valid(S_done)',
        '$closure_state_valid(S_done)',
        '$heap_valid($heap_graph(S_done))',
    ],
}

CASES['compound-warning-throw-restores-and-retires'] = {
    'source': SOURCES['compound-throw'],
    'stage': ('S.TODO = (THROW_SEARCH n_exception) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail* '
              '-- if perrorcall.RESUME = API_CALLABLE_RESULT papiquery 1'),
    'checks': [
        'papiquery.SOURCE = CONFIG_INVOKE pconfigcall',
        'pconfigcall.KIND = INTRINSIC_SET_ERROR_HANDLER',
        'papiquery.VALUE = PARRAY n_array',
        'papiquery.METHOD = DIRECT (PSTRING $ptascii("Base::ok"))',
        'papiquery.OUTER = (papiclass_outer)',
        'papiquery.PREFIX = 6 /\\ papiquery.WIDTH = 2',
        'perrorcall.CALLBACK = POBJECT n_handler',
        'S.ERRORHANDLER.CALLBACK = eps',
        '$api_query_valid(S, papiquery, 1)',
        '$error_entered_call_valid(S, perrorcall)',
        '$throwable_live(S, n_exception)',
        *VALID,
        'S_budget = $drive_steps(S, 0)',
        'S_budget.COMPLETION = BUDGET',
        'S_done = $drive(S_budget[.COMPLETION = NORMAL], 3000)',
        'S_done.COMPLETION = NORMAL',
        'S_done.EVENTS = [OUTPUT $ptascii("deprecation|"), OUTPUT $ptascii("stop")]',
        'S_done.CURRENT = eps /\\ S_done.FRAMES = eps',
        'S_done.ERRORHANDLER.CALLBACK = eps /\\ S_done.ERRORHANDLERS = eps',
        '(HARRAY n_array) <- $pools_nodes(S_done.POOLS)',
        '$heap_owners($heap_graph(S_done), HARRAY n_array) = 1',
        '~((HOBJECT n_handler) <- S_done.ALLOCATIONS)',
        *AFTER,
    ],
}

if __name__ == '__main__':
    protocol.run(CASES, extra_inputs=[Path(__file__), CATALOGUE])
