"""Top-level magic constant source controls, including phase and name provenance."""

CASES = {'FILE/read': b'<?php echo "[",__FILE__,"]";',
 'FILE/array': b'<?php $a=[__FILE__];echo $a[0];',
 'FILE/prepass': b'<?php [__FILE__ ? 1 : [[]=>1]];',
 'DIR/read': b'<?php echo "[",__DIR__,"]";',
 'DIR/array': b'<?php $a=[__DIR__];echo $a[0];',
 'DIR/prepass': b'<?php [__DIR__ ? 1 : [[]=>1]];',
 'LINE/read': b'<?php echo "[",__LINE__,"]";',
 'LINE/array': b'<?php $a=[__LINE__];echo $a[0];',
 'LINE/prepass': b'<?php [__LINE__ ? 1 : [[]=>1]];',
 'NAMESPACE/read': b'<?php echo "[",__NAMESPACE__,"]";',
 'NAMESPACE/array': b'<?php $a=[__NAMESPACE__];echo $a[0];',
 'NAMESPACE/prepass': b'<?php [__NAMESPACE__ ? 1 : [[]=>1]];',
 'CLASS/read': b'<?php echo "[",__CLASS__,"]";',
 'CLASS/array': b'<?php $a=[__CLASS__];echo $a[0];',
 'CLASS/prepass': b'<?php [__CLASS__ ? 1 : [[]=>1]];',
 'FUNCTION/read': b'<?php echo "[",__FUNCTION__,"]";',
 'FUNCTION/array': b'<?php $a=[__FUNCTION__];echo $a[0];',
 'FUNCTION/prepass': b'<?php [__FUNCTION__ ? 1 : [[]=>1]];',
 'METHOD/read': b'<?php echo "[",__METHOD__,"]";',
 'METHOD/array': b'<?php $a=[__METHOD__];echo $a[0];',
 'METHOD/prepass': b'<?php [__METHOD__ ? 1 : [[]=>1]];',
 'TRAIT/read': b'<?php echo "[",__TRAIT__,"]";',
 'TRAIT/array': b'<?php $a=[__TRAIT__];echo $a[0];',
 'TRAIT/prepass': b'<?php [__TRAIT__ ? 1 : [[]=>1]];',
 'PROPERTY/read': b'<?php echo "[",__PROPERTY__,"]";',
 'PROPERTY/array': b'<?php $a=[__PROPERTY__];echo $a[0];',
 'PROPERTY/prepass': b'<?php [__PROPERTY__ ? 1 : [[]=>1]];',
 'namespace': b'<?php namespace A\\B; echo __NAMESPACE__,":",__CLASS__,":",__FUNCTION__,":",__METHOD__,":",__'
              b'TRAIT__,":",__PROPERTY__;',
 'namespace-blocks': b'<?php namespace A {echo __NAMESPACE__;} namespace {echo "[",__NAMESPACE__,"]";}',
 'line-multiline': b'<?php\necho __LINE__,\n__LINE__;',
 'line-prepass': b'<?php\n[__LINE__ ? 1 : [[]=>1]];',
 'file-short': b'<?php __FILE__ || [,$x];',
 'function-short': b'<?php __FUNCTION__ && [,$x];',
 'dir-effect': b'<?php echo (list($x)=[1]) ? __DIR__ : __FILE__;',
 'namespace-name': b'<?php namespace N; ${__NAMESPACE__}=1; echo $N;',
 'function-name': b'<?php ${__FUNCTION__}=1; echo ${""};',
 'line-unpack': b'<?php [...[__LINE__]];',
 'file-concat-name': b'<?php ${__FILE__.""}=7;echo ${__FILE__};',
 'line-hole-line': b'<?php [\n__LINE__\n,,];',
 'file-prior-hole': b'<?php [\n__FILE__\n,,];',
 'bare-name-priority': b'<?php namespace N; [__NAMESPACE__ ? 1 : [[]=>1],,];',
 'magic-autoglobal-name': b'<?php namespace _ENV; ${__NAMESPACE__}=1;',
 'magic-concat-globals-name': b'<?php namespace GLO; ${__NAMESPACE__."BALS"}=1;',
 'magic-header-name': b'<?php namespace http_response_header; if(false){${__NAMESPACE__}=1;} echo ${__NAMESP'
                      b'ACE__};',
 'magic-header-after-cv': b'<?php namespace http_response_header; if(false){$http_response_header=1;} echo $'
                          b'{__NAMESPACE__};',
 'literal-global-priority': b'<?php ${"GLO"."BALS"}=__LINE__;',
 'computed-global-priority': b'<?php ${"GLOBALS"|""}=__LINE__;'}
