#!/usr/bin/env python3
"""Same-lexical called-class capture, retirement and fixed-source checks."""
from pathlib import Path
import json

import closure_call_protocol as protocol

ROOT = Path(__file__).resolve().parents[2]
CATALOGUE = ROOT / 'tests/semantics/rebound_called_class_cases.json'
SOURCES = {row['id']: row['source'] for row in json.loads(CATALOGUE.read_text())}
GUARDS = ['$call_descriptors_valid(S)', '$closure_state_valid(S)', '$heap_valid($heap_graph(S))']
CONVERT = ('S.TODO = (METHOD_CONVERT (SCOPED_TARGET porigin_class porigin_method '
           'porigin_called n_target_receiver? poperand_selector) porigin_site z) :: ptask_tail* '
           '-- if S.CURRENT = (pcallcontext)')
AFTER = [
    '$method_capture_current(S, porigin_site) = (pmethodcapture)',
    'pmethodcapture.FUNCTION = pcallcontext.FUNCTION',
    'pmethodcapture.CALLSITE = pcallcontext.CALLSITE',
    'pmethodcapture.LEXICAL_CLASS = pcallcontext.LEXICAL_CLASS',
    'pmethodcapture.CALLED_CLASS = pcallcontext.CALLED_CLASS',
    '$method_capture_called_scope(S, porigin_site, pmethodcapture)',
    '$method_capture_bound_classes(S, pmethodcapture)',
    '$method_capture_certificate_valid(S, porigin_site, (pmethodcapture))',
    '$method_convert_valid(S, SCOPED_TARGET porigin_class porigin_method porigin_called n_target_receiver? poperand_selector, porigin_site, z)',
    *GUARDS,
    'S_after = $drive_steps(S[.COMPLETION = NORMAL], 1)',
    'S_after.CURRENT = S.CURRENT',
    'S_after.RESULT = KNOWN (POBJECT n_capture)',
    'S_after.OBJECTS[n_capture] = METHODCLOSURE porigin_method porigin_site porigin_class (pmethodcapture)',
    '$class_method_origin(S_after.CLASSES, porigin_method) = (pmethoddesc)',
    '$closure_scope_at(S_after.CLOSURESCOPES, n_capture) = (pclosurescope)',
    'pclosurescope.LEXICAL = pmethoddesc.OWNER',
    'pclosurescope.CALLED = porigin_class', 'pclosurescope.RECEIVER = eps',
    '$node_children(S_after, HOBJECT n_capture) = eps',
    '$method_capture_authorized(S_after, pmethoddesc, porigin_site, porigin_class, pclosurescope, (pmethodcapture))',
    '$closure_scope_row_valid(S_after, pclosurescope)', '$closure_callable(S_after, n_capture)',
    '$closure_state_valid(S_after)', '$call_descriptors_valid(S_after)',
    '$heap_valid($heap_graph(S_after))',
    '~$method_capture_certificate_valid(S_after, porigin_site, (pmethodcapture[.CALLSITE = eps]))',
    '~$method_capture_certificate_valid(S_after, porigin_site, (pmethodcapture[.CALLSITE = (porigin_site)]))',
    '~$method_capture_certificate_valid(S_after, porigin_site, (pmethodcapture[.FUNCTION = porigin_method]))',
    'pmethodcapture_bad = pmethodcapture[.CALLSITE = eps]',
    'S_bad = S_after[.OBJECTS = $object_set(S_after.OBJECTS, n_capture, METHODCLOSURE porigin_method porigin_site porigin_class (pmethodcapture_bad))]',
    '$target_function(S_bad, CLOSURE_TARGET n_capture) = (pmethoddesc.FUNCTION)',
    '$heap_valid($heap_graph(S_bad))',
    '~$closure_scope_row_valid(S_bad, pclosurescope)', '~$closure_state_valid(S_bad)',
    '~$call_descriptors_valid(S_bad)',
]
BINDING = [
    'pcallcontext.TARGET = CLOSURE_TARGET n_source',
    'S.OBJECTS[n_source] = REALCLOSURE pcallcontext.FUNCTION pitem* pstaticcell*',
    'pcallcontext.CALLSITE = (porigin_call)',
    'pcallcontext.CALLED_CLASS = (porigin_class)',
    'pcallcontext.RECEIVER = (n_producer_receiver)',
    '$closure_binding_at(S.CLOSUREBINDINGS, n_source) = (pclosurebinding)',
    'pclosurebinding.LEXICAL = pcallcontext.LEXICAL_CLASS',
    'pclosurebinding.CALLED = pcallcontext.CALLED_CLASS',
    'pclosurebinding.RECEIVER = pcallcontext.RECEIVER',
    '$closure_binding_source_valid(S, pclosurebinding)',
    '$closure_source_class(S, porigin_site) = pcallcontext.LEXICAL_CLASS',
    'porigin_called = porigin_class', 'n_target_receiver? = eps',
]
CLONE = ('S.TODO = (CALL_ARGS (CLOSURE_TARGET n_capture) eps 0 eps (porigin_call) z) :: ptask_tail* '
         '-- if S.OBJECTS[n_capture] = METHODCLOSURE porigin_method porigin_site porigin_class (pmethodcapture) '
         '-- if $closure_scope_at(S.CLOSURESCOPES, n_capture) = (pclosurescope)')
RETIRED_CLONE = [
    'n_capture = 4', 'pmethodcapture.CALLED_CLASS = (porigin_class)',
    'pclosurescope.CALLED = porigin_class', 'pclosurescope.RECEIVER = eps',
    '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
    'pclosurescope.LEXICAL = pmethoddesc.OWNER',
    '$lookup(S.ENV, $ptascii("bound")) = (n_bound)', 'S.STORE[n_bound] = DEFINED PNULL',
    '$lookup(S.ENV, $ptascii("c")) = (n_c)', 'S.STORE[n_c] = DEFINED PNULL',
    '$lookup(S.ENV, $ptascii("cb")) = (n_cb)', 'S.STORE[n_cb] = DEFINED PNULL',
    '$lookup(S.ENV, $ptascii("r")) = (n_r)', 'S.STORE[n_r] = DEFINED (PSTRING $ptascii("s"))',
    'S.OBJECTS[0] = INSTANCE porigin_class', '~((HOBJECT 0) <- S.ALLOCATIONS)',
    'S.OBJECTS[1] = REALCLOSURE pmethodcapture.FUNCTION pitem* pstaticcell*',
    '~((HOBJECT 1) <- S.ALLOCATIONS)', '~((HOBJECT 2) <- S.ALLOCATIONS)',
    '~((HOBJECT 3) <- S.ALLOCATIONS)', 'S.OBJECTS[3] = S.OBJECTS[n_capture]',
    '$clone_same_kind(S.OBJECTS[3], S.OBJECTS[n_capture])',
    '$node_children(S, HOBJECT n_capture) = eps',
    '$method_capture_called_scope(S, porigin_site, pmethodcapture)',
    '$method_capture_certificate_valid(S, porigin_site, (pmethodcapture))',
    '$method_capture_authorized(S, pmethoddesc, porigin_site, porigin_class, pclosurescope, (pmethodcapture))',
    *GUARDS,
    'pmethodcapture_bad = pmethodcapture[.CALLSITE = (porigin_site)]',
    'S_bad = S[.OBJECTS = $object_set(S.OBJECTS, n_capture, METHODCLOSURE porigin_method porigin_site porigin_class (pmethodcapture_bad))]',
    '~$clone_same_kind(S.OBJECTS[3], S_bad.OBJECTS[n_capture])',
    '~$closure_scope_row_valid(S_bad, pclosurescope)', '~$closure_state_valid(S_bad)',
    '~$call_descriptors_valid(S_bad)', '$heap_valid($heap_graph(S_bad))',
]
CASES = {
    'eps-lexical-keeps-called-class': {
        'source': SOURCES['eps-lexical-called-original'], 'stage': CONVERT,
        'checks': [
            *BINDING, 'pcallcontext.LEXICAL_CLASS = eps', *AFTER,
            'pmethodcapture_empty = pmethodcapture[.CALLED_CLASS = eps]',
            '$method_capture_bound_classes(S_after, pmethodcapture_empty)',
            '~$method_capture_called_scope(S_after, porigin_site, pmethodcapture_empty)',
            '~$method_capture_certificate_valid(S_after, porigin_site, (pmethodcapture_empty))',
            '~$method_capture_authorized(S_after, pmethoddesc, porigin_site, porigin_class, pclosurescope, eps)',
        ],
    },
    'nonempty-lexical-keeps-unrelated-called-class': {
        'source': SOURCES['nonempty-same-lexical-called-original'], 'stage': CONVERT,
        'checks': [
            *BINDING, 'pcallcontext.LEXICAL_CLASS = (porigin_lexical)',
            '$class_at(S.CLASSES, porigin_lexical) = (pclassdesc_lexical)',
            'pclassdesc_lexical.NAME = $ptascii("A")',
            '~$class_origin_matches(S, porigin_class, pclassdesc_lexical.NAME, |S.CLASSES|)',
            *AFTER,
            'pmethodcapture_same = pmethodcapture[.CALLED_CLASS = (porigin_lexical)]',
            '$method_capture_bound_classes(S_after, pmethodcapture_same)',
            '~$method_capture_called_scope(S_after, porigin_site, pmethodcapture_same)',
            '~$method_capture_certificate_valid(S_after, porigin_site, (pmethodcapture_same))',
            '~$method_capture_authorized(S_after, pmethoddesc, porigin_site, porigin_class, pclosurescope, eps)',
        ],
    },
    'eps-called-clone-after-producer-retirement': {
        'source': SOURCES['eps-lexical-called-clone'], 'stage': CLONE,
        'checks': [
            'pmethodcapture.LEXICAL_CLASS = eps',
            '$lookup(S.ENV, $ptascii("a")) = (n_a)', 'S.STORE[n_a] = DEFINED PNULL',
            *RETIRED_CLONE,
        ],
    },
    'nonempty-called-clone-after-producer-retirement': {
        'source': SOURCES['nonempty-same-lexical-called-clone'], 'stage': CLONE,
        'checks': [
            'pmethodcapture.LEXICAL_CLASS = (porigin_lexical)',
            'pmethodcapture.LEXICAL_CLASS =/= pmethodcapture.CALLED_CLASS',
            '$lookup(S.ENV, $ptascii("b")) = (n_b)', 'S.STORE[n_b] = DEFINED PNULL',
            *RETIRED_CLONE,
        ],
    },
    'named-method-keeps-source-owned-eps-authority': {
        'source': SOURCES['source-owned-method-keeps-eps-evidence'], 'stage': CONVERT,
        'checks': [
            'pcallcontext.LEXICAL_CLASS = (porigin_lexical)',
            'pcallcontext.CALLED_CLASS = (porigin_class)',
            '$class_method_origin(S.CLASSES, pcallcontext.FUNCTION) = (pmethoddesc_owner)',
            'pmethoddesc_owner.NAME = $ptascii("cap")',
            'pmethoddesc_owner.OWNER = porigin_lexical',
            '~$method_capture_template(S, pcallcontext.FUNCTION)',
            '$closure_source_class(S, porigin_site) = (porigin_lexical)',
            'porigin_lexical =/= porigin_class',
            'pmethodcapture_bad = {FUNCTION pcallcontext.FUNCTION, CALLSITE pcallcontext.CALLSITE, LEXICAL_CLASS pcallcontext.LEXICAL_CLASS, CALLED_CLASS pcallcontext.CALLED_CLASS}',
            '~$method_capture_called_scope(S, porigin_site, pmethodcapture_bad)',
            '$method_capture_current(S, porigin_site) = eps',
            '~$method_capture_certificate_valid(S, porigin_site, (pmethodcapture_bad))',
            '$method_convert_valid(S, SCOPED_TARGET porigin_class porigin_method porigin_called n_target_receiver? poperand_selector, porigin_site, z)',
            *GUARDS,
            'S_after = $drive_steps(S[.COMPLETION = NORMAL], 1)',
            'S_after.RESULT = KNOWN (POBJECT n_capture)',
            'S_after.OBJECTS[n_capture] = METHODCLOSURE porigin_method porigin_site porigin_class eps',
            '$closure_scope_at(S_after.CLOSURESCOPES, n_capture) = (pclosurescope)',
            'pclosurescope.LEXICAL = porigin_lexical', 'pclosurescope.CALLED = porigin_class',
            'pclosurescope.RECEIVER = eps', '$node_children(S_after, HOBJECT n_capture) = eps',
            '$closure_state_valid(S_after)', '$call_descriptors_valid(S_after)',
            '$heap_valid($heap_graph(S_after))',
            'S_bad = S_after[.OBJECTS = $object_set(S_after.OBJECTS, n_capture, METHODCLOSURE porigin_method porigin_site porigin_class (pmethodcapture_bad))]',
            '~$closure_scope_row_valid(S_bad, pclosurescope)', '~$closure_state_valid(S_bad)',
            '~$call_descriptors_valid(S_bad)', '$heap_valid($heap_graph(S_bad))',
        ],
    },
    'fixed-global-literal-rejects-invented-called-class': {
        'source': SOURCES['fixed-global-literal-has-no-called-class'],
        'stage': ('S.TODO = (CALL_ARGS (CLOSURE_TARGET n_source) eps 0 eps (porigin_call) z) :: ptask_tail* '
                  '-- if S.OBJECTS[n_source] = REALCLOSURE porigin_template pitem* pstaticcell*'),
        'checks': [
            'S.CURRENT = eps', 'S.FRAMES = eps',
            '$closure_source_class(S, porigin_template) = eps',
            '$target_lexical_class(S, CLOSURE_TARGET n_source) = eps',
            '$target_called_class(S, CLOSURE_TARGET n_source) = eps',
            '$origin_child((porigin_call), [PCFIELD 0]) = (porigin_template)',
            'porigin_template = PORIGIN n_unit pcpath_template',
            'porigin_site = PORIGIN n_unit (pcpath_template ++ [PCFIELD 6, PCINDEX 0, PCFIELD 0])',
            '$origin_node(S.SOURCES, porigin_site) = (NExprStaticCall (NName (BYTES text_class) metadata_class) phpType20 (SEQUENCE phpType7*) metadata)',
            '$ptlc($base64(text_class)) = $ptascii("static")', '$ppfirstclass(phpType7*)',
            '$class_named(S.CLASSNAMES, $ptascii("a")) = (porigin_class)',
            '$class_at(S.CLASSES, porigin_class) = (pclassdesc)',
            '$method_named(pclassdesc.METHODS, $ptascii("f")) = (pmethoddesc)',
            'pmethoddesc.STATIC', 'pmethoddesc.VISIBILITY = PROPERTY_PUBLIC',
            'pmethodcapture_bad = {FUNCTION porigin_template, CALLSITE (porigin_call), LEXICAL_CLASS eps, CALLED_CLASS (porigin_class)}',
            '$method_capture_template(S, porigin_template)',
            '$method_capture_bound_classes(S, pmethodcapture_bad)',
            '$method_capture_called_scope(S, porigin_site, pmethodcapture_bad)',
            '$method_accessible(S, pmethoddesc, eps)',
            '~$method_capture_literal_scope(S, pmethodcapture_bad, porigin_template)',
            '~$method_capture_literal_valid(S, pmethodcapture_bad, porigin_template, false)',
            '~$method_capture_invocation_valid(S, pmethodcapture_bad, porigin_call)',
            '~$method_capture_certificate_valid(S, porigin_site, (pmethodcapture_bad))',
            *GUARDS,
            'n_capture = |S.OBJECTS|',
            'pclosurescope_bad = {OBJECT n_capture, LEXICAL pmethoddesc.OWNER, CALLED porigin_class, RECEIVER eps, CREATION eps}',
            'S_bad = S[.OBJECTS = S.OBJECTS ++ [METHODCLOSURE pmethoddesc.FUNCTION.ORIGIN porigin_site porigin_class (pmethodcapture_bad)]][.ALLOCATIONS = S.ALLOCATIONS ++ [HOBJECT n_capture]][.CLOSURESCOPES = S.CLOSURESCOPES ++ [pclosurescope_bad]][.RESULT = KNOWN (POBJECT n_capture)]',
            '$method_capture_in_scope(S_bad, pmethoddesc, porigin_site, porigin_class, pclosurescope_bad, eps, (porigin_class))',
            '$target_function(S_bad, CLOSURE_TARGET n_capture) = (pmethoddesc.FUNCTION)',
            '$node_children(S_bad, HOBJECT n_capture) = eps', '$heap_valid($heap_graph(S_bad))',
            '~$closure_scope_row_valid(S_bad, pclosurescope_bad)', '~$closure_state_valid(S_bad)',
            '~$call_descriptors_valid(S_bad)',
        ],
    },
    'fixed-class-literal-rejects-unrelated-called-class': {
        'source': SOURCES['fixed-class-literal-inherits-called-descendant'], 'stage': CONVERT,
        'checks': [
            'pcallcontext.LEXICAL_CLASS = (porigin_lexical)',
            'pcallcontext.CALLED_CLASS = (porigin_class)',
            '$class_at(S.CLASSES, porigin_lexical) = (pclassdesc_lexical)',
            'pclassdesc_lexical.NAME = $ptascii("A")',
            '$class_origin_matches(S, porigin_class, pclassdesc_lexical.NAME, |S.CLASSES|)',
            'pcallcontext.CALLSITE = (porigin_call)',
            '$origin_child((porigin_call), [PCFIELD 0]) = (pcallcontext.FUNCTION)',
            '$closure_nearest_owner(S, $closure_creation_owners($all_functions(S), porigin_call), eps) = (porigin_owner)',
            '$class_method_origin(S.CLASSES, porigin_owner) = (pmethoddesc_owner)',
            'pmethoddesc_owner.STATIC', '~$method_capture_template(S, porigin_owner)',
            '$method_capture_current(S, porigin_site) = (pmethodcapture)',
            'pmethodcapture.FUNCTION = pcallcontext.FUNCTION',
            'pmethodcapture.CALLSITE = pcallcontext.CALLSITE',
            'pmethodcapture.LEXICAL_CLASS = pcallcontext.LEXICAL_CLASS',
            'pmethodcapture.CALLED_CLASS = pcallcontext.CALLED_CLASS',
            '$method_capture_called_scope(S, porigin_site, pmethodcapture)',
            '$method_capture_literal_scope(S, pmethodcapture, pmethodcapture.FUNCTION)',
            '$method_capture_certificate_valid(S, porigin_site, (pmethodcapture))',
            '$method_convert_valid(S, SCOPED_TARGET porigin_class porigin_method porigin_called n_target_receiver? poperand_selector, porigin_site, z)',
            *GUARDS,
            '$class_named(S.CLASSNAMES, $ptascii("b")) = (porigin_b)',
            '$class_at(S.CLASSES, porigin_b) = (pclassdesc_b)',
            '$method_named(pclassdesc_b.METHODS, $ptascii("f")) = (pmethoddesc_b)',
            'pmethoddesc_b.STATIC', 'pmethoddesc_b.VISIBILITY = PROPERTY_PUBLIC',
            '~$class_origin_matches(S, porigin_b, pclassdesc_lexical.NAME, |S.CLASSES|)',
            'pmethodcapture_b = pmethodcapture[.CALLED_CLASS = (porigin_b)]',
            '$method_capture_bound_classes(S, pmethodcapture_b)',
            '$method_capture_called_scope(S, porigin_site, pmethodcapture_b)',
            '~$method_capture_literal_scope(S, pmethodcapture_b, pmethodcapture.FUNCTION)',
            '~$method_capture_invocation_valid(S, pmethodcapture_b, porigin_call)',
            '~$method_capture_certificate_valid(S, porigin_site, (pmethodcapture_b))',
            '$method_accessible(S, pmethoddesc_b, (porigin_lexical))',
            'n_capture = |S.OBJECTS|',
            'pclosurescope_b = {OBJECT n_capture, LEXICAL pmethoddesc_b.OWNER, CALLED porigin_b, RECEIVER eps, CREATION eps}',
            '$method_capture_in_scope(S, pmethoddesc_b, porigin_site, porigin_b, pclosurescope_b, (porigin_lexical), (porigin_b))',
            'S_bad_b = S[.OBJECTS = S.OBJECTS ++ [METHODCLOSURE pmethoddesc_b.FUNCTION.ORIGIN porigin_site porigin_b (pmethodcapture_b)]][.ALLOCATIONS = S.ALLOCATIONS ++ [HOBJECT n_capture]][.CLOSURESCOPES = S.CLOSURESCOPES ++ [pclosurescope_b]][.RESULT = KNOWN (POBJECT n_capture)]',
            '$target_function(S_bad_b, CLOSURE_TARGET n_capture) = (pmethoddesc_b.FUNCTION)',
            '$node_children(S_bad_b, HOBJECT n_capture) = eps',
            '$method_convert_valid(S_bad_b, SCOPED_TARGET porigin_class porigin_method porigin_called n_target_receiver? poperand_selector, porigin_site, z)',
            '$heap_valid($heap_graph(S_bad_b))',
            '~$closure_scope_row_valid(S_bad_b, pclosurescope_b)', '~$closure_state_valid(S_bad_b)',
            '~$call_descriptors_valid(S_bad_b)',
        ],
    },
}

if __name__ == '__main__':
    protocol.run(CASES, (Path(__file__), CATALOGUE, ROOT / 'tests/semantics/profile.json',
                        ROOT / '.tools/request-clock.so'))
