#!/usr/bin/env python3
"""Source-derived capture authorization, retirement and forgery checks."""
from pathlib import Path
import json

import closure_call_protocol as protocol
import method_class_selector_protocol as methods

ROOT = Path(__file__).resolve().parents[2]
CATALOGUE = ROOT / 'tests/semantics/rebound_method_capture_cases.json'
SOURCES = {row['id']: row['source'] for row in json.loads(CATALOGUE.read_text())}
GUARDS = ['$call_descriptors_valid(S)', '$closure_state_valid(S)', '$heap_valid($heap_graph(S))']
CONVERT = ('S.TODO = (METHOD_CONVERT (STATIC_METHOD_TARGET porigin_class porigin_method) '
           'porigin_site z) :: ptask_tail* -- if S.CURRENT = (pcallcontext)')
AFTER = [
    '$call_task_valid(S, METHOD_CONVERT (STATIC_METHOD_TARGET porigin_class porigin_method) porigin_site z)',
    '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
    'pmethoddesc.STATIC', '$closure_source_class(S, porigin_site) = eps',
    'pcallcontext.LEXICAL_CLASS = (porigin_class)',
    'pcallcontext.CALLED_CLASS = (porigin_class)',
    'pcallcontext.CALLSITE = (porigin_call)',
    '$method_capture_current(S, porigin_site) = (pmethodcapture)',
    'pmethodcapture.FUNCTION = pcallcontext.FUNCTION',
    'pmethodcapture.CALLSITE = pcallcontext.CALLSITE',
    'pmethodcapture.LEXICAL_CLASS = pcallcontext.LEXICAL_CLASS',
    'pmethodcapture.CALLED_CLASS = pcallcontext.CALLED_CLASS',
    '$method_capture_certificate_valid(S, porigin_site, (pmethodcapture))',
    *GUARDS,
    'S_after = $drive_steps(S[.COMPLETION = NORMAL], 1)',
    'S_after.CURRENT = S.CURRENT',
    'S_after.RESULT = KNOWN (POBJECT n_capture)',
    'S_after.OBJECTS[n_capture] = METHODCLOSURE porigin_method porigin_site porigin_class (pmethodcapture)',
    '$closure_scope_at(S_after.CLOSURESCOPES, n_capture) = (pclosurescope)',
    'pclosurescope.LEXICAL = pmethoddesc.OWNER',
    'pclosurescope.CALLED = porigin_class', 'pclosurescope.RECEIVER = eps',
    '$node_children(S_after, HOBJECT n_capture) = eps',
    '$method_capture_authorized(S_after, pmethoddesc, porigin_site, porigin_class, pclosurescope, (pmethodcapture))',
    '$closure_scope_row_valid(S_after, pclosurescope)',
    '$closure_state_valid(S_after)', '$closure_callable(S_after, n_capture)',
    '$call_descriptors_valid(S_after)', '$heap_valid($heap_graph(S_after))',
]
CASES = {
    'private-created-certificate': {
        'source': SOURCES['rebound-private-producer-lifetime'], 'stage': CONVERT,
        'checks': [
            *AFTER, 'pmethoddesc.VISIBILITY = PROPERTY_PRIVATE',
            '~$method_capture_authorized(S_after, pmethoddesc, porigin_site, porigin_class, pclosurescope, eps)',
            'S_bad = S_after[.OBJECTS = $object_set(S_after.OBJECTS, n_capture, METHODCLOSURE porigin_method porigin_site porigin_class eps)]',
            '~$closure_scope_row_valid(S_bad, pclosurescope)', '~$closure_callable(S_bad, n_capture)',
            '~$closure_state_valid(S_bad)', '~$call_descriptors_valid(S_bad)',
            '$heap_valid($heap_graph(S_bad))',
            '~$method_capture_certificate_valid(S_after, porigin_site, (pmethodcapture[.CALLSITE = eps]))',
            '~$method_capture_certificate_valid(S_after, porigin_site, (pmethodcapture[.FUNCTION = porigin_method]))',
            '~$method_capture_certificate_valid(S_after, porigin_method, (pmethodcapture))',
            '~$method_capture_certificate_valid(S_after, porigin_site, (pmethodcapture[.CALLSITE = (porigin_site)]))',
            '~$method_capture_authorized(S_after, pmethoddesc, porigin_site, porigin_class, pclosurescope, (pmethodcapture[.LEXICAL_CLASS = eps]))',
            '~$method_capture_authorized(S_after, pmethoddesc, porigin_site, porigin_class, pclosurescope, (pmethodcapture[.CALLED_CLASS = eps]))',
        ],
    },
    'protected-clone-after-producer-retirement': {
        'source': SOURCES['rebound-protected-direct-clone'],
        'stage': ('S.TODO = (CALL_ARGS (CLOSURE_TARGET n_capture) eps 0 eps (porigin_call) z) :: ptask_tail* '
                  '-- if S.OBJECTS[n_capture] = METHODCLOSURE porigin_method porigin_site porigin_class (pmethodcapture) '
                  '-- if $closure_scope_at(S.CLOSURESCOPES, n_capture) = (pclosurescope)'),
        'checks': [
            '$class_named(S.CLASSNAMES, $ptascii("a")) = (porigin_a)',
            '$class_named(S.CLASSNAMES, $ptascii("p")) = (porigin_p)',
            'pmethodcapture.LEXICAL_CLASS = (porigin_a)', 'pmethodcapture.CALLED_CLASS = (porigin_a)',
            'pclosurescope.LEXICAL = porigin_p', 'pclosurescope.CALLED = porigin_a',
            'pclosurescope.RECEIVER = eps', 'porigin_a =/= porigin_p',
            '$lookup(S.ENV, $ptascii("a")) = (n_a)', 'S.STORE[n_a] = DEFINED PNULL',
            '$lookup(S.ENV, $ptascii("c")) = (n_c)', 'S.STORE[n_c] = DEFINED PNULL',
            '$lookup(S.ENV, $ptascii("cb")) = (n_cb)', 'S.STORE[n_cb] = DEFINED PNULL',
            '$lookup(S.ENV, $ptascii("r")) = (n_r)', 'S.STORE[n_r] = DEFINED (PSTRING $ptascii("s"))',
            'S.OBJECTS[0] = INSTANCE porigin_a', '~((HOBJECT 0) <- S.ALLOCATIONS)',
            'S.OBJECTS[1] = REALCLOSURE pmethodcapture.FUNCTION pitem* pstaticcell*',
            '~((HOBJECT 1) <- S.ALLOCATIONS)', '~((HOBJECT 2) <- S.ALLOCATIONS)',
            'S.OBJECTS[2] = S.OBJECTS[n_capture]',
            '$clone_same_kind(S.OBJECTS[2], S.OBJECTS[n_capture])',
            '$node_children(S, HOBJECT n_capture) = eps',
            '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
            'pmethoddesc.VISIBILITY = PROPERTY_PROTECTED',
            '$method_capture_authorized(S, pmethoddesc, porigin_site, porigin_class, pclosurescope, (pmethodcapture))',
            '~$method_capture_authorized(S, pmethoddesc, porigin_site, porigin_class, pclosurescope, eps)',
            '~$method_capture_authorized(S, pmethoddesc, porigin_site, porigin_class, pclosurescope, (pmethodcapture[.LEXICAL_CLASS = (porigin_p)]))',
            *GUARDS,
            'pmethodcapture_bad = pmethodcapture[.CALLSITE = (porigin_site)]',
            'S_bad = S[.OBJECTS = $object_set(S.OBJECTS, n_capture, METHODCLOSURE porigin_method porigin_site porigin_class (pmethodcapture_bad))]',
            '~$clone_same_kind(S.OBJECTS[2], S_bad.OBJECTS[n_capture])',
            '~$closure_scope_row_valid(S_bad, pclosurescope)', '~$closure_state_valid(S_bad)',
            '~$call_descriptors_valid(S_bad)', '$heap_valid($heap_graph(S_bad))',
        ],
    },
    'fixed-newthis-and-literal-invocation': {
        'source': SOURCES['rebound-fixed-literal-and-newthis'], 'stage': CONVERT,
        'checks': [
            *AFTER,
            '$class_named(S.CLASSNAMES, $ptascii("b")) = (porigin_b)',
            '$class_named(S.CLASSNAMES, $ptascii("p")) = (porigin_p)',
            'pmethoddesc.OWNER = porigin_p',
            '$method_accessible(S, pmethoddesc, (porigin_b))',
            'pmethodcapture_bad = pmethodcapture[.LEXICAL_CLASS = (porigin_b)][.CALLED_CLASS = (porigin_b)]',
            '$method_capture_in_scope(S_after, pmethoddesc, porigin_site, porigin_b, pclosurescope[.CALLED = porigin_b], (porigin_b), (porigin_b))',
            '~$method_capture_certificate_valid(S_after, porigin_site, (pmethodcapture_bad))',
            '~$method_capture_authorized(S_after, pmethoddesc, porigin_site, porigin_b, pclosurescope[.CALLED = porigin_b], (pmethodcapture_bad))',
            '~$method_capture_authorized(S_after, pmethoddesc, porigin_site, porigin_class, pclosurescope, (pmethodcapture_bad))',
            'porigin_other = PORIGIN 0 ([PCINDEX 4, PCFIELD 0, PCFIELD 1])',
            '$origin_node(S.SOURCES, porigin_other) = (NExprMethodCall expression_other phpType20_other phpType6_other metadata_other)',
            '$origin_child((porigin_other), [PCFIELD 0]) = (porigin_template_other)',
            '$method_capture_template(S, porigin_template_other)',
            'porigin_template_other =/= pmethodcapture.FUNCTION',
            '~$method_capture_certificate_valid(S_after, porigin_site, (pmethodcapture[.CALLSITE = (porigin_other)]))',
            'porigin_nonclosure_method = PORIGIN 0 ([PCINDEX 7, PCFIELD 1, PCINDEX 0, PCFIELD 0])',
            '$origin_node(S.SOURCES, porigin_nonclosure_method) = (NExprMethodCall expression_new phpType20_new phpType6_new metadata_new)',
            '$method_capture_incompatible(expression_new)',
            '~$method_capture_invocation_valid(S_after, pmethodcapture, porigin_nonclosure_method)',
            'porigin_nonclosure_call = PORIGIN 0 ([PCINDEX 7, PCFIELD 1, PCINDEX 1, PCFIELD 0])',
            '$dynamic_site(S_after, (porigin_nonclosure_call))',
            '~$method_capture_invocation_valid(S_after, pmethodcapture, porigin_nonclosure_call)',
            'porigin_literal_name = PORIGIN 0 ([PCINDEX 7, PCFIELD 1, PCINDEX 2, PCFIELD 0])',
            '$origin_node(S.SOURCES, porigin_literal_name) = (NExprMethodCall expression_name (NScalarString (BYTES text_name) metadata_member) phpType6_name metadata_name)',
            '$parser_literal(NScalarString (BYTES text_name) metadata_member) = (PSTRING $ptascii("other"))',
            '~$method_capture_source_name(NScalarString (BYTES text_name) metadata_member, $ptascii("call"))',
            '~$method_capture_source_name(NScalarString (BYTES text_name) metadata_member, $ptascii("__invoke"))',
            '~$method_capture_invocation_valid(S_after, pmethodcapture, porigin_literal_name)',
        ],
    },
    'fixed-global-literal-rejects-invented-scope': {
        'source': SOURCES['capture-fixed-global-literal'],
        'stage': ('S.TODO = (METHOD_CONVERT (SCOPED_TARGET porigin_class porigin_method porigin_called '
                  'n_receiver? poperand_selector) porigin_site z) :: ptask_tail* -- if S.CURRENT = (pcallcontext)'),
        'checks': [
            'pcallcontext.LEXICAL_CLASS = eps', 'pcallcontext.CALLED_CLASS = eps',
            'pcallcontext.CALLSITE = (porigin_call)', '$closure_source_class(S, porigin_site) = eps',
            '$method_capture_current(S, porigin_site) = eps',
            '$method_convert_valid(S, SCOPED_TARGET porigin_class porigin_method porigin_called n_receiver? poperand_selector, porigin_site, z)',
            *GUARDS,
            'pmethodcapture_bad = {FUNCTION pcallcontext.FUNCTION, CALLSITE pcallcontext.CALLSITE, LEXICAL_CLASS (porigin_class), CALLED_CLASS (porigin_class)}',
            '$method_capture_template(S, pcallcontext.FUNCTION)',
            '$origin_child((porigin_call), [PCFIELD 0]) = (pcallcontext.FUNCTION)',
            '~$method_capture_literal_valid(S, pmethodcapture_bad, pcallcontext.FUNCTION, false)',
            '~$method_capture_certificate_valid(S, porigin_site, (pmethodcapture_bad))',
            'S_after = $drive_steps(S[.COMPLETION = NORMAL], 1)',
            'S_after.RESULT = KNOWN (POBJECT n_capture)',
            'S_after.OBJECTS[n_capture] = METHODCLOSURE porigin_method porigin_site porigin_class eps',
            '$closure_state_valid(S_after)', '$call_descriptors_valid(S_after)',
            '$heap_valid($heap_graph(S_after))',
        ],
    },
    'static-bound-template-class-channels': {
        'source': SOURCES['rebound-bound-static-private'],
        'stage': ('S.TODO = (METHOD_CONVERT (SCOPED_TARGET porigin_class porigin_method porigin_called '
                  'n_receiver? poperand_selector) porigin_site z) :: ptask_tail* -- if S.CURRENT = (pcallcontext)'),
        'checks': [
            'pcallcontext.TARGET = CLOSURE_TARGET n_source',
            'pcallcontext.RECEIVER = eps', 'pcallcontext.LEXICAL_CLASS = (porigin_class)',
            'pcallcontext.CALLED_CLASS = (porigin_class)',
            '$function_at(S.CLOSURETEMPLATES, pcallcontext.FUNCTION) = (pfunction)',
            '$closure_static(S, pfunction)', '$method_capture_current(S, porigin_site) = (pmethodcapture)',
            '$method_capture_certificate_valid(S, porigin_site, (pmethodcapture))',
            '~$method_capture_bound_classes(S, pmethodcapture[.CALLED_CLASS = eps])',
            *GUARDS,
            'S_after = $drive_steps(S[.COMPLETION = NORMAL], 1)',
            'S_after.RESULT = KNOWN (POBJECT n_capture)',
            'S_after.OBJECTS[n_capture] = METHODCLOSURE porigin_method porigin_site porigin_class (pmethodcapture)',
            '$node_children(S_after, HOBJECT n_capture) = eps',
            '$closure_state_valid(S_after)', '$call_descriptors_valid(S_after)',
            '$heap_valid($heap_graph(S_after))',
        ],
    },
    'self-keyword-keeps-executed-called-class': {
        'source': SOURCES['rebound-protected-self-clone'],
        'stage': ('S.TODO = (METHOD_CONVERT (SCOPED_TARGET porigin_class porigin_method porigin_called '
                  'n_receiver? poperand_selector) porigin_site z) :: ptask_tail* -- if S.CURRENT = (pcallcontext)'),
        'checks': [
            '$method_capture_current(S, porigin_site) = (pmethodcapture)',
            'pmethodcapture.LEXICAL_CLASS = (porigin_class)',
            'pmethodcapture.CALLED_CLASS = (porigin_called)',
            '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
            'pmethoddesc.OWNER = porigin_p', 'porigin_p =/= porigin_called',
            '$method_capture_certificate_valid(S, porigin_site, (pmethodcapture))', *GUARDS,
            'S_after = $drive_steps(S[.COMPLETION = NORMAL], 1)',
            'S_after.RESULT = KNOWN (POBJECT n_capture)',
            'S_after.OBJECTS[n_capture] = METHODCLOSURE porigin_method porigin_site porigin_class (pmethodcapture)',
            '$closure_scope_at(S_after.CLOSURESCOPES, n_capture) = (pclosurescope)',
            'pclosurescope.LEXICAL = porigin_p', 'pclosurescope.CALLED = porigin_called',
            '$method_capture_authorized(S_after, pmethoddesc, porigin_site, porigin_class, pclosurescope, (pmethodcapture))',
            '~$method_capture_authorized(S_after, pmethoddesc, porigin_site, porigin_class, pclosurescope[.CALLED = porigin_p], (pmethodcapture))',
            '$closure_state_valid(S_after)', '$call_descriptors_valid(S_after)',
            '$heap_valid($heap_graph(S_after))',
        ],
    },
    'public-capture-rejects-missing-source-context': {
        'source': SOURCES['capture-public-fixed-source-context'],
        'stage': ('S.TODO = (METHOD_CONVERT (SCOPED_TARGET porigin_class porigin_method porigin_called '
                  'n_receiver? poperand_selector) porigin_site z) :: ptask_tail* -- if S.CURRENT = (pcallcontext)'),
        'checks': [
            '$closure_source_class(S, porigin_site) = (porigin_class)',
            '$method_capture_current(S, porigin_site) = eps',
            '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
            'pmethoddesc.VISIBILITY = PROPERTY_PUBLIC', *GUARDS,
            'S_main = S[.CURRENT = eps][.FRAMES = eps]',
            '$call_current_valid(S_main)',
            '$call_selected_valid(S_main, SCOPED_TARGET porigin_class porigin_method porigin_called n_receiver? poperand_selector, (porigin_site))',
            '$call_line_valid(S_main, (porigin_site), z)',
            '$method_capture_current(S_main, porigin_site) = eps',
            '~$method_capture_creation_context_valid(S_main, porigin_site)',
            '~$method_convert_valid(S_main, SCOPED_TARGET porigin_class porigin_method porigin_called n_receiver? poperand_selector, porigin_site, z)',
        ],
    },
    'bound-unrelated-lexical-and-called-classes': {
        'source': SOURCES['rebound-bound-unrelated-called-class'],
        'stage': ('S.TODO = (METHOD_CONVERT (SCOPED_TARGET porigin_class porigin_method porigin_called '
                  'n_receiver? poperand_selector) porigin_site z) :: ptask_tail* -- if S.CURRENT = (pcallcontext)'),
        'checks': [
            '$class_named(S.CLASSNAMES, $ptascii("a")) = (porigin_a)',
            '$class_named(S.CLASSNAMES, $ptascii("b")) = (porigin_b)',
            'porigin_class = porigin_b', 'porigin_called = porigin_b',
            'pcallcontext.LEXICAL_CLASS = (porigin_a)', 'pcallcontext.CALLED_CLASS = (porigin_b)',
            '~$class_origin_matches(S, porigin_b, $ptascii("A"), |S.CLASSES|)',
            '$method_capture_current(S, porigin_site) = (pmethodcapture)',
            '$method_capture_bound_classes(S, pmethodcapture)',
            '$method_capture_certificate_valid(S, porigin_site, (pmethodcapture))', *GUARDS,
            'S_after = $drive_steps(S[.COMPLETION = NORMAL], 1)',
            'S_after.RESULT = KNOWN (POBJECT n_capture)',
            'S_after.OBJECTS[n_capture] = METHODCLOSURE porigin_method porigin_site porigin_class (pmethodcapture)',
            '$closure_scope_at(S_after.CLOSURESCOPES, n_capture) = (pclosurescope)',
            'pclosurescope.LEXICAL = porigin_b', 'pclosurescope.CALLED = porigin_b',
            '$node_children(S_after, HOBJECT n_capture) = eps',
            '$class_method_origin(S.CLASSES, porigin_method) = (pmethoddesc)',
            '$method_capture_authorized(S_after, pmethoddesc, porigin_site, porigin_class, pclosurescope, (pmethodcapture))',
            '$closure_state_valid(S_after)', '$call_descriptors_valid(S_after)',
            '$heap_valid($heap_graph(S_after))',
        ],
    },
    'fixed-computed-member-rejects-other-private-method': {
        'source': SOURCES['rebound-fixed-computed-member'], 'stage': CONVERT,
        'checks': [
            *AFTER,
            '$class_at(S.CLASSES, porigin_class) = (pclassdesc)',
            '$method_named(pclassdesc.METHODS, $ptascii("g")) = (pmethoddesc_g)',
            'pmethoddesc_g.STATIC', 'pmethoddesc_g.VISIBILITY = PROPERTY_PRIVATE',
            '$method_class_selected(S, porigin_class, $ptascii("g"), (porigin_class)) = (pmethoddesc_g)',
            '$method_accessible(S, pmethoddesc_g, (porigin_class))',
            '$call_selected_valid(S, STATIC_METHOD_TARGET porigin_class pmethoddesc_g.FUNCTION.ORIGIN, (porigin_site))',
            '~$method_capture_site(S, porigin_site, pmethoddesc_g)',
            '~$method_convert_valid(S, STATIC_METHOD_TARGET porigin_class pmethoddesc_g.FUNCTION.ORIGIN, porigin_site, z)',
            'S_bad = S_after[.OBJECTS = $object_set(S_after.OBJECTS, n_capture, METHODCLOSURE pmethoddesc_g.FUNCTION.ORIGIN porigin_site porigin_class (pmethodcapture))]',
            '$target_function(S_bad, CLOSURE_TARGET n_capture) = (pmethoddesc_g.FUNCTION)',
            '~$method_capture_authorized(S_bad, pmethoddesc_g, porigin_site, porigin_class, pclosurescope, (pmethodcapture))',
            '~$closure_scope_row_valid(S_bad, pclosurescope)', '~$closure_state_valid(S_bad)',
            '~$call_descriptors_valid(S_bad)', '$heap_valid($heap_graph(S_bad))',
        ],
    },
    'fixed-private-parent-conversion': methods.CASES['static-private-first-class-conversion'],
    'fixed-method-saved-instance': methods.CASES['captured-method-saved-instance'],
}

if __name__ == '__main__':
    protocol.run(CASES, (Path(__file__), CATALOGUE, Path(methods.__file__), ROOT / '.tools/request-clock.so'))
