"""Source-derived diagnostic continuations retain selection and conversion."""

CASES = [
    ('estrict-dispatch-protocol', 'estrict-runtime-repeat-dead-branch', '''true
  -- if S.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*
  -- if perrorcall.RESUME = DEPRECATED_CONSTANT_RESULT pdeprecatedconstant''', [
        'S.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = DEPRECATED_CONSTANT_RESULT pdeprecatedconstant',
        '$call_descriptors_valid(S)',
        '$deprecated_constant_valid(S, pdeprecatedconstant)',
        '$error_call_valid(S, perrorcall)',
        'S.ORIGIN = (pdeprecatedconstant.SITE)',
        'perrorcall.LEVEL = 8192',
        'perrorcall.LINE = 4',
        'perrorcall.MESSAGE = $deprecated_constant_message()',
        'pdeprecatedconstant.PREFIX = 0',
        '$deprecated_constant_selected(S, pdeprecatedconstant.SITE)',
        '$compiled_read(S, pdeprecatedconstant.SITE) = eps',
        '$deprecated_constant_active(S)',
        '$deprecated_constant_active_tasks(S.TODO)',
        '~$deprecated_constant_active($initial_state(NORMAL))',
        '~$deprecated_constant_valid(S[.CODE = eps], pdeprecatedconstant)',
        '~$deprecated_constant_valid(S[.ORIGIN = eps], pdeprecatedconstant)',
        '~$deprecated_constant_valid(S, pdeprecatedconstant[.LINE = 1])',
        '~$deprecated_constant_valid(S, pdeprecatedconstant[.PREFIX = 1])',
        '~$error_call_valid(S, perrorcall[.LEVEL = 512])',
        '~$error_call_valid(S, perrorcall[.MESSAGE = eps])',
        '~$error_call_valid(S, perrorcall[.LINE = 1])',
        '~$error_call_valid(S, perrorcall[.SITE = PORIGIN 0 eps])',
        '~$error_call_valid(S, perrorcall[.EVENT = OUTPUT eps])',
        'S_recursive = $deprecated_constant_start(S, pdeprecatedconstant.SITE, ptask_tail*)',
        'S_recursive.RESULT = KNOWN (PINT 2048)',
        'S_recursive.EVENTS = S.EVENTS',
        'S_recursive.TODO = ptask_tail*',
        'S_done = $drive(S, 1500)',
        'S_done.COMPLETION = NORMAL',
        '~$deprecated_constant_active(S_done)',
        'S_done.REPORTING = 30719',
        'S_done.REPORTINGINI = $ptascii("30719")',
    ]),
    ('reporting-lossy-dispatch-protocol', 'reporting-lossy-handler-postconversion-old', '''true
  -- if S.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*
  -- if perrorcall.RESUME = REPORTING_LONG_RESULT pconfigcall i''', [
        'S.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = REPORTING_LONG_RESULT pconfigcall i',
        '$call_descriptors_valid(S)',
        '$config_invoke_valid(S, pconfigcall)',
        '$reporting_long_valid(S, pconfigcall, i)',
        '$error_call_valid(S, perrorcall)',
        'S.FILEINCLUDEPATH = eps',
        'S.FILECWD = eps',
        'i = 3',
        'pconfigcall.KIND = INTRINSIC_ERROR_REPORTING',
        'pconfigcall.SENT = [NAMED_SENT (KNOWN (PSTRING $ptascii("3.5")))]',
        'perrorcall.LEVEL = 8192',
        'perrorcall.LINE = 3',
        'perrorcall.MESSAGE = $ptascii("Implicit conversion from float-string ") ++ [34] ++ $ptascii("3.5") ++ [34] ++ $ptascii(" to int loses precision")',
        '$reporting_lossy_value(PINT 3) = eps',
        '$reporting_lossy_value(PSTRING $ptascii("3")) = eps',
        '$reporting_lossy_value(PSTRING $ptascii("3.0")) = eps',
        '$reporting_lossy_value(PSTRING ($ptascii("3.5") ++ [0])) = eps',
        '~$reporting_long_valid(S[.CODE = eps], pconfigcall, i)',
        '~$reporting_long_valid(S[.ORIGIN = eps], pconfigcall, i)',
        '~$reporting_long_valid(S, pconfigcall[.KIND = INTRINSIC_TRIGGER_ERROR], i)',
        '~$reporting_long_valid(S, pconfigcall[.LINE = 1], i)',
        '~$reporting_long_valid(S, pconfigcall, 4)',
        '~$error_call_valid(S, perrorcall[.LEVEL = 512])',
        '~$error_call_valid(S, perrorcall[.MESSAGE = eps])',
        '~$error_call_valid(S, perrorcall[.LINE = 1])',
        '~$error_call_valid(S, perrorcall[.EVENT = OUTPUT eps])',
        'S_equal = $reporting_long_finish(S[.REPORTING = 3][.REPORTINGINI = $ptascii("3") ++ [0] ++ $ptascii("kept")], 3)',
        'S_equal.RESULT = KNOWN (PINT 3)',
        'S_equal.REPORTINGINI = $ptascii("3") ++ [0] ++ $ptascii("kept")',
        'S_changed = $reporting_long_finish(S[.REPORTING = 512], 3)',
        'S_changed.RESULT = KNOWN (PINT 512)',
        'S_changed.REPORTING = 3',
        'S_changed.REPORTINGINI = $ptascii("3")',
        'S_changed.REPORTINGMODIFIED',
        'S_done = $drive(S, 1500)',
        'S_done.COMPLETION = NORMAL',
        'S_done.REPORTING = 3',
        'S_done.REPORTINGINI = $ptascii("3")',
        'S_done.REPORTINGMODIFIED',
    ]),
]
