"""Raw reporting bytes and modified-entry state keep separate live meanings."""

SOURCE_ID = 'reporting-raw-get-set-restore'
STAGE = '''true
  -- if S.TODO = (CONFIG_INVOKE pconfigcall) :: ptask_tail*
  -- if pconfigcall.KIND = INTRINSIC_INI_SET
  -- if $config_reporting_selected(pconfigcall)'''

CHECKS = [
    'S_initial_reporting = $initial_state(NORMAL)',
    '~S_initial_reporting.REPORTINGMODIFIED',
    'S_initial_reporting.REPORTINGINI = $ptascii("30719")',
    '$reporting_ini_mask([32,9] ++ $ptascii("+512suffix")) = 512',
    '$reporting_ini_mask($ptascii("2.5")) = 2',
    '$reporting_ini_mask($ptascii("2e3")) = 2',
    '$reporting_ini_mask($ptascii("0x200")) = 0',
    '$reporting_ini_mask($ptascii("E_ALL")) = 0',
    '$reporting_ini_mask([0,50]) = 0',
    '$reporting_ini_mask([50,0,53]) = 2',
    '$reporting_ini_mask($ptascii("9223372036854775807")) = $(-1)',
    '$reporting_ini_mask($ptascii("9223372036854775808")) = $(-1)',
    '$reporting_ini_mask($ptascii("-9223372036854775808")) = 0',
    '$reporting_ini_mask($ptascii("-9223372036854775809")) = 0',
    '$reporting_ini_mask($ptascii("4294967296")) = 0',
    '$builtin_value_bytes($ptascii("E_ERROR")) = (PINT 1)',
    '$builtin_value_bytes($ptascii("E_WARNING")) = (PINT 2)',
    '$builtin_value_bytes($ptascii("E_PARSE")) = (PINT 4)',
    '$builtin_value_bytes($ptascii("E_NOTICE")) = (PINT 8)',
    '$builtin_value_bytes($ptascii("E_CORE_ERROR")) = (PINT 16)',
    '$builtin_value_bytes($ptascii("E_CORE_WARNING")) = (PINT 32)',
    '$builtin_value_bytes($ptascii("E_COMPILE_ERROR")) = (PINT 64)',
    '$builtin_value_bytes($ptascii("E_COMPILE_WARNING")) = (PINT 128)',
    '$builtin_value_bytes($ptascii("E_USER_ERROR")) = (PINT 256)',
    '$builtin_value_bytes($ptascii("E_USER_WARNING")) = (PINT 512)',
    '$builtin_value_bytes($ptascii("E_USER_NOTICE")) = (PINT 1024)',
    '$builtin_value_bytes($ptascii("E_RECOVERABLE_ERROR")) = (PINT 4096)',
    '$builtin_value_bytes($ptascii("E_DEPRECATED")) = (PINT 8192)',
    '$builtin_value_bytes($ptascii("E_USER_DEPRECATED")) = (PINT 16384)',
    '$builtin_value_bytes($ptascii("E_ALL")) = (PINT 30719)',
    '$builtin_value_bytes($ptascii("e_warning")) = eps',
    '$constant_candidates($ptascii("Diagnostic\\\\E_WARNING"), ($ptascii("E_WARNING"))) = (VALUE (PINT 2))',
    '$constant_lookup_bytes($ptascii("E_STRICT")) = (ABRUPT (UNSUPPORTED "initial constant"))',
    'porigin_reporting = PORIGIN 0 eps',
    'S_silenced = $silence_begin(S_initial_reporting, porigin_reporting)',
    'S_silenced.REPORTING = 4437',
    'S_silenced.REPORTINGMODIFIED',
    'S_silenced.REPORTINGINI = S_initial_reporting.REPORTINGINI',
    '$config_reporting_restore(S_silenced).REPORTING = 30719',
    '~$config_reporting_restore(S_silenced).REPORTINGMODIFIED',
    'S_fatal = $silence_begin(S_initial_reporting[.REPORTING = 1], porigin_reporting)',
    '~S_fatal.REPORTINGMODIFIED',
    '$config_reporting_restore(S_fatal).REPORTING = 1',
    '$config_reporting_restore(S_fatal).REPORTINGINI = $ptascii("30719")',
    '$config_reporting_restore(S_fatal[.REPORTINGMODIFIED = true]).REPORTING = 30719',
    '$silence_restore(S_silenced[.REPORTING = 512], 30719).REPORTING = 512',
    'S.TODO = (CONFIG_INVOKE pconfigcall) :: ptask_tail*',
    'S.FILEINCLUDEPATH = eps',
    'S.FILECWD = eps',
    '$call_descriptors_valid(S)',
    '$config_invoke_valid(S, pconfigcall)',
    '$config_reporting_selected(pconfigcall)',
    '~$config_reporting_selected(pconfigcall[.KIND = INTRINSIC_CHDIR])',
    '~$config_invoke_valid(S, pconfigcall[.KIND = INTRINSIC_INI_RESTORE])',
    '~$config_invoke_valid(S[.CODE = eps], pconfigcall)',
    '~$config_invoke_valid(S, pconfigcall[.LINE = $(pconfigcall.LINE + 1)])',
    'PhpStep: S ~> S_changed',
    'S_changed.REPORTING = 512',
    'S_changed.REPORTINGINI = [32,9] ++ $ptascii("+512junk") ++ [0] ++ $ptascii("tail")',
    'S_changed.REPORTINGMODIFIED',
    'S_changed.RESULT = KNOWN (PSTRING $ptascii("30719"))',
    'S_changed.BASE = BASE_VALUE (KNOWN PNULL)',
    'S_changed.TODO = ptask_tail*',
    'S_changed.FILEINCLUDEPATH = eps',
    'S_done = $drive(S_changed, 1500)',
    'S_done.COMPLETION = NORMAL',
    'S_done.REPORTING = 30719',
    'S_done.REPORTINGINI = $ptascii("30719")',
    '~S_done.REPORTINGMODIFIED',
]

CASE = ('reporting-raw-mask-protocol', SOURCE_ID, STAGE, CHECKS)
