"""Source-derived diagnostic continuations retain selection and conversion."""

SHADOW_SOURCE = b'namespace Late; const E_STRICT="shadow";'

CLASS_PREFIX = r'''
dec $diagnostic_drop_class_bind(ptask*, porigin) : ptask*
def $diagnostic_drop_class_bind(eps, porigin) = eps
def $diagnostic_drop_class_bind((CLASS_CONST_BIND porigin) :: ptask_tail*, porigin) = $diagnostic_drop_class_bind(ptask_tail*, porigin)
def $diagnostic_drop_class_bind(ptask :: ptask_tail*, porigin) = ptask :: $diagnostic_drop_class_bind(ptask_tail*, porigin)
  -- if ptask =/= CLASS_CONST_BIND porigin
'''

def checked_shadow_program(frontend, adapter):
    import base64
    parsed = frontend.request({'op': 'parse-eval', 'id': '1', 'mode': 'eval',
                               'profile': 'cli-raw-85',
                               'source': base64.b64encode(SHADOW_SOURCE).decode()})
    assert parsed['accepted'], parsed
    checked = adapter.request({'op': 'check', 'ast': parsed['ast'], 'fixture': True})
    assert checked['ok'], checked
    return checked['fixture']

CASES = [
    ('estrict-suspended-class-protocol', 'independent-estrict-class-default-handler-throw-context', '''true
  -- if S.CLASSCONSTANTINIT =/= eps
  -- if S.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*
  -- if perrorcall.RESUME = DEPRECATED_CONSTANT_RESULT pdeprecatedconstant''', [
        'S.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = DEPRECATED_CONSTANT_RESULT pdeprecatedconstant',
        'S.CLASSCONSTANTINIT = [pclassconstantcontext]',
        'S.CONSTCONTEXT = (pconstantcontext)',
        'pconstantcontext.ORIGIN = pclassconstantcontext.DECL',
        'pclassconstantcontext.PREVIOUS = eps',
        '$class_constant_bindings(S.TODO) = [pclassconstantcontext.DECL]',
        '$class_constant_frames_bindings(S.FRAMES) = eps',
        '$class_constant_scope_stack(S) = [pclassconstantcontext]',
        '$class_constant_active(S)',
        '$class_constant_busy_unique(S.CLASSCONSTANTINIT)',
        '$class_constant_state_valid(S)',
        '$call_descriptors_valid(S)',
        'PhpStep: S ~> S_handler',
        'S_handler.CONSTCONTEXT = eps',
        'S_handler.CLASSCONSTANTINIT = [pclassconstantcontext]',
        '~$class_constant_active(S_handler)',
        '$class_constant_scope_stack(S_handler) = eps',
        'S_handler.FRAMES = pframe :: pframe_saved*',
        'pframe.CONSTCONTEXT = (pconstantcontext)',
        '$class_constant_bindings(pframe.TODO) = [pclassconstantcontext.DECL]',
        '$class_constant_frames_bindings(S_handler.FRAMES) = [pclassconstantcontext.DECL]',
        '$class_constant_frame_stack(S_handler, pframe, pframe_saved*) = [pclassconstantcontext]',
        'S_scope = $constant_frame_scope(S_handler, pframe, pframe_saved*)',
        'S_scope.CONSTCONTEXT = (pconstantcontext)',
        'S_scope.CLASSCONSTANTINIT = [pclassconstantcontext]',
        '$class_constant_scope_stack(S_scope) = [pclassconstantcontext]',
        '$class_constant_active(S_scope)',
        '$constant_context_valid(S_handler)',
        '$constant_context_valid(S_scope)',
        '$class_constant_state_valid(S_handler)',
        '$call_descriptors_valid(S_handler)',
        '~$call_descriptors_valid(S_handler[.FRAMES = pframe[.CONSTCONTEXT = eps] :: pframe_saved*])',
        '~$call_descriptors_valid(S_handler[.FRAMES = pframe[.CONSTCONTEXT = (pconstantcontext[.LINE = $(pconstantcontext.LINE + 1)])] :: pframe_saved*])',
        '~$call_descriptors_valid(S_handler[.FRAMES = pframe[.CONSTCONTEXT = (pconstantcontext[.ORIGIN = pdeprecatedconstant.SITE])] :: pframe_saved*])',
        '~$class_constant_state_valid(S_handler[.FRAMES = pframe[.TODO = $diagnostic_drop_class_bind(pframe.TODO, pclassconstantcontext.DECL)] :: pframe_saved*])',
        '~$class_constant_state_valid(S_handler[.CLASSCONSTANTINIT = eps])',
        '~$class_constant_state_valid(S_handler[.CLASSCONSTANTINIT = [pclassconstantcontext[.LINE = $(pclassconstantcontext.LINE + 1)]]])',
        '~$class_constant_protected(pclassconstantcontext.SELECTION, pclassconstantcontext.PREVIOUS)',
        '$class_constant_busy_unique([pclassconstantcontext, pclassconstantcontext])',
        'pclassconstantcontext_protected = pclassconstantcontext[.PREVIOUS = (pconstantcontext)]',
        '$class_constant_protected(pclassconstantcontext_protected.SELECTION, pclassconstantcontext_protected.PREVIOUS)',
        '$class_constant_busy_unique([pclassconstantcontext_protected])',
        '~$class_constant_busy_unique([pclassconstantcontext_protected, pclassconstantcontext_protected])',
        '~$class_constant_state_valid(S_handler[.CLASSCONSTANTINIT = [pclassconstantcontext_protected, pclassconstantcontext_protected]][.CONSTCONTEXT = (pconstantcontext)][.TODO = (CLASS_CONST_BIND pclassconstantcontext.DECL) :: S_handler.TODO][.FRAMES = pframe[.CONSTCONTEXT = (pconstantcontext)] :: pframe_saved*])',
        'S_done = $drive(S, 1500)',
        'S_done.COMPLETION = NORMAL',
        'S_done.CONSTCONTEXT = eps',
        'S_done.CLASSCONSTANTINIT = eps',
        '~$deprecated_constant_active(S_done)',
        '$class_constant_state_valid(S_done)',
        '$call_descriptors_valid(S_done)',
    ]),
    ('estrict-selected-shadow-protocol', 'estrict-handler-publishes-namespace-shadow', '''true
  -- if S.TODO = ptask :: ptask_tail*
  -- if $deprecated_constant_active_task(ptask)''', [
        'S.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = DEPRECATED_CONSTANT_RESULT pdeprecatedconstant',
        'S.CONSTCONTEXT = (pconstantcontext)',
        '$constant_fact_at(pconstantcontext.FACTS, pdeprecatedconstant.SITE) = eps',
        'pdeprecatedconstant.PREFIX = 0',
        '$deprecated_constant_valid(S, pdeprecatedconstant)',
        '$call_descriptors_valid(S)',
        'PhpStep: S ~> S_handler',
        'S_handler.CONSTCONTEXT = eps',
        'S_handler.CLASSCONSTANTINIT = S.CLASSCONSTANTINIT',
        'S_handler.FRAMES = pframe :: pframe_saved*',
        'pframe.CONSTCONTEXT = (pconstantcontext)',
        'S_scope = $constant_frame_scope(S_handler, pframe, pframe_saved*)',
        'S_scope.CONSTCONTEXT = (pconstantcontext)',
        'S_scope.ORIGIN = S.ORIGIN',
        'S_scope.TODO = (ERROR_HANDLER_RESULT perrorcall_entered) :: ptask_tail*',
        'perrorcall_entered.TARGET = (pcalltarget_entered)',
        'perrorcall_entered = perrorcall[.TARGET = (pcalltarget_entered)]',
        '$constant_context_valid(S_handler)',
        '$constant_context_valid(S_scope)',
        '$call_descriptors_valid(S_handler)',
        '~$call_descriptors_valid(S_handler[.FRAMES = pframe[.CONSTCONTEXT = eps] :: pframe_saved*])',
        '~$call_descriptors_valid(S_handler[.FRAMES = pframe[.CONSTCONTEXT = (pconstantcontext[.LINE = $(pconstantcontext.LINE + 1)])] :: pframe_saved*])',
        '~$call_descriptors_valid(S_handler[.FRAMES = pframe[.CONSTCONTEXT = (pconstantcontext[.ORIGIN = pdeprecatedconstant.SITE])] :: pframe_saved*])',
        '~$call_descriptors_valid(S_handler[.FRAMES = pframe[.CONSTCONTEXT = (pconstantcontext[.FACTS = [{ORIGIN pdeprecatedconstant.SITE, VALUE (PINT 2048), CLASS PVSTRING true, LOOKUP eps}]])] :: pframe_saved*])',
        'S_wait = $drive(S, 1500)',
        'S_wait.COMPLETION = SOURCE_PENDING',
        'S_wait.EVALCONTEXTS = pevalcontext :: pevalcontext_tail*',
        'S_wait.TODO = (EVAL_AWAIT n) :: ptask_wait*',
        'n = pevalcontext.UNIT',
        'pevalcontext.BYTES = $ptascii("namespace Late; const E_STRICT=") ++ [34] ++ $ptascii("shadow") ++ [34,59]',
        '$call_descriptors_valid(S_wait)',
        'S_resumed = $eval_resume(S_wait, SOURCE_ACCEPT n pevalcontext.BYTES SHADOW_PROGRAM)',
        'S_resumed.COMPLETION = NORMAL',
        'S_late_reached = $seek(S_resumed, 1500)',
        r'S_late_reached.COMPLETION = NORMAL \/ S_late_reached.COMPLETION = BUDGET',
        'S_late = S_late_reached[.COMPLETION = NORMAL]',
        'S_late.TODO = (ERROR_HANDLER_RESULT perrorcall_late) :: ptask_tail*',
        'S_late.CONSTCONTEXT = (pconstantcontext)',
        'perrorcall_late.TARGET = (pcalltarget)',
        'perrorcall_late = perrorcall[.TARGET = (pcalltarget)]',
        'S_late.RESULT = KNOWN (PINT 0)',
        '$user_constant_at(S_late.USERCONSTANTS, $user_constant_key($ptascii("Late") ++ [92] ++ $ptascii("E_STRICT"))) = (puserconstant)',
        'puserconstant.VALUE = PSTRING $ptascii("shadow")',
        'puserconstant.CLASS = PVSTRING true',
        '~$deprecated_constant_selected(S_late, pdeprecatedconstant.SITE)',
        '$deprecated_constant_valid(S_late, pdeprecatedconstant)',
        '$call_descriptors_valid(S_late)',
        '$constant_result_class(S_late, pdeprecatedconstant.SITE) = PVSTRING true',
        'PhpStep: S_late ~> S_finish',
        'S_finish.TODO = (DEPRECATED_CONSTANT_RESULT pdeprecatedconstant) :: ptask_tail*',
        'PhpStep: S_finish ~> S_value',
        'S_value.RESULT = KNOWN (PINT 2048)',
        'S_value.CONSTCONTEXT = (pconstantcontext_value)',
        '$constant_fact_at(pconstantcontext_value.FACTS, pdeprecatedconstant.SITE) = ({ORIGIN pdeprecatedconstant.SITE, VALUE (PINT 2048), CLASS PVSCALAR, LOOKUP eps})',
        'S_value.TODO = (ORIGIN_RETURN porigin_previous?) :: (CONSTANT_OBSERVE pdeprecatedconstant.SITE) :: ptask_after*',
        'PhpStep: S_value ~> S_restored',
        'PhpStep: S_restored ~> S_observed',
        '$constant_class(S_observed, pdeprecatedconstant.SITE) = PVSCALAR',
        '$constant_operand(S_observed, pdeprecatedconstant.SITE) = (PINT 2048)',
        '$call_descriptors_valid(S_observed)',
        'S_done = $drive(S_observed, 1500)',
        'S_done.COMPLETION = NORMAL',
        'S_done.DEFAULTCACHE = [pdefaultcache]',
        'pdefaultcache.VALUE = PINT 2048',
        'pdefaultcache.CLASS = PVSCALAR',
    ]),
    ('estrict-dispatch-protocol', 'estrict-runtime-repeat-dead-branch', '''true
  -- if S.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*
  -- if perrorcall.RESUME = DEPRECATED_CONSTANT_RESULT pdeprecatedconstant''', [
        'S.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = DEPRECATED_CONSTANT_RESULT pdeprecatedconstant',
        '$call_descriptors_valid(S)',
        '$deprecated_constant_valid(S, pdeprecatedconstant)',
        '$error_call_valid(S, perrorcall)',
        'S.ORIGIN = (pdeprecatedconstant.SITE)',
        'perrorcall.LEVEL = 8192',
        'perrorcall.LINE = 4',
        'perrorcall.MESSAGE = $deprecated_constant_message()',
        'pdeprecatedconstant.PREFIX = 0',
        '$deprecated_constant_selected(S, pdeprecatedconstant.SITE)',
        '$compiled_read(S, pdeprecatedconstant.SITE) = eps',
        '$deprecated_constant_active(S)',
        '$deprecated_constant_active_tasks(S.TODO)',
        '~$deprecated_constant_active($initial_state(NORMAL))',
        '~$deprecated_constant_valid(S[.CODE = eps], pdeprecatedconstant)',
        '~$deprecated_constant_valid(S[.ORIGIN = eps], pdeprecatedconstant)',
        '~$deprecated_constant_valid(S, pdeprecatedconstant[.LINE = 1])',
        '~$deprecated_constant_valid(S, pdeprecatedconstant[.PREFIX = 1])',
        '~$error_call_valid(S, perrorcall[.LEVEL = 512])',
        '~$error_call_valid(S, perrorcall[.MESSAGE = eps])',
        '~$error_call_valid(S, perrorcall[.LINE = 1])',
        '~$error_call_valid(S, perrorcall[.SITE = PORIGIN 0 eps])',
        '~$error_call_valid(S, perrorcall[.EVENT = OUTPUT eps])',
        'S_recursive = $deprecated_constant_start(S, pdeprecatedconstant.SITE, ptask_tail*)',
        'S_recursive.RESULT = KNOWN (PINT 2048)',
        'S_recursive.EVENTS = S.EVENTS',
        'S_recursive.TODO = ptask_tail*',
        'S_done = $drive(S, 1500)',
        'S_done.COMPLETION = NORMAL',
        '~$deprecated_constant_active(S_done)',
        'S_done.REPORTING = 30719',
        'S_done.REPORTINGINI = $ptascii("30719")',
    ]),
    ('reporting-lossy-dispatch-protocol', 'reporting-lossy-handler-postconversion-old', '''true
  -- if S.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*
  -- if perrorcall.RESUME = REPORTING_LONG_RESULT pconfigcall i''', [
        'S.TODO = (ERROR_HANDLER_INVOKE perrorcall) :: ptask_tail*',
        'perrorcall.RESUME = REPORTING_LONG_RESULT pconfigcall i',
        '$call_descriptors_valid(S)',
        '$config_invoke_valid(S, pconfigcall)',
        '$reporting_long_valid(S, pconfigcall, i)',
        '$error_call_valid(S, perrorcall)',
        'S.FILEINCLUDEPATH = eps',
        'S.FILECWD = eps',
        'i = 3',
        'pconfigcall.KIND = INTRINSIC_ERROR_REPORTING',
        'pconfigcall.SENT = [NAMED_SENT (KNOWN (PSTRING $ptascii("3.5")))]',
        'perrorcall.LEVEL = 8192',
        'perrorcall.LINE = 3',
        'perrorcall.MESSAGE = $ptascii("Implicit conversion from float-string ") ++ [34] ++ $ptascii("3.5") ++ [34] ++ $ptascii(" to int loses precision")',
        '$reporting_lossy_value(PINT 3) = eps',
        '$reporting_lossy_value(PSTRING $ptascii("3")) = eps',
        '$reporting_lossy_value(PSTRING $ptascii("3.0")) = eps',
        '$reporting_lossy_value(PSTRING ($ptascii("3.5") ++ [0])) = eps',
        '~$reporting_long_valid(S[.CODE = eps], pconfigcall, i)',
        '~$reporting_long_valid(S[.ORIGIN = eps], pconfigcall, i)',
        '~$reporting_long_valid(S, pconfigcall[.KIND = INTRINSIC_TRIGGER_ERROR], i)',
        '~$reporting_long_valid(S, pconfigcall[.LINE = 1], i)',
        '~$reporting_long_valid(S, pconfigcall, 4)',
        '~$error_call_valid(S, perrorcall[.LEVEL = 512])',
        '~$error_call_valid(S, perrorcall[.MESSAGE = eps])',
        '~$error_call_valid(S, perrorcall[.LINE = 1])',
        '~$error_call_valid(S, perrorcall[.EVENT = OUTPUT eps])',
        'S_equal = $reporting_long_finish(S[.REPORTING = 3][.REPORTINGINI = $ptascii("3") ++ [0] ++ $ptascii("kept")], 3)',
        'S_equal.RESULT = KNOWN (PINT 3)',
        'S_equal.REPORTINGINI = $ptascii("3") ++ [0] ++ $ptascii("kept")',
        'S_changed = $reporting_long_finish(S[.REPORTING = 512], 3)',
        'S_changed.RESULT = KNOWN (PINT 512)',
        'S_changed.REPORTING = 3',
        'S_changed.REPORTINGINI = $ptascii("3")',
        'S_changed.REPORTINGMODIFIED',
        'S_done = $drive(S, 1500)',
        'S_done.COMPLETION = NORMAL',
        'S_done.REPORTING = 3',
        'S_done.REPORTINGINI = $ptascii("3")',
        'S_done.REPORTINGMODIFIED',
    ]),
]
