"""Authored and independently captured exact request/GLOBALS source catalogue."""
CASES = [{'id': 'compiler/key/empty-array/read',
  'source': b'<?php echo "A";echo $GLOBALS[\n[]\n];echo "B";'},
 {'id': 'compiler/key/empty-array/write', 'source': b'<?php echo "A";$GLOBALS[\n[]\n]=7;echo "B";'},
 {'id': 'compiler/key/empty-array/unset',
  'source': b'<?php echo "A";unset($GLOBALS[\n[]\n]);echo "B";'},
 {'id': 'compiler/key/empty-array/quiet',
  'source': b'<?php echo "A";echo $GLOBALS[\n[]\n]??7;echo "B";'},
 {'id': 'compiler/key/empty-array/coalesce-write',
  'source': b'<?php echo "A";$GLOBALS[\n[]\n]??=7;echo "B";'},
 {'id': 'compiler/key/empty-array/reference',
  'source': b'<?php echo "A";$r=&$GLOBALS[\n[]\n];echo "B";'},
 {'id': 'compiler/key/array/read', 'source': b'<?php echo "A";echo $GLOBALS[\n[1]\n];echo "B";'},
 {'id': 'compiler/key/array/write', 'source': b'<?php echo "A";$GLOBALS[\n[1]\n]=7;echo "B";'},
 {'id': 'compiler/key/array/unset', 'source': b'<?php echo "A";unset($GLOBALS[\n[1]\n]);echo "B";'},
 {'id': 'compiler/key/array/quiet',
  'source': b'<?php echo "A";echo $GLOBALS[\n[1]\n]??7;echo "B";'},
 {'id': 'compiler/key/array/coalesce-write',
  'source': b'<?php echo "A";$GLOBALS[\n[1]\n]??=7;echo "B";'},
 {'id': 'compiler/key/array/reference',
  'source': b'<?php echo "A";$r=&$GLOBALS[\n[1]\n];echo "B";'},
 {'id': 'compiler/key/nan/read', 'source': b'<?php echo "A";echo $GLOBALS[\nNAN\n];echo "B";'},
 {'id': 'compiler/key/nan/write', 'source': b'<?php echo "A";$GLOBALS[\nNAN\n]=7;echo "B";'},
 {'id': 'compiler/key/nan/unset', 'source': b'<?php echo "A";unset($GLOBALS[\nNAN\n]);echo "B";'},
 {'id': 'compiler/key/nan/quiet', 'source': b'<?php echo "A";echo $GLOBALS[\nNAN\n]??7;echo "B";'},
 {'id': 'compiler/key/nan/coalesce-write',
  'source': b'<?php echo "A";$GLOBALS[\nNAN\n]??=7;echo "B";'},
 {'id': 'compiler/key/nan/reference', 'source': b'<?php echo "A";$r=&$GLOBALS[\nNAN\n];echo "B";'},
 {'id': 'compiler/key/infinity/read', 'source': b'<?php echo "A";echo $GLOBALS[\nINF\n];echo "B";'},
 {'id': 'compiler/key/infinity/write', 'source': b'<?php echo "A";$GLOBALS[\nINF\n]=7;echo "B";'},
 {'id': 'compiler/key/infinity/unset',
  'source': b'<?php echo "A";unset($GLOBALS[\nINF\n]);echo "B";'},
 {'id': 'compiler/key/infinity/quiet',
  'source': b'<?php echo "A";echo $GLOBALS[\nINF\n]??7;echo "B";'},
 {'id': 'compiler/key/infinity/coalesce-write',
  'source': b'<?php echo "A";$GLOBALS[\nINF\n]??=7;echo "B";'},
 {'id': 'compiler/key/infinity/reference',
  'source': b'<?php echo "A";$r=&$GLOBALS[\nINF\n];echo "B";'},
 {'id': 'compiler/key/list-effect/read',
  'source': b'<?php echo "A";echo $GLOBALS[\n(list($x)=[1])\n];echo "B";'},
 {'id': 'compiler/key/list-effect/write',
  'source': b'<?php echo "A";$GLOBALS[\n(list($x)=[1])\n]=7;echo "B";'},
 {'id': 'compiler/key/list-effect/unset',
  'source': b'<?php echo "A";unset($GLOBALS[\n(list($x)=[1])\n]);echo "B";'},
 {'id': 'compiler/key/list-effect/quiet',
  'source': b'<?php echo "A";echo $GLOBALS[\n(list($x)=[1])\n]??7;echo "B";'},
 {'id': 'compiler/key/list-effect/coalesce-write',
  'source': b'<?php echo "A";$GLOBALS[\n(list($x)=[1])\n]??=7;echo "B";'},
 {'id': 'compiler/key/list-effect/reference',
  'source': b'<?php echo "A";$r=&$GLOBALS[\n(list($x)=[1])\n];echo "B";'},
 {'id': 'compiler/key/header/read',
  'source': b'<?php echo "A";echo $GLOBALS[\n"http_response_header"\n];echo "B";'},
 {'id': 'compiler/key/header/write',
  'source': b'<?php echo "A";$GLOBALS[\n"http_response_header"\n]=7;echo "B";'},
 {'id': 'compiler/key/header/unset',
  'source': b'<?php echo "A";unset($GLOBALS[\n"http_response_header"\n]);echo "B";'},
 {'id': 'compiler/key/header/quiet',
  'source': b'<?php echo "A";echo $GLOBALS[\n"http_response_header"\n]??7;echo "B";'},
 {'id': 'compiler/key/header/coalesce-write',
  'source': b'<?php echo "A";$GLOBALS[\n"http_response_header"\n]??=7;echo "B";'},
 {'id': 'compiler/key/header/reference',
  'source': b'<?php echo "A";$r=&$GLOBALS[\n"http_response_header"\n];echo "B";'},
 {'id': 'compiler/key/null/read', 'source': b'<?php echo "A";echo $GLOBALS[\nnull\n];echo "B";'},
 {'id': 'compiler/key/null/write', 'source': b'<?php echo "A";$GLOBALS[\nnull\n]=7;echo "B";'},
 {'id': 'compiler/key/null/unset', 'source': b'<?php echo "A";unset($GLOBALS[\nnull\n]);echo "B";'},
 {'id': 'compiler/key/null/quiet',
  'source': b'<?php echo "A";echo $GLOBALS[\nnull\n]??7;echo "B";'},
 {'id': 'compiler/key/null/coalesce-write',
  'source': b'<?php echo "A";$GLOBALS[\nnull\n]??=7;echo "B";'},
 {'id': 'compiler/key/null/reference',
  'source': b'<?php echo "A";$r=&$GLOBALS[\nnull\n];echo "B";'},
 {'id': 'compiler/key/float/read', 'source': b'<?php echo "A";echo $GLOBALS[\n1.2\n];echo "B";'},
 {'id': 'compiler/key/float/write', 'source': b'<?php echo "A";$GLOBALS[\n1.2\n]=7;echo "B";'},
 {'id': 'compiler/key/float/unset', 'source': b'<?php echo "A";unset($GLOBALS[\n1.2\n]);echo "B";'},
 {'id': 'compiler/key/float/quiet',
  'source': b'<?php echo "A";echo $GLOBALS[\n1.2\n]??7;echo "B";'},
 {'id': 'compiler/key/float/coalesce-write',
  'source': b'<?php echo "A";$GLOBALS[\n1.2\n]??=7;echo "B";'},
 {'id': 'compiler/key/float/reference',
  'source': b'<?php echo "A";$r=&$GLOBALS[\n1.2\n];echo "B";'},
 {'id': 'compiler/phase/append-read', 'source': b'<?php echo $GLOBALS[];'},
 {'id': 'compiler/phase/append-write', 'source': b'<?php $GLOBALS[]=1;'},
 {'id': 'compiler/phase/append-quiet', 'source': b'<?php echo $GLOBALS[]??1;'},
 {'id': 'compiler/phase/append-coalesce', 'source': b'<?php $GLOBALS[]??=1;'},
 {'id': 'compiler/phase/append-unset', 'source': b'<?php unset($GLOBALS[]);'},
 {'id': 'compiler/phase/literal-concat-read', 'source': b'<?php echo ${"GLO"."BALS"}[[]];'},
 {'id': 'compiler/phase/literal-concat-quiet', 'source': b'<?php echo ${"GLO"."BALS"}[[]]??1;'},
 {'id': 'compiler/phase/ternary-base-read', 'source': b'<?php echo ${true?"GLOBALS":"x"}[[]];'},
 {'id': 'compiler/phase/ternary-base-write', 'source': b'<?php ${true?"GLOBALS":"x"}[[]]=1;'},
 {'id': 'compiler/phase/global-read-header-flag',
  'source': b'<?php echo $GLOBALS["http_response_header"];echo $http_response_header;'},
 {'id': 'compiler/phase/global-write-header-flag',
  'source': b'<?php $GLOBALS["http_response_header"]=1;echo $http_response_header;'},
 {'id': 'compiler/phase/global-coalesce-header-flag',
  'source': b'<?php $GLOBALS["http_response_header"]??=1;echo $http_response_header;'},
 {'id': 'compiler/phase/cast-nan-name', 'source': b'<?php echo $GLOBALS[(string)NAN];'},
 {'id': 'compiler/phase/write-hole-priority', 'source': b'<?php $GLOBALS[[]]=[,$x];'},
 {'id': 'compiler/phase/coalesce-hole-priority', 'source': b'<?php $GLOBALS[[]]??=[,$x];'},
 {'id': 'compiler/phase/nested-append-priority', 'source': b'<?php echo $GLOBALS[][[]]??1;'},
 {'id': 'compiler/cv-order/dead-read',
  'source': b'<?php if(false){$b;$a;} $a=1;$b=2; foreach($GLOBALS as $probe_key=>$probe_value){if('
            b'$probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d")echo $probe_k'
            b'ey;} '},
 {'id': 'compiler/cv-order/dead-write',
  'source': b'<?php if(false){$b=0;$a=0;} $a=1;$b=2; foreach($GLOBALS as $probe_key=>$probe_value)'
            b'{if($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d")echo $pro'
            b'be_key;} '},
 {'id': 'compiler/cv-order/dead-dynamic-constant',
  'source': b'<?php if(false){${"b"|""};$a;} $a=1;${"b"|""}=2; foreach($GLOBALS as $probe_key=>$pr'
            b'obe_value){if($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d"'
            b')echo $probe_key;} '},
 {'id': 'compiler/cv-order/dead-literal-concat',
  'source': b'<?php if(false){${"b".""};$a;} $a=1;${"b".""}=2; foreach($GLOBALS as $probe_key=>$pr'
            b'obe_value){if($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d"'
            b')echo $probe_key;} '},
 {'id': 'compiler/cv-order/dead-ternary-name',
  'source': b'<?php if(false){${true?"b":"b"};$a;} $a=1;${true?"b":"b"}=2; foreach($GLOBALS as $pr'
            b'obe_key=>$probe_value){if($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$pro'
            b'be_key==="d")echo $probe_key;} '},
 {'id': 'compiler/cv-order/assignment-order',
  'source': b'<?php if(false){$b=$a;} $a=1;$b=2; foreach($GLOBALS as $probe_key=>$probe_value){if('
            b'$probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d")echo $probe_k'
            b'ey;} '},
 {'id': 'compiler/cv-order/reference-order',
  'source': b'<?php if(false){$b=&$a;} $a=1;$b=2; foreach($GLOBALS as $probe_key=>$probe_value){if'
            b'($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d")echo $probe_'
            b'key;} '},
 {'id': 'compiler/cv-order/dim-order',
  'source': b'<?php if(false){$b[$c]=$a;} $a=1;$b=2;$c=3; foreach($GLOBALS as $probe_key=>$probe_v'
            b'alue){if($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d")echo'
            b' $probe_key;} '},
 {'id': 'compiler/cv-order/list-rhs-order',
  'source': b'<?php if(false){list($b,$c)=$a;} $c=3;$b=2;$a=1; foreach($GLOBALS as $probe_key=>$pr'
            b'obe_value){if($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d"'
            b')echo $probe_key;} '},
 {'id': 'compiler/cv-order/list-key-order',
  'source': b'<?php if(false){list($c=>$b)=$a;} $c=3;$b=2;$a=1; foreach($GLOBALS as $probe_key=>$p'
            b'robe_value){if($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d'
            b'")echo $probe_key;} '},
 {'id': 'compiler/cv-order/foreach-order',
  'source': b'<?php foreach([] as $a=>$b){$c=1;} $a=1;$b=2;$c=3; foreach($GLOBALS as $probe_key=>$'
            b'probe_value){if($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="'
            b'd")echo $probe_key;} '},
 {'id': 'compiler/cv-order/foreach-iterable-order',
  'source': b'<?php if(false){foreach($c as $a=>$b){}} $a=1;$b=2;$c=3; foreach($GLOBALS as $probe_'
            b'key=>$probe_value){if($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_k'
            b'ey==="d")echo $probe_key;} '},
 {'id': 'compiler/cv-order/for-order',
  'source': b'<?php for($a=0;$b??false;$c=0){$d=0;} $a=1;$b=2;$c=3;$d=4; foreach($GLOBALS as $prob'
            b'e_key=>$probe_value){if($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe'
            b'_key==="d")echo $probe_key;} '},
 {'id': 'compiler/cv-order/skipped-short-circuit',
  'source': b'<?php false&&$b; $a=1;${"b"|""}=2; foreach($GLOBALS as $probe_key=>$probe_value){if('
            b'$probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d")echo $probe_k'
            b'ey;} '},
 {'id': 'compiler/cv-order/visited-coalesce-rhs',
  'source': b'<?php $a??$b; $a=1;$b=2; foreach($GLOBALS as $probe_key=>$probe_value){if($probe_key'
            b'==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d")echo $probe_key;} '},
 {'id': 'compiler/cv-order/coalesce-assignment',
  'source': b'<?php if(false){$b[$c]??=$a;} $a=1;$b=2;$c=3; foreach($GLOBALS as $probe_key=>$probe'
            b'_value){if($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d")ec'
            b'ho $probe_key;} '},
 {'id': 'compiler/cv-order/global-key-not-cv',
  'source': b'<?php if(false){$GLOBALS["b"];$a;} $a=1;$GLOBALS["b"]=2; foreach($GLOBALS as $probe_'
            b'key=>$probe_value){if($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_k'
            b'ey==="d")echo $probe_key;} '},
 {'id': 'compiler/cv-order/computed-global-name',
  'source': b'<?php ${true?"GLOBALS":"x"}=["b"=>2]; $a=1; foreach($GLOBALS as $probe_key=>$probe_v'
            b'alue){if($probe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d")echo'
            b' $probe_key;} '},
 {'id': 'compiler/cv-order/unset-reassign',
  'source': b'<?php $b=2;$a=1;unset($b);$b=3; foreach($GLOBALS as $probe_key=>$probe_value){if($pr'
            b'obe_key==="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d")echo $probe_key;'
            b'} '},
 {'id': 'compiler/cv-order/dynamic-before-cv',
  'source': b'<?php ${"b"|""}=2;$a=1; foreach($GLOBALS as $probe_key=>$probe_value){if($probe_key='
            b'=="a"||$probe_key==="b"||$probe_key==="c"||$probe_key==="d")echo $probe_key;} '},
 {'id': 'compiler/cv-special/this-read', 'source': b'<?php echo $this;'},
 {'id': 'compiler/cv-special/this-quiet', 'source': b'<?php echo $this??1;'},
 {'id': 'compiler/cv-special/this-compound', 'source': b'<?php $this+=1;'},
 {'id': 'compiler/cv-special/this-dim', 'source': b'<?php echo $this[0];'},
 {'id': 'compiler/cv-special/this-list', 'source': b'<?php list($a)=$this;'},
 {'id': 'compiler/cv-special/this-list-ref', 'source': b'<?php list(&$a)=$this;'},
 {'id': 'compiler/cv-special/this-list-concat', 'source': b'<?php list($a)=${"th"."is"};'},
 {'id': 'compiler/cv-special/this-list-temp', 'source': b'<?php list($a)=${true?"this":"x"};'},
 {'id': 'compiler/cv-special/autoglobals',
  'source': b'<?php echo $_GET,$_POST,$_COOKIE,$_REQUEST,$_FILES,$_ENV,$_SERVER,$GLOBALS;'},
 {'id': 'compiler/cv-special/empty-name', 'source': b'<?php ${""}=1; echo ${""};'},
 {'id': 'compiler/cv-special/numeric-name', 'source': b'<?php ${1}=1; ${1.5}=2;'},
 {'id': 'compiler/cv-special/binary-name', 'source': b'<?php ${"a\\0b"}=1;'},
 {'id': 'compiler/cv-special/autoglobal-dim', 'source': b'<?php $GLOBALS["a"]=1; echo $_GET["a"];'},
 {'id': 'compiler/cv-special/header', 'source': b'<?php echo $http_response_header;'},
 {'id': 'compiler/activation/baseline',
  'source': b'<?php  foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_REQUEST")echo "'
            b'R";} '},
 {'id': 'compiler/activation/env',
  'source': b'<?php $_ENV; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_REQUEST")'
            b'echo "R";} '},
 {'id': 'compiler/activation/request',
  'source': b'<?php $_REQUEST; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_REQUE'
            b'ST")echo "R";} '},
 {'id': 'compiler/activation/env-request',
  'source': b'<?php $_ENV;$_REQUEST; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="'
            b'_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/request-env',
  'source': b'<?php $_REQUEST;$_ENV; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="'
            b'_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/dead-env',
  'source': b'<?php if(false){$_ENV;} foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==='
            b'"_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/dead-write',
  'source': b'<?php if(false){$_ENV=[];} foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k'
            b'==="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/dead-unset',
  'source': b'<?php if(false){unset($_ENV);} foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";i'
            b'f($k==="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/skip-and',
  'source': b'<?php false&&$_ENV; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_RE'
            b'QUEST")echo "R";} '},
 {'id': 'compiler/activation/skip-or',
  'source': b'<?php true||$_ENV; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_REQ'
            b'UEST")echo "R";} '},
 {'id': 'compiler/activation/skip-ternary',
  'source': b'<?php true?1:$_ENV; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_RE'
            b'QUEST")echo "R";} '},
 {'id': 'compiler/activation/visit-ternary',
  'source': b'<?php true?$_ENV:1; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_RE'
            b'QUEST")echo "R";} '},
 {'id': 'compiler/activation/skip-coalesce',
  'source': b'<?php 1??$_ENV; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_REQUES'
            b'T")echo "R";} '},
 {'id': 'compiler/activation/visit-coalesce',
  'source': b'<?php $x??$_ENV; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_REQUE'
            b'ST")echo "R";} '},
 {'id': 'compiler/activation/literal-concat',
  'source': b'<?php ${"_E"."NV"}; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_RE'
            b'QUEST")echo "R";} '},
 {'id': 'compiler/activation/computed-ternary',
  'source': b'<?php ${true?"_ENV":"x"}; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k='
            b'=="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/computed-bitwise',
  'source': b'<?php ${"_ENV"|""}; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_RE'
            b'QUEST")echo "R";} '},
 {'id': 'compiler/activation/computed-cast',
  'source': b'<?php ${(string)"_ENV"}; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k=='
            b'="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/runtime-name',
  'source': b'<?php $n="_ENV";$$n; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_R'
            b'EQUEST")echo "R";} '},
 {'id': 'compiler/activation/global-key',
  'source': b'<?php $GLOBALS["_ENV"]; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==='
            b'"_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/global-key-write',
  'source': b'<?php $GLOBALS["_ENV"]=[]; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k'
            b'==="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/global-key-unset',
  'source': b'<?php unset($GLOBALS["_ENV"]); foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";i'
            b'f($k==="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/global-key-coalesce',
  'source': b'<?php $GLOBALS["_ENV"]??=[]; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if('
            b'$k==="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/env-coalesce',
  'source': b'<?php $_ENV??=[]; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_REQU'
            b'EST")echo "R";} '},
 {'id': 'compiler/activation/foreach-dead',
  'source': b'<?php foreach([] as $_ENV){} foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if('
            b'$k==="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/list-rhs',
  'source': b'<?php if(false){list($a)=$_ENV;} foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E"'
            b';if($k==="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/list-target',
  'source': b'<?php if(false){list($_ENV)=[];} foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E"'
            b';if($k==="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/direct-globals',
  'source': b'<?php $GLOBALS; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if($k==="_REQUES'
            b'T")echo "R";} '},
 {'id': 'compiler/activation/list-globals',
  'source': b'<?php if(false){list($a)=$GLOBALS;} foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo '
            b'"E";if($k==="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/computed-globals',
  'source': b'<?php ${true?"GLOBALS":"x"}; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";if('
            b'$k==="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/for-order',
  'source': b'<?php for(;$_ENV;){$_REQUEST;break;} foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo'
            b' "E";if($k==="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/duplicate',
  'source': b'<?php $_ENV;$_ENV;$_REQUEST;$_ENV; foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "'
            b'E";if($k==="_REQUEST")echo "R";} '},
 {'id': 'compiler/activation/request-before-get-write',
  'source': b'<?php $_GET["x"]=1;echo $_REQUEST["x"]??"missing"; foreach($GLOBALS as $k=>$v){if($k'
            b'==="_ENV")echo "E";if($k==="_REQUEST")echo "R";} '},
 {'id': 'activation-extra/refetch',
  'source': b'<?php if(false){$_ENV??=$_REQUEST;} foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo '
            b'"E";if($k==="_REQUEST")echo "R";}'},
 {'id': 'activation-extra/computed-refetch',
  'source': b'<?php if(false){${"_ENV"|""}??=$_REQUEST;} foreach($GLOBALS as $k=>$v){if($k==="_ENV'
            b'")echo "E";if($k==="_REQUEST")echo "R";}'},
 {'id': 'activation-extra/temporary-name',
  'source': b'<?php if(false){${true?"_ENV":"_REQUEST"};} foreach($GLOBALS as $k=>$v){if($k==="_EN'
            b'V")echo "E";if($k==="_REQUEST")echo "R";}'},
 {'id': 'activation-extra/key-before-rhs',
  'source': b'<?php if(false){$_ENV[($_REQUEST=[])]??=1;} foreach($GLOBALS as $k=>$v){if($k==="_EN'
            b'V")echo "E";if($k==="_REQUEST")echo "R";}'},
 {'id': 'activation-extra/for-loop',
  'source': b'<?php if(false){for(;$_ENV;$_REQUEST){$_ENV;}} foreach($GLOBALS as $k=>$v){if($k==="'
            b'_ENV")echo "E";if($k==="_REQUEST")echo "R";}'},
 {'id': 'activation-extra/list-rhs',
  'source': b'<?php if(false){[$_ENV]=$_REQUEST;} foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo '
            b'"E";if($k==="_REQUEST")echo "R";}'},
 {'id': 'activation-extra/foreach',
  'source': b'<?php if(false){foreach($_ENV as $_REQUEST){}} foreach($GLOBALS as $k=>$v){if($k==="'
            b'_ENV")echo "E";if($k==="_REQUEST")echo "R";}'},
 {'id': 'activation-extra/unset-order',
  'source': b'<?php if(false){unset($_REQUEST,$_ENV);} foreach($GLOBALS as $k=>$v){if($k==="_ENV")'
            b'echo "E";if($k==="_REQUEST")echo "R";}'},
 {'id': 'activation-extra/empty-and',
  'source': b'<?php if(false){empty($_REQUEST)&&$_ENV;} foreach($GLOBALS as $k=>$v){if($k==="_ENV"'
            b')echo "E";if($k==="_REQUEST")echo "R";}'},
 {'id': 'activation-extra/multi-isset',
  'source': b'<?php if(false){isset($_ENV,$_REQUEST);} foreach($GLOBALS as $k=>$v){if($k==="_ENV")'
            b'echo "E";if($k==="_REQUEST")echo "R";}'},
 {'id': 'activation-extra/globals-refetch',
  'source': b'<?php if(false){$GLOBALS["_ENV"]??=$_REQUEST;} foreach($GLOBALS as $k=>$v){if($k==="'
            b'_ENV")echo "E";if($k==="_REQUEST")echo "R";}'},
 {'id': 'activation-extra/literal-name',
  'source': b'<?php if(false){${"_E"."NV"};} foreach($GLOBALS as $k=>$v){if($k==="_ENV")echo "E";i'
            b'f($k==="_REQUEST")echo "R";}'},
 {'id': 'snapshot/snapshot-value', 'source': b'<?php $x=1;$s=$GLOBALS;$x=2;echo $s["x"],$x;'},
 {'id': 'snapshot/snapshot-explicit-reference',
  'source': b'<?php $x=1;$r=&$x;$s=$GLOBALS;$x=2;echo $s["x"],$s["r"];'},
 {'id': 'snapshot/snapshot-reference-rebind',
  'source': b'<?php $x=1;$r=&$x;$s=$GLOBALS;unset($x);$x=3;echo $s["x"],$s["r"],$x;'},
 {'id': 'snapshot/snapshot-array-cow',
  'source': b'<?php $x=[1];$s=$GLOBALS;$s["x"][0]=2;echo $x[0],$s["x"][0];'},
 {'id': 'snapshot/snapshot-embedded-reference',
  'source': b'<?php $v=1;$x=[&$v];$s=$GLOBALS;$s["x"][0]=2;echo $v,$x[0];'},
 {'id': 'snapshot/snapshot-lhs-undefined-omitted',
  'source': b'<?php $s=$GLOBALS;echo $s["s"]??"missing";'},
 {'id': 'snapshot/snapshot-dead-cv-omitted',
  'source': b'<?php if(false){$missing=1;}$s=$GLOBALS;foreach($s as $k=>$v){if($k==="missing"){ech'
            b'o "bad";}}echo "ok";'},
 {'id': 'snapshot/snapshot-reference-initializes-null',
  'source': b'<?php $r=&$missing;$s=$GLOBALS;echo $s["missing"]===null,$s["r"]===null;'},
 {'id': 'snapshot/snapshot-numeric-keys',
  'source': b'<?php ${"12"}=1;${"012"}=2;${"-1"}=3;$s=$GLOBALS;foreach($s as $k=>$v){if($k===12){e'
            b'cho "I",$v;}if($k==="012"){echo "S",$v;}if($k===-1){echo "N",$v;}}'},
 {'id': 'snapshot/snapshot-dead-cv-order',
  'source': b'<?php if(false){$x=0;}$y=2;$x=1;$s=$GLOBALS;foreach($s as $k=>$v){if($k==="x"||$k==='
            b'"y"){echo $k,$v;}}'},
 {'id': 'snapshot/snapshot-unset-reinsert-order',
  'source': b'<?php $x=1;$y=2;unset($x);$x=3;$s=$GLOBALS;foreach($s as $k=>$v){if($k==="x"||$k==="'
            b'y"){echo $k,$v;}}'},
 {'id': 'snapshot/snapshot-dynamic-insertion-order',
  'source': b'<?php $n="x";$$n=1;$y=2;$s=$GLOBALS;foreach($s as $k=>$v){if($k==="x"||$k==="y"){ech'
            b'o $k,$v;}}'},
 {'id': 'snapshot/snapshot-later-global-insert',
  'source': b'<?php $s=$GLOBALS;$GLOBALS["z"]=9;echo $s["z"]??0;'},
 {'id': 'snapshot/snapshot-dynamic-globals-name',
  'source': b'<?php $x=1;$n="GLOBALS";$s=$$n;$x=2;echo $s["x"],$x;'},
 {'id': 'snapshot/globals-foreach-value-snapshot',
  'source': b'<?php $x=1;$y=2;foreach($GLOBALS as $k=>$v){if($k==="x"){echo $v;$y=9;}if($k==="y"){'
            b'echo $v;}}'},
 {'id': 'snapshot/globals-whole-reference-rejection',
  'source': b'<?php echo "before";$s=&$GLOBALS;echo "after";'},
 {'id': 'snapshot-extra/snapshot-singleton-reference',
  'source': b'<?php $x=1;$r=&$x;unset($r);$s=$GLOBALS;$x=2;echo $s["x"],$x;'},
 {'id': 'snapshot-extra/snapshot-numeric-singleton-reference',
  'source': b'<?php ${"12"}=1;$r=&${"12"};unset($r);$s=$GLOBALS;${"12"}=2;echo $s[12],${"12"};'},
 {'id': 'snapshot-extra/snapshot-global-unset-cv-order',
  'source': b'<?php $x=1;$y=2;unset($GLOBALS["x"]);$x=3;$s=$GLOBALS;foreach($s as $k=>$v){if($k==='
            b'"x"||$k==="y"){echo $k,$v;}}'},
 {'id': 'snapshot-extra/snapshot-dynamic-name-array-write',
  'source': b'<?php $n="GLOBALS";$$n=["x"=>7];echo ${$n}["x"],$GLOBALS["x"]??0;'},
 {'id': 'symbol/dynamic-unset-cv',
  'source': b'<?php $a=1;$b=2;$n="a";unset($$n);$$n=3; foreach($GLOBALS as $k=>$v){if($k==="a"||$k'
            b'==="b")echo $k,$v;}'},
 {'id': 'symbol/dynamic-unset-noncv',
  'source': b'<?php $n="a";$$n=1;$m="b";$$m=2;unset($$n);$$n=3; foreach($GLOBALS as $k=>$v){if($k='
            b'=="a"||$k==="b")echo $k,$v;}'},
 {'id': 'symbol/globals-unset-cv',
  'source': b'<?php $a=1;$b=2;unset($GLOBALS["a"]);$GLOBALS["a"]=3; foreach($GLOBALS as $k=>$v){if'
            b'($k==="a"||$k==="b")echo $k,$v;}'},
 {'id': 'symbol/globals-unset-noncv',
  'source': b'<?php $GLOBALS["a"]=1;$GLOBALS["b"]=2;unset($GLOBALS["a"]);$GLOBALS["a"]=3; foreach('
            b'$GLOBALS as $k=>$v){if($k==="a"||$k==="b")echo $k,$v;}'},
 {'id': 'symbol/numeric-singleton-snapshot',
  'source': b'<?php ${"1"}=1;$r=&${"1"};unset($r);$s=$GLOBALS;$s[1]=7;echo ${"1"};'},
 {'id': 'symbol/numeric-shared-snapshot',
  'source': b'<?php ${"1"}=1;$r=&${"1"};$s=$GLOBALS;$s[1]=7;echo $r;'},
 {'id': 'this/constant-read', 'source': b'<?php echo "A";echo $GLOBALS["this"];echo "B";'},
 {'id': 'this/constant-write',
  'source': b'<?php echo "A";$GLOBALS["this"]=7;echo "done";echo "B";'},
 {'id': 'this/constant-quiet', 'source': b'<?php echo "A";echo $GLOBALS["this"]??7;echo "B";'},
 {'id': 'this/constant-unset',
  'source': b'<?php echo "A";unset($GLOBALS["this"]);echo "done";echo "B";'},
 {'id': 'this/constant-reference',
  'source': b'<?php echo "A";$r=&$GLOBALS["this"];echo "done";echo "B";'},
 {'id': 'this/dynamic-read', 'source': b'<?php echo "A";$n="this";echo $GLOBALS[$n];echo "B";'},
 {'id': 'this/dynamic-write',
  'source': b'<?php echo "A";$n="this";$GLOBALS[$n]=7;echo "done";echo "B";'},
 {'id': 'this/dynamic-quiet', 'source': b'<?php echo "A";$n="this";echo $GLOBALS[$n]??7;echo "B";'},
 {'id': 'this/dynamic-unset',
  'source': b'<?php echo "A";$n="this";unset($GLOBALS[$n]);echo "done";echo "B";'},
 {'id': 'this/dynamic-reference',
  'source': b'<?php echo "A";$n="this";$r=&$GLOBALS[$n];echo "done";echo "B";'},
 {'id': 'this-nested/nested-unset',
  'source': b'<?php echo "A";unset($GLOBALS["this"][0]);echo "done";echo "B";'},
 {'id': 'this-nested/nested-read', 'source': b'<?php echo "A";echo $GLOBALS["this"][0];echo "B";'},
 {'id': 'this-nested/nested-quiet',
  'source': b'<?php echo "A";echo $GLOBALS["this"][0]??7;echo "B";'},
 {'id': 'this-nested/nested-isset',
  'source': b'<?php echo "A";echo isset($GLOBALS["this"][0]),empty($GLOBALS["this"][0]);echo "B";'},
 {'id': 'this-nested/nested-write',
  'source': b'<?php echo "A";$GLOBALS["this"][0]=7;echo "done";echo "B";'},
 {'id': 'this-nested/nested-reference',
  'source': b'<?php echo "A";$r=&$GLOBALS["this"][0];echo "done";echo "B";'},
 {'id': 'this-nested/compound', 'source': b'<?php echo "A";$GLOBALS["this"]+=1;echo "B";'},
 {'id': 'this-nested/coalesce-effects',
  'source': b'<?php echo "A";$GLOBALS["this"]??=($x=1);echo $x;echo "B";'},
 {'id': 'historical/concat-name-1-4', 'source': b'<?php ${true?"this":"other"} = 1;'},
 {'id': 'historical/concat-name-1-5', 'source': b'<?php unset(${true?"this":"other"});'},
 {'id': 'historical/concat-name-8-0', 'source': b'<?php echo ${"GLO"."BALS"};'},
 {'id': 'historical/concat-name-8-1', 'source': b'<?php (void)${"GLO"."BALS"};echo 1;'},
 {'id': 'historical/concat-name-8-2', 'source': b'<?php echo (string)${"GLO"."BALS"};'},
 {'id': 'historical/concat-name-8-4', 'source': b'<?php ${"GLO"."BALS"} = 1;'},
 {'id': 'historical/concat-name-8-5', 'source': b'<?php unset(${"GLO"."BALS"});'},
 {'id': 'bootstrap/proxy-duplicate',
  'source': b'<?php echo $_ENV["HTTP_PROXY"],":",$_SERVER["HTTP_PROXY"],":",$_ENV["DUP"],":",$_SER'
            b'VER["DUP"];',
  'environment': [b'LC_ALL=C',
                  b'TZ=UTC',
                  b'HTTP_PROXY=first',
                  b'HTTP_PROXY=last',
                  b'DUP=first',
                  b'DUP=last'],
  'clock': [-1, 500000],
  'extra_ini': []},
 {'id': 'bootstrap/proxy-empty-first',
  'source': b'<?php echo "[",$_ENV["HTTP_PROXY"],"][",$_SERVER["HTTP_PROXY"],"]";',
  'environment': [b'LC_ALL=C', b'TZ=UTC', b'HTTP_PROXY=', b'HTTP_PROXY=last'],
  'clock': [-1, 500000],
  'extra_ini': []},
 {'id': 'bootstrap/proxy-case-sensitive',
  'source': b'<?php echo $_ENV["HTTP_PROXY"],":",$_ENV["http_proxy"];',
  'environment': [b'LC_ALL=C',
                  b'TZ=UTC',
                  b'http_proxy=lower',
                  b'HTTP_PROXY=upper',
                  b'http_proxy=last'],
  'clock': [-1, 500000],
  'extra_ini': []},
 {'id': 'bootstrap/server-overwrite-order',
  'source': b'<?php foreach($_SERVER as $k=>$v){echo "[",$k,"]";} echo ":",$_SERVER["REQUEST_TIME"'
            b'],":",$_SERVER["REQUEST_TIME_FLOAT"],":",$_SERVER["argc"],":",$_SERVER["argv"][1];',
  'environment': [b'LC_ALL=C',
                  b'TZ=UTC',
                  b'REQUEST_TIME=old',
                  b'argv=old',
                  b'PHP_SELF=old',
                  b'REQUEST_TIME_FLOAT=old',
                  b'argc=old',
                  b'SCRIPT_FILENAME=old',
                  b'Z=last'],
  'clock': [-1, 500000],
  'extra_ini': []},
 {'id': 'bootstrap/argc-disabled',
  'source': b'<?php echo $argc,":",$argv[1],":",$_SERVER["argc"],":",$_SERVER["argv"][1];',
  'environment': [b'LC_ALL=C', b'TZ=UTC'],
  'clock': [-1, 500000],
  'extra_ini': ['register_argc_argv=0']},
 {'id': 'bootstrap/server-disabled',
  'source': b'<?php echo $argc,":",$argv[1],":";foreach($_SERVER as $k=>$v){echo $k;}',
  'environment': [b'LC_ALL=C', b'TZ=UTC'],
  'clock': [-1, 500000],
  'extra_ini': ['variables_order=EGPC']},
 {'id': 'bootstrap/env-disabled',
  'source': b'<?php echo empty($_ENV),":",$_SERVER["A"];',
  'environment': [b'LC_ALL=C', b'TZ=UTC', b'A=one'],
  'clock': [-1, 500000],
  'extra_ini': ['variables_order=GPCS']},
 {'id': 'bootstrap/jit-disabled',
  'source': b'<?php foreach($GLOBALS as $k=>$v){echo "[",$k,"]";}',
  'environment': [b'LC_ALL=C', b'TZ=UTC', b'A=one'],
  'clock': [-1, 500000],
  'extra_ini': ['auto_globals_jit=0']},
 {'id': 'isset/isset-globals-temp', 'source': b'<?php echo isset(${true?"GLOBALS":"x"});'},
 {'id': 'isset/empty-globals-temp', 'source': b'<?php echo empty(${true?"GLOBALS":"x"});'},
 {'id': 'isset/isset-global-array-key', 'source': b'<?php echo isset($GLOBALS[[]]);'},
 {'id': 'isset/empty-global-array-key', 'source': b'<?php echo empty($GLOBALS[[]]);'},
 {'id': 'this-more/dynamic-this-write', 'source': b'<?php $n="this";echo "A";$$n=1;'},
 {'id': 'this-more/computed-this-write', 'source': b'<?php echo "A";${true?"this":"x"}=1;'},
 {'id': 'this-more/dynamic-this-unset', 'source': b'<?php $n="this";echo "A";unset($$n);echo "B";'},
 {'id': 'this-more/dynamic-this-read', 'source': b'<?php $n="this";echo "A",$$n,"B";'},
 {'id': 'this-more/dynamic-this-reference-source', 'source': b'<?php $n="this";echo "A";$r=&$$n;'},
 {'id': 'this-more/dynamic-this-reference-target',
  'source': b'<?php $n="this";$x=1;echo "A";$$n=&$x;'},
 {'id': 'this-more/computed-this-reference-target-missing',
  'source': b'<?php echo "A";${true?"this":"x"}=&$missing;'},
 {'id': 'this-more/dynamic-this-reference-target-temp',
  'source': b'<?php $n="this";$a=[1];echo "A";$$n=&$a[0];'},
 {'id': 'this-more/dynamic-this-dimension-write', 'source': b'<?php $n="this";echo "A";$$n[0]=1;'},
 {'id': 'this-more/dynamic-this-dimension-reference',
  'source': b'<?php $n="this";echo "A";$r=&$$n[0];'},
 {'id': 'this-more/dynamic-this-dimension-unset',
  'source': b'<?php $n="this";echo "A";unset($$n[0]);echo "B";'},
 {'id': 'this-more/dynamic-this-dimension-quiet', 'source': b'<?php $n="this";echo $$n[0]??7;'},
 {'id': 'this-more/dynamic-this-dimension-isset',
  'source': b'<?php $n="this";echo isset($$n[0]),empty($$n[0]);'},
 {'id': 'this-more/dynamic-this-dimension-compound',
  'source': b'<?php $n="this";echo "A";$$n[0]+=1;'},
 {'id': 'this-more/dynamic-this-dimension-coalesce',
  'source': b'<?php $n="this";echo "A";$$n[0]??=1;'},
 {'id': 'this-more/dynamic-this-direct-coalesce', 'source': b'<?php $n="this";echo "A";$$n??=1;'},
 {'id': 'ownership/pg-reference-cow',
  'source': b'<?php $r=&$_GET;$r["x"]=1;$s=$GLOBALS;echo $_GET["x"],empty($_REQUEST);unset($_GET);'
            b'$r["x"]=2;echo $s["_GET"]["x"],$r["x"];'},
 {'id': 'ownership/pg-visible-rebind',
  'source': b'<?php $_GET=[1];$r=&$_GET;$_GET=[2];$s=$GLOBALS;unset($_GET);$r[0]=3;echo $s["_GET"]'
            b'[0],empty($_REQUEST);'},
 {'id': 'ownership/global-reference-cycle',
  'source': b'<?php $x=[];$x[0]=&$x;$s=$GLOBALS;unset($x);$s["x"][1]=2;echo $s["x"][0][1];'},
 {'id': 'ownership/global-foreach-cv-unset',
  'source': b'<?php $x=1;$y=2;foreach($GLOBALS as $k=>$v){if($k==="x"){echo $v;unset($GLOBALS["y"]'
            b');$y=3;}if($k==="y")echo $v;}echo $y;'},
 {'id': 'ownership/global-foreach-ref-result',
  'source': b'<?php $a=[1];foreach($a as &$v){$s=$GLOBALS;$s["v"]=2;}echo $a[0],$v;'},
 {'id': 'ownership/global-coalesce-cv-name',
  'source': b'<?php $n="x";$GLOBALS[$n]??=($n="y");echo $GLOBALS["x"]??0,$GLOBALS["y"]??0;'},
 {'id': 'ownership/global-coalesce-temp-name',
  'source': b'<?php $n="x";$GLOBALS["".$n]??=($n="y");echo $GLOBALS["x"]??0,$GLOBALS["y"]??0;'},
 {'id': 'ownership/global-coalesce-ref-name',
  'source': b'<?php $n="x";$GLOBALS[($r=&$n)]??=($n="y");echo $GLOBALS["x"]??0,$GLOBALS["y"]??0;'},
 {'id': 'ownership/global-ref-target',
  'source': b'<?php $n="x";$src=1;$GLOBALS[$n]=&$src;$src=2;echo $x;unset($GLOBALS["x"]);$src=3;ec'
            b'ho $src;'},
 {'id': 'ownership/global-ref-target-cow',
  'source': b'<?php $src=[1];$GLOBALS["x"]=&$src;$s=$GLOBALS;$s["x"][0]=2;echo $src[0];'},
 {'id': 'ownership/server-argv-cow',
  'source': b'<?php $a=$argv;$_SERVER["argv"][1]="changed";echo $argv[1],$a[1],$_SERVER["argv"][1]'
            b';'},
 {'id': 'ownership/argv-server-cow',
  'source': b'<?php $a=$_SERVER;$argv[1]="changed";echo $argv[1],$a["argv"][1],$_SERVER["argv"][1]'
            b';'},
 {'id': 'ownership/env-compile-before-effect',
  'source': b'<?php $GLOBALS["_ENV"]["FIRST"]="changed";echo $_ENV["FIRST"];'},
 {'id': 'ownership/env-dynamic-not-activated',
  'source': b'<?php $n="_ENV";echo empty($$n);$$n=["FIRST"=>"changed"];echo $$n["FIRST"];'},
 {'id': 'ownership/request-empty-hidden-gpc',
  'source': b'<?php $_GET["x"]=1;$_POST["x"]=2;$_COOKIE["x"]=3;echo empty($_REQUEST);'},
 {'id': 'ownership/global-this-unset-nested',
  'source': b'<?php echo "A";unset($GLOBALS["this"][0]);'},
 {'id': 'ownership/global-superglobal-unset',
  'source': b'<?php unset($GLOBALS["_SERVER"]);echo empty($_SERVER);$GLOBALS["_SERVER"]=[1];echo $'
            b'_SERVER[0];'},
 {'id': 'ownership/global-argc-reference',
  'source': b'<?php $a=&$argc;$b=&$GLOBALS["argc"];$a=7;echo $argc,$b,$_SERVER["argc"];'},
 {'id': 'argc/0', 'source': b'<?php echo $argc;'},
 {'id': 'argc/1', 'source': b'<?php $a=&$argc;$a=7;echo $argc,$_SERVER["argc"];'},
 {'id': 'argc/2', 'source': b'<?php $n="argc";$a=&$$n;$a=7;echo $argc,$_SERVER["argc"];'},
 {'id': 'argc/3', 'source': b'<?php unset($GLOBALS);'},
 {'id': 'argc/4', 'source': b'<?php $n="GLOBALS";unset($$n);'},
 {'id': 'argc/5', 'source': b'<?php $GLOBALS["a"]??=1;echo $a;'}]

CASES += [{'id': 'request-boundary/raw-environment',
  'source': b'<?php foreach($_ENV as $k=>$v)echo $k,":",$v,";";',
  'environment': [b'=empty',
                  b'A.B=dot',
                  b'A B=space',
                  b'A[B=bracket',
                  b'12=twelve',
                  b'012=zero',
                  b'-2=negative',
                  b'RAW=\xff',
                  b'\xff=key',
                  b'DUP=first',
                  b'DUP=last']},
 {'id': 'request-boundary/reserved-collisions',
  'source': b'<?php echo $_ENV["LD_PRELOAD"],":",$_SERVER["LD_PRELOAD"],":",$_ENV["PHP_SPEC_REQUES'
            b'T_FD"],":",$_SERVER["HTTP_PROXY"],":",$_ENV["HTTP_PROXY"];',
  'environment': [b'LD_PRELOAD=authored',
                  b'PHP_SPEC_REQUEST_FD=authored-fd',
                  b'HTTP_PROXY=first',
                  b'HTTP_PROXY=last']},
 {'id': 'request-boundary/argv-bytes',
  'source': b'<?php echo $argc,":",$argv[1],":",$argv[2],":",$_SERVER["argc"],":",$_SERVER["argv"]'
            b'[2];',
  'argv': [b'', b'\xff']},
 {'id': 'request-boundary/empty-environment',
  'source': b'<?php echo empty($_ENV),":",$_SERVER["DOCUMENT_ROOT"],":",empty($_REQUEST);',
  'environment': []},
 {'id': 'request-boundary/lowercase-order',
  'source': b'<?php echo $_ENV["FIRST"],":",$_SERVER["FIRST"],":",empty($_GET),empty($_POST),empty'
            b'($_COOKIE);',
  'extra_ini': ['variables_order=egpcs']},
 {'id': 'request-boundary/no-server-env',
  'source': b'<?php echo empty($_SERVER),empty($_ENV),":",$argc,":",$argv[1];',
  'extra_ini': ['variables_order=GPC', 'auto_globals_jit=0']},
 {'id': 'request-boundary/clock-0',
  'source': b'<?php echo $_SERVER["REQUEST_TIME"],":",$_SERVER["REQUEST_TIME_FLOAT"];',
  'clock': [0, 0]},
 {'id': 'request-boundary/clock-1',
  'source': b'<?php echo $_SERVER["REQUEST_TIME"],":",$_SERVER["REQUEST_TIME_FLOAT"];',
  'clock': [-1, 500000]},
 {'id': 'request-boundary/clock-2',
  'source': b'<?php echo $_SERVER["REQUEST_TIME"],":",$_SERVER["REQUEST_TIME_FLOAT"];',
  'clock': [-1, 999999]},
 {'id': 'request-boundary/clock-3',
  'source': b'<?php echo $_SERVER["REQUEST_TIME"],":",$_SERVER["REQUEST_TIME_FLOAT"];',
  'clock': [9007199254740993, 999999]},
 {'id': 'request-boundary/clock-4',
  'source': b'<?php echo $_SERVER["REQUEST_TIME"],":",$_SERVER["REQUEST_TIME_FLOAT"];',
  'clock': [-9223372036854775808, 0]},
 {'id': 'request-boundary/clock-5',
  'source': b'<?php echo $_SERVER["REQUEST_TIME"],":",$_SERVER["REQUEST_TIME_FLOAT"];',
  'clock': [9223372036854775807, 999999]}]

CASES += [
    {'id': 'request-path/relative', 'source': b'<?php echo $argv[0],":",$_SERVER["PHP_SELF"],":",$_SERVER["SCRIPT_FILENAME"],":",__FILE__,":",__DIR__;', 'invocation': 'relative'},
    {'id': 'request-path/symlink', 'source': b'<?php echo $argv[0],":",$_SERVER["PHP_SELF"],":",$_SERVER["SCRIPT_FILENAME"],":",__FILE__,":",__DIR__;', 'invocation': 'symlink'},
]

CASES += [{'id': 'magic-request/magic-autoglobal-name',
  'source': b'<?php namespace _ENV; ${__NAMESPACE__}=1;'},
 {'id': 'magic-request/magic-concat-globals-name',
  'source': b'<?php namespace GLO; ${__NAMESPACE__."BALS"}=1;'},
 {'id': 'magic-request/computed-global-priority', 'source': b'<?php ${"GLOBALS"|""}=__LINE__;'}]
