#!/usr/bin/env python3
"""Real constant initializer errors retain context and retire failed owners."""
from pathlib import Path
import json

import closure_call_protocol as protocol

HERE = Path(__file__).resolve().parent
CATALOGUE = HERE / 'trait_data_public_object_initializer_review_cases.json'
HELPERS = HERE / 'trait_public_object_initializer_review.watsup'
protocol.MODULES = [*protocol.MODULES, HELPERS]
SOURCES = {row['id']: row['source']
           for row in json.loads(CATALOGUE.read_text())['cases']}

STAGE = ('S.TODO = (STMT (NStmtClass phpType14 phpType24 phpType3 '
         'phpType44 phpType42 phpType23 metadata)) :: ptask_tail* '
         '-- if S.ORIGIN = (porigin_c) '
         '-- if $class_at(S.CLASSES, porigin_c) = (pclassdesc_c) '
         '-- if pclassdesc_c.NAME = $ptascii("C")')

BINDINGS = [
    'S.CURRENT = eps',
    'S.FRAMES = eps',
    '$call_descriptors_valid(S)',
    '$declaration_history_valid(S)',
    '$class_constant_state_valid(S)',
    '$heap_valid($heap_graph(S))',
    '$class_named(S.CLASSNAMES, $ptascii("c")) = eps',
    '$class_named(S.CLASSNAMES, $ptascii("t")) = (porigin_t)',
    '$class_named(S.CLASSNAMES, $ptascii("p")) = (porigin_p)',
    '$class_at(S.CLASSES, porigin_p) = (pclassdesc_p)',
    '$class_constant_desc(pclassdesc_p.CONSTANTS, $ptascii("Y")) = (pclassconstantdesc_y)',
    'pclassconstantdesc_y.OWNER = porigin_p',
    '~pclassconstantdesc_y.FOLDED',
    '$trait_cache_object_source(S, pclassconstantdesc_y)',
    '$default_cache_at(S.CLASSCONSTANTCACHE, pclassconstantdesc_y.ORIGIN) = eps',
    'S.ERRORHANDLER.CALLBACK = (pvalue_handler)',
    'pvalue_handler = POBJECT n_handler',
    '$ppproperty_desc_at(pclassdesc_c.PROPERTIES, $ptascii("x")) = (ppropertydesc_c)',
    'ppropertydesc_c.DEFAULT = PROP_DEFERRED porigin_root',
    'porigin_root = PORIGIN n_source pcpath_root',
    '$origin_node(S.SOURCES, porigin_root) = (expression_root)',
    'z_demand = $expression_line(expression_root)',
    'z_demand = 5',
]

PREDECESSOR = [
    '$review_trait_object_seed(S, pclassdesc_c, porigin_root) = (F_seed)',
    '$trait_recording(F_seed, pcpath_root)',
    'F_seed.EXTERNAL = (S)',
    'F_seed.RECORD = (pfrecorder)',
    'pfrecorder.CLASS = porigin_c',
    'pfrecorder.ROOT = porigin_root',
    '$review_trait_object_start(F_seed, pcpath_root, pclassconstantdesc_y, z_demand) = ((S_start, ptraitcachecause))',
    'ptraitcachecause.CLASS = porigin_c',
    'ptraitcachecause.ROOT = porigin_root',
    'ptraitcachecause.LOOKUPS = [porigin_root]',
    'ptraitcachecause.PREFIX = |S.DECLARATIONS|',
    'ptraitcachecause.USERPREFIX = |S.USERCONSTANTS|',
    '$review_trait_object_error(F_seed, S_start, ptraitcachecause, 300) = ((F_seen, S_before, S_raw))',
    'S_before.COMPLETION = NORMAL',
    '$class_constant_active(S_before)',
    'S_before.CLASSCONSTANTINIT = pclassconstantcontext :: pclassconstantcontext_tail*',
    'pclassconstantcontext.DECL = pclassconstantdesc_y.ORIGIN',
    'S_before.CONSTCONTEXT = (pconstantcontext)',
    'pconstantcontext.ORIGIN = pclassconstantdesc_y.ORIGIN',
    'F_seen.MEMORY = F_seed.MEMORY',
    'F_seen.RECORD = F_seed.RECORD',
    '$trait_cache_object_scalar_error(S_raw.COMPLETION)',
    'F_seen.RECORDED = [pfdiagnostic]',
    'pfdiagnostic.OWNER = porigin_p',
    'pfdiagnostic.LEVEL = 8192',
    'pfdiagnostic.LINE = 2',
    'pfdiagnostic.MESSAGE = $deprecated_constant_message()',
    'S_context = $trait_cache_object_failure_context(S_before, S_raw)',
    'S_cont = $throwable_continuation(S_before, S_context)',
    'S_throw = $throwable_transition(S_before, S_context)',
    'S_throw.COMPLETION = THROWING n_throw',
    'n_throw = |S_raw.OBJECTS|',
    'S_throw.OBJECTS[n_throw] = THROWABLE pthrowable_inner',
    '$throwable_field(S_throw, n_throw, "message") = PSTRING ptbytes_message',
    '$throwable_field(S_throw, n_throw, "line") = PINT z_error',
    '$throwable_field(S_throw, n_throw, "trace") = PARRAY n_trace',
    '$heap_owners($heap_graph(S_throw), HOBJECT n_throw) = 1',
    'F_error = $trait_cache_object_resume(F_seen, pcpath_root, pclassconstantdesc_y, z_demand, S_before, S_raw, ptraitcachecause)',
    '$trait_fold_error(F_error) = (ptraitdataerror)',
    'F_error.VALUE = eps',
    'ptraitdataerror.KIND = pthrowable_inner.KIND',
    'ptraitdataerror.MESSAGE = ptbytes_message',
    'ptraitdataerror.LINE = z_error',
    'ptraitdataerror.TRACE = $eval_exception_trace(S_cont)',
    'pthrowable_inner.FILEORIGIN = (ptraitdataerror.OWNER)',
    'F_error.MEMORY.ERRORORIGIN = pthrowable_inner.FILEORIGIN',
    'F_error.MEMORY.TODO = F_seed.MEMORY.TODO',
    'F_error.MEMORY.ORIGIN = F_seed.MEMORY.ORIGIN',
    'F_error.MEMORY.CONSTCONTEXT = F_seed.MEMORY.CONSTCONTEXT',
    'F_error.MEMORY.CLASSCONSTANTINIT = F_seed.MEMORY.CLASSCONSTANTINIT',
    'F_error.MEMORY.RESULT = F_seed.MEMORY.RESULT',
    'F_error.MEMORY.BASE = F_seed.MEMORY.BASE',
    'F_error.MEMORY.HELD = F_seed.MEMORY.HELD',
    'F_error.MEMORY.EVENTS = eps',
    'F_error.MEMORY.OBJECTPROPS = S.OBJECTPROPS',
    '$objectprops_at(F_error.MEMORY.OBJECTPROPS, n_throw) = eps',
    '~((HOBJECT n_throw) <- F_error.MEMORY.ALLOCATIONS)',
    '$heap_owners($heap_graph(F_error.MEMORY), HOBJECT n_throw) = 0',
    '$heap_owners($heap_graph(F_error.MEMORY), HARRAY n_trace) = 0',
    '$default_cache_at(F_error.MEMORY.CLASSCONSTANTCACHE, pclassconstantdesc_y.ORIGIN) = eps',
    '$trait_cache_event_at(F_error.MEMORY.CLASSCONSTANTHISTORY, pclassconstantdesc_y.ORIGIN) = eps',
    '$trait_member_fold(S, pclassdesc_c, porigin_root) = (F_full)',
    '$trait_fold_error(F_full) = (ptraitdataerror)',
    'F_full.RECORDED = F_error.RECORDED',
    'F_full.MEMORY.ALLOCATIONS = F_error.MEMORY.ALLOCATIONS',
]

RECORD_GUARDS = [
    '~$trait_recording(F_seen[.RECORD = eps], pcpath_root)',
    '~$trait_recording(F_seen[.EXTERNAL = eps], pcpath_root)',
    '~$trait_recording(F_seen[.RECORD = (pfrecorder[.CLASS = porigin_p])], pcpath_root)',
    '~$trait_recording(F_seen[.RECORD = (pfrecorder[.ROOT = porigin_c])], pcpath_root)',
    '~$trait_recording(F_seen[.EXTERNAL = (S[.SOURCES = eps])], pcpath_root)',
    '~$trait_recording(F_seen[.CLASSCONTEXT = eps], pcpath_root)',
    'F_bad = $trait_cache_object_resume(F_seen[.RECORD = eps], pcpath_root, pclassconstantdesc_y, z_demand, S_before, S_raw, ptraitcachecause)',
    'F_bad.MEMORY.COMPLETION = UNSUPPORTED "public trait object dependency exception"',
]

EXPRESSION_TRACE = [
    'z_error = 2',
    'ptraitdataerror.OWNER = porigin_p',
    'ptraitdataerror.TRACE = [ptraceframe_expression]',
    'ptraceframe_expression.FUNCTION = $ptascii("[constant expression]")',
    'ptraceframe_expression.FILE = $call_sourcefile(S.FILES, porigin_c)',
    'ptraceframe_expression.LINE = 5',
    'ptraceframe_expression.CLASS = eps',
    'ptraceframe_expression.ARGS = eps',
    '$class_constant_override(S_cont) = ((porigin_p, 2))',
]

TERMINAL = [
    'PhpStep: S ~> S_failed',
    'S_failed.COMPLETION = REQUESTFATAL $ptascii("CompileError") ptbytes_fatal 5',
    'S_failed.CLASSES = S.CLASSES',
    'S_failed.CLASSNAMES = S.CLASSNAMES',
    'S_failed.ERRORHANDLER = S.ERRORHANDLER',
    '(HOBJECT n_handler) <- S_failed.ALLOCATIONS',
    '$heap_owners($heap_graph(S_failed), HOBJECT n_handler) = 1',
    'S_failed.CURRENT = S.CURRENT',
    'S_failed.FRAMES = S.FRAMES',
    'S_failed.TRACE = eps',
    'S_failed.ERRORFATALTRACE = eps',
    'S_failed.OBJECTPROPS = S.OBJECTPROPS',
    '$default_cache_at(S_failed.CLASSCONSTANTCACHE, pclassconstantdesc_y.ORIGIN) = eps',
    '$trait_cache_event_at(S_failed.CLASSCONSTANTHISTORY, pclassconstantdesc_y.ORIGIN) = eps',
    '$heap_owners($heap_graph(S_failed), HOBJECT n_throw) = 0',
    '$heap_owners($heap_graph(S_failed), HARRAY n_trace) = 0',
    '$objectprops_at(S_failed.OBJECTPROPS, n_throw) = eps',
    '$review_trait_initializer_output(S_failed.EVENTS) = $ptascii("PRE;")',
    '$class_named(S_failed.CLASSNAMES, $ptascii("c")) = eps',
    '$iterator_notice_seeds(S_failed.TODO) = eps',
    '$call_descriptors_valid(S_failed)',
    '$declaration_history_valid(S_failed)',
    '$class_constant_state_valid(S_failed)',
    '$constant_callable_records_valid(S_failed, S_failed.CONSTANTCLOSURES)',
    '$heap_valid($heap_graph(S_failed))',
    'S_done = $drive(S_failed, 3000)',
    'S_done.COMPLETION = S_failed.COMPLETION',
    'S_done.SHUTDOWN.PHASE = SHUTDOWN_DONE',
    'S_done.CURRENT = eps',
    'S_done.FRAMES = eps',
    '$class_named(S_done.CLASSNAMES, $ptascii("c")) = eps',
    '$default_cache_at(S_done.CLASSCONSTANTCACHE, pclassconstantdesc_y.ORIGIN) = eps',
    '$heap_owners($heap_graph(S_done), HOBJECT n_throw) = 0',
    '$heap_owners($heap_graph(S_done), HARRAY n_trace) = 0',
    '$objectprops_at(S_done.OBJECTPROPS, n_throw) = eps',
    '$call_descriptors_valid(S_done)',
    '$declaration_history_valid(S_done)',
    '$class_constant_state_valid(S_done)',
    '$constant_callable_records_valid(S_done, S_done.CONSTANTCLOSURES)',
    '$heap_valid($heap_graph(S_done))',
]

NO_CACHE = [
    'n_fcc = |S.OBJECTS|',
    'S_raw.OBJECTS[n_fcc] = CONSTANTCLOSURE porigin_fcc pobject_fcc',
    '$constant_callable_record(S_raw.CONSTANTCLOSURES, n_fcc) = (pconstantclosure_fcc)',
    'pconstantclosure_fcc.DECL = pclassconstantdesc_y.ORIGIN',
    '~((HOBJECT n_fcc) <- F_error.MEMORY.ALLOCATIONS)',
    '$heap_owners($heap_graph(F_error.MEMORY), HOBJECT n_fcc) = 0',
    'F_error.MEMORY.ALLOCATIONS = S.ALLOCATIONS',
    'F_error.MEMORY.CLASSCONSTANTCACHE = S.CLASSCONSTANTCACHE',
    'F_error.MEMORY.CLASSCONSTANTHISTORY = S.CLASSCONSTANTHISTORY',
    'S_failed.ALLOCATIONS = S.ALLOCATIONS',
    'S_failed.CLASSCONSTANTCACHE = S.CLASSCONSTANTCACHE',
    'S_failed.CLASSCONSTANTHISTORY = S.CLASSCONSTANTHISTORY',
    'S_failed.DECLARATIONS = S.DECLARATIONS',
    '$heap_owners($heap_graph(S_failed), HOBJECT n_fcc) = 0',
    '$heap_owners($heap_graph(S_done), HOBJECT n_fcc) = 0',
    '$review_trait_initializer_output(S_done.EVENTS) = $ptascii("PRE;S;")',
]

CASES = {
    'early-compiled-name-error-uses-real-at-child-and-retires-first-throwable': {
        'source': SOURCES['public-fcc-initializer-error-after-created-closure'],
        'stage': STAGE,
        'checks': BINDINGS + PREDECESSOR + RECORD_GUARDS + [
            'ptraitdataerror.KIND = "Error"',
            'ptraitdataerror.MESSAGE = $ptascii("Undefined constant ") ++ [34] ++ $ptascii("DOES_NOT_EXIST") ++ [34]',
            'S_before.TODO = (AT porigin_value (EVAL expression_error)) :: ptask_error_tail*',
            'S_raw.COMPLETION = PHPERROR $ptascii("DOES_NOT_EXIST") 2',
            'S_before.ORIGIN = (porigin_item)',
            'porigin_value = $constant_child(porigin_item, [PCFIELD 1])',
            'S_context.ORIGIN = (porigin_value)',
            'S_context.CLASSCONSTANTINIT = S_before.CLASSCONSTANTINIT',
            'S_context.CONSTCONTEXT = S_before.CONSTCONTEXT',
            'S_context.TODO = S_raw.TODO',
            '$trait_cache_object_failure_context(S_before[.SOURCES = eps], S_raw) = S_raw',
            '$trait_cache_object_failure_context(S_before[.TODO = (AT porigin_c (EVAL expression_error)) :: ptask_error_tail*], S_raw) = S_raw',
            '$trait_cache_object_failure_context(S_before[.CLASSCONSTANTINIT = eps], S_raw) = S_raw',
            '$trait_cache_object_failure_context(S_before, S_raw[.CONSTCONTEXT = eps]) = S_raw[.CONSTCONTEXT = eps]',
        ] + EXPRESSION_TRACE + TERMINAL + NO_CACHE,
    },
    'typed-binder-error-keeps-restored-property-demand-without-expression-frame': {
        'source': SOURCES['public-fcc-initializer-type-error-after-created-closure'],
        'stage': STAGE,
        'checks': BINDINGS + PREDECESSOR + [
            'ptraitdataerror.KIND = "TypeError"',
            'ptraitdataerror.MESSAGE = $ptascii("Cannot assign Closure to class constant P::Y of type int")',
            'z_error = 5',
            'ptraitdataerror.TRACE = eps',
            'S_before.TODO = (CLASS_CONST_BIND pclassconstantdesc_y.ORIGIN) :: ptask_error_tail*',
            '$trait_cache_object_type_error(S_before)',
            'PhpStep: S_before ~> S_raw_bound',
            'S_raw_bound[.EVENTS = eps] = S_raw',
            'S_raw.CLASSCONSTANTINIT = eps',
            'S_raw.CONSTCONTEXT = eps',
            'S_raw.ORIGIN = (porigin_root)',
            'S_context = S_raw',
            '$class_constant_override(S_cont) = eps',
        ] + TERMINAL + NO_CACHE,
    },
    'array-key-type-error-uses-real-value-consumer-with-expression-frame': {
        'source': SOURCES['public-fcc-array-key-type-error-keeps-constant-expression-frame'],
        'stage': STAGE,
        'checks': BINDINGS + PREDECESSOR + [
            'ptraitdataerror.KIND = "TypeError"',
            'ptraitdataerror.MESSAGE = $ptascii("Cannot access offset of type array on array")',
            'S_before.TODO = (ARRAY_VALUE n_array (poperand_key) phpType13_rest* z_value) :: ptask_error_tail*',
            'z_value = 2',
            'S_before.ORIGIN = (porigin_item)',
            '$origin_node(S_before.SOURCES, porigin_item) = (NArrayItem phpType5 expression_value (BOOLEAN false) (BOOLEAN false) metadata_item)',
            'porigin_value = $constant_child(porigin_item, [PCFIELD 1])',
            'S_context.ORIGIN = (porigin_value)',
            'S_context.CLASSCONSTANTINIT = S_before.CLASSCONSTANTINIT',
            'S_context.CONSTCONTEXT = S_before.CONSTCONTEXT',
            '$trait_cache_object_failure_context(S_before[.SOURCES = eps], S_raw) = S_raw',
            '$trait_cache_object_failure_context(S_before[.ORIGIN = (porigin_c)], S_raw[.ORIGIN = (porigin_c)]) = S_raw[.ORIGIN = (porigin_c)]',
            '$trait_cache_object_failure_context(S_before[.TODO = (ARRAY_VALUE n_array (poperand_key) phpType13_rest* 99) :: ptask_error_tail*], S_raw) = S_raw',
            '$trait_cache_object_failure_context(S_before[.CLASSCONSTANTINIT = eps], S_raw) = S_raw',
        ] + EXPRESSION_TRACE + TERMINAL + NO_CACHE,
    },
    'nested-completed-closure-cache-survives-failed-y-and-two-throwables': {
        'source': SOURCES['public-nested-fcc-initializer-error-keeps-completed-closure-cache'],
        'stage': STAGE,
        'checks': BINDINGS + PREDECESSOR + [
            'ptraitdataerror.KIND = "Error"',
            '$class_constant_desc(pclassdesc_p.CONSTANTS, $ptascii("Z")) = (pclassconstantdesc_z)',
            '$default_cache_at(S.CLASSCONSTANTCACHE, pclassconstantdesc_z.ORIGIN) = eps',
            '$default_cache_at(F_error.MEMORY.CLASSCONSTANTCACHE, pclassconstantdesc_z.ORIGIN) = (pdefaultcache_z)',
            'F_error.MEMORY.CLASSCONSTANTCACHE = S.CLASSCONSTANTCACHE ++ [pdefaultcache_z]',
            'pdefaultcache_z.VALUE = POBJECT n_z',
            'pdefaultcache_z.CLASS = PVCLOSURE n_z porigin_site_z',
            'n_z = |S.OBJECTS|',
            'n_fcc = $(n_z + 1)',
            'S_raw.OBJECTS[n_fcc] = CONSTANTCLOSURE porigin_fcc pobject_fcc',
            '$heap_owners($heap_graph(F_error.MEMORY), HOBJECT n_fcc) = 0',
            '$heap_owners($heap_graph(F_error.MEMORY), HOBJECT n_z) = 1',
            'F_error.MEMORY.ALLOCATIONS = S.ALLOCATIONS ++ [HOBJECT n_z]',
            '$trait_cache_event_at(F_error.MEMORY.CLASSCONSTANTHISTORY, pclassconstantdesc_z.ORIGIN) = (ptraitcachecause_z)',
            'ptraitcachecause_z.CLASS = porigin_c',
            'ptraitcachecause_z.ROOT = porigin_root',
            'ptraitcachecause_z.PREFIX = |S.DECLARATIONS|',
            'ptraitcachecause_z.USERPREFIX = |S.USERCONSTANTS|',
            '|ptraitcachecause_z.LOOKUPS| = 2',
            'ptraitcachecause_z.LOOKUPS[0] = porigin_root',
            '$constant_callable_record(F_error.MEMORY.CONSTANTCLOSURES, n_z) = (pconstantclosure_z)',
            'pconstantclosure_z.DECL = pclassconstantdesc_z.ORIGIN',
            'pconstantclosure_z.SITE = porigin_site_z',
            '$closure_scope_at(F_error.MEMORY.CLOSURESCOPES, n_z) = (pclosurescope_z)',
            'pclosurescope_z.LEXICAL = porigin_p',
            'pclosurescope_z.CALLED = porigin_p',
        ] + EXPRESSION_TRACE + TERMINAL + [
            'S_failed.CLASSCONSTANTCACHE = F_error.MEMORY.CLASSCONSTANTCACHE',
            'S_failed.CLASSCONSTANTHISTORY = F_error.MEMORY.CLASSCONSTANTHISTORY',
            'S_failed.ALLOCATIONS = S.ALLOCATIONS ++ [HOBJECT n_z]',
            'S_failed.DECLARATIONS = S.DECLARATIONS ++ [PDRTRAITCACHEFAIL porigin_c $declaration_cause(S)]',
            '$trait_cache_cause_valid(S_failed, pclassconstantdesc_z.ORIGIN, ptraitcachecause_z)',
            '$constant_callable_record_valid(S_failed, pconstantclosure_z)',
            '$constant_callable_cache_valid(S_failed, pclassconstantdesc_z, pdefaultcache_z.CLASS, ptraitcachecause_z.PREFIX)',
            '~$trait_cache_cause_valid(S_failed, pclassconstantdesc_z.ORIGIN, ptraitcachecause_z[.CLASS = porigin_t])',
            '~$trait_cache_cause_valid(S_failed, pclassconstantdesc_z.ORIGIN, ptraitcachecause_z[.LOOKUPS = [porigin_root]])',
            '~$constant_callable_record_valid(S_failed, pconstantclosure_z[.DECL = pclassconstantdesc_y.ORIGIN])',
            '$heap_owners($heap_graph(S_failed), HOBJECT n_z) = 1',
            '$heap_owners($heap_graph(S_failed), HOBJECT n_fcc) = 0',
            '$default_cache_at(S_done.CLASSCONSTANTCACHE, pclassconstantdesc_z.ORIGIN) = (pdefaultcache_z)',
            '$heap_owners($heap_graph(S_done), HOBJECT n_z) = 1',
            '$heap_owners($heap_graph(S_done), HOBJECT n_fcc) = 0',
            '$review_trait_initializer_output(S_done.EVENTS) = $ptascii("PRE;S;P:P;")',
        ],
    },
}

if __name__ == '__main__':
    protocol.run(CASES, (Path(__file__).resolve(), CATALOGUE, HELPERS))
