#!/usr/bin/env python3
"""Source-bound cold Closure filling beside a genuine warm foreign cache."""
from pathlib import Path
import json

import closure_call_protocol as protocol

HERE = Path(__file__).resolve().parent
CATALOGUE = HERE / 'trait_data_public_object_foreign_review_cases.json'
DIM = HERE / 'trait_data_public_object_dim_review_cases.json'
SOURCE = json.loads(CATALOGUE.read_text())['cases'][0]['source']
DIM_SOURCE = json.loads(DIM.read_text())['cases'][0]['source']

CASES = {
    'public-closure-cache-keeps-full-source-and-distinct-foreign-owner': {
        'source': SOURCE,
        'stage': ('S.TODO = (STMT (NStmtClass phpType14 phpType24 phpType3 phpType44 phpType42 phpType23 metadata)) :: ptask_tail* '
                  '-- if S.ORIGIN = (porigin_c) '
                  '-- if $class_at(S.CLASSES, porigin_c) = (pclassdesc_c) '
                  '-- if pclassdesc_c.NAME = $ptascii("C")'),
        'checks': [
            'S.CURRENT = eps',
            'S.FRAMES = eps',
            '$call_descriptors_valid(S)',
            '$declaration_history_valid(S)',
            '$class_constant_state_valid(S)',
            '$constant_callable_records_valid(S, S.CONSTANTCLOSURES)',
            '$heap_valid($heap_graph(S))',
            '$class_named(S.CLASSNAMES, $ptascii("c")) = eps',
            '$class_named(S.CLASSNAMES, $ptascii("p")) = (porigin_p)',
            '$class_at(S.CLASSES, porigin_p) = (pclassdesc_p)',
            '$class_constant_desc(pclassdesc_p.CONSTANTS, $ptascii("Y")) = (pclassconstantdesc_y)',
            '$class_constant_desc(pclassdesc_p.CONSTANTS, $ptascii("Z")) = (pclassconstantdesc_z)',
            'pclassconstantdesc_y.OWNER = porigin_p',
            'pclassconstantdesc_z.OWNER = porigin_p',
            '$default_cache_at(S.CLASSCONSTANTCACHE, pclassconstantdesc_y.ORIGIN) = eps',
            '$default_cache_at(S.CLASSCONSTANTCACHE, pclassconstantdesc_z.ORIGIN) = (pdefaultcache_z)',
            'pdefaultcache_z.VALUE = POBJECT n_z',
            'pdefaultcache_z.CLASS = PVCLOSURE n_z porigin_site_z',
            '$lookup(S.ENV, $ptascii("z")) = (n_cell_z)',
            'S.STORE[n_cell_z] = DEFINED (POBJECT n_z)',
            '$heap_owners($heap_graph(S), HOBJECT n_z) = 2',
            '$constant_callable_record(S.CONSTANTCLOSURES, n_z) = (pconstantclosure_z)',
            'pconstantclosure_z.DECL = pclassconstantdesc_z.ORIGIN',
            '$constant_callable_record_valid(S, pconstantclosure_z)',
            'S_after = $activate_class(S[.TODO = ptask_tail*], pclassdesc_c)',
            'S_after.COMPLETION = NORMAL',
            '$class_named(S_after.CLASSNAMES, $ptascii("c")) = (porigin_c)',
            '$default_cache_at(S_after.CLASSCONSTANTCACHE, pclassconstantdesc_y.ORIGIN) = (pdefaultcache_y)',
            'pdefaultcache_y.VALUE = POBJECT n_y',
            'pdefaultcache_y.CLASS = PVCLOSURE n_y porigin_site_y',
            'S_after.CLASSCONSTANTCACHE = S.CLASSCONSTANTCACHE ++ [pdefaultcache_y]',
            'n_y =/= n_z',
            'porigin_site_y =/= porigin_site_z',
            '$default_cache_at(S_after.CLASSCONSTANTCACHE, pclassconstantdesc_z.ORIGIN) = (pdefaultcache_z)',
            'S_after.OBJECTS[n_z] = S.OBJECTS[n_z]',
            '$heap_owners($heap_graph(S_after), HOBJECT n_z) = 2',
            '$heap_owners($heap_graph(S_after), HOBJECT n_y) = 1',
            '$heap_count(HOBJECT n_y, $class_constant_roots(S_after.CLASSCONSTANTCACHE)) = 1',
            '$constant_callable_record(S_after.CONSTANTCLOSURES, n_y) = (pconstantclosure_y)',
            'pconstantclosure_y.DECL = pclassconstantdesc_y.ORIGIN',
            'pconstantclosure_y.SITE = porigin_site_y',
            'pconstantclosure_y.PREFIX = |S.DECLARATIONS|',
            '$constant_callable_record_valid(S_after, pconstantclosure_y)',
            '~$constant_callable_record_valid(S_after, pconstantclosure_y[.DECL = pclassconstantdesc_z.ORIGIN])',
            '~$constant_callable_record_valid(S_after, pconstantclosure_y[.PREFIX = 0])',
            '$closure_scope_at(S_after.CLOSURESCOPES, n_y) = (pclosurescope_y)',
            'pclosurescope_y.LEXICAL = porigin_p',
            'pclosurescope_y.CALLED = porigin_p',
            'pclosurescope_y.RECEIVER = eps',
            '$trait_cache_event_at(S_after.CLASSCONSTANTHISTORY, pclassconstantdesc_y.ORIGIN) = (ptraitcachecause_y)',
            'ptraitcachecause_y.CLASS = porigin_c',
            'ptraitcachecause_y.PREFIX = |S.DECLARATIONS|',
            'ptraitcachecause_y.USERPREFIX = |S.USERCONSTANTS|',
            'ptraitcachecause_y.LOOKUPS = [ptraitcachecause_y.ROOT]',
            '$trait_cache_cause_valid(S_after, pclassconstantdesc_y.ORIGIN, ptraitcachecause_y)',
            '$constant_callable_cache_valid(S_after, pclassconstantdesc_y, pdefaultcache_y.CLASS, ptraitcachecause_y.PREFIX)',
            '~$constant_callable_cache_valid(S_after, pclassconstantdesc_y, pdefaultcache_z.CLASS, ptraitcachecause_y.PREFIX)',
            '$call_descriptors_valid(S_after)',
            '$declaration_history_valid(S_after)',
            '$class_constant_state_valid(S_after)',
            '$constant_callable_records_valid(S_after, S_after.CONSTANTCLOSURES)',
            '$heap_valid($heap_graph(S_after))',
            'S_foreign = S_after[.CLASSCONSTANTCACHE = S.CLASSCONSTANTCACHE ++ [pdefaultcache_y[.VALUE = pdefaultcache_z.VALUE][.CLASS = pdefaultcache_z.CLASS]]]',
            '~$class_constant_state_valid(S_foreign)',
            'S_done = $drive(S_after, 3000)',
            'S_done.COMPLETION = COMPLETE',
            '$default_cache_at(S_done.CLASSCONSTANTCACHE, pclassconstantdesc_y.ORIGIN) = (pdefaultcache_y)',
            '$default_cache_at(S_done.CLASSCONSTANTCACHE, pclassconstantdesc_z.ORIGIN) = (pdefaultcache_z)',
            '$call_descriptors_valid(S_done)',
            '$declaration_history_valid(S_done)',
            '$class_constant_state_valid(S_done)',
            '$constant_callable_records_valid(S_done, S_done.CONSTANTCLOSURES)',
            '$heap_valid($heap_graph(S_done))',
        ],
    },
    'literal-dim-keeps-last-replacing-fcc-source-and-retires-earlier-owner': {
        'source': DIM_SOURCE,
        'stage': ('S.TODO = (STMT (NStmtClass phpType14 phpType24 phpType3 phpType44 phpType42 phpType23 metadata)) :: ptask_tail* '
                  '-- if S.ORIGIN = (porigin_c) '
                  '-- if $class_at(S.CLASSES, porigin_c) = (pclassdesc_c) '
                  '-- if pclassdesc_c.NAME = $ptascii("C")'),
        'checks': [
            '$call_descriptors_valid(S)',
            '$declaration_history_valid(S)',
            '$class_constant_state_valid(S)',
            '$constant_callable_records_valid(S, S.CONSTANTCLOSURES)',
            '$heap_valid($heap_graph(S))',
            '$class_named(S.CLASSNAMES, $ptascii("p")) = (porigin_p)',
            '$class_at(S.CLASSES, porigin_p) = (pclassdesc_p)',
            '$class_constant_desc(pclassdesc_p.CONSTANTS, $ptascii("Y")) = (pclassconstantdesc_y)',
            '$default_cache_at(S.CLASSCONSTANTCACHE, pclassconstantdesc_y.ORIGIN) = eps',
            'S_after = $activate_class(S[.TODO = ptask_tail*], pclassdesc_c)',
            'S_after.COMPLETION = NORMAL',
            '$default_cache_at(S_after.CLASSCONSTANTCACHE, pclassconstantdesc_y.ORIGIN) = (pdefaultcache_y)',
            'pdefaultcache_y.VALUE = POBJECT n_y',
            'pdefaultcache_y.CLASS = PVCLOSURE n_y porigin_selected',
            'n_old = |S.OBJECTS|',
            'n_y = $(n_old + 1)',
            '$constant_callable_record(S_after.CONSTANTCLOSURES, n_old) = (pconstantclosure_old)',
            '$constant_callable_record(S_after.CONSTANTCLOSURES, n_y) = (pconstantclosure_selected)',
            'S_after.CONSTANTCLOSURES = S.CONSTANTCLOSURES ++ [pconstantclosure_old, pconstantclosure_selected]',
            'pconstantclosure_old.DECL = pclassconstantdesc_y.ORIGIN',
            'pconstantclosure_selected.DECL = pclassconstantdesc_y.ORIGIN',
            'pconstantclosure_old.SITE =/= porigin_selected',
            'pconstantclosure_selected.SITE = porigin_selected',
            'pconstantclosure_old.PREFIX = |S.DECLARATIONS|',
            'pconstantclosure_selected.PREFIX = |S.DECLARATIONS|',
            '$constant_callable_record_valid(S_after, pconstantclosure_old)',
            '$constant_callable_record_valid(S_after, pconstantclosure_selected)',
            '$constant_callable_flow(S_after, pconstantclosure_old.SITE, porigin_p, PVCLOSURE n_old pconstantclosure_old.SITE, pconstantclosure_old.PREFIX, eps)',
            '$trait_cache_dim_source(S_after, $constant_child(pclassconstantdesc_y.INITIALIZER, [PCFIELD 0]), KINT 0, porigin_p, |S.DECLARATIONS|) = (porigin_selected)',
            '$constant_callable_cache_valid(S_after, pclassconstantdesc_y, pdefaultcache_y.CLASS, |S.DECLARATIONS|)',
            '~$constant_callable_cache_valid(S_after, pclassconstantdesc_y, PVCLOSURE n_old pconstantclosure_old.SITE, |S.DECLARATIONS|)',
            '~((HOBJECT n_old) <- S_after.ALLOCATIONS)',
            '$heap_owners($heap_graph(S_after), HOBJECT n_old) = 0',
            '$heap_owners($heap_graph(S_after), HOBJECT n_y) = 1',
            'S_after.ALLOCATIONS = S.ALLOCATIONS ++ [HOBJECT n_y]',
            '$call_descriptors_valid(S_after)',
            '$declaration_history_valid(S_after)',
            '$class_constant_state_valid(S_after)',
            '$constant_callable_records_valid(S_after, S_after.CONSTANTCLOSURES)',
            '$heap_valid($heap_graph(S_after))',
            'S_done = $drive(S_after, 3000)',
            'S_done.COMPLETION = COMPLETE',
            '$default_cache_at(S_done.CLASSCONSTANTCACHE, pclassconstantdesc_y.ORIGIN) = (pdefaultcache_y)',
            '$heap_owners($heap_graph(S_done), HOBJECT n_old) = 0',
            '$heap_owners($heap_graph(S_done), HOBJECT n_y) = 2',
            '$class_constant_state_valid(S_done)',
            '$constant_callable_records_valid(S_done, S_done.CONSTANTCLOSURES)',
            '$heap_valid($heap_graph(S_done))',
        ],
    },
}

if __name__ == '__main__':
    protocol.run(CASES, (Path(__file__).resolve(), CATALOGUE, DIM))
