"""Reached cast aliases, selected copies, SEND owners and ASSIGN retirement."""
from error_handler_protocol import PREFIX

GUARDS = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
          '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))']
FINISH = [
    'S_done = $drive(S, 3000)', 'S_done.COMPLETION = NORMAL',
    'S_done.TODO = eps', 'S_done.CURRENT = eps', 'S_done.FRAMES = eps',
    'S_done.BORROWEDREAD = eps', 'S_done.HELD = eps', 'S_done.TRACE = eps',
    'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
    '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))',
    'S_done = $drive(S_initial[.COMPLETION = NORMAL], 3000)',
]
NULL_READ = [
    'S.TODO = (ERROR_READ_RESULT perrorread) :: ptask_tail*',
    'perrorread.INPUT = VARIABLE perrorread.NAME z_variable',
    'perrorread.RESULT = KNOWN PNULL', 'perrorread.TASK = perrorread.ORIGINAL',
    '$error_read_valid(S, perrorread)',
    '$call_task_valid(S, ERROR_READ_RESULT perrorread)',
    '~$error_read_valid(S, perrorread[.RESULT = KNOWN (PINT 9)])',
    '~$error_read_valid(S, perrorread[.NAME = $ptascii("forged213")])',
    '~$error_read_valid(S, perrorread[.LINE = 999])',
    'S.CURRENT = eps', 'S.FRAMES = eps', 'S.BORROWEDREAD = eps',
    'S.ORIGIN = (porigin)',
    'PhpStep: S ~> S_resume', 'S_resume.RESULT = KNOWN PNULL',
    'S_resume.TODO = perrorread.TASK :: ptask_tail*',
]
CASES = [
    ('cast-null-before-aliased-destination-write', 'casts-through-callback-created-alias',
     'S.TODO = (ERROR_READ_RESULT perrorread) :: ptask_tail* -- if perrorread.ORIGINAL = CAST_RESULT CASTARRAY z', [
        *NULL_READ,
        'perrorread.ORIGINAL = CAST_RESULT CASTARRAY z',
        'perrorread.NAME = $ptascii("missing213")',
        '$origin_node(S.SOURCES, porigin) = (NExprCastArray expression metadata)',
        '$error_variable_source(S, S.ORIGIN, [PCFIELD 0], perrorread.NAME)',
        '$lookup(S.ENV, perrorread.NAME) = (n_cell)',
        '$lookup(S.ENV, $ptascii("other213")) = (n_cell)',
        'S.STORE[n_cell] = DEFINED (PINT 9)',
        'n_cell <- S.REFCELLS',
        '$heap_owners($heap_graph(S), HCELL n_cell) = 2',
        '~$error_read_valid(S, perrorread[.ORIGINAL = CAST_RESULT CASTOBJECT z][.TASK = CAST_RESULT CASTOBJECT z])',
        'n_array = |S.ARRAYS|',
        'PhpStep: S_resume ~> S_cast',
        'S_cast.COMPLETION = NORMAL', 'S_cast.RESULT = KNOWN (PARRAY n_array)',
        'S_cast.ARRAYS[n_array].ITEMS = eps', '(HARRAY n_array) <- S_cast.ALLOCATIONS',
        '$heap_owners($heap_graph(S_cast), HARRAY n_array) = 1',
        'S_cast.STORE[n_cell] = DEFINED (PINT 9)',
        '$heap_valid($heap_graph(S_cast))',
        *GUARDS, *FINISH,
    ]),
    ('copy-keeps-actual-folded-arm', 'selected-copy-folded-runtime-and-throw',
     'S.TODO = (ERROR_READ_RESULT perrorread) :: ptask_tail*', [
        *NULL_READ,
        'perrorread.ORIGINAL = VALUE_COPY z', 'perrorread.NAME = $ptascii("left213")',
        '$origin_node(S.SOURCES, porigin) = (NExprTernary expression_cond expression_left expression_right metadata)',
        '$compiled_redirect(S, porigin) = ((porigin_target, expression_left, false, z_parent))',
        '$origin_child(S.ORIGIN, [PCFIELD 1]) = (porigin_target)',
        '$compiled_copy_redirect(S, porigin) = (z)',
        '$error_copy_selected(S, porigin, [PCFIELD 1])',
        '~$error_copy_selected(S, porigin, [PCFIELD 2])',
        'perrorread.LINE = z',
        '$lookup(S.ENV, perrorread.NAME) = (n_left)',
        'S.STORE[n_left] = DEFINED (PINT 9)',
        '$lookup(S.ENV, $ptascii("right213")) = (n_right)',
        'S.STORE[n_right] = DEFINED (PINT 8)',
        'perrorread_other = perrorread[.NAME = $ptascii("right213")][.INPUT = VARIABLE $ptascii("right213") z_variable]',
        '~$error_read_valid(S, perrorread_other)',
        'PhpStep: S_resume ~> S_copy',
        'S_copy.COMPLETION = NORMAL', 'S_copy.RESULT = KNOWN PNULL',
        'S_copy.TODO = ptask_tail*',
        'S_copy.STORE[n_left] = DEFINED (PINT 9)',
        'S_copy.STORE[n_right] = DEFINED (PINT 8)',
        *GUARDS, *FINISH,
    ]),
    ('selected-closure-and-prior-array-root', 'positional-send-retains-closure-and-array',
     'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* -- if S.CURRENT = (pcallcontext) -- if pcallcontext.ARGC = 4', [
        'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail*',
        'pargcall.KIND = INTRINSIC_FUNC_NUM_ARGS',
        '$call_task_valid(S, ARGINFO_INVOKE pargcall)',
        'S.CURRENT = (pcallcontext)', 'pcallcontext.TARGET = CLOSURE_TARGET n_handler',
        'pcallcontext.ARGC = 4',
        '$target_function(S, pcallcontext.TARGET) = (pfunction_handler)',
        'S.CVS = pfunction_handler.CVS', 'S.ERRORHANDLER.CALLBACK = eps',
        'S.BORROWEDREAD = eps', 'S.FRAMES = [pframe]',
        'pframe.CONTEXT = eps', 'pframe.BORROWEDREAD = eps',
        'pframe.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_saved*',
        'perrorcall.TARGET = (pcallcontext.TARGET)',
        'perrorcall.RESUME = ERROR_READ_RESULT perrorread',
        'perrorread.ORIGINAL = CALL_SEND (CLOSURE_TARGET n_selected) eps 1 ([KNOWN (PARRAY n_snapshot)]) (porigin) z',
        'perrorread.TASK = perrorread.ORIGINAL', 'perrorread.RESULT = KNOWN PNULL',
        'perrorread.NAME = $ptascii("missing213")',
        'S_caller = S[.CURRENT = pframe.CONTEXT][.FRAMES = eps][.ORIGIN = pframe.ORIGIN][.TODO = pframe.TODO][.BORROWEDREAD = pframe.BORROWEDREAD]',
        'S_caller.ORIGIN = (porigin)',
        '$error_read_valid(S_caller, perrorread)', '$error_entered_call_valid(S_caller, perrorcall)',
        '$error_context_valid(S, pcallcontext)',
        '$arginfo_values(S, pcallcontext) = $error_handler_values(S, perrorcall)',
        '$call_task_valid(S_caller, perrorread.TASK)',
        '$target_function(S, CLOSURE_TARGET n_selected) = (pfunction_selected)',
        'S.ARRAYS[n_snapshot].ITEMS = [ENTRY (KINT 0) (DIRECT (PINT 1))]',
        '$heap_owners($heap_graph(S), HARRAY n_snapshot) = 1',
        '$heap_owners($heap_graph(S), HOBJECT n_selected) = 1',
        'S_global = $global_table_view(S)',
        '$lookup(S_global.ENV, $ptascii("seed213")) = (n_seed)',
        'S.STORE[n_seed] = DEFINED (PARRAY n_live_array)',
        'n_live_array =/= n_snapshot',
        'S.ARRAYS[n_live_array].ITEMS = [ENTRY (KINT 0) (DIRECT (PINT 1)), ENTRY (KINT 1) (DIRECT (PINT 2))]',
        '$lookup(S_global.ENV, $ptascii("callee213")) = (n_callee)',
        'S.STORE[n_callee] = DEFINED PNULL',
        '~$call_current_valid(S[.CURRENT = (pcallcontext[.ARGC = 0])])',
        '~$call_current_valid(S[.CVS = eps])',
        '~$error_read_valid(S_caller, perrorread[.ORIGINAL = CALL_SEND (CLOSURE_TARGET 999) eps 1 ([KNOWN (PARRAY n_snapshot)]) (porigin) z][.TASK = CALL_SEND (CLOSURE_TARGET 999) eps 1 ([KNOWN (PARRAY n_snapshot)]) (porigin) z])',
        '~$call_frames_valid(S, [pframe[.TODO = (ERROR_HANDLER_RESULT perrorcall[.RESUME = ERROR_READ_RESULT perrorread[.RESULT = KNOWN (PINT 9)]]) :: ptask_saved*]])',
        *GUARDS, *FINISH,
    ]),
    ('nullable-typed-alias-retains-pending-throw', 'direct-assign-nullable-typed-alias-on-throw',
     'S.TODO = (THROW_SEARCH n_throw) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail* -- if S.CURRENT = eps -- if S.FRAMES = eps', [
        'S.TODO = (THROW_SEARCH n_throw) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail*',
        'S.CURRENT = eps', 'S.FRAMES = eps', 'S.BORROWEDREAD = eps',
        'perrorcall.RESUME = ERROR_READ_RESULT perrorread',
        'perrorcall.CALLBACK = POBJECT n_handler',
        'perrorread.ORIGINAL = WRITE_NAME $ptascii("destination213") z',
        'perrorread.TASK = perrorread.ORIGINAL', 'perrorread.RESULT = KNOWN PNULL',
        '$error_read_valid(S, perrorread)', '$error_entered_call_valid(S, perrorcall)',
        '$call_task_valid(S, ERROR_HANDLER_RESULT perrorcall)',
        '$lookup(S.ENV, $ptascii("destination213")) = (n_cell)',
        'S.STORE[n_cell] = DEFINED (PINT 7)', 'n_cell <- S.REFCELLS',
        '$propref_at(S.PROPREFS, n_cell) = (ppropref)', 'ppropref.SOURCES =/= eps',
        '$heap_owners($heap_graph(S), HCELL n_cell) = 2',
        'S.OBJECTS[n_throw] = THROWABLE pthrowable', 'pthrowable.KIND = "Error"',
        '~$error_read_valid(S, perrorread[.ORIGINAL = WRITE_NAME $ptascii("forged213") z][.TASK = WRITE_NAME $ptascii("forged213") z])',
        'PhpStep: S ~> S_written', 'S_written.COMPLETION = NORMAL',
        'S_written.TODO = (THROW_SEARCH n_throw) :: ptask_tail*',
        'S_written.STORE[n_cell] = DEFINED PNULL',
        'S_written.OBJECTS[n_throw] = S.OBJECTS[n_throw]',
        'S_written.ERRORHANDLER.CALLBACK = (POBJECT n_handler)',
        '$propref_at(S_written.PROPREFS, n_cell) = (ppropref)',
        '$call_descriptors_valid(S_written)', '$heap_valid($heap_graph(S_written))',
        *GUARDS, *FINISH,
    ]),
]
