"""Reached global/local separation, nested borrowed reads and throw retirement."""
from error_handler_protocol import PREFIX

GUARDS = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
          '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))']
FINISH = [
    'S_done = $drive(S, 1500)', 'S_done.COMPLETION = NORMAL',
    'S_done.TODO = eps', 'S_done.FRAMES = eps', 'S_done.CURRENT = eps',
    'S_done.BORROWEDREAD = eps', 'S_done.TRACE = eps',
    'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
    '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))',
    'S_done = $drive(S_initial[.COMPLETION = NORMAL], 1500)',
]

CASES = [
    ('globals-borrow-and-local-shadow', 'globals-root-and-handler-local',
     'S.TODO = (EMIT z) :: ptask_tail* -- if S.RESULT = VARIABLE ($ptascii("a")) z_variable -- if S.CURRENT = (pcallcontext) -- if pcallcontext.NAME = $ptascii("warningReadGlobals13")', [
         'S.CURRENT = (pcallcontext)',
         'pcallcontext.NAME = $ptascii("warningReadGlobals13")',
         'pcallcontext.ARGC = 4', 'pcallcontext.INSTANCE = eps',
         'S.BORROWEDREAD = eps', 'S.FRAMES = [pframe]',
         'pframe.CONTEXT = eps', 'pframe.LOCALS = eps',
         'pframe.BORROWEDREAD = (pidentityread)',
         'pframe.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_saved*',
         'perrorcall.RESUME = ERROR_IDENTITY_RESULT pidentityread',
         'perrorcall.TARGET = (pcallcontext.TARGET)',
         'pidentityread.OP = IDENTICAL',
         'pidentityread.LEFT = $ptascii("a")', 'pidentityread.RIGHT = $ptascii("missing")',
         'S_caller = S[.CURRENT = eps][.FRAMES = eps][.ORIGIN = pframe.ORIGIN][.TODO = pframe.TODO][.BORROWEDREAD = pframe.BORROWEDREAD]',
         '$identity_read_valid(S_caller, pidentityread)',
         '$error_entered_call_valid(S_caller, perrorcall)',
         '$error_context_valid(S, pcallcontext)',
         '$lookup(S.ENV, $ptascii("a")) = (n_local)',
         'S.STORE[n_local] = DEFINED (PINT 5)',
         'S_global = $global_table_view(S)',
         '$lookup(S_global.ENV, $ptascii("a")) = (n_rebound)',
         '$lookup(S_global.ENV, $ptascii("y")) = (n_rebound)',
         'n_rebound =/= pidentityread.CELL',
         'S.STORE[n_rebound] = DEFINED (PINT 9)',
         '$lookup(S_global.ENV, $ptascii("x")) = (pidentityread.CELL)',
         'S.STORE[pidentityread.CELL] = DEFINED PNULL',
         '$heap_owners($heap_prune($heap_graph(S)), HCELL pidentityread.CELL) = 1',
         '~((HCELL pidentityread.CELL) <- $task_nodes(perrorcall.RESUME))',
         '~$error_entered_call_valid(S_caller, perrorcall[.RESUME = ERROR_IDENTITY_RESULT pidentityread[.CELL = n_rebound]])',
         '~$call_current_valid(S[.FRAMES = [pframe[.BORROWEDREAD = eps]]])',
         '~$call_frames_valid(S, [pframe[.TODO = ptask_saved*]])',
         *GUARDS, *FINISH,
     ]),
    ('nested-borrowed-arginfo', 'nested-borrow-normal',
     'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail*', [
         'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail*',
         'pargcall.KIND = INTRINSIC_FUNC_NUM_ARGS',
         '$call_task_valid(S, ARGINFO_INVOKE pargcall)',
         'S.CURRENT = (pcallcontext)', 'pcallcontext.TARGET = CLOSURE_TARGET n_inner',
         'pcallcontext.INSTANCE = (n_inner)', 'pcallcontext.ARGC = 4',
         '$target_function(S, pcallcontext.TARGET) = (pfunction)', 'S.CVS = pfunction.CVS',
         'S.BORROWEDREAD = eps', 'S.ERRORHANDLER.CALLBACK = eps',
         'S.FRAMES = [pframe_inner, pframe_outer]',
         'pframe_inner.CONTEXT = (pcallcontext_outer)',
         'pframe_inner.BORROWEDREAD = (pidentityread_inner)',
         'pframe_outer.BORROWEDREAD = (pidentityread_outer)',
         'pframe_inner.TODO = (ERROR_HANDLER_RESULT perrorcall_inner) :: ptask_inner*',
         'pframe_outer.TODO = (ERROR_HANDLER_RESULT perrorcall_outer) :: ptask_outer*',
         'perrorcall_inner.RESUME = ERROR_IDENTITY_RESULT pidentityread_inner',
         'perrorcall_outer.RESUME = ERROR_IDENTITY_RESULT pidentityread_outer',
         'perrorcall_inner.CALLBACK = POBJECT n_inner',
         'pcallcontext_outer.TARGET = CLOSURE_TARGET n_outer',
         'perrorcall_outer.CALLBACK = POBJECT n_outer',
         'pidentityread_inner.CELL =/= pidentityread_outer.CELL',
         'pidentityread_inner.LEFT = $ptascii("p")',
         'pidentityread_inner.RIGHT = $ptascii("inner_missing")',
         'pidentityread_outer.LEFT = $ptascii("a")',
         'pidentityread_outer.RIGHT = $ptascii("outer_missing")',
         'S.STORE[pidentityread_inner.CELL] = DEFINED PNULL',
         'S.STORE[pidentityread_outer.CELL] = DEFINED PNULL',
         '$identity_read_live(S, pidentityread_inner)', '$identity_read_live(S, pidentityread_outer)',
         '$error_context_valid(S, pcallcontext)', '$error_context_valid(S, pcallcontext_outer)',
         '$arginfo_values(S, pcallcontext) = $error_handler_values(S, perrorcall_inner)',
         '~((HCELL pidentityread_inner.CELL) <- $task_nodes(perrorcall_inner.RESUME))',
         '~((HCELL pidentityread_outer.CELL) <- $task_nodes(perrorcall_outer.RESUME))',
         '~$call_current_valid(S[.CURRENT = (pcallcontext[.ARGC = 0])])',
         '~$call_current_valid(S[.CVS = eps])',
         '~$call_current_valid(S[.FRAMES = [pframe_inner[.BORROWEDREAD = eps],pframe_outer]])',
         '~$call_frames_valid(S, [pframe_inner[.TODO = (ERROR_HANDLER_RESULT perrorcall_inner[.RESUME = ERROR_IDENTITY_RESULT pidentityread_inner[.CELL = pidentityread_outer.CELL]]) :: ptask_inner*],pframe_outer])',
         '~$call_frames_valid(S, [pframe_inner,pframe_outer[.BORROWEDREAD = (pidentityread_inner)]])',
         *GUARDS, *FINISH,
     ]),
    ('inner-throw-preserves-outer-borrow', 'nested-borrow-throw',
     'S.TODO = (EMIT z) :: ptask_tail* -- if S.RESULT = KNOWN (PSTRING ($ptascii("C")))', [
         'S.CURRENT = (pcallcontext)', 'pcallcontext.TARGET = CLOSURE_TARGET n_outer',
         'pcallcontext.ARGC = 4', 'S.BORROWEDREAD = eps',
         'S.FRAMES = [pframe_outer]', 'pframe_outer.CONTEXT = eps',
         'pframe_outer.BORROWEDREAD = (pidentityread_outer)',
         'pframe_outer.TODO = (ERROR_HANDLER_RESULT perrorcall_outer) :: ptask_outer*',
         'perrorcall_outer.RESUME = ERROR_IDENTITY_RESULT pidentityread_outer',
         'perrorcall_outer.CALLBACK = POBJECT n_outer',
         'pidentityread_outer.OP = NOTIDENTICAL',
         'pidentityread_outer.LEFT = $ptascii("a")',
         'pidentityread_outer.RIGHT = $ptascii("outer_missing")',
         'S.STORE[pidentityread_outer.CELL] = DEFINED PNULL',
         '$identity_read_live(S, pidentityread_outer)',
         '$lookup(S.ENV, $ptascii("local")) = (n_inner_cell)',
         'n_inner_cell =/= pidentityread_outer.CELL',
         'S.STORE[n_inner_cell] = DEFINED (PINT 8)',
         'S.ERRORHANDLER.CALLBACK = (POBJECT n_inner)', 'n_inner =/= n_outer',
         'S_caller = S[.CURRENT = eps][.FRAMES = eps][.ORIGIN = pframe_outer.ORIGIN][.TODO = pframe_outer.TODO][.BORROWEDREAD = pframe_outer.BORROWEDREAD]',
         '$error_entered_call_valid(S_caller, perrorcall_outer)',
         '$error_context_valid(S, pcallcontext)',
         '~$call_frames_valid(S, [pframe_outer[.BORROWEDREAD = eps]])',
         '~$call_frames_valid(S, [pframe_outer[.TODO = (ERROR_HANDLER_RESULT perrorcall_outer[.RESUME = ERROR_IDENTITY_RESULT pidentityread_outer[.CELL = n_inner_cell]]) :: ptask_outer*]])',
         *GUARDS, *FINISH,
     ]),
]
