"""Genuine reference arguments, live constraints and replacement throw chains."""
from error_handler_protocol import PREFIX

GUARDS = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
          '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))']
FINISH = [
    'S_done = $drive(S, 3000)', 'S_done.COMPLETION = NORMAL',
    'S_done.TODO = eps', 'S_done.CURRENT = eps', 'S_done.FRAMES = eps',
    'S_done.BORROWEDREAD = eps', 'S_done.HELD = eps', 'S_done.TRACE = eps',
    'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
    '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))',
    'S_done = $drive(S_initial[.COMPLETION = NORMAL], 3000)',
]

CASES = [
    ('named-created-reference-aliases', 'named-reference-shares-created-null',
     'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail* -- if S.CURRENT = (pcallcontext) -- if pcallcontext.NAME = $ptascii("namedPair220")', [
        'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail*',
        'pargcall.KIND = INTRINSIC_FUNC_NUM_ARGS',
        '$call_task_valid(S, ARGINFO_INVOKE pargcall)',
        'S.CURRENT = (pcallcontext)', 'pcallcontext.ARGC = 2',
        'pcallcontext.NAME = $ptascii("namedPair220")',
        '$target_function(S, pcallcontext.TARGET) = (pfunction)',
        'pcallcontext.FUNCTION = pfunction.ORIGIN',
        'pfunction.SIGNATURE.PARAMETERS[0].BYREF',
        'pfunction.SIGNATURE.PARAMETERS[1].BYREF',
        'pcallcontext.PARAMS = [$ptascii("first"),$ptascii("second")]',
        'pcallcontext.EXTRA = eps', 'pcallcontext.NAMED = eps',
        'S.CVS = pfunction.CVS', 'S.BORROWEDREAD = eps',
        'S.FRAMES = [pframe]', 'pframe.CONTEXT = eps',
        'pframe.BORROWEDREAD = eps',
        'pcallcontext.CALLSITE = (porigin_call)',
        '$call_argument_source(S, porigin_call) = PCALLARGUMENTS phpType7* n_field',
        'phpType7*[0] = NArg (NIdentifier (BYTES "c2Vjb25k") metadata_second) expression_second (BOOLEAN false) (BOOLEAN false) metadata_arg_second',
        'phpType7*[1] = NArg (NIdentifier (BYTES "Zmlyc3Q=") metadata_first) expression_first (BOOLEAN false) (BOOLEAN false) metadata_arg_first',
        '$named_arg_target(pfunction, phpType7*[0], 0) = NAMED_POSITION 1',
        '$named_arg_target(pfunction, phpType7*[1], 2) = NAMED_POSITION 0',
        '$lookup(S.ENV, $ptascii("first")) = (n_cell)',
        '$lookup(S.ENV, $ptascii("second")) = (n_cell)',
        'S_global = $global_table_view(S)',
        '$lookup(S_global.ENV, $ptascii("missing220")) = (n_cell)',
        'S.STORE[n_cell] = DEFINED PNULL', 'n_cell <- S.REFCELLS',
        '(HCELL n_cell) <- S.ALLOCATIONS',
        '$call_reference_operand_valid(S, REFERENCE n_cell)',
        '$heap_owners($heap_graph(S), HCELL n_cell) = 3',
        '$arginfo_values(S, pcallcontext) = [PNULL,PNULL]',
        '$lookup(S_global.ENV, $ptascii("hits220")) = (n_hits)',
        'S.STORE[n_hits] = DEFINED (PINT 0)',
        'S.ERRORHANDLER.CALLBACK = (POBJECT n_handler)',
        '~$error_context_kind(S, pcallcontext)',
        '~$call_reference_operand_valid(S[.STORE = $set_cell(S.STORE, n_cell, UNDEFINED)], REFERENCE n_cell)',
        '~$call_reference_operand_valid(S[.REFCELLS = eps], REFERENCE n_cell)',
        '~$call_current_valid(S[.CURRENT = (pcallcontext[.ARGC = 1])])',
        '~$call_current_valid(S[.CVS = eps])',
        *GUARDS, *FINISH,
    ]),
    ('normal-resume-checks-live-destination-constraint', 'returned-handler-attaches-rejecting-destination',
     'S.TODO = (ERROR_READ_RESULT perrorread) :: ptask_tail*', [
        'S.TODO = (ERROR_READ_RESULT perrorread) :: ptask_tail*',
        'S.CURRENT = eps', 'S.FRAMES = eps', 'S.BORROWEDREAD = eps',
        'perrorread.ORIGINAL = WRITE_NAME $ptascii("destination220") z',
        'perrorread.TASK = perrorread.ORIGINAL',
        'perrorread.INPUT = VARIABLE $ptascii("missing220") z_variable',
        'perrorread.RESULT = KNOWN PNULL', 'perrorread.LINE = z',
        '$error_read_valid(S, perrorread)',
        '$call_task_valid(S, ERROR_READ_RESULT perrorread)',
        'S.ORIGIN = (porigin)',
        '$origin_node(S.SOURCES, porigin) = (NExprAssign expression_left expression_right metadata)',
        '$error_variable_source(S, S.ORIGIN, [PCFIELD 0], $ptascii("destination220"))',
        '$error_variable_source(S, S.ORIGIN, [PCFIELD 1], $ptascii("missing220"))',
        '$lookup(S.ENV, $ptascii("destination220")) = (n_cell)',
        'n_cell <- S.REFCELLS', 'S.STORE[n_cell] = DEFINED (PINT 7)',
        '$propref_at(S.PROPREFS, n_cell) = (ppropref)',
        'ppropref.SOURCES =/= eps',
        '$lookup(S.ENV, $ptascii("missing220")) = (n_missing)',
        'S.STORE[n_missing] = DEFINED (PINT 9)',
        '$heap_owners($heap_graph(S), HCELL n_cell) = 2',
        'S.ERRORHANDLER.CALLBACK = (POBJECT n_handler)',
        '~$error_read_valid(S, perrorread[.RESULT = KNOWN (PINT 9)])',
        '~$error_read_valid(S, perrorread[.LINE = 999])',
        '~$error_read_valid(S, perrorread[.ORIGINAL = WRITE_NAME $ptascii("forged220") z][.TASK = WRITE_NAME $ptascii("forged220") z])',
        'PhpStep: S ~> S_resume', 'S_resume.COMPLETION = NORMAL',
        'S_resume.RESULT = KNOWN PNULL',
        'S_resume.TODO = perrorread.TASK :: ptask_tail*',
        'PhpStep: S_resume ~> S_rejected',
        'S_rejected.COMPLETION = THROWN "TypeError" preqbytes z',
        'preqbytes = $ptascii("Cannot assign null to reference held by property Attach220::$slot of type int")',
        'S_rejected.STORE[n_cell] = DEFINED (PINT 7)',
        'S_rejected.STORE[n_missing] = DEFINED (PINT 9)',
        '$propref_at(S_rejected.PROPREFS, n_cell) = (ppropref)',
        '$heap_valid($heap_graph(S_rejected))',
        *GUARDS, *FINISH,
    ]),
    ('throw-replacement-retains-exact-previous-chain', 'rejected-write-replaces-error-and-retains-previous-chain',
     'S.TODO = (THROW_SEARCH n_old) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail* -- if S.CURRENT = eps -- if S.FRAMES = eps', [
        'S.TODO = (THROW_SEARCH n_old) :: (ERROR_HANDLER_RESULT perrorcall) :: ptask_tail*',
        'S.CURRENT = eps', 'S.FRAMES = eps', 'S.BORROWEDREAD = eps',
        'perrorcall.RESUME = ERROR_READ_RESULT perrorread',
        'perrorcall.CALLBACK = POBJECT n_handler',
        'perrorread.ORIGINAL = WRITE_NAME $ptascii("destination220") z',
        'perrorread.TASK = perrorread.ORIGINAL',
        'perrorread.INPUT = VARIABLE $ptascii("missing220") z_variable',
        'perrorread.RESULT = KNOWN PNULL', 'perrorread.LINE = z',
        '$error_read_valid(S, perrorread)', '$error_entered_call_valid(S, perrorcall)',
        '$call_task_valid(S, ERROR_HANDLER_RESULT perrorcall)',
        'S.ORIGIN = (porigin)',
        '$lookup(S.ENV, $ptascii("destination220")) = (n_cell)',
        'S.STORE[n_cell] = DEFINED (PINT 7)', 'n_cell <- S.REFCELLS',
        '$propref_at(S.PROPREFS, n_cell) = (ppropref)',
        'ppropref.SOURCES =/= eps',
        '$heap_owners($heap_graph(S), HCELL n_cell) = 2',
        '$lookup(S.ENV, $ptascii("pending220")) = (n_pending)',
        'S.STORE[n_pending] = DEFINED (POBJECT n_old)',
        '$lookup(S.ENV, $ptascii("seed220")) = (n_seed_cell)',
        'S.STORE[n_seed_cell] = DEFINED (POBJECT n_seed)',
        '$throwable_field(S, n_old, "previous") = POBJECT n_seed',
        '$throwable_field(S, n_seed, "previous") = PNULL',
        '$throwable_chain(S, n_old, eps) = THROWCHAIN ([n_old,n_seed])',
        '~$error_read_valid(S, perrorread[.LINE = z_variable])',
        '~$error_read_valid(S, perrorread[.RESULT = KNOWN (PINT 9)])',
        'n_new = |S.OBJECTS|',
        'PhpStep: S ~> S_replaced', 'S_replaced.COMPLETION = NORMAL',
        'S_replaced.TODO = (THROW_SEARCH n_new) :: ptask_tail*',
        'S_replaced.RESULT = KNOWN PNULL',
        'S_replaced.BASE = BASE_VALUE (KNOWN PNULL)', 'S_replaced.HELD = eps',
        'S_replaced.ORIGIN = S.ORIGIN',
        'S_replaced.OBJECTS[n_new] = THROWABLE pthrowable',
        'pthrowable.KIND = "TypeError"', 'pthrowable.ORIGIN = (porigin)',
        '$throwable_field(S_replaced, n_new, "previous") = POBJECT n_old',
        '$throwable_field(S_replaced, n_old, "previous") = POBJECT n_seed',
        '$throwable_chain(S_replaced, n_new, eps) = THROWCHAIN ([n_new,n_old,n_seed])',
        '$throwable_field(S_replaced, n_new, "line") = PINT z',
        '$throwable_field(S_replaced, n_new, "file") = PSTRING $call_sourcefile(S.FILES, porigin)',
        '$throwable_field(S_replaced, n_new, "trace") = PARRAY n_trace',
        'S_replaced.ARRAYS[n_trace].ITEMS = eps',
        'S_replaced.STORE[n_cell] = DEFINED (PINT 7)',
        '$propref_at(S_replaced.PROPREFS, n_cell) = (ppropref)',
        'S_replaced.ERRORHANDLER.CALLBACK = (POBJECT n_handler)',
        '$throwable_live(S_replaced, n_new)',
        '$call_descriptors_valid(S_replaced)', '$heap_valid($heap_graph(S_replaced))',
        'S_pending = S[.TODO = (THROW_SEARCH n_old) :: ptask_tail*]',
        'S_write = $scope_write_name(S_pending, [PCFIELD 0], $ptascii("destination220"), PNULL)',
        'S_write.COMPLETION = THROWN "TypeError" preqbytes z',
        'S_unsupported = S_write[.COMPLETION = UNSUPPORTED "check propagation"]',
        '$error_assign_rejected(S_pending, S_unsupported) = S_unsupported',
        'S_cycle = $throwable_set_previous_id(S_pending, n_old, (n_old))',
        'S_cycle_write = $scope_write_name(S_cycle, [PCFIELD 0], $ptascii("destination220"), PNULL)',
        '$error_assign_rejected(S_cycle, S_cycle_write).COMPLETION = UNSUPPORTED "invalid Throwable previous chain"',
        *GUARDS, *FINISH,
    ]),
]
