"""Reached source-certified loop, short-circuit and ternary warning consumers."""
from error_handler_protocol import PREFIX

GUARDS = ['$call_current_valid(S)', '$call_frames_valid(S, S.FRAMES)',
          '$call_descriptors_valid(S)', '$heap_valid($heap_graph(S))']
FINISH = [
    'S_done = $drive(S, 1800)', 'S_done.COMPLETION = NORMAL',
    'S_done.TODO = eps', 'S_done.CURRENT = eps', 'S_done.FRAMES = eps',
    'S_done.BORROWEDREAD = eps', 'S_done.TRACE = eps',
    'S_done.ERRORHANDLER.CALLBACK = eps', 'S_done.ERRORHANDLERS = eps',
    '$call_descriptors_valid(S_done)', '$heap_valid($heap_graph(S_done))',
    'S_done = $drive(S_initial[.COMPLETION = NORMAL], 1800)',
]
NULL_READ = [
    'S.TODO = (ERROR_READ_RESULT perrorread) :: ptask_tail*',
    'perrorread.INPUT = VARIABLE perrorread.NAME z_variable',
    'perrorread.RESULT = KNOWN PNULL', 'perrorread.TASK = perrorread.ORIGINAL',
    '$error_read_valid(S, perrorread)',
    '$call_task_valid(S, ERROR_READ_RESULT perrorread)',
    '~$error_read_valid(S, perrorread[.RESULT = KNOWN (PINT 7)])',
    '~$error_read_valid(S, perrorread[.NAME = $ptascii("forged209")])',
    '~$error_read_valid(S, perrorread[.LINE = 999])',
    '$lookup(S.ENV, perrorread.NAME) = (n_live)',
    'S.STORE[n_live] = DEFINED (PINT 7)',
    'S.CURRENT = eps', 'S.FRAMES = eps', 'S.BORROWEDREAD = eps',
    'PhpStep: S ~> S_resume', 'S_resume.RESULT = KNOWN PNULL',
    'S_resume.BASE = perrorread.BASE',
    'S_resume.TODO = perrorread.TASK :: ptask_tail*',
    'S_resume.STORE[n_live] = DEFINED (PINT 7)',
]

CASES = [
    ('loop-handler-saved-consumer', 'while-do-for-original-null',
     'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail*', [
        'S.TODO = (ARGINFO_INVOKE pargcall) :: ptask_tail*',
        'pargcall.KIND = INTRINSIC_FUNC_NUM_ARGS',
        '$call_task_valid(S, ARGINFO_INVOKE pargcall)',
        'S.CURRENT = (pcallcontext)', 'pcallcontext.TARGET = CLOSURE_TARGET n_handler',
        'pcallcontext.INSTANCE = (n_handler)', 'pcallcontext.ARGC = 4',
        '$target_function(S, pcallcontext.TARGET) = (pfunction)', 'S.CVS = pfunction.CVS',
        'S.BORROWEDREAD = eps', 'S.ERRORHANDLER.CALLBACK = eps',
        'S.FRAMES = [pframe]', 'pframe.CONTEXT = eps', 'pframe.BORROWEDREAD = eps',
        'pframe.TODO = (ERROR_HANDLER_RESULT perrorcall) :: ptask_saved*',
        'perrorcall.RESUME = ERROR_READ_RESULT perrorread',
        'perrorcall.TARGET = (pcallcontext.TARGET)', 'perrorcall.CALLBACK = POBJECT n_handler',
        'perrorread.NAME = $ptascii("while209")',
        'perrorread.ORIGINAL = CHOOSE ptask_true* eps z',
        'perrorread.TASK = perrorread.ORIGINAL', 'perrorread.RESULT = KNOWN PNULL',
        'S_caller = S[.CURRENT = eps][.FRAMES = eps][.ORIGIN = pframe.ORIGIN][.TODO = pframe.TODO][.BORROWEDREAD = pframe.BORROWEDREAD]',
        'S_caller.ORIGIN = (porigin)',
        '$origin_node(S.SOURCES, porigin) = (NStmtWhile expression phpType23 metadata)',
        'ptask_true* = $loop_body_tasks(NStmtWhile expression phpType23 metadata, S_caller.ORIGIN)',
        'z = $runtime_line(S_caller, [PCFIELD 0], expression)', 'perrorread.LINE = z',
        '$error_variable_source(S_caller, S_caller.ORIGIN, [PCFIELD 0], perrorread.NAME)',
        '$error_read_valid(S_caller, perrorread)', '$error_entered_call_valid(S_caller, perrorcall)',
        '$error_context_valid(S, pcallcontext)',
        '$arginfo_values(S, pcallcontext) = $error_handler_values(S, perrorcall)',
        'S_global = $global_table_view(S)',
        '$lookup(S_global.ENV, perrorread.NAME) = (n_live)',
        'S.STORE[n_live] = DEFINED (PINT 7)',
        '~$error_read_valid(S_caller, perrorread[.ORIGINAL = CHOOSE eps eps z][.TASK = CHOOSE eps eps z])',
        '~$call_current_valid(S[.CURRENT = (pcallcontext[.ARGC = 0])])',
        '~$call_current_valid(S[.CVS = eps])',
        '~$call_frames_valid(S, [pframe[.TODO = (ERROR_HANDLER_RESULT perrorcall[.RESUME = ERROR_READ_RESULT perrorread[.RESULT = KNOWN (PINT 7)]]) :: ptask_saved*]])',
        *GUARDS, *FINISH,
     ]),
    ('short-left-skips-right', 'boolean-short-left-and-right',
     'S.TODO = (ERROR_READ_RESULT perrorread) :: ptask_tail* -- if perrorread.NAME = $ptascii("left209")', [
        *NULL_READ,
        'perrorread.ORIGINAL = SHORT_RESULT false expression_right z_left z_right',
        'perrorread.LINE = z_left', 'S.ORIGIN = (porigin)',
        '$origin_node(S.SOURCES, porigin) = (NExprBinaryOpBooleanAnd expression_left expression_right metadata)',
        '$error_variable_source(S, S.ORIGIN, [PCFIELD 0], perrorread.NAME)',
        'z_left = $runtime_line(S, [PCFIELD 0], expression_left)',
        'z_right = $runtime_line(S, [PCFIELD 1], expression_right)',
        '~$error_read_valid(S, perrorread[.ORIGINAL = SHORT_RESULT true expression_right z_left z_right][.TASK = SHORT_RESULT true expression_right z_left z_right])',
        '~$error_read_valid(S, perrorread[.ORIGINAL = SHORT_RESULT false expression_left z_left z_right][.TASK = SHORT_RESULT false expression_left z_left z_right])',
        '$lookup(S.ENV, $ptascii("effect")) = (n_effect)',
        'S.STORE[n_effect] = DEFINED (PINT 0)',
        'PhpStep: S_resume ~> S_chosen',
        'S_chosen.TODO = ptask_tail*', 'S_chosen.RESULT = KNOWN (PBOOL false)',
        'S_chosen.STORE[n_effect] = DEFINED (PINT 0)',
        *GUARDS, *FINISH,
     ]),
    ('short-left-enters-right', 'boolean-short-left-and-right',
     'S.TODO = (ERROR_READ_RESULT perrorread) :: ptask_tail* -- if perrorread.ORIGINAL = SHORT_RESULT true expression_right z_left z_right', [
        *NULL_READ,
        'perrorread.ORIGINAL = SHORT_RESULT true expression_right z_left z_right',
        'perrorread.LINE = z_left', 'S.ORIGIN = (porigin)',
        '$origin_node(S.SOURCES, porigin) = (NExprBinaryOpBooleanOr expression_left expression_right metadata)',
        '$error_variable_source(S, S.ORIGIN, [PCFIELD 0], perrorread.NAME)',
        'z_left = $runtime_line(S, [PCFIELD 0], expression_left)',
        'z_right = $runtime_line(S, [PCFIELD 1], expression_right)',
        '~$error_read_valid(S, perrorread[.ORIGINAL = SHORT_RESULT false expression_right z_left z_right][.TASK = SHORT_RESULT false expression_right z_left z_right])',
        '~$error_read_valid(S, perrorread[.ORIGINAL = SHORT_RESULT true expression_left z_left z_right][.TASK = SHORT_RESULT true expression_left z_left z_right])',
        '$lookup(S.ENV, $ptascii("effect")) = (n_effect)',
        'S.STORE[n_effect] = DEFINED (PINT 0)',
        'PhpStep: S_resume ~> S_chosen',
        'S_chosen.TODO = [$at_task($origin_child(S.ORIGIN, [PCFIELD 1]), EVAL expression_right), TRUTH_RESULT false z_right] ++ ptask_tail*',
        'S_chosen.RESULT = KNOWN PNULL', 'S_chosen.STORE[n_effect] = DEFINED (PINT 0)',
        *GUARDS, *FINISH,
     ]),
    ('ternary-condition-selects-false', 'ternary-condition-original-null',
     'S.TODO = (ERROR_READ_RESULT perrorread) :: ptask_tail*', [
        *NULL_READ,
        'perrorread.ORIGINAL = SELECT_VALUE expression_true expression_false z_cond z_true z_false',
        'perrorread.LINE = z_cond', 'S.ORIGIN = (porigin)',
        '$origin_node(S.SOURCES, porigin) = (NExprTernary expression_cond expression_true expression_false metadata)',
        '$error_variable_source(S, S.ORIGIN, [PCFIELD 0], perrorread.NAME)',
        '~$error_read_valid(S, perrorread[.ORIGINAL = SELECT_VALUE expression_false expression_true z_cond z_true z_false][.TASK = SELECT_VALUE expression_false expression_true z_cond z_true z_false])',
        'PhpStep: S_resume ~> S_chosen',
        'S_chosen.TODO = [$at_task($origin_child(S.ORIGIN, [PCFIELD 2]), EVAL expression_false), VALUE_COPY z_false] ++ ptask_tail*',
        'S_chosen.RESULT = KNOWN PNULL', 'S_chosen.STORE[n_live] = DEFINED (PINT 7)',
        *GUARDS, *FINISH,
     ]),
]
