<?php

// File:    view_by_permalink.php
// License: GNU GPL
// Purpose: Presents a post via permalink passed on the URL.  post is show
// 	along with comments and a form for caputuring additional comments.
//
require_once('settings.php');
$page_title = ':: permalink view';
include_once("$wb_inc_dir/header.php");

$db = DB_connect($site, $user, $pass);
DB_select_db($database, $db);

// parse the passed vars into something useful
// also check for nulls
$the_id = $_GET['the_id'];
$The_id = DB_quote($the_id);



// Session Variables
//
$login    = (isset($_SESSION['login'])) ? $_SESSION['login'] : "";
$www      = (isset($_SESSION['www'])) ? $_SESSION['www'] : "";
$email    = (isset($_SESSION['email'])) ? $_SESSION['email'] : "";


// select post
$result = DB_query("SELECT * FROM wbtbl_posts WHERE id=$The_id
        ORDER BY year, month, day limit $front_page_max", $db);

// output post
echo "<!-- generated by wheatblog: start -->\n\n";


$db2 = new DatabaseClass();

while($row = DB_fetch_array($result)) {
    $the_id     = $row['id'];
    $the_day    = $row['day'];
    $the_month  = $row['month'];
    $the_date   = $row['date'];
    $the_year   = $row['year'];
    $the_locked = $row['locked'];
    $the_cat    = $row['category'];
    $The_cat = DB_quote($the_cat);

    // parse out the category id into its string value
    $result2 = DB_query("SELECT * FROM wbtbl_categories where id=$The_cat", $db);

    while($row2 = DB_fetch_array($result2)) {
        $the_category_name = $row2['category'];
    }

    $the_showpref = $row['showpref'];
    $the_title    = $row['title'];
    $the_body     = $row['body'];

    // Post body
    # removed interpolation
    # inserted markup for better formatting control

    echo '<div class="subcontent">'."\n";
    echo '<div class="post-heading">'."\n"; # heading is important, needs to be seperate
    echo '<h3 class="post-title">'.$the_title.'</h3>'."\n";
    echo '<h4 class="post-date">'.$the_day.', '.$the_month.'.'.$the_date.'.'.$the_year.'</h4>'."\n";
    echo '</div>'."\n";  # closes div.post-heading
    echo '<div class="post-body">'.$the_body.'</div>'."\n\n";

    // Post category
    # removed interpolation

    echo '<div class="post-menu">'."\n".'<ul class="postnav">'."\n"; #links are now unordered list

    echo '<li title="Current Category"><a href="view_by_category.php?the_category='.$the_category.'">'.$the_category_name. '</a></li>'."\n";

    # only difference from  "universal" post display is the ommission of comments

    echo "\n".'</ul>'."\n".'</div>'."\n";  # closes list and div.post-menu
    echo '</div>'."\n\n"; # closes div.indent
}

// ---------------------------
// comments
// ---------------------------

// set vars to null
$comment_month        = '';
$comment_date         = '';
$comment_year         = '';
$comment_title        = '';
$comment_body         = '';
$comment_author_name  = '';
$comment_author_email = '';
$comment_author_url   = '';
$the_post_id          = '';

// select comments for this post
$result3 = DB_query("SELECT * FROM wbtbl_comments where post_id=$The_id
        ORDER BY comment_year, comment_month, comment_date", $db);

// print a comments header
echo '<div class="subcontent"><h3 class="cnt-subhead">Comments</h3></div>';

while($row = DB_fetch_array($result3)) {
    $comment_month        = $row['comment_month'];
    $comment_date         = $row['comment_date'];
    $comment_year         = $row['comment_year'];
    $comment_body         = $row['comment_body'];
    $comment_author_name  = $row['comment_author_name'];
    $comment_author_email = $row['comment_author_email'];
    $comment_author_url   = $row['comment_author_url'];

    // print comments
    echo '<div class="subcontent-comment">'."\n";
    echo '<div class="comment-heading">'."\n"; # heading is important, needs to be seperate
    echo '<h3 class="comment-auth"><strong>'.$comment_author_name.'</strong> said:</h3>'."\n";
    echo '<h4 class="comment-date">'.$the_day.', '.$the_month.'.'.$the_date.'.'.$the_year.'</h4>'."\n";
    echo '</div>'."\n";  # closes div.post-heading
    echo '<div class="comment-body">'.$comment_body.'</div>'."\n\n";
    echo '<div class="comment-menu">'."\n".
         '<ul class="postnav">'."\n".
         '<li title="Email '.$comment_author_email.'"><a href="mailto:'.$comment_author_email.'">email</a></li>'.'|'."\n".
         '<li title="Visit '.$comment_author_name.'\'s Website ('.$comment_author_url.')"><a href="'.$comment_author_url.'">website</a></li>'."\n".
         '</ul>' ."\n".
         '</div>'."\n".
         '</div>'."\n";
}

// provides demarkation between comments / comment form
//
echo('
		<div class="subcontent-heading"></div>
		<!-- generated by wheatblog: stop -->
	');




// A post is either locked, or not locked.  If locked, just tell the user
// and be done with it.  I wonder if we should include exit in footer.php?
//
if ($the_locked) {
    echo '<div class="subcontent"><h3 class="cnt-subhead" id="lock">This post is locked. No ' .
        'comments are allowed.</h3></div>'."\n";

    include('includes/footer.php');
    exit;
}


// New comment dialog header
# JBE - removed interpolation

// new comment form
# JBE - removed interpolation

echo '<div class="subcontent">'."\n";
echo '<div class="comment-heading">'.
     '<h3 class="post-title">Post a Comment</h3>';
echo '<h4 class="comment-date">'."\n".'Date: ' . date("m") . '/' . date("d") . '/' . date("Y") .'</h4></div>'."\n";
echo '<div class="comment-body">';
echo '<form method="post" action="add_comment.php">'."\n".
     '<input name="comment_month" type="hidden" value="'.date("m").'" />'."\n".
     '<input name="comment_date" type="hidden" value="'.date("d").'" />'."\n".
     '<input name="comment_year" type="hidden" value="'.date("Y").'" />'."\n".
     '<input name="the_id" type="hidden" value="'.$the_id.'" />'."\n";

// author
echo 'Name<br />'."\n";
echo '<input name="comment_author_name" ';
echo ($login != '') ? "value=\"$login\" " : '';
echo  'type="text" /><br />'."\n".'Email<br />';

// email
echo '<input name="comment_author_email" ';
echo ($email != '') ? "value=\"$email\" " : '';
echo 'type="text" /><br />'."\n".'WWW<br />';

// www
echo '<input name="comment_author_url" ';
echo ($www != '') ? "value=\"$www\" " : '';
echo 'type="text" /><br />'."\n".'Comment<br />';

// comment and captcha
echo'<textarea name="comment_body" rows="100" cols="50" class="wheatblog_textarea"></textarea><br />'."\n".'<br />'."\n".
    'Please type the number you see in the image below into the box below it.<br />'."\n".
'<img src="captcha.php" /> <br />'."\n".
'<input type="text" name="captcha" /><br />'."\n".
'<input type="submit" value="post comment" /><br />'."\n".
'</form>'."\n".
'</div>'."\n\n";
echo '<div class="comment-menu">&nbsp;</div>';
echo '</div>';

include_once("$wb_inc_dir/footer.php");
