<?php

//
// File:    view_links.php
// License: GNU GPL
// Purpose: Echoes out links as URLs
//
require_once('./settings.php');
$page_title = ':: view links';
include_once("$wb_inc_dir/header.php");


// Connect to the RDBMS and select the database.
$db = DB_connect($site, $user, $pass);
DB_select_db($database, $db);

// select all links in the database
$result = DB_query("select *   
        from wbtbl_links 
        order by link_name", $db);

// output the current links
echo("<!-- generated by wheatblog: start -->\n\n");

echo("\n\n".'<div class="subcontent">'."\n");

# code in progress
# tables actually serve a legit purpose, I swear
# [wheat said]: for tabular data, tables are the best tool

echo '<table id="vb-table" width="100%" cellpadding="0" cellspacing="0">'.
     '<thead>'.
     '<tr id="vb-heading">
		 <td width="50%">Link Name</td>
		 <td width="50%">Link URL</td>
		 </tr>
		 </thead>';
echo '<tbody>'."\n";

// loop through results and echo links
while($row = DB_fetch_array($result)) {
    $the_id = $row["id"];
    $the_link_name = $row["link_name"];
    $the_link_location = $row["link_location"];

    // echo the links
    echo '<tr class="vb-body">';
    echo '<td class="td-title"><span>'.$the_link_name.'</span></td>'."\n";
    echo '<td class="vb-td"><span><a href="'.$the_link_location."\">".$the_link_location.'</a></span></td>'."\n";
    echo '</tr>';
}

echo '</tbody>'."\n".'</table>'."\n".'</div>';


include_once("$wb_inc_dir/footer.php");
