<?php
//
// File:    admin/manage_posts.php
// License: GNU GPL
// Purpose:
//
require('../settings.php');

if (! isAdmin()) {
    HariKari('You are not the admin.');
}

$page_title = 'Managing Posts';
include_once("$wb_inc_dir/header.php");


$qryMonth = (isset($_POST['qryMonth'])) ? $_POST['qryMonth'] : date('n');
$qryYear  = (isset($_POST['qryYear'])) ? $_POST['qryYear'] : date('Y');

$db = DB_connect($site, $user, $pass);
DB_select_db($database, $db);


// select recent posts in the database
//
$result = DB_query("select * from wbtbl_posts
        where month='$qryMonth' and year='$qryYear' 
        order by year DESC, month DESC, date DESC, id DESC", $db);

echo "<!-- generated by wheatblog: start -->\n\n";


// present post query/filter options
?>
	
	<!-- brought this form out of echo -->
	<div class="adminbar" id="manageform">
		<span>Currently viewing all posts from </span> 
		<form name="datelist" action="manage_posts.php" method="post"> 



			<select name="qryMonth">
			<?php
         // Print the month options
         //
         for ($month=1; $month<=12; ++$month) {
             // zero padded representation of the month
             $monthPad = sprintf("%02s", $month);

             // If this page is being displayed as the result of a query
             // (eg- user wants to see 4/2005), use the query data for the
             // default select option.  If no query was made, use the current
             // month and current year as the default select option.
             //
             if (isset($_POST['qryMonth'])) {
                 $frmMonth = $_POST['qryMonth'];
             } else {
                 $frmMonth = date('n');
             }

             // Select the default year to show on the form.
             $select = ($month == $frmMonth) ? 'selected' : '';

             echo "<option value=\"$month\" $select>$monthPad</option>";
         }
?>
			</select>



			<select name="qryYear"> 
			<?php
// Print the year options
//
for ($year=2000; $year<=2010; ++$year) {
    // Please see the comment on frmMonth, above.
    //
    if (isset($_POST['qryYear'])) {
        $frmYear = $_POST['qryYear'];
    } else {
        $frmYear = date('Y');
    }

    // Select the default year to show on the form.
    $select = ($year == $frmYear) ? 'selected' : '';

    echo "<option value=\"$year\" $select>$year</option>";
}
?>
			</select> 



		<a id="datelist" title="Change View" href="javascript:document.datelist.submit();">Change View</a>
        </form> 
        </div>
<?php

    while($row = DB_fetch_array($result)) {
        $the_id       = $row['id'];
        $the_day      = $row['day'];
        $the_month    = $row['month'];
        $the_date     = $row['date'];
        $the_year     = $row['year'];
        $the_category = $row['category'];

        // parse out the category id into its string value
        $result2 = DB_query("select *   
                from wbtbl_categories   
                where id = '$the_category'", $db);

        while($row2 = DB_fetch_array($result2)) {
            $the_category_name = $row2["category"];
        }

        $the_showpref = $row["showpref"];
        if($the_showpref == 1) {
            $the_showpref_as_text = "visible";
        } else {
            $the_showpref_as_text = "hidden";
        }
        $the_title = $row['title'];
        $the_body  = $row['body'];
        $comments  = $row['comments'];


        // Post body
        //
        echo '<div class="subcontent">'."\n";
        echo '<div class="post-heading">'."\n"; # heading is important, needs to be seperate
        echo '<h3 class="post-title">'.$the_title.'</h3>'."\n";
        echo '<h4 class="post-date">'.$the_day.', '.$the_month.'.'.$the_date.'.'.$the_year.'</h4>'."\n";
        echo '</div>'."\n";  # closes div.post-heading
        echo '<div class="post-body">'.$the_body.'</div>'."\n\n";

        // Post category

        echo '<div class="post-menu">'."\n".'<ul class="postnav">'."\n"; #links are now unordered list

        echo '<li class="postid" title="Post ID">Post ID:'.$the_id.'</li>'."\n";
        echo '<li title="Edit this Post"><a href="edit_post.php?id='.$the_id.'">Edit</a></li>'."\n";
        echo '<li title="Delete this Post"><a href="delete_post.php?id='.$the_id.'" onclick="return deleteConfirm();">Delete</a></li>'."\n";
        echo '<li title="Toggle Visibility"><a href="edit_post.php?id='.$the_id.'">'.$the_showpref_as_text.'</a></li>'."\n";
        echo '<li title="Current Category"><a href="view_by_category.php?the_category='.$the_category.'">'.$the_category_name. '</a></li>'."\n";
        echo '<li title="Edit Comments">'.'<a href="edit_post.php?id='.$the_id.'">'.'Edit Comments ('. $comments .')</a></li>'."\n";

        echo "\n".'</ul>'."\n".'</div>'."\n";  # closes list and div.post-menu
        echo '</div>'."\n\n"; # closes div.subcontent


    }

include_once("$wb_inc_dir/footer.php");
?>
