#!/usr/bin/env python3
"""Generate explicit typed constructors from the reviewed pinned node contracts."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT / 'spec/nodes.json').read_text())
nodes = data['nodes']
types = {}

def normalize(desc):
    if 'union' in desc:
        out = []
        for child in desc['union']:
            out.extend(normalize(child))
        return tuple(sorted(set(out), key=repr))
    if 'list' in desc:
        return (('list', normalize(desc['list'])),)
    atom = desc['atom']
    if atom in ('string', 'int', 'float', 'bool', 'null'):
        return ((atom,),)
    matches = tuple(('node', tag) for tag, node in nodes.items() if atom in node['parents'])
    if not matches and atom != 'PhpParser\\Node\\Expr\\Error':
        raise ValueError(f'Unknown type {atom}')
    return matches

def type_name(desc):
    key = normalize(desc)
    if key not in types:
        types[key] = 'phpType' + str(len(types))
        for alt in key:
            if alt[0] == 'list':
                name_for_key(alt[1])
    return types[key]

def name_for_key(key):
    if key not in types:
        types[key] = 'phpType' + str(len(types))
        for alt in key:
            if alt[0] == 'list': name_for_key(alt[1])
    return types[key]

for atom, name in [('PhpParser\\Node\\Stmt', 'statement'), ('PhpParser\\Node\\Expr', 'expression'), ('PhpParser\\Node\\Name', 'name')]:
    types[normalize({'atom': atom})] = name
for tag, node in nodes.items():
    node['constructor'] = 'N' + tag.replace('_', '')
    for field in node['fields']:
        field['domain'] = type_name(field['type'])
metadata = {
    **{k: 'int' for k in ('startLine', 'endLine', 'startFilePos', 'endFilePos', 'startTokenPos', 'endTokenPos', 'kind', 'namespaceBraceLine', 'statementTerminatorLine')},
    **{k: 'text' for k in ('rawValue', 'docLabel', 'docIndentation', 'propertyName')},
    'hasLeadingNewline': 'bool',
    'comments': 'comment*',
}
lines = [';; Generated by scripts/generate-schema.py. Review spec/nodes.json before regeneration.',
         ';; Text payloads are canonical base64 bytes; floating payloads are 16 hex IEEE-754 bits.',
         'syntax ' + ', '.join(types.values()),
         'syntax comment = COMMENT bool text int int int int int int',
         'syntax metadataEntry = ' + ' | '.join('M' + k + ' ' + v for k, v in metadata.items()),
         'syntax metadata = metadataEntry*', '']
for key, name in types.items():
    variants = []
    for alt in key:
        kind = alt[0]
        if kind == 'node':
            node = nodes[alt[1]]
            variants.append(node['constructor'] + ' ' + ' '.join(f['domain'] for f in node['fields']) + ' metadata')
        elif kind == 'list': variants.append('SEQUENCE ' + types[alt[1]] + '*')
        else: variants.append({'string': 'BYTES text', 'int': 'INTEGER int', 'float': 'FLOAT text', 'bool': 'BOOLEAN bool', 'null': 'ABSENT'}[kind])
    lines.append('syntax ' + name + ' =\n  ' + '\n  | '.join(variants))
    lines.append('')
lines.append('syntax program = PROGRAM statement* | ENCODEDPROGRAM text text text text text? statement*')
(ROOT / 'spec/php.watsup').write_text('\n'.join(lines) + '\n')
data['metadata'] = metadata
data['domains'] = {name: key for key, name in types.items()}
(ROOT / 'spec/schema.json').write_text(json.dumps(data, indent=2) + '\n')
print(f'{len(nodes)} constructors; {len(types)} field domains')
