#!/usr/bin/env python3
"""Generate structural checked-node accessors from the reviewed schema."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / 'spec/schema.json'
OUTPUT = ROOT / 'spec/semantics/11-source-occurrences.watsup'


def generate(schema):
    nodes, domains = schema['nodes'], schema['domains']
    keys = {json.dumps(v, sort_keys=True): k for k, v in domains.items()}
    lines = [';; Generated by scripts/generate-occurrences.py from spec/schema.json.',
             ';; Structural order only; this is not PHP compilation or evaluation order.',
             'syntax pcstep = PCFIELD nat | PCINDEX nat',
             'syntax pcpath = pcstep*',
             'syntax pcnode =']
    for i, node in enumerate(nodes.values()):
        fields = ' '.join(f['domain'] for f in node['fields'])
        lines.append(('  ' if i == 0 else '  | ') + node['constructor'] + ' ' + fields + ' metadata')
    lines += ['syntax pcoccurrence = PCOCCURRENCE pcpath pcnode',
              'syntax pcunit = { ID nat, AST program, OCCURRENCES pcoccurrence* }',
              'var pci : nat',
              'dec $pcchildren(pcnode, pcpath) : pcoccurrence*',
              'dec $pcmetadata(pcnode) : metadata',
              'dec $pcwalk(pcoccurrence*) : pcoccurrence*',
              'dec $pcsource(nat, program) : pcunit',
              'dec $pcprogram(program) : statement*']
    declarations, definitions = [], []
    def pattern(node):
        fields = [f"{f['domain']}_{i}" for i, f in enumerate(node['fields'])]
        return node['constructor'] + ' ' + ' '.join(fields) + ' metadata', fields
    for domain, alts in domains.items():
        declarations.append(f'dec $pcfield_{domain}({domain}, pcpath) : pcoccurrence*')
        for alt in alts:
            if alt[0] == 'node':
                pat, _ = pattern(nodes[alt[1]])
                definitions.append(f'def $pcfield_{domain}({pat}, pcpath) = [(PCOCCURRENCE pcpath ({pat}))]')
            elif alt[0] == 'list':
                child = keys[json.dumps(alt[1], sort_keys=True)]
                declarations.append(f'dec $pclist_{domain}({child}*, pcpath, nat) : pcoccurrence*')
                definitions += [f'def $pcfield_{domain}(SEQUENCE {child}*, pcpath) = $pclist_{domain}({child}*, pcpath, 0)',
                    f'def $pclist_{domain}(eps, pcpath, pci) = eps',
                    f'def $pclist_{domain}({child} :: {child}_tail*, pcpath, pci) = $pcfield_{child}({child}, pcpath ++ [(PCINDEX pci)]) ++ $pclist_{domain}({child}_tail*, pcpath, $(pci + 1))']
            else:
                pat = {'string':'BYTES text', 'int':'INTEGER int', 'float':'FLOAT text', 'bool':'BOOLEAN bool', 'null':'ABSENT'}[alt[0]]
                definitions.append(f'def $pcfield_{domain}({pat}, pcpath) = eps')
    for node in nodes.values():
        pat, fields = pattern(node)
        children = ' ++ '.join(f"$pcfield_{f['domain']}({v}, pcpath ++ [(PCFIELD {i})])" for i, (f, v) in enumerate(zip(node['fields'], fields))) or 'eps'
        definitions += [f'def $pcchildren({pat}, pcpath) = {children}',
                        f'def $pcmetadata({pat}) = metadata']
    statement_lists = [name for name, alternatives in domains.items() if alternatives == [['list', domains['statement']]]]
    if len(statement_lists) != 1:
        raise ValueError('expected one statement-list domain')
    statement_list = statement_lists[0]
    lines += declarations + definitions + [
        'def $pcprogram(PROGRAM statement*) = statement*',
        'def $pcprogram(ENCODEDPROGRAM text_1 text_2 text_3 text_4 text? statement*) = statement*',
        'def $pcwalk(eps) = eps',
        'def $pcwalk((PCOCCURRENCE pcpath pcnode) :: pcoccurrence*) = [(PCOCCURRENCE pcpath pcnode)] ++ $pcwalk($pcchildren(pcnode, pcpath)) ++ $pcwalk(pcoccurrence*)',
        f'def $pcsource(pci, program) = {{ ID pci, AST program, OCCURRENCES $pcwalk($pclist_{statement_list}($pcprogram(program), eps, 0)) }}',
    ]
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = generate(json.loads(SCHEMA.read_text()))
    if args.check:
        if OUTPUT.read_text() != generated:
            raise SystemExit('generated occurrence rules differ; run scripts/generate-occurrences.py')
    else:
        OUTPUT.write_text(generated)
