#!/usr/bin/env python3
"""Derive pinned CLI namespace occupancy from configured C registration tables.

This generator never invokes PHP. Native metadata belongs to its separate test.
The local PHP dependency build must already have produced its configuration.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import shlex
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
TARGET = 'spec/semantics/24-builtin-functions.watsup'
MODULES = ['date', 'pcre', 'ctype', 'hash', 'json', 'lexbor', 'mbstring',
           'opcache', 'random', 'reflection', 'standard', 'spl', 'tokenizer', 'uri']
SOURCES = ['Zend/zend_builtin_functions.c', 'ext/date/php_date.c',
           'ext/pcre/php_pcre.c', 'ext/ctype/ctype.c', 'ext/hash/hash.c',
           'ext/json/json.c', 'ext/mbstring/mbstring.c',
           'ext/opcache/zend_accelerator_module.c', 'ext/random/random.c',
           'ext/standard/basic_functions.c', 'ext/spl/php_spl.c',
           'ext/tokenizer/tokenizer.c', 'sapi/cli/php_cli.c']


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def derive(root):
    build = root / '.tools/php-build'
    makefile = build / 'Makefile'
    registration = build / 'main/internal_functions.c'
    actual = re.findall(r'\bphpext_(\w+)_ptr\s*,', registration.read_text())
    if actual != MODULES:
        raise ValueError('configured module registration changed: ' + repr(actual))
    includes = shlex.split(re.search(r'^INCLUDES = (.*)$', makefile.read_text(), re.M)[1])
    # Build recipes use a disposable source copy. Read original imported source.
    includes = [arg.replace(str(root / '.tools/php-src'), str(root / 'vendor/php-src'))
                for arg in includes]
    inputs = {makefile, registration}
    records = []
    for source, module in [('ext/lexbor/php_lexbor.c', 'lexbor'), ('ext/reflection/php_reflection.c', 'Reflection'), ('ext/uri/php_uri.c', 'uri')]:
        path = root / 'vendor/php-src' / source
        text = re.sub(r'/\*.*?\*/', '', path.read_text(), flags=re.S)
        if re.search(r'"' + module + r'"\s*,\s*NULL\s*,', text) is None:
            raise ValueError('formerly empty module function table changed: ' + source)
        inputs.add(path)
    tmp = tempfile.mkdtemp(prefix='builtin-entries-', dir=root / '.tools')
    for source in SOURCES:
        path = root / 'vendor/php-src' / source
        dependencies = Path(tmp) / 'dependencies.d'
        command = ['cc', '-E', '-P', '-MMD', '-MF', str(dependencies),
                   '-DHAVE_CONFIG_H', '-DZEND_SIGNALS',
                   '-I' + str(build / Path(source).parent), '-I' + str(path.parent),
                   *includes, str(path)]
        stem = Path(tmp) / source.replace('/', '_')
        stem.with_suffix('.command.json').write_text(json.dumps(command) + '\n')
        try:
            result = subprocess.run(command, capture_output=True, text=True, timeout=60)
        except subprocess.TimeoutExpired as error:
            stem.with_suffix('.stdout').write_bytes(error.stdout or b'')
            stem.with_suffix('.stderr').write_bytes(error.stderr or b'')
            stem.with_suffix('.status.json').write_text(json.dumps({'status': 'timeout'}) + '\n')
            raise
        stem.with_suffix('.stdout').write_text(result.stdout)
        stem.with_suffix('.stderr').write_text(result.stderr)
        stem.with_suffix('.status.json').write_text(json.dumps({'status': 'completed', 'exit': result.returncode}) + '\n')
        if result.returncode:
            raise RuntimeError(source + ': ' + result.stderr)
        dependencies_text = dependencies.read_text().replace('\\\n', '')
        for name in shlex.split(dependencies_text.split(':', 1)[1]):
            dependency = Path(name).resolve()
            dependency.relative_to(root)
            inputs.add(dependency)
        table = 'additional_functions' if source.startswith('sapi/') else 'ext_functions'
        match = re.search(r'\b' + table + r'\[\]\s*=\s*\{(.*?)\n\};', result.stdout, re.S)
        if match is None:
            raise ValueError('missing registration table: ' + source)
        names = re.findall(r'\{\s*"([^"]+)"\s*,', match[1])
        if not names or any(not re.fullmatch(r'[a-z_][a-z_0-9]*', name) for name in names):
            raise ValueError('unexpected registration entry: ' + source)
        records.append({'source': 'vendor/php-src/' + source, 'table': table,
                        'preprocessed_table_sha256': hashlib.sha256(match[1].encode()).hexdigest(),
                        'names': names})
    names = [name for record in records for name in record['names']]
    if len(names) != len(set(names)):
        raise ValueError('duplicate initial function registration')
    lines = [';; Generated by scripts/generate-builtin-functions.py from configured',
             ';; PHP 8.5.10 CLI function-entry tables. Namespace occupancy only;',
             ';; no library implementation or runtime PHP delegation is implied.',
             'dec $pfunction_builtin(ptbytes) : bool',
             'dec $pfunction_builtin_lower(ptbytes) : bool',
             'def $pfunction_builtin(ptbytes) = $pfunction_builtin_lower($ptlc(ptbytes))']
    for first in sorted({name[0] for name in names}):
        suffixes = sorted(name[1:] for name in names if name[0] == first)
        terms = ['([' + ','.join(str(byte) for byte in suffix.encode()) + '])' for suffix in suffixes]
        lines += ['def $pfunction_builtin_lower(' + str(ord(first)) + ' :: ptbytes) = ptbytes <- [',
                  ',\n'.join('  ' + term for term in terms), ']']
    lines += ['def $pfunction_builtin_lower(ptbytes) = false -- otherwise', '']
    report = {'scope': 'configured CLI initial global function names; source-derived, no PHP execution',
              'modules': actual, 'function_count': len(names), 'tables': records,
              'raw': str(Path(tmp).relative_to(root)),
              'producer_root': str(root),
              'generator': {'path': str(Path(__file__).resolve()), 'sha256': digest(Path(__file__))},
              'preprocessor': {'command': 'cc', 'version': subprocess.run(['cc', '--version'], capture_output=True, text=True, check=True).stdout.splitlines()[0]},
              'inputs': {str(path.relative_to(root)): digest(path) for path in sorted(inputs)}}
    return '\n'.join(lines), report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output, report = derive(ROOT)
    target = ROOT / TARGET
    if args.check:
        if target.read_text() != output:
            parser.exit(1, 'builtin function table differs from configured sources\n')
    else:
        target.write_text(output)
        (ROOT / 'coverage/semantics/builtin-function-sources.json').write_text(
            json.dumps(report, indent=2) + '\n')
    print(str(report['function_count']) + ' source-derived builtin function names')


if __name__ == '__main__':
    main()
