#!/usr/bin/env python3
"""Encode the pinned pow tables as bits without executing floating arithmetic."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'vendor/libm-pow-source/sysdeps/ieee754/dbl-64'


def bits(expression):
    match = re.fullmatch(r'\s*([+-]?)(0x[0-9a-f.]+)p([+-]?\d+)(?:\s*\*\s*(-?\d+|N))?\s*', expression)
    assert match, expression
    sign, mantissa, exponent, factor = match.groups()
    factor = 128 if factor == 'N' else int(factor or '1')
    assert abs(factor) & (abs(factor) - 1) == 0
    sign_bit = (sign == '-') != (factor < 0)
    exponent = int(exponent) + abs(factor).bit_length() - 1
    mantissa = mantissa[2:]
    if '.' in mantissa:
        whole, fraction = mantissa.split('.')
        exponent -= 4 * len(fraction)
        mantissa = whole + fraction
    value = int(mantissa, 16)
    while value and value % 2 == 0:
        value //= 2
        exponent += 1
    if value == 0:
        return int(sign_bit) << 63
    assert value.bit_length() <= 53, expression  # Every imported literal is exact.
    unbiased = exponent + value.bit_length() - 1
    assert -1022 <= unbiased <= 1023, expression
    significand = value << (53 - value.bit_length())
    return ((int(sign_bit) << 63) + ((unbiased + 1023) << 52) + significand - (1 << 52))


def field(source, name):
    return bits(re.search(r'\.' + name + r'\s*=\s*([^,]+),', source).group(1))


def polynomial(source):
    body = re.search(r'\.poly\s*=\s*\{(.*?)\}', source, re.S).group(1)
    return [bits(line.strip().rstrip(',')) for line in body.splitlines()
            if line.strip() and not line.lstrip().startswith(('#', '//'))]


def main():
    log = (SOURCE / 'e_pow_log_data.c').read_text()
    exp = (SOURCE / 'e_exp_data.c').read_text()
    config = (SOURCE / 'math_config.h').read_text()
    assert re.search(r'#define POW_LOG_TABLE_BITS 7\b', config)
    assert re.search(r'#define EXP_TABLE_BITS 7\b', config)
    log_rows = [[bits(value) for value in row.split(',')]
                for row in re.findall(r'^A\(([^\n]+)\)$', log, re.M)]
    exp_body = re.search(r'\.tab\s*=\s*\{(.*?)\}', exp, re.S).group(1)
    exp_values = [int(value, 16) for value in re.findall(r'0x[0-9a-f]+', exp_body)]
    exp_rows = list(zip(exp_values[::2], exp_values[1::2]))
    assert len(log_rows) == len(exp_rows) == 128
    lines = [';; Generated by scripts/generate-libm-data.py from pinned GNU libc data.',
             ';; Copyright (C) 2018-2024 Free Software Foundation, Inc.',
             ';; LGPL-2.1-or-later; see vendor/libm-pow-source/COPYING.LIB and LICENSES.',
             ';; Encoding uses integer operations only; no host float parser or evaluator.', '']
    for name, source in [('ln2hi', log), ('ln2lo', log), ('invln2N', exp),
                         ('negln2hiN', exp), ('negln2loN', exp), ('shift', exp)]:
        lines += [f'dec $pow_{name}() : nat', f'def $pow_{name}() = {field(source, name)}', '']
    for name, coefficients in [('log_coeff', polynomial(log)), ('exp_coeff', polynomial(exp))]:
        assert len(coefficients) == (7 if name == 'log_coeff' else 4)
        lines.append(f'dec $pow_{name}(nat) : nat')
        lines.extend(f'def $pow_{name}({i}) = {value}' for i, value in enumerate(coefficients))
        lines.append('')
    for name, rows in [('log_table', log_rows), ('exp_table', exp_rows)]:
        lines.append(f'dec $pow_{name}(nat) : ({", ".join(["nat"] * len(rows[0]))})')
        lines.extend(f'def $pow_{name}({i}) = ({", ".join(map(str,row))})' for i,row in enumerate(rows))
        lines.append('')
    (ROOT / 'spec/semantics/08-libm-data.watsup').write_text('\n'.join(lines))


if __name__ == '__main__':
    main()
